extends: existence
message: "Do not use periods in all-uppercase abbreviations such as '%s'."
link: 'https://www.ibm.com/developerworks/library/styleguidelines/index.html#N100DC'
level: error
nonword: true
tokens:
  - '\b(?:[A-Z]\.){3,5}'
