extends: existence
message: "Add spaces around the dash in '%s'."
link: 'https://www.ibm.com/developerworks/library/styleguidelines/index.html#N106BF'
ignorecase: true
nonword: true
level: error
action:
  name: edit
  params:
    - remove
    - ' '
tokens:
  - '[^\s][—–][^\s]'
