extends: existence
message: "Avoid the ellipsis (...) except to indicate omitted words."
link: https://www.ibm.com/developerworks/library/styleguidelines/index.html
nonword: true
level: warning
action:
  name: remove
tokens:
  - '\.\.\.'
  - '…'
