extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: 'https://www.ibm.com/developerworks/library/styleguidelines/index.html#N1030C'
level: suggestion
scope: heading
match: $sentence
indicators:
  - ':'
exceptions:
  - IBM
