extends: substitution
message: "Use '%s' instead of '%s'."
link: 'https://www.ibm.com/developerworks/library/styleguidelines/index.html#wordlist'
ignorecase: true
level: error
nonword: true
action:
  name: replace
swap:
  '\b(?:eg|e\.g\.)[\s,]': for example
  '\b(?:ie|i\.e\.)[\s,]': that is
  '\betc\.': and so on
  '\bvs\.': versus
