extends: existence
message: "Use the Oxford comma in '%s'."
link: 'https://www.ibm.com/developerworks/library/styleguidelines/index.html#N106BF'
level: suggestion
tokens:
  - '(?:[^,]+,){1,}\s\w+\sand'
