extends: occurrence
message: "Try to keep sentences less than 25 words."
link: 'https://www.ibm.com/developerworks/library/styleguidelines/index.html#N106FB'
scope: sentence
level: suggestion
max: 25
token: \b(\w+)\b
