// Text snippet included in the following assemblies:
//
// logging/v5_5/logging-5-5-configuration.adoc
// logging/v5_6/logging-5-6-configuration.adoc
// logging/v5_7/logging-5-7-configuration.adoc
// logging/.meta-logging-quickref.adoc
// logging/cluster-logging-support.adoc
//
// Text snippet included in the following modules:
//

:_content-type: SNIPPET

Only the configuration options described in this documentation are supported for the {logging}.

Do not use any other configuration options, as they are unsupported. Configuration paradigms might change across {product-title} releases, and such cases can only be handled gracefully if all configuration possibilities are controlled. If you use configurations other than those described in this documentation, your changes will be overwritten, because Operators are designed to reconcile any differences.

[NOTE]
====
If you must perform configurations not described in the {product-title} documentation, you must set your Red Hat OpenShift Logging Operator to `Unmanaged`. An unmanaged OpenShift Logging environment is not supported and does not receive updates until you return OpenShift Logging to `Managed`.
====
