// Text snippet included in the following assemblies:
//
//
// Text snippet included in the following modules:
//
//
:_content-type: SNIPPET

You can configure your {logging} deployment with Custom Resource (CR) YAML files implemented by each Operator.

*Red Hat Openshift Logging Operator*:

* `ClusterLogging` (CL) - Deploys the collector and forwarder which currently are both implemented by a daemonset running on each node.

* `ClusterLogForwarder` (CLF) - Generates collector configuration to forward logs per user configuration.

*Loki Operator*:

* `LokiStack` - Controls the Loki cluster as log store and the web proxy with OpenShift Container Platform authentication integration to enforce multi-tenancy.

*OpenShift Elasticsearch Operator*:

[NOTE]
====
These CRs are generated and managed by the `ClusterLogging` Operator, manual changes cannot be made without being overwritten by the Operator.
====

* `ElasticSearch` - Configure and deploy an Elasticsearch instance as the default log store.

* `Kibana` - Configure and deploy Kibana instance to search, query and view logs.
