// Text snippet included in the following modules:
//
// * modules/nodes-cluster-resource-configure.adoc
// * modules/nodes-cluster-resource-configure-multi.adoc

:_mod-docs-content-type: SNIPPET

. Change to the `openshift-cluster-resource-override` namespace.
+
[source,terminal]
----
$ oc project openshift-cluster-resource-override
----

* Optional: Create a `ClusterResourceOverride` object that sets the CPU request to a percentage of the CPU request in the pod spec:

.. Create a YAML file similar to the following:
+
[source,yaml]
----
apiVersion: operator.autoscaling.openshift.io/v1
kind: ClusterResourceOverride
metadata:
    name: development
spec:
  podResourceOverride:
    spec:
      cpuRequestOverride:
        type: RequestRelative
        requestRelative:
          percent: 50
      memoryRequestToLimitPercent: 25
      limitCPUToMemoryPercent: 200
----
+
where
+
--
`metadata.name`:: Specifies a name for the CR. Use `cluster` for legacy single-profile mode, or any custom name, such as `production` or `development`, for multi-profile mode.
`spec.podResourceOverride.spec.cpuRequestOverride.type`:: Specifies the strategy for CPU request override: `LimitRelative` (percentage of CPU limit) or `RequestRelative` (percentage of existing CPU request).
`spec.podResourceOverride.spec.cpuRequestOverride.requestRelative.percent`:: When using `RequestRelative` type, specifies the percentage of the existing CPU request to use as the new request.  For example, a value of `50` means the request is reduced to 50% of the original. This parameter is optional.
`spec.podResourceOverride.spec.memoryRequestToLimitPercent`:: Specifies the percentage to override the container memory limit, if used, between 1-100. The default is `50`. This parameter is optional.
`spec.podResourceOverride.spec.limitCPUToMemoryPercent`:: Specifies the percentage to override the container memory limit, if used. Scaling 1 Gi of RAM at 100 percent is equal to 1 CPU core. This is processed before overriding the CPU request, if configured. The default is `200`. This parameter is optional.
--

.. Create the `ClusterResourceOverride` object:
+
[source,terminal]
----
$ oc create -f <file-name>.yaml
----
+
For example:
+
[source,terminal]
----
$ oc create -f cro-cr.yaml
----

. Optional: Create a `ClusterResourceOverride` object sets the CPU request to a percentage of the CPU limit in the pod spec:

.. Create a YAML file similar to the following:
+
[source,yaml]
----
apiVersion: operator.autoscaling.openshift.io/v1
kind: ClusterResourceOverride
metadata:
    name: development
spec:
  podResourceOverride:
    spec:
      cpuRequestOverride:
        type: LimitRelative
        limitRelative:
          percent: 50
      memoryRequestToLimitPercent: 25
      limitCPUToMemoryPercent: 200
----
+
where
+
--
`metadata.name`:: Specifies a name for the CR. Use `cluster` for legacy single-profile mode, or any custom name, such as `production` or `development`, for multi-profile mode.
`spec.podResourceOverride.spec.limitCPUToMemoryPercent`:: Specifies the percentage to override the container memory limit, if used. Scaling 1 Gi of RAM at 100 percent is equal to 1 CPU core. This is processed before overriding the CPU request, if configured. The default is `200`. This parameter is optional.
`spec.podResourceOverride.spec.cpuRequestOverride.type.LimitRelative`:: Specifies the `LimitRelative` strategy for CPU request override, which sets a container’s CPU request to a percentage of its CPU limit.
`spec.podResourceOverride.spec.cpuRequestOverride.limitRelative.percent`:: Specifies the percentage to limit the CPU request. This parameter is optional.
`spec.podResourceOverride.spec.memoryRequestToLimitPercent`:: Specifies the percentage to override the container memory limit, if used, between 1-100. The default is `50`. This parameter is optional.
`spec.podResourceOverride.spec.limitCPUToMemoryPercent`:: Specifies the percentage to override the container memory limit, if used. Scaling 1 Gi of RAM at 100 percent is equal to 1 CPU core. This is processed before overriding the CPU request, if configured. The default is `200`. This parameter is optional.
--

.. Create the `ClusterResourceOverride` object:
+
[source,terminal]
----
$ oc create -f <file-name>.yaml
----
+
For example:
+
[source,terminal]
----
$ oc create -f cro-cr.yaml
----

