apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: ran-du-performance
  namespace: openshift-cluster-node-tuning-operator
  annotations: {}
spec:
  profile:
    - name: ran-du-performance
      # Please note:
      # - The 'include' line must match the associated PerformanceProfile name, following below pattern
      #   include=openshift-node-performance-${PerformanceProfile.metadata.name}
      data: |
        [main]
        summary=Top-level ran-du performance tuning overrides
        include=openshift-node-performance-openshift-node-performance-profile,ran-du-performance-architecture-common
    - name: ran-du-performance-architecture-common
      data: |
        [main]
        summary=Common cross-architecture performance tuning which also includes architecture-specific profiles
        include=ran-du-common-${f:lscpu_check:Architecture\:\s*x86_64:x86:Architecture\:\s*aarch64:aarch64}
        [service]
        service.chronyd=stop,disable
        service.stalld=start,enable
        [bootloader]
        cmdline_ran_rcu=rcupdate.rcu_normal_after_boot=0
        cmdline_ran_efi=efi=runtime
    - name: ran-du-common-aarch64
      data: |
        [main]
        summary=Configuration specific to aarch64 performance
    - name: ran-du-common-x86
      data: |
        [main]
        summary=Configuration specific to x86_64 performance
        [scheduler]
        group.ice-ptp=0:f:10:*:ice-ptp.*
        group.ice-gnss=0:f:10:*:ice-gnss.*
        group.ice-dplls=0:f:10:*:ice-dplls.*
        [bootloader]
        cmdline_x86_blacklist=module_blacklist=irdma,mgag200
        [sysctl]
        kernel.panic_on_unrecovered_nmi=1
  recommend:
    - machineConfigLabels:
        machineconfiguration.openshift.io/role: $mcp
      priority: 18
      profile: ran-du-performance
