include::modules/serverless-document-attributes.adoc[]
[id="installing-openshift-serverless"]
= Installing {ServerlessProductName}
include::modules/common-attributes.adoc[]
:context: installing-openshift-serverless

toc::[]

[NOTE]
====
{ServerlessProductName} is supported for installation in a restricted network environment. For more information, see xref:../../operators/olm-restricted-networks.adoc#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks].
====

== Prerequisites

* To run {ServerlessProductName}, the {product-title} cluster must be sized correctly. The minimum requirement to use {ServerlessProductName} is a cluster with 10 CPUs and 40GB memory.
+
[NOTE]
====
The total size requirements to run {ServerlessProductName} are dependent on the applications deployed. By default, each pod requests ~400m of CPU, so the minimum requirements are based on this value.

In the size requirement provided, an application can scale up to 10 replicas. Lowering the actual CPU request of applications can increase the number of possible replicas.
====

* For more advanced use-cases such as logging, monitoring, or metering on {product-title}, you must deploy more resources. Recommended requirements for such use-cases are 24 CPUs and 96GB of memory.

* You can use the MachineSet API to manually scale your cluster up to the desired size. The minimum requirements usually mean that you must scale up one of the default MachineSets by two additional machines.

[NOTE]
====
The requirements provided relate only to the pool of worker machines of the {product-title} cluster. Master nodes are not used for general scheduling and are omitted from the requirements.
====

.Additional resources
* For more information on using the MachineSet API, see the documentation on xref:../../machine_management/creating_machinesets/creating-machineset-aws.adoc#creating-machineset-aws[Creating MachineSets].
* For more information on scaling a MachineSet manually, see the documentation on xref:../../machine_management/manually-scaling-machineset.adoc#manually-scaling-machineset[manually scaling MachineSets].

[id="installing-serverless-operator"]
== Installing the {ServerlessOperatorName}

The {ServerlessOperatorName} can be installed by a cluster administrator using the Operator Hub in the {product-title} web console.
For details, see the {product-title} documentation on xref:../../operators/olm-adding-operators-to-cluster.adoc#olm-adding-operators-to-a-cluster[adding Operators to a cluster].

.Next steps
* After the {ServerlessOperatorName} is installed, you can install the Knative Serving component. See the documentation on xref:../installing_serverless/installing-knative-serving.adoc#installing-knative-serving[Installing Knative Serving].
// * Once the {ServerlessOperatorName} is installed, you can install the Knative Eventing component. See the documentation on xref:../installing-knative-eventing.adoc#installing-knative-eventing[Installing Knative Eventing].
