:_mod-docs-content-type: ASSEMBLY
[id="compliance-operator-supported-profiles"]
= Supported compliance profiles
include::_attributes/common-attributes.adoc[]
:context: compliance-operator-supported-profiles

toc::[]

There are several profiles available as part of the Compliance Operator (CO)
installation. While you can use the following profiles to assess gaps in a
cluster, usage alone does not infer or guarantee compliance with a particular
profile and is not an auditor.

In order to be compliant or certified under these various standards, you need
to engage an authorized auditor such as a Qualified Security Assessor (QSA),
Joint Authorization Board (JAB), or other industry recognized regulatory
authority to assess your environment. You are required to work with an
authorized auditor to achieve compliance with a standard.


[IMPORTANT]
====
The Compliance Operator might report incorrect results on some managed platforms, such as OpenShift Dedicated and Azure Red Hat OpenShift. For more information, see the link:https://access.redhat.com/solutions/6983418[Red Hat Knowledgebase Solution #6983418].
====

include::modules/compliance-supported-profiles.adoc[leveloffset=+1]

[id="additional-resources-compliance-operator-"]
[role="_additional-resources"]
== Additional resources

* xref:../../../security/compliance_operator/co-concepts/compliance-operator-understanding.adoc#compliance_profile_types_understanding-compliance[Compliance Operator profile types]