[id="configuring-keystone-identity-provider"]
= Configuring a Keystone identity provider
include::modules/common-attributes.adoc[]
:context: configuring-keystone-identity-provider

toc::[]

Configure the `keystone` identity provider to integrate
your {product-title} cluster with Keystone to enable shared authentication with
an OpenStack Keystone v3 server configured to store users in an internal
database. This configuration allows users to log in to {product-title} with
their Keystone credentials.

http://docs.openstack.org/developer/keystone/[Keystone] is an OpenStack project
that provides identity, token, catalog, and policy services.

You can configure the integration with Keystone so that the new {product-title}
users are based on either the Keystone user names or unique Keystone IDs.
With both methods, users log in by entering their Keystone user name and
password. Basing the {product-title} users off of the Keystone ID is more
secure. If you delete a Keystone user and create a new Keystone user with that
user name, the new user might have access to the old user's resources.

include::modules/identity-provider-overview.adoc[leveloffset=+1]

include::modules/identity-provider-secret.adoc[leveloffset=+1]

include::modules/identity-provider-config-map.adoc[leveloffset=+1]

include::modules/identity-provider-keystone-CR.adoc[leveloffset=+1]

// Included here so that it is associated with the above module
.Additional resources

* See xref:../../authentication/understanding-identity-provider.adoc#identity-provider-parameters_understanding-identity-provider[Identity provider parameters] for information on parameters, such as `mappingMethod`, that are common to all identity providers.

include::modules/identity-provider-add.adoc[leveloffset=+1]
