[id="about-mtc-4"]
= About the {mtc-full}
include::modules/common-attributes.adoc[]
:context: about-mtc-4

toc::[]

You can migrate application workloads to {product-title} {product-version} with the {mtc-full} ({mtc-short}). {mtc-short} enables you to control the migration and to minimize application downtime.

The {mtc-short} web console and API, based on Kubernetes custom resources, enable you to migrate stateful and stateless application workloads at the granularity of a namespace.

{mtc-short} supports the file system and snapshot data copy methods for migrating data from the source cluster to the target cluster. You can select a method that is suited for your environment and is supported by your storage provider.

You can use migration hooks to run Ansible playbooks at certain points during the migration. The hooks are added when you create a migration plan.

include::modules/migration-mtc-workflow.adoc[leveloffset=+1]
include::modules/migration-mtc-custom-resources.adoc[leveloffset=+1]
include::modules/migration-understanding-data-copy-methods.adoc[leveloffset=+1]
include::modules/migration-about-migration-hooks.adoc[leveloffset=+1]
