:_mod-docs-content-type: ASSEMBLY
[id="configuring-node-port-service-range"]
= Configuring the node port service range
include::_attributes/common-attributes.adoc[]
:context: configuring-node-port-service-range

toc::[]

During cluster installation, you can configure the node port range to meet the requirements of your cluster. After cluster installation, only a cluster administrator can expand the range as a postinstallation task. If your cluster uses a large number of node ports, consider increasing the available port range according to the requirements of your cluster.

If you do not set a node port range during cluster installation, the default range of `30000-32768` applies to your cluster. In this situation, you can expand the range on either side, but you must preserve `30000-32768` within your new port range.

[IMPORTANT]
====
Red{nbsp}Hat has not performed testing outside the default port range of `30000-32768`. For ranges outside the default port range, ensure that you test to verify the expanding node port range does not impact your cluster. In particular, ensure that there is:

- No overlap with any ports already in use by host processes
- No overlap with any ports already in use by pods that are configured with host networking

If you expanded the range and a port allocation issue occurs, create a new cluster and set the required range for it.

If you expand the node port range and {oc-first} stops working because of a port conflict with the {product-title} API server, you must create a new cluster.
====

// Expanding the node port range
include::modules/nw-nodeport-service-range-edit.adoc[leveloffset=+1]

[role="_additional-resources"]
[id="configuring-node-port-service-range-additional-resources"]
== Additional resources

* xref:../../networking/ingress_load_balancing/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-nodeport.adoc#configuring-ingress-cluster-traffic-nodeport[Configuring ingress cluster traffic using a NodePort]
* xref:../../rest_api/config_apis/network-config-openshift-io-v1.adoc#network-config-openshift-io-v1[Network [config.openshift.io/v1]]
* xref:../../rest_api/network_apis/service-v1.adoc#service-v1[Service [core/v1]]
