// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="networking-apis"]
= Networking APIs
:toc: macro
:toc-title:

toc::[]

== Ingress [networking.k8s.io/v1]

Description::
+
--
Ingress is a collection of rules that allow inbound connections to reach the endpoints defined by a backend. An Ingress can be configured to give services externally-reachable urls, load balance traffic, terminate SSL, offer name based virtual hosting etc.
--

Type::
  `object`

== IngressClass [networking.k8s.io/v1]

Description::
+
--
IngressClass represents the class of the Ingress, referenced by the Ingress Spec. The `ingressclass.kubernetes.io/is-default-class` annotation can be used to indicate that an IngressClass should be considered default. When a single IngressClass resource has this annotation set to true, new Ingress resources without a class specified will be assigned this default class.
--

Type::
  `object`

== NetworkPolicy [networking.k8s.io/v1]

Description::
+
--
NetworkPolicy describes what network traffic is allowed for a set of Pods
--

Type::
  `object`

