:context: dedicated-understanding-aws
[id="welcome-index"]
= Understanding cloud infrastructure access
include::modules/common-attributes.adoc[]

Amazon Web Services (AWS) infrastructure access permits link:https://access.redhat.com/node/3610411[Customer Portal Organization Administrators] and cluster owners to enable AWS Identity and Access Management (IAM) users to
have federated access to the AWS Management Console for their {product-title} (ROSA) cluster.

[id="enabling-aws-access"]
== Enabling AWS access
AWS access can be granted for customer AWS users, and private cluster access can be implemented to suit the needs of your ROSA environment.

Get started with xref:../cloud_infrastructure_access/dedicated-aws-access.adoc#dedicated-aws-access[Accessing AWS infrastructure] for your ROSA cluster. By creating an AWS user and account and providing that user with access to the ROSA AWS account.

After you have access to the ROSA AWS account, use one or more of the following methods to establish a private connection to your cluster:

- xref:../cloud_infrastructure_access/dedicated-aws-peering.adoc#dedicated-aws-peering[Configuring AWS VPC peering]: Enable VPC peering to route network traffic between two private IP addresses.

- xref:../cloud_infrastructure_access/dedicated-aws-vpn.adoc#dedicated-aws-vpn[Configuring AWS VPN]: Establish a Virtual Private Network to securely connect your private network to your Amazon Virtual Private Cloud.

- xref:../cloud_infrastructure_access/dedicated-aws-dc.adoc#dedicated-aws-dc[Configuring AWS Direct Connect]: Configure AWS Direct Connect to establish a dedicated network connection between your private network and an AWS Direct Connect location.

After configuring your cloud infrastructure access, learn more about xref:../cloud_infrastructure_access/rosa-private-cluster.adoc[Configuring a private cluster].
