:_mod-docs-content-type: ASSEMBLY
[id="cloud-experts-getting-started-autoscaling"]
= Tutorial: Autoscaling

include::_attributes/attributes-openshift-dedicated.adoc[]
:context: cloud-experts-getting-started-autoscaling

toc::[]

[role="_abstract"]
The xref:../../rosa_cluster_admin/rosa_nodes/rosa-nodes-about-autoscaling-nodes.adoc#rosa-nodes-about-autoscaling-nodes[cluster autoscaler] adds or removes worker nodes from a cluster based on pod resources.

The cluster autoscaler increases the size of the cluster when:

* Pods fail to schedule on the current nodes due to insufficient resources.
* Another node is necessary to meet deployment needs.

The cluster autoscaler does not increase the cluster resources beyond the limits that you specify. 

The cluster autoscaler decreases the size of the cluster when:

* Some nodes are consistently not needed for a significant period. For example, when a node has low resource use and all of its important pods can fit on other nodes.

include::modules/cloud-experts-getting-started-autoscaling-cli.adoc[leveloffset=+1]
include::modules/cloud-experts-getting-started-autoscaling-ui.adoc[leveloffset=+1]