:_module-type: CONCEPT
//Specify the module-type as either "CONCEPT, PROCEDURE, or REFERENCE"

// Module included in the following assemblies:
//
// * assemblies/remote-health-monitoring.adoc

[id="about-telemtry_{context}"]
= About Telemtry

[role="_abstract"]
Telemetry sends a carefully chosen subset of the cluster monitoring metrics to Red Hat. The Telemeter Client fetches the metrics values every four minutes and thirty seconds and uploads the data to Red Hat. These metrics are described in this document.

This stream of data is used by Red Hat to monitor the clusters in real-time and to react as necessary to problems that impact our customers. It also allows Red Hat to roll out OpenShift Container Platform upgrades to customers to minimize service impact and continuously improve the upgrade experience.

This debugging information is available to Red Hat Support and Engineering teams with the same restrictions as accessing data reported through support cases. All connected cluster information is used by Red Hat to help make OpenShift Dedicated better and more intuitive to use.

== Information collected by Telemtry

The following information is collected by Telemetry:

* The unique random identifier that is generated during an installation
* Version information, including the {product-title} cluster version and installed update details that are used to determine update version availability
* Update information, including the number of updates available per cluster, the channel and image repository used for an update, update progress information, and the number of errors that occur in an update
* The name of the provider platform that {product-title} is deployed on and the data center location
* Sizing information about clusters, machine types, and machines, including the number of CPU cores and the amount of RAM used for each
* The number of etcd members and the number of objects stored in the etcd cluster
* The {product-title} framework components installed in a cluster and their condition and status
* Usage information about components, features, and extensions
* Usage details about Technology Previews and unsupported configurations
* Information about degraded software and nodes marked as `NotReady`
* Events for all namespaces listed as "related objects" for a degraded Operator
* Configuration details that help Red Hat Support to provide beneficial support for customers. This includes node configuration at the cloud infrastructure level, host names, IP addresses, Kubernetes pod names, namespaces, and services.
* Information about the validity of certificates

Telemetry does not collect identifying information such as user names, or passwords. Red Hat does not intend to collect personal information. If Red Hat discovers that personal information has been inadvertently received, Red Hat will delete such information. To the extent that any telemetry data constitutes personal data, please refer to the link:https://www.redhat.com/en/about/privacy-policy[Red Hat Privacy Statement] for more information about Red Hat’s privacy practices.
