:system-module-type: PROCEDURE
// Module included in the following assemblies:
//
// * assemblies/adding-service.adoc

[id="access-service_{context}"]

= Accessing installed services on your cluster

[role="_abstract"]
Once you have successfully installed a service on your cluster, you can then access it through the {product-title} console.


.Prerequisites

* You have successfully installed a service on your {product-title} cluster.


.Procedure

. Navigate to the *Clusters* page in link:https://cloud.redhat.com/openshift/[OpenShift Cluster Manager (OCM)].

. Select the cluster with an installed service you want to access.

. Navigate to the *Add-ons* tab, and locate the installed service you want to access.

. Click *View on console* from the service option to open the {product-title} console.

. Enter your credentials to log in to the {product-title} console.

. Click the *Red Hat Applications* menu by clicking the three-by-three matrix icon in the upper right corner of the main screen.

. Select the service you want to open from the drop-down menu. A new browser tab will open and you will be required to authenticate through Red Hat Single Sign-On.

You have now accessed your service and can begin using it.
