// Module is included in the following assemblies:
//
// * managing_cluster_configuration/managing-openshift-cluster-configuration.adoc

:_mod-docs-content-type: PROCEDURE
[id="access-the-default-argocd-instance_{context}"]
= Access the default Argo CD instance

[role="_abstract"]
After analyzing the default Argo CD instance details, you can access it through the Argo CD UI to check whether it is available for use.

.Prerequisite

* You have your login credentials to access the {OCP} cluster with `cluster-admin` privileges.


.Procedure

. Click the **Application Launcher** menu in the top right corner of the {OCP} web console.
. Select **Cluster Argo CD** from the dropdown list. The Argo CD login page opens.
. Click the **LOG IN VIA OPENSHIFT** button. The {OCP} login page opens.
. Enter your {OCP} credentials. The **Authorize Access** page opens.
. Click **Allow selected permissions** to provide requested permission. The Argo CD UI page opens.

At this point, the UI is empty as you have not created any Argo CD applications. You can check the **User Info** page to view the user details. 

