// Module included in the following assemblies:
//
// * installing/installing_helm/install-helm-quick.adoc
// * installing/installing_helm/install-helm-customization.adoc
:_module-type: PROCEDURE
[id="adding-helm-repository_{context}"]
= Adding the Helm chart repository

.Procedure

* Add {product-title} charts repository.
+
[source,terminal]
----
$ helm repo add rhacs https://mirror.openshift.com/pub/rhacs/charts/
----
+
The Helm repository for {product-title} includes two Helm charts for installing different components.

** Central services Helm chart (`central-services`) for installing the centralized components (Central and Scanner).
+
[NOTE]
====
You deploy centralized components only once and you can monitor multiple separate clusters by using the same installation.
====
** Secured Cluster Services Helm chart (`secured-cluster-services`) for installing the per-cluster (Sensor and Admission controller) and per-node (Collector) components.
+
[NOTE]
====
Deploy the per-cluster components into each cluster that you want to monitor and deploy the per-node components in all nodes that you want to monitor.
====

.Verification

* Run the following command to verify the added chart repository:
+
[source,terminal]
----
$ helm search repo -l rhacs/
----
