// Module included in the following assemblies:
//
// *operating/using-the-administration-events-page.adoc

:_mod-docs-content-type: CONCEPT
[id="administration-events-page-overview_{context}"]
= Administration events page overview

The administration events page organizes information in the following groups:

* *Domain*: Categorizes events by the specific area or domain within {product-title-short} in which the event occurred. This classification helps organize and understand the context of events. 
+
The following domains are included:

** `Authentication`
** `General`
** `Image Scanning`
** `Integrations`

* *Resource type*: Classifies events based on the resource or component type involved. 
+
The following resource types are included:

** `API Token`
** `Cluster`
** `Image`
** `Node`
** `Notifier`

* *Level*: Indicates the severity or importance of an event. 
+
The following levels are included: 

** `Error`
** `Warning`
** `Success` 
** `Info`
** `Unknown`

* *Event last occurred at*: Provides information about the timestamp and date when an event occurred. It helps track the timing of events, which is essential for diagnosing issues and understanding the sequence of actions or incidents.

* *Count*: Indicates the number of times a particular event occurred. This number is useful in assessing the frequency of an issue. An event that has occurred multiple times indicates a persistent issue that you need to fix.

Each event also gives you an indication of what you need to do to fix the error.