// Module included in the following assemblies:
//
// * installing/installing-with-agent-based-installer/preparing-to-install-with-agent-based-installer.adoc

:_mod-docs-content-type: REFERENCE
[id="agent-install-sample-config-bonds-vlans_{context}"]
= Example: Bonds and VLAN interface node network configuration

[role="_abstract"]
See example manifest files to better understand configuration options for deploying your cluster.

The following `agent-config.yaml` file is an example of a manifest for bond and VLAN interfaces:

[source,yaml]
----
  apiVersion: v1alpha1
  kind: AgentConfig
  rendezvousIP: 10.10.10.14
  hosts:
    - hostname: master0
      role: master
      interfaces:
       - name: enp0s4
         macAddress: 00:21:50:90:c0:10
       - name: enp0s5
         macAddress: 00:21:50:90:c0:20
      networkConfig:
        interfaces:
          - name: bond0.300
            type: vlan
            state: up
            vlan:
              base-iface: bond0
              id: 300
            ipv4:
              enabled: true
              address:
                - ip: 10.10.10.14
                  prefix-length: 24
              dhcp: false
          - name: bond0
            type: bond
            state: up
            mac-address: 00:21:50:90:c0:10
            ipv4:
              enabled: false
            ipv6:
              enabled: false
            link-aggregation:
              mode: active-backup
              options:
                miimon: "150"
              port:
               - enp0s4
               - enp0s5
        dns-resolver:
          config:
            server:
              - 10.10.10.11
              - 10.10.10.12
        routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 10.10.10.10
              next-hop-interface: bond0.300
              table-id: 254
----
where:

`networkConfig.interfaces.name`:: Specifies the name of the interface.
+
[NOTE]
====
This value does not need to match the device name.
====
`networkConfig.interfaces.type`:: Specifies the type of interface. Specifying `vlan` creates a VLAN and specifying `bond` creates a bond.
`link-aggregation.mode`:: Specifies the bonding mode.
`link-aggregation.options.mode`:: Specifies the MII link monitoring frequency in milliseconds. This example inspects the bond link every 150 milliseconds.
`dns-resolver`:: Specifies the search and server settings for the DNS server. This configuration is optional.
`routes.config.next-hop-address`:: Specifies the next hop address for the node traffic. This must be in the same subnet as the IP address set for the specified interface.
`routes.config.next-hop-interface`:: Specifies the next hop interface for the node traffic.
