// Module included in the following assemblies:
//
// * ai_applications/mcp_server/mcp-server-overview.adoc

:_mod-docs-content-type: PROCEDURE
[id="ai-app-mcp-server-install-helm_{context}"]
= Install the MCP server Helm chart

[role="_abstract"]
To install the Model Context Protocol (MCP) server for Red Hat {product-title} feature, install the MCP server for Red Hat {product-title} Helm chart.

.Prerequisites

* Access to OpenShift console with admin rights.

.Procedure

. Install the MCP server for Red Hat {product-title} Helm chart by running the following command:
+
[source,terminal]
----
$ helm repo add openshift-helm-charts https://charts.openshift.io/
----
+
[source,terminal]
----
$ helm upgrade -i -n openshift-mcp-server --create-namespace openshift-mcp-server \
    openshift-helm-charts/redhat-openshift-mcp-server \
    --set config.toolsets={core,helm,kubevirt} \
    --set ingress.host=<hostname>
----
+
Where `<hostname>` is a fully qualified domain name (FQDN) that serves as the entry point for the {product-title} MCP server. This host address is used by the Ingress controller to route external traffic to the MCP server service. This should be a URL such as `mcp-server.apps.cluster-name.domain.com`.

.Verification

The command returns output similar to the following:

.Example
[source,terminal]
----
Release "openshift-mcp-server" does not exist. Installing it now.
NAME: openshift-mcp-server
LAST DEPLOYED: Mon Apr 20 09:28:13 2026
NAMESPACE: openshift-mcp-server
STATUS: deployed
REVISION: 1
TEST SUITE: None
----
