// Module included in the following assemblies:
//
// * hardware_accelerators/amd-gpu-operator.adoc

:_content-type: PROCEDURE
[id="amd-installing-gpu-operator_{context}"]
= Installing the AMD GPU Operator

As a cluster administrator, you can install the AMD GPU Operator by using the OpenShift CLI and the web console. Use the following procedure to install the AMD community release of the Operator.

.Prerequisites

* Install the xref:../hardware_enablement/psap-node-feature-discovery-operator.adoc#installing-the-node-feature-discovery-operator_node-feature-discovery-operator[Node Feature Discovery Operator].

* Install the xref:../hardware_enablement/kmm-kernel-module-management.adoc#kmm-install_kernel-module-management-operator[Kernel Module Management Operator].


.Procedure 

. Ensure that there is no previous installation of the Operator:
+
[source,terminal]
----
$ oc get pods -n openshift-amd-gpu
----
+
.Example output
[source,terminal]
----
No resources found in openshift-amd-gpu namespace.
----

. Ensure that the worker nodes are not labeled with 'amd.com/gpu':
+
[source,terminal]
----
$  oc describe node | egrep "Resource.*Requests|amd.com/gpu"
----
+
.Example output
[source,terminal]
----
Resource           Requests      Limits
----

. Log in to the {product-title} web console.

. Install the AMD GPU Operator:

.. In the {product-title} web console, click **Operators → OperatorHub**.

.. Select **AMD GPU Operator**. 

.. In the Show community Operator dialog, click **Continue**.

.. Click **Install**.

.. From the **Installed Namespace** list, select the `openshift-kmm` namespace.

.. Click **Install**.

.. When the Operator is installed, click **View Operator**. 

. Check if the Operator has created the `amd-gpu-operator-controller-manager`:
+
[source,terminal]
----
$ oc get pods -n openshift-amd-gpu
----
+
.Example output
[source,terminal]
----
NAME                                                   READY   STATUS    RESTARTS   AGE
amd-gpu-operator-controller-manager-5c58556d57-6xlwt   2/2     Running   0          80s
----

. Navigate to **Operators → Installed Operators → Details** view for the AMD GPU Operator.

. Click **Create Instance**.

. In the Create DeviceConfig view, click **Create** to build the AMD GPU driver. 

.Verification

. Check if the build is running:
+
[source,terminal]
----
$ oc get pods -n openshift-amd-gpu
----
+
.Example output
[source,terminal]
----
NAME                                                   READY   STATUS    RESTARTS   AGE
amd-gpu-operator-controller-manager-5c58556d57-6xlwt   2/2     Running   0          117s
dc-internal-registry-build-5rltr-build                 1/1     Running   0          37s
----

. Check the AMD drivers build logs:
+
[source,terminal]
----
$ oc logs dc-internal-registry-build-5rltr-build -n openshift-amd-gpu -f
----
+
.Example output
[source,terminal]
----
...
  CC [M]  /amdgpu-drivers-source/amd/amdgpu/si_dma.o
  CC [M]  /amdgpu-drivers-source/amd/amdgpu/dce_v6_0.o
  CC [M]  /amdgpu-drivers-source/amd/amdgpu/uvd_v3_1.o
...
Writing manifest to image destination
Successfully pushed image-registry.openshift-image-registry.svc:5000/openshift-amd-gpu/amd_gpu_kmm_modules@sha256:a66912cb3c22fe561c1ffbc8e2c5bb5b05199353ff2afaf20390a6412d3bfa68
Push successful
----

. Locate the `amd.com/gpu` resources to schedule your AMD-GPU-accelerated pods:
+
[source,terminal]
----
$ oc describe node | egrep "Resource.*Requests|amd.com/gpu" 
----
+
.Example output
[source,terminal]
----
amd.com/gpu:        1
amd.com/gpu:        1
Resource           Requests      Limits
amd.com/gpu        0             0
----
