// Module included in the following assemblies:
//
// * operating/respond-to-violations.adoc

:_mod-docs-content-type: PROCEDURE
[id="analyzing-all-violations_{context}"]
= Analyzing all violations

By viewing the *Violations* page, you can analyze all violations and take corrective action.

.Procedure

. In the {product-title-short} portal, click *Violations*.
. Click one of the following tabs to view violations by category:
** *User Workloads*: Displays violations for user-managed workloads.
** *Platform*: Displays violations for workloads used by {ocp} and layered services.
** *All violations*: Displays violations for user workloads and platform components. It also displays audit log violations for cluster resources.
. Click one of the following tabs to view violations by type:
** *Active*: Displays violations in the build and deploy stages or unresolved runtime violations.
** *Resolved*: Displays the following violations:
*** Violations in the build and deploy stages for workloads that were removed or modified to be compliant
*** Manually resolved runtime violations
*** Violations that were generated before a policy exclusion was added
** *Attempted*: Displays violations for deployment actions that were attempted but blocked by the evaluation of enforced policies. For example, if the admission controller detected that the attempted deployment action, such as a deployment create, update, or scale, would cause a policy violation, it prevented the operation from running in the cluster.
. Optional: Choose a method to reorganize or filter information on the *Violations* page:
** To sort the violations in ascending or descending order, select a column heading.
** To filter violations, use the filter bar.
** To see more details about the violation, select a violation in the *Violations* page.
. Optional: Choose the appropriate method to exclude a deployment from the policy:
** If you selected a single deployment, click the overflow menu {kebab} and then select *Exclude deployment from policy*.
** If you selected multiple deployments, from the *Row actions* drop-down list, select *Exclude deployments from policy*.
//Do we need to add an explanation for "Mark as resolved"?