// Module included in the following assemblies:
//
// * operating/audit-listening-endpoints.adoc

:_mod-docs-content-type: CONCEPT
[id="audit-listening-endpoints-overview_{context}"]
= Listening endpoints overview

[role="_abstract"]
You can view information about processes and the ports that they are listening on by using the {product-title-short} web portal or the API.

You can view information about processes and ports that they are listening on by using the following methods:

* In the {product-title-short} web portal, go to *Network* -> *Listening Endpoints*.
* Connect to the `ListeningEndpointsService` object in the API. For more information on the API, go to *Help* -> *API reference* in the {product-title-short} web portal.

The page provides a list of processes by deployment, with the following information displayed for each process on the list:

* Deployment name
* Cluster
* Namespace
* Count, or the number of processes listening on the ports in the deployment

You can further filter the information displayed on the page by using the filter field and entering individual deployments, namespaces, and clusters.

//"expand icon" is used elsewhere in docs
Click the expand icon at the top of the list to expand all sections for all deployments listed, or click the expand icon on a single deployment line to view additional information about that deployment. The expanded view displays the following information:

* Exec file path: Location of the process
* PID: System ID of the process
* Port: Port on which the process is listening
* Protocol: Protocol in use by the process
* Pod ID: Name of the pod that contains the process
* Container name: Name of the container that runs the listening process

Clicking on a deployment name brings you to the *Risk* page in the {product-title-short} web portal, where you can view information about the deployment, including risk indicators such as policy violations and additional deployment details.
