// Module included in the following assemblies:
//
// * installing/installing-aws-localzone.adoc
// * installing/installing_aws/installing-aws-wavelength.adoc

:_mod-docs-content-type: CONCEPT

[id="aws-edge-zones-installing-intro_{context}"]

You can quickly install an {product-title} cluster in Amazon Web Services (AWS) {aws-service-name-short}
by setting the zone names in the edge compute pool of the `install-config.yaml` file, or install a cluster
in an existing VPC that with {aws-service-name-single} subnets.

ifdef::aws-localzones[]
{aws-service-name-full} are a type of infrastructure that place Cloud Resources close to metropolitan regions.
For more information, see the link:{zone-aws-doc}[{aws-service-name-full} Documentation].
endif::aws-localzones[]
ifdef::aws-wavelength[]

// Review. Source https://aws.amazon.com/wavelength/features/
AWS Wavelength is an infrastructure offering optimized for mobile edge computing applications. Wavelength Zones
are AWS infrastructure deployments that embed AWS compute and storage services within communications service
providers’ (CSP) 5G networks, so application traffic from 5G devices reach application servers running in
Wavelength Zones without leaving the telecommunications network. This avoids the latency that would result from
application traffic traversing multiple hops across the internet to reach its destination, which allows customers
to take full advantage of the latency and bandwidth benefits offered by modern 5G networks.

For more information, see the link:{zone-aws-doc}[{aws-service-name-full} Documentation].

endif::aws-wavelength[]

== Prerequisites

* You reviewed details about the xref:../../architecture/architecture-installation.adoc#architecture-installation[{product-title} installation and update] processes.
* You read the documentation on xref:../../installing/installing-preparing.adoc#installing-preparing[selecting a cluster installation method and preparing it for users].
* You xref:../../installing/installing_aws/installing-aws-account.adoc#installing-aws-account[configured an AWS account] to host the cluster.
+
[IMPORTANT]
====
If you have an AWS profile stored on your computer, it must not use a temporary session token that you generated while using
a multi-factor authentication device. The cluster continues to use your current AWS credentials to create AWS resources for the
entire life of the cluster, so you must use key-based, long-term credentials. To generate appropriate keys, see
link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html[Managing Access Keys for IAM Users]
in the AWS documentation. You can supply the keys when you run the installation program.
====
* You downloaded the AWS CLI and installed it on your computer. See link:https://docs.aws.amazon.com/cli/latest/userguide/install-bundle.html[Install the AWS CLI Using the Bundled Installer (Linux, macOS, or UNIX)]
  in the AWS documentation.
* If you use a firewall, you xref:../../installing/install_config/configuring-firewall.adoc#configuring-firewall[configured it to allow the sites] that your cluster requires access to.
ifdef::aws-localzones[]
* You noted the region and supported link:https://aws.amazon.com/about-aws/global-infrastructure/localzones/locations[AWS Local Zones locations]
  to create the network resources in.
* You read the link:https://aws.amazon.com/about-aws/global-infrastructure/localzones/features/[Features] for each AWS {aws-service-name-full} location.
endif::aws-localzones[]
ifdef::aws-wavelength[]
* You noted the region and supported link:https://aws.amazon.com/wavelength/locations[{aws-service-name-full} locations]
  to create the network resources in.
* You read the link:https://aws.amazon.com/wavelength/features[Features] available on {aws-service-name-full}.
* You read the link:https://docs.aws.amazon.com/wavelength/latest/developerguide/wavelength-quotas.html[Quotas and considerations for Wavelength Zones].
endif::aws-wavelength[]
