// This is included in the following assemblies:
//
// * installing/installing_bare_metal/bare-metal-postinstallation-configuration.adoc

:_mod-docs-content-type: REFERENCE
[id="bmo-about-the-hostupdatepolicy-resource_{context}"]
= About the HostUpdatePolicy resource

[role="_abstract"]
To manage the firmware and BMC settings of your bare-metal hosts without interruption, you can configure the `HostUpdatePolicy` resource. This resource enables live updates for provisioned hosts, which are disabled by default.

== The `HostUpdatePolicy` spec

The `spec` section of the `HostUpdatePolicy` resource provides two settings:

`firmwareSettings`:: This setting corresponds to the `HostFirmwareSettings` resource.

`firmwareUpdates`:: This setting corresponds to the `HostFirmwareComponents` resource.

When you set the value to `onPreparing`, you can only update the host during provisioning, which is the default setting. When you set the value to `onReboot`, you can update a provisioned host by applying the resource and rebooting the bare-metal host. Then, follow the procedure for editing the `HostFirmwareSettings` or `HostFirmwareComponents` resource.

.Example `HostUpdatePolicy` resource
[source,yaml]
----
apiVersion: metal3.io/v1alpha1
kind: HostUpdatePolicy
metadata:
  name: <hostname>
  namespace: openshift-machine-api
spec:
  firmwareSettings: <setting>
  firmwareUpdates: <setting>
----
+
where:
<hostname>:: The name of the bare-metal host.
<setting>:: The update policy setting. Specify `onPreparing` to disable live updates. Specify `onReboot` to enable live updates.