// Module included in the following assemblies:
//
// * machine_management/cluster_api_machine_management/cluster-api-about.adoc

:_mod-docs-content-type: REFERENCE
[id="capi-tech-preview-limitations_{context}"]
= Cluster API limitations

Using the Cluster API to manage machines is a Technology Preview feature and has the following limitations:

* To use this feature, you must enable the `TechPreviewNoUpgrade` feature set.
+
[IMPORTANT]
====
Enabling this feature set cannot be undone and prevents minor version updates.
====

* Only {aws-first}, {gcp-first}, and {vmw-first} clusters can use the Cluster API.

* You must manually create the primary resources that the Cluster API requires.
For more information, see "Getting started with the Cluster API".

* You cannot use the Cluster API to manage control plane machines.

* Migration of existing compute machine sets created by the Machine API to Cluster API compute machine sets is not supported.

* Full feature parity with the Machine API is not available.

* For clusters that use the Cluster API, {oc-first} commands prioritize Cluster API objects over Machine API objects.
This behavior impacts any `oc` command that acts upon any object that is represented in both the Cluster API and the Machine API.
+
For more information and a workaround for this issue, see "Referencing the intended objects when using the CLI" in the troubleshooting content.