// Module included in the following assemblies:
//
// * authentication/managing_cloud_provider_credentials/cco-mode-sts.adoc
// * authentication/managing_cloud_provider_credentials/cco-mode-gcp-workload-identity.adoc
// * installing/installing_ibm_cloud_public/configuring-iam-ibm-cloud.adoc
// * installing/installing_ibm_powervs/preparing-to-install-on-ibm-power-vs.doc
// * installing/installing_alibaba/manually-creating-alibaba-ram.adoc
// * installing/installing_nutanix/preparing-to-install-on-nutanix.adoc
// * updating/preparing_for_updates/preparing-manual-creds-update.adoc

ifeval::["{context}" == "cco-mode-sts"]
:aws-sts:
endif::[]
ifeval::["{context}" == "cco-mode-gcp-workload-identity"]
:google-cloud-platform:
endif::[]
ifeval::["{context}" == "configuring-iam-ibm-cloud"]
:ibm-cloud:
endif::[]
ifeval::["{context}" == "manually-creating-alibaba-ram"]
:alibabacloud:
endif::[]
ifeval::["{context}" == "preparing-to-install-on-nutanix"]
:nutanix:
endif::[]
ifeval::["{context}" == "preparing-manual-creds-update"]
:update:
endif::[]
ifeval::["{context}" == "preparing-to-install-on-ibm-power-vs"]
:ibm-power-vs:
endif::[]

:_content-type: PROCEDURE
[id="cco-ccoctl-configuring_{context}"]
ifndef::update[= Configuring the Cloud Credential Operator utility]
ifdef::update[= Configuring the Cloud Credential Operator utility for a cluster update]

//This applies only to Alibaba Cloud.
ifdef::alibabacloud[]
To assign RAM users and policies that provide long-lived RAM AccessKeys (AKs) for each in-cluster component, extract and prepare the Cloud Credential Operator (CCO) utility (`ccoctl`) binary.
endif::alibabacloud[]

//Nutanix-only intro because it needs context in its install procedure.
ifdef::nutanix[]
The Cloud Credential Operator (CCO) manages cloud provider credentials as Kubernetes custom resource definitions (CRDs). To install a cluster on Nutanix, you must set the CCO to `manual` mode as part of the installation process.
endif::nutanix[]
ifdef::ibm-power-vs[]
The Cloud Credential Operator (CCO) manages cloud provider credentials as Kubernetes custom resource definitions (CRDs). To install a cluster on {ibmpowerProductName} Virtual Server, you must set the CCO to `manual` mode as part of the installation process.
endif::ibm-power-vs[]

//Alibaba Cloud uses ccoctl, but creates different kinds of resources than other clouds, so this applies to everyone else. The upgrade procs also have a different intro, so they are excluded here.
ifndef::alibabacloud,update[]
To create and manage cloud credentials from outside of the cluster when the Cloud Credential Operator (CCO) is operating in manual mode, extract and prepare the CCO utility (`ccoctl`) binary.
endif::alibabacloud,update[]

//Intro for the upgrade procs.
ifdef::update[]
To upgrade a cluster that uses the Cloud Credential Operator (CCO) in manual mode to create and manage cloud credentials from outside of the cluster, extract and prepare the CCO utility (`ccoctl`) binary.
endif::update[]

[NOTE]
====
The `ccoctl` utility is a Linux binary that must run in a Linux environment.
====

.Prerequisites

* You have access to an {product-title} account with cluster administrator access.
* You have installed the OpenShift CLI (`oc`).

//Upgrade prereqs
ifdef::update[]
* Your cluster was configured using the `ccoctl` utility to create and manage cloud credentials from outside of the cluster.
endif::update[]

//AWS permissions needed when running ccoctl during install (I think we can omit from upgrade, since they already have an appropriate AWS account if they are upgrading).
ifdef::aws-sts[]
* You have created an AWS account for the `ccoctl` utility to use with the following permissions:
+
.Required AWS permissions
[cols="a,a"]
|====
|Permission type |Required permissions

|`iam` permissions
|* `iam:CreateOpenIDConnectProvider`
* `iam:CreateRole`
* `iam:DeleteOpenIDConnectProvider`
* `iam:DeleteRole`
* `iam:DeleteRolePolicy`
* `iam:GetOpenIDConnectProvider`
* `iam:GetRole`
* `iam:GetUser`
* `iam:ListOpenIDConnectProviders`
* `iam:ListRolePolicies`
* `iam:ListRoles`
* `iam:PutRolePolicy`
* `iam:TagOpenIDConnectProvider`
* `iam:TagRole`

|`s3` permissions
|* `s3:CreateBucket`
* `s3:DeleteBucket`
* `s3:DeleteObject`
* `s3:GetBucketAcl`
* `s3:GetBucketTagging`
* `s3:GetObject`
* `s3:GetObjectAcl`
* `s3:GetObjectTagging`
* `s3:ListBucket`
* `s3:PutBucketAcl`
* `s3:PutBucketPolicy`
* `s3:PutBucketPublicAccessBlock`
* `s3:PutBucketTagging`
* `s3:PutObject`
* `s3:PutObjectAcl`
* `s3:PutObjectTagging`

|`cloudfront` permissions
|* `cloudfront:ListCloudFrontOriginAccessIdentities`
* `cloudfront:ListDistributions`
* `cloudfront:ListTagsForResource`

|====
+
If you plan to store the OIDC configuration in a private S3 bucket that is accessed by the IAM identity provider through a public CloudFront distribution URL, the AWS account that runs the `ccoctl` utility requires the following additional permissions:
+
--
* `cloudfront:CreateCloudFrontOriginAccessIdentity`
* `cloudfront:CreateDistribution`
* `cloudfront:DeleteCloudFrontOriginAccessIdentity`
* `cloudfront:DeleteDistribution`
* `cloudfront:GetCloudFrontOriginAccessIdentity`
* `cloudfront:GetCloudFrontOriginAccessIdentityConfig`
* `cloudfront:GetDistribution`
* `cloudfront:TagResource`
* `cloudfront:UpdateDistribution`
--
+
[NOTE]
====
These additional permissions support the use of the `--create-private-s3-bucket` option when processing credentials requests with the `ccoctl aws create-all` command.
====
endif::aws-sts[]

.Procedure

. Obtain the {product-title} release image by running the following command:
+
[source,terminal]
----
$ RELEASE_IMAGE=$(./openshift-install version | awk '/release image/ {print $3}')
----

. Obtain the CCO container image from the {product-title} release image by running the following command:
+
[source,terminal]
----
$ CCO_IMAGE=$(oc adm release info --image-for='cloud-credential-operator' $RELEASE_IMAGE -a ~/.pull-secret)
----
+
[NOTE]
====
Ensure that the architecture of the `$RELEASE_IMAGE` matches the architecture of the environment in which you will use the `ccoctl` tool.
====

. Extract the `ccoctl` binary from the CCO container image within the {product-title} release image by running the following command:
+
[source,terminal]
----
$ oc image extract $CCO_IMAGE --file="/usr/bin/ccoctl" -a ~/.pull-secret
----

. Change the permissions to make `ccoctl` executable by running the following command:
+
[source,terminal]
----
$ chmod 775 ccoctl
----

.Verification

* To verify that `ccoctl` is ready to use, display the help file by running the following command:
+
[source,terminal]
----
$ ccoctl --help
----
+
.Output of `ccoctl --help`
[source,terminal]
----
OpenShift credentials provisioning tool

Usage:
  ccoctl [command]

Available Commands:
  alibabacloud Manage credentials objects for alibaba cloud
  aws          Manage credentials objects for AWS cloud
  gcp          Manage credentials objects for Google cloud
  help         Help about any command
  ibmcloud     Manage credentials objects for IBM Cloud
  nutanix      Manage credentials objects for Nutanix

Flags:
  -h, --help   help for ccoctl

Use "ccoctl [command] --help" for more information about a command.
----

ifeval::["{context}" == "cco-mode-sts"]
:!aws-sts:
endif::[]
ifeval::["{context}" == "cco-mode-gcp-workload-identity"]
:!google-cloud-platform:
endif::[]
ifeval::["{context}" == "configuring-iam-ibm-cloud"]
:!ibm-cloud:
endif::[]
ifeval::["{context}" == "manually-creating-alibaba-ram"]
:!alibabacloud:
endif::[]
ifeval::["{context}" == "preparing-to-install-on-nutanix"]
:!nutanix:
endif::[]
ifeval::["{context}" == "preparing-manual-creds-update"]
:!update:
endif::[]
ifeval::["{context}" == "preparing-to-install-on-ibm-power-vs"]
:!ibm-power-vs:
endif::[]
