// Module included in the following assemblies:
//
// * security/cert_manager_operator/cert-manager-creating-certificate.adoc

:_mod-docs-content-type: PROCEDURE
[id="cert-manager-certificate-mgmt_{context}"]
= Creating certificates for user workloads

.Prerequisites

* You have access to the cluster with `cluster-admin` privileges.
* You have installed the {cert-manager-operator}.

.Procedure

. Create an issuer. For more information, see "Configuring an issuer" in the "Additional resources" section.

. Create a certificate:

.. Create a YAML file, for example, `certificate.yaml`, that defines the `Certificate` object:
+
.Example `certificate.yaml` file
+
[source, yaml]
----
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <tls_cert> #<1>
  namespace: <issuer_namespace> #<2>
spec:
  isCA: false
  commonName: '<common_name>' #<3>
  secretName: <secret_name> #<4>
  dnsNames:
  - "<domain_name>" #<5>
  issuerRef:
    name: <issuer_name> #<6>
    kind: Issuer
----
<1> Provide a name for the certificate.
<2> Specify the namespace of the issuer.
<3> Specify the common name (CN).
<4> Specify the name of the secret to create that contains the certificate.
<5> Specify the domain name.
<6> Specify the name of the issuer.

.. Create the `Certificate` object by running the following command:
+
[source, terminal]
----
$ oc create -f certificate.yaml
----

.Verification

* Verify that the certificate is created and ready to use by running the following command:
+ 
[source, terminal]
----
$ oc get certificate -w -n <issuer_namespace>
----
+
Once certificate is in `Ready` status, workloads on your cluster can start using the generated certificate secret.
