// Module included in the following assemblies:
//
// * cloud_experts_osd_tutorials/cloud-experts-osd-limit-egress-ngfw.adoc

:_mod-docs-content-type: PROCEDURE
[id="cloud-experts-osd-limit-egress-ngfw-clean-resource_{context}"]
= Cleaning up resources

To prevent ongoing charges, after you delete your cluster you must manually delete the {GCP} networking infrastructure you created as part of this tutorial. Deleting the cluster will not automatically remove these underlying resources. You can clean up these resources using a combination of gcloud CLI commands and actions within the {GCP} console.

Before you begin the process of cleaning up the the resources you created for this tutorial, run the following commands and complete any prompts.

. To authenticate your identity run the following command:
+
[source,terminal]
----
$ gcloud init
----
+
. To log in to your {GCP} account, run the following command:
+
[source,terminal]
----
$ gcloud auth application-default login
----
+
. To log in to the OpenShift Cluster manager CLI tool, run the following command:
+
[source,terminal]
----
$ ocm login --use-auth-code
----

You are now ready to clean up the resources you created as part of this tutorial. To respect resource dependencies, delete them in the reverse order of their creation.

. Delete the firewall policy's association with the VPC by running the following command:
+
[source,terminal]
----
$ gcloud compute network-firewall-policies associations delete \
    --firewall-policy=${prefix} \
    --network=${prefix}-vpc \
    --global-firewall-policy
----
+
. Delete the global network firewall policy by running the following command:
+
[source,terminal]
----
$ gcloud compute network-firewall-policies delete ${prefix} --global
----
+
. A managed DNS zone in {GCP} cannot be deleted until all user-defined record sets are removed. Define variables to target the specific {GCP} project and the managed DNS zone being cleaned up by running the following command:
+
[source,terminal]
----
$ cat /tmp/delete_records.sh
PROJECT_ID=<your-project-id>
ZONE_NAME=<your-managed-zone-name>
----
+
. List the record sets that are included within the Private DNS zone by running the following command:
+
[source,terminal]
----
$ gcloud \
    dns record-sets list \
    --project=$PROJECT_ID \
    --zone=$ZONE_NAME \
    --filter="type!=NS AND type!=SOA" \
    --format="value(name,type)" | while read name type;
----
+
. Delete the record sets that are included within that Private DNS Zone by running the following command:
+
[source,terminal]
----
$ gcloud --project=$PROJECT_ID dns record-sets delete "$name" --zone=$ZONE_NAME --type="$type"
----
+
. Delete the Private DNS Zone by running the following command:
+
[source,terminal]
----
$ gcloud dns managed-zones delete ${prefix}-googleapis
----
+
. Delete the Cloud NAT gateway:
+
[source,terminal]
----
$ gcloud compute routers nats delete ${prefix}-cloudnat-${region} \
    --router=${prefix}-router \
    --router-region=${region}
----
+
. Delete the Cloud Router by running the following command:
+
[source,terminal]
----
$ gcloud compute routers delete ${prefix}-router --region=${region}
----
+
. Delete the reserved IP address by running the following command:
+
[source,terminal]
+
----
$ gcloud compute addresses delete ${prefix}-${region}-cloudnatip --region=${region}
----
+
. Delete the worker subnet by running the following command:
+
[source,terminal]
+
----
$ gcloud compute networks subnets delete ${prefix}-worker --region=${region}
----
+
. Delete the control plane subnet by running the following command:
+
[source,terminal]
+
----
$ gcloud compute networks subnets delete ${prefix}-control-plane --region=${region}
----
+
. Delete the PSC subnet by running the following command:
+
[source,terminal]
----
$ gcloud compute networks subnets delete ${prefix}-psc --region=${region}
----
+
. Delete the VPC by running the following command:
+
[source,terminal]
----
$ gcloud compute networks delete ${prefix}-vpc
----
