// Module included in the following assemblies:
//
// * cloud_experts_tutorials/cloud-experts-custom-dns-resolver.adoc

:_mod-docs-content-type: PROCEDURE
[id="cloud-experts-custom-dns-resolver-configure-dns-server-classic_{context}"]
= Configure your DNS server

[role="_abstract"]
{product-title} clusters require you to configure DNS server to forward the necessary private hosted zones to your Amazon Route 53 Inbound Resolver:

* `<domain-prefix>.<unique-ID>.p1.openshiftapps.com`

This Amazon Route 53 private hosted zones is created during cluster creation. The `domain-prefix` is a customer-specified value, but the `unique-ID` is randomly generated during cluster creation and cannot be preselected. As such, you must wait for the cluster creation process to begin before configuring forwarding for the `p1.openshiftapps.com` private hosted zone. 

.Procedure
. Create your cluster.
+
. Once your cluster has begun the creation process, locate the newly created private hosted zone:
+
[source,terminal]
----
$ aws route53 list-hosted-zones-by-vpc \
  --vpc-id ${VPC_ID} \
  --vpc-region ${REGION} \
  --query 'HostedZoneSummaries[*].Name' \
  --output table
----
+
.Example output
[source,text]
----
----------------------------------------------
|           ListHostedZonesByVPC             |
+--------------------------------------------+
|  domain-prefix.agls.p3.openshiftapps.com.  |
+--------------------------------------------+
----
+
[NOTE]
====
It may take a few minutes for the cluster creation process to create the private hosted zones in Route 53. If you do not see an `p1.openshiftapps.com` domain, wait a few minutes and run the command again.
====
+
. Once you know the unique ID of the cluster domain, configure your DNS server to forward all DNS requests for `<domain-prefix>.<unique-ID>.p1.openshiftapps.com` to your Amazon Route 53 Inbound Resolver endpoints. For BIND DNS servers, edit your `/etc/named.conf` file in your favorite text editor and add a new zone using the below example: 
+
.Example
[source,terminal]
----
zone "<domain-prefix>.<unique-ID>.p1.openshiftapps.com" {
  type forward;
  forward only;
  forwarders {
    10.0.45.253;
    10.0.23.131;
    10.0.148.159;
  };
};
----
+
--
* Replace `<domain-prefix>` with your cluster domain prefix and `<unique-ID>` with your unique ID collected above.
* Replace with the IP addresses of your inbound resolver endpoints collected above, ensuring that following each IP address there is a `;`.
--