// Module included in the following assemblies:
//
// * cloud_experts_tutorials/cloud-experts-getting-started/cloud-experts-getting-started-openshift-concepts.adoc

:_mod-docs-content-type: CONCEPT
[id="cloud-experts-getting-started-openshift-concepts-routes_{context}"]
= Routes

[role="_abstract"]
An OpenShift route exposes a service at a hostname so that external clients can reach it by name. When a `Route` object is created on OpenShift, it gets picked up by the built-in HAProxy load balancer to expose the requested service and make it externally available with the given configuration.

Similar to the Kubernetes `Ingress` object, Red Hat created the concept of route to fill a need and then contributed the design principles behind it to the community, which heavily influenced the `Ingress` design. A route does have some additional features as can be seen in the following chart:

[cols="1,1,1"]
|===
|Feature | Ingress on OpenShift | Route on OpenShift

|Standard Kubernetes object
| **X**
|

|External access to services
| **X**
| **X**

|Persistent (sticky) sessions
| **X**
| **X**

|Load-balancing strategies (e.g. round robin)
| **X**
| **X**

|Rate-limit and throttling
| **X**
| **X**

|IP whitelisting
| **X**
| **X**

|TLS edge termination for improved security
| **X**
| **X**

|TLS re-encryption for improved security
|
| **X**

|TLS passhtrough for improved security
|
| **X**

|Multiple weighted backends (split traffic)
|
| **X**

|Generated pattern-based hostnames
|
| **X**

|Wildcard domains
|
| **X**
|===

[NOTE]
====
DNS resolution for a hostname is handled separately from routing. Your administrator might have configured a cloud domain that will always correctly resolve to the router or modify your unrelated hostname DNS records independently to resolve to the router.
====

An individual route can override some defaults by providing specific configurations in its annotations.