// Module included in the following assemblies:

// *scalability_and_performance/cluster-compare/creating-a-reference-configuration.adoc

:_mod-docs-content-type: CONCEPT

[id="cluster-compare-metadata-structure_{context}"]
= Structure of the metadata.yaml file

[role="_abstract"]
The `metadata.yaml` file provides a central configuration point to define and configure the templates in a reference configuration. 
The file features a hierarchy of `parts` and `components`. `parts` are groups of `components` and `components` are groups of templates.
Under each component, you can configure template dependencies, validation rules, and add descriptive metadata.

.Example metadata.yaml file
[source,yaml]
----
apiVersion: v2
parts:
  - name: <part_name>
    components:
      - name: <component_name>
        <component_configuration>
  - name: Part2
      - name: Component2
        <component2_configuration>
----

where:

`parts`:: Every `part` typically describes a workload or a set of workloads.
`<part_name>`:: Specifies a `part` name.
`<component_name>`:: Specifies a `component` name.
`<component_configuration>`:: Specifies the configuration for a template. For example, define template relationships or configure what fields to use in a comparison.
