// Module included in the following assemblies:
//
// * configuring/configuring-log-forwarding.adoc

:_mod-docs-content-type: PROCEDURE
[id="cluster-logging-collector-log-forward-loki_{context}"]
= Forwarding logs to an external Loki logging system

To configure log forwarding to Loki, you must create a `ClusterLogForwarder` custom resource (CR) with an output to Loki, and a pipeline that uses the output. The output to Loki can use the HTTP (insecure) or HTTPS (secure HTTP) connection.

.Prerequisites

* You have installed {clo}.
* You have administrator access to {ocp-product-title}.
* You have installed {oc-first}.
* You have a Loki logging system running at the URL specified in the `url` field.

.Procedure

. Create or edit a YAML file that defines the `ClusterLogForwarder` CR object:
+
[source,yaml]
----
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: <log_forwarder_name>
  namespace: <log_forwarder_namespace>
spec:
  serviceAccount: 
    name: <service_account_name> # <1>
  outputs:
  - name: loki-output # <2>
    type: loki # <3>
    loki:
      authentication: # <4>
        username:
          key: username
          secretName: to-loki-secret
        password:
          key: password
          secretName: to-loki-secret
        token:
          from: secret
          secret:
            key: ca-bundle.crt
            name: to-loki-secret
      labelKeys: # <5>
        - <label_keys>
      tenantKey: '{.kubernetes.namespace_name||"application"}' # <6>
      url: https://loki.secure.com:3100 # <7>
  pipelines:
  - name:  my-pipeline
    inputRefs:  # <8>
    - application
    - audit
    outputRefs: # <9>
    - loki-output
----
<1> Specify the name of your service account.
<2> Specify a name for the output.
<3> Specify the type as `loki`.
<4> Specify the authentication information.
<5> Specify which log record keys are mapped to Loki stream labels. If you do not set the `labelKeys` field, the `ClusterLogForwarder` CR uses these default keys: `log_type`, `kubernetes.container_name`, `kubernetes.namespace_name`, `kubernetes.pod_name`.
<6> Specify the tenant for the logs. The value can be a combination of static and dynamic values consisting of field paths separated by `||`. Encase dynamic values inside  single curly brackets `{}`. Follow dynamic values with a static fallback value.
<7> Specify the URL for Loki.
<8> Specify the names of inputs defined in the `input.name` field for this pipeline. You can also use the built-in values `application`, `infrastructure`, `audit`.
<9> Specify the names of outputs defined in the `outputs.name` field for this pipeline.
+
[NOTE]
====
Because Loki requires log streams to be correctly ordered by timestamp, `labelKeys` always includes the `kubernetes_host` label set, even if you do not specify it. This inclusion ensures that each stream originates from a single host, which prevents timestamps from becoming disordered due to clock differences on different hosts.
====

. Apply the `ClusterLogForwarder` CR object by running the following command:
+
[source,terminal]
----
$ oc apply -f <filename>.yaml
----
