// Module included in the following assembly:
//
// * scalability_and_performance/cluster-compare/creating-a-reference-configuration.adoc

:_mod-docs-content-type: PROCEDURE

[id="cluster-compare-configure-capturegroups_{context}"]
= Configuring inline validation with the capturegroups function

[role="_abstract"]
Use the `capturegroups` inline function for more precise validation of fields featuring multi-line strings. This function also ensures that identically named capture groups have the same values across multiple fields.

.Procedure

. Create a `metadata.yaml` file to match your use case. Use the following structure as an example:
+
[source,yaml]
----
apiVersion: v2
parts:
- name: Part1
  components:
  - name: Example
    allOf:
    - path: example.yaml
      config:
        perField:
        - pathToKey: <path_to_key_regex>
          inlineDiffFunc: regex
        - pathToKey: <path_to_key_capturegroups>
          inlineDiffFunc: capturegroups
----
+
where:

`<path_to_key_regex>`:: Specifies the field for inline validation.
`inlineDiffFunc: regex`:: Enables inline validation by using capture groups.
`<path_to_key_capturegroups>`:: Specifies the multi-line field for capture-group validation.
`inlineDiffFunc: capturegroups`:: Enables inline validation by using capture groups.

. Use a regular expression to validate the field in the associated template:
+
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dashboard
data:
  username: "(?<username>[a-z0-9]+)"
  bigTextBlock: |-
    This static content outside of a capture group should match exactly.
    Here is a username capture group: (?<username>[a-z0-9]+).
    It should match this capture group: (?<username>[a-z0-9]+).
----
+
If the username value in the `data.username` field and the value captured in `bigTextBlock` do not match, the `cluster-compare` plugin warns you about the inconsistent matching. The following example shows the output with a warning about the inconsistent matching:
+
[source,terminal]
----
WARNING: Capturegroup (?<username>…) matched multiple values: « mismatchuser | exampleuser »
----
