// Module included in the following assemblies:
// Epic CNF-792 (4.8)
// * scalability_and_performance/cnf-create-performance-profiles.adoc

[id="gathering-data-about-your-cluster-using-must-gather_{context}"]
= Gathering data about your cluster using `must-gather`

The Performance Profile Creator (PPC) tool requires `must-gather` data. As a cluster administrator, run `must-gather` to capture information about your cluster.

.Prerequisites

* Access to the cluster as a user with the `cluster-admin` role.
* Access to the Performance Addon Operator image.
* The OpenShift CLI (`oc`) installed.

.Procedure

. Navigate to the directory where you want to store the `must-gather` data.

. Run `must-gather` on your cluster:
+
[source,terminal]
----
$ oc adm must-gather --image=<PAO_image> --dest-dir=<dir>
----
+
[NOTE]
====
`must-gather` must be run with the `performance-addon-operator-must-gather` image. The output can optionally be compressed. Compressed output is required if you are running the Performance Profile Creator wrapper script.
====

+
.Example
+
[source,terminal]
----
$ oc adm must-gather --image=registry.redhat.io/openshift4/performance-addon-operator-must-gather-rhel8:v4.9 --dest-dir=must-gather
----
. Create a compressed file from the `must-gather` directory:
+
[source,terminal]
----
$ tar cvaf must-gather.tar.gz must-gather/
----
