// CNF-1498 Validate and Document Intel SRO and SRIOV FEC Operator
// Module included in the following assemblies:
//
// *cnf-optimize-data-performance-n3000.adoc

[id="cnf-programming-the-sriov-operator_{context}"]
= Configuring the SR-IOV-FEC Operator for Intel FPGA PAC N3000

This section describes how to program the SR-IOV-FEC Operator for Intel FPGA PAC N3000.
The SR-IOV-FEC Operator handles the management of the forward error correction (FEC) devices that are used to accelerate the FEC process in vRAN L1 applications.

Configuring the SR-IOV-FEC Operator involves:

* Creating the desired virtual functions (VFs) for the FEC device
* Binding the VFs to the appropriate drivers
* Configuring the VF queues for desired functionality in a 4G or 5G deployment

The role of forward error correction (FEC) is to correct transmission errors, where certain bits in a message can be lost or garbled. Messages can be lost or garbled due to noise in the transmission media, interference, or low signal strength.
Without FEC, a garbled message would have to be resent, adding to the network load and impacting throughput and latency.

.Prerequisites

* Intel FPGA PAC N3000 card
* Node or nodes installed with the OpenNESS Operator for Intel FPGA PAC N3000 (Programming)
* Node or nodes installed with the OpenNESS Operator for Wireless FEC Accelerators
* RT kernel configured with Performance Addon Operator

.Procedure

. Change to the `vran-acceleration-operators` project:
+
[source,terminal]
----
$ oc project vran-acceleration-operators
----

. Verify that the SR-IOV-FEC Operator is installed:
+
[source,terminal]
----
$ oc get csv -o custom-columns=Name:.metadata.name,Phase:.status.phase
----
+
.Example output
[source,terminal]
----
Name                                        Phase
sriov-fec.v1.1.0                            Succeeded
n3000.v1.1.0                                Succeeded
----

. Verify that the `N3000` and `sriov-fec` pods are running:
+
[source,terminal]
----
$  oc get pods
----
+
.Example output
[source,terminal]
----
NAME                                            READY       STATUS      RESTARTS    AGE
fpga-driver-daemonset-8xz4c                     1/1         Running     0           15d
fpgainfo-exporter-vhvdq                         1/1         Running     1           15d
N3000-controller-manager-b68475c76-gcc6v        2/2         Running     1           15d
N3000-daemonset-5k55l                           1/1         Running     1           15d
N3000-discovery-blmjl                           1/1         Running     1           15d
N3000-discovery-lblh7                           1/1         Running     1           15d
sriov-device-plugin-j5jlv                       1/1         Running     1           15d
sriov-fec-controller-manager-85b6b8f4d4-gd2qg   1/1         Running     1           15d
sriov-fec-daemonset-kqqs6                       1/1         Running     1           15d
----
The following section provides information on the installed pods:
* `fpga-driver-daemonset` provides and loads the required Open Programmable Accelerator Engine (OPAE) drivers
* `fpgainfo-exporter` provides N3000 telemetry data for Prometheus
* `N3000-controller-manager` applies N3000Node CRs to the cluster and manages all the operand containers
* `N3000-daemonset` is the main worker application
* `N3000-discovery` discovers N3000 Accelerator devices installed and labels worker nodes if devices are present
* `sriov-device-plugin` expose the FEC virtual functions as resources under the node
* `sriov-fec-controller-manager` applies CR to the node and maintains the operands containers
* `sriov-fec-daemonset` is responsible for:
** Discovering the SRIOV NICs on each node.
** Syncing the status of the custom resource (CR) defined in step 6.
** Taking the spec of the CR as input and configuring the discovered NICs.

. Retrieve all the nodes containing one of the supported vRAN FEC accelerator devices:
+
[source,terminal]
----
$ oc get sriovfecnodeconfig
----
+
.Example output
[source,terminal]
----
NAME             CONFIGURED
node1            Succeeded
----

. Find the physical function (PF) of the SR-IOV FEC accelerator device to configure:
+
[source,terminal]
----
$ oc get sriovfecnodeconfig node1 -o yaml
----
+
.Example output
[source,yaml]
----
status:
    conditions:
    - lastTransitionTime: "2021-03-19T17:19:37Z"
      message: Configured successfully
      observedGeneration: 1
      reason: ConfigurationSucceeded
      status: "True"
      type: Configured
    inventory:
        sriovAccelerators:
        - deviceID: 0d5c
          driver: ""
          maxVirtualFunctions: 16
          pciAddress: 0000.1d.00.0 <1>
          vendorID: "8086"
          virtualFunctions: [] <2>
----
<1> This field indicates the PCI Address of the card.
<2> This field shows that the virtual functions are empty.

. Configure the FEC device with the desired setting.

.. Create the following custom resource (CR) and save the YAML in the `sriovfec_n3000_cr.yaml` file:
+
[source,yaml]
----
apiVersion: sriovfec.intel.com/v1
kind: SriovFecClusterConfig
metadata:
    name: config
    namespace: vran-acceleration-operators
    spec:
      nodes:
        - nodeName: node1 <1>
          physicalFunctions:
            - pciAddress: 0000.1d.00.0 <2>
              pfDriver: pci-pf-stub
              vfDriver: vfio-pci
              vfAmount: 2 <3>
              bbDevConfig:
                n3000:
                  # Network Type: either "FPGA_5GNR" or "FPGA_LTE"
                  networkType: "FPGA_5GNR"
                  pfMode: false
                  flrTimeout: 610
                  downlink:
                    bandwidth: 3
                    loadBalance: 128
                    queues: <4>
                      vf0: 16
                      vf1: 16
                      vf2: 0
                      vf3: 0
                      vf4: 0
                      vf5: 0
                      vf6: 0
                      vf7: 0
                  uplink:
                    bandwidth: 3
                    loadBalance: 128
                    queues: <5>
                      vf0: 16
                      vf1: 16
                      vf2: 0
                      vf3: 0
                      vf4: 0
                      vf5: 0
                      vf6: 0
                      vf7: 0
----
<1> Specify the node name.
<2> Specify the PCI Address of the card on which the SR-IOV-FEC Operator will be installed.
<3> Specify the number of virtual functions. Create two virtual functions.
<4> On `vf0` create one queue with 16 buses (downlink and uplink).
<5> On `vf1` create one queue with 16 buses (downlink and uplink).
+
[NOTE]
====
For Intel PAC N3000 for vRAN Acceleration the user can create up to 8 VF devices. Each FEC PF device provides a total of 64 queues to be configured, 32 queues for uplink and 32 queues for downlink. The queues would be typically distributed evenly across the VFs.
====

.. Apply the CR:
+
[source,terminal]
----
$ oc apply -f sriovfec_n3000_cr.yaml
----
+
After applying the CR, the SR-IOV FEC daemon starts configuring the FEC device.

.Verification
. Check the status:
+
[source,terminal]
----
$ oc get sriovfecclusterconfig config -o yaml
----
+
.Example output
[source,yaml]
----
status:
    conditions:
    - lastTransitionTime: "2020-12-15T17:19:37Z"
      message: Configured successfully
      observedGeneration: 1
      reason: ConfigurationSucceeded
      status: "True"
      type: Configured
    inventory:
      sriovAccelerators:
      - deviceID: 0d8f
        driver: pci-pf-stub
        maxVirtualFunctions: 8
        pciAddress: 0000:1d:00.0
        vendorID: "8086"
        virtualFunctions:
        - deviceID: 0d90
          driver: vfio-pci
          pciAddress: 0000:1d:00.1
        - deviceID: 0d90
          driver: vfio-pci
          pciAddress: 0000:1d:00.2
----

. Check the logs:
.. Determine the name of the SR-IOV daemon pod:
+
[source,terminal]
----
$ oc get pod | grep sriov-fec-daemonset
----
+
.Example output

[source,terminal]
----
sriov-fec-daemonset-kqqs6                      1/1     Running   0          19h
----

.. View the logs:
+
[source,terminal]
----
$ oc logs sriov-fec-daemonset-kqqs6
----
+
.Example output
[source,terminal]
----
2020-12-16T12:46:47.720Z        INFO    daemon.NodeConfigurator.applyConfig     configuring PF  {"requestedConfig": {"pciAddress":"0000:1d:00.0","pfDriver":"pci-pf-stub","vfDriver":"vfio-pci","vfAmount":2,"bbDevConfig":{"n3000":{
"networkType":"FPGA_5GNR","pfMode":false,"flrTimeout":610,"downlink":{"bandwidth":3,"loadBalance":128,"queues":{"vf0":16,"vf1":16}},"uplink":{"bandwidth":3,"loadBalance":128,"queues":{"vf0":16,"vf1":16}}}}}}
2020-12-16T12:46:47.720Z        INFO    daemon.NodeConfigurator.loadModule      executing command       {"cmd": "/usr/sbin/chroot /host/ modprobe pci-pf-stub"}
2020-12-16T12:46:47.724Z        INFO    daemon.NodeConfigurator.loadModule      commands output {"output": ""}
2020-12-16T12:46:47.724Z        INFO    daemon.NodeConfigurator.loadModule      executing command       {"cmd": "/usr/sbin/chroot /host/ modprobe vfio-pci"}
2020-12-16T12:46:47.727Z        INFO    daemon.NodeConfigurator.loadModule      commands output {"output": ""}
2020-12-16T12:46:47.727Z        INFO    daemon.NodeConfigurator device's driver_override path   {"path": "/sys/bus/pci/devices/0000:1d:00.0/driver_override"}
2020-12-16T12:46:47.727Z        INFO    daemon.NodeConfigurator driver bind path        {"path": "/sys/bus/pci/drivers/pci-pf-stub/bind"}
2020-12-16T12:46:47.998Z        INFO    daemon.NodeConfigurator device's driver_override path   {"path": "/sys/bus/pci/devices/0000:1d:00.1/driver_override"}
2020-12-16T12:46:47.998Z        INFO    daemon.NodeConfigurator driver bind path        {"path": "/sys/bus/pci/drivers/vfio-pci/bind"}
2020-12-16T12:46:47.998Z        INFO    daemon.NodeConfigurator device's driver_override path   {"path": "/sys/bus/pci/devices/0000:1d:00.2/driver_override"}
2020-12-16T12:46:47.998Z        INFO    daemon.NodeConfigurator driver bind path        {"path": "/sys/bus/pci/drivers/vfio-pci/bind"}
2020-12-16T12:46:47.999Z        INFO    daemon.NodeConfigurator.applyConfig     executing command       {"cmd": "/sriov_workdir/pf_bb_config FPGA_5GNR -c /sriov_artifacts/0000:1d:00.0.ini -p 0000:1d:00.0"}
2020-12-16T12:46:48.017Z        INFO    daemon.NodeConfigurator.applyConfig     commands output {"output": "ERROR: Section (FLR) or name (flr_time_out) is not valid.
FEC FPGA RTL v3.0
UL.DL Weights = 3.3
UL.DL Load Balance = 1
28.128
Queue-PF/VF Mapping Table = READY
Ring Descriptor Size = 256 bytes

--------+-----+-----+-----+-----+-----+-----+-----+-----+-----+
        |  PF | VF0 | VF1 | VF2 | VF3 | VF4 | VF5 | VF6 | VF7 |
--------+-----+-----+-----+-----+-----+-----+-----+-----+-----+
UL-Q'00 |     |  X  |     |     |     |     |     |     |     |
UL-Q'01 |     |  X  |     |     |     |     |     |     |     |
UL-Q'02 |     |  X  |     |     |     |     |     |     |     |
UL-Q'03 |     |  X  |     |     |     |     |     |     |     |
UL-Q'04 |     |  X  |     |     |     |     |     |     |     |
UL-Q'05 |     |  X  |     |     |     |     |     |     |     |
UL-Q'06 |     |  X  |     |     |     |     |     |     |     |
UL-Q'07 |     |  X  |     |     |     |     |     |     |     |
UL-Q'08 |     |  X  |     |     |     |     |     |     |     |
UL-Q'09 |     |  X  |     |     |     |     |     |     |     |
UL-Q'10 |     |  X  |     |     |     |     |     |     |     |
UL-Q'11 |     |  X  |     |     |     |     |     |     |     |
UL-Q'12 |     |  X  |     |     |     |     |     |     |     |
UL-Q'13 |     |  X  |     |     |     |     |     |     |     |
UL-Q'14 |     |  X  |     |     |     |     |     |     |     |
UL-Q'15 |     |  X  |     |     |     |     |     |     |     |
UL-Q'16 |     |     |  X  |     |     |     |     |     |     |
UL-Q'17 |     |     |  X  |     |     |     |     |     |     |
UL-Q'18 |     |     |  X  |     |     |     |     |     |     |
UL-Q'19 |     |     |  X  |     |     |     |     |     |     |
UL-Q'20 |     |     |  X  |     |     |     |     |     |     |
UL-Q'21 |     |     |  X  |     |     |     |     |     |     |
UL-Q'22 |     |     |  X  |     |     |     |     |     |     |
UL-Q'23 |     |     |  X  |     |     |     |     |     |     |
UL-Q'24 |     |     |  X  |     |     |     |     |     |     |
UL-Q'25 |     |     |  X  |     |     |     |     |     |     |
UL-Q'26 |     |     |  X  |     |     |     |     |     |     |
UL-Q'27 |     |     |  X  |     |     |     |     |     |     |
UL-Q'28 |     |     |  X  |     |     |     |     |     |     |
UL-Q'29 |     |     |  X  |     |     |     |     |     |     |
UL-Q'30 |     |     |  X  |     |     |     |     |     |     |
UL-Q'31 |     |     |  X  |     |     |     |     |     |     |
DL-Q'32 |     |  X  |     |     |     |     |     |     |     |
DL-Q'33 |     |  X  |     |     |     |     |     |     |     |
DL-Q'34 |     |  X  |     |     |     |     |     |     |     |
DL-Q'35 |     |  X  |     |     |     |     |     |     |     |
DL-Q'36 |     |  X  |     |     |     |     |     |     |     |
DL-Q'37 |     |  X  |     |     |     |     |     |     |     |
DL-Q'38 |     |  X  |     |     |     |     |     |     |     |
DL-Q'39 |     |  X  |     |     |     |     |     |     |     |
DL-Q'40 |     |  X  |     |     |     |     |     |     |     |
DL-Q'41 |     |  X  |     |     |     |     |     |     |     |
DL-Q'42 |     |  X  |     |     |     |     |     |     |     |
DL-Q'43 |     |  X  |     |     |     |     |     |     |     |
DL-Q'44 |     |  X  |     |     |     |     |     |     |     |
DL-Q'45 |     |  X  |     |     |     |     |     |     |     |
DL-Q'46 |     |  X  |     |     |     |     |     |     |     |
DL-Q'47 |     |  X  |     |     |     |     |     |     |     |
DL-Q'48 |     |     |  X  |     |     |     |     |     |     |
DL-Q'49 |     |     |  X  |     |     |     |     |     |     |
DL-Q'50 |     |     |  X  |     |     |     |     |     |     |
DL-Q'51 |     |     |  X  |     |     |     |     |     |     |
DL-Q'52 |     |     |  X  |     |     |     |     |     |     |
DL-Q'53 |     |     |  X  |     |     |     |     |     |     |
DL-Q'54 |     |     |  X  |     |     |     |     |     |     |
DL-Q'55 |     |     |  X  |     |     |     |     |     |     |
DL-Q'56 |     |     |  X  |     |     |     |     |     |     |
DL-Q'57 |     |     |  X  |     |     |     |     |     |     |
DL-Q'58 |     |     |  X  |     |     |     |     |     |     |
DL-Q'59 |     |     |  X  |     |     |     |     |     |     |
DL-Q'60 |     |     |  X  |     |     |     |     |     |     |
DL-Q'61 |     |     |  X  |     |     |     |     |     |     |
DL-Q'62 |     |     |  X  |     |     |     |     |     |     |
DL-Q'63 |     |     |  X  |     |     |     |     |     |     |
--------+-----+-----+-----+-----+-----+-----+-----+-----+-----+

Mode of operation = VF-mode
FPGA_5GNR PF [0000:1d:00.0] configuration complete!"}
2020-12-16T12:46:48.017Z        INFO    daemon.NodeConfigurator.enableMasterBus executing command       {"cmd": "/usr/sbin/chroot /host/ setpci -v -s 0000:1d:00.0 COMMAND"}
2020-12-16T12:46:48.037Z        INFO    daemon.NodeConfigurator.enableMasterBus commands output {"output": "0000:1d:00.0 @04 = 0102\n"}
2020-12-16T12:46:48.037Z        INFO    daemon.NodeConfigurator.enableMasterBus executing command       {"cmd": "/usr/sbin/chroot /host/ setpci -v -s 0000:1d:00.0 COMMAND=0106"}
2020-12-16T12:46:48.054Z        INFO    daemon.NodeConfigurator.enableMasterBus commands output {"output": "0000:1d:00.0 @04 0106\n"}
2020-12-16T12:46:48.054Z        INFO    daemon.NodeConfigurator.enableMasterBus MasterBus set   {"pci": "0000:1d:00.0", "output": "0000:1d:00.0 @04 0106\n"}
2020-12-16T12:46:48.160Z        INFO    daemon.drainhelper.Run()        worker function - end   {"performUncordon": true}
----

. Check the FEC configuration of the card:
+
[source,terminal]
----
$ oc get sriovfecnodeconfig node1 -o yaml
----
+
.Example output
[source,yaml]
----
status:
    conditions:
    - lastTransitionTime: "2020-12-15T17:19:37Z"
      message: Configured successfully
      observedGeneration: 1
      reason: ConfigurationSucceeded
      status: "True"
      type: Configured
    inventory:
      sriovAccelerators:
      - deviceID: 0d8f <1>
        driver: pci-pf-stub
        maxVirtualFunctions: 8
        pciAddress: 0000:1d:00.0
        vendorID: "8086"
      virtualFunctions:
      - deviceID: 0d90 <2>
        driver: vfio-pci
        pciAddress: 0000:1d:00.1
      - deviceID: 0d90
        driver: vfio-pci
        pciAddress: 0000:1d:00.2
----
<1> `0d8f` is the `deviceID` physical function of the FEC device.
<2> `0d90` is the `deviceID` virtual function of the FEC device.
