// Module included in the following assemblies:
// Epic CNF-792 (4.8)
// * scalability_and_performance/cnf-create-performance-profiles.adoc

[id="running-the-performance-profile-profile-cluster-using-podman_{context}"]
= Running the Performance Profile Creator using `podman`

As a cluster administrator, you can run `podman` and Performance Profile Creator to create a performance profile.

.Prerequisites

* Access to the cluster as a user with the `cluster-admin` role.
* A cluster installed on bare metal hardware.
* A node with `podman` and OpenShift CLI (`oc`) installed.


.Procedure

. Check the machine config pool:

+
[source,terminal]
----
$ oc get mcp
----
.Example output
+
[source,terminal]
----
NAME         CONFIG                                                 UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master       rendered-master-acd1358917e9f98cbdb599aea622d78b       True      False      False      3              3                   3                     0                      22h
worker-cnf   rendered-worker-cnf-1d871ac76e1951d32b2fe92369879826   False     True       False      2              1                   1                     0                      22h
----

. Optional: Display help for the PPC tool:
+
[source,terminal]
----
$ podman run --entrypoint performance-profile-creator quay.io/openshift-kni/performance-addon-operator:4.8-snapshot -h
----
+
.Example output
+
[source,terminal]
----
A tool that automates creation of Performance Profiles

Usage:
  performance-profile-creator [flags]

Flags:
      --disable-ht                        Disable Hyperthreading
  -h, --help                              help for performance-profile-creator
      --info string                       Show cluster information; requires --must-gather-dir-path, ignore the other arguments. [Valid values: log, json] (default "log")
      --mcp-name string                   MCP name corresponding to the target machines (required)
      --must-gather-dir-path string       Must gather directory path (default "must-gather")
      --power-consumption-mode string     The power consumption mode.  [Valid values: default, low-latency, ultra-low-latency] (default "default")
      --profile-name string               Name of the performance profile to be created (default "performance")
      --reserved-cpu-count int            Number of reserved CPUs (required)
      --rt-kernel                         Enable Real Time Kernel (required)
      --split-reserved-cpus-across-numa   Split the Reserved CPUs across NUMA nodes
      --topology-manager-policy string    Kubelet Topology Manager Policy of the performance profile to be created. [Valid values: single-numa-node, best-effort, restricted] (default "restricted")
      --user-level-networking             Run with User level Networking(DPDK) enabled
----

. Run the performance profile creator tool in discovery mode:
+
[NOTE]
====
Discovery mode inspects your cluster using the output from `must-gather`. The output produced includes information on the:

* NUMA cell partitioning with the allocated CPU ids
* Whether hyperthreading is enabled

Using this information you can set appropriate values for some of the arguments supplied to the performance profile creator tool.
====
+
[source,terminal]
----
$ podman run --entrypoint performance-profile-creator -v /must-gather:/must-gather:z quay.io/openshift-kni/performance-addon-operator:4.8-snapshot --info log --must-gather-dir-path /must-gather
----
+
[NOTE]
====
This command uses the performance profile creator as a new entry point to `podman`. It maps the `must-gather` data for the host into the container image and invokes the required user-supplied profile arguments to produce the `my-performance-profile.yaml` file.

The `-v` option can be the path to either:

* The `must-gather` output directory
* An existing directory containing the `must-gather` decompressed tarball

The `info` option requires a value which specifies the output format. Possible values are log and JSON. The JSON format is reserved for debugging.
====
+
. Run `podman`:
+
[source,terminal]
----
$ podman run --entrypoint performance-profile-creator -v /must-gather:/must-gather:z quay.io/openshift-kni/performance-addon-operator:4.8-snapshot --mcp-name=worker-cnf --reserved-cpu-count=20 --rt-kernel=true --split-reserved-cpus-across-numa=false --topology-manager-policy=single-numa-node --must-gather-dir-path /must-gather  --power-consumption-mode=ultra-low-latency > my-performance-profile.yaml
----
+
The following arguments are required:

* `reserved-cpu-count`
* `mcp-name`
+
The `mcp-name` argument in this example is set to `worker-cnf` based on the output of the command `oc get mcp`.
* `rt-kernel`
+
[NOTE]
====
For Single Node OpenShift (SNO) use `--mcp-name=master`.
====

+
. Review the created YAML file:
+
[source,terminal]
----
$ cat my-performance-profile.yaml
----
.Example output
+
[source,terminal]
----
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: performance
spec:
  additionalKernelArgs:
  - nmi_watchdog=0
  - audit=0
  - mce=off
  - processor.max_cstate=1
  - intel_idle.max_cstate=0
  - idle=poll
  cpu:
    isolated: 1,3,5,7,9,11,13,15,17,19-39,41,43,45,47,49,51,53,55,57,59-79
    reserved: 0,2,4,6,8,10,12,14,16,18,40,42,44,46,48,50,52,54,56,58
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  numa:
    topologyPolicy: single-numa-node
  realTimeKernel:
    enabled: true
----

. Apply the generated profile:

+
[source,terminal]
----
$ oc apply -f my-performance-profile.yaml
----

.How to run `podman` to create a Performance profile
The following example illustrates how to run `podman` to create a performance profile with 20 reserved CPUs that are to be split across the NUMA nodes.

Node hardware configuration:

* 80 CPUs
* Hyperthreading enabled
* Two NUMA nodes
* Even numbered CPUs run on NUMA node 0 and odd numbered CPUs run on NUMA node 1

Run `podman` to create the performance profile:

[source,terminal]
----
$ podman run --entrypoint performance-profile-creator -v /must-gather:/must-gather:z quay.io/openshift-kni/performance-addon-operator:4.8-snapshot --mcp-name=worker-cnf --reserved-cpu-count=20 --rt-kernel=true --split-reserved-cpus-across-numa=true --must-gather-dir-path /must-gather > my-performance-profile.yaml
----

The created profile is described in the following YAML:

[source,yaml]
----
  apiVersion: performance.openshift.io/v2
  kind: PerformanceProfile
  metadata:
    name: performance
  spec:
    cpu:
      isolated: 10-39,50-79
      reserved: 0-9,40-49
    nodeSelector:
      node-role.kubernetes.io/worker-cnf: ""
    numa:
      topologyPolicy: restricted
    realTimeKernel:
      enabled: true
----

[NOTE]
====
In this case, 10 CPUs are reserved on NUMA node 0 and 10 are reserved on NUMA node 1.
====
