// Module included in the following assemblies:
//
// *scalability_and_performance/cnf-numa-aware-scheduling.adoc

:_mod-docs-content-type: PROCEDURE
[id="cnf-disabling-rte-image-validation_{context}"]
= Disabling RTE image validation

[role="_abstract"]
You can disable RTE image validation by setting the `EXPORTER_IMAGE_RESTRICTION` environment variable to `false`.

[WARNING]
====
Disabling RTE image validation creates a security risk. A malicious RTE image can:

* Access sensitive hardware topology information on worker nodes
* Observe node resource allocation and NUMA zone configurations
* Read detailed system information that could facilitate other attacks
* Execute code with the RTE daemon set service account permissions
====

.Prerequisites

* You have installed the OpenShift CLI (`oc`).
* You have logged in as a user with `cluster-admin` privileges.
* You have installed the NUMA Resources Operator.

.Procedure

. Disable validation by patching the NUMA Resources Operator subscription by running the following command:
+
[source,terminal]
----
$ oc patch subscription numaresources-operator \
  -n openshift-numaresources \
  --type=merge \
  -p '{"spec":{"config":{"env":[{"name":"EXPORTER_IMAGE_RESTRICTION","value":"false"}]}}}'
----

. Wait for the NUMA Resources Operator pod to restart by monitoring the pod status with the following command:
+
[source,terminal]
----
$ oc get pods -n openshift-numaresources -w
----

. Verify that validation is disabled by checking the NUMA Resources Operator pod environment by running the following command:
+
[source,terminal]
----
$ oc exec -n openshift-numaresources deploy/numaresources-controller-manager -- \
  printenv EXPORTER_IMAGE_RESTRICTION
----
+
An example of the expected output is provided below:
+
[source,terminal]
----
false
----
