// Module included in the following assemblies:
//
// *scalability_and_performance/cnf-numa-aware-scheduling.adoc

:_mod-docs-content-type: PROCEDURE

[id="cnf-configuring-nrop-on-schedulable-cp-nodes_{context}"]
= Configuring NUMA Resources Operator on schedulable control plane nodes


[role="_abstract"]
This procedure describes how to configure the NUMA Resources Operator (NROP) to manage control plane nodes that a user configures to be schedulable. This is particularly useful in compact clusters where control plane nodes also serve as worker nodes, or in multi-node OpenShift (MNO) clusters where control plane nodes are configured as schedulable to run workloads.

When you configure control plane nodes to be schedulable, you can optionally configure the NUMA Resources Operator to manage them. To do this, define separate `nodeGroups` for the control plane and worker nodes in the NUMAResourcesOperator custom resource (CR)

This configuration allows the NUMA Resources Operator to schedule pods on both control plane and worker nodes, taking into consideration resource availability and NUMA topology. The NUMA Resources Operator treats Control plane nodes like any other schedulable node on the cluster, and they can be included in the `nodeGroups` for Topology-Aware Scheduling (TAS).

.Prerequisites

* Install the {oc-first}.
* Log in as a user with `cluster-admin` privileges.
* Install the NUMA Resources Operator.

.Procedure

. To enable Topology Aware Scheduling (TAS) on control plane nodes, configure the nodes to be schedulable first. This allows the NUMA Resources Operator to deploy and manage pods on them. Without this action, the operator cannot deploy the pods required to gather NUMA topology information from these nodes. Follow these steps to make the control plane nodes schedulable:

.. Edit the `schedulers.config.openshift.io` resource by running the following command:
+
[source,terminal]
----
$ oc edit schedulers.config.openshift.io cluster
----

.. In the editor, set the `mastersSchedulable` field to `true`, then save and exit the editor.
+
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  creationTimestamp: "2019-09-10T03:04:05Z"
  generation: 1
  name: cluster
  resourceVersion: "433"
  selfLink: /apis/config.openshift.io/v1/schedulers/cluster
  uid: a636d30a-d377-11e9-88d4-0a60097bee62
spec:
  mastersSchedulable: true
status: {}
#...
----

. Configure the NUMA Resources Operator, you must create a single `NUMAResourcesOperator` CR on the cluster. The `nodeGroups` configuration in this CR tells the Operator which nodes to manage.
+
[NOTE]
====
You can specify multiple non-overlapping node sets for the NUMA Resources Operator to manage. Each of these sets should correspond to a different machine config pool (MCP). The NUMA Resources Operator then manages the schedulable control plane nodes within these specified node groups.
====

.. For a compact cluster, the compact cluster's master nodes are also the schedulable nodes, so specify only the master pool. Create the following `nodeGroups` configuration in the `NUMAResourcesOperator` CR:
+
[source,yaml]
----
apiVersion: nodetopology.openshift.io/v1
kind: NUMAResourcesOperator
metadata:
  name: numaresourcesoperator
spec:
  nodeGroups:
    - poolName: master
----
+
[NOTE]
====
Configuring a compact cluster with a worker pool in addition to the `master` pool should be avoided. While this setup does not break the cluster or affect operator functionality, it can lead to redundant or duplicate pods and create unnecessary noise in the system. The worker pool is essentially a pointless, empty MCP in this context and serves no purpose.
====

.. For an MNO cluster where both control plane and worker nodes are schedulable, you have the option to configure the NUMA Resources Operator to manage multiple `nodeGroups`. You can specify which nodes to include by adding their corresponding MCPs to the `nodeGroups` list in the `NUMAResourcesOperator` CR. The configuration depends entirely on your specific requirements. For example, to manage both the `master` and `worker-cnf` pools, create the following `nodeGroups` configuration in the NUMAResourcesOperator CR:
+
[source,yaml]
----
apiVersion: nodetopology.openshift.io/v1
kind: NUMAResourcesOperator
metadata:
  name: numaresourcesoperator
spec:
  nodeGroups:
    - poolName: master
    - poolName: worker-cnf 
----
+
[NOTE]
====
You can customize this list including any combination of `nodeGroups` you want to manage with Topology-Aware Scheduling. To prevent issues with duplicate, pending pods, you must ensure that each `poolName` in your configuration corresponds to an MachineConfigPool (MCP) with a unique node selector label. This label should be applied only to the nodes within that specific pool and not overlap with labels on any other nodes in the cluster. The `worker-cnf` MCP  designates a set of nodes that run telecommunications workloads
====

.. After you update the `nodeGroups` field in the `NUMAResourcesOperator` CR to reflect your cluster's configuration, apply the changes by running the following command:
+
[source,terminal]
----
$ oc apply -f <filename>.yaml
----
+
[NOTE]
====
Replace `<filename>.yaml` with the name of your configuration file.
====

.Verification

After applying the configuration, verify that the NUMA Resources Operator is correctly managing the schedulable control plane nodes by performing the following checks:

. Confirm that the control plane nodes have the worker role and are schedulable by running the following command:
+
[source,terminal]
----
$ oc get nodes
----
+
.Example output:

[source,terminal]
----
NAME                                        STATUS   ROLES                         AGE   VERSION
master-0                                    Ready    control-plane,master,worker   67m   v1.32.8
worker-0                                    Ready    worker                        60m   v1.32.8
worker-1                                    Ready    worker                        60m   v1.32.8
master-1                                    Ready    control-plane,master,worker   64m   v1.32.8
master-2                                    Ready    control-plane,master,worker   64m   v1.32.8
worker-2                                    Ready    worker                        60m   v1.32.8
----

. Check the schedulability status by running the following command: 
+
[source,terminal]
----
$ oc get node <master_node_name> -o jsonpath='{.spec.unschedulable}'
----
+
[NOTE]
====
The output should be `false` or blank, confirming the node is schedulable.
====

. Verify that the NUMA Resources Operator's pods are running on the control plane nodes by running the following command:
+
[source,terminal]
----
$ oc get pods -n openshift-numa-resources -o wide
----

. Confirm that the NUMA Resources Operator has collected and reported the NUMA topology data for all nodes, including the masters, by running the following command:
+
[source,terminal]
----
$ oc get noderesourcetopologies.topology.node.k8s.io
----
+
The presence of a `NodeResourceTopology` resource for a node confirms that the NUMA Resources Operator was able to schedule a pod on it to collect the data.
+
.Example output:
[source,terminal]
----
NAME                AGE
master-0            23m
worker-0            23m
worker-1            23m
master-1            23m
master-2            23m
worker-2            23m
----

. Inspect a single Node Resource Topology by running the following command:
+
[source,terminal]
----
$ oc get noderesourcetopologies <master_node_name> -o yaml
----
+
.Example output:
[source,yaml]
----
apiVersion: topology.node.k8s.io/v1alpha2
attributes:
- name: nodeTopologyPodsFingerprint
  value: pfp0v001ef46db3751d8e999
- name: nodeTopologyPodsFingerprintMethod
  value: with-exclusive-resources
- name: topologyManagerScope
  value: container
- name: topologyManagerPolicy
  value: best-effort
kind: NodeResourceTopology
metadata:
  annotations:
    k8stopoawareschedwg/rte-update: periodic
    topology.node.k8s.io/fingerprint: pfp0v001ef46db3751d8e999
  creationTimestamp: "2025-09-11T12:37:24Z"
  generation: 1
  name: ip-10-0-16-35.us-west-1.compute.internal
  resourceVersion: "37796"
  uid: 1eedf537-be6f-47ac-b598-43d6187ce3fc
zones:
- costs:
  - name: node-0
    value: 10
  name: node-0
  resources:
  - allocatable: "3"
    available: "2"
    capacity: "4"
    name: cpu
  - allocatable: 1476189952
    available: 1378189952
    capacity: 1576189952
    name: memory
  type: Node
----
+
The presence of this resource for a node with a master role proves that the NUMA Resources Operator was able to deploy its discovery pods onto that node. These pods are what gather the NUMA topology data, and they can only be scheduled on nodes that are considered schedulable.
+
The output confirms that the procedure to make the master nodes schedulable was successful, as the NUMA Resources Operator has now collected and reported the NUMA-related information for that specific control plane node. 