// Module included in the following assemblies:
//
// * scalability_and_performance/low_latency_tuning/cnf-provisioning-low-latency-workloads.adoc

:_mod-docs-content-type: PROCEDURE
[id="cnf-node-tuning-operator-creating-pod-with-guaranteed-qos-class_{context}"]
= Creating a pod with a guaranteed QoS class

[role="_abstract"]
You can create a pod with a quality of service (QoS) class of `Guaranteed` for high-performance workloads. Configuring a pod with a QoS class of `Guaranteed` ensures that the pod has priority access to the specified CPU and memory resources.

To create a pod with a QoS class of `Guaranteed`, you must apply the following specifications:

* Set identical values for the memory limit and memory request fields for each container in the pod.
* Set identical values for CPU limit and CPU request fields for each container in the pod.

In general, a pod with a QoS class of `Guaranteed` will not be evicted from a node. One exception is during resource contention caused by system daemons exceeding reserved resources. In this scenario, the `kubelet` might evict pods to preserve node stability, starting with the lowest priority pods.

.Prerequisites

* Access to the cluster as a user with the `cluster-admin` role

* The OpenShift CLI (`oc`)

.Procedure

. Create a namespace for the pod by running the following command:
+
[source,terminal]
----
$ oc create namespace qos-example
----
+
This example uses the `qos-example` namespace.
+
The output resembles the following example:
+
[source,terminal]
----
namespace/qos-example created
----

. Create the `Pod` resource:

.. Create a YAML file that defines the `Pod` resource:
+
--
Create a `qos-example.yaml` file as in the following example:

[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
  namespace: qos-example
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: qos-demo-ctr
    image: quay.io/openshifttest/hello-openshift:openshift
    resources:
      limits:
        memory: "200Mi"
        cpu: "1"
      requests:
        memory: "200Mi"
        cpu: "1"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
----

* `image` specifies a public `hello-openshift` image.
* `limits.memory` sets the memory limit to 200 MB.
* `limits.cpu` sets the CPU limit to 1 CPU.
* `requests.memory` sets the memory request to 200 MB.
* `requests.cpu` sets the CPU request to 1 CPU.
+
[NOTE]
====
If you specify a memory limit for a container, but do not specify a memory request, {product-title} automatically assigns a memory request that matches the limit. Similarly, if you specify a CPU limit for a container, but do not specify a CPU request, {product-title} automatically assigns a CPU request that matches the limit.
====
--

.. Create the `Pod` resource by running the following command:
+
[source,terminal]
----
$ oc apply -f qos-example.yaml --namespace=qos-example
----
+
The output resembles the following example:
+
[source,terminal]
----
pod/qos-demo created
----

.Verification

* View the `qosClass` value for the pod by running the following command:
+
[source,terminal]
----
$ oc get pod qos-demo --namespace=qos-example --output=yaml | grep qosClass
----
+
The output resembles the following example:
+
[source,yaml]
----
    qosClass: Guaranteed
----

