// Module included in the following assemblies:
//
// * cnv/cnv_virtual_machines/cnv-accessing-vm-consoles.adoc

[id="cnv-vm-console-web_{context}"]
= Virtual machine console sessions

You can connect to the VNC and serial consoles of a running virtual machine from
the *Consoles* tab in the *Virtual Machine Details* screen of the web console.

There are two consoles available: the graphical *VNC Console* and the
*Serial Console*. The *VNC Console* opens by default whenever you navigate to
the *Consoles* tab. You can switch between the consoles using the
*VNC Console* *Serial Console* list.

Console sessions remain active in the background unless they are disconnected.
When the *Disconnect before switching* checkbox is active and you switch
consoles, the current console session is disconnected and a new session with the
selected console connects to the virtual machine. This ensures only one console
session is open at a time.

.Options for the *VNC Console*
The *Send Key* button lists key combinations to send to the virtual machine.

.Options for the *Serial Console*
Use the *Disconnect* button to manually disconnect the *Serial Console* session from the virtual machine. +
Use the *Reconnect* button to manually open a *Serial Console* session to the virtual machine.
