// Module included in the following assemblies:
//
// * cnv/cnv_virtual_machines/cnv_cloning_vms/cnv-cloning-vm-disk-into-new-datavolume.adoc
// * cnv/cnv_virtual_machines/cnv_cloning_vms/cnv-cloning-vm-disk-into-new-datavolume-block.adoc

// `blockstorage` conditionals are used (declared in the "*-block" assembly) to separate content 

[id="cnv-cloning-pvc-of-vm-disk-into-new-datavolume_{context}"]
= Cloning the PersistentVolumeClaim of a virtual machine disk into a new DataVolume

You can clone a PersistentVolumeClaim (PVC) of an existing virtual machine disk
into a new DataVolume. The new DataVolume can then be used for a new virtual
machine.

[NOTE]
====
When a DataVolume is created independently of a virtual machine, the lifecycle
of the DataVolume is independent of the virtual machine. If the virtual machine
is deleted, neither the DataVolume nor its associated PVC is deleted.
====

.Prerequisites

* Determine the PVC of an existing virtual machine disk to use. You must power
down the virtual machine that is associated with the PVC before you can clone it.
* Install the OpenShift Command-line Interface (CLI), commonly known as `oc`.
ifdef::blockstorage[]
* At least one available block PersistentVolume (PV) that is the same size as or larger than the source PVC.
endif::[]

.Procedure

. Examine the virtual machine disk you want to clone to identify the name and
namespace of the associated PVC.

. Create a YAML file for a DataVolume object that specifies the name of the
new DataVolume, the name and namespace of the source PVC, 
ifdef::blockstorage[]
`volumeMode: Block` so that an available block PV is used,
endif::[]
and the size of the new DataVolume.
+
For example:
+
[source,yaml]
----
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: <cloner-datavolume> <1>
spec:
  source:
    pvc:
      namespace: "<source-namespace>" <2>
      name: "<my-favorite-vm-disk>" <3>
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: <2Gi> <4>
ifdef::blockstorage[]
    volumeMode: Block <5>
endif::[]
----
<1> The name of the new DataVolume.
<2> The namespace where the source PVC exists.
<3> The name of the source PVC.
<4> The size of the new DataVolume. You must allocate enough space, or the
cloning operation fails. The size must be the same as or larger than the source PVC.
ifdef::blockstorage[]
<5> Specifies that the destination is a block PV
endif::[]

. Start cloning the PVC by creating the DataVolume:
+
----
$ oc create -f <cloner-datavolume>.yaml
----
+
[NOTE]
====
DataVolumes prevent a virtual machine from starting before the PVC is prepared,
so you can create a virtual machine that references the new DataVolume while the
PVC clones.
====
