// Module included in the following assemblies:
//
// * cnv_users_guide/cnv_users_guide.adoc

[[importvmdisk-pvc]]
= Importing a virtual machine disk to a PVC

The process of importing a virtual machine disk is handled by the CDI
controller. When a PVC is created with special
`cdi.kubevirt.io/storage.import` annotations, the controller creates a
short-lived import pod that attaches to the PV and downloads the virtual
disk image into the PV.

You cannot import images from insecure registries using the Containerized Data
Importer, even if you mark a registry as insecure with the
`openshift_docker_insecure_registries` attribute in your {product-title}
inventory file.

[CAUTION]
====
When you import a disk image into a PersistentVolumeClaim, the disk image is
expanded to use the full storage capacity that is requested in the PVC. To use
this space, the disk partitions and file system(s) in the virtual machine
might need to be expanded.

The resizing procedure varies based on the operating system installed on the VM.
Refer to the operating system documentation for details.
====

.Prerequisites

* The virtual machine disk can be RAW or QCOW2 format and can be compressed
using *xz* or *gzip*.
* The disk image must be available at either an *HTTP* or *S3*
endpoint.

[NOTE]
====
For locally provisioned storage, the PV needs to be created
before the PVC. This is not required for OpenShift Container Storage,
for which the PVs are created dynamically.
====

.Procedure

. Identify an *HTTP* or *S3* file server hosting the virtual disk
image that you want to import. You need the complete URL, in
either format:
+
* *_http://www.example.com/path/to/data_*
* *_s3://bucketName/fileName_*
+
Use this URL as the `cdi.kubevirt.io/storage.import.endpoint`
annotation value in your PVC configuration file.
+
For example: `cdi.kubevirt.io/storage.import.endpoint:
https://download.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2`


. If the file server requires authentication credentials, edit the
*_endpoint-secret.yaml_* file:
+
----
apiVersion: v1
kind: Secret
metadata:
  name: endpoint-secret
  labels:
    app: containerized-data-importer
type: Opaque
data:
  accessKeyId: ""  # <optional: your key or user name, base64 encoded>
  secretKey:    "" # <optional: your secret or password, base64 encoded>
----
+
.. Save the value of `metadata.name` to use with the
`cdi.kubevirt.io/storage.import.secret` annotation in your PVC
configuration file.
+
For example: `cdi.kubevirt.io/storage.import.secret:
endpoint-secret`

. Apply *_endpoint-secret.yaml_* to the cluster:
+
----
$ oc apply -f endpoint-secret.yaml
----

. Edit the PVC configuration file, making sure to include the required
annotations.
+
For example:
+
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "example-vmdisk-volume"
  labels:
   app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://download.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2" <1>
    cdi.kubevirt.io/storage.import.secret: "endpoint-secret" <2>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
----
<1> Endpoint annotation for the import image URL
<2> Endpoint annotation for the authorization secret

. Create the PVC using the `oc` CLI:
+
----
$ oc create -f <pvc.yaml> <1>
----
<1> The PersistentVolumeClaim file name.
+
After the disk image is successfully imported into the PV, the
import pod expires, and you can bind the PVC to a virtual machine object
within {product-title}.

Next, xref:cnv_creating_vm.adoc#createvm[create a virtual machine] object to
bind to the PVC.

