// Module included in the following assemblies:
//
// * configure/configure-the-collector.adoc

:_mod-docs-content-type: CONCEPT
[id="collector-input-receivers_{context}"]
= About input receivers

[role="_abstract"]
The Red Hat OpenShift Logging Operator deploys a service for each configured input receiver so that clients can write to the collector. This service exposes the port specified for the input receiver. For log forwarder `ClusterLogForwarder` CR deployments, the service name is in the `<clusterlogforwarder_resource_name>-<input_name>` format.

[IMPORTANT]
====
Receiver inputs are only supported when logs originate from a Red{nbsp}Hat-supported product that is installed on the same cluster as the Red Hat OpenShift Logging Operator, or when logging is installed on {hcp}.
====

The collector supports two types of receiver inputs:

HTTP receiver::
Receives and parses audit logs. Use this receiver when:
+
* Logging is installed on {hcp}.
* Logs originate from a Red{nbsp}Hat-supported product that is installed on the same cluster as the Red Hat OpenShift Logging Operator. For example, {VirtProductName}.

Syslog receiver::
Receives and parses infrastructure logs in journal format. Use this receiver when:
+
* Logs originate from a Red{nbsp}Hat-supported product that is installed on the same cluster as the Red Hat OpenShift Logging Operator. For example:
** Red Hat OpenStack Services on OpenShift (RHOSO)
** {VirtProductName}
