// Module included in the following assemblies:
//
// * operating/examine-images-for-vulnerabilities.adoc

:_mod-docs-content-type: REFERENCE
[id="common-scanner-warning-messages_{context}"]
= Understanding and addressing common Scanner warning messages

[role="_abstract"]
When scanning images with {rh-rhacs-first}, you might see the `CVE DATA MAY BE INACCURATE` warning message.
Scanner displays this message when it cannot retrieve complete information about the operating system or other packages in the image.

The following table shows some common Scanner warning messages:

.Warning messages
[%autowidth]
|===
| *Message* | *Description*

|`Unable to retrieve the OS CVE data, only Language CVE data is available`
|Indicates that Scanner does not officially support the base operating system of the image; therefore, it cannot retrieve CVE data for the operating system-level packages.

|`Stale OS CVE data`
|Indicates that the base operating system of the image has reached end-of-life, which means the vendor no longer updates the vulnerability data. For example, Debian 8 and 9.

For more information about the files needed to identify the components in the images, see "Examining images for vulnerabilities".


|`Failed to get the base OS information`
|Indicates that Scanner scanned the image, but could not find the base operating system used for the image.

|`Failed to retrieve metadata from the registry`
|Indicates that the target registry is unreachable on the network. The cause could be a firewall blocking `docker.io`, or an authentication issue preventing access.

To analyze the root cause, create a special registry integration for private registries or repositories to get the pod logs for {product-title-short} Central. For instructions on how to do this, see "Integrating with image registries".

|`Image out of scope for Red{nbsp}Hat Vulnerability Scanner Certification`
a|Indicates that Scanner scanned the image, but the image is old and does not fall within the scope of Red{nbsp}Hat Scanner Certification. For more information, see the "Partner Guide for Red{nbsp}Hat Vulnerability Scanner Certification".

IMPORTANT: If you are using a Red{nbsp}Hat container image, consider using a base image newer than June 2020.

|===
