// Module included in the following assemblies:
//
// * security/compliance_operator/co-scans/compliance-scans.adoc

:_mod-docs-content-type: CONCEPT
[id="compliance-scansetting-cr_{context}"]
= `ScanSetting` Custom Resource

[role="_abstract"]
You can configure the scan limits attribute of the `ScanSetting` custom resource to override the default CPU and memory limits of scanner pods to meet your environment's resource requirements.

The Compliance Operator uses defaults of 500Mi memory and 100m CPU for the scanner container, and 200Mi memory and 100m CPU for the `api-resource-collector` container. To set the memory limits of the Operator, modify the `Subscription` object if installed through OLM or the Operator deployment itself.

[IMPORTANT]
====
Increasing the memory limit for the Compliance Operator or the scanner pods is needed if the default limits are not sufficient and the Operator or scanner pods are ended by the Out Of Memory (OOM) process. For more information, see Increasing Compliance Operator resource limits.
====
