// Module included in the following assemblies:
//
// *introduction/introduction.adoc

:_mod-docs-content-type: CONCEPT
[id="rhcl-platform-eng-workflow_{context}"]
= Platform provider workflow

[role="_abstract"]
You can use {prodname} to set up ingress `Gateway` objects on {ocp} clusters in specific regions. You can configure all policies identically on all `Gateway` objects for consistency.

For example, configure DNS policies to ensure that customers in Brazil are routed to the South American data center and so on. You can also configure TLS, authentication and authorization, and rate-limiting policies to ensure that gateway security, performance, and monitoring all conform to your standards.

Connect gateways and load balance::
You must start by creating at least one `Gateway` object. If `Gateway` objects exist, you can move on to configuring access policies for those `Gateway` objects.

You can connect `Gateway` objects by creating a DNS policy and configuring a global load balancing strategy. DNS records are reconciled with your cloud DNS provider automatically, whether in a single-cluster or multicluster environment. You can use the following tools:

* Automatic DNS configuration
* Mutiple DNS providers
* DNS-based load balancing, such as round-robin, weighted, and geo-based
* Single or multicluster ready

Secure Gateways::
After you create your `Gateway` objects, secure them. You can secure `Gateway` objects by using a TLS policy that automatically generates certificate requests for the host names specified in your gateway. You can also set up application security defaults and overrides by using authentication and authorization policies and rate-limiting policies. You can use the following tools:

* TLS: Automatic certificate requests and ACME providers
* Auth policies
* Rate-limiting: Global rate-limiting, external IDPs, default and overrides

Observe Gateways::
After you create and secure your `Gateway` objects, you can configure your observability stack. Observe your connectivity and runtime metrics by using dashboards and alerts. For example, configure metrics for policy compliance and governance, resource consumption, error rates, request latency and throughput.
