:_mod-docs-content-type: CONCEPT
[id="customizing-permissions-by-creating-user-defined-cluster-roles-for-cluster-scoped-instances_{context}"]
= Customize permissions with user-defined cluster roles

[role="_abstract"]
Customize cluster-scoped Argo CD instance permissions by disabling default cluster roles and creating user-defined cluster roles and role bindings for control plane components.

For the default cluster-scoped instance, the {gitops-title} Operator grants additional permissions for managing certain cluster-scoped resources. The Operator creates cluster roles and cluster role bindings for the {gitops-shortname} control plane components to operate at the cluster level.

If you do not want the cluster-scoped instance to have all of the Operator-given permissions and choose to add or remove permissions to cluster-wide resources, you must first disable the creation of the default cluster roles for the cluster-scoped instance. Then, you can customize permissions for the following cluster-scoped instances:

* Default Argo CD instance (default cluster-scoped instance)
* User-defined cluster-scoped Argo CD instance

This guide provides instructions with examples to help you create a user-defined cluster-scoped Argo CD instance and deploy an Argo CD application in your defined namespace that contains custom configurations for your cluster. Disable the creation of the default cluster roles for the cluster-scoped instance and customize permissions for user-defined cluster-scoped instances by creating new cluster roles and cluster role bindings for the {gitops-shortname} control plane components.

[NOTE]
====
As a developer, if you are creating an Argo CD application and deploying cluster-wide resources, ensure that your cluster administrator grants the necessary permissions.
====

Otherwise, after the Argo CD reconciliation, you will see an authentication error message in the application's `Status` field similar to the following example:

--
*Example authentication error message:*
[source,terminal]
----
persistentvolumes is forbidden: User "system:serviceaccount:gitops-demo:argocd-argocd-application-controller" cannot create resource "persistentvolumes" in API group "" at the cluster scope.
----
--

