// Module included in the following assemblies:
//
// * networking/networking_overview/about-managed-networking.adoc

:_mod-docs-content-type: CONCEPT
[id="con_about-managed-networking_{context}"]
= About networking for managed clusters

[role="_abstract"]
To optimize network traffic management and security across hybrid clusters, configure {openshift-networking}.

The {openshift-networking} ecosystem of networking capabilities integrates ingress, egress, load balancing, high-performance throughput, security, and inter- and intra-cluster traffic management. The {openshift-networking} ecosystem also provides role-based observability tooling to reduce its natural complexities.

The following list details some of the most commonly used {openshift-networking} features available on your cluster:

* Cluster Network Operator for network plugin management.

ifdef::openshift-rosa-hcp[]
* Primary cluster network provided by OVN-Kubernetes, the default Container Network Interface (CNI) plugin.
endif::openshift-rosa-hcp[]

ifndef::openshift-rosa-hcp[]
* Primary cluster network provided by either of the following Container Network Interface (CNI) plugins:
+
** OVN-Kubernetes network plugin, which is the default CNI plugin.
** {OCP-short} SDN network plugin, which was deprecated in {OCP-short} 4.16 and removed in {OCP-short} 4.17.
endif::openshift-rosa-hcp[]

ifdef::openshift-rosa,openshift-dedicated[]
[IMPORTANT]
====
Before upgrading {product-title} clusters that are configured with the OpenShift SDN network plugin to version 4.17, you must migrate to the OVN-Kubernetes network plugin. For more information, see _Migrating from the OpenShift SDN network plugin to the OVN-Kubernetes network plugin_.
====
endif::openshift-rosa,openshift-dedicated[]
