// module included in the following assemblies:
//
// * configuration/monitor-acs.adoc

:_mod-docs-content-type: PROCEDURE
[id="configuring-custom-prometheus-metrics-by-using-the-api_{context}"]
= Configuring custom Prometheus metrics by using the API

[role="_abstract"]
You can configure custom Prometheus metrics for {rh-rhacs-first} by using the API. The metrics configuration is a part of the private config section of the `/v1/config` service request or response payload.

.Procedure

. To get the current configuration, run the following command:
+
[source,terminal]
----
$ curl "$ROX_API_ENDPOINT/v1/config" -H "Authorization: Bearer $ROX_API_TOKEN" | jq
----
+
The `jq` command formats and displays the JSON response from the API in a readable way.
+
.Example output
+
[source,terminal]
----
{
  "publicConfig": { ... }
  "privateConfig": { ... }
}
----
. To add a policy violation metric named `component_severity`, which includes only component and severity labels, to the configuration, run the following command:
+
[source,text]
----
$ curl "$ROX_API_ENDPOINT/v1/config" -H "Authorization: Bearer $ROX_API_TOKEN" | \
  jq '.privateConfig.metrics.policyViolations.descriptors += {
        component_severity: { labels: [ "Component", "Severity" ] }
      } |
      { config: . }' | \
  curl -X PUT "$ROX_API_ENDPOINT/v1/config" -H "Authorization: Bearer $ROX_API_TOKEN" --data-binary @-
----
+
The `jq` command adds a new `component_severity` metric descriptor with the labels `Component` and `Severity` to the `policyViolations` configuration, then wraps the result in a `config` object for the update request.