// module included in the following assemblies:
//
// * configuration/monitor-acs.adoc

:_mod-docs-content-type: CONCEPT
[id="configure-custom-prometheus-metrics_{context}"]
= Configure custom Prometheus metrics

[role="_abstract"]
You can configure custom Prometheus metrics for {rh-rhacs-first} by using the API or {product-title-short} portal.

You can view the Prometheus metrics that are exposed on the API endpoint at the `/metrics` path. Use the `/v1/config` API to configure metrics with custom names and labels. You can enable or disable one or more of the predefined metrics in the *System Configuration* page.

Collecting and exposing metrics is resource intensive in large environments. The output size depends on the selected labels. For example, selecting only the `Cluster` and `Severity` labels for an image vulnerability metric produces up to five times the number of clusters in records. Adding labels such as `Namespace` increases the output proportionally. Choose labels carefully to avoid unnecessary load.

[NOTE]
====
Scrape requests require permissions to view the Administration resources and are subject for the scoped access control.
====