// Module included in the following assemblies:
//
// * operating/examine-images-for-vulnerabilities.adoc
:_mod-docs-content-type: PROCEDURE
[id="configuring-vm-scanning_{context}"]
= Configuring the virtual machine feature flag

[role="_abstract"]
To use {product-title} ({product-title-short}) to scan virtual machines (VMs), you must configure a feature flag. You must also configure vsock support in {ocp-virt}.

.Procedure

. Configure the VM feature flag environment on following components:
* Central container in the Central pod
* Sensor container in the Sensor pod
* Compliance container in the Collector pod
.. Set the environment variable `ROX_VIRTUAL_MACHINES=true`.`
. Enable virtual socket (vsock) support in {ocp-virt} by adding the following annotation: 
+
[source,terminal]
----
metadata:
 annotations:
   kubevirt.kubevirt.io/jsonpatch: |-
     [
       {
         "op":"add",
         "path":"/spec/configuration/developerConfiguration/featureGates/-",
         "value":"VSOCK"
       }
     ]
----
.. You can add the annotation by completing one of the following steps:
* Edit the CR manually to add the necessary annotation.
* Apply a JSON patch by entering the following command:
+
[source,terminal]
----
$ cat << EOF | kubectl apply -f -
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
  annotations:
    kubevirt.kubevirt.io/jsonpatch: |-
      [
        {
          "op":"add",
          "path":"/spec/configuration/developerConfiguration/featureGates/-",
          "value":"VSOCK"
        }
      ]
spec: {}
EOF
----
* Apply the patch using `kubectl` by entering the following command:
+
[source,terminal]
----
$ kubectl patch hyperconverged kubevirt-hyperconverged -n openshift-cnv --type=merge -p '
  {
    "metadata": {
      "annotations": {
        "kubevirt.kubevirt.io/jsonpatch": "[{\"op\":\"add\",\"path\":\"/spec/configuration/developerConfiguration/featureGates/-\",\"value\":\"VSOCK\"}]"
      }
    }
  }'
----