// Module included in the following assemblies:
//
// * backup_and_restore/application_backup_and_restore/installing/installing-oadp-ibm-cloud.adoc

:_mod-docs-content-type: PROCEDURE
[id="configuring-ibm-cos_{context}"]
= Configuring {ibm-cloud-object-storage} instance

You create an {ibm-cloud-object-storage} instance to store the {oadp-short} backup data. After you create COS instance, you configure the COS instance with `HMAC` service credentials.

.Prerequisites

* You have an {ibm-cloud-title} Platform account.
* You have installed the {ibm-cloud-title} Object Storage CLI.
* You are logged in to the  {ibm-cloud-title} cluster.

.Procedure

. Set a bucket name.
+
[source,terminal]
----
$ BUCKET=<bucket_name>
----

. Set a bucket region.
+
[source,terminal]
----
$ REGION=<bucket_region> <1>
----
<1> For example, `eu-gb`.

. Set a resource group.
+
[source,terminal]
----
$ RESOURCE_GROUP=<resource_group> <1>
----
<1> For example, `"default"`.

. Create an {ibm-cloud-title} resource `service-instance` by running the following command:
+
[source,terminal]
----
$ ibmcloud resource service-instance-create \
<service_instance_name> \// <1>
<service_name> \// <2>
<service_plan> \// <3>
<region_name>\// <4>
----
<1> Specify a name for the `service-instance`.
<2> Specify the service name. Alternatively, you can also specify a service ID instead of the service name.
<3> Specify the service plan for your {ibm-cloud-title} account.
<4> Specify the region name. 

.Example command
+
[source,terminal]
----
$ ibmcloud resource service-instance-create $BUCKET cloud-object-storage \
standard \
global \
-d premium-global-deployment // <1>
----
<1> The `-d` flag specifies the deployment name.

. Extract the `service-instance-id` by running the following command:
+
[source,terminal]
----
$ SERVICE_INSTANCE_ID=$(ibmcloud resource service-instance $BUCKET --output json | jq -r '.[0].id')
----

. Create a COS bucket by running the following command. The values for `$BUCKET`, `$SERVICE_INSTANCE_ID`, and `$REGION` will be replaced.
+
[source,terminal]
----
$ ibmcloud cos bucket-create --bucket $BUCKET --ibm-service-instance-id $SERVICE_INSTANCE_ID --region $REGION
----

. Create `HMAC` credentials by running the following command. In the command, you pass `"HMAC":true` as a parameter.
+
[source,terminal]
----
$ ibmcloud resource service-key-create $BUCKET Writer --instance-name $BUCKET --parameters {\"HMAC\":true}
----

. Extract the `access_key_id` and the `secret_access_key` from the `HMAC` credentials and save them in a `cloud-credentials` file. {oadp-short} uses the `cloud-credentials` file to create a `secret` for the backup storage location. Run the following command.
+
[source,terminal]
----
$ cat > cloud-credentials << __EOF__
[default]
aws_access_key_id=$(ibmcloud resource service-key $BUCKET -o json  | jq -r '.[0].credentials.cos_hmac_keys.access_key_id')
aws_secret_access_key=$(ibmcloud resource service-key $BUCKET -o json  | jq -r '.[0].credentials.cos_hmac_keys.secret_access_key')
__EOF__
----