// Module included in the following assemblies:
//
// * knative-serving/config-applications/configuring-revision-timeouts.adoc

:_mod-docs-content-type: PROCEDURE
[id="configuring-revision-timeout_{context}"]
= Configuring revision timeout

You can configure the default number of seconds for the revision timeout based on the request.

.Prerequisites

* You have installed the {ServerlessOperatorName} and Knative Serving.
* You have the required permissions for your cluster:
** Cluster administrator permissions on {ocp-product-title}
** Cluster administrator or dedicated administrator permissions on {rosa-product-title}
** Cluster administrator or dedicated administrator permissions on {dedicated-product-title}

.Procedure

* Choose the appropriate method to configure the revision timeout:
** To configure the revision timeout globally, set the `revision-timeout-seconds` field in the `KnativeServing` custom resource (CR):
+
[source,yaml]
----
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    defaults:
      revision-timeout-seconds: "300"
----
+
** To configure the timeout per revision by setting the `timeoutSeconds` field in your service definition:
+
[source,yaml]
----
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: my-ns
spec:
  template:
    spec:
      timeoutSeconds: 300
      containers:
      - image: ghcr.io/knative/helloworld-go:latest
----

+
[NOTE]
====
To set the revision timeout to a value over 600 seconds (10 minutes), you must increase the default {ocp-product-title} route timeout and the maximum revision timeout. 

For instructions on how to configure timeouts for requests exceeding the default 600 seconds (10 minutes), see "Long-running requests".
====
