// Module included in the following assemblies:
//
// * integration/integrate-with-image-registries.adoc
:_mod-docs-content-type: PROCEDURE
[id="configuring-assumerole-without-iam_{context}"]
= Configuring AssumeRole without container IAM

[role="_abstract"]
To use AssumeRole without container IAM, you must use an access and a secret key to authenticate as an link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html[AWS user with programmatic access].

.Procedure
. Depending on whether the AssumeRole user is in the same account as the ECR registry or in a different account, you must either:
* Create a new role with the desired permissions if the user for which you want to assume role is in the same account as the ECR registry.
+
[NOTE]
====
When creating the role, you can choose any trusted entity as required. However, you must modify it after creation.
====
* Or, you must provide permissions to access the ECR registry and define its trust relationship if the user is in a different account than the ECR registry:
+
[source,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::<ecr-registry>:role/<assumerole-readonly>" <1>
        }
    ]
}
----
<1> Replace `<assumerole-readonly>` with the role you want to assume.
. Configure the trust relationship of the role by including the user ARN under the *Principal* field:
+
[source,json]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::<ecr-registry>:user/<role-name>"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
----
