// Module included in the following assemblies:
//
// * operating/examine-images-for-vulnerabilities.adoc
:_mod-docs-content-type: CONCEPT
[id="about-scanner-v4_{context}"]
= About RHACS Scanner v4

[role="_abstract"]
{product-title-short} provides its own scanner, or you can configure an integration to use {product-title-short} with another vulnerability scanner.

Beginning with release 4.4, Scanner v4, built from the StackRox and Clair scanners, is the default scanner for language and OS-specific image components. For earlier releases, you had to configure a separate integration to use Clair v4 as your scanner. A separate integration is no longer required for Clair scanning functionality.

You can also configure {product-title-short} to use the {product-title-short} StackRox Scanner. This scanner was the default scanner in {product-title-short} before Scanner v4 was introduced in release 4.4. It originates from a fork of the Clair v2 open source scanner. You must continue using this scanner for RHCOS node scanning and for active vulnerability management until that functionality is supported using Scanner v4 in a future release.

Alternatively, you can xref:../integration/integrate-with-image-vulnerability-scanners.adoc#integrate-with-image-vulnerability-scanners[configure an integration] to use another supported scanner, such as Google Container Analysis or Red Hat Quay.