// Module included in the following assemblies:
//
// * machine_management/creating-infrastructure-machines.adoc

[id="converting-machine-api-infra-machines_{context}"]
= Converting infrastructure machines created using the Machine API

[IMPORTANT]
====
Creating infra machines using the Machine API is now deprecated.
====

Infrastructure machines created using the Machine API had both the `worker` and `infra` labels applied. This dual label required you to also taint the node so that compute workloads were not scheduled on it, to stay in compliance with our subscription guidelines. Managing infra workloads using taints is a tedious and cumbersome process, which is no longer recommended for infra nodes. Machines created using the Machine API must be converted to use only the `infra` label and have a custom machine config pool that manages it.

.Procedure

. Find the infra nodes that are misconfigured with the `worker,infra` dual labels:
+
[source,terminal]
----
$ oc get nodes -l node-role.kubernetes.io/infra
----
+
.Example output
[source,terminal]
+
----
NAME                           STATUS   ROLES          AGE   VERSION
ip-10-0-205-158.ec2.internal   Ready    worker,infra   64m   v1.20.0+551f7b2.20.0
----

. Remove the `worker` label from the node you want to use as an infra node:
+
[source,terminal]
----
$ oc label node <node_name> node-role.kubernetes.io/worker-
----

. Create a dedicated machine config pool to manage your infra nodes.

[NOTE]
====
When removing the `worker` label from your infra node, it is no longer managed by the default machine config pool configured for compute nodes; it is unmanaged. This means the Machine Config Operator (MCO) no longer manages the node, and can not be upgraded. A dedicated machine config pool for your infra nodes allows the MCO to manage the lifecycle of those node types.
====

You can now move infrastructure workloads to the infrastructure nodes that you created.
