// Module included in the following assemblies:
//
// * machine_management/cpmso-configuration.adoc

:_mod-docs-content-type: REFERENCE
[id="cpmso-yaml-provider-spec-aws_{context}"]
= Sample AWS provider specification

When you create a control plane machine set for an existing cluster, the provider specification must match the `providerSpec` configuration in the control plane machine custom resource (CR) that is created by the installation program. You can omit any field that is set in the failure domain section of the CR.

In the following example, `<cluster_id>` is the infrastructure ID that is based on the cluster ID that you set when you provisioned the cluster. If you have the OpenShift CLI installed, you can obtain the infrastructure ID by running the following command:

[source,terminal]
----
$ oc get -o jsonpath='{.status.infrastructureName}{"\n"}' infrastructure cluster
----

.Sample AWS `providerSpec` values
[source,yaml]
----
apiVersion: machine.openshift.io/v1
kind: ControlPlaneMachineSet
metadata:
  name: cluster
  namespace: openshift-machine-api
spec:
# ...
  template:
# ...
      spec:
        providerSpec:
          value:
            ami:
              id: ami-<ami_id_string> <1>
            apiVersion: machine.openshift.io/v1beta1
            blockDevices:
            - ebs: <2>
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ""
                volumeSize: 120
                volumeType: gp3
            credentialsSecret:
              name: aws-cloud-credentials <3>
            deviceIndex: 0
            iamInstanceProfile:
              id: <cluster_id>-master-profile <4>
            instanceType: m6i.xlarge <5>
            kind: AWSMachineProviderConfig <6>
            loadBalancers: <7>
            - name: <cluster_id>-int
              type: network
            - name: <cluster_id>-ext
              type: network
            metadata:
              creationTimestamp: null
            metadataServiceOptions: {}
            placement: <8>
              region: <region> <9>
              availabilityZone: "" <10>
              tenancy: <11>
            securityGroups:
            - filters:
              - name: tag:Name
                values:
                - <cluster_id>-master-sg <12>
            subnet: {} <13>
            userDataSecret:
              name: master-user-data <14>
----
<1> Specifies the {op-system-first} Amazon Machine Images (AMI) ID for the cluster. The AMI must belong to the same region as the cluster. If you want to use an AWS Marketplace image, you must complete the {product-title} subscription from the link:https://aws.amazon.com/marketplace/fulfillment?productId=59ead7de-2540-4653-a8b0-fa7926d5c845[AWS Marketplace] to obtain an AMI ID for your region.
<2> Specifies the configuration of an encrypted EBS volume.
<3> Specifies the secret name for the cluster. Do not change this value.
<4> Specifies the AWS Identity and Access Management (IAM) instance profile. Do not change this value.
<5> Specifies the AWS instance type for the control plane.
<6> Specifies the cloud provider platform type. Do not change this value.
<7> Specifies the internal (`int`) and external (`ext`) load balancers for the cluster.
+
[NOTE]
====
You can omit the external (`ext`) load balancer parameters on private {product-title} clusters.
====
<8> Specifies where to create the control plane instance in AWS.
<9> Specifies the AWS region for the cluster.
<10> This parameter is configured in the failure domain and is shown with an empty value here. If a value specified for this parameter differs from the value in the failure domain, the Control Plane Machine Set Operator overwrites it with the value in the failure domain.
<11> Specifies the AWS Dedicated Instance configuration for the control plane. For more information, see AWS documentation about link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/dedicated-instance.html[Dedicated Instances]. The following values are valid:
* `default`: The Dedicated Instance runs on shared hardware.
* `dedicated`: The Dedicated Instance runs on single-tenant hardware.
* `host`: The Dedicated Instance runs on a Dedicated Host, which is an isolated server with configurations that you can control.
<12> Specifies the control plane machines security group.
<13> This parameter is configured in the failure domain and is shown with an empty value here. If a value specified for this parameter differs from the value in the failure domain, the Control Plane Machine Set Operator overwrites it with the value in the failure domain.
+
[NOTE]
====
If the failure domain configuration does not specify a value, the value in the provider specification is used.
Configuring a subnet in the failure domain overwrites the subnet value in the provider specification.
====
//TODO: clarify with dev about this one in 4.16+
<14> Specifies the control plane user data secret. Do not change this value.