// Module included in the following assemblies:
//
// IPI
// * installing/installing_bare_metal_ipi/ipi-install-installation-workflow.adoc
// * installing/ipi-install-post-installation-configuration.adoc
// UPI
// * installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
// * installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
// * installing/installing_bare_metal/installing-bare-metal.adoc
// * post_installation_configuration/post-install-bare-metal-configuration.adoc

ifeval::["{context}" == "ipi-install-post-installation-configuration"]
:postinstall-bare-metal-ipi:
endif::[]
ifeval::["{context}" == "post-install-bare-metal-configuration"]
:postinstall-bare-metal-upi:
endif::[]

:_mod-docs-content-type: PROCEDURE
[id="creating-manifest-file-customized-br-ex-bridge_{context}"]
= Creating a manifest object that includes a customized br-ex bridge

[role="_abstract"]
ifndef::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]
By default, {product-title} automatically configures the Open vSwitch (OVS) `br-ex` bridge. For advanced networking requirements, on a bare-metal platform you can override the default behavior by creating a `MachineConfig` object that includes an NMState configuration file. 

Consider using the customized `br-ex` bridge configuration for any of the following tasks:

* You need to modify the `br-ex` bridge after you installed the cluster.
* You need to modify the maximum transmission unit (MTU) for your cluster.
* You need to update DNS values.
* You need to modify attributes for a different bond interface, such as MIImon (Media Independent Interface Monitor), bonding mode, or Quality of Service (QoS).
* You need to enable Link Layer Discovery Protocol (LLDP) to discover and troubleshoot switch connectivity.
endif::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]

Consider using the default OVS br-ex bridge configuration if you require a standard environment with a single network interface controller (NIC) and standard OVS settings.

ifdef::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]
By default, {product-title} automatically configures the Open vSwitch (OVS) `br-ex` bridge on bare-metal nodes. For advanced networking requirements, you can override the default behavior by creating a `NodeNetworkConfigurationPolicy` (NNCP) custom resource (CR) that includes an NMState configuration file. 

The Kubernetes NMState Operator uses the NMState configuration file to create a customized `br-ex` bridge network configuration on each node in your cluster.

[IMPORTANT]
====
After creating the `NodeNetworkConfigurationPolicy` CR, copy content from the NMState configuration file that was created during cluster installation into the NNCP CR. An incomplete NNCP CR can result in loss of network connectivity, because the NNCP overrides all existing policies.
====

Consider using the customized `br-ex` bridge configuration for any of the following tasks:

* You want to make postinstallation changes to the bridge, such as changing the Open vSwitch (OVS) or OVN-Kubernetes `br-ex` bridge network. The default OVS `br-ex` bridge mechanism does not support making postinstallation changes to the bridge.
* You want to deploy the bridge on a different interface than the interface available on a host or server IP address.
* You want to make advanced configurations to the bridge that are not possible with the default OVS `br-ex` bridge mechanism. Using the default mechanism for these configurations might result in the bridge failing to connect multiple network interfaces and facilitating data forwarding between the interfaces.
endif::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]

ifndef::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]
[NOTE]
====
If you require an environment with a single network interface controller (NIC) and default network settings, use the default OVS `br-ex` bridge mechanism.
====

After you install {op-system-first} and the system reboots, the Machine Config Operator injects Ignition configuration files into each node in your cluster, so that each node receives the `br-ex` bridge network configuration. To prevent configuration conflicts, the default OVS `br-ex` bridge mechanism is disabled.
endif::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]

[WARNING]
====
The following list of interface names are reserved and you cannot use the names with NMstate configurations:

* `br-ext`
* `br-int`
* `br-local`
* `br-nexthop`
* `br0`
* `ext-vxlan`
* `ext`
* `genev_sys_*`
* `int`
* `k8s-*`
* `ovn-k8s-*`
* `patch-br-*`
* `tun0`
* `vxlan_sys_*`
====

.Prerequisites
ifndef::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]
* Optional: You have installed the link:https://nmstate.io/user/quick_guide.html[`nmstatectl`] CLI tool to validate your NMState configuration.
endif::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]

ifdef::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]
* You have installed the Kubernetes NMState Operator.
* You have identified the specific nodes where you want to apply the policy.
endif::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]

.Procedure

ifndef::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]
. Create a NMState configuration file that has decoded base64 information for your customized `br-ex` bridge network:
+
.Example of an NMState configuration for a customized `br-ex` bridge network
[source,yaml]
----
interfaces:
- name: enp2s0
  type: ethernet
  state: up
  mtu: 9000
  ipv4:
    enabled: false
  ipv6:
    enabled: false
- name: br-ex
  type: ovs-bridge
  state: up
  ipv4:
    enabled: false
    dhcp: false
  ipv6:
    enabled: false
    dhcp: false
  bridge:
    options:
      mcast-snooping-enable: true
    port:
    - name: enp2s0
    - name: br-ex
- name: br-ex
  type: ovs-interface
  state: up
  copy-mac-from: enp2s0
  mtu: 9000
  ipv4:
    enabled: true
    dhcp: true
    auto-route-metric: 48
  ipv6:
    enabled: true
    dhcp: true
    auto-route-metric: 48
# ...
----
+
where:
+
`interfaces.name`:: Specifies the name of the interface.
`interfaces.type`:: Specifies the type of ethernet.
`interfaces.state`:: Specifies the requested state for the interface after creation.
`mtu`:: To ensure network stability and performance, you must explicitly declare the MTU in the manifest for every interface. Do not rely on automatic MTU configuration. The MTU configured on a bridge port or VLAN-tagged interface must not exceed the maximum frame size supported by the attached physical medium. A mismatch causes packet fragmentation or connectivity loss.
`ipv4.enabled`:: Disables IPv4 and IPv6 in this example.
`port.name`:: Specifies the node NIC to which the bridge attaches.
`auto-route-metric`:: Sets the parameter to `48` to ensure the `br-ex` default route always has the highest precedence (lowest metric). This configuration prevents routing conflicts with any other interfaces that are automatically configured by the `NetworkManager` service.

. Use the `cat` command to base64-encode the contents of the NMState configuration:
+
[source,terminal]
----
$ cat <nmstate_configuration>.yml | base64
----
+
where:
+
`<nmstate_configuration>`:: Replace `<nmstate_configuration>` with the name of your NMState resource YAML file.

. Create a `MachineConfig` manifest file and define a customized `br-ex` bridge network configuration analogous to the following example:
+
[source,yaml]
----
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 10-br-ex-worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,<base64_encoded_nmstate_configuration>
        mode: 0644
        overwrite: true
        path: /etc/nmstate/openshift/worker-0.yml
      - contents:
          source: data:text/plain;charset=utf-8;base64,<base64_encoded_nmstate_configuration>
        mode: 0644
        overwrite: true
        path: /etc/nmstate/openshift/worker-1.yml
# ...
----
+
where:
+
`metadata.name`:: The name of the policy.
`contents.source`:: Writes the encoded base64 information to the specified path.
`path`:: For each node in your cluster, specify the hostname path to your node and the base-64 encoded Ignition configuration file data for the machine type. The `worker` role is the default role for nodes in your cluster. You must use the `.yml` extension for configuration files. For example, use `$(hostname -s).yml` when specifying the short hostname path for each node or all nodes in the `MachineConfig` manifest file.
+
You can apply a single global configuration to all nodes in your cluster by using the `/etc/nmstate/openshift/cluster.yml` configuration file. In this case, you do not need to specify the short hostname path for each node, such as `/etc/nmstate/openshift/<node_hostname>.yml`. For example:
+
[source,yaml]
----
# ...
      - contents:
          source: data:text/plain;charset=utf-8;base64,<base64_encoded_nmstate_configuration>
        mode: 0644
        overwrite: true
        path: /etc/nmstate/openshift/cluster.yml
# ...
----

. Apply the updates from the `MachineConfig` object to your cluster by entering the following command:
+
[source,terminal]
----
$ oc apply -f <machine_config>.yml
----
endif::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]

ifdef::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]
* Create a `NodeNetworkConfigurationPolicy` (NNCP) CR and define a customized `br-ex` bridge network configuration. The `br-ex` NNCP CR must include the OVN-Kubernetes masquerade IP address and subnet of your network. The example NNCP CR includes default values in the `ipv4.address.ip` and `ipv6.address.ip` parameters. You can set the masquerade IP address in the `ipv4.address.ip`, `ipv6.address.ip`, or both parameters.
+
[IMPORTANT]
====
As a post-installation task, you cannot change the primary IP address of the customized `br-ex` bridge. If you want to convert your single-stack cluster network to a dual-stack cluster network, you can add or change a secondary IPv6 address in the NNCP CR, but the existing primary IP address cannot be changed.
====
+
[source,yaml]
----
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: worker-0-br-ex
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-0
    desiredState:
    interfaces:
    - name: enp2s0
      type: ethernet
      state: up
      ipv4:
        enabled: false
      ipv6:
        enabled: false
    - name: br-ex
      type: ovs-bridge
      state: up
      ipv4:
        enabled: false
        dhcp: false
      ipv6:
        enabled: false
        dhcp: false
      bridge:
        options:
          mcast-snooping-enable: true
        port:
        - name: enp2s0
        - name: br-ex
    - name: br-ex
      type: ovs-interface
      state: up
      copy-mac-from: enp2s0
      ipv4:
        enabled: true
        dhcp: true
        auto-route-metric: 48
        address:
        - ip: "169.254.0.2"
          prefix-length: 17
      ipv6:
        enabled: true
        dhcp: true
        auto-route-metric: 48
        address:
        - ip: "fd69::2"
        prefix-length: 112
# ...
----
+
where:
+
`metadata.name`:: Name of the policy.
`interfaces.name`:: Name of the interface.
`interfaces.type`:: The type of ethernet.
`interfaces.state`:: The requested state for the interface after creation.
`ipv4.enabled`:: Disables IPv4 and IPv6 in this example.
`port.name`:: The node NIC to which the bridge is attached.
`address.ip`:: Shows the default IPv4 and IPv6 IP addresses. Ensure that you set the masquerade IPv4 and IPv6 IP addresses of your network. 
`auto-route-metric`:: Set the parameter to `48` to ensure the `br-ex` default route always has the highest precedence (lowest metric). This configuration prevents routing conflicts with any other interfaces that are automatically configured by the `NetworkManager` service.
endif::postinstall-bare-metal-ipi,postinstall-bare-metal-upi[]

.Next steps

* Scaling compute nodes to apply the manifest object that includes a customized `br-ex` bridge to each compute node that exists in your cluster. For more information, see "Expanding the cluster" in the _Additional resources_ section.

ifeval::["{context}" == "ipi-install-post-installation-configuration"]
:!postinstall-bare-metal-ipi:
endif::[]
ifeval::["{context}" == "bare-metal-configuration"]
:!postinstall-bare-metal-upi:
endif::[]

