// Module included in the following assemblies:
//
// applications/projects/working-with-projects.adoc

:_content-type: PROCEDURE
[id="creating-a-project-using-the-CLI_{context}"]
= Creating a project using the CLI

If allowed by your cluster administrator, you can create a new project.

[NOTE]
====
Projects starting with `openshift-` and `kube-` are considered critical by {product-title}. As such, {product-title} does not allow you to create Projects starting with `openshift-` or `kube-` using the `oc new-project` command.
ifndef::openshift-dedicated[]
Cluster administrators can create these projects using the `oc adm new-project` command.
endif::openshift-dedicated[]
ifdef::openshift-dedicated[]
For {product-title} clusters that use the Customer Cloud Subscription (CCS) model, users with `cluster-admin` privileges can create these projects using the `oc adm new-project` command.
endif::openshift-dedicated[]
====

ifndef::openshift-dedicated[]
[NOTE]
====
You cannot assign an SCC to pods created in one of the default namespaces: `default`, `kube-system`, `kube-public`, `openshift-node`, `openshift-infra`, and `openshift`. You cannot use these namespaces for running pods or services.
====
endif::openshift-dedicated[]
ifdef::openshift-dedicated[]
[NOTE]
====
In {product-title} clusters that use the Customer Cloud Subscription (CCS) model, you cannot assign an SCC to pods created in one of the default namespaces: `default`, `kube-system`, `kube-public`, `openshift-node`, `openshift-infra`, and `openshift`. You cannot use these namespaces for running pods or services. You cannot create any SCCs for {product-title} clusters that use a Red Hat cloud account, because SCC resource creation requires `cluster-admin` privileges.
====
endif::openshift-dedicated[]

.Procedure

* Run:
+
[source,terminal]
----
$ oc new-project <project_name> \
    --description="<description>" --display-name="<display_name>"
----
+
For example:
+
[source,terminal]
----
$ oc new-project hello-openshift \
    --description="This is an example project" \
    --display-name="Hello OpenShift"
----

[NOTE]
====
The number of projects you are allowed to create
ifdef::openshift-enterprise,openshift-webscale,openshift-origin,openshift-dedicated,openshift-rosa[]
might be limited by the system administrator.
endif::[]
ifdef::openshift-online[]
is limited.
endif::[]
After your limit is reached, you might have to delete an existing project in
order to create a new one.
====
