// Module included in the following assemblies:
//
// * installing/installing_sno/install-sno-installing-sno.adoc

:_module-type: PROCEDURE
:_mod-docs-content-type: PROCEDURE
[id="create-custom-live-rhcos-iso_{context}"]
= Creating a custom live {op-system} ISO for remote server access

In some cases, you cannot attach an external disk drive to a server, however, you need to access the server remotely to provision a node.
It is recommended to enable SSH access to the server.
You can create a live {op-system} ISO with SSHd enabled and with predefined credentials so that you can access the server after it boots.

.Prerequisites

* You installed the `butane` utility.

.Procedure

. Download the `coreos-installer` binary from the `coreos-installer` image link:https://mirror.openshift.com/pub/openshift-v4/clients/coreos-installer/latest/[mirror] page.

. Download the latest live {op-system} ISO from link:https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.12/latest/[mirror.openshift.com].

. Create the `embedded.yaml` file that the `butane` utility uses to create the Ignition file:
+
[source,yaml,subs="attributes+"]
----
variant: openshift
version: {product-version}.0
metadata:
  name: sshd
  labels:
    machineconfiguration.openshift.io/role: worker
passwd:
  users:
    - name: core <1>
      ssh_authorized_keys:
        - '<ssh_key>'
----
<1> The `core` user has sudo privileges.

. Run the `butane` utility to create the Ignition file using the following command:
+
[source,terminal]
----
$ butane -pr embedded.yaml -o embedded.ign
----

. After the Ignition file is created, you can include the configuration in a new live {op-system} ISO, which is named `rhcos-sshd-{product-version}.0-x86_64-live.x86_64.iso`, with the `coreos-installer` utility:
+
[source,terminal,subs="attributes+"]
----
$ coreos-installer iso ignition embed -i embedded.ign rhcos-{product-version}.0-x86_64-live.x86_64.iso -o rhcos-sshd-{product-version}.0-x86_64-live.x86_64.iso
----

.Verification

* Check that the custom live ISO can be used to boot the server by running the following command:
+
[source,terminal,subs="attributes+"]
----
# coreos-installer iso ignition show rhcos-sshd-{product-version}.0-x86_64-live.x86_64.iso
----

+
.Example output
[source,json]
----
{
  "ignition": {
    "version": "3.2.0"
  },
  "passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZnG8AIzlDAhpyENpK2qKiTT8EbRWOrz7NXjRzopbPu215mocaJgjjwJjh1cYhgPhpAp6M/ttTk7I4OI7g4588Apx4bwJep6oWTU35LkY8ZxkGVPAJL8kVlTdKQviDv3XX12l4QfnDom4tm4gVbRH0gNT1wzhnLP+LKYm2Ohr9D7p9NBnAdro6k++XWgkDeijLRUTwdEyWunIdW1f8G0Mg8Y1Xzr13BUo3+8aey7HLKJMDtobkz/C8ESYA/f7HJc5FxF0XbapWWovSSDJrr9OmlL9f4TfE+cQk3s+eoKiz2bgNPRgEEwihVbGsCN4grA+RzLCAOpec+2dTJrQvFqsD alosadag@sonnelicht.local"
        ]
      }
    ]
  }
}
----
