// module included in the following assemblies:
//
// * configuration/monitor-acs.adoc

:_mod-docs-content-type: REFERENCE
[id="custom-metric-categories_{context}"]
= Custom metric categories

You can enable specific Prometheus metrics that you want to expose on the `/metrics` path of the central API endpoint.

The following table lists the available metric categories, their configurability, and default status:

.Metric category and configuration status
[cols="2,2,2",options="header"]
|===
| Metric category | Configurable | Default status

| Image vulnerabilities
| Yes
| Disabled by default

| Node vulnerabilities
| Yes
| Disabled by default

| Policy violations
| Yes
| Disabled by default

| Total policy numbers
| No
| Enabled by default

| Cluster health
| No
| Enabled by default

| Certificate expiry
| No
| Enabled by default

|===

Each category is configured with a data gathering period and a list of metrics. A metric is associated with a set of labels and their include and exclude filters. The label filters are regular expressions, applied to the values before aggregation. You can use them to reduce the `/metrics` output to relevant records. For example, you can use the include filter expression `ACTIVE` for label "State" of a policy violation metric to aggregate only active policy violation alerts, or use the exclude filter expression `false` for label "IsPlatformWorkload" of an image vulnerability metric to exclude platform workload vulnerabilities. Include filters are applied before exclude filters.

[NOTE]
====
The `/metrics` path is accessible for API tokens with Administration resource view permissions. The value of the labels are subject to scoped access control.
====