//module included in the following assemblies:
// * configuration/monitor-acs.adoc

:_mod-docs-content-type: CONCEPT
[id="custom-prometheus-metrics_{context}"]
= Custom Prometheus metrics

[role="_abstract"]
With {product-title}, you can enable some Prometheus metrics to be exposed on the `/metrics` path of the central API endpoint. You can use these metrics with a Prometheus server to monitor {product-title-short} in another application, such as a Perses dashboard in {ocp}.

The available metric categories include:

* Image vulnerabilities
* Node vulnerabilities
* Policy violations
* Total policy numbers
* Cluster health
* Certificate expiry

Each category is configured with a data gathering period and a list of metrics. A metric is associated with a set of labels.

[NOTE]
====
The `/metrics` path is accessible for API tokens with Administration resource view permissions. The values of the labels are subject to scoped access control.
====

The currently enabled metrics are shown on the *System Configuration* page of the *Platform Configuration* section of the {product-title-short} portal. In edit mode, you can enable or disable one of the predefined metrics.

You can use the `/v1/config` API to configure metrics with custom metric names and a custom set of labels.

Accepted image vulnerability labels include the following:

* Cluster
* Namespace
* Deployment
* IsPlatformWorkload
* ImageID
* ImageRegistry
* ImageRemote
* ImageTag
* Component
* ComponentVersion
* OperatingSystem
* CVE
* CVSS
* Severity
* EPSSPercentile
* EPSSProbability
* IsFixable

Accepted node vulnerability labels include the following:

* Cluster
* Node
* Kernel
* OperatingSystem
* OSImage
* Component
* ComponentVersion
* CVE
* CVSS
* Severity
* EPSSPercentile
* EPSSProbability
* IsFixable
* IsSnoozed

Accepted policy violation labels include the following:

* Cluster
* Namespace
* Resource
* Deployment
* IsDeploymentActive
* IsPlatformComponent
* Policy
* Categories
* Severity
* Action
* Message
* Stage
* State
* Entity
* EntityName

The total policy numbers are exposed as the `rox_central_cfg_total_policies` metric, which contains the following label:

* Enabled

The cluster health metric is exposed as `rox_central_health_cluster_info`, and contains the following labels:

* Cluster
* Type
* Status
* Upgradeability

The certificate expiry metric is exposed as `rox_central_cert_exp_hours`, and contains the following label:

* Component