// Module included in the following assemblies:
//
// scalability_and_performance/optimizing-compute-resources.adoc

[id="how-to-debug-issues-with-rhel-tools-{context}"]
= Debugging scaling or performance issues using the RHEL Tools container image

Red Hat distributes a `rhel-tools` container image, packaging tools that aid in
debugging scaling or performance problems. This container image:

* Allows users to deploy minimal footprint container hosts by moving packages out
of the base distribution and into this support container.

* Provides debugging capabilities for Red Hat Enterprise Linux 7 Atomic Host,
which has an immutable package tree. `rhel-tools` includes utilities such as
tcpdump, sosreport, git, gdb, perf, and many more common system administration
utilities.

.Procedure

. to use the rhel-tools` container, run:
+
----
# atomic run rhel7/rhel-tools
----

.Additional resources

* link:https://access.redhat.com/documentation/en/red-hat-enterprise-linux-atomic-host/7/getting-started-with-containers/chapter-11-using-the-atomic-tools-container-image[RHEL
Tools Container documentation ]
