// Module included in the following assemblies:
//
// * rosa_cluster_admin/cloud_infrastructure_access/dedicated-aws-vpn.adoc

:_mod-docs-content-type: PROCEDURE
[id="dedicated-aws-vpn-establishing-connection_{context}"]
= Establishing the VPN connection and enabling route propagation

[role="_abstract"]
After you create the customer gateway and virtual private gateway, establish the Site-to-Site VPN connection and enable route propagation.

.Prerequisites

* You created a customer gateway in your {product-title} AWS account.
* You have a virtual private gateway attached to the cluster VPC.

.Procedure

. From the VPC dashboard, under Virtual private network (VPN) click on *Site-to-Site VPN connections*.
. Click *Create VPN connection*.
.. Give it a meaningful name tag.
.. Select the Virtual private gateway created previously.
.. For Customer gateway, select *Existing*.
.. Select the Customer gateway id by name.
.. If the VPN will use BGP, select *Dynamic*, otherwise select *Static* and enter the Static IP CIDRs. If there are multiple CIDRs, add each CIDR as *Another Rule*.
.. Click *Create VPN connection*.
.. Under *State* wait for the VPN status to change from *Pending* to *Available*, approximately 5 to 10 minutes.
. Select the VPN you just created and click *Download configuration*.
.. From the list, select the vendor, platform, and version of the customer gateway device, then click *Download*.
.. The *Generic* vendor configuration is also available for retrieving information in a plain text format.
+
[NOTE]
====
After the VPN connection has been established, be sure to set up Route Propagation or the VPN may not function as expected. Note the VPC subnet information, which you must add to your configuration as the remote network. 
====
. From the VPC Dashboard, under Virtual private cloud, click on *Route tables*.
. Select the private Route table associated with the VPC that contains your
{product-title} cluster.
+
[NOTE]
====
On some clusters, there may be more than one route table for a particular VPC. Select the private one that has a number of explicitly associated subnets.
====
. Click on the *Route Propagation* tab.
. In the table that appears, you should see the Virtual Private Gateway you created previously. Check the value in the *Propagate* column.
.. If *Propagation* is set to *No*, click *Edit route propagation*, check the *Enable* checkbox in Propagation and click *Save*.
+
After you configure your VPN tunnel and AWS detects it as *Up*, your static or BGP routes are automatically added to the route table.
