// Module included in the following assemblies:
//
// * authentication/using-service-accounts.adoc

[id="dedicated-admin-role-overview_{context}"]
ifdef::openshift-dedicated[]
= About the dedicated administrator role

The accounts for dedicated administrators of an {product-title} cluster,
have increased
permissions and access to all user-created projects.

////
[NOTE]
====
Some configuration changes or procedures discussed in this guide can be
performed by only the {product-title} Operations Team. They are included in this
guide for informational purposes to help you as an {product-title} cluster
administrator better understand what configuration options are possible. If you
want to request a change to your cluster that you cannot perform using the
administrator CLI, open a support case on the
https://access.redhat.com/support/[Red Hat Customer Portal].
====
////

When your account has the `dedicated-admins-cluster` authorization role
bound to it, you
are automatically bound to the `dedicated-admins-project` role for any new projects
that users in the cluster create.

You can perform actions that are associated with a set of verbs, such as `create`,
to operate on a set of resource names, such as `templates`. To view the details
of these roles and their sets of
verbs and resources, run the following commands:

[source,terminal]
----
$ oc describe clusterrole/dedicated-admins-cluster
$ oc describe clusterrole/dedicated-admins-project
----

The verb names do not necessarily all map directly to `oc` commands but rather
equate more generally to the types of CLI operations you can perform. For
example, having the `list` verb means that you can display a list of all objects
of a given resource name by running the `oc get` command, but the `get` verb 
means that you can display the details of a specific object if you know its name
by runnign the `oc describe` command.

{product-title} administrators can grant users a `dedicated-reader` role, which
provides view-only access at the cluster level and view access for all
user projects.

endif::[]
