// Module included in the following assemblies:
//
// * logging/dedicated-cluster-deploying.adoc

[id="cluster-logging-deploy-multitenant_{context}"]
= Installing cluster logging into a multitenant network

If you are deploying cluster logging into a cluster that uses multitenant isolation mode, projects are isolated from other projects. As a result, network traffic is not allowed between pods or services in different projects.

Because the Elasticsearch Operator and the Cluster Logging Operator are installed in different projects, you must explicitly allow access between the  `openshift-operators-redhat` and `openshift-logging` projects.

{product-title} only supports multitenant isolation mode with the OpenShift SDN CNI plug-in.

.Prerequisites
* You have configured multitenant isolation mode with the OpenShift SDN CNI plug-in set to the *NetworkPolicy* mode. For more information, see the [product-title} Networking section.

.Procedure

To allow traffic between the Elasticsearch Operator and the Cluster Logging Operator, create a network policy object in the `openshift-logging` namespace that allows ingress from the `openshift-operators-redhat` project to the `openshift-logging` project.
+
For example:
+
[source,yaml]
----
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-openshift-operators-redhat
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: openshift-operators-redhat
----
