// Module included in the following assemblies:
//
// * installing/acs-default-requirements.adoc
// * cloud_service/acscs-default-requirements.adoc
:_mod-docs-content-type: CONCEPT
[id="default-requirements-secured-cluster-services_{context}"]
= Secured cluster services

Secured cluster services contain the following components:

* Sensor
* Admission controller
* Collector
* Scanner (optional)
* Scanner V4 (optional)

If you use a web proxy or firewall, you must ensure that secured clusters and Central can communicate on HTTPS port 443.

[id="default-requirements-secured-cluster-services-sensor_{context}"]
== Sensor

Sensor monitors your Kubernetes and {ocp} clusters. These services currently deploy in a single deployment, which handles interactions with the Kubernetes API and coordinates with the other {product-title} components.

[discrete]
=== CPU and memory requirements

The following table lists the minimum CPU and memory values required to install and run sensor on secured clusters.

[cols="3",options="header"]
|===
| Sensor | CPU | Memory

| *Request*
| 2 cores
| 4 GiB

| *Limit*
| 4 cores
| 8 GiB
|===

[id="default-requirements-secured-cluster-services-admission-controller_{context}"]
== Admission controller

The Admission controller prevents users from creating workloads that violate policies you configure.

[discrete]
=== CPU and memory requirements

By default, the admission control service runs 3 replicas. The following table lists the request and limits for each replica.

[cols="3",options="header"]
|===
| Admission controller | CPU | Memory

| *Request*
| 0.05 cores
| 100 MiB

| *Limit*
| 0.5 cores
| 500 MiB
|===

[id="default-requirements-secured-cluster-services-collector_{context}"]
== Collector

Collector monitors runtime activity on each node in your secured clusters as a DaemonSet. It connects to Sensor to report this information. The collector pod has three containers. The first container is collector, which monitors and reports the runtime activity on the node. The other two are compliance and node-inventory.

[discrete]
=== Collection requirements

To use the `CORE_BPF` collection method, the base kernel must support BTF, and the BTF file must be available to collector.
In general, the kernel version must be later than 5.8 (4.18 for {op-system-base} nodes) and the `CONFIG_DEBUG_INFO_BTF` configuration option must be set.

Collector looks for the BTF file in the standard locations shown in the following list:

.BTF file locations
[%collapsible]
====
[source,terminal]
----
/sys/kernel/btf/vmlinux
/boot/vmlinux-<kernel-version>
/lib/modules/<kernel-version>/vmlinux-<kernel-version>
/lib/modules/<kernel-version>/build/vmlinux
/usr/lib/modules/<kernel-version>/kernel/vmlinux
/usr/lib/debug/boot/vmlinux-<kernel-version>
/usr/lib/debug/boot/vmlinux-<kernel-version>.debug
/usr/lib/debug/lib/modules/<kernel-version>/vmlinux
----
====

If any of these files exists, it is likely that the kernel has BTF support and `CORE_BPF` is configurable.

[discrete]
=== CPU and memory requirements

By default, the collector pod runs 3 containers. The following tables list the request and limits for each container and the total for each collector pod.

[discrete]
==== Collector container

[cols="3",options="header"]
|===
| Type | CPU | Memory
| *Request*
| 0.06 cores
| 320 MiB

| *Limit*
| 0.9 cores
| 1000 MiB
|===

[discrete]
==== Compliance container

[cols="3",options="header"]
|===

| Type | CPU | Memory
| *Request*
| 0.01 cores
| 10 MiB

| *Limit*
| 1 core
| 2000 MiB
|===

[discrete]
==== Node-inventory container

[cols="3",options="header"]
|===
|Type | CPU | Memory
| *Request*
| 0.01 cores
| 10 MiB

| *Limit*
| 1 core
| 500 MiB
|===

[discrete]
==== Total collector pod requirements

[cols="3",options="header"]
|===
|Type | CPU | Memory
| *Request*
| 0.07 cores
| 340 MiB

| *Limit*
| 2.75 cores
| 3500 MiB
|===

[id="default-requirements-secured-cluster-services-scanner_{context}"]
== Scanner

[discrete]
=== CPU and memory requirements

The requirements in this table are based on the default of 3 replicas.

|===
| StackRox Scanner | CPU | Memory

| *Request*
| 3 cores
| 4500 MiB

| *Limit*
| 6 cores
| 12 GiB
|===

The StackRox Scanner requires Scanner DB (PostgreSQL 15) to store data. The following table lists the minimum memory and storage values required to install and run Scanner DB.

|===
| Scanner DB | CPU | Memory

| *Request*
| 0.2 cores
| 512 MiB

| *Limit*
| 2 cores
| 4 GiB
|===

[id="default-requirements-secured-cluster-services-scanner-v4_{context}"]
== Scanner V4

Scanner V4 is optional. If Scanner V4 is installed on secured clusters, the following requirements apply.

[discrete]
=== CPU, memory, and storage requirements

[discrete]
=== Scanner V4 Indexer

The requirements in this table are based on the default of 2 replicas.

[cols="3",options="header"]
|===
| Scanner V4 Indexer | CPU | Memory
| *Request*
| 2 cores
| 3000 MiB

| *Limit*
| 4 cores
| 6 GiB
|===

[discrete]
=== Scanner V4 DB

Scanner V4 requires Scanner V4 DB (PostgreSQL 15) to store data. The following table lists the minimum CPU, memory, and storage values required to install and run Scanner V4 DB. For Scanner V4 DB, a PVC is not required, but it is strongly recommended because it ensures optimal performance.

[cols="4",options="header"]
|===
| Scanner V4 DB | CPU | Memory | Storage
| *Request*
| 0.2 cores
| 2 GiB
| 10 GiB

| *Limit*
| 2 cores
| 4 GiB
| 10 GiB
|===
