// Module included in the following assemblies:
//
// * operating/manage_security_policies/security-policy-reference.adoc
:_mod-docs-content-type: CONCEPT
[id="default-security-policies_{context}"]
= Default security policies

[role="_abstract"]

The default security policies in {product-title} provide broad coverage to identify security issues and ensure best practices for security in your environment. By configuring those policies, you can automatically prevent high-risk service deployments in your environment and respond to runtime security incidents.

[NOTE]
====
The severity levels for policies in {product-title} are different from the severity levels that Red{nbsp}Hat Product Security assigns.

The {product-title} policy severity levels are Critical, High, Medium, and Low. Red{nbsp}Hat Product Security rates vulnerability severity levels as Critical, Important, Moderate, and Low.

While a policy's severity level and the Red{nbsp}Hat Product Security severity levels can interact, it is important to distinguish between them. For more information about the Red{nbsp}Hat Product Security severity levels, see link:https://access.redhat.com/security/updates/classification[Severity Ratings].
====
