// Module included in the following assemblies:
//
// * applications/deployments/route-based-deployment-strategies.adoc

:_mod-docs-content-type: CONCEPT
[id="deployments-graceful-termination_{context}"]
= Graceful termination

[role="_abstract"]
To avoid dropping user connections when pods shut down in {product-title}, you can rely on graceful termination. The platform sends a `TERM` signal so your application can stop accepting new traffic, close open connections, and exit before the grace period ends.

On shutdown, {product-title} sends a `TERM` signal to the processes in the container. Application code, on receiving `SIGTERM`, stop accepting new connections. This ensures that load balancers route traffic to other active instances. The application code then waits until all open connections are closed, or gracefully terminate individual connections at the next opportunity, before exiting.

After the graceful termination period expires, a process that has not exited is sent the `KILL` signal, which immediately ends the process. The
`terminationGracePeriodSeconds` attribute of a pod or pod template controls the graceful termination period (default 30 seconds) and can be customized per application as necessary.
