// Module included in the following assemblies:
//
// * distr_tracing_tempo/distr-tracing-tempo-configuring.adoc

:_content-type: PROCEDURE
[id="distr-tracing-tempo-accessing-console_{context}"]
= Accessing the Tempo console

To access the Tempo console you must have either {SMProductName} or {DTProductName} installed, and {TempoName} installed, configured, and deployed.

The installation process creates a route to access the Tempo console.

If you know the URL for the Tempo console, you can access it directly. If you do not know the URL, use the following directions.

.Procedure from OpenShift console
. Log in to the {product-title} web console as a user with cluster-admin rights. If you use {product-dedicated}, you must have an account with the `dedicated-admin` role.

. Navigate to *Networking* -> *Routes*.

. On the *Routes* page, select the control plane project, for example `tracing-system`, from the *Namespace* menu.
+
The *Location* column displays the linked address for each route.
+
. If necessary, use the filter to find the `tempo` route. Click the route *Location* to launch the console.

. Click *Log In With OpenShift*.

////
.Procedure from Kiali console

. Launch the Kiali console.

. Click *Distributed Tracing* in the left navigation pane.

. Click *Log In With OpenShift*.
////

.Procedure from the CLI

. Log in to the {product-title} CLI as a user with the `cluster-admin` role. If you use {product-dedicated}, you must have an account with the `dedicated-admin` role.
+
[source,terminal]
----
$ oc login --username=<NAMEOFUSER> https://<HOSTNAME>:6443
----
+
. To query for details of the route using the command line, enter the following command. In this example, `tracing-system` is the control plane namespace.
+
[source,terminal]
----
$ export TEMPO_URL=$(oc get route -n tracing-system tempo -o jsonpath='{.spec.host}')
----
+
. Launch a browser and navigate to ``\https://<TEMPO_URL>``, where `<TEMPO_URL>` is the route that you discovered in the previous step.

. Log in using the same user name and password that you use to access the {Product-title} console.

. If you have added services to the service mesh and have generated traces, you can use the filters and *Find Traces* button to search your trace data.
+
If you are validating the console installation, there is no trace data to display.
