// Module included in the following assemblies:
//CC-3 (alongside 4.10 dev preview)
// * hardware_enablement/dpu-hardware-offload.adoc


:_content-type: PROCEDURE
[id="modify-log-rotation-crio_{context}"]
= Modify log rotation of CRI-O

The BlueField-2 DPU has 16G eMMC, and when {product-title} is running over time the logs can fill up the disc. In {product-title}, the rotation is carried out by default at approximately 50M and 5 files. The pod log file size and number are managed by the kubelet on each node which then passes the setting on to CRI-O. The default settings currently used in {product-title} are as follows:

[source,terminal]
----
--container-log-max-size 50Mi (default 50Mi)
--container-log-max-files 5 (default 5)
----

The current kubelet configuration used by a node is located at `/etc/kubernetes/kubelet.conf`. The default parameters are overwritten from CRI-O:

[source,terminal]
----
containerLogMaxSize: 50Mi
containerLogMaxFiles: 5
----

Pod/container logs are already rotated automatically by default. The `kubelet.conf` file is managed by the machine-config operator so additional steps are necessary.

Limit the container logs on the infrastructure cluster worker nodes following this procedure.

.Procedure

. Obtain the MachineConfig for the kubelet:
+
[source,terminal]
----
oc get machineconfig | grep -i kubelet
----
+
.Example output
+
[source,terminal]
----
01-master-kubelet                                       46327eb10a201b48be7fb3da96a2ffe322539af8   3.2.0             47m
01-worker-kubelet                                       46327eb10a201b48be7fb3da96a2ffe322539af8   3.2.0             47m
----

. Set up a custom kubelet for the worker nodes (nodes with DPUs) on the infrastructure cluster.

.. Label the worker machineconfigpool with custom-kubelet custom tag of logrotation:
+
[source,terminal]
----
$ oc label machineconfigpool worker custom-kubelet=logrotation
----

.. Create a YAML file `logrotation.yaml` defining a `kubeletconfig` custom resource (CR) for your configuration change:
+
[source,yaml]
----
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: cr-logrotation
spec:
  machineConfigPoolSelector:
    matchLabels:
      custom-kubelet: logrotation <1>
  kubeletConfig:
    containerLogMaxFiles: 3 <2>
    containerLogMaxSize: 10Mi <3>
----
<1> Set this value to the same as the `custom-kubelet` value configured in step 2a.
<2> Set the desired maximum number (for example 3) of container log files that can be present for a container.
<3> Set the desired maximum size (for example 10Mi) of container log file before it is rotated.

.. Create the CR object:
+
[source,terminal]
----
$ oc create -f logrotation.yaml
----

.Verification

. Verify the kubeletconfig:
+
[source,terminal]
----
$ oc get kubeletconfig
----

. Verify the kubeletconfig:
+
[source,terminal]
----
$ oc get kubeletconfig -o yaml
----

. Verify that three machineconfigs now exist:
+
[source,terminal]
----
$ oc get machineconfig | grep -i kubelet
----
+
.Example output

[source,terminal]
----
01-master-kubelet                                       46327eb10a201b48be7fb3da96a2ffe322539af8   3.2.0             74m
01-worker-kubelet                                       46327eb10a201b48be7fb3da96a2ffe322539af8   3.2.0             74m
99-worker-generated-kubelet                             46327eb10a201b48be7fb3da96a2ffe322539af8   3.2.0             11m
----

. Enter into a debug session on one of the worker nodes. This step instantiates a debug pod called <node_name>-debug:
+
[source,terminal]
----
$ oc debug node/<node_name>
----

. Set `/host` as the root directory within the debug shell. The debug pod mounts the host’s root file system in `/host` within the pod. By changing the root directory to `/host`, you can run binaries contained in the host’s executable paths:
+
[source,terminal]
----
# chroot /host
----

. Verify the settings in `kubelet.conf`:
+
[source,terminal]
----
# grep -e containerLogMaxSize -e containerLogMaxFiles /etc/kubernetes/kubelet.conf
----
+
.Example output
+
[source,terminal]
----
 "containerLogMaxSize": "10Mi",
 "containerLogMaxFiles": 3,
----