// Module included in the following assemblies:
//
// * nodes/nodes/eco-poison-pill-operator.adoc

[id="installing-poison-pill-operator-using-cli_{context}"]
= Installing the Poison Pill Operator by using the CLI

You can use the OpenShift CLI (`oc`) to install the Poison Pill Operator.

.Prerequisites

* Install the OpenShift CLI (`oc`).
* Log in as a user with `cluster-admin` privileges.

.Procedure

. Create a `Namespace` custom resource (CR) for the Poison Pill Operator:
.. Define the `Namespace` CR and save the YAML file, for example, `poison-pill-namespace.yaml`:
+
[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: poison-pill
----
.. To create the `Namespace` CR, run the following command:
+
[source,terminal]
----
$ oc create -f poison-pill-namespace.yaml
----

. Create an `OperatorGroup` CR:
.. Define the `OperatorGroup` CR and save the YAML file, for example, `poison-pill-operator-group.yaml`:
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: poison-pill-manager
  namespace: poison-pill
spec:
  targetNamespaces:
  - poison-pill
----
.. To create the `OperatorGroup` CR, run the following command:
+
[source,terminal]
----
$ oc create -f poison-pill-operator-group.yaml
----

. Create a `Subscription` CR:
.. Define the `Subscription` CR and save the YAML file, for example, `poison-pill-subscription.yaml`:
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: poison-pill-manager
    namespace: poison-pill
spec:
    channel: alpha
    name: poison-pill-manager
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    package: poison-pill-manager
----
.. To create the `Subscription` CR, run the following command:
+
[source,terminal]
----
$ oc create -f poison-pill-subscription.yaml
----

.Verification

. Verify that the installation succeeded by inspecting the CSV resource:
+
[source,terminal]
----
$ oc get csv -n poison-pill
----
+
.Example output
[source,terminal]
----
NAME                   DISPLAY                 VERSION   REPLACES    PHASE
poison-pill.v0.1.4     Poison Pill Operator    0.1.4                 Succeeded
----

. Verify that the Poison Pill Operator is up and running:
+
[source,terminal]
----
$ oc get deploy -n poison-pill
----
+
.Example output
[source,terminal]
----
NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
poison-pill-controller-manager       1/1     1            1           10d
----

. Verify that the Poison Pill Operator created the `PoisonPillConfig` CR:
+
[source,terminal]
----
$ oc get PoisonPillConfig -n poison-pill
----
+
.Example output
[source,terminal]
----
NAME                 AGE
poison-pill-config   10d
----
. Verify that each poison pill pod is scheduled and running on each worker node:
+
[source,terminal]
----
$ oc get daemonset -n poison-pill
----
+
.Example output
[source,terminal]
----
NAME             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
poison-pill-ds   2         2         2       2            2           <none>          10d
----
+
[NOTE]
====
This command is unsupported for the control plane nodes.
====