// Module included in the following assemblies:
//
// * logging/efk-logging-manual-rollout.adoc

[id='efk-logging-manual-rollout-rolling-{context}']
= Performing an Elasticsearch rolling cluster restart

A rolling restart is recommended, when any of the following changes are made:

* nodes on which Elasticsearch pods run require a reboot
* `logging-elasticsearch` configmap
* `logging-es-*`` deployment configuration
* new image deployment, or upgrade

This will be the recommended restart policy going forward.

[NOTE]
====
Any action you do for an ES cluster will need to be repeated for the ops cluster
if `openshift_logging_use_ops` was configured to be `True`.
====

. Prevent shard balancing when purposely bringing down nodes:
+
----
$ oc exec -c elasticsearch <any_es_pod_in_the_cluster> --
          curl -s
          --cacert /etc/elasticsearch/secret/admin-ca \
          --cert /etc/elasticsearch/secret/admin-cert \
          --key /etc/elasticsearch/secret/admin-key \
          -XPUT 'https://localhost:9200/_cluster/settings' \
          -d '{ "transient": { "cluster.routing.allocation.enable" : "none" } }'
----

. Once complete, for each `dc` you have for an ES cluster, run `oc rollout latest`
to deploy the latest version of the `dc` object:
+
----
$ oc rollout latest <dc_name>
----
+
You will see a new pod deployed. Once the pod has two ready containers, you can
move on to the next `dc`.

. Once all `dc`s for the cluster have been rolled out, re-enable shard balancing:
+
----
$ oc exec -c elasticsearch <any_es_pod_in_the_cluster> --
          curl -s
          --cacert /etc/elasticsearch/secret/admin-ca \
          --cert /etc/elasticsearch/secret/admin-cert \
          --key /etc/elasticsearch/secret/admin-key \
          -XPUT 'https://localhost:9200/_cluster/settings' \
          -d '{ "transient": { "cluster.routing.allocation.enable" : "all" } }'
----
