// Module included in the following assemblies:
//
// * logging/efk-logging.adoc

[id='efk-logging-about-{context}']
= About EFK logging in {product-title}

As an {product-title} cluster administrator, you can deploy the Elasticsearch, Fluentd, and Kibana (EFK) stack to
aggregate logs for a range of {product-title} services. 

Application developers can view the logs of the projects for which they have view access. The EFK stack
aggregates logs from hosts and applications, whether coming from multiple
containers or even deleted pods.

The EFK stack aggregates logs from nodes and applications
running inside your {product-title} cluster. Once deployed it uses
link:http://www.fluentd.org/architecture[Fluentd] to aggregate event logs from
all nodes, projects, and pods into
link:https://www.elastic.co/products/elasticsearch[Elasticsearch (ES)]. It also
provides a centralized
link:https://www.elastic.co/guide/en/kibana/current/introduction.html[Kibana]
web UI where users and administrators can create rich visualizations and
dashboards with the aggregated data.
