// Module included in the following assemblies:
//
// * logging/efk-logging-configuring.adoc

[id="efk-logging-configuring-image-about_{context}"]
= Understanding the cluster logging component images

There are several components in cluster logging, each one implemented with one
or more images.  Each image is specified by an environment variable
defined in the *cluster-logging-operator* deployment in the *openshift-logging* project and should not be changed.

You can view the images by running the following command:

----
oc -n openshift-logging set env deployment/cluster-logging-operator --list | grep _IMAGE

ELASTICSEARCH_IMAGE=quay.io/openshift/origin-logging-elasticsearch5:latest <1>
FLUENTD_IMAGE=quay.io/openshift/origin-logging-fluentd:latest <2>
KIBANA_IMAGE=quay.io/openshift/origin-logging-kibana5:latest <3>
CURATOR_IMAGE=quay.io/openshift/origin-logging-curator5:latest <4>
OAUTH_PROXY_IMAGE=quay.io/openshift/origin-oauth-proxy:latest <5>
----
<1> *ELASTICSEARCH_IMAGE* deploys Elasticsearch.
<2> *FLUENTD_IMAGE* deploys Fluentd.
<3> *KIBANA_IMAGE* deploys Kibana.
<4> *CURATOR_IMAGE* deploys Curator.
<5> *OAUTH_PROXY_IMAGE* defines OAUTH for OpenShift Container Platform.

[NOTE]
====
The values might be different depending on your environment.
====



////
Comment out until 4.1
* *RSYSLOG_IMAGE* deploys Rsyslog, by default `docker.io/viaq/rsyslog:latest`. <1>

<1> The image used for RSYSLOG when deployed. You can change this value using an environment variable. You cannot change this value through the Cluster Logging CR.

[NOTE]
====
The Rsyslog log collector is in Technology Preview.
====
////

