// Module included in the following assemblies:
//
// * logging/efk-logging-fluentd.adoc

[id="efk-logging-fluentd-log-location_{context}"]
= Configuring the collected log location

The log collector, Fluentd or Rsyslog, writes logs to a specified file or to the default location, `/var/log/fluentd/fluentd.log`
or `/var/log/rsyslog/rsyslog.log`, based on the `LOGGING_FILE_PATH` environment variable.

.Prerequisite

Set cluster logging to the unmanaged state.

.Procedure

To set the output location for the Fluentd logs:

. Edit the `LOGGING_FILE_PATH`  parameter in the `fluentd` or `rsyslog` daemonset. You can specify a particular file or `console`:
+
----
spec:
  template:
    spec:
      containers:
          env:            
            - name: LOGGING_FILE_PATH
              value: console <1>
----
<1> Specify the log output method: 
* use `console` to use the Fluentd default location. Retrieve the logs with the `oc logs [-f] <pod_name>` command.
* use `<path-to-log/fluentd.log> to sends the log output to the specified file. Retrieve the logs with the `oc exec <pod_name> -- logs` command.
This is the default setting.
+
Or, use the CLI:
+
----
oc -n openshift-logging set env daemonset/fluentd LOGGING_FILE_PATH=/logs/fluentd.log
----
+
----
oc -n openshift-logging set env daemonset/rsyslog LOGGING_FILE_PATH=/logs/rsyslog.log
----

