// Module included in the following assemblies:
//
// * operating/examine-images-for-vulnerabilities.adoc
:_mod-docs-content-type: PROCEDURE
[id="enabling-scanner-v4-operator-secured-cluster_{context}"]
= Enabling RHACS Scanner V4 on the secured cluster when installing with the Operator

[role="_abstract"]
Scanner V4 is not enabled by default, but you can enable it during installation. Use this procedure to understand the steps you must follow when enabling Scanner V4. However, you might need to refer to the detailed installation documentation in "Additional resources", depending on the configuration of your other components.

.Prerequisite

* You set up Central and the secured cluster by using an init bundle or CRS so that they can communicate with each other.

.Procedure

. On the secured cluster, follow the installation procedures as described in "Installing {product-title-short} on secured clusters by using the Operator". Choose one of these methods to enable Scanner V4:
* In the *Scanner V4 Component Settings* section, in the *Scanner V4 Component* menu, select *AutoSense*.
* In the SecuredCluster CR YAML, configure the following parameter:
+
[source,yaml]
----
  scannerV4:
    scannerComponent: AutoSense
----