// Module included in the following assemblies:
//
// * configuration/monitor-acs.adoc
:_module-type: PROCEDURE
[id="enable-monitoring-central-operator_{context}"]
= Monitoring Central services by using the {product-title-short} Operator

[role="_abstract"]
You can monitor Central services, Central and Scanner, by changing the configuration of the `Central` custom resource. For more information on configuration options, see "Central configuration options using the Operator" in the "Additional resources" section.

.Procedure
. On the {ocp} web console, go to the *Operators* -> *Installed Operators* page.
. Select the {product-title} Operator from the list of installed Operators.
. Click on the *Central* tab.
. From the list of Central instances, click on a Central instance for which you want to enable monitoring for.
. Click on the *YAML* tab and update the YAML configuration:
* For monitoring Central, enable the `central.monitoring.exposeEndpoint` configuration option for the `Central` custom resource.
* For monitoring Scanner, enable the `scanner.monitoring.exposeEndpoint` configuration option for the `Central` custom resource.
. Click *Save*.