// Module included in the following assemblies:
//
// * work_with_shared_resources/using-shared-resource-csi-driver.adoc

:_mod-docs-content-type: PROCEDURE
[id="ephemeral-storage-using-a-sharedsecret-custom-resource-in-a-pod_{context}"]
= Using a SharedSecret custom resource in a pod

[role="_abstract"]
To access the `SharedSecret` custom resource (CR) from a pod, you grant role-based access control (RBAC) permission to a service account.

.Prerequisites

* You are logged in to the {ocp-product-title} cluster  as one of the following users:
** A cluster administrator who has created the `SharedSecret` CR instance for the `Secret` object.
** A user with permissions to access the target namespaces and to create or manage the `SharedSecret` custom resource for the `Secret` to be shared.
* You must have permissions to perform the following actions:
** Run the `oc adm policy who-can use <sharedsecret_identifier>` command to check if a service account is allowed to use the `SharedSecret` CR and the service account is listed in your namespace.
** Confirm that the service account of your pod is allowed to use the `csi` volume. If you created the pod as a user, confirm that you are allowed to use the `csi` volume.

[NOTE]
====
If you are unable to complete the last two prerequisites, the cluster administrator can establish the necessary RBAC permission so that you can enable service accounts to use the `SharedSecret` CR.
====

.Procedure

. Create the `RoleBinding` object in the cluster associated with the role and grant the permission to your service account to use the shared resource. See the following example configuration:
+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-shared-secret
  namespace: app-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: use-shared-secret
subjects:
  - kind: ServiceAccount
    name: <service_account_name>
----
+
where:

`metadata.name`:: Defines the name of the `RoleBinding` CR. 

`<service_account_name>`:: Specifies the name of the service account of your application.

. Mount the shared resource `csi` driver into a pod or any other resource that accepts `csi` volumes. See the following example configuration:
+
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: example-shared-secret
  namespace: <app_namespace>
spec:
  ...
  serviceAccountName: default
  volumes:
    - name: shared-secret
      csi:
        readOnly: true 
        driver: csi.sharedresource.openshift.io
        volumeAttributes:
          sharedSecret: shared-test-secret
----
+
where:

`<app_namespace>`:: Specifies the name of the namespace of your application.

`volumes.volumeAttributes.sharedSecret`:: Defines the value of the `sharedSecret` attribute that must be same as the name of the `SharedSecret` CR.

+
[IMPORTANT]
====
The pod fails to start in the following cases:

* The value of the `sharedSecret` attribute does not match the name of the `SharedSecret` instance.
* A volume is defined but not mounted, the pod stays in the `ContainerCreating` state and eventually fails.
====

.Verification

. Run the following command to verify the permission granted to your service account:
+
[source,terminal]
----
$ oc describe rolebinding share-etc-pki-entitlement -n openshift-config-managed
----
+
.Example output
+
[source,terminal]
----
Name:         share-etc-pki-entitlement
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  Role
  Name:  share-etc-pki-entitlement
Subjects:
  Kind            Name                        Namespace
  ----            ----                        ---------
  ServiceAccount  csi-driver-shared-resource  openshift-builds
----

