// Module included in the following assemblies:
//
// * security/external_secrets_operator/external-secrets-operator-release-notes.adoc
:_mod-docs-content-type: REFERENCE
[id="external-secrets-operator-rn-1-2-1_{context}"]
= Release notes for {external-secrets-operator} 1.2.1

[role="_abstract"]
{external-secrets-operator} 1.2.1 is based on the upstream external-secrets version v2.5.0.

Issued: 2026-09-10

The following advisories are available for the {external-secrets-operator}:

* link:https://access.redhat.com/errata/RHBA-2026:66361[RHBA-2026:66361]
* link:https://access.redhat.com/errata/RHSA-2026:66363[RHSA-2026:66363]
* link:https://access.redhat.com/errata/RHBA-2026:66362[RHBA-2026:66362]
* link:https://access.redhat.com/errata/RHBA-2026:66382[RHBA-2026:66382]

[NOTE]
====
This release updates the NTLM library that is used by the webhook provider for `NTLM` and Neg`otiate authentication. This update modifies the initial handshake message, but the configuration settings, credentials, and secret synchronization behavior remain unchanged. Most NTLM servers are unaffected. However, webhook stores that use `NTLM` or `Negotiate` authentication might encounter errors if a server rejects the new handshake format.
====

[id="external-secrets-operator-1-2-1-features-enhancements_{context}"]
== New features and enhancements
Operand container argument overrides in the Operator subscription::

With this release, you can override container arguments for core components of `external-secrets` operand by specifying the environment variables in the {external-secrets-operator} `Subscription` object.

For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html/security_and_compliance/external-secrets-operator-for-red-hat-openshift#external-secrets-operator-overriding-operand-arguments_external-secrets-log-levels[Customizing the External Secrets Operator for Red Hat OpenShift].


[id="external-secrets-operator-1-2-1-cves_{context}"]
== CVEs

* https://access.redhat.com/security/cve/cve-2026-33818[CVE-2026-33818]
* https://access.redhat.com/security/cve/cve-2026-41178[CVE-2026-41178]
* https://access.redhat.com/security/cve/cve-2026-56852[CVE-2026-56852]
* https://access.redhat.com/security/cve/cve-2026-56853[CVE-2026-56853]
* https://access.redhat.com/security/cve/cve-2026-56858[CVE-2026-56858]
* https://access.redhat.com/security/cve/cve-2026-56860[CVE-2026-56860]
* https://access.redhat.com/security/cve/cve-2026-56862[CVE-2026-56862]
* https://access.redhat.com/security/cve/cve-2026-71556[CVE-2026-71556]
