// Module included in the following assemblies:
//
// * authentication/external-auth.adoc

:_mod-docs-content-type: PROCEDURE
[id="external-auth-configuring_{context}"]
= Configuring an external OIDC identity provider for direct authentication

You can configure {product-title} to directly use an external OIDC identity provider to issue tokens for authentication.

.Prerequisites

* You have configured your external authentication provider.
+
This procedure uses Keycloak as the identity provider and assumes that you have the following clients configured:

** A confidential client for the web console called `console-test` with the valid redirect URIs set to [x-]`https://<openshift_console_route>/auth/callback`

** A public client for the {oc-first} called `oc-cli-test` with the valid redirect URIs set to [x-]`http://localhost:8080`

* You have access to the `kubeconfig` file generated by the installation program for the cluster.
* You have backed up any existing authentication configuration, in case you need to revert back to using the built-in OAuth server for authentication.

.Procedure

. Ensure that you are using the `kubeconfig` file generated by the installation program, or another long-lived method of logging in as a cluster administrator.

. Create a secret that allows you to authenticate with the web console by running the following command:
+
[source,terminal]
----
$ oc create secret generic console-secret \
    --from-literal=clientSecret=<secret_value> \// <1>
    -n openshift-config
----
<1> Replace `<secret_value>` with the value of the secret for the `console-test` client in your identity provider.

. Optional: Create a config map that contains the provider's certificate authority bundle by running the following command:
+
[source,terminal]
----
$ oc create configmap keycloak-oidc-ca --from-file=ca-bundle.crt=my-directory/ca-bundle.crt \// <1>
    -n openshift-config
----
<1> Specify the path to your provider's `ca-bundle.crt` file.

. Edit the authentication configuration by running the following command:
+
[source,terminal]
----
$ oc edit authentication.config/cluster
----

. Update the authentication configuration by setting the `type` field to `OIDC`, configuring the `oidcProviders` field for your provider, and setting the `webhookTokenAuthenticator` field to `null`:
+
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: Authentication
metadata:
# ...
spec:
  type: OIDC # <1>
  webhookTokenAuthenticator: null # <2>
  oidcProviders: # <3>
  - claimMappings:
      extra: # <4>
      - key: example.com/role
        valueExpression: claims.?role.orValue("unknown")
      groups:
        claim: groups # <5>
        prefix: 'oidc-groups-test:'
      uid: # <6>
        claim: "sub"
      username:
        claim: email #<7>
        prefixPolicy: Prefix
        prefix:
          prefixString: 'oidc-user-test:'
    issuer:
      audiences: # <8>
      - console-test
      - oc-cli-test
      issuerCertificateAuthority:
        name: keycloak-oidc-ca # <9>
      issuerURL: https://keycloak-keycloak.apps.example.com/realms/master # <10>
    name: 'keycloak-oidc-server' # <11>
    oidcClients:
    - clientID: oc-cli-test # <12>
      componentName: cli
      componentNamespace: openshift-console
    - clientID: console-test # <13>
      clientSecret:
        name: console-secret # <14>
      componentName: console
      componentNamespace: openshift-console
      extraScopes: # <15>
        - email
        - profile
----
<1> Must be set to `OIDC` to indicate to use an external OIDC identity provider.
<2> Must be set to `null` when `type` is set to `OIDC`.
<3> The OIDC provider configuration. Currently, only one OIDC provider configuration is allowed.
<4> An optional field for configuring the mappings used to construct the extra attributes for the cluster identity.
<5> The name of the claim to construct group names for the cluster identity.
<6> An optional field for configuring the claim mapping used to construct the uid for the cluster identity.
<7> The name of the claim to construct usernames for the cluster identity.
<8> The list of audiences that this authentication provider issues tokens for.
<9> The name of the config map that contains the `ca-bundle.crt` key. If unset, system trust is used instead.
<10> The URL for the token issuer.
<11> The name for external OIDC provider.
<12> The client ID that your provider uses for the {oc-first}.
<13> The client ID that your provider uses for the {product-title} web console.
<14> The name of the secret that stores the secret value for the console client.
<15> The extra scopes to request. Some providers, such as GitLab, might require extra scopes in order to log in through the web console properly.
+
For more details on all available parameters, see "OIDC provider configuration parameters".

. Exit and save the changes to apply the new configuration.

. Wait for the cluster to roll out new revisions to all nodes.

.. Check the Kubernetes API server Operator status by running the following command:
+
[source,terminal]
----
$ oc get co kube-apiserver
----
+
.Example output
[source,terminal]
----
NAME             VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
kube-apiserver   4.21.0    True        True          False      85m     NodeInstallerProgressing: 2 node are at revision 8; 1 node is at revision 10
----
+
The message in the preceding example shows that one node has progressed to the new revision and two nodes have not yet updated. It can take 20 minutes or more to roll out the new revision to all nodes, depending on the size of your cluster.

.. To troubleshoot any issues, you can also check the Cluster Authentication Operator and `kube-apiserver` pod logs for errors.

.Verification

. Verify that you can log in to the {oc-first} by authenticating with your identity provider:

.. Log in by running the following command:
+
[source,terminal]
----
$ oc login --exec-plugin=oc-oidc \// <1>
    --issuer-url=https://keycloak-keycloak.apps.example.com/realms/master \// <2>
    --client-id=oc-cli-test \// <3>
    --extra-scopes=email --callback-port=8080 \
    --oidc-certificate-authority my-directory/ca-bundle.crt <4>
----
<1> Specify `oc-oidc` as the exec plugin type. Only a value of `oc-oidc` is allowed.
<2> Specify the issuer URL for your identity provider.
<3> Specify client ID for the {oc-first}.
<4> Specify the path to the `ca-bundle.crt` file on your local machine.
+
.Example output
[source,terminal]
----
Please visit the following URL in your browser: http://localhost:8080
----

.. Open http://localhost:8080 in a browser.

.. Authenticate with credentials from your identity provider.
+
After successfully authenticating, you should see a message similar to the following output in your terminal:
+
[source,terminal]
----
Logged into "https://api.my-cluster.example.com:6443" as "oidc-user-test:user1@example.com" from an external oidc issuer.
----

. Verify that you can log in to the {product-title} web console by authenticating with your identity provider:

.. Open the web console URL for your cluster in a browser.
+
You are redirected to your identity provider to log in.

.. Authenticate with credentials from your identity provider.
+
Verify that you logged in successfully and are redirected to the {product-title} web console.
