// Module included in the following assemblies:
//
// * security/external_secrets_operator/external-secrets-log-levels.adoc

:_mod-docs-content-type: PROCEDURE
[id="external-secrets-enable-operator-log-level_{context}"]
= Setting a log level for the {external-secrets-operator}

You can set a log level for the {external-secrets-operator} to determine the verbosity of the operator log messages.

.Prerequisites

* You have access to the cluster with `cluster-admin` privileges.
* You have created the `ExternalSecretsConfig` custom resource.

.Procedure

* Update the subscription object for {external-secrets-operator} to provide the verbosity level for the operator logs by running the following command:
+
[source,terminal]
----
$ oc -n <external_secrets_operator_namespace> patch subscription openshift-external-secrets-operator --type='merge' -p '{"spec":{"config":{"env":[{"name":"OPERATOR_LOG_LEVEL","value":"<log_level>"}]}}}'
----
+
where:

external_secrets_operator_namespace:: Namespace where the operator is installed.

log_level:: Supports the value range of 1-5. The default is 2.

.Verification

. The External Secrets Operator pod is redeployed. Verify that the log level of the {external-secrets-operator} is updated by running the following command:
+
[source,terminal]
----
$ oc set env deploy/external-secrets-operator-controller-manager -n external-secrets-operator --list | grep -e OPERATOR_LOG_LEVEL -e container
----
+
.Example output
[source,terminal]
----
# deployments/external-secrets-operator-controller-manager, container manager
OPERATOR_LOG_LEVEL=2
----

. Verify that the log level of the {external-secrets-operator} is updated by running the `oc logs` command:
+
[source,terminal]
----
$ oc logs -n external-secrets-operator -f deployments/external-secrets-operator-controller-manager -c manager
----