// Module included in the following assemblies:
//
// * getting-started/openshift-web-console.adoc

:_content-type: PROCEDURE
[id="getting-started-web-console-creating-new-project_{context}"]
= Creating a new project

A project enables a community of users to organize and manage their content in isolation. Projects are {product-title} extensions to Kubernetes namespaces. Projects have additional features that enable user self-provisioning.

Users must receive access to projects from administrators. Cluster administrators can allow developers to create their own projects. In most cases, users automatically have access to their own projects.

Each project has its own set of objects, policies, constraints, and service accounts.

.Prerequisites

* You are logged in to the {product-title} web console.
* You are in the *Developer* perspective.
* You have the appropriate roles and permissions in a project to create applications and other workloads in {product-title}.

.Procedure

. In the *+Add* view, select *Project* -> *Create Project*.
. In the *Name* field, enter `user-getting-started`.
. Optional: In the *Display name* field, enter `Getting Started with OpenShift`.
+
[NOTE]
====
*Display name* and *Description* fields are optional.
====
. Click *Create*.

You have created your first project on {product-title}.
