// Module included in the following assemblies:
//
// * argocd_instance/argo-cd-cr-component-properties.adoc

:_mod-docs-content-type: REFERENCE
[id="argo-cd-properties_{context}"]
= Argo CD custom resource properties

The Argo CD Custom Resource consists of the following properties:

|===
<<<<<<< HEAD
|**Name** |**Description** |**Default** | **Properties**
|`applicationInstanceLabelKey` |The `metadata.label` key name where Argo CD injects the app name as a tracking label.|`app.kubernetes.io/instance` |

|`applicationSet`
|`applicationSet` controller configuration options.
| `_<object>_`
a|* _<image>_ - The container image for the `applicationSet` controller. This overrides the `ARGOCD_APPLICATIONSET_IMAGE` environment variable.
  * _<version>_ - The tag to use with the `applicationSet` container image.
  * _<resources>_ - The container compute resources.
  * _<logLevel>_ - The log level used by the Argo CD Application Controller component. Valid options are `debug`, `info`, `error`, and `warn`.
  * _<logFormat>_ - The log format used by the Argo CD Application Controller component. Valid options are `text` or `json`.
  * _<parallelismLimit>_ - The kubectl parallelism limit to set for the controller (`--kubectl-parallelism-limit` flag).

|`configManagementPlugins`    |Add a configuration management plugin.| `__<empty>__` |

|`controller`    |Argo CD Application Controller options.| `__<object>__`
a|* _<processors.operation>_ - The number of operation processors.
  * _<processors.status>_ - The number of status processors.
  * _<resources>_ - The container compute resources.
  * _<logLevel>_ - The log level used by the Argo CD Application Controller component. Valid options are `debug`, `info`, `error`, and `warn`.
  * _<appSync>_ - AppSync is used to control the sync frequency of Argo CD applications.
  * _<sharding.enabled>_ - Enable sharding on the Argo CD Application Controller component. This property is used to manage a large number of clusters to relieve memory pressure on the controller component.
  * _<sharding.replicas>_ - The number of replicas that are used to support sharding of the Argo CD Application Controller.
  * _<env>_ - Environment to set for the application controller workloads.

|`disableAdmin`    |Disables the built-in admin user.|`false` |
|`gaTrackingID`    |Use a Google Analytics tracking ID.|`__<empty>__` |
|`gaAnonymizeUsers`    |Enable hashed usernames sent to google analytics.|`false` |

|`ha`    |High availablity options.| `__<object>__`
a|* _<enabled>_ - Toggle high availability support globally for Argo CD.
  * _<redisProxyImage>_ - The Redis HAProxy container image. This overrides the `ARGOCD_REDIS_HA_PROXY_IMAGE` environment variable.
  * _<redisProxyVersion>_ - The tag to use for the Redis HAProxy container image.

|`helpChatURL`    |URL for getting chat help (this will typically be your Slack channel for support).|`https://mycorp.slack.com/argo-cd` |
|`helpChatText`    |The text that appears in a text box for getting chat help.|`Chat now!`|
|`image`    |The container image for all Argo CD components. This overrides the `ARGOCD_IMAGE` environment variable.|`argoproj/argocd` |
|`ingress`    |Ingress configuration options.| `__<object>__` |
|`initialRepositories`    |Initial Git repositories to configure Argo CD to use upon creation of the cluster.|`__<empty>__` |

|`notifications`    |Notifications controller configuration options.|`__<object>__`
a|* _<enabled>_ - The toggle to start the notifications-controller.
  * _<image>_ - The container image for all Argo CD components. This overrides the `ARGOCD_IMAGE` environment variable.
  * _<version>_ - The tag to use with the Notifications container image.
  * _<resources>_ - The container compute resources.
  * _<logLevel>_ - The log level used by the Argo CD Application Controller component. Valid options are `debug`, `info`, `error`, and `warn`.

|`repositoryCredentials`    |Git repository credential templates to configure Argo CD to use upon creation of the cluster.| `__<empty>__` |

|`initialSSHKnownHosts`    |Initial SSH Known Hosts for Argo CD to use upon creation of the cluster.| `__<default_Argo_CD_Known_Hosts>__` |

|`kustomizeBuildOptions`    |The build options and parameters to use with `kustomize build`.|`__<empty>__` |

|`oidcConfig` |The OIDC configuration as an alternative to Dex.|`__<empty>__` |

|`nodePlacement` |Add the `nodeSelector` and the `tolerations`.|`__<empty>__` |

|`prometheus` |Prometheus configuration options.|`__<object>__`
a|* _<enabled>_ - Toggle Prometheus support globally for Argo CD.
  * _<host>_ - The hostname to use for Ingress or Route resources.
  * _<ingress>_ - Toggles Ingress for Prometheus.
  * _<route>_ - Route configuration options.
  * _<size>_ - The replica count for the Prometheus `StatefulSet`.

|`rbac` |RBAC configuration options.|`__<object>__`
a|* _<defaultPolicy>_ - The `policy.default` property in the `argocd-rbac-cm` config map. The name of the default role which Argo CD falls back to when authorizing API requests.
  * _<policy>_ - The `policy.csv` property in the `argocd-rbac-cm` config map. CSV data containing user-defined RBAC policies and role definitions.
  * _<scopes>_ - The scopes property in the `argocd-rbac-cm` config map. Controls which OIDC scopes to examine during RBAC enforcement (in addition to sub scope).

|`redis` |Redis configuration options.|`__<object>__`
a|* _<autotls>_ - Use the provider to create the Redis server's TLS certificate. Only the `openshift` value is currently available.
  * _<disableTLSVerification>_ - Defines whether the Redis server should be accessed using strict TLS validation.
  * _<image>_ - The container image for Redis. This overrides the `ARGOCD_REDIS_IMAGE` environment variable.
  * _<resources>_ - The container compute resources.
  * _<version>_ - The tag to use with the Redis container image.
|`resourceCustomizations` |Customize resource behavior.|`__<empty>__` |
|`resourceExclusions` |Completely ignore entire classes of resource group.|`__<empty>__` |
|`resourceInclusions` |The configuration to configure which resource group/kinds are applied.|`__<empty>__` |

|`server` |Argo CD Server configuration options.|`__<object>__`
a|* _<autoscale>_ - Server autoscale configuration options.
  * _<extraCommandArgs>_ - List of arguments added to the existing arguments set by the Operator.
  * _<grpc>_ - gRPC configuration options.
  * _<host>_ - The hostname used for Ingress or Route resources.
  * _<ingress>_ - Ingress configuration for the Argo CD server component.
  * _<insecure>_ - Toggles the insecure flag for Argo CD server.
  * _<resources>_ - The container compute resources.
  * _<replicas>_ - The number of replicas for the Argo CD server. Must be greater than or equal to `0`. If `autoscale` is enabled, `replicas` is ignored.
  * _<route>_ - Route configuration options.
  * _<service.Type>_ - The `serviceType` used for the service resource.
  * _<logLevel>_ - The log level to be used by the Argo CD Server component. Valid options are  `debug`, `info`, `error`, and `warn`.
  * _<logFormat>_ - The log format used by the Argo CD Application Controller component. Valid options are `text` or `json`.
  * _<env>_ - Environment to set for the server workloads.
=======
|*Name* |*Description* |*Default* | *Properties*
|`ApplicationInstanceLabelKey` |The `metadata.label` key name where Argo CD injects the app name as a tracking label.|`app.kubernetes.io/instance` |
|`ApplicationSet` 
|`ApplicationSet` controller configuration options.
| `_<Object>_`
a|* _<Image>_ - The container image for the `ApplicationSet` controller. This overrides the `ARGOCD_APPLICATIONSET_IMAGE` environment variable.
  * _<Version>_ - The tag to use with the `ApplicationSet` container image.
  * _<Resources>_ - The container compute resources.
  * _<LogLevel>_ - The log level used by the Argo CD Application Controller component. Valid options are `debug`, `info`, `error`, and `warn`.
  * _<LogFormat>_ - The log format used by the Argo CD Application Controller component. Valid options are `text` or `json`.
  * _<PrallelismLimit>_ - The kubectl parallelism limit to set for the controller `(--kubectl-parallelism-limit flag)`.
|`ConfigManagementPlugins`    |Add a configuration management plugin.| `__<empty>__` |
|`Controller`    |Argo CD Application Controller options.| `__<Object>__`
a|* _<Processors.Operation>_ - The number of operation processors.
  * _<Processors.Status>_ - The number of status processors.
  * _<Resources>_ - The container compute resources.
  * _<LogLevel>_ - The log level used by the Argo CD Application Controller component. Valid options are `debug`, `info`, `error`, and `warn`.
  * _<AppSync>_ - AppSync is used to control the sync frequency of Argo CD applications
  * _<Sharding.enabled>_ - Enable sharding on the Argo CD Application Controller component. This property is used to manage a large number of clusters to relieve memory pressure on the controller component.
  * _<Sharding.replicas>_ - The number of replicas that will be used to support sharding of the Argo CD Application Controller.
  * _<Env>_ - Environment to set for the application controller workloads.
|`DisableAdmin`    |Disables the built-in admin user.|`false` |
|`GATrackingID`    |Use a Google Analytics tracking ID.|`__<empty>__` |
|`GAAnonymizeusers`    |Enable hashed usernames sent to google analytics.|`false` |
|`HA`    |High availablity options.| `__<Object>__`
a|* _<Enabled>_ - Toggle high availability support globally for Argo CD.
  * _<RedisProxyImage>_ - The Redis HAProxy container image. This overrides the `ARGOCD_REDIS_HA_PROXY_IMAGE` environment variable.
  * _<RedisProxyVersion>_ - The tag to use for the Redis HAProxy container image.
|`HelpChatURL`    |URL for getting chat help (this will typically be your Slack channel for support).|`https://mycorp.slack.com/argo-cd` |
|`HelpChatText`    |The text that appears in a text box for getting chat help.|`Chat now!`|
|`Image`    |The container image for all Argo CD components. This overrides the `ARGOCD_IMAGE` environment variable.|`argoproj/argocd` |
|`Ingress`    |Ingress configuration options.| `__<Object>__` |
|`InitialRepositories`    |Initial Git repositories to configure Argo CD to use upon creation of the cluster.|`__<empty>__` |
|`Notifications`    |Notifications controller configuration options.|`__<Object>__`
a|* _<Enabled>_ - The toggle to start the notifications-controller.
  * _<Image>_ - The container image for all Argo CD components. This overrides the `ARGOCD_IMAGE` environment variable.
  * _<Version>_ - The tag to use with the Notifications container image.
  * _<Resources>_ - The container compute resources.
  * _<LogLevel>_ - The log level used by the Argo CD Application Controller component. Valid options are `debug`, `info`, `error`, and `warn`.
|`RepositoryCredentials`    |Git repository credential templates to configure Argo CD to use upon creation of the cluster.| `__<empty>__` |
|`InitialSSHKnownHosts`    |Initial SSH Known Hosts for Argo CD to use upon creation of the cluster.| `__<default_Argo_CD_Known_Hosts>__` |
|`KustomizeBuildOptions`    |The build options and parameters to use with `kustomize build`.|`__<empty>__` |
|`OIDCConfig` |The OIDC configuration as an alternative to Dex.|`__<empty>__` |
|`NodePlacement` |Add the `nodeSelector` and the `tolerations`.|`__<empty>__` |
|`Prometheus` |Prometheus configuration options.|`__<Object>__`
a|* _<Enabled>_ - Toggle Prometheus support globally for Argo CD.
  * _<Host>_ - The hostname to use for Ingress or Route resources.
  * _<Ingress>_ - Toggles Ingress for Prometheus.
  * _<Route>_ - Route configuration options.
  * _<Size>_ - The replica count for the Prometheus `StatefulSet`.
|`RBAC` |RBAC configuration options.|`__<Object>__`
a|* _<DefaultPolicy>_ - The `policy.default` property in the `argocd-rbac-cm` config map. The name of the default role which Argo CD will fall back to, when authorizing API requests.
  * _<Policy>_ - The `policy.csv` property in the `argocd-rbac-cm` config map. CSV data containing user-defined RBAC policies and role definitions.
  * _<Scopes>_ - The scopes property in the `argocd-rbac-cm` config map. Controls which OIDC scopes to examine during RBAC enforcement (in addition to sub scope).
|`Redis` |Redis configuration options.|`__<Object>__`
a|* _<AutoTLS>_ - Use the provider to create the Redis server's TLS certificate (one of: openshift). Currently only available for {OCP}.
  * _<DisableTLSVerification>_ - Define whether the Redis server should be accessed using strict TLS validation.
  * _<Image>_ - The container image for Redis. This overrides the `ARGOCD_REDIS_IMAGE` environment variable.
  * _<Resources>_ - The container compute resources.
  * _<Version>_ - The tag to use with the Redis container image.
|`ResourceCustomizations` |Customize resource behavior.|`__<empty>__` |
|`ResourceExclusions` |Completely ignore entire classes of resource group.|`__<empty>__` |
|`ResourceInclusions` |The configuration to configure which resource group/kinds are applied.|`__<empty>__` |
|`Server` |Argo CD Server configuration options.|`__<Object>__`
a|* _<Autoscale>_ - Server autoscale configuration options.
  * _<ExtraCommandArgs>_ - List of arguments added to the existing arguments set by the Operator.
  * _<GRPC>_ - GRPC configuration options.
  * _<Host>_ - The hostname used for Ingress or Route resources.
  * _<Ingress>_ - Ingress configuration for the Argo CD server component.
  * _<Insecure>_ - Toggles the insecure flag for Argo CD server.
  * _<Resources>_ - The container compute resources.
  * _<Replicas>_ - The number of replicas for the Argo CD server. Must be greater than or equal to `0`. If `Autoscale` is enabled, `Replicas` is ignored.
  * _<Route>_ - Route configuration options.
  * _<Service.Type>_ - The `ServiceType` used for the service resource.
  * _<LogLevel>_ - The log level to be used by the Argo CD Server component. Valid options are  `debug`, `info`, `error`, and `warn`.
  * _<LogFormat>_ - The log format used by the Argo CD Application Controller component. Valid options are `text` or `json`.
  * _<Env>_ - Environment to set for the server workloads.
|`SSO` |Single Sign-on options.|`__<Object>__`
a|* _<Image>_ - The container image for Keycloak. This overrides the `ARGOCD_KEYCLOAK_IMAGE` environment variable.
  * _<Keycloak>_ - Configuration options for Keycloak SSO provider.
  * _<Dex>_ - Configuration options for Dex SSO provider.
  * _<Provider>_ - The name of the provider used to configure Single Sign-on. For now the supported options are Dex and Keycloak.
  * _<Resources>_ - The container compute resources.
  * _<VerifyTLS>_ - Whether to enforce strict TLS checking when communicating with Keycloak service.
  * _<Version>_ - The tag to use with the Keycloak container image.
|`StatusBadgeEnabled` |Enable application status badge.|`true` |
|`TLS` |TLS configuration options.|`__<Object>__`
a|* _<CA.ConfigMapName>_ - The name of the `ConfigMap` which contains the CA certificate.
  * _<CA.SecretName>_ - The name of the secret which contains the CA Certificate and Key.
  * _<InitialCerts>_ - Initial set of certificates in the `argocd-tls-certs-cm` config map for connecting Git repositories via HTTPS.
|`UserAnonyousEnabled` |Enable anonymous user access.|`true` |
|`Version` |The tag to use with the container image for all Argo CD components.|Latest Argo CD version|
|`Banner` |Add a UI banner message.|`__<Object>__`
a|* _<Banner.Content>_ - The banner message content (required if a banner is displayed).
  * _<Banner.URL.SecretName>_ - The banner message link URL (optional). 
|===
>>>>>>> 4016f704dee42cab6342829485bac106457d7b19

|`sso` |Single Sign-on options.|`__<object>__`
proa|* _<image>_ - The container image for Keycloak. This overrides the `ARGOCD_KEYCLOAK_IMAGE` environment variable.
  * _<keycloak>_ - Configuration options for Keycloak SSO provider.
  * _<dex>_ - Configuration options for Dex SSO provider.
  * _<provider>_ - The name of the provider used to configure Single Sign-on. For now the supported options are Dex and Keycloak.
  * _<resources>_ - The container compute resources.
  * _<verifyTLS>_ - Defines whether to enforce strict TLS checking when communicating with Keycloak service.
  * _<version>_ - The tag to use with the Keycloak container image.
|`statusBadgeEnabled` |Enable application status badge.|`true` |

|`tls` |TLS configuration options.|`__<object>__`
a|* _<ca.configMapName>_ - The name of the `ConfigMap` which contains the CA certificate.
  * _<ca.secretName>_ - The name of the secret which contains the CA Certificate and Key.
  * _<initialCerts>_ - Initial set of certificates in the `argocd-tls-certs-cm` config map for connecting Git repositories via HTTPS.
|`usersAnonymousEnabled` |Enable anonymous user access.|`true` |
|`version` |The tag to use with the container image for all Argo CD components.|Latest Argo CD version|

|`banner` |Add a UI banner message.|`__<object>__`
a|* _<banner.content>_ - The banner message content (required if a banner is displayed).
  * _<banner.url.secretName>_ - The banner message link URL (optional).
|===