// Module included in the following assembly:
//
// * release_notes/gitops-release-notes-1-19.adoc

:_mod-docs-content-type: REFERENCE

[id="gitops-release-notes-1-19-2_{context}"]
= Release notes for {gitops-title} 1.19.2

{gitops-title} 1.19.2 is now available on {OCP} 4.14, 4.16, 4.17, 4.18, 4.19, 4.20, and 4.21.

[id="errata-updates-1-19-2_{context}"]
== Errata updates

[id="RHSA-2026:3884-gitops-1-19-1-security-update-advisory_{context}"]
=== RHSA-2026:3884 - {gitops-title} 1.19.1 security update advisory

Issued: 2026-03-05

The list of security fixes that are included in this release is documented in the following advisory:

* link:https://access.redhat.com/errata/RHSA-2026:3884[RHSA-2026:3884]

If you have installed the {gitops-title} Operator in the default namespace, run the following command to view the container images in this release:

[source,terminal]
----
$ oc describe deployment gitops-operator-controller-manager -n openshift-gitops-operator
----

[id="fixed-issues-1-19-2_{context}"]
== Fixed issues

ImageUpdater spec.namespace field is deprecated::
Before this update, the `spec.namespace` field in the `ImageUpdater` Custom Resource (CR) specified the namespace where the controller searched for target applications. With this update, the `spec.namespace` field is deprecated and will be removed in a future release. The controller now uses the `metadata.namespace` of the `ImageUpdater` resource to identify target applications. As a result, operations are restricted to the local namespace. You must create `ImageUpdater` resources in the same namespace as the applications they manage; configurations where these namespaces differ are no longer supported.
+
link:https://issues.redhat.com/browse/GITOPS-8876[GITOPS-8876]

ApplicationSet controller permissions updated for AppProjects::
Before this update, the `ApplicationSet` controller lacked permission to list AppProject resources at the cluster scope. As a result, reconciliation failed when `ApplicationSet` resources were created in namespaces other than the default Argo CD namespace. With this release, the controller ClusterRole is updated to include the required permissions for `appprojects.argoproj.io`. This change aligns the configuration with the upstream version and enables the `ApplicationSet` controller to generate applications across all namespaces in the cluster successfully.
+
link:https://issues.redhat.com/browse/GITOPS-8922[GITOPS-8922]