// Module included in the following assembly:
//
// * release_notes/gitops-release-notes-1-19.adoc

:_mod-docs-content-type: REFERENCE

[id="gitops-release-notes-1-19-6_{context}"]
= Release notes for {gitops-title} 1.19.6

[role="_abstract"]

{gitops-title} 1.19.6 is available on {OCP} 4.14, 4.16, 4.17, 4.18, 4.19, 4.20, and 4.21.

[id="errata-updates-1-19-6_{context}"]
== Errata updates

[id="RHSA-2026:52857-gitops-1-19-6-security-update-advisory_{context}"]
=== RHSA-2026:52857 - {gitops-title} 1.19.6 security update advisory

Issued: 2026-08-10

The list of security fixes that are included in this release is documented in the following advisory:

* link:https://access.redhat.com/errata/RHSA-2026:52857[RHSA-2026:52857]

If you have installed the {gitops-title} Operator in the default namespace, run the following command to view the container images in this release:

[source,terminal,subs="+quotes"]
----
$ oc describe deployment openshift-gitops-operator-controller-manager -n openshift-gitops-operator
----

[id="enhancements-1-19-6_{context}"]
== New Features and Enhancements

Network policies for Argo CD workload pods::
With this update, {gitops-title} creates Kubernetes `NetworkPolicy` resources for Argo CD workload pods to restrict unnecessary ingress and egress traffic. These network policies provide a least-privilege network security posture for Argo CD components. To disable this feature, set the `spec.networkPolicy.enabled` field to `false`.
+
[WARNING]
====
Disabling network policies removes network-level access restrictions for Argo CD components and can increase the attack surface of your cluster. Do not disable network policies in production or security-sensitive environments unless you have alternative network security measures in place.
====
+
link:https://redhat.atlassian.net/browse/GITOPS-10402[GITOPS-10402]
