// Module included in the following assembly:
//
// * argocd-agent-installation/gitops-deploy-argocd-application-in-managed-mode.adoc

:_mod-docs-content-type: PROCEDURE
[id="gitops-deploy-argocd-application-in-managed-mode_{context}"]
= Deploying an Argo CD application in managed mode

In managed agent mode, the *hub* acts as the source of truth. Argo CD applications must be created in the hub cluster. The agent creates and manages the application in the spoke cluster based on the configuration defined in the hub.

.Procedure

. Create the Argo CD Application manifest file, `application.yaml`, with the following configuration:
+
[source,yaml]
----
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-demo-app
  namespace: agent-managed # Namespace created for agent in hub
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-developer/openshift-gitops-getting-started
    targetRevision: HEAD
    path: app
  destination:
    name: agent-managed # Name given to the agent in hub  
    namespace: my-app
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
   managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
    - CreateNamespace=true
----

. Apply the configuration in the hub cluster by running the following command:
+
[source,terminal]
----
$ oc apply -f application.yaml -n agent-managed --context "<PRINCIPAL_CONTEXT>"
----

. To verify that the application is created in the spoke cluster, run the following command:
+
[source,terminal]
----
$ oc get application.argoproj.io/my-demo-app -n openshift-gitops --context "<AGENT_CONTEXT>"
----

. To check that the application is synced and healthy from the hub, run the following command:
+
[source,terminal]
----
$ oc get application.argoproj.io/my-demo-app -n agent-managed --context "<PRINCIPAL_CONTEXT>"
----

.Verification

If the configuration is correct, the agent creates the application and its associated resources in the spoke cluster.
Because the hub is the source of truth, any direct changes made in the spoke cluster are automatically reverted by the agent.