// Module included in the following assembly:
//
// * declarative_clusterconfig/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.adoc

:_mod-docs-content-type: PROCEDURE
[id="configuring-respectRBAC-using-the-web-UI_{context}"]
= Configuring respectRBAC by using the web console

You can configure `respectRBAC` in the web console.

.Procedure

. Log in to the {OCP} web console. 

. In the *Administrator* perspective of the web console, click *Operators* -> *Installed Operators*.

. Create or select the project where you want to install the user-defined Argo CD instance from the *Project* list.

. Select *{gitops-title}* from the installed Operators list and click the *Argo CD* tab.

. Configure the `respectRBAC` parameter in the *Argo CD* tab.
+
[source,yaml]
----
spec:
  controller:
    respectRBAC: strict
----

. Click *Create*.
+
After successful installation, verify that the Argo CD instance is listed under the *Argo CD* tab and the *Status* is *Available*.

. After the Argo CD instance is created, verify that the `resource.respectRBAC` parameter in the `ConfigMap` resource is updated successfully by completing the following steps.

.. In the *Administrator* perspective, go to *Workload* -> *ConfigMaps*.
.. In the *Project* option, select the *Argo CD* namespace.
.. Select the `argocd-cm` config map.
.. Select the *YAML* tab to view the `resource.respectRBAC` parameter.