// Module included in the following assembly:
//
// * declarative_clusterconfig/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.adoc

:_mod-docs-content-type: PROCEDURE
[id="gitops-configuring-respect-rbac-using-gitops_{context}"]
= Configuring respectRBAC using {gitops-title}

[role="_abstract"]
The `respectRBAC` feature in Argo CD controls how Argo CD watches resources on a cluster. By default, Argo CD attempts to watch all Kubernetes resources (CRDs) on a cluster at the cluster scope. With the `respectRBAC` feature, you can restrict the ArgoCD controller from discovering or syncing specific resources using only controller RBAC, without manually configuring resource exclusions.

To enable this feature, set the `.spec.controller.respectRBAC` key in the Argo CD resource. After you set this key, the controller automatically stops watching resources it cannot list or access. For example, this prevents a situation where the Argo CD cluster role restricts Argo CD from watching OpenShift Routes, which would otherwise result in an error during synchronization, stating that it cannot watch the resource.

You can enable the `respectRBAC` feature by creating an Argo CD instance through the command-line interface (CLI) or the web console.

.Prerequisites

Ensure that you created and updated a namespace in the `Subscription` resource, so `Subscription` can host a cluster-scoped Argo CD instance. For more information, see "Using an Argo CD instance to manage cluster-scoped resources".

[id="configuring-respectRBAC-using-the-cli_{context}"]
== Configuring respectRBAC using the CLI

You can configure the `respectRBAC` feature by using the CLI.

.Procedure

. Create a YAML object file, for example, `argo-cd-resource.yaml`, to configure the `respectRBAC` feature: 
+
.Example `ArgoCD` YAML to create `respectRBAC` 
[source,yaml]
----
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: example-argocd #<1>
spec:
  controller:
    respectRBAC: strict #<2>
----
<1> Specify the name of the Argo CD instance.
<2> You can specify the value of the `.spec.controller.respectRBAC` key in the `ArgoCD` resource as `normal` or `strict`. Consider setting a value as `normal` to balance accuracy and speed as resource listing is a lightweight operation. Set the value as `strict` if Argo CD reports errors indicating that it cannot access resources when you set the value as `normal`.  Setting `strict` increases the number of API calls to the server and it is more accurate compared to `normal` as Argo CD performs additional validations of RBAC resources to determine permissions.

. Apply the changes to the YAML file by running the following command.
+
[source,terminal]
----
$ oc apply -f argocd-resource.yaml -n argo-cd-instance #<1>
----
<1> Specify the name of the YAML file that includes the `ArgoCD` resource and the namespace that hosts `ArgoCD`.
+
. Verify that the status of the `.status.phase` field is `Available` by running the following command:
+
[source,terminal]
----
$ oc get argocd <argocd_instance_name> -n <argocd_namespace> -o jsonpath='{.status.phase}' #<1>
----
<1> Replace `<argocd_instance_name>` with the name of your Argo CD instance for example, `example-argocd`.

. Verify that the `resource.respectRBAC` parameter in the `ConfigMap` resource is updated successfully:
.. To retrieve the contents of the `argocd-cm` config map, run the following command:
+
[source,terminal]
----
$ oc get cm argocd-cm -n <argocd_namespace> -o yaml
----
.. Verify that the `argocd-cm` `ConfigMap` contains the `resource.respectRBAC` parameter and ensure its value is set to either `strict` or `normal`.

[id="configuring-respectRBAC-using-the-web-UI_{context}"]
== Configuring respectRBAC by using the web console

You can configure `respectRBAC` in the web console.

.Procedure

. Log in to the {OCP} web console. 

. In the *Administrator* perspective of the web console, click *Operators* -> *Installed Operators*.

. Create or select the project where you want to install the user-defined Argo CD instance from the *Project* list.

. Select *{gitops-title}* from the installed Operators list and click the *Argo CD* tab.

. Configure the `respectRBAC` parameter in the *Argo CD* tab.
+
[source,yaml]
----
spec:
  controller:
    respectRBAC: strict
----

. Click *Create*.
+
After successful installation, verify that the Argo CD instance is listed under the *Argo CD* tab and the *Status* is *Available*.

. After the Argo CD instance is created, verify that the `resource.respectRBAC` parameter in the `ConfigMap` resource is updated successfully by completing the following steps.

.. In the *Administrator* perspective, go to *Workload* -> *ConfigMaps*.
.. In the *Project* option, select the *Argo CD* namespace.
.. Select the `argocd-cm` config map.
.. Select the *YAML* tab to view the `resource.respectRBAC` parameter.