// Module included in the following assembly:
//
// * release_notes/gitops-release-notes-1-18.adoc

:_mod-docs-content-type: REFERENCE

[id="gitops-release-notes-1-18-5_{context}"]
= Release notes for {gitops-title} 1.18.5

[role="_abstract"]
{gitops-title} 1.18.5 is available on {OCP} 4.14, 4.16, 4.17, 4.18, 4.19, and 4.20.

[id="errata-updates-1-18-5_{context}"]
== Errata updates

[id="RHSA-2026:9697-gitops-1-18-5-security-update-advisory_{context}"]
=== RHSA-2026:9697 - {gitops-title} 1.18.5 security update advisory

Issued: 2026-04-22

The list of security fixes included in this release is available in the following advisory:

* link:https://access.redhat.com/errata/RHSA-2026:9697[RHSA-2026:9697]

If you have installed the {gitops-title} Operator in the default namespace, run the following command to view the container images in this release:

[source,terminal]
----
$ oc describe deployment openshift-gitops-operator-controller-manager -n openshift-gitops-operator
----

[id="fixed-issues-1-18-5_{context}"]
== Fixed issues

Pod Security label synchronization aligned with SCCs in the openshift-gitops namespace::
Before this update, the {gitops-title} Operator set static Pod Security labels on the `openshift-gitops` namespace. These labels could go out of sync with the cluster policy. With this release, the {gitops-title} Operator sets `security.openshift.io/scc.podSecurityLabelSync=true`. It no longer hard-codes `pod-security.kubernetes.io/*` labels on the namespace. OpenShift now synchronizes Pod Security labels from Security Context Constraints (SCCs). This ensures that labels stay aligned with cluster policy.
+
link:https://issues.redhat.com/browse/GITOPS-9158[GITOPS-9158]