// Module included in the following assemblies:
//
// * backup_and_restore/graceful-cluster-restart.adoc

:_mod-docs-content-type: PROCEDURE
[id="graceful-restart_{context}"]
= Restarting the cluster

[role="_abstract"]
You can restart the cluster after a graceful shutdown by powering on nodes, uncordoning schedulable nodes, and approving pending certificate signing requests (CSRs) if nodes are not ready. The cluster returns to normal operations after all nodes and Operators are healthy.

.Prerequisites

* You have access to the cluster as a user with the `cluster-admin` role.
* You have gracefully shut down your cluster.

If your cluster fails to recover, follow the steps in "Restoring to a previous cluster state".

.Procedure

. Turn on the control plane nodes.

** If you are using the `admin.kubeconfig` from the cluster installation and the API virtual IP address (VIP) is up, complete the following steps:

.. Set the `KUBECONFIG` environment variable to the `admin.kubeconfig` path.
.. Uncordon each control plane node in the cluster by running the following command:
+
[source,terminal]
----
$ oc adm uncordon <node>
----

** If you do not have access to your `admin.kubeconfig` credentials, complete the following steps:

.. Use SSH to connect to a control plane node.
.. Copy the `localhost-recovery.kubeconfig` file to the `/root` directory.
.. Use that file to uncordon each control plane node in the cluster by running the following command:
+
[source,terminal]
----
$ oc adm uncordon <node>
----

. Power on any cluster dependencies, such as external storage or a Lightweight Directory Access Protocol (LDAP) server.

. Start all cluster machines.
+
Use the appropriate method for your cloud environment to start the machines, for example, from the web console for your cloud provider.
+
Wait approximately 10 minutes before continuing to check the status of control plane nodes.

. Verify that all control plane nodes are ready by running the following command:
+
[source,terminal]
----
$ oc get nodes -l node-role.kubernetes.io/master
----
+
The control plane nodes are ready if the status is `Ready`, as shown in the following output:
+
[source,terminal]
----
NAME                           STATUS   ROLES                  AGE   VERSION
ip-10-0-168-251.ec2.internal   Ready    control-plane,master   75m   v1.33.4
ip-10-0-170-223.ec2.internal   Ready    control-plane,master   75m   v1.33.4
ip-10-0-211-16.ec2.internal    Ready    control-plane,master   75m   v1.33.4
----

. If the control plane nodes are not ready, then check whether there are any pending CSRs that must be approved.

.. Get the list of current CSRs by running the following command:
+
[source,terminal]
----
$ oc get csr
----

.. Review the details of each CSR to verify that it is valid by running the following command:
+
[source,terminal]
----
$ oc describe csr <csr_name>
----

.. Approve each valid CSR by running the following command:
+
[source,terminal]
----
$ oc adm certificate approve <csr_name>
----

. After the control plane nodes are ready, verify that all compute nodes are ready by running the following command:
+
[source,terminal]
----
$ oc get nodes -l node-role.kubernetes.io/worker
----
+
The worker nodes are ready if the status is `Ready`, as shown in the following output:
+
[source,terminal]
----
NAME                           STATUS   ROLES    AGE   VERSION
ip-10-0-179-95.ec2.internal    Ready    worker   64m   v1.33.4
ip-10-0-182-134.ec2.internal   Ready    worker   64m   v1.33.4
ip-10-0-250-100.ec2.internal   Ready    worker   64m   v1.33.4
----

. If the compute nodes are not ready, then check whether there are any pending CSRs that must be approved.

.. Get the list of current CSRs by running the following command:
+
[source,terminal]
----
$ oc get csr
----

.. Review the details of each CSR to verify the validity of the CSR by running the following command:
+
[source,terminal]
----
$ oc describe csr <csr_name>
----

.. Approve each valid CSR by running the following command:
+
[source,terminal]
----
$ oc adm certificate approve <csr_name>
----

. After the control plane and compute nodes are ready, mark all the nodes in the cluster as schedulable by running the following command:
+
[source,terminal]
----
$ for node in $(oc get nodes -o jsonpath='{.items[*].metadata.name}'); do echo ${node} ; oc adm uncordon ${node} ; done
----

. Verify that the cluster started properly.

.. Check that there are no degraded cluster Operators by running the following command:
+
[source,terminal]
----
$ oc get clusteroperators
----
+
.Example output
[source,terminal,subs="attributes+"]
----
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             {product-version}.0    True        False         False      59m
cloud-credential                           {product-version}.0    True        False         False      85m
cluster-autoscaler                         {product-version}.0    True        False         False      73m
config-operator                            {product-version}.0    True        False         False      73m
console                                    {product-version}.0    True        False         False      62m
csi-snapshot-controller                    {product-version}.0    True        False         False      66m
dns                                        {product-version}.0    True        False         False      76m
etcd                                       {product-version}.0    True        False         False      76m
...
----

.. Check that all nodes are in the `Ready` state by running the following command:
+
[source,terminal]
----
$ oc get nodes
----
+
.Example output
[source,terminal]
----
NAME                           STATUS   ROLES                  AGE   VERSION
ip-10-0-168-251.ec2.internal   Ready    control-plane,master   82m   v1.33.4
ip-10-0-170-223.ec2.internal   Ready    control-plane,master   82m   v1.33.4
ip-10-0-179-95.ec2.internal    Ready    worker                 70m   v1.33.4
ip-10-0-182-134.ec2.internal   Ready    worker                 70m   v1.33.4
ip-10-0-211-16.ec2.internal    Ready    control-plane,master   82m   v1.33.4
ip-10-0-250-100.ec2.internal   Ready    worker                 69m   v1.33.4
----
+
If the cluster did not start properly, follow the steps in "Restoring to a previous cluster state".
