// Module included in the following assemblies:
//
// * hosted_control_planes/hcp-deploy/hcp-deploy-aws.adoc
// * hosted_control_planes/hcp-deploy/hcp-deploy-azure.adoc
// * hosted_control_planes/hcp-deploy/hcp-deploy-bm.adoc
// * hosted_control_planes/hcp-deploy/hcp-deploy-non-bm.adoc
// * hosted_control_planes/hcp-deploy/hcp-deploy-ibm-power.adoc
// * hosted_control_planes/hcp-deploy/hcp-deploy-ibmz.adoc
// * hosted_control_planes/hcp-deploy/hcp-deploy-virt.adoc


:_mod-docs-content-type: CONCEPT
[id="hcp-cluster-capabilities_{context}"]
= Capabilities for hosted clusters

[role="_abstract"]
To reduce resource consumption and prevent unnecessary Operators and operands from being deployed, administrators can enable or disable optional {product-title} components when they create a hosted cluster.

When capabilities are not specified on a `HostedCluster` resource, the cluster uses the {product-title} version's `DefaultCapabilitySet` settings, excluding the `baremetal` capability. As a result, most optional components are enabled by default. 

[IMPORTANT]
====
Capabilities are immutable after cluster creation. You cannot change them after you create the `HostedCluster` resource.
====