// Module included in the following assemblies:
//
// * hosted_control_planes/hcp-deploy/hcp-deploy-aws.adoc

:_mod-docs-content-type: PROCEDURE
[id="hcp-aws-deploy-hc_{context}"]
= Creating a hosted cluster on {aws-short}

[role="_abstract"]
Create a hosted cluster on {aws-first} by using the hosted control plane command-line interface (`hcp`). 

A _hosted cluster_ is an {product-title} cluster with its API endpoint and control plane that are hosted on a management cluster. The hosted cluster includes the control plane and its corresponding data plane.

The hosted cluster is automatically imported as a managed cluster. If you want to disable this automatic import feature, see "Disabling the automatic import of hosted clusters into {mce-short}".

By default for {hcp} on {aws-short}, you use an AMD64 hosted cluster. However, you can enable {hcp} to run on an ARM64 hosted cluster. For more information, see "Running hosted clusters on an ARM64 architecture".

For compatible combinations of node pools and hosted clusters, see the following table:

.Compatible architectures for node pools and hosted clusters
[cols="2,2",options="header"]
|===
| Hosted cluster | Node pools
| AMD64 | AMD64 or ARM64
| ARM64 | ARM64 or AMD64
|===

.Prerequisites

* You have set up the hosted control plane CLI, `hcp`.

* You have enabled the `local-cluster` managed cluster as the management cluster.

* You created an {aws-short} Identity and Access Management (IAM) role and {aws-short} Security Token Service (STS) credentials.

.Procedure

. To create a hosted cluster on {aws-short}, run the following command:
+
[source,terminal]
----
$ hcp create cluster aws \
    --name <hosted_cluster_name> \
    --infra-id <infra_id> \
    --base-domain <basedomain> \
    --sts-creds <path_to_sts_credential_file> \
    --pull-secret <path_to_pull_secret> \
    --region <region> \
    --generate-ssh \
    --node-pool-replicas <node_pool_replica_count> \
    --namespace <hosted_cluster_namespace> \
    --role-arn <role_name> \
    --render-into <file_name>.yaml
----
+
where:

`<hosted_cluster_name>`:: Specifies the name of your hosted cluster.
`<infra_id>`:: Specifies your infrastructure name. You must provide the same value for `<hosted_cluster_name>` and `<infra_id>`. Otherwise the cluster might not appear correctly in the {mce} console.
`<basedomain>`:: Specifies your base domain, for example, `example.com`.
`<path_to_sts_credential_file>`:: Specifies the path to your AWS STS credentials file, for example, `/home/user/sts-creds/sts-creds.json`.
`<path_to_pull_secret>`:: Specifies the path to your pull secret, for example, `/user/name/pullsecret`.
`<region>`:: Specifies the AWS region name, for example, `us-east-1`.
`<node_pool_replica_count>`:: Specifies the node pool replica count, for example, `3`.
`<hosted_cluster_namespace>`:: Specifies that you want to create the `HostedCluster` and `NodePool` custom resource in a specific namespace. Otherwise, by default, all `HostedCluster` and `NodePool` custom resources are created in the `clusters` namespace.
`<role_name>`:: Specifies the Amazon Resource Name (ARN), for example, `arn:aws:iam::820196288204:role/myrole`.
`<file_name>`:: Specifies whether the EC2 instance runs on shared or single tenant hardware. The `--render-into` flag renders Kubernetes resources into the YAML file that you specify in this field. Continue to the next step to edit the YAML file.

. If you included the `--render-into` flag in the previous command, edit the specified YAML file. Edit the `NodePool` specification in the YAML file to indicate whether the EC2 instance should run on shared or single-tenant hardware, similar to the following example:
+
.Example YAML file
[source,yaml]
----
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: <nodepool_name>
spec:
  platform:
    aws:
      placement:
        tenancy: "default"
----
+
where:

`<nodepool_name>`:: Specifies the name of the `NodePool` resource.
`spec.platform.aws.placement.tenancy`:: Specifies a valid value for tenancy: `"default"`, `"dedicated"`, or `"host"`. Use `"default"` when node pool instances run on shared hardware. Use `"dedicated"` when each node pool instance runs on single-tenant hardware. Use `"host"` when node pool instances run on your pre-allocated dedicated hosts.

. If you use external load balancers, configure the ingress endpoint by editing the `HostedCluster` resource as shown in the following example. If you do not configure the endpoint, the default behavior is to randomize the node port that the service exposes the ingress on. To configure how the ingress controller publishes the default ingress route, set the `endpointPublishingStrategy` parameter and its underlying functions:
+
[source,yaml]
----
#...
spec:
  operatorConfiguration:
    ingressOperator:
      endpointPublishingStrategy:
        type: LoadBalancerService
        loadBalancer:
          scope: Internal
#...
----
+
The `spec.operatorConfiguration.ingressOperator.endPointPublishingStrategy.type` parameter specifies the endpoint for the load balancer. For {aws-short}, use the `LoadBalancerService` type.

.Verification

. Verify the status of your hosted cluster to check that the value of `AVAILABLE` is `True`. Run the following command:
+
[source,terminal]
----
$ oc get hostedclusters -n <hosted_cluster_namespace>
----

. Get a list of your node pools by running the following command:
+
[source,terminal]
----
$ oc get nodepools --namespace <hosted_cluster_namespace>
----