// Module included in the following assemblies:
//
// * hosted-control-planes/hcp-updating.adoc

:_mod-docs-content-type: CONCEPT
[id="hosted-control-planes-upgrading-requirements_{context}"]
= Requirements to upgrade {hcp}

The {mce} can manage one or more {product-title} clusters. After you create a hosted cluster on {product-title}, you must import your hosted cluster in the {mce-short} as a managed cluster. Then, you can use the {product-title} cluster as a management cluster.

Consider the following requirements before you start updating {hcp}:

* You must use the bare metal platform for an {product-title} cluster when using {VirtProductName} as a provider.

* You must use bare metal or {VirtProductName} as the cloud platform for the hosted cluster. You can find the platform type of your hosted cluster in the `spec.Platform.type` specification of the `HostedCluster` custom resource (CR).

You must upgrade the {product-title} cluster, {mce-short}, hosted cluster, and node pools by completing the following tasks:

. Upgrade an {product-title} cluster to the latest version. For more information, see "Updating a cluster using the web console" or "Updating a cluster using the CLI".
. Upgrade the {mce-short} to the latest version. For more information, see "Updating installed Operators".
. Upgrade the hosted cluster and node pools from the previous {product-title} version to the latest version. For more information, see "Updating a control plane in a hosted cluster" and "Updating node pools in a hosted cluster".
