//Module included in the following assemblies:
// hosted_control_planes/hcp-deploy/hcp-deploy-azure.adoc

:_mod-docs-content-type: PROCEDURE
[id="hcp-azure-workload-delete_{context}"]
= Deleting {azure-short} Workload Identities

[role="_abstract"]
As part of the process to delete a hosted cluster on {azure-short}, you need to delete the Workload Identities.

To delete the Workload Identities, you enter a command on the {hcp} command-line interface, `hcp`. The command uses the file that was generated when you created the Workload Identities to identify the identities to delete. Both the managed identities and their federated credentials are removed.

.Prerequisites

* If you created infrastructure by using the Workload Identities, delete the infrastructure before you delete the identities.

.Procedure

* Enter the following command:
+
[source,terminal]
----
$ hcp destroy iam azure \
    --azure-creds <azure_credentials_file> \
    --workload-identities-file <workload_identities_file> \
    --resource-group-name <resource_group> \
    --name <my_cluster_name> \
    --infra-id <infra_id> \
    --dns-zone-rg-name <dns_zone_rg> \
    --cloud <my_cloud_environment>
----
+
where:
+
`<azure_credentials_file>`:: Specifies the {azure-short} credentials file with permission to create managed identities and federated credentials.
`<workload_identities_file>`:: Specifies the path to the Workload Identities JSON file, such as `my-cluster-name-iam-output.json`.
`<resource_group>`:: Specifies the name of the resource group where you created identities.
`<my_cluster_name>`:: Specifies the name of your hosted cluster.
`<infra_id>`:: Specifies the unique identifier for naming {azure-short} resources. Typically, this identifier is the cluster name with a suffix.
`<dns_zone_rg>`:: Specifies the DNS zone resource group. 
+
Optionally, you can also specify the `--cloud` flag to set the {azure-short} cloud environment. The default value is `AzurePublicCloud`.

