// Module included in the following assemblies:
// * edge_computing/image_base_install/ibi-understanding-image-based-install.adoc

:_mod-docs-content-type: CONCEPT
[id="ibi-image-based-deployment-overview_{context}"]
= Image-based deployment for {sno} clusters

[role="_abstract"]
You can use the `openshift-install` program or the IBI Operator to configure and deploy a host that you preinstalled with an image-based installation.

{sno-caps} cluster deployment::

To configure the target host with site-specific details by using the `openshift-install` program, you must create the following resources:
+
--
* The `install-config.yaml` installation manifest

* The `image-based-config.yaml` manifest
--
+
The `openshift-install` program uses these resources to generate a configuration ISO that you attach to the preinstalled target host to complete the deployment.

Managed {sno} cluster deployment::

{rh-rhacm-first} and the {mce} (MCE) use a hub-and-spoke architecture to manage and deploy {sno} clusters across multiple sites. Using this approach, the hub cluster serves as a central control plane that manages the spoke clusters, which are often remote {sno} clusters deployed at the far edge of the network.
+
You can define the site-specific configuration resources for an image-based deployment in the hub cluster. The IBI Operator uses these configuration resources to reconfigure the preinstalled host at the remote site and deploy the host as a managed {sno} cluster. This approach is especially beneficial for telecommunications providers and other service providers with extensive, distributed infrastructures, where an end-to-end installation at the remote site would be time-consuming and costly.
+
The following is a high-level overview of the image-based deployment process for hosts preinstalled with an imaged-based installation:
+
--
* Define the site-specific configuration resources for the preinstalled host in the hub cluster.
* Apply these resources in the hub cluster. This initiates the deployment process.
* The IBI Operator creates a configuration ISO.
* The IBI Operator boots the target preinstalled host with the configuration ISO attached.
* The host mounts the configuration ISO and begins the reconfiguration process.
* When the reconfiguration completes, the {sno} cluster is ready.
--
+
As the host is already preinstalled using an image-based installation, a technician can reconfigure and deploy the host in a matter of minutes.
