// Module included in the following assemblies:
//
// * edge_computing/ibi-image-based-install.adoc 

:_mod-docs-content-type: PROCEDURE
[id="ibi-install-lcao-console_{context}"]
= Installing the {lcao} by using the web console

You can use the {product-title} web console to install the {lcao} from the 4.15 Operator catalog.

.Prerequisites

* Log in as a user with `cluster-admin` privileges.

.Procedure

. In the {product-title} web console, navigate to *Operators* → *OperatorHub*.
. Search for the *{lcao}* from the list of available Operators, and then click *Install*.
. On the *Install Operator* page, under *A specific namespace on the cluster* select *openshift-lifecycle-agent*. Then, click Install.
. Click *Install*.

.Verification

To confirm that the installation is successful:

. Navigate to the *Operators* → *Installed Operators* page.
. Ensure that the {lcao} is listed in the *openshift-lifecycle-agent* project with a *Status* of *InstallSucceeded*.

[NOTE]
====
During installation an Operator might display a *Failed* status. If the installation later succeeds with an *InstallSucceeded* message, you can ignore the *Failed* message.
====

If the Operator is not installed successfully:

. Go to the *Operators* → *Installed Operators* page and inspect the *Operator Subscriptions* and *Install Plans* tabs for any failure or errors under *Status*.
. Go to the *Workloads* → *Pods* page and check the logs for pods in the *openshift-lifecycle-agent* project.