// Module included in the following assemblies:
//
// * images/using_images/images-other-jenkins.adoc

[id="images-other-jenkins-config-kubernetes_{context}"]
= Configuring the Jenkins Kubernetes plug-in

The {product-title} Jenkins image includes the pre-installed
https://wiki.jenkins-ci.org/display/JENKINS/Kubernetes+Plugin[Kubernetes
plug-in] that allows Jenkins agents to be dynamically provisioned on multiple
container hosts using Kubernetes and {product-title}.

To use the Kubernetes plug-in, {product-title} provides images that are suitable
for use as Jenkins agents: the `Base`, `Maven`, and `Node.js` images.

Both the Maven and Node.js agent images are automatically configured as
Kubernetes Pod Template images within the {product-title} Jenkins image's
configuration for the Kubernetes plug-in. That configuration includes labels for
each of the images that can be applied to any of your Jenkins jobs under their
`Restrict where this project can be run` setting. If the label is applied,
jobs run under an {product-title} Pod running the
respective agent image.

The Jenkins image also provides auto-discovery and auto-configuration of
additional agent images for the Kubernetes plug-in.

With the {product-title} Sync plug-in, the Jenkins image on Jenkins start-up
searches for the following within the project that it is running or the
projects specifically listed in the plug-in's configuration:

* Imagestreams that have the label `role` set to `jenkins-slave`.
* Imagestreamtags that have the annotation `role` set to `jenkins-slave`.
* ConfigMaps that have the label `role` set to `jenkins-slave`.

When it finds an imagestream with the appropriate label, or imagestreamtag
with the appropriate annotation, it generates the corresponding Kubernetes
plug-in configuration so you can assign your Jenkins jobs to run in a Pod
that runs the container image that is provided by the imagestream.

The name and image references of the imagestream or imagestreamtag are mapped
to the name and image fields in the Kubernetes plug-in Pod template. You can
control the label field of the Kubernetes plug-in Pod template by setting an
annotation on the imagestream or imagestreamtag object with the key
`slave-label`. Otherwise, the name is used as the label.

[NOTE]
====
Do not log in to the Jenkins console and modify the Pod Template configuration.
If you do so after the Pod Template is created, and the OpenShift Sync plug-in
detects that the image associated with the ImageStream or ImageStreamTag has
changed, it replaces the Pod Template and overwrites those configuration
changes. You cannot merge a new configuration with the existing configuration.

Consider the ConfigMap approach if you have more complex configuration needs.
====

When it finds a ConfigMap with the appropriate label, it assumes that any values
in the key-value data payload of the ConfigMap contains XML that is consistent
with the configuration format for Jenkins and the Kubernetes plug-in Pod
templates. A key differentiator to note when using ConfigMaps, instead of
imagestreams or imagestreamtags, is that you can control all the parameters
of the Kubernetes plug-in Pod template.

Example ConfigMap for `jenkins-agent`:

[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: jenkins-agent
  labels:
    role: jenkins-slave
data:
  template1: |-
    <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
      <inheritFrom></inheritFrom>
      <name>template1</name>
      <instanceCap>2147483647</instanceCap>
      <idleMinutes>0</idleMinutes>
      <label>template1</label>
      <serviceAccount>jenkins</serviceAccount>
      <nodeSelector></nodeSelector>
      <volumes/>
      <containers>
        <org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
          <name>jnlp</name>
          <image>openshift/jenkins-agent-maven-35-centos7:v3.10</image>
          <privileged>false</privileged>
          <alwaysPullImage>true</alwaysPullImage>
          <workingDir>/tmp</workingDir>
          <command></command>
          <args>${computer.jnlpmac} ${computer.name}</args>
          <ttyEnabled>false</ttyEnabled>
          <resourceRequestCpu></resourceRequestCpu>
          <resourceRequestMemory></resourceRequestMemory>
          <resourceLimitCpu></resourceLimitCpu>
          <resourceLimitMemory></resourceLimitMemory>
          <envVars/>
        </org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
      </containers>
      <envVars/>
      <annotations/>
      <imagePullSecrets/>
      <nodeProperties/>
    </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
----

Another example that uses multiple containers would be (where we use {product-title} ImageStream image references to
ImageStreams installed in the 'openshift' namespace that work when running in an {product-title} cluster):

[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: jenkins-agent
  labels:
    role: jenkins-slave
data:
  template1: |-
        <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
          <inheritFrom></inheritFrom>
          <name>template2</name>
          <instanceCap>2147483647</instanceCap>
          <idleMinutes>0</idleMinutes>
          <label>template1</label>
          <serviceAccount>jenkins</serviceAccount>
          <nodeSelector></nodeSelector>
          <volumes/>
          <containers>
            <org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
              <name>jnlp</name>
              <image>image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-base:latest</image>
              <privileged>false</privileged>
              <alwaysPullImage>true</alwaysPullImage>
              <workingDir>/home/jenkins/agent</workingDir>
              <command></command>
              <args>\$(JENKINS_SECRET) \$(JENKINS_NAME)</args>
              <ttyEnabled>false</ttyEnabled>
              <resourceRequestCpu></resourceRequestCpu>
              <resourceRequestMemory></resourceRequestMemory>
              <resourceLimitCpu></resourceLimitCpu>
              <resourceLimitMemory></resourceLimitMemory>
              <envVars/>
            </org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
            <org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
              <name>java</name>
              <image>image-registry.openshift-image-registry.svc:5000/openshift/java:latest</image>
              <privileged>false</privileged>
              <alwaysPullImage>true</alwaysPullImage>
              <workingDir>/home/jenkins/agent</workingDir>
              <command>cat</command>
              <args></args>
              <ttyEnabled>true</ttyEnabled>
              <resourceRequestCpu></resourceRequestCpu>
              <resourceRequestMemory></resourceRequestMemory>
              <resourceLimitCpu></resourceLimitCpu>
              <resourceLimitMemory></resourceLimitMemory>
              <envVars/>
            </org.csanchez.jenkins.plugins.kubernetes.ContainerTemplate>
          </containers>
          <envVars/>
          <annotations/>
          <imagePullSecrets/>
          <nodeProperties/>
        </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
----


[NOTE]
====
If you log in to the Jenkins console and make further changes to the Pod Template
configuration after the Pod Template is created, and the OpenShift Sync plug-in
detects that the ConfigMap has changed, it will replace the Pod Template and
overwrite those configuration changes. You cannot merge a new configuration with
the existing configuration.

Do not log in to the Jenkins console and modify the Pod Template configuration.
If you do so after the Pod Template is created, and the OpenShift Sync plug-in
detects that the image associated with the ImageStream or ImageStreamTag has
changed, it replaces the Pod Template and overwrites those configuration
changes. You cannot merge a new configuration with the existing configuration.

Consider the ConfigMap approach if you have more complex configuration needs.

====

After it is installed, the OpenShift Sync plug-in monitors the API server of
{product-title} for updates to `ImageStreams`, `ImageStreamTags`, and
`ConfigMaps` and adjusts the configuration of the Kubernetes plug-in.

The following rules apply:

* Removing the label or annotation from the `ConfigMap`, `ImageStream`, or
`ImageStreamTag` results in the deletion of any existing `PodTemplate` from
the configuration of the Kubernetes plug-in.
* If those objects are removed, the corresponding configuration
is removed from the Kubernetes plug-in.
* Either creating appropriately labeled or annotated `ConfigMap`,
`ImageStream`, or `ImageStreamTag` objects, or the adding of labels after their
initial creation, leads to creating of a `PodTemplate` in the Kubernetes-plugin
configuration.
* In the case of the `PodTemplate` by `ConfigMap` form, changes to the `ConfigMap`
data for the `PodTemplate` are applied to the `PodTemplate` settings in the
Kubernetes plug-in configuration and overrides any changes that were made to the
`PodTemplate` through the Jenkins UI between changes to the `ConfigMap`.

To use a container image as a Jenkins agent, the image must run the slave agent as
an entrypoint. For more details about this, refer to the official
https://wiki.jenkins-ci.org/display/JENKINS/Distributed+builds#Distributedbuilds-Launchslaveagentheadlessly[Jenkins
documentation].
