// Module included in the following assemblies:
//
// * openshift_images/managing-images/using-imagestreams-with-kube-resources.adoc


:_mod-docs-content-type: PROCEDURE
[id="images-managing-images-enabling-imagestreams-kube_{context}"]
= Enabling image streams with Kubernetes resources

[role="_abstract"]
When using Kubernetes resources, you must reference image streams located within the same project by specifying a single segment value, such as `ruby:2.5`, which identifies the image stream name and its tag. This ensures the resource correctly targets the local image stream within its scope.

include::snippets/default-projects.adoc[]

There are two ways to enable image streams with Kubernetes resources:

* Enabling image stream resolution on a specific resource. This allows only this resource to use the image stream name in the image field.
* Enabling image stream resolution on an image stream. This allows all resources pointing to this image stream to use it in the image field.

You can use `oc set image-lookup` to enable image stream resolution on a specific resource or image stream resolution on an image stream.

.Procedure

. To allow all resources to reference the image stream named `mysql`, enter the following command:
+
[source,terminal]
----
$ oc set image-lookup mysql
----
+
This sets the `Imagestream.spec.lookupPolicy.local` field to true.
+
.Imagestream with image lookup enabled
[source,yaml]
----
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: mysql
  name: mysql
  namespace: myproject
spec:
  lookupPolicy:
    local: true
----
+
When enabled, the behavior is enabled for all tags within the image stream.
+
. Then you can query the image streams and see if the option is set:
+
[source,terminal]
----
$ oc set image-lookup imagestream --list
----

. Optional: You can enable image lookup on a specific resource.
+
To allow the Kubernetes deployment named `mysql` to use image streams, run the following command:
+
[source,terminal]
----
$ oc set image-lookup deploy/mysql
----
+
This sets the `alpha.image.policy.openshift.io/resolve-names` annotation
on the deployment.
+
.Deployment with image lookup enabled
[source,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: myproject
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
    spec:
      containers:
      - image: mysql:latest
        imagePullPolicy: Always
        name: mysql
----

. Optional: To disable image lookup, pass `--enabled=false`:
+
[source,terminal]
----
$ oc set image-lookup deploy/mysql --enabled=false
----
