// Module included in the following assemblies:
//
// * machine_management/creating_machinesets/creating-infrastructure-machinesets.adoc
// * nodes-nodes-creating-infrastructure-nodes.adoc

[id="infrastructure-components_{context}"]
= {product-title} infrastructure components

Each self-managed Red{nbsp}Hat OpenShift subscription includes entitlements for {product-title} and other OpenShift-related components. These entitlements are included for running {product-title} control plane and infrastructure workloads and do not need to be accounted for during sizing.

To qualify as an infrastructure node and use the included entitlement, only components that are supporting the cluster, and not part of an end-user application, can run on those instances. Examples include the following components:

* Kubernetes and {product-title} control plane services
* The default router
* The integrated container image registry
* The HAProxy-based Ingress Controller
* The cluster metrics collection, or monitoring service, including components for monitoring user-defined projects
* Cluster aggregated logging
* Red Hat Quay
* {rh-storage-first}
* Red Hat Advanced Cluster Management for Kubernetes
* Red Hat Advanced Cluster Security for Kubernetes
* Red Hat OpenShift GitOps
* Red Hat OpenShift Pipelines
* {SMProductName}

// Updated the list to match the list under "Red Hat OpenShift control plane and infrastructure nodes" in https://www.redhat.com/en/resources/openshift-subscription-sizing-guide

Any node that runs any other container, pod, or component is a worker node that your subscription must cover.
