// Module included in the following assemblies:
//
// * operators/operator-reference.adoc
// * installing/cluster-capabilities.adoc

ifeval::["{context}" == "cluster-capabilities"]
:cluster-caps:
endif::[]

ifeval::["{context}" == "cluster-operators-ref"]
:operator-ref:
endif::[]

:_content-type: REFERENCE
[id="insights-operator_{context}"]
ifdef::operator-ref[= Insights Operator]
ifdef::cluster-caps[= Insights capability]

ifdef::operator-ref[]

[NOTE]
====
The Insights Operator is an optional cluster capability that can be disabled by cluster administrators during installation. For more information about optional cluster capabilities, see "Cluster capabilities" in _Installing_.
====

endif::operator-ref[]

[discrete]
== Purpose

ifdef::cluster-caps[]

The Insights Operator provides the features for the `Insights` capability.

endif::cluster-caps[]

The Insights Operator gathers {product-title} configuration data and sends it to Red Hat. The data is used to produce proactive insights recommendations about potential issues that a cluster might be exposed to. These insights are communicated to cluster administrators through Insights Advisor on link:https://console.redhat.com/[console.redhat.com].

ifdef::operator-ref[]

[discrete]
== Project

link:https://github.com/openshift/insights-operator[insights-operator]

[discrete]
== Configuration

No configuration is required.

endif::operator-ref[]

[discrete]
== Notes

Insights Operator complements {product-title} Telemetry.

ifeval::["{context}" == "cluster-operators-ref"]
:!operator-ref:
endif::[]

ifeval::["{context}" == "cluster-caps"]
:!cluster-caps:
endif::[]