// Module included in the following assemblies:
//
// * support/remote_health_monitoring/about-remote-health-monitoring.adoc

[id="insights-operator-about_{context}"]
= About the Insights Operator

The Insights Operator periodically gathers anonymized configuration and component failure status and reports that to Red Hat. This is a subset of the information captured by the `must-gather` tool and allows Red Hat to assess important configuration and deeper failure data than is reported via Telemetry. This data is sent several times a day and describes:

* Important configuration information about the environment that the cluster runs in
* Details about the state of the cluster and its major components
* Debugging information about infrastructure Pods or nodes that are reporting failures

This debugging information is available to Red Hat Support and engineering teams with the same restrictions as accessing data reported via support cases. All connected cluster information is used by Red Hat to help make {product-title} better and more intuitive to use. None of the information is shared with third parties.
