// Module included in the following assemblies:
//
// *installing/installing-gather-logs.adoc

[id="installation-bootstrap-gather_{context}"]
= Gathering logs from a failed installation

If you gave an SSH key to your installation program, you can gather data about
your failed installation.

[NOTE]
====
You use a different command to gather logs about an unsuccessful installation
than to gather logs from a running cluster. If you must gather logs from a
running cluster, use the `oc adm must-gather` command.
====

.Prerequisites

* Your {product-title} installation failed before the bootstrap process
finished. The bootstrap node must be running and accessible through SSH.
* The `ssh-agent` process is active on your computer, and you provided both the
`ssh-agent` process and the installation program the same SSH key.
* If you tried to install a cluster on infrastructure that you provisioned, you
must have the fully-qualified domain names of the control plane, or master,
machines.

.Procedure

. Generate the commands that are required to obtain the installation logs from
the bootstrap and control plane machines:
+
--
** If you used installer-provisioned infrastructure, run the following command:
+
----
$ ./openshift-install gather bootstrap --dir=<directory> <1>
----
<1> `installation_directory` is the directory you stored the {product-title}
definition files that the installation program creates.
+
For installer-provisioned infrastructure, the installation program stores
information about the cluster, so you do not specify the host names or IP
addresses

** If you used infrastructure that you provisioned yourself, run the following
command:
+
----
$ ./openshift-install gather bootstrap --dir=<directory> \ <1>
    --bootstrap <bootstrap_address> \ <2>
    --master "<master_address> <master_address> <master_address>" <3>
----
<1> `installation_directory` is the directory you stored the {product-title}
definition files that the installation program creates.
<2> `<bootstrap_address>` is the fully-qualified domain name or IP address of
the cluster's bootstrap machine.
<3> `<master_address>` is the fully-qualified domain name or IP address of a
control plane, or master, machine in your cluster. Specify a space-delimited
list that contains all the control plane machines in your cluster.
--
+
The command output resembles the following example:
+
----
INFO Use the following commands to gather logs from the cluster
INFO ssh -A core@<bootstrap_address> '/usr/local/bin/installer-gather.sh <master_address> <master_address> <master_address>'
INFO scp core@<bootstrap_address>:~/log-bundle.tar.gz .
----
+
You use both commands that are displayed to gather and download the logs.

. Gather logs from the bootstrap and master machines:
+
----
$ ssh -A core@<bootstrap_address> '/usr/local/bin/installer-gather.sh <master_address> <master_address> <master_address>'
----
+
You SSH into the bootstrap machine and run the gather tool, which is designed to
collect as much data as possible from the bootstrap and control plane machines
in your cluster and compress all of the gathered files.
+
[NOTE]
====
It is normal to see errors in the command output. If the command output
displays the instructions to download the compressed log files,
`log-bundle.tar.gz`, then the command succeeded.
====

. Download the compressed file that contains the logs:
+
----
$ scp core@<bootstrap_address>:~/log-bundle.tar.gz . <1>
----
<1> `<bootstrap_address>` is the fully-qualified domain name or IP address of the bootstrap
machine.
+
The command to download the log files is included at the end of the gather
command output.
+
If you open a Red Hat support case about your installation failure, include
the compressed logs in the case.
