// Module included in the following assemblies:
//
// * installing/installing_rhv/installing-rhv-user-infra.adoc
// * installing/installing-rhv-restricted-network.adoc

[id="installation-rhv-customizing-install-config-yaml_{context}"]
= Customizing install-config.yaml

Here, you use three Python scripts to override some of the installation program's default behaviors:

* By default, the installation program uses the machine API to create nodes. To override this default behavior, you set the number of compute nodes to zero replicas. Later, you use Ansible playbooks to create the compute nodes.

* By default, the installation program sets the IP range of the machine network for nodes. To override this default behavior, you set the IP range to match your infrastructure.

* By default, the installation program sets the platform to `ovirt`. However, installing a cluster on user-provisioned infrastructure is more similar to installing a cluster on bare metal. Therefore, you delete the ovirt platform section from `install-config.yaml` and change the platform to `none`. Instead, you use `inventory.yml` to specify all of the required settings.

NOTE: These snippets work with Python 3 and Python 2.

// TBD - https://issues.redhat.com/browse/OCPRHV-414
// Please discuss with engineering whether these three scripts can/should be combined into a single script.
// Also consider combining this topic with other customization topics.

.Procedure
//TBD - Should we combine these into one script?

. Set the number of compute nodes to zero replicas:
+
[source,python]
----
$ python3 -c 'import os, yaml
path = "%s/install-config.yaml" % os.environ["ASSETS_DIR"]
conf = yaml.safe_load(open(path))
conf["compute"][0]["replicas"] = 0
open(path, "w").write(yaml.dump(conf, default_flow_style=False))'
----


. Set the IP range of the machine network. For example, to set the range to `172.16.0.0/16`, enter:
+
[source,python]
----
$ python3 -c 'import os, yaml
path = "%s/install-config.yaml" % os.environ["ASSETS_DIR"]
conf = yaml.safe_load(open(path))
conf["networking"]["machineNetwork"][0]["cidr"] = "172.16.0.0/16"
open(path, "w").write(yaml.dump(conf, default_flow_style=False))'
----


. Remove the `ovirt` section and change the platform to `none`:
+
[source,python]
----
$ python3 -c 'import os, yaml
path = "%s/install-config.yaml" % os.environ["ASSETS_DIR"]
conf = yaml.safe_load(open(path))
platform = conf["platform"]
del platform["ovirt"]
platform["none"] = {}
open(path, "w").write(yaml.dump(conf, default_flow_style=False))'
----
+
[WARNING]
====
Red Hat Virtualization does not currently support installation with user-provisioned infrastructure on the oVirt platform. Therefore, you must set the platform to `none`, allowing {product-title} to identify each node as a bare-metal node and the cluster as a bare-metal cluster. This is the same as xref:../../installing/installing_platform_agnostic/installing-platform-agnostic.adoc#installing-platform-agnostic[installing a cluster on any platform], and has the following limitations:

. There will be no cluster provider so you must manually add each machine and there will be no node scaling capabilities.
. The oVirt CSI driver will not be installed and there will be no CSI capabilities.
====
