// Module included in the following assemblies:
//
// * installing/install_config/installing-restricted-networks-preparations.adoc

[id="installation-restricted-network-samples_{context}"]
= Using sample imagestreams in a restricted network installation

Most imagestreams in the OpenShift namespace managed by the Samples Operator
point to images located in the Red Hat registry at link:registry.redhat.io[registry.redhat.io]. Mirroring
will not apply to these imagestreams.

The `jenkins`, `jenkins-agent-maven`, and `jenkins-agent-nodejs` imagestreams
come from the install payload and are managed by the Samples Operator, so no
further mirroring procedures are needed for those imagestreams.

[NOTE]
====
The `cli`, `installer`, `must-gather`, and `tests` imagestreams, while
part of the install payload, are not managed by the Samples Operator. These are
not addressed in this procedure.
====

.Prerequisites
* Access to the cluster as a user with the `cluster-admin` role.
* Create a pull secret for your mirror registry.

.Procedure

. Mirror images from link:registry.redhat.io[registry.redhat.io] associated with any imagestreams you need
in the restricted network environment into one of the defined mirrors:
+
----
$ oc image mirror myregistry.com/myimage:latest myregistry.com/myimage:stable
----
+
. Add the required trusted CAs for the mirror in the cluster’s image
configuration object:
+
----
$ oc create configmap registry-config --from-file=$path/ca.crt -n openshift-config
$ oc patch image.config.openshift.io/cluster --patch '{"spec":{"additionalTrustedCA":{"name":"registry-config"}}}' --type=merge
----
+
//(meaning https://github.com/openshift/api/blob/master/config/v1/types_image.go#L46 … add ref to associated doc)
+
. Update the `samplesRegistry` field in the Samples Operator configuration object
to contain the `hostname` portion of the mirror location defined in the mirror
configuration:
+
----
$ oc get configs.samples.operator.openshift.io -n openshift-cluster-samples-operator
----
+
[NOTE]
====
This is required because the imagestream import process does not use the mirror or search mechanism at this time.
====
+
. Add any imagestreams that are not mirrored into the `skippedImagestreams` field
of the Samples Operator configuration object. Or if you do not want to support
any of the sample imagestreams, set the Samples Operator to `Removed` in the
Samples Operator configuration object.
+
[NOTE]
====
Any unmirrored imagestreams that are not skipped, or if the Samples Operator is
not changed to `Removed`, will result in the Samples Operator reporting a
`Degraded` status two hours after the imagestream imports start failing.
====
+
Many of the templates in the OpenShift namespace
reference the imagestreams. So using `Removed` to purge both the imagestreams
and templates will eliminate the possibility of attempts to use them if they
are not functional because of any missing imagestreams.
