// Module included in the following assemblies:
//
// * installing/install_config/installing-customizing.adoc

[id="installation-special-config-encrypt-disk-tang_{context}"]
= Enabling Tang disk encryption
Use this procedure to enable Tang mode disk encryption during {product-title} deployment.

.Procedure

. Access a Red Hat Enterprise Linux server from which you can configure the encryption
settings and run `openshift-install` to install a cluster and `oc` to work with it.
. Set up or access an existing Tang server. See link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/configuring-automated-unlocking-of-encrypted-volumes-using-policy-based-decryption_security-hardening#network-bound-disk-encryption_configuring-automated-unlocking-of-encrypted-volumes-using-policy-based-decryption[Network-bound disk encryption]
for instructions. See link:https://youtu.be/2uLKvB8Z5D0[Securing Automated Decryption New Cryptography and Techniques]
for a presentation on Tang.


. Add kernel arguments to configure networking when you do the {op-system-first} installations for your cluster. For example, to configure DHCP networking, identify `ip=dhcp`, or set static networking when you add parameters to the kernel command line. For both DHCP and static networking, you also must provide the `rd.neednet=1` kernel argument.

[IMPORTANT]
====
Skipping this step causes the second boot to fail.
====

[start=4]
. Install the `clevis` package, if it is not already installed:

[source,terminal]
----
$ sudo yum install clevis -y
----

[start=5]
. Generate a thumbprint from the Tang server.

.. In the following command, replace the value of `url` with the Tang server URL:
+
[source,terminal]
----
$ echo nifty random wordwords \
     | clevis-encrypt-tang \
       '{"url":"https://tang.example.org"}'
----
+
.Example output
[source,terminal]
----
The advertisement contains the following signing keys:

PLjNyRdGw03zlRoGjQYMahSZGu9
----

.. When the `Do you wish to trust these keys? [ynYN]` prompt displays, type `Y`, and the thumbprint is displayed:
+
.Example output
[source,terminal]
----
eyJhbmc3SlRyMXpPenc3ajhEQ01tZVJiTi1oM...
----

. Create a Base64 encoded file, replacing the URL of the Tang server (`url`) and thumbprint (`thp`) you just generated:
+
[source,terminal]
----
$ (cat <<EOM
{
 "url": "https://tang.example.com",
 "thp": "PLjNyRdGw03zlRoGjQYMahSZGu9"
}
EOM
) | base64 -w0
----
+
.Example output
[source,terminal]
----
ewogInVybCI6ICJodHRwczovL3RhbmcuZXhhbXBsZS5jb20iLAogInRocCI6ICJaUk1leTFjR3cwN3psVExHYlhuUWFoUzBHdTAiCn0K
----

. In the `openshift` directory, create master or worker files to encrypt disks for those nodes.

** For worker nodes, use the following command:
+
[source,terminal]
----
$ cat << EOF > ./99-openshift-worker-tang-encryption.yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: worker-tang
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;base64,e30K
          source: data:text/plain;base64,ewogInVybCI6ICJodHRwczovL3RhbmcuZXhhbXBsZS5jb20iLAogInRocCI6ICJaUk1leTFjR3cwN3psVExHYlhuUWFoUzBHdTAiCn0K
        mode: 420
        overwrite: true
        path: /etc/clevis.json
EOF
----

** For master nodes, use the following command:
+
[source,terminal]
----
$ cat << EOF > ./99-openshift-master-tang-encryption.yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: master-tang
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;base64,e30K
          source: data:text/plain;base64,ewogInVybCI6ICJodHRwczovL3RhbmcuZXhhbXBsZS5jb20iLAogInRocCI6ICJaUk1leTFjR3cwN3psVExHYlhuUWFoUzBHdTAiCn0K
        mode: 420
        overwrite: true
        path: /etc/clevis.json
EOF
----

. Add the `rd.neednet=1` kernel argument, as shown in the following example:
+
[source,yaml]
----
  apiVersion: machineconfiguration.openshift.io/v1
  kind: MachineConfig
  metadata:
    name: <node_type>-tang <.>
  spec:
    config:
      ignition:
        version: 3.1.0
    kernelArguments:
      - rd.neednet=1 <.>
----
+
<1> Use the name you defined in the previous examples based on the type of node you are configuring, for example: `name: worker-tang`.
+
<2> Required.

. Continue with the remainder of the {product-title} deployment.
