// Module included in the following assemblies:
//
// * installing/installing_azure/installing-azure-user-infra.adoc
// * installing/installing_azure_stack_hub/installing-azure-stack-hub-user-infra.adoc

ifeval::["{context}" == "installing-azure-user-infra"]
:azure:
:cp: Azure
endif::[]
ifeval::["{context}" == "installing-azure-stack-hub-user-infra"]
:ash:
:cp: Azure Stack Hub
endif::[]

[id="installation-azure-user-infra-wait-for-bootstrap_{context}"]
= Wait for bootstrap completion and remove bootstrap resources in {cp}

After you create all of the required infrastructure in Microsoft {cp}, wait for
the bootstrap process to complete on the machines that you provisioned by using
the Ignition config files that you generated with the installation program.

.Prerequisites

* Configure an Azure account.
* Generate the Ignition config files for your cluster.
* Create and configure a VNet and associated subnets in {cp}.
* Create and configure networking and load balancers in {cp}.
* Create control plane and compute roles.
* Create the bootstrap machine.
* Create the control plane machines.

.Procedure

. Change to the directory that contains the installation program and run the
following command:
+
[source,terminal]
----
$ ./openshift-install wait-for bootstrap-complete --dir=<installation_directory> \ <1>
    --log-level info <2>
----
<1> For `<installation_directory>`, specify the path to the directory that you
stored the installation files in.
<2> To view different installation details, specify `warn`, `debug`, or
`error` instead of `info`.
+
If the command exits without a `FATAL` warning, your production control plane
has initialized.

. Delete the bootstrap resources:
+
[source,terminal]
----
$ az network nsg rule delete -g ${RESOURCE_GROUP} --nsg-name ${INFRA_ID}-nsg --name bootstrap_ssh_in
$ az vm stop -g ${RESOURCE_GROUP} --name ${INFRA_ID}-bootstrap
$ az vm deallocate -g ${RESOURCE_GROUP} --name ${INFRA_ID}-bootstrap
$ az vm delete -g ${RESOURCE_GROUP} --name ${INFRA_ID}-bootstrap --yes
$ az disk delete -g ${RESOURCE_GROUP} --name ${INFRA_ID}-bootstrap_OSDisk --no-wait --yes
$ az network nic delete -g ${RESOURCE_GROUP} --name ${INFRA_ID}-bootstrap-nic --no-wait
$ az storage blob delete --account-key ${ACCOUNT_KEY} --account-name ${CLUSTER_NAME}sa --container-name files --name bootstrap.ign
$ az network public-ip delete -g ${RESOURCE_GROUP} --name ${INFRA_ID}-bootstrap-ssh-pip
----

ifeval::["{context}" == "installing-azure-user-infra"]
:!azure:
:!cp: Azure
endif::[]
ifeval::["{context}" == "installing-azure-stack-hub-user-infra"]
:!ash:
:!cp: Azure Stack Hub
endif::[]
