// Module included in the following assemblies:
//
// * virt/install/installing-ove.adoc

:_mod-docs-content-type: PROCEDURE
[id="virt-installing-ove-iso_{context}"]
= Downloading the installation ISO

[role="_abstract"]
You must first download the ISO image that will be used to run the installation on your bare-metal machines.
This image includes all of the necessary {product-title} release images, as well as the {olm-first} Operators needed to install Virtualization on the cluster.

[NOTE]
====
The size of the ISO image can vary depending on the release you select.
====

.Procedure

. Log in to the {hybrid-console-url}.

. On the *Red Hat OpenShift* tile, click *OpenShift*.

. On the *Red Hat OpenShift Container Platform* tile, click *Create cluster*.

. Click the *Datacenter* tab.

. Under *Assisted Installer*, click *Create cluster*.

. In the *Cluster details* page, select the toggle for "I'm installing on a disconnected/air-gapped/secured environment".

. Select an {product-title} version in the *OpenShift version* dropdown menu.

. Click *Next*.

. Optional: Preconfigure the ISO on the *Optional configurations* page:

.. Enter the Rendezvous IP in the *Rendezvous IP* field.

.. Upload a SSH public key in the *SSH public key* field.

.. Select *Edit pull secret* and add a pull secret to the field that appears.

.. Select *Configure proxy settings* and provide proxy details to the fields that appear.

.. Select *Add your own NTP (Network Time Protocol) sources* and add NTP sources to the field that appears.

. Click *Next*.

. Click *Download ISO*.