// Module included in the following assemblies:
//
// * installing/installing-troubleshooting.adoc
// * support/troubleshooting/troubleshooting-installations.adoc

[id="installation-bootstrap-gather_{context}"]
= Gathering logs from a failed installation

If you gave an SSH key to your installation program, you can gather data about
your failed installation.

[NOTE]
====
You use a different command to gather logs about an unsuccessful installation
than to gather logs from a running cluster. If you must gather logs from a
running cluster, use the `oc adm must-gather` command.
====

.Prerequisites

* Your {product-title} installation failed before the bootstrap process finished. The bootstrap node is running and accessible through SSH.
* The `ssh-agent` process is active on your computer, and you provided the same SSH key to both the `ssh-agent` process and the installation program.
* If you tried to install a cluster on infrastructure that you provisioned, you must have the fully qualified domain names of the bootstrap and control plane nodes (also known as the master nodes).

.Procedure

. Generate the commands that are required to obtain the installation logs from
the bootstrap and control plane machines:
+
--
** If you used installer-provisioned infrastructure, change to the directory that contains the installation program and run the following command:
+
[source,terminal]
----
$ ./openshift-install gather bootstrap --dir <installation_directory> <1>
----
<1> `installation_directory` is the directory you specified when you ran `./openshift-install create cluster`. This directory contains the {product-title}
definition files that the installation program creates.
+
For installer-provisioned infrastructure, the installation program stores
information about the cluster, so you do not specify the hostnames or IP
addresses.

** If you used infrastructure that you provisioned yourself, change to the directory that contains the installation program and run the following
command:
+
[source,terminal]
----
$ ./openshift-install gather bootstrap --dir <installation_directory> \ <1>
    --bootstrap <bootstrap_address> \ <2>
    --master <master_1_address> \ <3>
    --master <master_2_address> \ <3>
    --master <master_3_address>" <3>
----
<1> For `installation_directory`, specify the same directory you specified when you ran `./openshift-install create cluster`. This directory contains the {product-title}
definition files that the installation program creates.
<2> `<bootstrap_address>` is the fully qualified domain name or IP address of
the cluster's bootstrap machine.
<3> For each control plane, or master, machine in your cluster, replace `<master_*_address>` with its fully qualified domain name or IP address.
+
[NOTE]
====
A default cluster contains three control plane machines. List all of your control plane machines as shown, no matter how many your cluster uses.
====
--
+
.Example output
[source,terminal]
----
INFO Pulling debug logs from the bootstrap machine
INFO Bootstrap gather logs captured here "<installation_directory>/log-bundle-<timestamp>.tar.gz"
----
+
If you open a Red Hat support case about your installation failure, include
the compressed logs in the case.
