// Module included in the following assemblies:
//
// * installing/installing_bare_metal/installing-bare-metal.adoc

[id="installation-bare-metal-config-yaml-{context}"]
= Sample `install-config.yaml` file for bare metal

You can customize the `install-config.yaml` file to specify more details about
your {product-title} cluster's platform or modify the values of the required
parameters.

[source,yaml]
----
apiVersion: v1beta4
baseDomain: example.com <1>
compute:
- name: worker
  replicas: 0 <2>
controlPlane:
  name: master
  replicas: 3
metadata:
  name: test <3>
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14 <4>
    hostPrefix: 23 <5>
networkType: OpenShiftSDN
serviceNetwork: <6>
- 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths": ...}' <7>
sshKey: 'ssh-ed25519 AAAA...' <8>
----
<1> The base domain of the cluster. All DNS records must be sub-domains of this
base and include the cluster name.
<2> You must set the number of workers to `0`.
<3> The cluster name.
<4> A block of IP addresses from which pod IPs are allocated.
<5> The subnet prefix length to assign to each individual node. For example, if
`hostPrefix` is set to `23`, then each node is assigned a `/23` subnet out of
the given `cidr`, which allows for 510 (2^(32 - 23) - 2) pod IPs addresses.
<6> The IP address pool to use for service IP addresses. You can enter only
one IP address pool.
<7> The pull secret that provides components in the cluster access to images for
{product-title} components.
<8> The default SSH key for the `core` user.