// Module included in the following assemblies:
//
// * installing/installing_aws_upi/installing-aws-upi.adoc

[id="installation-aws-upi-installation-{context}"]
= Completing an AWS UPI installation

After you start the {product-title} installation on Amazon Web Service (AWS)
user-provisioned infrastructure, remove the bootstrap node, reconcile the default
Machine and MachineSet definitions, and delete unused nodes

.Prerequisites

* Deploy the bootstrap node for an {product-title} cluster on user-provisioned AWS infrastructure.
* Install the `oc` CLI and log in.

.Procedure

. Delete the bootstrap resources. If you used the CloudFormation template,
link:https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-delete-stack.html[delete its stack]:
+
----
$ aws cloudformation delete-stack --stack-name <name> <1>
----
<1> `<name>` is the name of your bootstrap stack.

////
. View the list of machines in the `openshift-machine-api` namespace:
+
----
$ oc get machines --namespace openshift-machine-api
NAME                                    INSTANCE   STATE     TYPE        REGION      ZONE         AGE
test-tkh7l-master-0                                       m4.xlarge   us-east-2   us-east-2a   9m22s
test-tkh7l-master-1                                       m4.xlarge   us-east-2   us-east-2b   9m22s
test-tkh7l-master-2                                       m4.xlarge   us-east-2   us-east-2c   9m21s
test-tkh7l-worker-us-east-2a-qjcxq                        m4.large    us-east-2   us-east-2a   8m6s
test-tkh7l-worker-us-east-2b-nq8zs                        m4.large    us-east-2   us-east-2b   8m6s
test-tkh7l-worker-us-east-2c-ww6c6                        m4.large    us-east-2   us-east-2c   8m7s
----
+
Note the `NAME` of each node. Because you manually deployed control plane
nodes, the master machines are not controlled by the Machine API. Similarly,
the worker machines are not backed by AWS instances on your subnet. You delete
each of these machines.

. Delete each of the listed machines:
+
----
$ oc delete machine --namespace openshift-machine-api <node_name> <1>
machine.machine.openshift.io "<node_name>" deleted
----
<1> Specify the name of a master or worker node to delete.
////

. Review the pending certificate signing requests (CSRs) and ensure that the
requests are for the machines that you added to the cluster:
+
----
$ oc get csr

NAME        AGE     REQUESTOR                                                                   CONDITION
csr-8b2br   15m     system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-8vnps   15m     system:serviceaccount:openshift-machine-config-operator:node-bootstrapper   Approved,Issued
csr-b96j4   25s     system:node:ip-10-0-52-215.us-east-2.compute.internal                       Approved,Issued
csr-bfd72   5m26s   system:node:ip-10-0-50-126.us-east-2.compute.internal                       Pending
csr-c57lv   5m26s   system:node:ip-10-0-95-157.us-east-2.compute.internal                       Pending
----

. Approve the CSRs for your cluster machines.
** To approve them individually, run the following command for each valid
CSR:
+
----
$ oc adm certificate approve <csr_name> <1>
----
<1> `<csr_name>` is the name of a CSR from the list of current CSRs.

** If all the CSRs are valid, approve them all by running the following
command:
+
----
$ oc get csr -ojson | jq -r '.items[] | select(.status == {} ) | .metadata.name' | xargs oc adm certificate approve
----

. Complete the cluster installation:
+
----
$ ./openshift-install wait-for install-complete
INFO Waiting up to 30m0s for the cluster to initialize...
----
