// Module included in the following assemblies:
//
// * installing/installing_with_agent_based_installer/installing-with-agent-basic.adoc

:_mod-docs-content-type: PROCEDURE
[id="installing-ocp-agent-local-arbiter-node_{context}"]
= Configure a local arbiter node

[role="_abstract"]
Configure an {product-title} cluster with a local arbiter node to maintain high availability with only two control plane nodes, reducing infrastructure costs and hardware requirements.

[IMPORTANT]
====
You can configure a local arbiter node only. Remote arbiter nodes are not supported.
====

To deploy a cluster with two control plane nodes and one local arbiter node, you must define the following nodes in the `install-config.yaml` file:

* 2 control plane nodes
* 1 arbiter node

The arbiter node must meet the following minimum system requirements:

* 2 vCPUs
* 8 GB of RAM
* 50 GB of SSD or equivalent storage

The arbiter node must be located in a network environment with an end-to-end latency of less than 500 milliseconds, including disk I/O. In high-latency environments, you might need to apply the `etcd` slow profile.

The control plane nodes must meet the following minimum system requirements:

* 4 vCPUs
* 16 GB of RAM
* 120 GB of SSD or equivalent storage

Additionally, the control plane nodes must also have enough storage for the workload.

.Prerequisites

* You have downloaded {oc-first} and the installation program.
* You have logged into the {oc-first}.

.Procedure

. Edit the `install-config.yaml` file to define the arbiter node alongside control plane nodes.
+
.Example `install-config.yaml` configuration for deploying an arbiter node
[source,yaml]
----
apiVersion: v1
baseDomain: devcluster.openshift.com
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    platform: {}
    replicas: 0
arbiter: <1>
  architecture: amd64
  hyperthreading: Enabled
  replicas: 1 <2>
  name: arbiter <3>
  platform:
    baremetal: {}
controlPlane: <4>
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    baremetal: {}
  replicas: 2 <5>
platform:
  baremetal:
# ...
    hosts:
      - name: cluster-master-0
        role: master
# ...
      - name: cluster-master-1
        role: master
        ...
      - name: cluster-arbiter-0
        role: arbiter
# ...
----
<1> Defines the arbiter machine pool. You must configure this field to deploy a cluster with an arbiter node.
<2> Set the `replicas` field to `1` for the arbiter pool. You cannot set this field to a value that is greater than 1.
<3> Specifies a name for the arbiter machine pool.
<4> Defines the control plane machine pool.
<5> When an arbiter pool is defined, two control plane replicas are valid.

. Save the modified `install-config.yaml` file.

[role="_additional-resources"]
.Additional resources
* xref:../../installing/installing_with_agent_based_installer/preparing-to-install-with-agent-based-installer.adoc#preparing-to-install-with-agent-based-installer[Preparing to install with Agent-based Installer]