// Module included in the following assemblies:
//
// * installing/installing_vsphere/installing-vsphere-installer-provisioned.adoc
// * installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.adoc
// * installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.adoc

[id="installation-vsphere-installer-infra-requirements_{context}"]
= Requirements for vCenter cluster install

Before you install an {product-title} cluster on your vCenter that uses installer-provisioned infrastructure, you must prepare your environment. Logging in to a user account or group that has administrative privileges is the simplest way to access all of the necessary permissions in vCenter.

By configuring roles and permissions, vCenter authentication determines how a group or user can access vSphere components and objects, both globally and locally.

[discrete]
[id="installation-vsphere-installer-infra-requirements-account_{context}"]
== Applying vCenter account privileges

To install an {product-title} cluster in a vCenter, the installation program requires access to an account with privileges to read and create the required resources.

[IMPORTANT]
====
It is recommended that you apply role access privileges globally to ensure that the required permissions are met. If these permissions are not applied globally, you must determine which entities to grant the role permissions to. At minimum, the user or group must have read-only access for both the vCenter and the vSphere entities.
====

.Procedure
To configure your vCenter environment so that a user or group in {product-title} has the necessary privileges to provision storage for the installer:

. Assign the `ReadOnly` role in vCenter to the vSphere user or group that manages {product-title} volumes. This allows them to view the node VM object state and details.

. Grant the user or group with read-only privileges on the node VM object.

. Propagate the `ReadOnly` role set to all the parent entities of the node VM object at the vCenter level, as shown in the following table:
+
.Required vSphere parent entities
[cols="1a,5a,5a",options="header"]
|===

|Role
|Privileges
|Entities

|`Read-only`
|`System.Anonymous`, `System.Read`, `System.View`
|vCenter, Datacenter, Datastore Cluster, Datastore Storage Folder
|===

. Create a custom role in vCenter with read-only privileges.

. Apply the new custom role to the {product-title} user at the vCenter level.

. Propagate the new custom role set to all the child entities of the node VM object at the vCenter level, as shown in the following table:
+
.Required vSphere levels
[cols="1a,5a",options="header"]
|===

|Level
|Privileges

|Datastore
|* *Allocate space*
* *Browse datastore*
* *Low level file operations*
* *Remove file*

|Folder
|* *Create folder*
* *Delete folder*

|vSphere Tagging
|* All privileges

|Network
|* *Assign network*

|Resource
|* *Assign virtual machine to resource pool*

|Profile-driven storage
|* All privileges

|Tasks
|* All privileges

|vApp
|* All privileges

|Virtual machine
|* All privileges

|===
+
[NOTE]
====
It might be possible to further refine the categories where "All privileges" are granted.
====

. Verify that the vCenter user or group permissions are now inherited by the role you created.

For more information about creating an account with the required privileges, see link:https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-5372F580-5C23-4E9C-8A4E-EF1B4DD9033E.html[vSphere Permissions and User Management Tasks] in the vSphere documentation.

[discrete]
[id="installation-vsphere-installer-infra-requirements-vmotion_{context}"]
== Using {product-title} with vMotion

[IMPORTANT]
====
{product-title} generally supports compute-only vMotion. Using Storage vMotion can cause issues and is not supported.
====

If you are using vSphere volumes in your pods, migrating a VM across datastores either manually or through Storage vMotion causes invalid references within {product-title} persistent volume (PV) objects. These references prevent affected pods from starting up and can result in data loss.

Similarly, {product-title} does not support selective migration of VMDKs across datastores, using datastore clusters for VM provisioning or for dynamic or static provisioning of PVs, or using a datastore that is part of a datastore cluster for dynamic or static provisioning of PVs.

[discrete]
[id="installation-vsphere-installer-infra-requirements-resources_{context}"]
== Cluster resources

When you deploy an {product-title} cluster that uses installer-provisioned infrastructure, the installation program must be able to create several resources in your vCenter instance.

A standard {product-title} installation creates the following vCenter resources:

* 1 Folder
* 1 Tag category
* 1 Tag
* Virtual machines:
** 1 template
** 1 temporary bootstrap node
** 3 control plane nodes
** 3 compute machines

Although these resources use 856 GB of storage, the bootstrap node is destroyed during the cluster installation process. A minimum of 800 GB of storage is required to use a standard cluster.

If you deploy more compute machines, the {product-title} cluster will use more storage.

[discrete]
[id="installation-vsphere-installer-infra-requirements-limits_{context}"]
== Cluster limits

Available resources vary between clusters. The number of possible clusters within a vCenter is limited primarily by available storage space and any limitations on the number of required resources. Be sure to consider both limitations to the vCenter resources that the cluster creates and the resources that you require to deploy a cluster, such as IP addresses and networks.

[discrete]
[id="installation-vsphere-installer-infra-requirements-networking_{context}"]
== Networking requirements

You must use DHCP for the network and ensure that the DHCP server is configured to provide persistent IP addresses to the cluster machines. Additionally, you must create the following networking resources before you install the {product-title} cluster:

[discrete]
[id="installation-vsphere-installer-infra-requirements-_{context}"]
=== Required IP Addresses
An installer-provisioned vSphere installation requires two static IP addresses:

* The **API** address is used to access the cluster API.
* The **Ingress** address is used for cluster ingress traffic.

You must provide these IP addresses to the installation program when you install the {product-title} cluster.

[discrete]
[id="installation-vsphere-installer-infra-requirements-dns-records_{context}"]
=== DNS records
You must create DNS records for two static IP addresses in the appropriate DNS server for the vCenter instance that hosts your {product-title} cluster. In each record, `<cluster_name>` is the cluster name and `<base_domain>` is the cluster base domain that you specify when you install the cluster. A complete DNS record takes the form: `<component>.<cluster_name>.<base_domain>.`.

.Required DNS records
[cols="1a,5a,3a",options="header"]
|===

|Component
|Record
|Description

|API VIP
|`api.<cluster_name>.<base_domain>.`
|This DNS A/AAAA or CNAME record must point to the load balancer
for the control plane machines. This record must be resolvable by both clients
external to the cluster and from all the nodes within the cluster.

|Ingress VIP
|`*.apps.<cluster_name>.<base_domain>.`
|A wildcard DNS A/AAAA or CNAME record that points to the load balancer that targets the
machines that run the Ingress router pods, which are the worker nodes by
default. This record must be resolvable by both clients external to the cluster
and from all the nodes within the cluster.
|===
