// Module included in the following assemblies:
//
// * installing/installing_bare_metal/installing-bare-metal.adoc
// * installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
// * installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
// * installing/installing_vsphere/installing-vsphere.adoc
// * installing/installing_ibm_z/installing-ibm-z.adoc

ifeval::["{context}" == "installing-ibm-z"]
:ibm-z:
endif::[]

[id="installation-requirements-user-infra_{context}"]
= Machine requirements for a cluster with user-provisioned infrastructure

For a cluster that contains user-provisioned infrastructure, you must deploy all
of the required machines.

[id="machine-requirements_{context}"]
== Required machines

The smallest {product-title} clusters require the following hosts:

* One temporary bootstrap machine

* Three control plane, or master, machines

* At least two compute, or worker, machines

[NOTE]
====
The cluster requires the bootstrap machine to deploy the {product-title} cluster
on the three control plane machines. You can remove the bootstrap machine after
you install the cluster.
====

[IMPORTANT]
====
ifdef::ibm-z[]
To improve high availability of your cluster, distribute the control plane machines over different z/VM instances. These can, but need not, run on the same Z or LinuxONE hardware.
endif::ibm-z[]
ifndef::ibm-z[]
To maintain high availability of your cluster, use separate physical hosts for
these cluster machines.
endif::ibm-z[]
====

The bootstrap, control plane, and compute machines must use the {op-system-first} as the
operating system.

Note that {op-system} is based on Red Hat Enterprise Linux 8 and inherits all of its hardware certifications and requirements.
See link:https://access.redhat.com/articles/rhel-limits[Red Hat Enterprise Linux technology capabilities and limits].

[id="network-connectivity_{context}"]
== Network connectivity requirements

All the {op-system-first} machines require network in `initramfs` during boot to fetch Ignition config files from the Machine Config Server.
ifdef::ibm-z[]
The machines are configured with static IP addresses. No DHCP server is required.
endif::ibm-z[]
ifndef::ibm-z[]
During the initial boot, the machines require a DHCP server in order to establish a network
connection to download their Ignition config files.
endif::ibm-z[]

ifdef::ibm-z[]
[id="ibm-z-network-connectivity_{context}"]
== IBM Z network connectivity requirements

To install on IBM Z under z/VM, you require a single z/VM virtual NIC in layer 2 mode. You also need:

*   A direct-attached OSA or RoCE network adapter
*   A z/VM VSwitch set up. For a preferred setup, use OSA link aggregation.
endif::ibm-z[]

[id="minimum-resource-requirements_{context}"]
== Minimum resource requirements

Each cluster machine must meet the following minimum requirements:

[cols="2,2,2,2,2",options="header"]
|===

|Machine
|Operating System
|vCPU
|RAM
|Storage

|Bootstrap
|{op-system}
|4
|16 GB
|120 GB

|Control plane
|{op-system}
|4
|16 GB
|120 GB

|Compute
ifdef::ibm-z[|{op-system}]
ifndef::ibm-z[|{op-system} or RHEL 7.6]
|2
|8 GB
|120 GB

|===

ifdef::ibm-z[]
[id="minimum-ibm-z-system-requirements_{context}"]
== Minimum IBM Z system requirements

You can install {product-title} version {product-version} on the following IBM hardware:

* IBM Z, version z13 and later and z13s and later
* LinuxONE, any version

[discrete]
=== Hardware requirements

* 1 LPAR with 3 IFLs that supports SMT2
* 1 OSA or RoCE network adapter

[discrete]
=== Operating system requirements

* One instance of z/VM 7.1

On your z/VM instance, set up:

* 3 guest virtual machines for {product-title} control plane machines
* 2 guest virtual machines for {product-title} compute machines
* 1 guest virtual machine for the temporary {product-title} bootstrap machine

[discrete]
=== Disk storage for the z/VM guest virtual machines

* FICON attached disk storage (DASDs). These can be z/VM minidisks, fullpack minidisks, or dedicated DASDs. If available, use HyperPAV to ensure optimal performance.
+
[NOTE]
====
In {product-title} {product-version}, you must use DASD disks if you require multi-path support.
====
* FCP attached disk storage in single-path configuration.

[discrete]
=== Storage / Main Memory

* 16 GB for {product-title} control plane machines
* 8 GB for {product-title} compute machines
* 16 GB for the temporary {product-title} bootstrap machine

[id="preferred-ibm-z-system-requirements_{context}"]
== Preferred IBM Z system requirements

[discrete]
=== Hardware requirements

* 3 LPARs with 6 IFLs that support SMT2
* 1 or 2 OSA or RoCE network adapters, or both

[discrete]
=== Operating system requirements

* 2 or 3 instances of z/VM 7.1 for high availability

On your z/VM instances, set up:

* 3 guest virtual machines for {product-title} control plane machines, one per z/VM instance
* At least 6 guest virtual machines for {product-title} compute machines, distributed across the z/VM instances
* 1 guest virtual machine for the temporary {product-title} bootstrap machine

[discrete]
=== Disk storage for the z/VM guest virtual machines

* FICON attached disk storage (DASDs). These can be z/VM minidisks, fullpack minidisks, or dedicated DASDs. If available, use HyperPAV to ensure optimal performance.
+
[NOTE]
====
In {product-title} {product-version}, you must use DASD disks if you require multi-path support.
====
* FCP attached disk storage in single-path configuration.

[discrete]
=== Storage / Main Memory

* 16 GB for {product-title} control plane machines
* 8 GB for {product-title} compute machines
* 16 GB for the temporary {product-title} bootstrap machine
endif::ibm-z[]

[id="csr_management_{context}"]
== Certificate signing requests management

Because your cluster has limited access to automatic machine management when you
use infrastructure that you provision, you must provide a mechanism for approving
cluster certificate signing requests (CSRs) after installation. The
`kube-controller-manager` only approves the kubelet client CSRs. The
`machine-approver` cannot guarantee the validity of a serving certificate
that is requested by using kubelet credentials because it cannot confirm that
the correct machine issued the request. You must determine and implement a
method of verifying the validity of the kubelet serving certificate requests
and approving them.

ifeval::["{context}" == "installing-ibm-z"]
:!ibm-z:
endif::[]
