// Module included in the following assemblies:
//
// * installing/installing_nutanix/nutanix-failure-domains.adoc
// * post_installation_configuration/adding-nutanix-failure-domains.adoc

:_mod-docs-content-type: CONCEPT
[id="installation-nutanix-failure-domains-req_{context}"]
= Failure domain requirements

When planning to use failure domains, consider the following requirements:

* All Nutanix Prism Element instances must be managed by the same instance of Prism Central. A deployment that is comprised of multiple Prism Central instances is not supported.
* The machines that make up the Prism Element clusters must reside on the same Ethernet network for failure domains to be able to communicate with each other.
* A subnet is required in each Prism Element that will be used as a failure domain in the {product-title} cluster. When defining these subnets, they must share the same IP address prefix (CIDR) and should contain the virtual IP addresses that the {product-title} cluster uses.
