// Module included in the following assemblies:
//
// * installing/installing_ibm_z/installing-restricted-networks-ibm-z-kvm.adoc
// * installing/installing_ibm_z/installing-ibm-z-kvm.adoc

:_mod-docs-content-type: CONCEPT
[id="installation-ibm-z-kvm-user-infra-installing-rhcos_{context}"]
= Installing {op-system} and starting the {product-title} bootstrap process

To install {product-title} on {ibm-z-name} infrastructure that you provision, you must install {op-system-first} as {op-system-base-full} guest virtual machines. When you install {op-system}, you must provide the Ignition config file that was generated by the {product-title} installation program for the type of machine you are installing. If you have configured suitable networking, DNS, and load balancing infrastructure, the {product-title} bootstrap process begins automatically after the {op-system} machines have rebooted.

You can perform a fast-track installation of {op-system} that uses a prepackaged QEMU copy-on-write (QCOW2) disk image. Alternatively, you can perform a full installation on a new QCOW2 disk image.

To add further security to your system, you can optionally install {op-system} using {ibm-name} Secure Execution before proceeding to the fast-track installation.
