[id="installing-getting-debug-information"]
= Getting debug information for installation failures
include::modules/common-attributes.adoc[]
:context: installing-getting-debug-information

Optionally, do the following to debug a failed installation:

* Run the installer with `--log-level=debug`:
----
$ sudo ./openshift-install create cluster --dir=assets-dir --log-level=debug
----

* Inspect the debug messages. To see the log from a past installation, look in the assets directory for the hidden file, `.openshift_install.log`. For example, enter:
----
$ cat ~/assets-dir/.openshift_install.log
----

* Gather the most relevant error messages from the installer. For example:
----
$ sudo ./openshift-install gather bootstrap
FATAL bootstrap host address and at least one control plane host address must be provided
----

* Check for timeout errors.
Sometimes, the installer times out while the {product-title} cluster is spinning up in the background. The installer has three stages where it waits for cluster events. As the events happen, the installer displays status messages:

** *Bootstrap*: After 20 minutes,  `Waiting up to %v for bootstrapping to complete...`
** *Initialization*: After 30 minutes, `Waiting up to %v for the cluster at %s to initialize...`
** *Console route created*: After 10 minutes, `Waiting up to %v for the openshift-console route to be created...`

Then use the `wait-for` subcommands to troubleshoot issues related to these stages.

To wait until cluster bootstrapping has completed:
----
$ sudo ./openshift-install wait-for bootstrap-complete
----

To wait until the cluster is ready:
----
$ sudo ./openshift-install wait-for install-complete
----
