// Module included in the following assemblies:
//
// * installing/install_cloud_ocp/install-secured-cluster-cloud-ocp.adoc
// * installing/installing_ocp/install-secured-cluster-ocp.adoc

:_mod-docs-content-type: PROCEDURE
[id="install-secured-cluster-operator_{context}"]
= Installing secured cluster services

ifeval::["{context}" == "install-secured-cluster-cloud-ocp"]
:cloud-svc:
endif::[]

[role="_abstract"]
You can install Secured Cluster services on your clusters by using the Operator, which creates the `SecuredCluster` custom resource. You must install the Secured Cluster services on every cluster in your environment that you want to monitor.

[IMPORTANT]
====
When you install {product-title}:

* If you are installing {product-title-short} for the first time, you must first install the `Central` custom resource because the `SecuredCluster` custom resource installation is dependent on certificates that Central generates.
* Do not install `SecuredCluster` in projects whose names start with `kube`, `openshift`, or `redhat`, or in the `istio-system` project.
* If you are installing {product-title-short} `SecuredCluster` custom resource on a cluster that also hosts Central, ensure that you install it in the same namespace as Central.
* If you are installing {product-title} `SecuredCluster` custom resource on a cluster that does not host Central, Red{nbsp}Hat recommends that you install the {product-title} `SecuredCluster` custom resource in its own project and not in the project in which you have installed the {product-title} Operator.
====

.Prerequisites
* If you are using {ocp}, you must install version {ocp-supported-version} or later.
* You have installed the {product-title-short} Operator on the cluster that you want to secure, called the secured cluster.
* You have generated an init bundle or cluster registration secret (CRS) and applied it to the cluster in the recommended `stackrox` namespace.

.Procedure
. On the {ocp} web console for the secured cluster, go to the *Operators* -> *Installed Operators* page.
. Click the {product-title-short} Operator.
. If you have installed the Operator in the recommended namespace, {ocp} lists the project as `rhacs-operator`. Select *Project: rhacs-operator* -> *Create project*.
+
[NOTE]
====
* If you installed the Operator in a different namespace, {ocp} lists the name of that namespace instead of `rhacs-operator`.
====
. Click *Installed Operators*.
. You should have created the `stackrox` namespace when you applied the init bundle or the CRS. Make sure that you are in this namespace by verifying that *Project:stackrox* is selected in the menu.
. In *Provided APIs*, click *Secured Cluster*.
. Click *Create SecuredCluster*.
. Select one of the following options in the *Configure via* field:
* *Form view*: Use this option if you want to use the on-screen fields to configure the secured cluster and do not need to change any other fields.
* *YAML view*: Use this view to set up the secured cluster by using the YAML file. The YAML file is displayed in the window and you can edit fields in it. If you select this option, when you are finished editing the file, click *Create*.
. If you are using *Form view*, enter the new project name by accepting or editing the default name. The default value is *stackrox-secured-cluster-services*.
. Optional: Add any labels for the cluster.
. Enter a unique name for your `SecuredCluster` custom resource.
. For *Central Endpoint*, enter the address of your Central instance. For example, if Central is available at `\https://central.example.com`, then specify the central endpoint as `central.example.com`.
ifdef::cloud-svc[]
*  For {product-title-managed-short} use the *Central API Endpoint* address. You can view this information by choosing *Advanced Cluster Security* -> *ACS Instances* from the Red{nbsp}Hat Hybrid Cloud Console navigation menu, then clicking the {product-title-short} instance you created.
endif::cloud-svc[]
* Use the default value of `central.stackrox.svc:443` _only_ if you are installing secured cluster services in the same cluster where Central is installed.
* Do not use the default value when you are configuring multiple clusters. Instead, use the hostname when configuring the *Central Endpoint* value for each cluster.
. For the remaining fields, accept the default values or configure custom values if needed. For example, you might need to configure TLS if you are using custom certificates or untrusted CAs. See "Configuring Secured Cluster services options for {product-title-short} using the Operator" for more information.
. Click *Create*.
. After a brief pause, the *SecuredClusters* page displays the status of `stackrox-secured-cluster-services`. You might see the following conditions:
* *Conditions: Deployed, Initialized*: The secured cluster services have been installed and the secured cluster is communicating with Central.
* *Conditions: Initialized, Irreconcilable*: The secured cluster is not communicating with Central. Make sure that you applied the init bundle you created in the {product-title-short} web portal to the secured cluster.

.Next steps
. Configure additional secured cluster settings (optional).
. Verify installation.

ifeval::["{context}" == "install-secured-cluster-cloud-ocp"]
:!cloud-svc:
endif::[]
