// Module included in the following assemblies:
//
// * installing/installing_azure/installing-azure-user-infra.adoc
// * installing/installing_azure_stack_hub/installing-azure-stack-hub-user-infra.adoc
// * installing/installing_azure/installing-restricted-networks-azure-user-provisioned.adoc

ifeval::["{context}" == "installing-azure-user-infra"]
:azure:
endif::[]
ifeval::["{context}" == "installing-azure-stack-hub-user-infra"]
:ash:
endif::[]
ifeval::["{context}" == "installing-restricted-networks-azure-user-provisioned"]
:azure:
endif::[]

:_mod-docs-content-type: PROCEDURE
[id="installation-azure-create-resource-group-and-identity_{context}"]
= Creating the Azure resource group

ifdef::azure[]
You must create a Microsoft Azure link:https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview#resource-groups[resource group] before installing your {product-title} on {azure-first}.
endif::azure[]
ifdef::ash[]
You must create a Microsoft Azure link:https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview#resource-groups[resource group]. This is used during the installation of your {product-title} cluster on Azure Stack Hub.
endif::ash[]

.Procedure

ifdef::azure[]
. Create the resource group in a supported Azure region:
endif::azure[]
ifdef::ash[]
* Create the resource group in a supported Azure region:
endif::ash[]
+
[source,terminal]
----
$ az group create --name ${RESOURCE_GROUP} --location ${AZURE_REGION}
----

ifeval::["{context}" == "installing-azure-user-infra"]
:!azure:
endif::[]
ifeval::["{context}" == "installing-azure-stack-hub-user-infra"]
:!ash:
endif::[]
ifeval::["{context}" == "installing-restricted-networks-azure-user-provisioned"]
:!azure:
endif::[]
