// Module included in the following assemblies:
//
// * installing/installing_vmc/installing-restricted-networks-vmc-user-infra.adoc
// * installing/installing_vmc/installing-vmc-network-customizations-user-infra.adoc
// * installing/installing_vmc/installing-vmc-user-infra.adoc
// * installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
// * installing/installing_vsphere/installing-vsphere-network-customizations.adoc
// * installing/installing_vsphere/installing-vsphere.adoc

ifeval::["{context}" == "installing-restricted-networks-vsphere"]
:restricted:
endif::[]
ifeval::["{context}" == "installing-restricted-networks-vmc-user-infra"]
:restricted:
endif::[]

[id="installation-vsphere-config-yaml_{context}"]
= Sample `install-config.yaml` file for VMware vSphere

You can customize the `install-config.yaml` file to specify more details about
your {product-title} cluster's platform or modify the values of the required
parameters.

[source,yaml]
----
apiVersion: v1
baseDomain: example.com <1>
compute:
- hyperthreading: Enabled <2> <3>
  name: worker
  replicas: 0 <4>
controlPlane:
  hyperthreading: Enabled <2> <3>
  name: master
  replicas: 3 <5>
metadata:
  name: test <6>
platform:
  vsphere:
    vcenter: your.vcenter.server <7>
    username: username <8>
    password: password <9>
    datacenter: datacenter <10>
    defaultDatastore: datastore <11>
    folder: "/<datacenter_name>/vm/<folder_name>/<subfolder_name>" <12>
ifndef::restricted[]
ifndef::openshift-origin[]
fips: false <13>
endif::openshift-origin[]
ifndef::openshift-origin[]
pullSecret: '{"auths": ...}' <14>
endif::openshift-origin[]
ifdef::openshift-origin[]
pullSecret: '{"auths": ...}' <13>
endif::openshift-origin[]
endif::restricted[]
ifdef::restricted[]
ifndef::openshift-origin[]
fips: false <13>
pullSecret: '{"auths":{"<local_registry>": {"auth": "<credentials>","email": "you@example.com"}}}' <14>
endif::openshift-origin[]
ifdef::openshift-origin[]
pullSecret: '{"auths":{"<local_registry>": {"auth": "<credentials>","email": "you@example.com"}}}' <13>
endif::openshift-origin[]
endif::restricted[]
ifndef::openshift-origin[]
sshKey: 'ssh-ed25519 AAAA...' <15>
endif::openshift-origin[]
ifdef::openshift-origin[]
sshKey: 'ssh-ed25519 AAAA...' <14>
endif::openshift-origin[]
ifdef::restricted[]
ifndef::openshift-origin[]
additionalTrustBundle: | <16>
  -----BEGIN CERTIFICATE-----
  ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
  -----END CERTIFICATE-----
imageContentSources: <17>
- mirrors:
  - <local_registry>/<local_repository_name>/release
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - <local_registry>/<local_repository_name>/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
endif::openshift-origin[]
ifdef::openshift-origin[]
additionalTrustBundle: | <15>
  -----BEGIN CERTIFICATE-----
  ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
  -----END CERTIFICATE-----
imageContentSources: <16>
- mirrors:
  - <local_registry>/<local_repository_name>/release
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - <local_registry>/<local_repository_name>/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
endif::openshift-origin[]
endif::restricted[]
----
<1> The base domain of the cluster. All DNS records must be sub-domains of this
base and include the cluster name.
<2> The `controlPlane` section is a single mapping, but the compute section is a
sequence of mappings. To meet the requirements of the different data structures,
the first line of the `compute` section must begin with a hyphen, `-`, and the
first line of the `controlPlane` section must not. Although both sections
currently define a single machine pool, it is possible that future versions
of {product-title} will support defining multiple compute pools during
installation. Only one control plane pool is used.
<3> Whether to enable or disable simultaneous multithreading, or
`hyperthreading`. By default, simultaneous multithreading is enabled
to increase the performance of your machines' cores. You can disable it by
setting the parameter value to `Disabled`. If you disable simultaneous
multithreading in some cluster machines, you must disable it in all cluster
machines.
+
[IMPORTANT]
====
If you disable simultaneous multithreading, ensure that your capacity planning
accounts for the dramatically decreased machine performance.
Your machines must use at least 8 CPUs and 32 GB of RAM if you disable
simultaneous multithreading.
====
<4> You must set the value of the `replicas` parameter to `0`. This parameter
controls the number of workers that the cluster creates and manages for you,
which are functions that the cluster does not perform when you
use user-provisioned infrastructure. You must manually deploy worker
machines for the cluster to use before you finish installing {product-title}.
<5> The number of control plane machines that you add to the cluster. Because
the cluster uses this values as the number of etcd endpoints in the cluster, the
value must match the number of control plane machines that you deploy.
<6> The cluster name that you specified in your DNS records.
<7> The fully-qualified hostname or IP address of the vCenter server.
<8> The name of the user for accessing the server. This user must have at least
the roles and privileges that are required for
link:https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html[static or dynamic persistent volume provisioning]
in vSphere.
<9> The password associated with the vSphere user.
<10> The vSphere datacenter.
<11> The default vSphere datastore to use.
<12> Optional: For installer-provisioned infrastructure, the absolute path of an existing folder where the installation program creates the virtual machines, for example, `/<datacenter_name>/vm/<folder_name>/<subfolder_name>`. If you do not provide this value, the installation program creates a top-level folder in the datacenter virtual machine folder that is named with the infrastructure ID. If you are providing the infrastructure for the cluster, omit this parameter.
ifndef::openshift-origin[]
<13> Whether to enable or disable FIPS mode. By default, FIPS mode is not enabled. If FIPS mode is enabled, the {op-system-first} machines that {product-title} runs on bypass the default Kubernetes cryptography suite and use the cryptography modules that are provided with {op-system} instead.
+
[IMPORTANT]
====
The use of FIPS Validated / Modules in Process cryptographic libraries is only supported on {product-title} deployments on the `x86_64` architecture.
====
endif::openshift-origin[]
ifndef::restricted[]
ifndef::openshift-origin[]
<14> The pull secret that you obtained from the
link:https://console.redhat.com/openshift/install/pull-secret[Pull Secret] page on the {console-redhat-com} site. This pull secret allows you to authenticate with the services that are
provided by the included authorities, including Quay.io, which serves the
container images for {product-title} components.
<15> The public portion of the default SSH key for the `core` user in
{op-system-first}.
endif::openshift-origin[]
ifdef::openshift-origin[]
<13> The pull secret that you obtained from the
link:https://console.redhat.com/openshift/install/pull-secret[Pull Secret] page on the {console-redhat-com} site. This pull secret allows you to authenticate with the services that are
provided by the included authorities, including Quay.io, which serves the
container images for {product-title} components.
<14> The public portion of the default SSH key for the `core` user in
{op-system-first}.
+
[NOTE]
====
For production {product-title} clusters on which you want to perform installation debugging or disaster recovery, specify an SSH key that your `ssh-agent` process uses.
====
endif::openshift-origin[]
endif::restricted[]
ifdef::restricted[]
ifndef::openshift-origin[]
<14> For `<local_registry>`, specify the registry domain name, and optionally the
port, that your mirror registry uses to serve content. For example
`registry.example.com` or `registry.example.com:5000`. For `<credentials>`,
specify the base64-encoded user name and password for your mirror registry.
<15> The public portion of the default SSH key for the `core` user in
{op-system-first}.
+
[NOTE]
====
For production {product-title} clusters on which you want to perform installation debugging or disaster recovery, specify an SSH key that your `ssh-agent` process uses.
====
endif::openshift-origin[]
ifdef::openshift-origin[]
<13> For `<local_registry>`, specify the registry domain name, and optionally the
port, that your mirror registry uses to serve content. For example
`registry.example.com` or `registry.example.com:5000`. For `<credentials>`,
specify the base64-encoded user name and password for your mirror registry.
<14> The public portion of the default SSH key for the `core` user in
{op-system-first}.
+
[NOTE]
====
For production {product-title} clusters on which you want to perform installation debugging or disaster recovery, specify an SSH key that your `ssh-agent` process uses.
====
endif::openshift-origin[]
endif::restricted[]
ifdef::restricted[]
ifndef::openshift-origin[]
<16> Provide the contents of the certificate file that you used for your mirror
registry.
<17> Provide the `imageContentSources` section from the output of the command to
mirror the repository.
endif::openshift-origin[]
ifdef::openshift-origin[]
<15> Provide the contents of the certificate file that you used for your mirror
registry.
<16> Provide the `imageContentSources` section from the output of the command to
mirror the repository.
endif::openshift-origin[]
endif::restricted[]

ifeval::["{context}" == "installing-restricted-networks-vsphere"]
:!restricted:
endif::[]
ifdef::openshift-origin[]
:!restricted:
endif::[]
ifeval::["{context}" == "installing-restricted-networks-vmc-user-infra"]
:!restricted:
endif::[]
