// Module included in the following assemblies:
//
// * installing/install-ocp-operator.adoc
:_module-type: PROCEDURE
[id="install-secured-cluster-operator_{context}"]
= Installing secured cluster services

[role="_abstract"]
You can install secured cluster services on your clusters by using the `SecuredCluster` custom resource. You must install the secured cluster services on every cluster in your environment that you want to monitor.

[CAUTION]
====
To install Collector on systems configured with Unified Extensible Firmware Interface (UEFI) boot, you must use eBPF probes because kernel modules are unsigned, and the UEFI firmware cannot load unsigned packages.
====

.Prerequisites
* You must be using {ocp} 4.6 or later.
* Unless you are installing the `SecuredCluster` resource in the same namespace in which a `Central` resource exists, you must have generated an init bundle and already created the required resources by using the init bundle. If a `Central` resource exists in the same namespace, the operator will provision an init bundle automatically for you.

.Procedure
. On the {ocp} web console, navigate to the *Operators* -> *Installed Operators* page.
. Select the {product-title} Operator form the list of installed operators.
. By default, {ocp} lists the project as `openshift-operator`. Select *Project: openshift-operator* -> *Create project*.
+
[WARNING]
====
You must install {product-title} `SecuredCluster` resource in its own project and not the default `openshift-operators` project.
====
. Enter the new project name as *stackrox* or some other name, and click *Create*.
. Under the *Provided APIs* section, select *Create instance* on the *Secured Cluster* API.
. Enter a name for your `SecuredCluster` custom resource.
. For *Central Endpoint*, enter the address and port number of your Central instance.
For example, if Central is available at `\https://central.example.com`, then specify the central endpoint as `central.example.com:443`.
The default value of `central.stackrox.svc:443` only works when you install secured cluster services and Central in the same cluster.
. Accept the default values or configure custom values for the avilable options.
//Add a link for customization options
. Click *Create*.
