// Module included in the following assemblies:
//
// * installing/installing_aws/installing-restricted-networks-aws.adoc
// * installing/installing_bare_metal/installing-restricted-networks-bare-metal.adoc
// * installing/installing_vsphere/installing-restricted-networks-vsphere.adoc

[id="installation-about-restricted-networks_{context}"]
= About installations in restricted networks

In {product-title} {product-version}, you can perform an installation that does not
require an active connection to the internet to obtain software components. You
complete an installation in a restricted network on only infrastructure that you provision,
not infrastructure that the installation program provisions, so your platform selection is
limited.
// maybe point out that you can follow the bare metal installation rules on supported hardware and link to the matrix

If you choose to perform a restricted network installation on a cloud platform, you
still require access to its cloud APIs. Some cloud functions, like
Amazon Web Service's IAM service, require internet access, so you might still
require internet access.
//behind a proxy
Depending on your network, you might require less internet
access for an installation on bare metal hardware or on VMware vSphere.

To complete a restricted network installation, you must create a registry that
mirrors the contents of the {product-title} registry and contains the
installation media. You can create this mirror on a bastion host, which can
access both the internet and your closed network, or by using other methods
that meet your restrictions.

[IMPORTANT]
====
Restricted network installations always use user-provisioned infrastructure.
Because of the complexity of the configuration for user-provisioned installations,
consider completing a standard user-provisioned infrastructure installation before
you attempt a restricted network installation. Completing this test installation might
make it easier to isolate and troubleshoot any issues that might arise
during your installation in a restricted network.
====

[id="installation-restricted-network-limits{context}"]
== Additional limits

Clusters in restricted networks have the following additional limitations and restrictions:

* The ClusterVersion status includes an `Unable to retrieve available updates`
error.
//* The authentication Operator might randomly fail.
* By default, you cannot use the contents of the Developer Catalog because
 you cannot access the required ImageStreamTags.
//* The `TelemeterClientDown` and `Watchdog` alerts from the monitoring Operator always display.
