// Module included in the following assemblies:
//
// * installing/insall_config/enable-cluster-wide-proxy.adoc

[id="installation-proxy-configure-object_{context}"]
= Configure the Proxy object

A cluster administrator can interact with the `Proxy` object using
{product-title} `oc` commands.

.Prerequisites

* Cluster administrator permissions
* {product-title} `oc` commands installed

.Procedure

. Use the `oc edit` command to modify the `Proxy` object:

----
$ oc edit proxy/cluster -o yaml
----

. Use the `oc get` command to view the modified file:

----
$ oc get proxy/cluster -o yaml
apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  creationTimestamp: "2019-08-21T22:36:49Z"
  generation: 2
  name: cluster
  resourceVersion: "24913"
  selfLink: /apis/config.openshift.io/v1/proxies/cluster
  uid: <user ID string>
spec:
  httpProxy: <http://proxy>
  httpsProxy: <https://proxy>
  noProxy: example.com
  readinessEndpoints:
  - http://www.google.com
  - https://www.google.com
  trustedCA:
    name: user-ca-bundle
status:
  httpProxy: <http://proxy>
  httpsProxy: <https://proxy>
  noProxy: <IPs and URLs>
  ----
