// Module included in the following assemblies:
//
// * installing/installing_azure/installing-azure-user-infra.adoc
// * installing/installing_azure_stack_hub/installing-azure-stack-hub-user-infra.adoc

ifeval::["{context}" == "installing-azure-user-infra"]
:azure:
endif::[]
ifeval::["{context}" == "installing-azure-stack-hub-user-infra"]
:ash:
endif::[]

[id="installation-azure-user-infra-uploading-rhcos_{context}"]
= Uploading the {op-system} cluster image and bootstrap Ignition config file

The Azure client does not support deployments based on files existing locally;
therefore, you must copy and store the {op-system} virtual hard disk (VHD)
cluster image and bootstrap Ignition config file in a storage container so they
are accessible during deployment.

.Prerequisites

* Configure an Azure account.

* Generate the Ignition config files for your cluster.

.Procedure

. Create an Azure storage account to store the VHD cluster image:
+
[source,terminal]
----
$ az storage account create -g ${RESOURCE_GROUP} --location ${AZURE_REGION} --name ${CLUSTER_NAME}sa --kind Storage --sku Standard_LRS
----
+
[WARNING]
====
The Azure storage account name must be between 3 and 24 characters in length and
use numbers and lower-case letters only. If your `CLUSTER_NAME` variable does
not follow these restrictions, you must manually define the Azure storage
account name. For more information on Azure storage account name restrictions,
see link:https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/error-storage-account-name[Resolve errors for storage account names]
in the Azure documentation.
====

. Export the storage account key as an environment variable:
+
[source,terminal]
----
$ export ACCOUNT_KEY=`az storage account keys list -g ${RESOURCE_GROUP} --account-name ${CLUSTER_NAME}sa --query "[0].value" -o tsv`
----

. Export the URL of the {op-system} VHD to an environment variable:
+
ifdef::azure[]
[source,terminal]
----
$ export VHD_URL=`openshift-install coreos print-stream-json | jq -r '.architectures.x86_64."rhel-coreos-extensions"."azure-disk".url'`
----
endif::azure[]
ifdef::ash[]
[source,terminal]
----
$ export COMPRESSED_VHD_URL=`openshift-install coreos print-stream-json | jq -r '.architectures.x86_64.artifacts.azurestack.formats."vhd.gz".disk.location'`
----
endif::ash[]
+
[IMPORTANT]
====
The {op-system} images might not change with every release of {product-title}.
You must specify an image with the highest version that is
less than or equal to the {product-title} version that you install. Use the image version
that matches your {product-title} version if it is available.
====

. Create the storage container for the VHD:
+
[source,terminal]
----
$ az storage container create --name vhd --account-name ${CLUSTER_NAME}sa --account-key ${ACCOUNT_KEY}
----
ifdef::ash[]
. Download the compressed {op-system} VHD file locally:
+
[source,terminal]
----
$ curl -O -L ${COMPRESSED_VHD_URL}
----

. Decompress the VHD file.
+
[NOTE]
====
The decompressed VHD file is approximately 16 GB, so be sure that your host system has 16 GB of free space available. The VHD file can be deleted once you have uploaded it.
====
endif::ash[]

. Copy the chosen VHD to a blob:
+
ifdef::azure[]
[source,terminal]
----
$ az storage blob copy start --account-name ${CLUSTER_NAME}sa --account-key ${ACCOUNT_KEY} --destination-blob "rhcos.vhd" --destination-container vhd --source-uri "${VHD_URL}"
----
endif::azure[]
ifdef::ash[]
[source,terminal]
----
$ az storage blob upload --account-name ${CLUSTER_NAME}sa --account-key ${ACCOUNT_KEY} -c vhd -n "rhcos.vhd" -f rhcos-<rhcos_version>-azurestack.x86_64.vhd
----
endif::ash[]

. Create a blob storage container and upload the generated `bootstrap.ign` file:
+
[source,terminal]
----
$ az storage container create --name files --account-name ${CLUSTER_NAME}sa --account-key ${ACCOUNT_KEY}
----
+
[source,terminal]
----
$ az storage blob upload --account-name ${CLUSTER_NAME}sa --account-key ${ACCOUNT_KEY} -c "files" -f "<installation_directory>/bootstrap.ign" -n "bootstrap.ign"
----

ifeval::["{context}" == "installing-azure-user-infra"]
:!azure:
endif::[]
ifeval::["{context}" == "installing-azure-stack-hub-user-infra"]
:!ash:
endif::[]