// Module included in the following assemblies:
//
// * installing/installing_aws_user_infra/installing-aws-user-infra.adoc

[id="installation-extracting-infraid_{context}"]
= Extracting the infrastructure name

The Ignition configs contain a unique cluster identifier that you can use to
uniquely identify your cluster in Amazon Web Services (AWS) tags. The provided
CloudFormation templates contain references to this tag, so you must extract
it.

.Prerequisites

* Obtain the {product-title} installation program and the access token for your cluster.
* Generate the Ignition config files for your cluster.
* Install the `jq` package.

.Procedure

* To extract the infrastructure name from the Ignition config file metadata, run
the following command:
+
----
$ jq -r .infraID /<installation_directory>/metadata.json <1>
openshift-vw9j6 <2>
----
<1> For `<installation_directory>`, specify the path to the directory that you stored the
installation files in.
<2> The output of this command is your cluster name and a random string.
+
You need the output of this command to configure the provided CloudFormation
templates and can use it in other AWS tags.
