// Module included in the following assemblies:
//
// * installing/installing_vsphere/installing-restricted-networks-vsphere.adoc
// * installing/installing_vsphere/installing-vsphere.adoc
// * installing/installing_vsphere/installing-vsphere-network-customizations.adoc

[id="installation-required-vcenter-account-privileges_{context}"]
= Required vCenter account privileges

To install an {product-title} cluster in vCenter, the cluster requires access to an account with privileges to read and create the required resources. Using an account that has administrative privileges is the simplest way to access all of the necessary permissions.

A user requires the following privileges to install an {product-title} cluster:

* Datastore
** *Allocate space*
* Folder
** *Create folder*
** *Delete folder*
* vSphere Tagging
** All privileges
* Network
** *Assign network*
* Resource
** *Assign virtual machine to resource pool*
* Profile-driven storage
** All privileges
* vApp
** All privileges
* Virtual machine
** All privileges

For more information about creating an account with only the required privileges, see link:https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-5372F580-5C23-4E9C-8A4E-EF1B4DD9033E.html[vSphere Permissions and User Management Tasks] in the vSphere documentation.