// Module included in the following assemblies:
//
// * installing/installing_bare_metal_ipi/ipi-install-prerequisites.adoc

[id='node-requirements_{context}']
= Node requirements

IPI installation involves a number of hardware node requirements:

- **CPU architecture:** All nodes *must* use `x86_64` CPU architecture.

- **Unified Extensible Firmware Interface (UEFI):** UEFI boot is required on all {product-title} nodes when using IPv6 addressing on the provisioning network. In addition, UEFI Device PXE Settings must be set to use the IPv6 protocol on the provisioning network NIC.

- **Similar nodes:** Nodes *should* have an identical configuration per role. That is, control plane nodes *should* be the same brand and model with the same CPU, RAM and storage configuration. Worker nodes should be *identical*.

- **Baseboard Management Controller:** The `provisioner` node must be able to access the baseboard management controller (BMC) of each {product-title} cluster node. You may use IPMI, RedFish, or a proprietary protocol.

- **Latest generation:** Nodes should be of the most recent generation. IPI installation relies on IPMI, which should be compatible across nodes. Additionally, {op-system-base} 8 ships with the most recent drivers for RAID controllers. Ensure that the nodes are recent enough to support {op-system-base} 8 for the `provisioner` node and {op-system} 8 for the worker nodes.

- **Network interfaces:** Each node *must* have at least two 10 GB network interfaces (NICs)- one for the `provisioning` network and one for the routable `baremetal` network. Network interface names *must* follow the same naming convention across all nodes. For example, the first NIC name on a node, such as `eth0` or `eno1`, should be the same name on all of the other nodes.
The same principle applies to the remaining NICs on each node.

- **Registry node:** (Optional) If setting up a disconnected mirrored registry, it is recommended the registry reside in its own node.

- **Provisioner node:** IPI installation requires one `provisioner` node.

- **Control plane:** IPI installation requires three Control Plane (master) nodes for high availability.

- **Worker nodes:** A typical production cluster will have many worker nodes. IPI installation in a high availability environment requires at least two worker nodes in an initial cluster.
