// Module included in the following assemblies:
//
// * authentication/ldap-syncing.adoc

:_mod-docs-content-type: PROCEDURE
[id="ldap-syncing-pruning_{context}"]
= Running a group pruning job

[role="_abstract"]
Run a group pruning job to remove LDAP-synced groups from {product-title} when they no longer exist on your LDAP server so you can keep cluster group records aligned with your directory.

An administrator can also choose to remove groups from {product-title} records if the records on the LDAP server that created them are no longer present. The prune job accepts the same sync configuration file and allowlists or denylists as used for the sync job.

.Procedure

. To prune groups using a sync configuration file, run the following command:
+
[source,terminal]
----
$ oc adm prune groups --sync-config=/path/to/ldap-sync-config.yaml --confirm
----

. To prune groups using an allowlist file, run the following command:
+
[source,terminal]
----
$ oc adm prune groups --whitelist=/path/to/whitelist.txt --sync-config=/path/to/ldap-sync-config.yaml --confirm
----

. To prune groups using a denylist file, run the following command:
+
[source,terminal]
----
$ oc adm prune groups --blacklist=/path/to/blacklist.txt --sync-config=/path/to/ldap-sync-config.yaml --confirm
----
