// Module included in the following assemblies:
//
// * rosa_architecture/rosa_policy_service_definition/rosa-life-cycle.adoc
// * osd_architecture/osd_policy/osd-life-cycle.adoc

[id="rosa-limited-support_{context}"]
= Limited support status for End of Life minor versions

When a cluster transitions to a _Limited Support_ status due to the cluster's minor version being End of Life, Red Hat no longer proactively monitors the cluster, the SLA is no longer applicable, and credits requested against the SLA are denied. Red Hat will only provide commercially reasonable support to upgrade from an unsupported version to a supported version. All other support requests must be preceeded by the cluster no longer being on an End of Life minor version before they will be acknowledged. Red Hat does not make any runtime or SLA guarantees for versions after their end-of-life date. To receive continued support, upgrade the cluster to a supported version prior to the end-of-life date. If you do not upgrade the cluster prior to the end-of-life date, the cluster transitions to a Limited Support status until it is upgraded to a supported version.
