// Module included in the following assemblies:
//
// * rosa_architecture/rosa_policy_service_definition/rosa-life-cycle.adoc
// * rosa_architecture/rosa_policy_service_definition/rosa-hcp-life-cycle.adoc
// * osd_architecture/osd_policy/osd-life-cycle.adoc

[id="sd-life-cycle-dates_{context}"]
= Life cycle dates

[options="header"]
|===
|Version    |General availability   |End of life   |Extended Update Support (EUS) end date^[1]^
|4.19       |Jun 16, 2025           |Oct 21, 2026  |
|4.18       |Feb 26, 2025           |Jun 21, 2026  |Dec 21, 2026
|4.17       |Oct 14, 2024           |Feb 14, 2026  |
|4.16       |Jul 2, 2024            |Dec 27, 2025  |Jun 27, 2026
|4.15       |Feb 27, 2024           |Aug 27, 2025  |
|===

1. Extended Update Support (EUS) is available for  {product-title} customers on even-numbered versions, starting with version 4.16. To apply EUS to your {product-title} cluster, you must update the channel group to EUS.
ifdef::openshift-rosa-hcp,openshift-rosa[]
For more information about updating your cluster channel, see xref:../../cli_reference/rosa_cli/rosa-manage-objects-cli.html#rosa-edit-cluster_rosa-managing-objects-cli[edit cluster].
endif::openshift-rosa-hcp,openshift-rosa[]
For more information about EUS, see link:https://access.redhat.com/support/policy/updates/openshift#eus[Extended Update Support Add-On - Term 1].
