// Module included in the following assemblies:
//
// * observability/logging/log_collection_forwarding/log-forwarding.adoc

:_mod-docs-content-type: PROCEDURE
[id="log-collector-resources-scheduling_{context}"]
= Configuring resources and scheduling for logging collectors

[role="_abstract"]
Administrators can change the resources and scheduling of the collector by configuring the `collector` field in a `ClusterLogForwarder` custom resource (CR).

.Prerequisites

* You have administrator permissions.
* You have installed {clo}.
* You have created a `ClusterLogForwarder` CR.

.Procedure

. Update the `ClusterLogForwarder` CR to configure scheduling and resources.
+
The following example schedules collectors on infrastructure nodes:
+
[source,yaml]
----
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collector:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
# ...
----
+
The following example schedules collectors on dedicated infrastructure nodes with taints:
+
[source,yaml]
----
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collector:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
    - key: node-role.kubernetes.io/infra
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/infra
      operator: Exists
      effect: NoExecute
# ...
----
+
The following example shows all available scheduling and resource fields:
+
[source,yaml]
----
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collector:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
    tolerations:
    - key: node-role.kubernetes.io/infra
      operator: Exists
      effect: NoSchedule
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: node-role.kubernetes.io/infra
              operator: Exists
          weight: 1
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - collector
            topologyKey: topology.kubernetes.io/zone
          weight: 100
# ...
----

. Apply the `ClusterLogForwarder` CR by running the following command:
+
[source,terminal]
----
$ oc apply -f <filename>.yaml
----
