// Module included in the following assemblies:
//
// * observability/logging/performance_reliability/logging-flow-control-mechanisms.adoc

:_mod-docs-content-type: PROCEDURE
[id="logging-set-input-rate-limit_{context}"]
= Configuring log forwarder input rate limits

[role="_abstract"]
Control the volume of logs collected from your cluster by setting rate limits on forwarders.

You can limit the rate of incoming logs that are collected by configuring the `ClusterLogForwarder` custom resource (CR). You can set input limits on a per-container or per-namespace basis.

.Prerequisites

* You have installed the {clo}.
* You have administrator permissions.

.Procedure

. Add a `maxRecordsPerSecond` limit value to the `ClusterLogForwarder` CR for a specified input.
+
The following examples show how to configure input rate limits for different scenarios:
+
.Example `ClusterLogForwarder` CR that sets a per-container limit for containers with certain labels
[source,yaml]
----
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
# ...
spec:
# ...
  inputs:
    - name: <input_name>
      application:
        selector:
          matchLabels: { example: label }
        containerLimit:
          maxRecordsPerSecond: 0
# ...
----

spec.inputs.name::
  The input name.

spec.inputs.application.selector.matchLabels::
  A list of labels. If these labels match labels that are applied to a pod, the per-container limit specified in the `maxRecordsPerSecond` field is applied to those containers.

spec.inputs.application.containerLimit.maxRecordsPerSecond::
  Configures the rate limit. Setting the `maxRecordsPerSecond` field to `0` means that no logs are collected for the container. Setting the `maxRecordsPerSecond` field to some other value means that a maximum of that number of records per second are collected for the container.
+
.Example `ClusterLogForwarder` CR that sets a per-container limit for containers in selected namespaces
[source,yaml]
----
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
# ...
spec:
# ...
  inputs:
    - name: <input_name>
      application:
        namespaces: [ example-ns-1, example-ns-2 ]
        containerLimit:
          maxRecordsPerSecond: 10
    - name: <input_name>
      application:
        namespaces: [ test ]
        containerLimit:
          maxRecordsPerSecond: 1000
# ...
----

spec.inputs.name::
  The input name.

spec.inputs.application.namespaces::
  A list of namespaces. The per-container limit specified in the `maxRecordsPerSecond` field is applied to all containers in the namespaces listed.

spec.inputs.application.containerLimit.maxRecordsPerSecond::
  Configures the rate limit. Setting the `maxRecordsPerSecond` field to `10` means that a maximum of 10 records per second are collected for each container in the namespaces listed.

. Apply the `ClusterLogForwarder` CR:
+
.Example command
[source,terminal]
----
$ oc apply -f <filename>.yaml
----
