// Module included in the following assemblies:
//
// storage/persistent_storage/persistent_storage_local/persistent-storage-using-lvms.adoc

:_mod-docs-content-type: CONCEPT
[id="lvms-about-volume-clones_{context}"]
= About volume clones

[role="_abstract"]
A volume clone is a duplicate of an existing persistent volume claim (PVC) that creates a point-in-time copy of data more efficiently than snapshots, useful for testing, development, or creating independent copies of application data.

== Limitations for creating volume clones in multi-node topology

{lvms} has the following limitations for creating volume clones in multi-node topology:

* Creating volume clones is based on the LVM thin pool capabilities.
* The node must have additional storage after creating a volume clone for further updating the original data source.
* You can create volume clones only on the node where you have deployed the original data source.
* Pods relying on the PVC that uses the clone data can be scheduled only on the node where you have deployed the original data source.