// Module included in the following assemblies:
//
// * machine_management/manually-scaling-machineset.adoc

[id="machineset-manually-scaling_{context}"]
= Scaling a MachineSet manually

If you must add or remove an instance of a machine in a MachineSet, you can manually scale the MachineSet.

.Prerequisites

* Install an {product-title} cluster and the `oc` command line.
* Log in to  `oc` as a user with `cluster-admin` permission.

.Procedure

. View the MachineSets that are in the cluster:
+
----
$ oc get machinesets -n openshift-machine-api
----
+
The MachineSets are listed in the form of `<clusterid>-worker-<aws-region-az>`.

. Scale the MachineSet:
+
----
$ oc scale --replicas=2 machineset <machineset> -n openshift-machine-api
----
Or:
+
----
$ oc edit machineset <machineset> -n openshift-machine-api
----
+
You can scale the MachineSet up or down. It takes several minutes for the new
machines to be available.
+
[IMPORTANT]
====
By default, the {product-title} router pods are deployed on workers.
Because the router is required to access some cluster resources, including the
web console, do not scale the worker MachineSet to `1` or `0` unless you first
relocate the router pods.
====
