// Module included in the following assemblies:
//
// * machine_management/creating_machinesets/creating-machineset-aws.adoc
// * machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-aws.adoc

ifeval::["{context}" == "cpmso-supported-features-aws"]
:cpmso:
endif::[]

:_mod-docs-content-type: PROCEDURE
[id="machineset-creating-dedicated-instance_{context}"]
= Creating Dedicated Instances by using machine sets

[role="_abstract"]
You can configure a machine set to deploy machines as Dedicated Instances that run in a virtual private cloud (VPC) on hardware that only a single customer can use.
To change use Dedicated Instances, you update the placement tenancy value in the machine set custom resource (CR).

{aws-first} Dedicated Instances are EC2 instances that are physically isolated at the host hardware level.
This isolation applies to instances that a single payer account owns even if the instances belong to different {aws-short} accounts.

Public tenancy is the default tenancy.
Instances with public tenancy run on shared hardware and can share hardware with Dedicated Instances that  belong to the same {aws-short} account.

.Prerequisites

* You have access to the {oc-first} as a user with administrator privileges.

.Procedure

ifdef::cpmso[]
. Edit your control plane machine set custom resource (CR) by running the following command:
+
[source,terminal]
----
$ oc edit controlplanemachineset.machine.openshift.io cluster --namespace openshift-machine-api
----
endif::cpmso[]

ifndef::cpmso[]
. In a text editor, open an existing machine set custom resource (CR) or create a new one.
endif::cpmso[]

. Update the CR to implement your configuration changes:
+
[source,yaml]
----
ifdef::cpmso[]
apiVersion: machine.openshift.io/v1
kind: ControlPlaneMachineSet
# ...
spec:
  template:
    machines_v1beta1_machine_openshift_io:
      spec:
        providerSpec:
          value:
            placement:
              tenancy: dedicated
endif::cpmso[]
ifndef::cpmso[]
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
# ...
spec:
  template:
    spec:
      providerSpec:
        value:
          placement:
            tenancy: dedicated
endif::cpmso[]
----
+
To use Dedicated Instances, set the `placement.tenancy` parameter value to `dedicated`.

. Save your changes and exit the object specification.
ifdef::cpmso[]
+
When you save an update to the control plane machine set, the Control Plane Machine Set Operator updates the control plane machines according to your configured update strategy.

** For clusters that use the default `RollingUpdate` update strategy, the Operator automatically propagates the changes to your control plane configuration.

** For clusters that are configured to use the `OnDelete` update strategy, you must replace your control plane machines manually.
endif::cpmso[]

ifeval::["{context}" == "cpmso-supported-features-aws"]
:!cpmso:
endif::[]
