// Module included in the following assemblies:
//
// * machine_management/creating_machinesets/creating-machineset-vsphere.adoc
// * machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-vsphere.adoc

:_mod-docs-content-type: PROCEDURE
[id="machineset-vsphere-data-disks_{context}"]
= Configuring data disks by using machine sets

[role="_abstract"]
{product-title} clusters on {vmw-first} support adding up to 29 disks to the virtual machine (VM) controller.

:FeatureName: Configuring {vmw-short} data disks
include::snippets/technology-preview.adoc[]

By configuring data disks, you can attach disks to VMs and use them to store data for etcd, container images, and other uses.
Separating data can help avoid filling the primary disk so that important activities such as upgrades have the resources that they require.

[NOTE]
====
Adding data disks attaches them to the VM and mounts them to the location that {op-system} designates.
// To mount the data disks to a specific location, you must configure each machine to use the data disks according to your needs.
====

.Prerequisites

* You have administrator access to {oc-first} for an {product-title} cluster on {vmw-short}.

.Procedure

. In a text editor, open the YAML file for an existing machine set or create a new one.

. Edit the following lines under the `providerSpec` field:
+
--
[source,yaml]
----
tag::compute[]
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
end::compute[]
tag::controlplane[]
apiVersion: machine.openshift.io/v1
kind: ControlPlaneMachineSet
end::controlplane[]
# ...
spec:
  template:
tag::compute[]
    spec:
      providerSpec:
        value:
          dataDisks:
          - name: "<disk_name>"
            provisioningMode: "<mode>"
            sizeGiB: 20
          - name: "<disk_name>"
            provisioningMode: "<mode>"
            sizeGiB: 20
end::compute[]
tag::controlplane[]
    machines_v1beta1_machine_openshift_io:
      spec:
        providerSpec:
          value:
            dataDisks:
            - name: "<disk_name>"
              provisioningMode: "<mode>"
              sizeGiB: 20
            - name: "<disk_name>"
              provisioningMode: "<mode>"
              sizeGiB: 20
end::controlplane[]
# ...
----
--
+
where:
+
--
`dataDisks`:: Specifies a collection of 1-29 data disk definitions.
This sample configuration shows the formatting to include two data disk definitions.
`<disk_name>`:: Specifies the name of the data disk.
The name must meet the following requirements:
* Start and end with an alphanumeric character
* Consist only of alphanumeric characters, hyphens (`-`), and underscores (`_`)
* Have a maximum length of 80 characters
`<mode>`:: Specifies the data disk provisioning method.
This value defaults to the vSphere default storage policy if not set.
Valid values are `Thin`, `Thick`, and `EagerlyZeroed`.
`spec.template.spec.providerSpec.value.dataDisks.namesizeGiB`:: Specifies the size of the data disk in GiB. The maximum size is 16384 GiB.
`spec.template.machines_v1beta1_machine_openshift_io.spec. providerSpec.value.dataDisks.name.namesizeGiB`:: Specifies the size of the data disk in GiB. The maximum size is 16384 GiB.
--