// Module included in the following assemblies:
//
//Create a file with the YAML bits conditioned by platform.
// * machine_management/creating-infrastructure-machinesets.adoc
// * machine_management/creating_machinesets/creating-machineset-aws.adoc

ifeval::["{context}" == "creating-machineset-aws"]
:aws-mapi:
endif::[]
ifeval::["{context}" == "creating-machineset-azure"]
:azure-mapi:
endif::[]
ifeval::["{context}" == "creating-machineset-gcp"]
:gcp-mapi:
endif::[]

:_content-type: REFERENCE
[id="mapi-machine-set-yaml-universal_{context}"]
=  Sample YAML for a machine set custom resource

This sample YAML defines a machine set and demonstrates the required, recommended, and optional values for parameters in the default machine sets the installation program creates. Some parameters that appear in the default machine sets, such as `creationTimestamp` and `managedFields`, are omitted for brevity. Additional parameters in the `providerSpec` section to configure options and enable features that are platform-specific are not included in this example. 

ifdef::aws-mapi[]
[source,yaml]
----
include::snippets/mapi-machine-set-yaml-agnostic.adoc[]
        value:
          ami:
            id: ami-<ami_id_value_string> <6>
          apiVersion: awsproviderconfig.openshift.io/v1beta1 <7>
          blockDevices: <8>
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret: <9>
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: <infrastructure_id>-<role>-profile <1>
          instanceType: <aws_instance_type> <10>
          kind: AWSMachineProviderConfig <11>
          placement: <12>
            availabilityZone: <region><zone>
            region: <region>
          securityGroups: <13>
            - filters:
                - name: tag:Name
                  values:
                    - <infrastructure_id>-<role>-sg <1>
          subnet: <14>
            filters:
              - name: tag:Name
                values:
                  - <infrastructure_id>-private-<region><zone> <1>
          tags: <15>
            - name: kubernetes.io/cluster/<infrastructure_id> <1>
              value: owned
          userDataSecret: <16>
            name: worker-user-data
----
include::snippets/mapi-machine-set-yaml-agnostic-callouts.adoc[]
//The mapi-machine-set-yaml-agnostic snippet ends with callout <5>, so the first callout following that line must be <6>.
<6> The {op-system-first} Amazon Machine Image (AMI) ID for your AWS zone for your {product-title} nodes. You can obtain the AMI ID by running the following command:
+
[source,terminal]
----
$ oc -n openshift-machine-api \
    -o jsonpath='{.spec.template.spec.providerSpec.value.ami.id}{"\n"}' \
    get machineset/<infrastructure_id>-worker-<zone>
----
<7> The API version that the machine set uses. Do not change this value.
<8> The configuration for the block devices that your cluster uses.
<9> The {product-title} credentials secret for the cluster type. Do not change this value.
<10> The Amazon EC2 instance type that your cluster uses.
<11> The {product-title} resource kind for the cluster type. Do not change this value.
<12> The region and availability zone placement details for your cluster.
<13> The security group details for your cluster.
<14> The subnet details for your cluster. You can obtain the subnet by running the following command:
+
[source,terminal]
----
$  oc -n openshift-machine-api \
    -o jsonpath='{.spec.template.spec.providerSpec.value.subnet}{"\n"}' \
    get machineset/<infrastructure_id>-<role>-<region><zone>
----
<15> The {product-title} tag for your cluster. #What is this actually?# Do not change this value.
<16> The {product-title} user data secret for your cluster. Do not change this value.
endif::aws-mapi[]

ifdef::azure-mapi[]
[source,yaml]
----
include::snippets/mapi-machine-set-yaml-agnostic.adoc[]
        value:
          apiVersion: machine.openshift.io/v1beta1 <7>
          credentialsSecret: <8>
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          image: <9>
            offer: ""
            publisher: ""
            resourceID: /resourceGroups/<infrastructure_id>-rg/providers/Microsoft.Compute/images/<infrastructure_id> <10>
            sku: ""
            version: ""
          internalLoadBalancer: "" #This does not seem to be in the default machine sets.
          kind: AzureMachineProviderSpec <11>
          location: <region> <12>
          managedIdentity: <infrastructure_id>-identity <1>
          natRule: null #This does not seem to be in the default machine sets.
          networkResourceGroup: ""
          osDisk: <13>
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          publicLoadBalancer: <infrastructure_id> <1>
          resourceGroup: <infrastructure_id>-rg <1>
          sshPrivateKey: "" #This does not seem to be in the default machine sets.
          sshPublicKey: "" #This does not seem to be in the default machine sets.
          subnet: <infrastructure_id>-<role>-subnet <14>
          userDataSecret: <15>
            name: worker-user-data
          vmSize: <instance_size> <16>
          vnet: <infrastructure_id>-vnet <17>
          zone: <zone> <18>
----
include::snippets/mapi-machine-set-yaml-agnostic-callouts.adoc[]
//The mapi-machine-set-yaml-agnostic snippet ends with callout <6> for Azure, so the first callout following that line must be <7>.
<7> The API version that the machine set uses. Do not change this value.
<8> The {product-title} credentials secret for the cluster type. Do not change this value.
<9> The image details for machines created by this machine set.
<10> An image that is compatible with your instance type. The Hyper-V generation V2 images created by the installation program have a `-gen2` suffix, while V1 images have the same name without the suffix.
<11> The {product-title} resource kind for the cluster type. Do not change this value.
<12> The region to place machines on.
<13> The disk details for machines created by this machine set.
<14> The subnet for the machine set. You can obtain the subnet by running the following command:
+
[source,terminal]
----
$  oc -n openshift-machine-api \
    -o jsonpath='{.spec.template.spec.providerSpec.value.subnet}{"\n"}' \
    get machineset/<infrastructure_id>-<role>-<region><zone>
----
<15> The {product-title} user data secret for your cluster. Do not change this value.
<16> The Azure VM instance size for machines created by this machine set.
<17> The vnet for the machine set. You can obtain the vnet by running the following command:
+
[source,terminal]
----
$  oc -n openshift-machine-api \
    -o jsonpath='{.spec.template.spec.providerSpec.value.vnet}{"\n"}' \
    get machineset/<infrastructure_id>-<role>-<region><zone>
----
<18> The zone within your region to place machines on. Be sure that your region supports the zone that you specify.
endif::azure-mapi[]

ifdef::gcp-mapi[]
[source,yaml]
----
include::snippets/mapi-machine-set-yaml-agnostic.adoc[]
        value:
          apiVersion: gcpprovider.openshift.io/v1beta1 <6>
          canIPForward: false
          credentialsSecret: <7>
            name: gcp-cloud-credentials
          deletionProtection: false
          disks: <8>
          - autoDelete: true
            boot: true
            image: <path_to_image> <9>
            labels: null
            sizeGb: 128
            type: pd-ssd
          gcpMetadata: <10>
          - key: <custom_metadata_key>
            value: <custom_metadata_value>
          kind: GCPMachineProviderSpec <11>
          machineType: <instance_type> <12>
          networkInterfaces:
          - network: <infrastructure_id>-network <1>
            subnetwork: <infrastructure_id>-<role>-subnet <1>
          projectID: <project_name> <13>
          region: <region> <14>
          serviceAccounts:
          - email: <infrastructure_id>-w@<project_name>.iam.gserviceaccount.com <1> <13>
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
          tags:
          - <infrastructure_id>-<role> <1>
          userDataSecret: <15>
            name: worker-user-data
          zone: <region>-<zone> <16>
----
include::snippets/mapi-machine-set-yaml-agnostic-callouts.adoc[]
//The mapi-machine-set-yaml-agnostic snippet ends with callout <5>, so the first callout following that line must be <6>.
<6> The API version that the machine set uses. Do not change this value.
<7> The {product-title} credentials secret for the cluster type. Do not change this value.
<8> The disk details for machines created by this machine set.
<9> The path to the image that is used in current machine sets. You can obtain the path to the image by running the following command:
+
[source,terminal]
----
$ oc -n openshift-machine-api \
    -o jsonpath='{.spec.template.spec.providerSpec.value.disks[0].image}{"\n"}' \
    get machineset/<infrastructure_id>-<role>-<zone>
----
<10> Optional: Specify custom metadata in the form of a `key:value` pair. For example use cases, see the GCP documentation for link:https://cloud.google.com/compute/docs/metadata/setting-custom-metadata[setting custom metadata].
<11> The {product-title} resource kind for the cluster type. Do not change this value.
<12> The GCP instance type for machines created by this machine set.
<13> The name of the GCP project that you use for your cluster.
<14> The region to place machines on.
<15> The {product-title} user data secret for your cluster. Do not change this value.
<16> The zone within your region to place machines on. Be sure that your region supports the zone that you specify.
endif::gcp-mapi[]

ifeval::["{context}" == "creating-machineset-aws"]
:!aws-mapi:
endif::[]
ifeval::["{context}" == "creating-machineset-azure"]
:!azure-mapi:
endif::[]
ifeval::["{context}" == "creating-machineset-gcp"]
:!gcp-mapi:
endif::[]