// Module included in the following assemblies:
//
// * nodes/nodes/nodes-update-boot-images.adoc
// * machine_configuration/mco-update-boot-images.adoc

ifeval::["{context}" == "nodes-nodes-managing"]
:nodes:
endif::[]

:_mod-docs-content-type: PROCEDURE
[id="mco-update-boot-images_{context}"]
= About updated boot images

Because a boot image is used only when a node is scaled up, this feature has no effect on existing nodes.

For {gcp-short} and {aws-short}, you can disable the default behavior, if needed. When disabled, the boot image no longer updates with the cluster. For example, if your cluster was originally created with {product-title} 4.16, the boot image that the MCO would use to create nodes is the same 4.16 version, even if your cluster is at a later version.

For all other platforms, the MCO does not update the boot image with each cluster update.

[NOTE]
====
The ability to configure this behavior is available for only {gcp-short} and {aws-short} clusters. It is not supported for clusters managed by the {cluster-capi-operator}.
====

However, using an older boot image could cause the following issues:

* Extra time to start nodes
* Certificate expiration issues
* Version skew issues

For information on how to disable the default behavior, see "Disabling updated boot images". If you disable the default behavior, you can enable the default behavior at any time. For more information, see "Enabling updated boot images".

How the cluster behaves after disabling or re-enabling the default behavior, depends upon when you made the change, including the following scenarios:

* If you disable the behavior before updating to a new {product-title} version:
** The boot image version used by the machine sets remains the same version as when the feature was disabled. 
** Any new nodes use that same version.

* If you disable the behavior after updating to a new {product-title} version: 
** The boot image version used by the machine sets is updated to match the updated {product-title} version. 
** Any new nodes use the updated {product-title} version when a machine set is scaled. 
** If you update to a later {product-title} version, the boot image version in the machine sets remains at the current version and are not updated with the cluster.

* If you enable the behavior: 
** The boot image version used by the machine sets is updated to the current version, if different. 
** When you scale up nodes, the new nodes use the current {product-title} version in the cluster. 

To view the current boot image used in your cluster, examine a machine set:

.Example machine set with the boot image reference

[source,yaml]
----
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: ci-ln-hmy310k-72292-5f87z-worker-a
  namespace: openshift-machine-api
spec:
# ...
  template:
# ...
    spec:
# ...
      providerSpec:
# ...
        value:
          disks:
          - autoDelete: true
            boot: true
            image: projects/rhcos-cloud/global/images/rhcos-412-85-202203181601-0-gcp-x86-64 <1>
# ...
----
<1> This boot image is the same as the originally-installed {product-title} version, in this example {product-title} 4.12, regardless of the current version of the cluster. The way that the boot image is represented in the machine set depends on the platform, as the structure of the `providerSpec` field differs from platform to platform.
