// Module included in the following assemblies:
//
// * metering/metering-installing-metering.adoc

[id="metering-install-operator_{context}"]
= Installing the Metering Operator


.Procedure



. Create a Namespace for the Metering Operator:

.. Create a Namespace object YAML file (for example, `metering-namespace.yaml`) for the Metering Operator:
+
[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-metering <1>
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
----
<1> Set the name to `openshift-metering`. No other namespace is supported.

.. Create the Namespace:
+
----
$ oc create -f <file-name>.yaml
----
+
For example:
+
----
$ oc create -f metering-namespace.yaml
----
. In the {product-title} web console,  click *Operators* -> *OperatorHub*, and filter for `metering` to find the
Metering Operator.
. Click the Metering card, review the package description, and then click *Install*.
. Select the Operator recommended namespace, *openshift-metering*.
. Select an *Update Channel* and *Approval Strategy*.
. Click *Subscribe*.

. On the *Installed Operators* screen, the *Status* displays *Succeeded* when the Metering Operator finishes installation. Click the name of the Operator in the first column to view the *Operator Details* page.

[NOTE]
====
It might take a few minutes for the Metering Operator to appear.
====

From the *Operator Details* page you can create different resources related to metering. To complete your installation create a MeteringConfig resource to configure metering and install the components of the metering stack.
