// Module included in the following assemblies:
//
// * monitoring/cluster_monitoring/metering-configure-hive-metastore.adoc

[id="metering-use-mysql-or-postgresql-for-hive_{context}"]
= Use MySQL or PostgreSQL for the Hive metastore

The default installation of metering configures Hive to use an embedded Java database called Derby. This is unsuited for larger environments and can be replaced with either a MySQL or PostgreSQL database. Use the following example configuration files if your deployment requires a MySQL or PostgreSQL database for Hive.

There are 4 configuration options you can use to control the database used by Hive metastore: url, driver, username, and password.

Use the example configuration file below to use a MySQL database for Hive:

[source,yaml]
----
spec:
  hive:
    spec:
      config:
        url: "jdbc:mysql://mysql.example.com:3306/hive_metastore"
        driver: "com.mysql.jdbc.Driver"
        username: "REPLACEME"
        password: "REPLACEME"
----

You can pass additional JDBC parameters using the `spec.hive.config.url`. For more details see the https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html[MySQL Connector/J documentation].

Use the example configuration file below to use a PostgreSQL database for Hive:

[source,yaml]
----
spec:
  hive:
    spec:
      config:
        url: "jdbc:postgresql://postgresql.example.com:5432/hive_metastore"
        driver: "org.postgresql.Driver"
        username: "REPLACEME"
        password: "REPLACEME"
----
You can pass additional JDBC parameters using the URL. For more details see the https://jdbc.postgresql.org/documentation/head/connect.html#connection-parameters[PostgreSQL JDBC driver documentation].
