// Module included in the following assemblies:
//
// * microshift_networking/microshift-nw-router.adoc

:_mod-docs-content-type: CONCEPT
[id="microshift-about-router-config_{context}"]
= About configuring the router

[role="_abstract"]
To make ingress optional, you can configure {microshift-short} ingress router settings to manage which ports, if any, are exposed to network traffic. Specified routing is an example of ingress load balancing.

* The default ingress router is always on, running on all IP addresses on the `http: 80` and `https: 443` ports.
* Default router settings allow access to any namespace.

Some applications running on top of {microshift-short} might not require the default router and instead create their own. You can configure the router to control both ingress and namespace access.

[TIP]
====
You can check for the presence of the default router in your {microshift-short} installation before you begin configurations by using the `oc get deployment -n openshift-ingress` command, which returns the following output:

[source,terminal]
----
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
router-default   1/1     1            1           2d23h
----
====
