
// Module included in the following assemblies:
//
//microshift_release_notes/microshift-4-21-release-notes.adoc

:_mod-docs-content-type: CONCEPT
[id="microshift-4-21-asynch-updates_{context}"]
= Asynchronous updates

[role="_abstract"]
Security, bug fix, and enhancement updates for {microshift-short} {product-version} are released asynchronously through the Red{nbsp}Hat Network. All {microshift-short} {product-version} updates are https://access.redhat.com/downloads/content/290/[available on the Red{nbsp}Hat Customer Portal]. For more information about asynchronous updates, read the https://access.redhat.com/product-life-cycles?product=Red%20Hat%20build%20of%20Microshift,Red%20Hat%20Device%20Edge[{microshift-short} Life Cycle].

Red{nbsp}Hat Customer Portal users can enable update notifications in the account settings for Red{nbsp}Hat Subscription Management (RHSM). When notifications are enabled, you are notified through email whenever new updates relevant to your registered systems are released.

[NOTE]
====
Red{nbsp}Hat Customer Portal user accounts must have systems registered and consuming {microshift-short} entitlements for {microshift-short} update notification emails to generate.
====

This section is updated over time to provide notes on enhancements and bug fixes for future asynchronous releases of {microshift-short} {product-version}. Versioned asynchronous releases, for example with the form {microshift-short} {product-version}.z, are detailed in the following subsections.
