// Module included in the following assemblies:
//
// * microshift/microshift_configuring/microshift-node-access-kubeconfig.adoc

:_mod-docs-content-type: CONCEPT
[id="kubeconfig-files-overview_{context}"]
= Kubeconfig files for configuring node access

The two categories of `kubeconfig` files used in {microshift-short} are local access and remote access. Every time {microshift-short} starts, a set of `kubeconfig` files for local and remote access to the API server are generated. These files are generated in the `/var/lib/microshift/resources/kubeadmin/` directory by using preexisting configuration information.

Each access type requires a different authentication certificate signed by different Certificate Authorities (CAs). The generation of multiple `kubeconfig` files accommodates this need.

You can use the appropriate `kubeconfig` file for the access type needed in each case to provide authentication details. The contents of {microshift-short} `kubeconfig` files are determined by either default built-in values or a `config.yaml` file.

[NOTE]
====
A `kubeconfig` file must exist for the cluster to be accessible. The values are applied from built-in default values or a customized `config.yaml` file.
====

.Example contents of the kubeconfig files
[source,terminal]
----
/var/lib/microshift/resources/kubeadmin/
├── kubeconfig <1>
├── alt-name-1 <2>
│   └── kubeconfig
├── 1.2.3.4 <3>
│   └── kubeconfig
└── microshift-rhel9 <4>
    └── kubeconfig
----
<1> Local hostname. The main IP address of the host is always the default.
<2> Subject Alternative Names for API server certificates.
<3> DNS name.
<4> {microshift-short} hostname.
