//Module included in the following assemblies:
//
//* microshift_running_apps/microshift-operators-olm.adoc

:_mod-docs-content-type: PROCEDURE
[id="microshift-oc-mirror-config-cluster_{context}"]
= Configuring your {microshift-short} cluster to use Operators selected with oc mirror

After you mirror your image set to the mirror registry, you must apply the generated `CatalogSource` custom resource (CR) into the cluster. The `CatalogSource` CR is used by Operator Lifecycle Manager (OLM) to retrieve information about the available Operators in the mirror registry. You can then create a Subscription custom CR and apply that.

.Prerequisites

* You mirrored the image set to your registry mirror.
* You added image reference information to the CRI-O container runtime configuration.

.Procedure

. Apply the YAML file from the results directory to the cluster by running the following command:
+
[source,terminal]
----
$ oc apply -f ./oc-mirror-workspace/results-1708508014/catalogSource-cs-redhat-operator-index.yaml
----
+
.Example namespace configuration
[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-catalog
  namespace: openshift-marketplace <1>
spec:
  sourceType: grpc
  image: registry.example.com/redhat/redhat-operator-index:v4.15
  updateStrategy:
    registryPoll:
      interval: 60m
----
<1> The global namespace. Setting the `metadata.namespace` to `openshift-marketplace` enables the catalog to reference catalogs in all namespaces. Subscriptions in any namespace can reference catalogs created in the `openshift-marketplace` namespace.
+
.Example output
[source,terminal]
----
catalogsource.operators.coreos.com/cs-redhat-operator-index created
----

.Verification

. Verify that the `CatalogSource` resources were successfully installed by running the following command:
+
[source,terminal]
----
$ oc get catalogsource --all-namespaces
----
//add example output

. Verify that the catalog source is running by using the following command:
+
[source,terminal]
----
$ oc get pods -n openshift-marketplace
----
+
.Example output
[source,terminal]
----
NAME                             READY   STATUS    RESTARTS   AGE
cs-redhat-operator-index-4227b   2/2     Running   0          2m5s
----

. Create a Subscription CR configuration file by using the following example YAML:
+
.Subscription custom resource example YAML
[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-broker
  namespace: openshift-operators
spec:
  channel: 7.11.x
  name: amq-broker-rhel8
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
----

. Apply the Subscription CR configuration by running the following command:
+
[source,terminal]
----
$ oc apply -f <my-subscription-cr.yaml> <1>
----
<1> Replace _<my-subscription-cr.yaml>_ with the name of your Subscription CR.
+
.Example output
[source,terminal]
----
subscription.operators.coreos.com/cs-redhat-operator-index-4227b
----
