// Module included in the following assemblies:
//
// * microshift_ai/microshift-rhoai.adoc

:_mod-docs-content-type: CONCEPT
[id="microshift-rhoai-override-kserve-config_{context}"]
= Overriding KServe configuration

[role="_abstract"]
You can override KServe settings to customize your model-serving environment. 

Follow the general steps for your operating system.

Option 1::

. Make a copy of the existing `inferenceservice-config` config map file in the `redhat-ods-applications` namespace.

. Edit the settings you want to change.

. Overwrite the existing `ConfigMap` object.

. Restart KServe by either deleting the pod or scaling the `Deployment` pod parameter down to `0` and then back up to `1`.

Option 2::

. Copy the `/usr/lib/microshift/manifests.d/010-microshift-ai-model-serving-kserve/inferenceservice-config-microshift-patch.yaml` config map file.

. Edit the settings you want to change.

. Apply the `ConfigMap` object.

. Restart KServe by either deleting the pod or scaling the `Deployment` pod parameter down to `0` and then back up to `1`.

For {op-system-ostree} and {op-system-image} systems::

. Create a new manifest with the `ConfigMap` file, based on either the `/usr/lib/microshift/manifests.d/010-microshift-ai-model-serving-kserve/inferenceservice-config-microshift-patch.yaml` or `inferenceservice-config` file, in the `redhat-ods-applications` namespace.

. Place the new manifest in the `/usr/lib/microshift/manifests.d/` directory. Staring with prefix `011` is recommended so that your manifest is applied after the `/usr/lib/microshift/manifests.d/010-microshift-ai-model-serving-kserve/` directory contents.
