// Module included in the following assemblies:
//
//* microshift_support/microshift-etcd.adoc

:_mod-docs-content-type: PROCEDURE
[id="microshift-config-etcd_{context}"]
= Configuring the memoryLimitMB value to set parameters for the etcd server

By default, etcd uses as much memory as necessary to handle the load on the system. In memory-constrained systems, you might need to limit the amount of memory etcd uses.

.Procedure

* Edit the `/etc/microshift/config.yaml` file to set the `memoryLimitMB` value.
+
[source,yaml]
----
etcd:
  memoryLimitMB: 128
----
+
[NOTE]
====
The minimum required value for `memoryLimitMB` on {microshift-short} is 128 MB. Values close to the minimum value are more likely to impact etcd performance. The lower the limit, the longer etcd takes to respond to queries. If the limit is too low or the etcd usage is high, queries time out.
====

.Verification

. After modifying the `memoryLimitMB` value in `/etc/microshift/config.yaml`, restart {microshift-short} by running the following command:
+
[source,terminal]
----
$ sudo systemctl restart microshift
----

. Verify the new `memoryLimitMB` value is in use by running the following command:
+
[source,terminal]
----
$ systemctl show --property=MemoryHigh microshift-etcd.scope
----
