//Module included in the following assemblies:
//
// * microshift_running_apps/microshift_operators/microshift-operators-olm.adoc

:_mod-docs-content-type: CONCEPT
[id="microshift-olm-deploy-operators_{context}"]
= How to deploy Operators using OLM

After you create and deploy your custom catalog, you must create a Subscription custom resource (CR) that can access the catalog and install the Operators you choose. Where Operators run depends on the namespace in which you create the Subscription CR.

[IMPORTANT]
====
Operators in OLM have a watch scope. For example, some Operators only support watching their own namespace, while others support watching every namespace in the cluster. All Operators installed in a given namespace must have the same watch scope.
====

[id="microshift-olm-operators-connection-details_{context}"]
== Connectivity and OLM Operator deployment
Operators can be deployed anywhere a catalog is running.

* For clusters that are connected to the internet, mirroring images is not required. Images can be pulled over the network.
* For restricted networks in which {microshift-short} has access to an internal network only, images must be mirrored to an internal registry.
* For use cases in which {microshift-short} clusters are completely offline, all images must be embedded into an `osbuild` blueprint.
//TODO point to correct ref docs