// Module included in the following assemblies:
//
// microshift/microshift-embed-into-rpm-ostree.adoc

:_content-type: PROCEDURE
[id="adding-microshift-repos-image-builder_{context}"]
= Adding {product-title} repositories to Image Builder

Use the following procedure to add the {product-title} repositories to Image Builder on your build host.

.Prerequisites
* Your build host meets the Image Builder system requirements.
* You have installed and set up Image Builder and the `composer-cli` tool.
* You have root-user access to your build host.

.Procedure

. Create an Image Builder configuration file for adding the `rhocp-4.13` RPM repository source required to pull {product-title} RPMs by running the following command:
+
[source,terminal]
----
$ cat > rhocp-4.13.toml <<EOF
id = "rhocp-4.13"
name = "Red Hat OpenShift Container Platform 4.13 for RHEL 9"
type = "yum-baseurl"
url = "https://cdn.redhat.com/content/dist/layered/rhel9/$(uname -m)/rhocp/4.13/os"
check_gpg = true
check_ssl = true
system = false
rhsm = true
EOF
----

. Create an Image Builder configuration file for adding the `fast-datapath` RPM repository by running the following command:
+
[source,terminal]
----
$ cat > fast-datapath.toml <<EOF
id = "fast-datapath"
name = "Fast Datapath for RHEL 9"
type = "yum-baseurl"
url = "https://cdn.redhat.com/content/dist/layered/rhel9/$(uname -m)/fast-datapath/os"
check_gpg = true
check_ssl = true
system = false
rhsm = true
EOF
----

. Add the sources to the Image Builder by running the following commands:
+
[source,terminal]
----
$ sudo composer-cli sources add rhocp-4.13.toml
----
+
[source,terminal]
----
$ sudo composer-cli sources add fast-datapath.toml
----

.Verification

* Confirm that the sources were added properly by running the following command:
+
[source,terminal]
----
$ sudo composer-cli sources list
----
+
.Example output
+
[source,terminal]
----
appstream
baseos
fast-datapath
rhocp-4.13
----