
// Module included in the following assemblies:
//
//microshift_updating/microshift-update-options.adoc

:_mod-docs-content-type: CONCEPT
[id="microshift-standalone-updates_{context}"]
= Standalone {microshift-short} updates

[role="_abstract"]
You can update just your {microshift-short} version by embedding the new version in a {op-system-base} image or by installing the RPMs on a standard {op-system-base} operating system. Consider your current operating system version and deployments when planning a {microshift-short} update.

The following factors apply to a standalone {microshift-short} version update:

* {microshift-short} operates as an in-place update and does not require removal of the earlier version.
* Data backups beyond those required for the usual functioning of your applications are not required.
* You can potentially update {microshift-short} without reinstalling your applications and Operators.
* Only `rpm-ostree` updates include automatic rollbacks.

[IMPORTANT]
====
You must update {op-system-base} to update {microshift-short} if your current operating system is not compatible with the new version of {microshift-short} that you want to use.
====
