//Module included in the following assemblies:
//
//* microshift_running_apps/microshift-operators-olm.adoc

:_mod-docs-content-type: CONCEPT
[id="microshift-using-oc-mirror_{context}"]
= The oc mirror tool for Operators

You can use the oc mirror tool with {microshift-short} to filter and prune Operators from widely available options. You can then mirror the contents, or use the container images in an offline deployment with {op-system-ostree-first}.

[NOTE]
====
{microshift-short} uses the generally available version of oc mirror. Do not use the following procedures with the Technical Preview version of oc mirror.
====

You can mirror the images required for Operators locally or to a container mirror registry that supports link:https://docs.docker.com/registry/[Docker v2-2], such as Red Hat Quay. The procedure to mirror content from Red Hat hosted sites on the internet to an isolated image registry is the same, whichever registry you choose. After you mirror the content, you configure each cluster to retrieve this content from your mirror registry.

[id="microshift-populate-mirror-registry-connectivity_{context}"]
== Populating a mirror registry and considering connectivity

When you populate your registry, you can use one of following connectivity scenarios:

Connected mirroring::
If you have a host that can access both the internet and your mirror registry, but not your cluster node, you can directly mirror the content from that machine.

Disconnected mirroring::
If you do not have a host that can access both the internet and your mirror registry, you must mirror the images to a file system and then bring that host or removable media into your restricted environment.

[id="microshift-registry-reachability_{context}"]
== Ensure container registry is available

Regardless of the end-use scenario, a container registry must be reachable by every machine in the clusters that you provision. If the registry is unreachable, installation, updating, or other operations, such as workload relocation, might fail.

To avoid problems caused by an unreachable registry, use the following standard practices:

* Run mirror registries in a highly available way.
* Ensure that the mirror registry at least matches the production availability of your clusters.