//Module included in the following assemblies:
//
//* microshift_running_apps/microshift_operators/microshift-operators-oc-mirror.adoc

:_mod-docs-content-type: CONCEPT
[id="microshift-connectivity-considerations_{context}"]
= Connectivity considerations when populating a mirror registry

[role="_abstract"]
When you populate your mirror registry, you can use connected or disconnected mirroring depending on your use case.

Connected mirroring::
If you have a host that can access both the internet and your mirror registry, but not your node, you can directly mirror the content from that machine.

Disconnected mirroring::
If you do not have a host that can access both the internet and your mirror registry, you must mirror the images to a file system and then bring that host or removable media into your disconnected environment.
+
[IMPORTANT]
====
A container registry must be reachable by every machine in the node that you provision. Installing, updating, and other operations, such as relocating workloads, fail if the registry is unreachable.
====

To avoid problems caused by an unreachable registry, use the following standard practices:

* Run mirror registries in a highly available way.
* Ensure that the mirror registry at least matches the production availability of your node.
