// Module included in the following assemblies:
//
// * migration/installing-and-upgrading-4.adoc

[id="migration-upgrading-from-mtc-1-3_{context}"]
= Upgrading {mtc-short} 1.3

If you are upgrading {mtc-full} ({mtc-short}) version 1.3, you must update the `MigPlan` custom resource (CR) manifest on the cluster on which the `MigrationController` pod is running.

The `indirectImageMigration` and `indirectVolumeMigration` parameters do not exist in {mtc-short} 1.3. Their default value in version 1.4 is `false`, which means that direct image migration and direct volume migration are enabled.

If the direct migration requirements are not fulfilled, the migration plan cannot reach a `Ready` state unless these parameter values are changed to `true`.

.Prerequisites

* You must have {mtc-short} 1.3 installed.
* You must be logged in as a user with `cluster-admin` privileges.

.Procedure

. Log in to the cluster on which the `MigrationController` pod is running.
. Get the `MigPlan` CR manifest:
+
[source,terminal]
----
$ oc get migplan <migplan> -o yaml -n openshift-migration
----

. Update the following parameter values and save the file as `migplan.yaml`:
+
[source,yaml]
----
...
spec:
  indirectImageMigration: true
  indirectVolumeMigration: true
----

. Replace the `MigPlan` CR manifest to apply the changes:
+
[source,terminal]
----
$ oc replace -f migplan.yaml -n openshift-migration
----

. Get the updated `MigPlan` CR manifest to verify the changes:
+
[source,terminal]
----
$ oc get migplan <migplan> -o yaml -n openshift-migration
----
