// Module included in the following assemblies:
//
// * migrating_from_ocp_3_to_4/migrating-applications-3-4.adoc
// * migration-toolkit-for-containers/migrating-applications-with-mtc

[id="migration-mtc-cr-manifests_{context}"]
= {mtc-short} custom resource manifests

{mtc-full} ({mtc-short}) uses the following custom resource (CR) manifests to create CRs for migrating applications.

[id="directimagemigration_{context}"]
== DirectImageMigration

The `DirectImageMigration` CR copies images directly from the source cluster to the destination cluster.

[source,yaml]
----
apiVersion: migration.openshift.io/v1alpha1
kind: DirectImageMigration
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: <directimagemigration_name>
spec:
  srcMigClusterRef:
    name: <source_cluster_ref> <1>
    namespace: openshift-migration
  destMigClusterRef:
    name: <destination_cluster_ref> <2>
    namespace: openshift-migration
  namespaces:
  - <namespace> <3>
----
<1> Specify the `MigCluster` CR name of the source cluster.
<2> Specify the `MigCluster` CR name of the destination cluster.
<3> Specify one or more namespaces containing images to be migrated.

[id="directimagestreammigration_{context}"]
== DirectImageStreamMigration

The `DirectImageStreamMigration` CR copies image stream references directly from the source cluster to the destination cluster.

[source,yaml]
----
apiVersion: migration.openshift.io/v1alpha1
kind: DirectImageStreamMigration
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: directimagestreammigration_name
spec:
  srcMigClusterRef:
    name: <source_cluster_ref> <1>
    namespace: openshift-migration
  destMigClusterRef:
    name: <destination_cluster_ref> <2>
    namespace: openshift-migration
  imageStreamRef:
    name: <image_stream_name> <3>
    namespace: <source_image_stream_namespace> <4>
  destNamespace: <destination_image_stream_namespace> <5>
----
<1> Specify the `MigCluster` CR name of the source cluster.
<2> Specify the `MigCluster` CR name of the destination cluster.
<3> Specify the image stream name.
<4> Specify the image stream namespace on the source cluster.
<5> Specify the image stream namespace on the destination cluster.

[id="directvolumemigration_{context}"]
== DirectVolumeMigration

The `DirectVolumeMigration` CR copies persistent volumes (PVs) directly from the source cluster to the destination cluster.

[source,yaml]
----
apiVersion: migration.openshift.io/v1alpha1
kind: DirectVolumeMigration
metadata:
  name: <directvolumemigration_name>
  namespace: openshift-migration
spec:
  createDestinationNamespaces: false <1>
  deleteProgressReportingCRs: false <2>
  destMigClusterRef:
    name: host <3>
    namespace: openshift-migration
  persistentVolumeClaims:
  - name: <pvc_name> <4>
    namespace: <pvc_namespace> <5>
  srcMigClusterRef:
    name: <source_cluster_ref> <6>
    namespace: openshift-migration
----
<1> Namespaces are created for the PVs on the destination cluster if `true`.
<2> The `DirectVolumeMigrationProgress` CRs are deleted after migration if `true`. The default value is `false` so that `DirectVolumeMigrationProgress` CRs are retained for troubleshooting.
<3> Update the cluster name if the destination cluster is not the host cluster.
<4> Specify one or more PVCs to be migrated with direct volume migration.
<5> Specify the namespace of each PVC.
<6> Specify the `MigCluster` CR name of the source cluster.

[id="directvolumemigrationprogress_{context}"]
== DirectVolumeMigrationProgress

The `DirectVolumeMigrationProgress` CR shows the progress of the `DirectVolumeMigration` CR.

[source,yaml]
----
apiVersion: migration.openshift.io/v1alpha1
kind: DirectVolumeMigrationProgress
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: directvolumemigrationprogress_name
spec:
  clusterRef:
    name: source_cluster
    namespace: openshift-migration
  podRef:
    name: rsync_pod
    namespace: openshift-migration
----

[id="miganalytic_{context}"]
== MigAnalytic

The `MigAnalytic` CR collects the number of images, Kubernetes resources, and the PV capacity from an associated `MigPlan` CR.

[source,yaml]
----
apiVersion: migration.openshift.io/v1alpha1
kind: MigAnalytic
metadata:
  annotations:
    migplan: <migplan_name> <1>
  name: miganalytic_name
  namespace: openshift-migration
  labels:
    migplan: <migplan_name> <2>
spec:
  analyzeImageCount: true <3>
  analyzeK8SResources: true <4>
  analyzePVCapacity: true <5>
  listImages: false <6>
  listImagesLimit: 50 <7>
  migPlanRef:
    name: migplan_name <8>
    namespace: openshift-migration
----
<1> Specify the `MigPlan` CR name associated with the `MigAnalytic` CR.
<2> Specify the `MigPlan` CR name associated with the `MigAnalytic` CR.
<3> Optional: The number of images is returned if `true`.
<4> Optional: Returns the number, kind, and API version of the Kubernetes resources if `true`.
<5> Optional: Returns the PV capacity if `true`.
<6> Returns a list of image names if `true`. Default is `false` so that the output is not excessively long.
<7> Optional: Specify the maximum number of image names to return if `listImages` is `true`.
<8> Specify the `MigPlan` CR name associated with the `MigAnalytic` CR.

[id="migcluster_{context}"]
== MigCluster

The `MigCluster` CR defines a host, local, or remote cluster.

[source,yaml]
----
apiVersion: migration.openshift.io/v1alpha1
kind: MigCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: host <1>
  namespace: openshift-migration
spec:
  isHostCluster: true <2>
  azureResourceGroup: <azure_resource_group> <3>
  caBundle: <ca_bundle_base64> <4>
  insecure: false <5>
  refresh: false <6>
# The 'restartRestic' parameter is relevant for a source cluster.
# restartRestic: true <7>
# The following parameters are relevant for a remote cluster.
# isHostCluster: false
# exposedRegistryPath: <8>
# url: <destination_cluster_url> <9>
# serviceAccountSecretRef:
#   name: <source_secret_ref> <10>
#   namespace: openshift-config
----
<1> Optional: Update the cluster name if the `migration-controller` pod is not running on this cluster.
<2> The `migration-controller` pod runs on this cluster if `true`.
<3> Optional: If the storage provider is Microsoft Azure, specify the resource group.
<4> Optional: If you created a certificate bundle for self-signed CA certificates and if the  `insecure` parameter value is `false`, specify the base64-encoded certificate bundle.
<5> SSL verification is enabled if `false`.
<6> The cluster is validated if `true`.
<7> The `restic` pods are restarted on the source cluster after the `stage` pods are created if `true`.
<8> Optional: If you are using direct image migration, specify the exposed registry path of a remote cluster.
<9> Specify the URL of the remote cluster.
<10> Specify the name of the `Secret` CR for the remote cluster.

[id="mighook_{context}"]
== MigHook

The `MigHook` CR defines an Ansible playbook or a custom image that runs tasks at a specified stage of the migration.

[source,yaml]
----
apiVersion: migration.openshift.io/v1alpha1
kind: MigHook
metadata:
  generateName: <hook_name_prefix> <1>
  name: <hook_name> <2>
  namespace: openshift-migration
spec:
  activeDeadlineSeconds: <3>
  custom: false <4>
  image: <hook_image> <5>
  playbook: <ansible_playbook_base64> <6>
  targetCluster: source <7>
----
<1> Optional: A unique hash is appended to the value for this parameter so that each migration hook has a unique name. You do not need to specify the value of the `name` parameter.
<2> Specify the migration hook name, unless you specify the value of the `generateName` parameter.
<3> Optional: Specify the maximum number of seconds that a hook can run. The default value is `1800`.
<4> The hook is a custom image if `true`. The custom image can include Ansible or it can be written in a different programming language.
<5> Specify the custom image, for example, `quay.io/konveyor/hook-runner:latest`. Required if `custom` is `true`.
<6> Specify the entire base64-encoded Ansible playbook. Required if `custom` is `false`.
<7> Specify `source` or `destination` as the cluster on which the hook will run.

[id="migmigration_{context}"]
== MigMigration

The `MigMigration` CR runs an associated `MigPlan` CR.

You can create multiple `MigMigration` CRs associated with the same `MigPlan` CR for the following scenarios:

* You can run multiple _stage_ or incremental migrations to copy data without stopping the pods on the source cluster. Running stage migrations improves the performance of the actual migration.
* You can cancel a migration in progress.
* You can roll back a migration.

[source,yaml]
----
apiVersion: migration.openshift.io/v1alpha1
kind: MigMigration
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: migmigration_name
  namespace: openshift-migration
spec:
  canceled: false <1>
  rollback: false <2>
  stage: false <3>
  quiescePods: true <4>
  keepAnnotations: true <5>
  verify: false <6>
  migPlanRef:
    name: <migplan_ref> <7>
    namespace: openshift-migration
----
<1> A migration in progress is canceled if `true`.
<2> A completed migration is rolled back if `true`.
<3> Data is copied incrementally and the pods on the source cluster are not stopped if `true`.
<4> The pods on the source cluster are scaled to `0` after the `Backup` stage of a migration if `true`.
<5> The labels and annotations applied during the migration are retained if `true`.
<6> The status of the migrated pods on the destination cluster are checked and the names of pods that are not in a `Running` state are returned if `true`.
<7> `migPlanRef.name`: Specify the name of the associated `MigPlan` CR.

[id="migplan_{context}"]
== MigPlan

The `MigPlan` CR defines the parameters of a migration plan. It contains a group of virtual machines that are being migrated with the same parameters.

[IMPORTANT]
====
You must ensure that namespaces are not duplicated on the source or the destination clusters because the UID and GID ranges are copied during migration. The following examples will cause a validation error:

----
spec:
  namespaces:
    - namespace_2
    - namespace_1:namespace_2
----

----
spec:
  namespaces:
    - namespace_1:namespace_1
----
====

[source,yaml]
----
apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: migplan_name
  namespace: openshift-migration
spec:
  closed: false <1>
  srcMigClusterRef:
    name: <source_migcluster_ref> <2>
    namespace: openshift-migration
  destMigClusterRef:
    name: <destination_migcluster_ref> <3>
    namespace: openshift-migration
  hooks: <4>
    - executionNamespace: <namespace> <5>
      phase: <migration_phase> <6>
      reference:
        name: <mighook_name> <7>
        namespace: <hook_namespace> <8>
      serviceAccount: <service_account> <9>
  indirectImageMigration: true <10>
  indirectVolumeMigration: false <11>
  migStorageRef:
    name: <migstorage_name> <12>
    namespace: openshift-migration
  namespaces:
    - <source_namespace_1> <13>
    - <source_namespace_2>
    - <source_namespace_3>:<destination_namespace_4> <14>
  refresh: false  <15>
----
<1> The migration has completed if `true`. You cannot create another `MigMigration` CR for this `MigPlan` CR.
<2> Specify the name of the source cluster `MigCluster` CR.
<3> Specify the name of the destination cluster `MigCluster` CR.
<4> Optional: You can specify up to four migration hooks.
<5> Optional: Specify the namespace in which the hook will run.
<6> Optional: Specify the migration phase during which a hook runs. One hook can be assigned to one phase. The expected values are `PreBackup`, `PostBackup`, `PreRestore`, and `PostRestore`.
<7> Optional: Specify the name of the `MigHook` CR.
<8> Optional: Specify the namespace of `MigHook` CR.
<9> Optional: Specify a service account with `cluster-admin` privileges.
<10> Direct image migration is disabled if `true`. Images are copied from the source cluster to the replication repository and from the replication repository to the destination cluster.
<11> Direct volume migration is disabled if `true`. PVs are copied from the source cluster to the replication repository and from the replication repository to the destination cluster.
<12> Specify the name of `MigStorage` CR.
<13> Specify one or more source namespaces. If you specify only the source namespace, the destination namespace is the same.
<14> Specify the destination namespace if it is different from the source namespace.
<15> The `MigPlan` CR is validated if `true`.

[id="migstorage_{context}"]
== MigStorage

The `MigStorage` CR describes the object storage for the replication repository. You can configure Amazon Web Services, Microsoft Azure, Google Cloud Storage, and generic S3-compatible cloud storage, for example, Minio or NooBaa.

Different providers require different parameters.

[source,yaml]
----
apiVersion: migration.openshift.io/v1alpha1
kind: MigStorage
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: migstorage_name
  namespace: openshift-migration
spec:
  backupStorageProvider: <storage_provider> <1>
  volumeSnapshotProvider: <2>
  backupStorageConfig:
    awsBucketName: <3>
    awsRegion: <4>
    credsSecretRef:
      namespace: openshift-config
      name: <storage_secret> <5>
    awsKmsKeyId: <6>
    awsPublicUrl: <7>
    awsSignatureVersion: <8>
  volumeSnapshotConfig:
    awsRegion: <9>
    credsSecretRef:
      namespace: openshift-config
      name: <10>
  refresh: false <11>
----
<1> Specify the storage provider.
<2> Optional: If you are using the snapshot copy method, specify the storage provider.
<3> If you are using AWS, specify the bucket name.
<4> If you are using AWS, specify the bucket region, for example, `us-east-1`.
<5> Specify the name of the `Secret` CR that you created for the `MigStorage` CR.
<6> Optional: If you are using the AWS Key Management Service, specify the unique identifier of the key.
<7> Optional: If you granted public access to the AWS bucket, specify the bucket URL.
<8> Optional: Specify the AWS signature version for authenticating requests to the bucket, for example, `4`.
<9> Optional: If you are using the snapshot copy method, specify the geographical region of the clusters.
<10> Optional: If you are using the snapshot copy method, specify the name of the `Secret` CR that you created for the `MigStorage` CR.
<11> The cluster is validated if `true`.
