// Module included in the following assemblies:
//
// * migration_toolkit_for_containers/mtc-release-notes.adoc
:_mod-docs-content-type: REFERENCE
[id="migration-mtc-release-notes-1-8-5_{context}"]
= {mtc-full} 1.8.5 release notes

[id="technical-changes-1-8-5_{context}"]
== Technical changes

{mtc-first} 1.8.5 has the following technical changes:

.Federal Information Processing Standard (FIPS)

Federal Information Processing Standards (FIPS) are a set of computer security standards developed by the United States federal government in line with the Federal Information Security Management Act (FISMA).

Starting with version {mtc-short} 1.8.5 is designed for FIPS compliance.

[id="resolved-issues-1-8-5_{context}"]
== Resolved issues

{mtc-short} 1.8.5 has the following major resolved issues:
// been told not to include CVEs in OCP operator release notes

.Performing StorageClass conversion triggers the scale-down of all aplications of the namespace

In previous releases of {mtc-short}, when running a StorageClass conversion and if there was more than one application running, then {mtc-short} scaled down all the applications on the cutover phase, even those not involved in the migration. This issue has been resolved in {mtc-short} 1.8.5.  link:https://issues.redhat.com/browse/MIG-1661[(MIG-1661)]


[id="known-issues-1-8-5_{context}"]
== Known issues

{mtc-short} 1.8.5 has the following known issues:
// checking bugzilla and jira these are still open and scheduled to be resolved in later editions

.The associated SCC for service account cannot be migrated in {OCP} 4.12

The associated Security Context Constraints (SCCs) for service accounts in {OCP} 4.12 cannot be migrated. This issue is planned to be resolved in a future release of {mtc-short}. link:https://issues.redhat.com/browse/MIG-1454[(MIG-1454)].

.Rsync pod fails to start causing the DVM phase to fail

The DVM phase fails due to the Rsync pod failing to start, because of a permission issue. link:https://bugzilla.redhat.com/show_bug.cgi?id=2231403[(BZ#2231403)]

.Migrated builder pod fails to push to image registry

When migrating an application including `BuildConfig` from source to target cluster, the builder pod results in error, failing to push the image to the image registry. link:https://bugzilla.redhat.com/show_bug.cgi?id=2234781[(BZ#2234781)]

.Conflict condition gets cleared briefly after it is created

When creating a new state migration plan that results in a conflict error, that error is cleared shorty after it is displayed. link:https://bugzilla.redhat.com/show_bug.cgi?id=2144299[(BZ#2144299)]

.PvCapacityAdjustmentRequired Warning Not Displayed After Setting pv_resizing_threshold

The `PvCapacityAdjustmentRequired` warning fails to appear in the migration plan after the `pv_resizing_threshold` is adjusted. link:https://bugzilla.redhat.com/show_bug.cgi?id=2270160[(BZ#2270160)]
