// Module included in the following assemblies:
//
// * migration/migrating_3_4/troubleshooting-3-4.adoc
// * migration/migrating_4_1_4/troubleshooting-4-1-4.adoc
// * migration/migrating_4_2_4/troubleshooting-4-2-4.adoc
[id='migration-downloading-logs_{context}']
= Downloading migration logs

You can download the Velero, Restic, and Migration controller logs in the CAM web console to troubleshoot a failed migration.

.Procedure

. Log in to the CAM console.
. Click *Plans* to view the list of migration plans.
. Click the *Options* menu {kebab} of a specific migration plan and select *Logs*.
. Click *Download Logs* to download the logs of the Migration controller, Velero, and Restic for all clusters.
. To download a specific log:

.. Specify the log options:

* *Cluster*: Select the source, target, or CAM host cluster.
* *Log source*: Select *Velero*, *Restic*, or *Controller*.
* *Pod source*: Select the Pod name, for example, `controller-manager-78c469849c-v6wcf`
+
The selected log is displayed.
+
You can clear the log selection settings by changing your selection.

.. Click *Download Selected* to download the selected log.

Optionally, you can access the logs by using the CLI, as in the following example:

----
$ oc logs <pod-name> -f -n openshift-migration <1>
----
<1> Specify the Pod name.
