// Module included in the following assemblies:
//
// migration/migrating_openshift_3_to_4/migrating-openshift-3-to-4.adoc
[id='migration-running-migration-plan-cam_{context}']
= Running a migration plan in the CAM web console

You can migrate applications by running the migration plan you created in the CAM web console.

.Prerequisites

* Connected source cluster(s)
* Connected target cluster
* Connected S3 repository
* Valid migration plan

.Procedure

. Select a migration plan and click *Stage* (copies the data from the source cluster to the target cluster without stopping the application) or *Migrate* (stops the application on the source cluster and moves the data to the target cluster).

. Optionally, if you click *Migrate*, you can select *Do not stop applications on the source cluster during migration*.
. Click *Migrate*.

. When the migration is complete, verify that the application migrated successfully in the target cluster's web console:

.. Navigate to *Home* -> *Projects* and click the migrated project to view its status.
.. In the *Routes* section, click *Location* to ensure that the application is functioning.
.. Navigate to *Storage* -> *Persistent volumes* to verify that the migrated persistent volume is correctly provisioned.
