// Module included in the following assemblies:
//
// migration/migrating_3_4/migrating-applications-with-cam.adoc
// migration/migrating_4_1_4/migrating-applications-with-cam.adoc
// migration/migrating_4_2_4/migrating-applications-with-cam.adoc
[id='migration-changing-migration-plan-limits_{context}']
= Changing migration plan limits for large migrations

You can change the migration plan limits for large migrations.

[IMPORTANT]
====
Changes should first be tested in your environment to avoid a failed migration.
====

A single migration plan has the following default limits:

* 10 namespaces
+
If this limit is exceeded, the CAM web console displays a *Namespace limit exceeded* error and you cannot create a migration plan.

* 100 Pods
+
If the Pod limit is exceeded, the CAM web console displays a warning message similar to the following example: *Plan has been validated with warning condition(s). See warning message. Pod limit: 100 exceeded, found: 104*.

* 100 persistent volumes
+
If the persistent volume limit is exceeded, the CAM web console displays a similar warning message.

.Procedure

. Edit the Migration controller CR:
+
----
$ oc get migrationcontroller -n openshift-migration
NAME AGE
migration-controller 5d19h

$ oc edit migrationcontroller -n openshift-migration
----

. Update the following parameters:
+
[source,yaml]
----
[...]
migration_controller: true

# This configuration is loaded into mig-controller, and should be set on the
# cluster where `migration_controller: true`
mig_pv_limit: 100
mig_pod_limit: 100
mig_namespace_limit: 10
[...]
----
