[id="modifying-kubelet-one-time_{context}"]
= Modifying the kubelet as a one-time scenario

To modify the kubelet in a one-time scenario without rebooting the node due to the change of `machine-config(spec":{"paused":false}})`, allowing you to modify the kubelet without affecting the service, follow this procedure.

.Procedure

. Connect to the node in debug mode:
+
[source,terminal]
----
$ oc debug node/<node>
----
+
[source,terminal]
----
$ chroot /host
----

. After access is established, check the content:
+
[source,terminal]
----
$ systemctl cat kubelet
----
+
.Example output
[source,terminal]
----
# /etc/systemd/system/kubelet.service
mode: 0644
path: "/etc/systemd/system/kubelet.service.d/20-logging.conf"
contents:
  inline: |
    [Service]
    Environment="KUBELET_LOG_LEVEL=2"
----

. Define the new verbosity required in the `/etc/systemd/system/kubelet.service.d/20-logging.conf` file. In this example, the verbosity is changed from `v=1` to `v=8`:
+
[source,terminal]
----
$ vi -i -e 's/--v=1/--v=8/g' /etc/systemd/system/kubelet.service.d/20-logging.conf
----
+
Editing the config file or installing a new `logging.conf` file overrides the log level.

. Restart the service:
+
[source,terminal]
----
$ systemctl daemon-reload
----
+
[source,terminal]
----
$ systemctl restart kubelet
----

. Gather the logs, then edit the kubelet log level to revert to the former value to prevent issues, such as this error:
+
[source,terminal]
----
E0514 12:47:17.998892    2281 daemon.go:1350] content mismatch for file /etc/systemd/system/kubelet.service: [Unit]
----
