// Module included in the following assemblies:
//
// * monitoring/cluster_monitoring/configuring-the-monitoring-stack.adoc

[id="maintenance-and-support_{context}"]
= Maintenance and support

The supported way of configuring {product-title} Monitoring is by configuring it using the options described in this document. *Do not use other configurations, as they are unsupported.* Configuration paradigms might change across Prometheus releases, and such cases can only be handled gracefully if all configuration possibilities are controlled. If you use configurations other than those described in this section, your changes will disappear because the cluster-monitoring-operator reconciles any differences. The operator reverses everything to the defined state by default and by design.

Explicitly unsupported cases include:

* *Creating additional `ServiceMonitor` objects in the `openshift-&#42;` namespaces.* This extends the targets the cluster monitoring Prometheus instance scrapes, which can cause collisions and load differences that cannot be accounted for. These factors might make the Prometheus setup unstable.
* *Creating unexpected `ConfigMap` objects or `PrometheusRule` objects.* This causes the cluster monitoring Prometheus instance to include additional alerting and recording rules.
* *Modifying resources of the stack.* The Prometheus Monitoring Stack ensures its resources are always in the state it expects them to be. If they are modified, the stack will reset them.
* *Using resources of the stack for your purposes.* The resources created by the Prometheus Cluster Monitoring stack are not meant to be used by any other resources, as there are no guarantees about their backward compatibility.
* *Stopping the Cluster Monitoring Operator from reconciling the monitoring stack.*
* *Adding new alerting rules.*
* *Modifying the monitoring stack Grafana instance.*
