// Module included in the following assemblies:
//
// * monitoring/user-workload-monitoring.adoc

[id="granting-a-user-access-to-metrics_{context}"]
= Granting a user access to metrics

By default, only cluster administrator users have access to user workload metrics. Using the soft tenancy feature, you can also grant metrics access to an arbitrary user, who only has access to a particular project.

.Prerequisites

* You need to have deployed the workload that you want to monitor, such as an application or a service. This example uses the application described in xref:../monitoring/user-workload-monitoring.adoc#deploying-a-sample-application[Deploying a sample application].
* You need to have user workload monitoring enabled.
* You need to have a user created. For the sake of an example, you can create the `johnsmith` user by running `oc create user johnsmith`.

.Procedure

. In the Web console, navigate to *User Management* -> *Role Bindings* -> *Create Binding*.
. In the *Role Name* field, enter `cluster-monitoring-view`.
. In the *Subject Name* enter name of the user, for example `johnsmith`.
. Confirm the role binding. Now the user has been assigned the `cluster-monitoring-view` role, which allows him to access the metrics.
