// Module included in the following assemblies:
//
// * about-ocp-monitoring/about-ocp-monitoring.adoc

:_mod-docs-content-type: CONCEPT
[id="monitoring-stack-overview_{context}"]
= {product-title} overview

[role="_abstract"]
Your cluster includes a preconfigured, preinstalled, and self-updating monitoring stack that monitors core platform components. You also have the option to enable _user workload monitoring_ to monitor your own projects.

Core platform monitoring::
A cluster administrator can configure the monitoring stack with the supported configurations. Monitoring best practices are delivered out of the box.
+
_A set of alerts_ is included by default that notify administrators about issues with a cluster. _Default dashboards_ in the web console include visual representations of _cluster metrics_ to help you quickly understand the state of your cluster. With the web console, you can access metrics and manage alerts.

User workload monitoring::
After a cluster installation, cluster administrators can optionally enable user workload monitoring. By using this feature, cluster administrators, developers, and other users can configure how services and pods are monitored in their own projects.

As a cluster administrator, you can find answers to common problems, such as user metrics unavailability and high consumption of disk space by Prometheus, in "Troubleshooting monitoring issues".
