// Module included in the following assemblies:
//
// * network_observability/observing-network-traffic.adoc

:_mod-docs-content-type: CONCEPT
[id="network-observability-user-defined-networks_{context}"]
= User-defined networks

//delete comments before merge
//remember to update file name to match appropriate template
//likely a procedure; creating PR to have visual to work with and check against other content in observing-network-traffic to make sure it follows same format for consistency
//06/04/2025: copy/paste from blog post https://netobserv.io/posts/what-s-new-in-network-observability-1-8/ to create PR

User-defined networks (UDN) improve the flexibility and segmentation capabilities of the default Layer 3 topology for a Kubernetes pod network by enabling custom Layer 2 and Layer 3 network segments, where all these segments are isolated by default. These segments act as either primary or secondary networks for container pods and virtual machines that use the default OVN-Kubernetes CNI plugin.

UDNs enable a wide range of network architectures and topologies, enhancing network flexibility, security, and performance.

When UDN is enabled with Network Observability, the *Traffic* flow table has a UDN labels column. You can filter on *Source Network Name* and *Destination Network Name*.

The UDN feature also has a `ClusterUserDefinedNetwork` resource that allows a UDN to span across multiple namespaces.

[NOTE]
====
User-defined networks do not need to be enabled first in OpenShift Networking. You can configure Network Observability for UDN, and then enable UDN in OpenShift Networking.
====
//placeholder so info is there.
//fix this note. the wording, use attributes, etc.