// Module included in the following assemblies:
//
// * network_observability/network-observability-alerts.adoc

:_mod-docs-content-type: CONCEPT
[id="network-observability-alerts-overview_{context}"]
= Network observability alerts overview

//About network observability alerts? Network observability default alerts?

[role="_abstract"]
Network observability comes with predefined alerts for your convenience, so you can make the most of network observability's built-in metrics without writing complex PromQL queries or fine-tuning them yourself. The predefined alerts provide a quick health indication of your cluster's network.

//[id="network-observability-default-alerts_{context}"]
//== Default alerts
By default, network observability creates some alerts that are contextual to the features you enable.

For example, packet-drop-related alerts are only created if the `PacketDrop` agent feature is enabled. Because alerts are built on metrics, you might also see configuration warnings if some enabled alerts are missing their required metrics.

You can configure these metrics in `spec.processor.metrics.includeList` object of the `FlowCollector` custom resource (CR).

Here is a list of the alerts installed by default:

`PacketDropsByDevice`:: Triggered on a high percentage of packet drops from devices (`/proc/net/dev`). This alert is grouped by node, with a *Warning* severity above 5%.
`PacketDropsByKernel`:: Triggered on a high percentage of packet drops by the kernel. This alert requires the `PacketDrop` agent feature. Two variants are installed by default:
    * Grouped by node, with *Info* severity above 5% and *Warning* above 10%.
    * Grouped by namespace, with *Info* severity above 10% and *Warning* above 20%.
`IPsecErrors`:: Triggered when the Network Observability Operator detects IPsec encryption errors. This alert requires the `IPSec` agent feature.
`NetpolDenied`:: Triggered when the Network Observability Operator detects traffic that is denied by network policies. This alert requires the `NetworkEvents` agent feature.
`LatencyHighTrend`:: Triggered when the Network Observability Operator detects an increase in TCP latency. This alert requires the `FlowRTT` agent feature.
`DNSErrors`:: Triggered when the Network Observability Operator detects DNS errors. This alert requires the `DNSTracking` agent feature.
//* `ExternalEgressHighTrend`: TODO.
//* `ExternalIngressHighTrend`: TODO.

There are also some operational alerts that relate to network observability's self-health:

`NetObservNoFlows`:: Triggered when no flows are being observed for a certain period.
`NetObservLokiError`:: Triggered when flows are being dropped due to Loki errors.

You can configure, extend, or disable alerts for network observability. The configured alerts generate a `PrometheusRule` resource, which is used to feed the `Prometheus AlertManager`.