// Module included in the following assemblies:
//
// network_observability/metrics-alerts-dashboards.adoc

:_mod-docs-content-type: PROCEDURE
[id="network-observability-configuring-custom-metrics_{context}"]
= Configuring custom metrics by using FlowMetric API

[role="_abstract"]
You can configure the `FlowMetric` API to create custom metrics by using flowlogs data fields as Prometheus labels. You can add multiple `FlowMetric` resources to a project to see multiple dashboard views.

.Procedure

. In the web console, navigate to *Ecosystem* -> *Installed Operators*.
. In the *Provided APIs* heading for the *NetObserv Operator*, select *FlowMetric*.
. In the *Project:*  dropdown list, select the project of the Network Observability Operator instance.
. Click *Create FlowMetric*.
. Configure the `FlowMetric` resource for your custom metrics. For examples, see "Configuring custom metrics by using FlowMetric API examples".

.Verification
. Once the pods refresh, navigate to *Observe* -> *Metrics*.
. In the *Expression* field, you can type the metric name to view the corresponding result.