// Module included in the following assemblies:

// * networking/network_observability/installing-operators.adoc

:_mod-docs-content-type: PROCEDURE
[id="network-observability-lokistack-create_{context}"]
= Creating a LokiStack custom resource
You can deploy a LokiStack using the web console or CLI to create a namespace, or new project.

include::snippets/logging-clusteradmin-access-logs-snip.adoc[]
For more information about creating a `cluster-admin` group, see the "Additional resources" section.  

.Procedure

. Navigate to *Operators* -> *Installed Operators*, viewing *All projects* from the *Project* dropdown.
. Look for *Loki Operator*. In the details, under *Provided APIs*, select *LokiStack*.
. Click *Create LokiStack*.
. Ensure the following fields are specified in either *Form View* or *YAML view*:
+
[source,yaml]
----
  apiVersion: loki.grafana.com/v1
  kind: LokiStack
  metadata:
    name: loki
    namespace: netobserv   <1>
  spec:
    size: 1x.small
    storage:
      schemas:
      - version: v12
        effectiveDate: '2022-06-01'
      secret:
        name: loki-s3
        type: s3
    storageClassName: gp3  <2>
    tenants:
      mode: openshift-network
----
<1> The installation examples in this documentation use the same namespace, `netobserv`, across all components. You can optionally use a different namespace.
<2> Use a storage class name that is available on the cluster for `ReadWriteOnce` access mode. You can use `oc get storageclasses` to see what is available on your cluster.
+
[IMPORTANT]
====
You must not reuse the same `LokiStack` that is used for cluster logging.
====
. Click *Create*.

[id="deployment-sizing_{context}"]
== Deployment Sizing
Sizing for Loki follows the format of `N<x>._<size>_` where the value `<N>` is the number of instances and `<size>` specifies performance capabilities.

[NOTE]
====
1x.extra-small is for demo purposes only, and is not supported.
====

.Loki Sizing
[options="header"]
|========================================================================================
|                              | 1x.extra-small  | 1x.small            | 1x.medium
| *Data transfer*              | Demo use only.  | 500GB/day           | 2TB/day
| *Queries per second (QPS)*   | Demo use only.  | 25-50 QPS at 200ms  | 25-75 QPS at 200ms
| *Replication factor*         | None            | 2                   | 3
| *Total CPU requests*         | 5 vCPUs         | 36 vCPUs            | 54 vCPUs
| *Total Memory requests*      | 7.5Gi           | 63Gi                | 139Gi
| *Total Disk requests*        | 150Gi           | 300Gi               | 450Gi
|========================================================================================