// Module included in the following assemblies:
// * observability/network_observability/network-observability-automatic-installation.adoc

:_mod-docs-content-type: PROCEDURE
[id="network-observability-prevent-automatic-installation-during-upgrade_{context}"]
= Prevent automatic network observability installation during upgrades

[role="_abstract"]
You can configure the Network custom resource (CR) to prevent the Cluster Network Operator (CNO) from automatically installing network observability during a cluster upgrade.

.Prerequisites

* You have access to the cluster as a user with the `cluster-admin` role.
* The OpenShift CLI (`oc`) is installed.
* For Technology Preview, the `NetworkObservabilityInstall` feature gate is enabled for automatic installation to occur during the upgrade.

.Procedure

. Before upgrading your cluster, edit the Network CR by running the following command:
+
[source,terminal]
----
$ oc edit network.config.openshift.io cluster
----

. Add the `NoAction` installation policy to the `spec` section:
+
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  networkObservability:
    installationPolicy: NoAction
# ...
----

. Save and close the file to apply the changes.

. Proceed with the cluster upgrade. The CNO skips the network observability installation during and after the upgrade process.
