// Module included in the following assemblies:
//
// * operating/manage-network-policies.adoc
:_module-type: CONCEPT
[id="network-graph-view_{context}"]
= Network graph view

[role="_abstract"]
The network graph provides visibility and control over:

* The allowed network connections, as defined by the Kubernetes network policies.
* The active communications paths among namespaces and deployments.

In the *Network Graph* view, you can configure the type of connections you want to see.
In the *Flows* section (upper left), select:

* *Active* to view only active connections.
* *Allowed* to view only allowed network connections.
* *All* to view both active and allowed network connections.

In the network graph, each circle represents a deployment, each surrounding box represents a Kubernetes namespace, and each thick line represents connection between namespaces.
You can hover over these items to view more details.

To understand the meaning of other symbols in the network graph, move you mouse over other symbols in the legend (lower left) to view the tooltip indicating the meaning of those symbols.

When you hover over:

* a connection, you see information about the network flow, which includes active connections, port numbers and protocols in use.
* a deployment, you see information about ingress and egress connections, protocols, port numbers in use, and the direction of the network traffic between deployments.

[NOTE]
====
You need {product-title} version 3.0.47 or newer to see information about ingress and egress connections, protocols, port numbers, and the direction of the network traffic.
====

[discrete]
== Allowed network connections

{product-title} processes all network policies in each secured cluster to show you which deployments can contact each other, and which can reach external networks.

The network graph shows possible network connections as dashed lines.

[discrete]
== Actual network flows

{product-title} monitors running deployments and tracks traffic between them.
The network graph shows observed network flows as solid lines.

[discrete]
== Network baseline

{product-title} discovers existing network flows and creates a baseline.
//See link:/docs/manage-network-policies/use-network-baselining/[Use network baselining] for more details.

To view the network baseline for a deployment, select that deployment in the *Network Graph* view.
The *Network Flows* details panel show both anomalous and baseline flows.
From this panel, you can:

* Mark network flows from the baseline as anomalous by selecting *Mark as Anomalous*.
* Add network flows to baseline from the anomalous flows by selecting *Add to Baseline*.

[NOTE]
====
To use the *Network baseline* feature, you must use {product-title} version 3.0.54 or newer.
====

[discrete]
== External entities and connections

The *Network Graph* view shows information about network connections between managed clusters and external sources.
{product-title} also automatically discovers and highlights public CIDR (Classless Inter-Domain	Routing) addresses blocks, such as Google Cloud, AWS, Azure, Oracle Cloud, and Cloudflare.
Using this information, you can identify deployments with active external connections and if they are making or receiving unauthorized connections from outside of your network.

[NOTE]
====
You need {product-title} version 3.0.52 or newer to see information about active external connections.
====

By default, the external connections point to a common *External Entities* box, and different CIDR addresses blocks in the *Network Graph* view.
However, you can choose not to show auto-discovered CIDR blocks.

{product-title} includes IP ranges for the following cloud providers:

* Google Cloud
* AWS
* Azure
* Oracle Cloud
* Cloudflare

{product-title} fetches and updates the cloud providers' IP ranges every 7 days.
If you are using offline mode,  you can update these ranges by installing new support packages.
//Link to offline docs
