// Module included in the following assemblies:
//
// * observability/network_observability/network-observability-automatic-installation.adoc

:_mod-docs-content-type: PROCEDURE
[id="network-observability-automatic-installation-verification_{context}"]
= Verify automatic network observability installation

[role="_abstract"]
Verify that the Network Observability Operator and FlowCollector are running after automatic installation during cluster creation.

.Prerequisites

* You created the cluster with the `NetworkObservabilityInstall` feature gate enabled.
* You have access to the cluster as a user with the `cluster-admin` role.
* The OpenShift CLI (`oc`) is installed.

.Procedure

. Verify that the Network Observability Operator is installed and running by running the following command:
+
[source,terminal]
----
$ oc get pods -n netobserv-operator
----
+
.Example output
[source,terminal]
----
NAME                                                READY   STATUS    RESTARTS   AGE
netobserv-controller-manager-6d4b8d9f8c-xk7lm      2/2     Running   0          5m
----

. Verify that the cluster has a `FlowCollector` resource by running the following command:
+
[source,terminal]
----
$ oc get flowcollector cluster -n netobserv
----
+
.Example output
[source,terminal]
----
NAME      AGENT   SAMPLING   DEPLOYMENT MODEL   STATUS
cluster   eBPF    400        Service            Ready
----

. Verify that network traffic data is available in the web console by navigating to *Observe* -> *Network Traffic*.
