// Module included in the following assemblies:
// * network_observability/release_notes_archive/network-observability-operator-release-notes-archive.adoc

:_mod-docs-content-type: REFERENCE
[id="network-observability-operator-release-notes-1-6-0-new-features-and-enhancements_{context}"]
= Network Observability Operator 1.6.0 new features and enhancements

[role="_abstract"]
You can review the following new features and enhancements for the Network Observability Operator 1.6.0.

[id="network-observability-lokiless-enhancements-1.6_{context}"]
== Enhanced use of Network Observability Operator without Loki
You can now use Prometheus metrics and rely less on Loki for storage when using the Network Observability Operator.

For more information, see:

* xref:../../../observability/network_observability/installing-operators.adoc#network-observability-without-loki_network_observability[Network observability without Loki]

[id="network-observability-custom-metrics-1.6_{context}"]
== Custom metrics API
You can create custom metrics out of flowlogs data by using the `FlowMetrics` API. Flowlogs data can be used with Prometheus labels to customize cluster information on your dashboards. You can add custom labels for any subnet that you want to identify in your flows and metrics. This enhancement can also be used to more easily identify external traffic by using the new labels `SrcSubnetLabel` and `DstSubnetLabel`, which exists both in flow logs and in metrics. Those fields are empty when there is external traffic, which gives a way to identify it.

For more information, see:

* xref:../../../observability/network_observability/metrics-alerts-dashboards.adoc#network-observability-custom-metrics_metrics-dashboards-alerts[Custom metrics]
* xref:../../../observability/network_observability/flowmetric-api.adoc#flowmetric-flows-netobserv-io-v1alpha1[FlowMetric API reference]

[id="network-observability-eBPF-performance-enhancements-1.6_{context}"]
== eBPF performance enhancements
Experience improved performances of the eBPF agent, in terms of CPU and memory, with the following updates:

* The eBPF agent now uses TCX webhooks instead of TC.
* The *NetObserv / Health* dashboard has a new section that shows eBPF metrics.
** Based on the new eBPF metrics, an alert notifies you when the eBPF agent is dropping flows.
* Loki storage demand decreases significantly now that duplicated flows are removed. Instead of having multiple, individual duplicated flows per network interface, there is one de-duplicated flow with a list of related network interfaces.

[IMPORTANT]
=====
With the duplicated flows update, the *Interface* and *Interface Direction* fields in the *Network Traffic* table are renamed to *Interfaces* and *Interface Directions*, so any bookmarked *Quick filter* queries using these fields need to be updated to `interfaces` and `ifdirections`.
=====

For more information, see:

* xref:../../../observability/network_observability/network-observability-operator-monitoring.adoc#network-observability-netobserv-dashboard-ebpf-agent-alerts_network_observability[Using the eBPF agent alert]
* xref:../../../observability/network_observability/network-observability-overview.adoc#network-observability-dashboards_network-observability-overview[Network observability metrics dashboards]
* xref:../../../observability/network_observability/observing-network-traffic.adoc#network-observability-quickfilter_nw-observe-network-traffic[Filtering the network traffic]


[id="network-observability-ebpf-collection-filtering-1.6_{context}"]
== eBPF collection rule-based filtering
You can use rule-based filtering to reduce the volume of created flows. When this option is enabled, the *Netobserv / Health* dashboard for eBPF agent statistics has the *Filtered flows rate* view.

For more information, see:

* xref:../../../observability/network_observability/observing-network-traffic.adoc#network-observability-ebpf-flow-rule-filter_nw-observe-network-traffic[eBPF flow rule filter]
