// Module included in the following assemblies:
// * network_observability/network-observability-operator-release-notes-archive.adoc

:_mod-docs-content-type: REFERENCE
[id="network-observability-operator-release-notes-1-2-0-notable-technical-changes_{context}"]
= Network Observability Operator 1.2.0 notable technical changes

[role="_abstract"]
The Network Observability Operator 1.2.0 release requires installation in the `openshift-netobserv-operator` namespace due to new technical changes. Users who previously used a custom namespace must delete the old instance and reinstall the Operator.

Previously, you could install the Network Observability Operator using a custom namespace. This release introduces the `conversion webhook` which changes the `ClusterServiceVersion`. Because of this change, all the available namespaces are no longer listed. Additionally, to enable Operator metrics collection, namespaces that are shared with other Operators, like the `openshift-operators` namespace, cannot be used.

Now, the Operator must be installed in the `openshift-netobserv-operator` namespace.

You cannot automatically upgrade to the new Operator version if you previously installed the Network Observability Operator using a custom namespace. If you previously installed the Operator using a custom namespace, you must delete the instance of the Operator that was installed and re-install your operator in the `openshift-netobserv-operator` namespace. It is important to note that custom namespaces, such as the commonly used `netobserv` namespace, are still possible for the `FlowCollector`, Loki, Kafka, and other plug-ins.

 * link:https://issues.redhat.com/browse/NETOBSERV-907[*NETOBSERV-907*]
 * link:https://https://issues.redhat.com/browse/NETOBSERV-956[*NETOBSERV-956*]