// Module included in the following assemblies:
// * network_observability/network-observability-release-notes-1-10.adoc

:_mod-docs-content-type: REFERENCE
[id="network-observability-operator-release-notes-1-10-known-issues_{context}"]
= Network Observability Operator 1.10 known issues

[role="_abstract"]
Review the following known issues and their recommended workarounds (where available) that might affect your use of the Network Observability Operator 1.10 release.

[id="eBPF-agent-compatibility-with-older-open-shift-versions_{context}"]
== eBPF agent compatibility with older {product-title} versions
The eBPF agent used in the Network Observability Command Line Interface (CLI) packet capture feature is incompatible with {product-title} versions 4.16 and older.

This limitation prevents the eBPF-based Packet Capture Agent (PCA) from functioning correctly on those older clusters.

To work around this problem, you must manually configure PCA to use an older, compatible eBPF agent container image. For more information, see the Red Hat Knowledgebase Solution link:https://access.redhat.com/solutions/7132671[eBPF agent compatibility with older Openshift versions in Network Observability CLI 1.10+].

link:https://issues.redhat.com/browse/NETOBSERV-2358[NETOBSERV-2358]
