// Module included in the following assemblies:
//
// network_observability/observing-network-traffic.adoc

:_mod-docs-content-type: REFERENCE
[id="network-observability-configuring-options-overview_{context}"]
= Configuring advanced options for the Overview view

[role="_abstract"]
Customize the network traffic *Overview* view by configuring advanced options, such as graph scope, label truncation, and panel management, to refine the display of flow rate statistics and traffic data.

To access the advanced options, click *Show advanced options*. You can configure the details in the graph by using the *Display options* drop-down menu. The options available are as follows:

* *Scope*: Select to view the components that network traffic flows between. You can set the scope to *Node*, *Namespace*, *Owner*, *Zones*, *Cluster* or *Resource*. *Owner* is an aggregation of resources. *Resource* can be a pod, service, node, in case of host-network traffic, or an unknown IP address. The default value is *Namespace*.
* *Truncate labels*: Select the required width of the label from the drop-down list. The default value is *M*.

[id="network-observability-cao-managing-panels-overview_{context}"]
== Managing panels and display
You can select the required panels to be displayed, reorder them, and focus on a specific panel. To add or remove panels, click *Manage panels*.

The following panels are shown by default:

* *Top X average bytes rates*
* *Top X bytes rates stacked with total*

Other panels can be added in *Manage panels*:

* *Top X average packets rates*
* *Top X packets rates stacked with total*

*Query options* allows you to choose whether to show the *Top 5*, *Top 10*, or *Top 15* rates.