// Module included in the following assemblies:

// * networking/network_observability/configuring-operators.adoc

:_mod-docs-content-type: CONCEPT
[id="network-observability-config-flows-at-ingestion_{context}"]

= Filtering network flows at ingestion

You can create filters to limit the number of generated network flows, which is a way to reduce the amount of resources used by Network Observability.

There are two different kinds of filters that you can configure:

[id="ebpf-agent-filters_{context}"]
== eBPF agent filters

eBPF agent filters maximize performance because they take effect at the earliest stage of the Network Observability process

To configure eBPF agent filters with the Network Observability Operator, see "Filtering eBPF flow data using multiple rules".
//Filtering eBPF flow data using multiple rules is handled by PR 92375. Add as Additional resource in assembly

[id="flowlogs-pipeline-filters_{context}"]
== Flowlogs-pipeline filters

Flowlogs-pipeline filters use a simple query language to filter network flows:

[source, terminal]
----
(srcnamespace="netobserv" OR (srcnamespace="ingress" AND dstnamespace="netobserv")) AND srckind!="service"
----

Flowlogs-pipeline filters offer more filter flexibility because they take effect later in the process, but they primarily improve data storage.

You can configure the Network Observability Operator in the `FlowCollector` resource's `spec.processor.filters.` parameter. For example:

.Example YAML Flowlogs-pipeline filter
[source,yaml]
----
apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
spec:
  namespace: netobserv
  deploymentModel: Direct
  agent:
  processor:
    filters:
      - query: |
          (SrcK8S_Namespace="netobserv" OR (SrcK8S_Namespace="openshift-ingress" AND DstK8S_Namespace="netobserv"))
        outputTarget: Loki  <1>
        sampling: 10  <2>
----
<1> The filter can target a specific output (such as Loki logs or exported data), or all outputs.
<2> Optionally, a sampling ratio can be associated with the filter