// Module included in the following assemblies:
//
// * nodes/nodes-pods-allocate-dra.adoc

:_mod-docs-content-type: REFERENCE
[id="nodes-pods-allocate-dra-taints_{context}"]
= About device taints and tolerations

[role="_abstract"]
You can use device taints and tolerations with Dynamic Resource Allocation (DRA) to let drivers and administrators keep pods off of specific devices or restrict devices for specialized workloads.

An administrator can taint a device by creating a `DeviceTaintRule` object that adds a taint to any device that matches the specified device selector. The device selector can be a device class, a DRA driver, a device resource pool, or a specific device. The scheduler will not be able to schedule any new workloads on that device. And, depending upon the taint effect, any existing workloads are removed from the device and moved to other devices. You can apply matching tolerations for specific workloads through a resource claim to allow that workload to use the tainted device. 

For example, you can use a device taint rule to reserve devices for specialized workloads. Or, if a device is not working or is off-line for maintenance, you can prevent new pods from being scheduled on the device and remove any existing pods from the device.

[NOTE]
====
Taints can also be published directly by a DRA driver in a resource slice. Consult the documentation of a DRA driver to learn whether the driver uses taints and what their keys and values are.
====

The following example device taint rule taints all devices controlled by the `dra.example.com` driver. 

[source,yaml]
----
apiVersion: resource.k8s.io/v1
kind: DeviceTaintRule
metadata:
  name: example
spec:
  deviceSelector:
    driver: dra.example.com
  taint:
    key: dra.example.com/unhealthy
    value: Broken
    effect: NoExecute
    tolerationSeconds: 300
----

where:

`spec.deviceSelector`:: Specifies how to identify the devices that the taint applies to. Use the following options:
+
* `driver`. Specifies all the devices controlled by a specific DRA driver are tainted.
* `deviceClass`. Specifies that all the devices configured under a specific device class are tainted. You can specify a `deviceclass` and specific `driver` to avoid ambiguity.
* `pool`. Specifies that all the devices configured under a specific DRA driver node resource pool are tainted. You can specify a `pool` and specific `driver` to avoid ambiguity.
* `device` Specifies that an exact device is tainted. You can specify a `device`, `pool`, and specific `driver` to avoid ambiguity. 

`spec.taint.key`:: Specifies the key of the key/value pair for the taint.
`spec.taint.value`:: Specifies the value of the key/value pair for the taint.
`spec.taint.effect`:: Specifies the effect of the taint. Use one of the following options:
+
* `NoSchedule` blocks new workloads from being added to the device, but leaves existing workloads in place.
* `NoExecute` blocks new workloads from being added to the device and removes existing workloads. You can use the `tolerationSeconds` parameter with the `NoExecute` parameter to indicate how long a workload can remain bound to a device before being evicted.
* `None` is ignored by the scheduler. New workloads can be added to the device and existing workloads remain.

The following resource claim contains a toleration for the taint created with the previous device taint rule example. In this example, any associated workloads remain on the device for 300 seconds before termination.

[source,yaml]
----
apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  name: resilient-workload-claim
  namespace: default
spec:
  resourceClassName: example-device-class
  tolerations:
    - key: "dra.example.com/unhealthy"
      operator: "Equal"
      value: "Broken"
      effect: "NoExecute"
      tolerationSeconds: 300 
----
