// Module included in the following assemblies:
//
// * nodes/nodes-pods-using.adoc

:_mod-docs-content-type: CONCEPT
[id="nodes-pods-using-about_{context}"]
= Understanding pods

[role="_abstract"]
Understand how pods are scheduled, updated, and replaced in {product-title} so you can deploy and troubleshoot container workloads on the cluster.

Pods are the rough equivalent of a physical or virtual machine instance to a container. Each pod is allocated an internal IP address and has exclusive use of the port space for that pod. Containers within the pod can share local storage and networking.

Pods move through a lifecycle that begins when they are defined and assigned to a node, and ends when their containers exit or the pod is removed for another reason. Depending on policy and exit code, a pod might be removed after exit or retained to enable access to container logs.

{product-title} treats pods as largely immutable; changes cannot be made to a pod definition while it is running. {product-title} implements changes by terminating an existing pod and recreating it with a modified configuration, base images, or both. Pods are also treated as expendable, and do not maintain state when recreated. Therefore pods should usually be managed by higher-level controllers, rather than directly by users.

ifdef::openshift-enterprise,openshift-webscale[]
[NOTE]
====
For the maximum number of pods per {product-title} node host, see the Cluster limits.
====
endif::[]

[WARNING]
====
Bare pods that are not managed by a replication controller are not rescheduled upon node disruption.
====
