// Module included in the following assemblies:
//
// * nodes/nodes-pods-using.adoc

[id='nodes-pods-using-example_{context}']
= Example pod configurations in {product-title} 

{product-title} leverages the Kubernetes concept of a _pod_, which is one or more Containers deployed
together on one host, and the smallest compute unit that can be defined,
deployed, and managed.

The following is an example definition of a pod that provides a long-running
service, which is actually a part of the {product-title} infrastructure: the
integrated Container image registry. It demonstrates many features of pods, most of
which are discussed in other topics and thus only briefly mentioned here:

[[example-pod-definition]]
.Pod Object Definition (YAML)

[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  annotations: { ... }
  labels:                                <1>
    deployment: registry-1
    deploymentconfig: registry
    registry: default
  generateName: registry-1-       <2>
spec:
  containers:                            <3>
  - env:                                 <4>
    - name: OPENSHIFT_CA_DATA
      value: ...
    - name: OPENSHIFT_CERT_DATA
      value: ...
    - name: OPENSHIFT_INSECURE
      value: "false"
    - name: OPENSHIFT_KEY_DATA
      value: ...
    - name: OPENSHIFT_MASTER
      value: https://master.example.com:8443
    image: openshift/origin-registry:v0.6.2 <5>
    imagePullPolicy: IfNotPresent
    name: registry
    ports:                              <6>
    - containerPort: 5000
      protocol: TCP
    resources: {}
    securityContext: { ... }            <7>
    volumeMounts:                       <8>
    - mountPath: /registry
      name: registry-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-br6yz
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-cfg-at06w
  restartPolicy: Always                 <9>
  serviceAccount: default               <10>
  volumes:                              <11>
  - emptyDir: {}
    name: registry-storage
  - name: default-token-br6yz
    secret:
      secretName: default-token-br6yz
----

<1> Pods can be "tagged" with one or more labels, which can then
be used to select and manage groups of pods in a single operation. The labels
are stored in key/value format in the `*metadata*` hash. One label in this
example is *registry=default*.
<2> Pods must have a unique name within their namespace. A pod definition can specify
the basis of a name with the `*generateName*` attribute, and random characters
will be added automatically to generate a unique name.
<3> `*containers*` specifies an array of Container definitions; in this case (as
with most), just one.
<4> Environment variables can be specified to pass necessary values to each
Container.
<5> Each Container in the pod is instantiated from its own Container image.
<6> The Container can bind to ports which will be made available on the pod's
IP.
<7> {product-title} defines a security context for Containers which specifies whether they are allowed to run as
privileged Containers, run as a user of their choice, and more. The default
context is very restrictive but administrators can modify this as needed.
<8> The Container specifies where external storage volumes should be mounted
within the Container. In this case, there is a volume for storing the registry's
data, and one for access to credentials the registry needs for making requests
against the {product-title} API.
<9> The pod restart policy with possible values `Always`, `OnFailure`, and `Never`. The default value is `Always`.
<10> Pods making requests against the {product-title} API is a common enough pattern
that there is a `*serviceAccount*` field for specifying which service account user the pod should
authenticate as when making the requests. This enables fine-grained access
control for custom infrastructure components.
<11> The pod defines storage volumes that are available to its Container(s) to
use. In this case, it provides an ephemeral volume for the registry storage and
a `*secret*` volume containing the service account credentials.

[NOTE]
====
This pod definition does not include attributes that
are filled by {product-title} automatically after the pod is created and
its lifecycle begins. The
link:https://kubernetes.io/docs/concepts/workloads/pods/pod/[Kubernetes pod documentation] has details about the functionality and purpose of pods.
====

