// Module included in the following assemblies:
//
//* authentication/configmaps.adoc

[id="nodes-pods-configmaps-use-case-consuming-in-env-vars_{context}"]
= Populating environment variables in containers by using config maps

Config maps can be used to populate individual environment variables in containers or to populate environment variables in containers from all keys that form valid environment variable names.

As an example, consider the following config map:

.`ConfigMap` with two environment variables
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config <1>
  namespace: default <2>
data:
  special.how: very <3>
  special.type: charm <3>
----
<1> Name of the config map.
<2> The project in which the config map resides. Config maps can only be referenced by pods in the same project.
<3> Environment variables to inject.

.`ConfigMap` with one environment variable
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config <1>
  namespace: default
data:
  log_level: INFO <2>
----
<1> Name of the config map.
<2> Environment variable to inject.

.Procedure

* You can consume the keys of this `ConfigMap` in a pod using `configMapKeyRef` sections.
+
.Sample `Pod` specification configured to inject specific environment variables
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env: <1>
        - name: SPECIAL_LEVEL_KEY <2>
          valueFrom:
            configMapKeyRef:
              name: special-config <3>
              key: special.how <4>
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config <3>
              key: special.type <4>
              optional: true <5>
      envFrom: <6>
        - configMapRef:
            name: env-config <7>
  restartPolicy: Never
----
<1> Stanza to pull the specified environment variables from a `ConfigMap`.
<2> Name of a pod environment variable that you are injecting a key's value into.
<3> Name of the `ConfigMap` to pull specific environment variables from.
<4> Environment variable to pull from the `ConfigMap`.
<5> Makes the environment variable optional. As optional, the pod will be started even if the specified `ConfigMap` and keys do not exist.
<6> Stanza to pull all environment variables from a `ConfigMap`.
<7> Name of the `ConfigMap` to pull all environment variables from.
+
When this pod is run, the pod logs will include the following output:
+
----
SPECIAL_LEVEL_KEY=very
log_level=INFO
----

[NOTE]
====
`SPECIAL_TYPE_KEY=charm` is not listed in the example output because `optional: true` is set.
====
