// Module included in the following assemblies:
//
// * nodes/clusters/nodes-cluster-overcommit.adoc
// * post_installation_configuration/node-tasks.adoc

:_mod-docs-content-type: PROCEDURE
[id="nodes-cluster-resource-override-deploy-console_{context}"]
= Installing the Cluster Resource Override Operator using the web console

[role="_abstract"]
You can use the {product-title} web console to install the Cluster Resource Override Operator to help you control overcommit in your cluster.

ifndef::openshift-rosa,openshift-dedicated[]
By default, the installation process creates a Cluster Resource Override Operator pod on a worker node in the `clusterresourceoverride-operator` namespace. You can move this pod to another node, such as an infrastructure node, as needed. Infrastructure nodes are not counted toward the total number of subscriptions that are required to run the environment. For more information, see "Moving the Cluster Resource Override Operator pods".
endif::openshift-rosa,openshift-dedicated[]

.Prerequisites

* Default container limits are specified in a `LimitRange` object for the project, or limits are configured in `Pod` specs, if you use `memoryRequestToLimitPercent`, `cpuRequestToLimitPercent`, or `limitCPUToMemoryPercent`.
* A CPU request is specified on containers if you use `cpuRequestToRequestPercent`. A CPU limit is not required for that field.

.Procedure

. In the {product-title} web console, navigate to *Home* -> *Projects*.

.. Click *Create Project*.

.. Specify `clusterresourceoverride-operator` as the name of the project.

.. Click *Create*.

. Navigate to *Ecosystem* -> *Software Catalog*.

.. Choose *ClusterResourceOverride Operator* from the list of available Operators and click *Install*.

.. On the *Install Operator* page, make sure *A specific Namespace on the cluster* is selected for *Installation Mode*.

.. Make sure *clusterresourceoverride-operator* is selected for *Installed Namespace*.

.. Select an *Update Channel* and *Approval Strategy*.

.. Click *Install*.

. On the *Installed Operators* page, click *ClusterResourceOverride*.

.. On the *ClusterResourceOverride Operator* details page, click *Create ClusterResourceOverride*.

.. On the *Create ClusterResourceOverride* page, click *YAML view* and edit the YAML template to set the overcommit values as needed:
+
[source,yaml]
----
apiVersion: operator.autoscaling.openshift.io/v1
kind: ClusterResourceOverride
metadata:
  name: cluster
spec:
  podResourceOverride:
    spec:
      memoryRequestToLimitPercent: 50
      cpuRequestToLimitPercent: 25
      limitCPUToMemoryPercent: 200
      cpuRequestToRequestPercent: 50
----
+
where:
+
--
`metadata.name`:: Specifies a name for the CR. The name must be `cluster`.
`spec.podResourceOverride.spec.memoryRequestToLimitPercent`:: Specifies the percentage to override the container memory limit, if used, between 1 and 100. The default is `50`. This parameter is optional.
`spec.podResourceOverride.spec.cpuRequestToLimitPercent`:: Specifies the percentage to override the container CPU limit, if used, between 1 and 100. The default is `25`. This parameter is optional.
`spec.podResourceOverride.spec.limitCPUToMemoryPercent`:: Specifies the percentage to override the container memory limit, if used. Scaling 1 Gi of RAM at 100 percent is equal to 1 CPU core. This is processed before overriding the CPU request, if configured. The default is `200`. This parameter is optional.
`spec.podResourceOverride.spec.cpuRequestToRequestPercent`:: Specifies the percentage of the original CPU request to set as the new CPU request, between 1 and 100. Omit this field to disable request-relative CPU override. This parameter is optional and has no default. A CPU limit is not required.
--

.. Click *Create*.
+
A namespaced `ResourceOverride` object is optional.
You do not create one during Operator installation.
Cluster-wide overcommit continues to use the `ClusterResourceOverride` object named `cluster`.

. Check the current state of the admission webhook by checking the status of the cluster custom resource:

.. On the *ClusterResourceOverride Operator* page, click *cluster*.

.. On the *ClusterResourceOverride Details* page, click *YAML*. The `mutatingWebhookConfigurationRef` section displays when the webhook is called. The `validatingAdmissionPolicyRef` and `validatingAdmissionPolicyBindingRef` sections display when the Operator has created the `resourceoverride-exempt-namespace` policy that denies `ResourceOverride` objects in system namespaces.
+
[source,yaml]
----
apiVersion: operator.autoscaling.openshift.io/v1
kind: ClusterResourceOverride
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operator.autoscaling.openshift.io/v1","kind":"ClusterResourceOverride","metadata":{"annotations":{},"name":"cluster"},"spec":{"podResourceOverride":{"spec":{"cpuRequestToLimitPercent":25,"cpuRequestToRequestPercent":50,"limitCPUToMemoryPercent":200,"memoryRequestToLimitPercent":50}}}}
  creationTimestamp: "2019-12-18T22:35:02Z"
  generation: 1
  name: cluster
  resourceVersion: "127622"
  selfLink: /apis/operator.autoscaling.openshift.io/v1/clusterresourceoverrides/cluster
  uid: 978fc959-1717-4bd1-97d0-ae00ee111e8d
spec:
  podResourceOverride:
    spec:
      cpuRequestToLimitPercent: 25
      cpuRequestToRequestPercent: 50
      limitCPUToMemoryPercent: 200
      memoryRequestToLimitPercent: 50
status:

# ...

    mutatingWebhookConfigurationRef:
      apiVersion: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      name: clusterresourceoverrides.admission.autoscaling.openshift.io
      resourceVersion: "127621"
      uid: 98b3b8ae-d5ce-462b-8ab5-a729ea8f38f3
    validatingAdmissionPolicyRef:
      apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingAdmissionPolicy
      name: resourceoverride-exempt-namespace
      resourceVersion: "127623"
      uid: 7c9e4d2a-1b0f-4a6e-9c3d-5e8f7a6b4c21
    validatingAdmissionPolicyBindingRef:
      apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingAdmissionPolicyBinding
      name: resourceoverride-exempt-namespace
      resourceVersion: "127624"
      uid: 3f1a9c8b-2d4e-47b0-8e5a-6c7d9f0e1b32

# ...

----
+
where:
+
--
`status.resources.mutatingWebhookConfigurationRef`:: Specifies the `ClusterResourceOverride` admission webhook.
`status.resources.validatingAdmissionPolicyRef`:: Specifies the Operator-managed `ValidatingAdmissionPolicy` object named `resourceoverride-exempt-namespace`.
`status.resources.validatingAdmissionPolicyBindingRef`:: Specifies the Operator-managed `ValidatingAdmissionPolicyBinding` object that activates that policy.
--

////
. When the webhook is called, you can add a label to any Namespaces where you want overrides enabled:

.. Click `Administration` -> `Namespaces`.

.. Click the Namespace to edit then click *YAML*.

.. Add the label under `metadata`:
+
----
apiVersion: v1
kind: Namespace
metadata:

# ...

  labels:
    clusterresourceoverrides.admission.autoscaling.openshift.io: enabled
# ...
----
+
where:
+
--
`metadata.labels.clusterresourceoverrides.admission.autoscaling.openshift.io`:: Add the `clusterresourceoverrides.admission.autoscaling.openshift.io: enabled` label to the namespace.
--

////
