// Module included in the following assemblies:
//
// * nodes/nodes-cluster-overcommit.adoc

[id="nodes-cluster-overcommit-configure-nodes-{context}"]

= Configuring nodes for overcommitment

In an overcommitted environment, it is important to properly configure your node to provide best system behavior.

When the node starts, it ensures that the kernel tunable flags for memory
management are set properly. The kernel should never fail memory allocations
unless it runs out of physical memory.

To ensure this behavior, the node instructs the kernel to always overcommit
memory:

----
$ sysctl -w vm.overcommit_memory=1
----

The node also instructs the kernel not to panic when it runs out of memory.
Instead, the kernel OOM killer should kill processes based on priority:

----
$ sysctl -w vm.panic_on_oom=0
----

[NOTE]
====
The above flags should already be set on nodes, and no further action is
required.
====

You can also perform the following configurations for each node:

* Disable or enforce CPU limits using CPU CFS quotas

* Reserve resources for system processes

* Reserve memory across quality of service tiers
