// Module included in the following assemblies:
//
// * nodes/nodes-pods-autoscaling-events.adoc

[id="nodes-pods-autoscaling-events-about_{context}"]
= Understanding scaling by custom metrics

ifdef::openshift-origin,openshift-enterprise,openshift-webscale[]
To use horizontal pod autoscalers, your cluster administrator must have
properly configured cluster metrics.
endif::openshift-origin,openshift-enterprise,openshift-webscale[]


Kubernetes based Event Driven Autoscaler (KEDA). With KEDA, you can drive the scaling of any container in Kubernetes based on the number of events needing to be processed.

KEDA performs two key roles within Kubernetes:

    Agent — KEDA activates and deactivates Kubernetes Deployments to scale to and from zero on no events. This is one of the primary roles of the keda-operator container that runs when you install KEDA.
    Metrics — KEDA acts as a Kubernetes metrics server that exposes rich event data like queue length or stream lag to the Horizontal Pod Autoscaler to drive scale out. It is up to the Deployment to consume the events directly from the source. This preserves rich event integration and enables gestures like completing or abandoning queue messages to work out of the box. The metric serving is the primary role of the keda-operator-metrics-apiserver container that runs when you install KEDA.

When you install KEDA, it creates four custom resources definitions (CRD). These custom resources enable you to map an event source (and the authentication to that event source) to a Deployment, StatefulSet, Custom Resource or Job for scaling:

* `ScaledObject` (`scaledobjects.keda.sh`) represents the desired mapping between an event source (such as Rabbit MQ) and the Kubernetes Deployment, StatefulSet or any Custom Resource that defines /scale subresource. 
* `ScaledJobs` (`scaledjobs.keda.sh`) represents the mapping between event source and Kubernetes Job.
* `ClusterTriggerAuthentication (`clustertriggerauthentications.keda.sh`) and `TriggerAuthentication` (`triggerauthentications.keda.sh`) contain the authentication configuration or secrets to monitor the event source. A ScaledObject or ScaledJob can reference one of these CRDs.

== Supported metrics

KEDA emits the following Kubernetes events:

.Metrics
[cols="3a,5a,5a",options="header"]
|===

|Metric |Description |API version

|ScaledObjectReady
|Normal
|On the first time a ScaledObject is ready, or if the previous ready condition status of the object was Unknown or False

|ScaledJobReady
|Normal
|On the first time a ScaledJob is ready, or if the previous ready condition status of the object was Unknown or False

|ScaledObjectCheckFailed
|Warning
|If the check validation for a ScaledObject fails

|ScaledJobCheckFailed
|Warning
|If the check validation for a ScaledJob fails

|ScaledObjectDeleted
|Normal
|When a ScaledObject is deleted and removed from KEDA watch

|ScaledJobDeleted
|Normal
|When a ScaledJob is deleted and removed from KEDA watch

|KEDAScalersStarted
|Normal
|When Scalers watch loop have started for a ScaledObject or ScaledJob

|KEDAScalersStopped
|Normal
|When Scalers watch loop have stopped for a ScaledObject or a ScaledJob

|KEDAScalerFailed
|Warning
|When a Scaler fails to create or check its event source

|KEDAScaleTargetActivated
|Normal
|When the scale target (Deployment, StatefulSet, etc) of a ScaledObject is scaled to 1

|KEDAScaleTargetDeactivated
|Normal
|When the scale target (Deployment, StatefulSet, etc) of a ScaledObject is scaled to 0

|KEDAScaleTargetActivationFailed
|Warning
|When KEDA fails to scale the scale target of a ScaledObject to 1

|KEDAScaleTargetDeactivationFailed
|Warning
|When KEDA fails to scale the scale target of a ScaledObject to 0

|KEDAJobsCreated
|Normal
|When KEDA creates jobs for a ScaledJob

|TriggerAuthenticationAdded
|Normal
|When a new TriggerAuthentication is added

|TriggerAuthenticationDeleted
|Normal
|When a TriggerAuthentication is deleted

|ClusterTriggerAuthenticationAdded
|Normal
|When a new ClusterTriggerAuthentication is added

|ClusterTriggerAuthenticationDeleted
|Normal
|When a ClusterTriggerAuthentication is deleted

|===
