// Module included in the following assemblies:
//
// * nodes/nodes-sigstore-using.adoc

:_mod-docs-content-type: PROCEDURE
[id="nodes-sigstore-configure-cluster-policy_{context}"]
= Creating a cluster image policy CR

A `ClusterImagePolicy` custom resource (CR) enables a cluster administrator to configure a sigstore signature verification policy for the entire cluster. When enabled, the Machine Config Operator (MCO) watches the `ClusterImagePolicy` object and updates the `/etc/containers/policy.json` and `/etc/containers/registries.d/sigstore-registries.yaml` files on all the nodes in the cluster.

The following example shows general guidelines on how to configure a `ClusterImagePolicy` object. For more details on the parameters, see "About cluster and image policy parameters."

.Prerequisites
// Taken from https://issues.redhat.com/browse/OCPSTRAT-918
* You have a sigstore-supported public key infrastructure (PKI) or a link:https://docs.sigstore.dev/cosign/[Cosign public and private key pair] for signing operations.
* You have a signing process in place to sign your images.
* You have access to a registry that supports Cosign signatures, if you are using Cosign signatures.
* You enabled the required Technology Preview features for your cluster by editing the `FeatureGate` CR named `cluster`:
+
[source,terminal]
----
$ oc edit featuregate cluster
----
+
.Example `FeatureGate` CR
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: FeatureGate
metadata:
  name: cluster
spec:
  featureSet: TechPreviewNoUpgrade <1>
----
<1> Enables the required `SigstoreImageVerification` feature.
+
[WARNING]
====
Enabling the `TechPreviewNoUpgrade` feature set on your cluster cannot be undone and prevents minor version updates. This feature set allows you to enable these Technology Preview features on test clusters, where you can fully test them. Do not enable this feature set on production clusters.
====
+
After you save the changes, new machine configs are created, the machine config pools are updated, and scheduling on each node is disabled while the change is being applied.

.Procedure

. Create a cluster image policy object similar to the following examples. See "About image policy parameters" for specific details on these parameters.
+
--
.Example cluster image policy object with a public key policy and the `MatchRepoDigestOrExact` match policy
[source,yaml]
----
apiVersion: config.openshift.io/v1alpha1
kind: ClusterImagePolicy <1>
metadata:
  name: p1
spec:
  scopes: <2>
    - example.com
  policy: <3>
    rootOfTrust: <4>
      policyType: PublicKey <5>
      publicKey:
        keyData: a2V5RGF0YQ== <6>
        rekorKeyData: cmVrb3JLZXlEYXRh <7>
    signedIdentity: <8>
      matchPolicy: MatchRepoDigestOrExact
----
<1> Creates a `ClusterImagePolicy` object.
<2> Defines a list of repositories or images assigned to this policy. In a cluster image policy, make sure that the policy does not block the deployment of the {product-title} images in the `quay.io/openshift-release-dev/ocp-release` and `quay.io/openshift-release-dev/ocp-v4.0-art-dev` repositories. Images in these repositories are required for cluster operation.
<3> Specifies the parameters that define how the images are verified.
<4> Defines a root of trust for the policy.
<5> Specifies the policy types that define the root of trust, either a public key or a link:https://docs.sigstore.dev/certificate_authority/overview/[Fulcio certifice]. Here, a public key with Rekor verification.
<6> For a public key policy, specifies a base64-encoded public key in the PEM format. The maximum length is 8192 characters.
<7> Optional: Specifies a base64-encoded Rekor public key in the PEM format. The maximum length is 8192 characters.
<8> Optional: Specifies one of the following processes to verify the identity in the signature and the actual image identity:
* `MatchRepoDigestOrExact`.
* `MatchRepository`.
* `ExactRepository`. The `exactRepository` parameter must be specified.
* `RemapIdentity`. The `prefix` and `signedPrefix` parameters must be specified.
--
+
--
.Example cluster image policy object with a Fulcio certificate policy and the `remapIdentity` match policy
[source,yaml]
----
apiVersion: config.openshift.io/v1alpha1
kind: ClusterImagePolicy <1>
metadata:
  name: p1
spec:
  scopes: <2>
    - example.com
  policy: <3>
    rootOfTrust: <4>
      policyType: FulcioCAWithRekor <5>
      fulcioCAWithRekor: <6>
        fulcioCAData: a2V5RGF0YQ==
        fulcioSubject:
          oidcIssuer: "https://expected.OIDC.issuer/"
          signedEmail: "expected-signing-user@example.com"
        rekorKeyData: cmVrb3JLZXlEYXRh <7>
    signedIdentity:
      matchPolicy: RemapIdentity <8>
      remapIdentity:
        prefix: example.com <9>
        signedPrefix: mirror-example.com <10>
----
<1> Creates a `ClusterImagePolicy` object.
<2> Defines a list of repositories or images assigned to this policy. In a cluster image policy, make sure that the policy does not block the deployment of the {product-title} images in the `quay.io/openshift-release-dev/ocp-release` and `quay.io/openshift-release-dev/ocp-v4.0-art-dev` repositories. Images in these repositories are required for cluster operation.
<3> Specifies the parameters that define how the images are verified.
<4> Defines a root of trust for the policy.
<5> Specifies the policy types that define the root of trust, either a public key or a link:https://docs.sigstore.dev/certificate_authority/overview/[Fulcio certificate]. Here, a Fulcio certificate with required Rekor verification.
<6> For a Fulcio certificate policy, the following parameters are required:
* `fulcioCAData`: Specifies a base64-encoded Fulcio certificate in the PEM format. The maximum length is 8192 characters.
* `fulcioSubject`: Specifies the OIDC issuer and the email of the Fulcio authentication configuration.
<7> Specifies a base64-encoded Rekor public key in the PEM format. This parameter is required when the `policyType` is `FulcioCAWithRekor`. The maximum length is 8192 characters.
<8> Optional: Specifies one of the following processes to verify the identity in the signature and the actual image identity.
* `MatchRepoDigestOrExact`.
* `MatchRepository`.
* `ExactRepository`. The `exactRepository` parameter must be specified.
* `RemapIdentity`. The `prefix` and `signedPrefix` parameters must be specified.
<9> For the `remapIdentity` match policy, specifies the prefix that should be matched against the scoped image prefix. If the two match, the scoped image prefix is replaced with the value of `signedPrefix`. The maximum length is 512 characters.
<10> For the `remapIdentity` match policy, specifies the image prefix to be remapped, if needed. The maximum length is 512 characters.
--

. Create the cluster image policy object:
+
[source,terminal]
----
$ oc create -f <file_name>.yaml
----
+
The Machine Config Operator (MCO) updates the machine config pools (MCP) in your cluster.

.Verification

* After the nodes in your cluster are updated, you can verify that the cluster image policy has been configured:

.. Start a debug pod for the node by running the following command:
+
[source,terminal]
----
$ oc debug node/<node_name>
----

.. Set `/host` as the root directory within the debug shell by running the following command:
+
[source,terminal]
----
sh-5.1# chroot /host/
----

.. Examine the `policy.json` file  by running the following command:
+
[source,terminal]
----
sh-5.1# cat /etc/containers/policy.json
----
+
.Example output for the cluster image policy object with a public key showing the new cluster image policy
[source,json]
----
# ...
  "transports": {
# ...
    "docker": {
      "example.com": [
        {
          "type": "sigstoreSigned",
          "keyData": "a2V5RGF0YQ==",
          "rekorPublicKeyData": "cmVrb3JLZXlEYXRh",
          "signedIdentity": {
            "type": "matchRepoDigestOrExact"
          }
        }
      ],
# ...
----
+
.Example output for the cluster image policy object with a Fulcio certificate showing the new cluster image policy
[source,json]
----
# ...
  "transports": {
# ...
    "docker": {
      "example.com": [
        {
          "type": "sigstoreSigned",
          "fulcio": {
            "caData": "a2V5RGF0YQ==",
            "oidcIssuer": "https://expected.OIDC.issuer/",
            "subjectEmail": "expected-signing-user@example.com"
          },
          "rekorPublicKeyData": "cmVrb3JLZXlEYXRh",
          "signedIdentity": {
            "type": "remapIdentity",
            "prefix": "example.com",
            "signedPrefix": "mirror-example.com"
          }
        }
      ],
# ...
----

.. Examine the `sigstore-registries.yaml` file  by running the following command:
+
[source,terminal]
----
sh-5.1# cat /etc/containers/registries.d/sigstore-registries.yaml
----
+
.Example output showing that the scoped registry was added
[source,yaml]
----
docker:
  example.com:
    use-sigstore-attachments: true <1>
  quay.io/openshift-release-dev/ocp-release:
    use-sigstore-attachments: true
----
<1> When `true`, specifies that sigstore signatures are going to be read along with the image.
// https://github.com/openshift/api/blob/master/config/v1alpha1/zz_generated.crd-manifests/0000_10_config-operator_01_clusterimagepolicies-TechPreviewNoUpgrade.crd.yaml
