// Module included in the following assemblies:
//
// * nodes/nodes-scheduler-descheduler.adoc

[id="nodes-scheduler-descheduler-create-role-{context}"]
= Creating a cluster role for descheduling in {product-title}

In order for the Descheduler Operator to remove pods from nodes and replace them on other nodes, you first need a specific cluster role
with the necessary permissions for the descheduler to work in a pod.

.Procedure

To configure the necessary cluster role and associated service account:

. Create a cluster role with the following rules:
+
[source,yaml]
----
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: descheduler-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"] <1>
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"] <2>
- apiGroups: [""]
  resources: ["pods/eviction"] <3>
  verbs: ["create"]
----
<1> Configures the role to allow viewing nodes.
<2> Configures the role to allow viewing and deleting pods.
<3> Allows a node to evict pods bound to itself.

. Create the service account that runs the job:
+
----
$ oc create sa <file-name>.yaml -n openshift-operators
----
+
For example:
+
----
$ oc create sa descheduler-sa.yaml -n openshift-operators
----

. Bind the cluster role to the schedluer service account:
+
----
$ oc create clusterrolebinding descheduler-cluster-role-binding \
    --clusterrole=descheduler-cluster-role \
    --serviceaccount=openshift-operators:descheduler-sa
----
