// Module included in the following assemblies:
//
// * nodes/cma/nodes-cma-autoscaling-custom-http-add-on.adoc

:_mod-docs-content-type: PROCEDURE
[id="nodes-cma-autoscaling-custom-http-add-on-configure-app-scaling_{context}"]
= Configure HTTP-based autoscaling for your application

[role="_abstract"]
After installing the HTTP Add-on, you configure per-application autoscaling by creating an `InterceptorRoute` custom resource to define traffic routing and scaling metrics and a `ScaledObject` custom resource to link your scaling configuration to your application deployment.

.Prerequisites

* The HTTP Add-on is installed in your cluster. For information, see "Install the KEDA HTTP Add-on extension".

* You have access to a terminal with the `oc` command-line tool installed and authenticated to your {product-title} cluster.

* You have permissions to create deployment, service, route, interceptor route, and scaledbject` custom resources in the `default` namespace.

.Procedure

. Create a namespace for your application by running the following command:
+
[source,terminal]
----
$ oc new-project <namespace>
----
+
Replace `<namespace>` with the name of your namespace.

. Create your HTTP application deployment.

.. Create a file with the following content:
+
[source,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-http-app
  namespace: http-add-on-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-http-app
  template:
    metadata:
      labels:
        app: sample-http-app
    spec:
      containers:
      - name: app
        image: openshift/hello-openshift
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
----

.. Create the deployment:
+
[source,terminal]
----
$ oc create -f <file_name>.yaml
----

.. Verify the deployment is operating by running the following command:
+
[source,terminal]
----
$ oc get pods -n <namespace>
----
+
Replace `<namespace>` with the name of your namespace where you created the deployment.
+
.Example output
[source,terminal]
----
NAME                               READY   STATUS    RESTARTS   AGE
sample-http-app-5fc8679bf4-prb46   1/1     Running   0          6m57s
----

. Create a service to expose the application:

.. Create a file with the following content:
+
[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: sample-http-app
  namespace: http-add-on-example
spec:
  selector:
    app: sample-http-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
----

.. Create the service:
+
[source,terminal]
----
$ oc create -f <file_name>.yaml
----

.. Verify the service was created by running the following command:
+
[source,terminal]
----
$ oc get service -n <namespace>
----
+
Replace `<namespace>` with the name of the namespace where you created the service.
+
.Expected output
[source,terminal]
----
NAME              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
sample-http-app   ClusterIP   172.30.154.127   <none>        8080/TCP   6m19s
----

. Create an edge route to expose the application externally.

.. Create the route in the `openshift-keda` namespace by running the following command:
+
[source,yaml]
----
oc create route edge <name> \
  --service=keda-add-ons-http-interceptor-proxy \
  --port=proxy \
  -n openshift-keda
----
+
where:
+
--
* `<name>` is a name for your route. Replace `<name>` with a name of your route.
* `service=keda-add-ons-http-interceptor-proxy` specifies the service you want to expose. This must be `keda-add-ons-http-interceptor-proxy`.
* `port=proxy` specifies the port on the `keda-add-ons-http-interceptor-proxy` service that the route uses. Specifying `proxy` sets the port to `8080`. With an edge route, the port must be `8080`.
* `openshift-keda` specifies the namespace where your route will be created. This must be `openshift-keda`.
--
+
Leave the `spec.host` parameter unset to allow the cluster to assign the host name on your cluster's `*.apps` domain.

.. Get the route host name to use in the following step by running the following command:
+
[source,terminal]
----
$ oc get route <route_name> -n openshift-keda -o jsonpath={.spec.host}
----
+
Replace `<route_name>` with the name of the route.
+
.Example output
[source,terminal]
----
sample-http-app-openshift-keda.apps.ci-ln-wszd8jt-72292.origin-ci-int-gce.dev.rhcloud.com
----

. Create an `InterceptorRoute` custom resource to intercept traffic:

.. Create a file with the following content:
+
[source,yaml]
----
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: sample-app-interceptor
  namespace: http-add-on-example
spec:
  rules:
    - hosts:
        - sample-http-app-openshift-keda.apps.ci-ln-74rphxb-72292.gcp-3.ci.openshift.org
  target:
    service: sample-http-app
    port: 8080
  scalingMetric:
    requestRate:
      targetValue: 5
      window: 10s
      granularity: 1s
----
+
Modify the following fields for your application:

* `metadata.name`: Specifies a descriptive name for this interceptor route.
* `metadata.namespace`: Specifies the namespace where your application is deployed.
* `spec.rules.hosts`: Specifies the host name where traffic arrives for your application from your route or ingress. Use the host name from the previous step.
* `spec.target.service`: Specifies the name of your application's service.
* `spec.target.port`: Specifies the port exposed by the service. For example, if the service exposes port `80` and forwards to `targetPort: 8080`, the interceptor route must use port `80`.
* `spec.scalingMetric`. Specifies the default metric thresholds, either requests per second (`requestRate`), concurrent request count (`concurrency`), or both:
** `requestRate`. The `requestRate` metric measures incoming requests averaged over a measurement window. The baseline `requestRate` value is used as the scaling reference. You can set the following paramters:
+
--
* `targetValue` specifies how much traffic each replica should handle. The horizontal pod autoscaler (HPA) adds replicas when the average load per pod rises above that number.
* `window` is the sliding time window over which the average request rate is calculated. The default is 1 minute. 
* `granularity` is the bucket size within that window. The default is 1 second. Smaller granularity makes scaling more responsive but also more sensitive to burst traffic.
--

** `concurrency`. The `concurrency` metric measures in-flight HTTP requests. The baseline `concurrency` value is used as the scaling reference. For `concurrency` you can set `targetValue`. The `window` and `granularity` parameters are not available.

.. Create the interceptor route by running the following command:
+
[source,terminal]
----
$ oc create -f <file_name>.yaml
----

.. Verify that the interceptor route was created by running the following command:
+
[source,terminal]
----
$ oc get interceptorroute <route_name> -n <namespace_name>
----
+
Replace `<route_name>` with the name of the interceptor route and `<namespace_name>` with the namespace where you created the interceptor route.
+
.Expected output
[source,terminal]
----
NAME                     TARGETSERVICE     READY   AGE
sample-app-interceptor   sample-http-app   True    11s
----
+
Wait until the route interceptor is the `READY:True` state.

. Create a `ScaledObject` to configure scaling:
+
--
.. Create a file with the following content:
+
[source,yaml]
----
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sample-app-scaler
  namespace: http-add-on-example
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-http-app
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 30
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.openshift-keda.svc:9090
        interceptorRoute: sample-app-interceptor
----
+
Modify the following fields for your application:

* `metadata.name`: Specify a descriptive name for this scaled object.
* `metadata.namespace`: Specify the namespace where your application is deployed. Must be the same namespace as the interceptor route.
* `spec.scaleTargetRef.kind`: Specify the API version the object you used to create your application pod. The default is `apps/v1`.
* `spec.scaleTargetRef.kind`: Specify the kind of the object as `Deployment`, `StatefulSet` or `CustomResource`.
* `spec.scaleTargetRef.name`: Specify the exact name of the object.
* `spec.minReplicaCount`: Specify the minimum replicas your application should scale down to.
* `spec.maxReplicaCount`: Specify the maximum replicas your application should scale up to.
* `spec.cooldownPeriod`: Specify the time in seconds to wait before scaling to zero after traffic drops.
* `spec.triggers.type`: Specify the underlying core metric scaler engine that watches your workload. Must be `external-push`.
* `spec.triggers.metadata.scalerAddress`: Specify the endpoint for the HTTP Add-on scaler service. Must be `keda-add-ons-http-external-scaler.openshift-keda.svc:9090`.
* `spec.triggers.metadata.interceptorRoute`: Specify the name of your interceptor route.

.. Create the scaled object by running the following command:
+
[source,terminal]
----
$ oc apply -f <file_name>.yaml
----

.. Verify the scaled object is created by running the following command:
+
[source,terminal]
----
$ oc get scaledobject <object_name> -n <namespace_name>
----
+
Replace `<object_name>` with the name of the interceptor route and `<namespace_name>` with the namespace where you created the interceptor route.
+
.Example output
[source,terminal]
----
NAME                SCALETARGETKIND      SCALETARGETNAME   MIN   MAX   READY   ACTIVE    FALLBACK   PAUSED   TRIGGERS        AUTHENTICATIONS   AGE
sample-app-scaler   apps/v1.Deployment   sample-http-app   0     10    True    Unknown   False      False    external-push                     12s
----
--
+
For more information on scaled objects, see "Add a custom metrics autoscaler to a workload".

.Verification

. Verify the autoscaling configuration is active:

.. Verify that the deployment currently has zero replicas by running the following command:
+
[source,terminal]
----
$ oc get deployment <deployment_name> -n <namespace_name>
----
+
Replace `<deployment_name>` with the name of the deployment and `<namespace_name>` with the namespace where you created the deployment.
+
.Expected output
[source,terminal]
----
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
sample-http-app    0/0     0            0           5m
----
+
There are no replicas because there is no traffic going to the application.

.. Check that an HPA was created by the scaled object by running the following command:
+
[source,terminal]
----
$ oc get hpa -n <namespace_name>
----
+
Replace `<namespace_name>` with the namespace where you created the scaled object.
+
.Example output
[source,terminal]
----
NAME                         REFERENCE                    TARGETS             MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-sample-app-scaler   Deployment/sample-http-app   <unknown>/5 (avg)   1         10        0          117s
----
+
The target rate is `unknown` because the deployment has no replicas.

. Generate traffic to observe autoscaling behavior, for example by running the following script:

.. Run the following example script to generate HTTP traffic to your cluster. This creates concurrent requests that can be monitored in your metrics dashboard:
+
[source,terminal]
----
for i in $(seq 1 30); do
  for j in $(seq 1 20); do
    curl -sk "https://<host_name>/"/dev/null &
  done
  wait
done
----
+
The curl command in this example sends one HTTP request to the route and prints the response, generating 600 total HTTP requests, 30 batches with 20 concurrent requests per batch, to populate performance metrics. 

.. Watch the deployment scale up in response to the traffic by running the following command:
+
[source,terminal]
----
$ oc get deployment <deployment_name> -n <namespace_name>
----
+
Replace `<deployment_name>` with the name of the deployment and `<namespace_name>` with the namespace where you created the deployment.
+
.Example output
[source,terminal]
----
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
sample-http-app   6/6     6            6           26m
----
+
You should see the `READY` and `AVAILABLE` fields increase. In this example, the deployment scaled up to 6 replicas.

.. Check the HPA status to see the current metrics and scaling activity by running the following command:
+
[source,terminal]
----
$ oc get hpa -n <namespace>
----
+
Replace `<namespace>` with the namespace where you created the scaled object.
+
[source,terminal]
----
NAME                         REFERENCE                    TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-sample-app-scaler   Deployment/sample-http-app   6500m/5 (avg)   1         10        6          15m
----
+
In this example, the HPA target rate is `6500m/5`, which represents 6.5 requests per second per pod against your target of 5 in the interceptor route, so the deployment grew to 6 replicas.

.. After traffic stops, wait for the 30-second cooldown, check the scaled object status by running the following command:
+
[source,terminal]
----
$ oc get deployment <deployment_name> -n <namespace_name>
----
+
Replace `<deployment_name>` with the name of the deployment and `<namespace_name>` with the namespace where you created the deployment.
+
[source,terminal]
----
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
sample-http-app   0/0     0            0           27m
----
+
The HPA scales the replicas down to the `minReplicaCount` value in the scaled object. The Custom Metrics Autoscaler then scales the replicas down to 0.
