// Module included in the following assemblies:
//
// * nodes/nodes-nodes-working.adoc

[id="nodes-nodes-working-master-schedulable_{context}"]
= Configuring control plane nodes as schedulable

You can configure control plane nodes (also known as the master nodes) to be
schedulable, meaning that new pods are allowed for placement on the master
nodes. By default, control plane nodes are not schedulable.

You can set the masters to be schedulable, but must retain the worker nodes.

[NOTE]
====
You can deploy {product-title} with no worker nodes on a bare metal cluster.
In this case, the control plane nodes are marked schedulable by default.
====

You can allow or disallow control plane nodes to be schedulable by configuring the `mastersSchedulable` field.

[IMPORTANT]
====
When you configure control plane nodes from the default unschedulable to schedulable, additional subscriptions are required. This is because control plane nodes then become worker nodes.
====

.Procedure

. Edit the `schedulers.config.openshift.io` resource.
+
[source,terminal]
----
$ oc edit schedulers.config.openshift.io cluster
----

. Configure the `mastersSchedulable` field.
+
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  creationTimestamp: "2019-09-10T03:04:05Z"
  generation: 1
  name: cluster
  resourceVersion: "433"
  selfLink: /apis/config.openshift.io/v1/schedulers/cluster
  uid: a636d30a-d377-11e9-88d4-0a60097bee62
spec:
  mastersSchedulable: false <1>
  policy:
    name: ""
status: {}
----
<1> Set to `true` to allow control plane nodes to be schedulable, or `false` to
disallow control plane nodes to be schedulable.

. Save the file to apply the changes.
