// Module included in the following assemblies:
//
//* nodes/pods/configmaps.adoc
//* applications/config-maps.adoc

[id="nodes-pods-configmaps-use-case-setting-command-line-arguments_{context}"]
= Setting command-line arguments for container commands with config maps

A config map can also be used to set the value of the commands or arguments in a container. This is accomplished by using the Kubernetes substitution syntax `$(VAR_NAME)`. Consider the following config map:

[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  special.how: very
  special.type: charm
----

.Procedure

* To inject values into a command in a container, you must consume the keys you want to use as environment variables, as in the consuming ConfigMaps in environment variables use case. Then you can refer to them in a container's command using the `$(VAR_NAME)` syntax.
+
.Sample `Pod` specification configured to inject specific environment variables
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "echo $(SPECIAL_LEVEL_KEY) $(SPECIAL_TYPE_KEY)" ] <1>
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.type
  restartPolicy: Never
----
<1> Inject the values into a command in a container using the keys you want to use as environment variables.
+
When this Pod is run, the output from the echo command run in the test-container container is as follows:
+
----
very charm
----
