// Module included in the following assemblies:
//
// * nodes/pods/nodes-pods-user-namespaces.adoc

:_mod-docs-content-type: PROCEDURE
[id="nodes-pods-user-namespaces-configuring_{context}"]
= Configuring Linux user namespace support

You can configure your pods to run in Linux user namespaces by setting the `hostUsers` parameter to `false` in the workload spec, as shown in the following procedure. 

Running workloads in user namespaces allows you to specify `RunAsAny` for Security Context Constraint (SCC) fields, such as `fsGroup`, `runAsGroup`, `runAsUser`, and `supplementalGroups`. Setting these fields to `RunAsAny` can have specific benefits described throughout the {product-title} documentation. Within a user namespace, `RunAsAny` is generally considered to be a safe practice. For extra security, you can create a new SCC specifically for workloads in user namespaces by setting the `userNamespaceLevel: RequirePodLevel` field in the SCC, which requires that the workloads run in user namespaces. To require a specific SCC, set the `openshift.io/required-scc` annotation in any workload resource that can set a pod manifest template, such as a deployment or daemon set.

Also, configuring workloads as `procMount: unmasked` is generally considered as safe within a user namespace. Setting `procMount` to `unmasked` has benefits that are beyond the scope of this documentation. 

To ensure that the namespace functionality exists on all nodes that you want to run in a user namespace, you can configure the minimum version of kubelet that is required for the nodes in your cluster. If the kubelet version in your cluster is lower than this version, new nodes are not scheduled and existing nodes are marked as degraded. For existing nodes with a lower version, the kubelet can only read the node object by using `oc get` or `oc update` commands, and the actions that the node can perform, by using a `SelfSubjectAccessReview`. The node is not allowed to gain access to any other API objects.     

.Prerequisites

* Enable the crun container runtime on the worker nodes. crun is currently the only released Open Container Initiative (OCI) runtime with support for user namespaces.
+
[source,yaml]
----
apiVersion: machineconfiguration.openshift.io/v1
kind: ContainerRuntimeConfig
metadata:
 name: enable-crun-worker
spec:
 machineConfigPoolSelector:
   matchLabels:
     pools.operator.machineconfiguration.openshift.io/worker: "" <1>
 containerRuntimeConfig:
   defaultRuntime: crun <2>
----
<1> Specifies the machine config pool label. 
<2> Specifies the container runtime to deploy.

* Optional: Create or edit an existing Security Context Constraint (SCC) to configure the `userNamespaceLevel` setting. This setting is optional, because the default value allows, but does not require, the use of user namespaces.
+
.Example `SecurityContextConstraints` object definition
[source,yaml]
----
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-admin
userNamespaceLevel: RequirePodLevel <1>
allowPrivilegedContainer: true
# ...
seLinuxContext: <2>
  type: RunAsAny
# ...
runAsUser:
  type: RunAsAny <3>
users: []
# ...
----
<1> Specify one of the following values:
** If set to the `AllowHostLevel` value, you can set `hostUser` to `true` or `false`. `AllowHostLevel` is the default. This setting allows you to use the SCC with pods that run in the host or an individual user namespace.  
** If set to the `RequirePodLevel` value, you must set `hostUser` to `false` in the workload spec. This setting requires you to use this SCC with pods that run in an individual user namespace. This setting is more secure. 
<2> This setting is required.
<3> Optional: It is considered safe to set this parameter to `RunAsAny`, as needed, if the associated workload runs in a user namespace.

* Optional: Configure the minimum kubelet version for your cluster.
+
.Example `SecurityContextConstraints` object definition
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: Node
metadata:
  name: cluster
spec: 
  minimumKubeletVersion: 1.30.0 <1>
# ...
----
<1> Specifies the minimum kubelet version to allow on the nodes in the cluster. For running workloads in user namespaces, it is recommended that you use a minimum version of `1.30.0`, which is the default, or higher.   

.Procedure

. Edit the default user ID (UID) and group ID (GID) range of the {product-title} namespace where your pod is deployed by running the following command:
+
[source,terminal]
----
$ oc edit ns/<namespace_name>
----
+
.Example namespace
[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: system:admin
    openshift.io/sa.scc.mcs: s0:c27,c24
    openshift.io/sa.scc.supplemental-groups: 1000/10000 <1>
    openshift.io/sa.scc.uid-range: 1000/10000 <2>
# ...
name: userns
# ...
----
<1> Edit the default GID to match the value you specify in the pod spec. The range for a Linux user namespace must be `65535` or lower. The default is `1000000000/10000`.
<2> Edit the default UID to match the value you specify in the pod spec. The range for a Linux user namespace must be `65535` or lower. The default is `1000000000/10000`.
+
[NOTE]
====
The range 1000/10000 means 10,000 values starting with ID 1000, so it specifies the range of IDs from 1000 to 10,999.
====

. Enable the use of Linux user namespaces by creating a workload configured to run with an appropriate SCC and with the `hostUsers` parameter set to `false`.

.. Create a YAML file similar to the following:
+
.Example pod specification
[source,yaml]
----
apiVersion: v1
kind: Deployment
metadata:
  namespace: userns
  name: userns-pod
# ...
spec:
#...
  template:
    metadata:
      labels:
        app: name
      annotations:
        openshift.io/required-scc: "scc-admin" <1>     
    spec:
      containers:
      - name: userns-container
        image: registry.access.redhat.com/ubi9
        command: ["sleep", "1000"]
        securityContext:
          capabilities:
            drop: ["ALL"]
          allowPrivilegeEscalation: false
          runAsNonRoot: true <2>
          procMount: unmasked <3>
          runAsUser: 1000 <4>
          runAsGroup: 1000 <5>
          hostUsers: false <6>
# ...
----
<1> Specifies the SCC to use with this workload.
<2> Specifies that the container will run with a user that has any UID other than 0.
<3> Specifies the type of proc mount to use for the containers. The `unmasked` value ensures that a container's `/proc` is mounted as read/write by the container process. This bypasses the default masking behavior of the container runtime, and should only be used with an SCC that sets `hostUsers` to `false`. The default is `Default`.
<4> Specifies the UID of the container. This must match the default value you set in the namespace object. 
<5> Specifies the GID of the containers. This must match the default value you set in the namespace object.
<6> Requests that the pod is to be run in a user namespace. If `true`, the pod runs in the host user namespace. If `false`, the pod runs in a new user namespace that is created for the pod. The default is `true`.

.. Create the object by running the following command:
+
----
$ oc create -f <file_name>.yaml
----

.Verification

. Check the user and group IDs being used by the container in the pod you created. The pod is inside the Linux user namespace.

.. Start a shell session with the container in your pod:
+
[source,terminal]
----
$ oc rsh -c <container_name> pod/<pod_name>
----
+
.Example command
[source,terminal]
----
$ oc rsh -c userns-container_name pod/userns-pod
----

.. Display the user and group IDs being used inside the container:
+
[source,terminal]
----
sh-5.1$ id
----
+
.Example output
[source,terminal]
----
uid=1000(1000) gid=1000(1000) groups=1000(1000)
----
<1> The UID and group for the container is `1000`, the same as you set in the pod spec.

.. Display the user ID being used in the container user namespace:
+
[source,terminal]
----
sh-5.1$ lsns -t user
----
+
.Example output
[source,terminal]
----
        NS TYPE  NPROCS PID USER COMMAND
4026532447 user       3   1 1000 /usr/bin/coreutils --coreutils-prog-shebang=sleep /usr/bin/sleep 1000 <1>
----
<1> The UID for the process is `1000`, the same as you set in the pod spec.

. Check the UID being used by the node. The node is outside of the Linux user namespace. This user ID should be different from the UID being used in the container.

.. Start a debug session for that node:
+
[source,terminal]
----
$ oc debug node/ci-ln-z5vppzb-72292-8zp2b-worker-c-q8sh9
----
+
.Example command
[source,terminal]
----
$ oc debug node/ci-ln-z5vppzb-72292-8zp2b-worker-c-q8sh9
----

.. Set `/host` as the root directory within the debug shell:
+
[source,terminal]
----
sh-5.1# chroot /host
----

.. Display the UID being used by the node:
+
[source,terminal]
----
sh-5.1#  lsns -t user
----
+
.Example command
[source,terminal]
----
        NS TYPE  NPROCS   PID USER       COMMAND
4026531837 user     233     1 root       /usr/lib/systemd/systemd --switched-root --system --deserialize 28
4026532447 user       1  4767 2908816384 /usr/bin/coreutils --coreutils-prog-shebang=sleep /usr/bin/sleep 1000 <1>
----
<1> The UID is `2908816384`, which is different from what you set in the pod spec.
