// Module included in the following assemblies:
//
// * nodes/nodes-scheduler-default.adoc


[id="nodes-scheduler-default-creating_{context}"]
= Creating a scheduler policy file

//Made changes to this file to match https://github.com/openshift/openshift-docs/pull/13626/files#diff-ba6ab177a3e2867eaefe07f48bd6e158

You can change the default scheduling behavior by creating a JSON file with the desired predicates and priorities. You then generate a config map from the JSON file and point the `cluster` Scheduler object to use the config map.

.Procedure

To configure the scheduler policy:

. Create a JSON file named `policy.cfg` with the desired predicates and priorities.
+
.Sample scheduler JSON file
[source,json]
----
{
"kind" : "Policy",
"apiVersion" : "v1",
"predicates" : [ <1>
        {"name" : "MaxGCEPDVolumeCount"},
        {"name" : "GeneralPredicates"},
        {"name" : "MaxAzureDiskVolumeCount"},
        {"name" : "MaxCSIVolumeCountPred"},
        {"name" : "CheckVolumeBinding"},
        {"name" : "MaxEBSVolumeCount"},
        {"name" : "MatchInterPodAffinity"},
        {"name" : "CheckNodeUnschedulable"},
        {"name" : "NoDiskConflict"},
        {"name" : "NoVolumeZoneConflict"},
        {"name" : "PodToleratesNodeTaints"}
        ],
"priorities" : [ <2>
        {"name" : "LeastRequestedPriority", "weight" : 1},
        {"name" : "BalancedResourceAllocation", "weight" : 1},
        {"name" : "ServiceSpreadingPriority", "weight" : 1},
        {"name" : "NodePreferAvoidPodsPriority", "weight" : 1},
        {"name" : "NodeAffinityPriority", "weight" : 1},
        {"name" : "TaintTolerationPriority", "weight" : 1},
        {"name" : "ImageLocalityPriority", "weight" : 1},
        {"name" : "SelectorSpreadPriority", "weight" : 1},
        {"name" : "InterPodAffinityPriority", "weight" : 1},
        {"name" : "EqualPriority", "weight" : 1}
        ]
}
----
<1> Add the predicates as needed.
<2> Add the priorities as needed.

. Create a config map based on the scheduler JSON file:
+
[source,terminal]
----
$ oc create configmap -n openshift-config --from-file=policy.cfg <configmap-name> <1>
----
<1> Enter a name for the config map.
+
For example:
+
[source,terminal]
----
$ oc create configmap -n openshift-config --from-file=policy.cfg scheduler-policy
----
+
.Example output
[source,terminal]
----
configmap/scheduler-policy created
----
+
[TIP]
====
You can alternatively apply the following YAML to create the config map:

[%collapsible]
=====
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: scheduler-policy
  namespace: openshift-config
data: <1>
  policy.cfg: |
    {
    "kind": "Policy",
    "apiVersion": "v1",
    "predicates": [
        {
            "name": "RequireRegion",
            "argument": {
                "labelPreference":
                    {"label": "region"},
                    {"presence": true}
            }
         }
      ],
    "priorities": [
        {
            "name":"ZonePreferred",
            "weight" : 1,
            "argument": {
                "labelPreference":
                    {"label": "zone"},
                    {"presence": true}
               }
           }
       ]
    }
----
<1> The `policy.cfg` file in JSON format with predicates and priorities.
=====
====

. Edit the Scheduler Operator custom resource to add the config map:
+
[source,terminal]
----
$ oc patch Scheduler cluster --type='merge' -p '{"spec":{"policy":{"name":"<configmap-name>"}}}' --type=merge <1>
----
+
<1> Specify the name of the config map.
+
For example:
+
[source,terminal]
----
$ oc patch Scheduler cluster --type='merge' -p '{"spec":{"policy":{"name":"scheduler-policy"}}}' --type=merge
----
+
[TIP]
====
You can alternatively apply the following YAML to add the config map:

[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  name: cluster
spec:
  mastersSchedulable: false
  policy:
    name: scheduler-policy <1>
----
<1> Add the name of the scheduler policy config map.
====
+
After making the change to the `Scheduler` config resource, wait for the `openshift-kube-apiserver` pods to redeploy. This can take several minutes. Until the pods redeploy, new scheduler does not take effect.

. Verify the scheduler policy is configured by viewing the log of a scheduler pod in the `openshift-kube-scheduler` namespace. The following command checks for the predicates and priorities that are being registered by the scheduler:
+
[source,terminal]
----
$ oc logs <scheduler-pod> | grep predicates
----
+
For example:
+
[source,terminal]
----
$ oc logs openshift-kube-scheduler-ip-10-0-141-29.ec2.internal | grep predicates
----
+
.Example output
[source,terminal]
----
Creating scheduler with fit predicates 'map[MaxGCEPDVolumeCount:{} MaxAzureDiskVolumeCount:{} CheckNodeUnschedulable:{} NoDiskConflict:{} NoVolumeZoneConflict:{} GeneralPredicates:{} MaxCSIVolumeCountPred:{} CheckVolumeBinding:{} MaxEBSVolumeCount:{} MatchInterPodAffinity:{} PodToleratesNodeTaints:{}]' and priority functions 'map[InterPodAffinityPriority:{} LeastRequestedPriority:{} ServiceSpreadingPriority:{} ImageLocalityPriority:{} SelectorSpreadPriority:{} EqualPriority:{} BalancedResourceAllocation:{} NodePreferAvoidPodsPriority:{} NodeAffinityPriority:{} TaintTolerationPriority:{}]'
----
