// Module included in the following assemblies:
// * networking/aws_load_balancer_operator/understanding-aws-load-balancer-operator.adoc

:_mod-docs-content-type: PROCEDURE
[id="nw-aws-load-balancer-operator_{context}"]
= Deploying the AWS Load Balancer Operator

[role="_abstract"]
After you deploy the The AWS Load Balancer Operator, the Operator automatically tags public subnets if the `kubernetes.io/role/elb` tag is missing. The Operator then identifies specific network resources in the underlying AWS cloud to ensure successful cluster integration.

The AWS Load Balancer Operator detects the following information from the underlying AWS cloud:

* The ID of the virtual private cloud (VPC) on which the cluster hosting the Operator is deployed.

* Public and private subnets of the discovered VPC.

The AWS Load Balancer Operator supports the Kubernetes service resource of type `LoadBalancer` by using Network Load Balancer (NLB) with the `instance` target type only.

.Procedure

. To deploy the AWS Load Balancer Operator on-demand from OperatorHub, create a `Subscription` object by running the following command:
+
[source,terminal]
----
$ oc -n aws-load-balancer-operator get sub aws-load-balancer-operator --template='{{.status.installplan.name}}{{"\n"}}'
----

. Check if the status of an install plan is `Complete` by running the following command:
+
[source,terminal]
----
$ oc -n aws-load-balancer-operator get ip <install_plan_name> --template='{{.status.phase}}{{"\n"}}'
----

. View the status of the `aws-load-balancer-operator-controller-manager` deployment by running the following command:
+
[source,terminal]
----
$ oc get -n aws-load-balancer-operator deployment/aws-load-balancer-operator-controller-manager
----
+
.Example output
[source,terminal]
----
NAME                                           READY     UP-TO-DATE   AVAILABLE   AGE
aws-load-balancer-operator-controller-manager  1/1       1            1           23h
----
