// Module included in the following assemblies:
//
// * networking/dns-operator.adoc

:_mod-docs-content-type: PROCEDURE
[id="nw-controlling-dns-pod-placement_{context}"]
= Controlling DNS pod placement

The DNS Operator has two daemon sets: one for CoreDNS called `dns-default` and one for managing the `/etc/hosts` file `called node-resolver`.

You might find a need to control which nodes have CoreDNS pods assigned and running, although this is not a common operation. For example, if the cluster administrator has configured security policies that can prohibit communication between pairs of nodes, that would necessitate restricting the set of nodes on which the daemonset for CoreDNS runs. If DNS pods are running on some nodes in the cluster and the nodes where DNS pods are not running have network connectivity to nodes where DNS pods are running, DNS service will be available to all pods.

The `node-resolver` daemon set must run on every node host because it adds an entry for the cluster image registry to support pulling images. The `node-resolver` pods have only one job: to look up the `image-registry.openshift-image-registry.svc` service's cluster IP address and add it to `/etc/hosts` on the node host so that the container runtime can resolve the service name.

As a cluster administrator, you can use a custom node selector to configure the daemon set for CoreDNS to run or not run on certain nodes.

.Prerequisites

* You installed the `oc` CLI.
* You are logged in to the cluster as a user with `cluster-admin` privileges.
* Your DNS Operator `managementState` is set to `Managed`.

.Procedure

* To allow the daemon set for CoreDNS to run on certain nodes, configure a taint and toleration:
+
. Modify the DNS Operator object named `default`:
+
[source,terminal]
----
$ oc edit dns.operator/default
----
+
. Specify a taint key and a toleration for the taint:
+
[source,yaml]
----
 spec:
   nodePlacement:
     tolerations:
     - effect: NoExecute
       key: "dns-only"
       operators: Equal
       value: abc
       tolerationSeconds: 3600 <1>
----
<1> If the taint is `dns-only`, it can be tolerated indefinitely. You can omit `tolerationSeconds`.
