// Module included in the following assemblies:
//
// * networking/networking_operators/configuring-dpu-operator.adoc

:_mod-docs-content-type: PROCEDURE
[id="nw-dpu-configuring-operator_{context}"]
= Configuring the DPU Operator 

To configure the DPU Operator follow these steps:

.Procedure

. Create a `DpuOperatorConfig` custom resource (CR) on both the host cluster and on each of the DPU clusters. The DPU Operator in each cluster is activated after this CR is created.

. Create a file named `dpu-operator-host-config.yaml` by using the following YAML:
+
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: DpuOperatorConfig
metadata:
 name: dpu-operator-config <1>
spec:
 mode: host <2>
----
+
<1> The name of the custom resource must be `dpu-operator-config`.
<2> Set the value to `host` on the host cluster. On each DPU cluster, which runs a single MicroShift cluster per DPU, set the value to `dpu`.

. Create the resource by running the following command:
+
[source,terminal]
----
$ oc apply -f dpu-operator-host-config.yaml
----

. You must label all nodes that either have an attached DPU or are functioning as a DPU. On the host cluster, this means labeling all compute nodes assuming each node has an attached DPU with `dpu=true`. On the DPU, where each MicroShift cluster consists of a single node, label that single node in each cluster with `dpu=true`. You can apply this label by running the following command:
+
[source,terminal]
----
$ oc label node <node_name> dpu=true
----
+
where:
+
`node_name`:: Refers to the name of your node, such as `worker-1`.
