// Module included in the following assemblies:
//
// * installing/installing_aws/installing-aws-customizations.adoc
// * networking/ingress/configuring_ingress_operator.adoc


[id='nw-installation-ingress-config-asset_{context}']
= The ingress configuration asset

The installer generates an asset with an `Ingress` resource in the
`config.openshift.io` API group, `cluster-ingress-02-config.yml`.

.YAML Definition of the `Ingress` resource
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
spec:
  domain: apps.openshiftdemos.com
----

The installer stores this asset in the `cluster-ingress-02-config.yml` file in
the `manifests/` directory. This `Ingress` resource defines the cluster-wide
configuration for ingress. This ingress configuration is used as follows:

* The ingress operator uses the domain from the cluster ingress configuration as
the domain for the default ingress controller.

* The OpenShift API server operator uses the domain from the cluster ingress
configuration as the domain used when generating a default host for a `Route`
resource that does not specify an explicit host.
