// Module included in the following assemblies:
//
// * ingress/configure-ingress-operator.adoc
// * security/configuring-tls-profile.adoc

ifeval::["{context}" == "configuring-ingress"]
:ingress:
endif::[]
ifeval::["{context}" == "tls-profile-control-plane"]
:controlplane:
endif::[]

[id="tls-profiles_{context}"]
ifdef::ingress[]
= Ingress controller TLS profiles
endif::[]
ifdef::controlplane[]
= About TLS security profiles for the control plane
endif::[]

The `tlsSecurityProfile` parameter defines the schema for a TLS security profile. This object is used by Operators to apply TLS security settings to operands.

ifdef::ingress[]
There are four TLS security profile types for the Ingress controller:

* `Old`
* `Intermediate`
* `Modern`
* `Custom`

The `Old`, `Intermediate`, and `Modern` profiles are based on link:https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_configurations[recommended configurations]. The `Custom` profile provides the ability to specify individual TLS security profile parameters.
endif::[]
ifdef::controlplane[]
There are three TLS security profile types for the control plane:

* `Old`
* `Intermediate`
* `Custom`

The `Old` and `Intermediate` profiles are based on link:https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_configurations[recommended configurations]. The `Custom` profile provides the ability to specify individual TLS security profile parameters.
endif::[]


.Sample `Old` profile configuration
[source,yaml]
----
spec:
  tlsSecurityProfile:
    type: Old
----

.Sample `Intermediate` profile configuration
[source,yaml]
----
spec:
  tlsSecurityProfile:
    type: Intermediate
----

// Modern profile is not supported for the control plane
ifdef::ingress[]
.Sample `Modern` profile configuration
[source,yaml]
----
spec:
  tlsSecurityProfile:
    type: Modern
----
endif::[]

The `Custom` profile is a user-defined TLS security profile.

[WARNING]
====
You must be careful using a `Custom` profile, because invalid configurations can cause problems.
====

.Sample `Custom` profile
[source,yaml]
----
spec:
  tlsSecurityProfile:
    type: Custom
    custom:
      ciphers:
        - ECDHE-ECDSA-AES128-GCM-SHA256
        - ECDHE-RSA-AES128-GCM-SHA256
      minTLSVersion: VersionTLS11
----

ifeval::["{context}" == "configuring-ingress"]
:!ingress:
endif::[]
ifeval::["{context}" == "tls-profile-control-plane"]
:!controlplane:
endif::[]
