// Module included in the following assemblies:
//
// * networking/external_dns_operator/nw-installing-external-dns-operator-on-cloud-providers.adoc

:_mod-docs-content-type: PROCEDURE
[id="nw-installing-external-dns-operator_{context}"]
= Installing the External DNS Operator

You can install the External DNS Operator by using the {product-title} OperatorHub.

.Procedure

. Click *Operators* -> *OperatorHub* in the {product-title} web console.
. Click *External DNS Operator*.
  You can use the *Filter by keyword* text box or the filter list to search for External DNS Operator from the list of Operators.
. On the *External DNS Operator* page, click *Install*.
. On the *Install Operator* page, ensure that you selected the following options:
.. Update the channel as *stable-v1*.
.. Installation mode as *A specific name on the cluster*.
.. Installed namespace as `external-dns-operator`. If namespace `external-dns-operator` does not exist, it gets created during the Operator installation.
.. Select *Approval Strategy* as *Automatic* or *Manual*. Approval Strategy is set to *Automatic* by default.
.. Click *Install*.

If you select *Automatic* updates, the Operator Lifecycle Manager (OLM) automatically upgrades the running instance of your Operator without any intervention.

If you select *Manual* updates, the OLM creates an update request. As a cluster administrator, you must then manually approve that update request to have the Operator updated to the new version.


.Verification

Verify that the External DNS Operator shows the *Status* as *Succeeded* on the *Installed Operators* dashboard.
