// Module included in the following assemblies:
//
// * ingress/ingress-operator.adoc
// * upgrade/

[id="nw-ingress-converting-http-header-case_{context}"]
= Converting HTTP header case

HAProxy 2.2 down-cases HTTP header names by default, for example, changing `Host: xyz.com` to `host: xyz.com`. If legacy applications are sensitive to the capitalization of HTTP header names, use the Ingress Controller `spec.httpHeaders.headerNameCaseAdjustments` API field for a solution to accommodate legacy applications until they can be fixed.

[IMPORTANT]
====
Because {product-title} 4.8 includes HAProxy 2.2, make sure to add the necessary configuration by using `spec.httpHeaders.headerNameCaseAdjustments` before upgrading.
====

.Prerequisites

* You have installed the OpenShift CLI (`oc`).
* You have access to the cluster as a user with the `cluster-admin` role.

.Procedure

As a cluster administrator, you can specify a HTTP header to be capitalized by entering the `oc patch command`.

* This example changes the HTTP `host` header to `Host`:
+
[source,terminal]
----
$ oc -n openshift-ingress-operator patch ingresscontrollers/default --type=merge --patch='{"spec":{"httpHeaders":{"headerNameCaseAdjustments":["Host"]}}}'
----
+
** You can annotate the Route of the application:
+
[source,terminal]
----
$ oc annotate routes/my-application haproxy.router.openshift.io/h1-adjust-case=true
----
+
The Ingress Controller then adjusts the `host` request header as specified.

* This example changes the HTTP `cache-control` header to `Cache-Control`:
+
[source,terminal]
----
$ oc -n openshift-ingress-operator patch ingresscontrollers/default --type=json --patch='[{"op":"add","path":"/spec/httpHeaders/headerNameCaseAdjustments/-","value":"Cache-Control"}]'
----
+
The Ingress Controller adjusts the `cache-control` response header as specified.

As cluster administrator you can specify adjustments using the `HeaderNameCaseAdjustments` field by configuring the `IngressController` YAML file.

. The following `IngressController` YAML adjusts the host request header to Host for HTTP/1 requests to appropriately annotated Routes and adjusts the `cache-control` response header to `Cache-Control` and the `content-length` response header to `Content-Length` for all HTTP/1 responses:
+
.Example `IngressController` YAML
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  httpHeaders:
    headerNameCaseAdjustments:
    - Host
    - Cache-Control
    - Content-Length
----
+
. The following Route enables HTTP response header name case adjustments using the `haproxy.router.openshift.io/h1-adjust-case` annotation:
+
.Example `Route` YAML
[source,yaml]
----
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/h1-adjust-case: true
  name: my-application
  namespace: my-application
spec:
  to:
    kind: Service
    name: my-application
----
