// Module included in the following assemblies:
//
// * networking/multiple_networks/configuring-additional-network.adoc

[id="nw-multus-ovn-k8s-object_{context}"]
= Configuration for an OVN-Kubernetes additional network

The following object describes the configuration parameters for the OVN-Kubernetes CNI plugin:

.OVN-Kubernetes network plugin JSON configuration object
[cols=".^2,.^2,.^6",options="header"]
|====
|Field|Type|Description

|`cniVersion`
|`string`
|The CNI specification version. The `0.3.1` value is required.

|`name`
|`string`
|The value for the `name` parameter you provided previously for the CNO configuration.

|`type`
|`string`
|The name of the CNI plugin to configure: `ovn-k8s-cni-overlay`.

|`topology`
|`string`
|

|`subnets`
|`string`
| For example, `10.128.0.0/16/24`.

|`mtu`
|`string`
|The maximum transmission unit (MTU) to the specified value. The default value is automatically set by the kernel.

|`netAttachDefName`
|`string`
| For example, `ns1/l3-network`.

|====

[id="nw-multus-macvlan-config-example_{context}"]
== OVN-Kubernetes plugin configuration examples

The following example configures an additional network named `macvlan-net`:

.OVN-Kubernetes CNI plugin layer 3 configuration example
[source,json]
----
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: l3-network
  namespace: ns1
spec:
  config: |2
    {
      "cniVersion": "0.3.1",
      "name": "l3-network",
      "type": "ovn-k8s-cni-overlay",
      "topology":"layer3",
      "subnets": "10.128.0.0/16/24",
      "mtu": 1300,
      "netAttachDefName": "ns1/l3-network"
    }
----

The following example configures an additional network named `macvlan-net`:

.OVN-Kubernetes CNI plugin layer 2 configuration example
[source,json]
----
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: l2-network
  namespace: ns1
spec:
  config: |2
    {
      "cniVersion": "0.3.1",
      "name": "l2-network",
      "type": "ovn-k8s-cni-overlay",
      "topology":"layer2",
      "subnets": "10.100.200.0/24",
      "mtu": 1300,
      "netAttachDefName": "ns1/l2-network"
    }
----
