// Module included in the following assemblies:
//
// * networking/multiple_networks/edit-additional-network.adoc

[id="nw-multus-edit-network_{context}"]
= Modifying an additional network attachment definition

As a cluster administrator, you can make changes to an existing additional
network. Any existing Pods attached to the additional network will not be updated.

.Prerequisites

* You have configured an additional network for your cluster.
* Install the OpenShift Command-line Interface (CLI), commonly known as `oc`.
* Log in as a user with `cluster-admin` privileges.

.Procedure

To edit an additional network for your cluster, complete the following steps:

. Run the following command to edit the Cluster Network Operator (CNO) CR in
your default text editor:
+
----
$ oc edit networks.operator.openshift.io cluster
----

. In the `additionalNetworks` collection, update the additional network with
your changes.

. Save your changes and quit the text editor to commit your changes.

. Optional: Confirm that the CNO updated the NetworkAttachmentDefinition CR by
running the following command. Replace `<network-name>` with the name of the
additional network to display. There might be a delay before the CNO updates the
NetworkAttachmentDefinition CR to reflect your changes.
+
----
$ oc get network-attachment-definitions <network-name> -o yaml
----
+
For example, the following console output displays a
NetworkAttachmentDefinition that is named `net1`:
+
----
$ oc get network-attachment-definitions net1 -o go-template='{{printf "%s\n" .spec.config}}'
{ "cniVersion": "0.3.1", "type": "macvlan",
"master": "ens5",
"mode": "bridge",
"ipam":       {"type":"static","routes":[{"dst":"0.0.0.0/0","gw":"10.128.2.1"}],"addresses":[{"address":"10.128.2.100/23","gateway":"10.128.2.1"}],"dns":{"nameservers":["172.30.0.10"],"domain":"us-west-2.compute.internal","search":["us-west-2.compute.internal"]}} }
----
