:_mod-docs-content-type: PROCEDURE
[id="nw-viewing-service-l2-status_{context}"]
= Viewing ServiceL2Status

[role="_abstract"]
You can verify which node is advertising your service in Layer 2 mode by checking the ServiceL2Status custom resource. This helps you troubleshoot L2 advertisement issues and confirm the expected announcer node.

The ServiceL2Status CR provides details about which node is advertising a service using Layer 2 mode. This is useful for troubleshooting to confirm that the correct node is acting as the announcer.

[NOTE]
====
ServiceL2Status resources are created in the `metallb-system` namespace, not in the namespace where your LoadBalancer service is deployed. Always query these resources with `-n metallb-system`.
====

.Prerequisites

* You have an {product-title} cluster with the MetalLB Operator installed.
* You have created a MetalLB instance. For example:
+
[source,yaml]
----
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
spec: {}
----
+
This deploys the MetalLB controller and speaker pods required for status monitoring.

.Procedure

. View the status of the ServiceL2Status CR by running the following command:
+
[source,terminal]
----
$ oc get ServiceL2Status -n metallb-system
----
+
The output is similar to the following:
+
[source,terminal]
----
NAME       ALLOCATED NODE                SERVICE NAME     SERVICE NAMESPACE
l2-dbxpc   ip-10-0-98-203.ec2.internal   router-default   openshift-ingress
----

. View the details of the ServiceL2Status CR for your service:
+
[source,terminal]
----
$ oc get servicel2status nginx-service-worker0 -n metallb-system -o yaml
----
+
The output is similar to the following:
+
[source,yaml]
----
apiVersion: metallb.io/v1beta1
kind: ServiceL2Status
metadata:
  creationTimestamp: "2025-11-18T13:26:04Z"
  generateName: l2-
  generation: 1
  labels:
    metallb.io/node: ip-10-0-98-203.ec2.internal
    metallb.io/service-name: router-default
    metallb.io/service-namespace: openshift-ingress
  name: l2-dbxpc
  namespace: metallb-system
  ownerReferences:
  - apiVersion: v1
    kind: Pod
    name: speaker-h2wm2
    uid: c7996932-138b-4582-94cf-70af13d91ee9
  resourceVersion: "77081"
  uid: 64bbf9f5-0b30-466b-a7aa-a0ff46fa78b2
spec: {}
status:
  node: ip-10-0-98-203.ec2.internal
  serviceName: router-default
  serviceNamespace: openshift-ingress
----
+
The output includes the following important fields:
+
* `metadata.labels.metallb.io/node` identifies the node that is advertising the service. This is useful for troubleshooting to verify which node is the announcer.
* `metadata.labels.metallb.io/service-name` identifies the service that is being advertised.
* `status.node` confirms the name of the node advertising the service.