// Module included in the following assemblies:
//
// * networking/metallb/about-metallb.adoc

[id="nw-metallb-software-components_{context}"]
= MetalLB software components

When you install the MetalLB Operator, the `metallb-operator-controller-manager` deployment starts a pod.
The pod is the implementation of the Operator.
The pod monitors for changes to the `MetalLB` custom resource and `AddressPool` custom resources.

When the Operator starts an instance of MetalLB, it starts a `controller` deployment and a `speaker` daemon set.

`controller`::
The Operator starts the deployment and a single pod.
When you add a service of type `LoadBalancer`, Kubernetes uses the `controller` to allocate an IP address from an address pool.

`speaker`::
The Operator starts a daemon set for `speaker` pods.
By default, a pod is started on each node in your cluster.
You can limit the pods to specific nodes by specifying a node selector in the `MetalLB` custom resource when you start MetalLB.
+
For layer 2 mode, after the `controller` allocates an IP address for the service, the `speaker` pods use an algorithm to determine which `speaker` pod on which node will announce the load balancer IP address.
The algorithm involves hashing the node name and the load balancer IP address.
See the section about external traffic policy for more information.
// IETF treats protocol names as proper nouns.
The `speaker` uses Address Resolution Protocol (ARP) to announce IPv4 addresses and Neighbor Discovery Protocol (NDP) to announce IPv6 addresses.

For BGP mode, after the `controller` allocates an IP address for the service, each `speaker` pod advertises the load balancer IP address with its BGP peers.
You can configure which nodes start BGP sessions with BGP peers.
+
Refer to the concepts for layer 2 mode and BGP mode for more information.
+
Requests for the load balancer IP address are routed to the node with the `speaker` that announces the IP address.
After the node receives the packets, the service proxy routes the packets to an endpoint for the service.
The endpoint can be on the same node in the optimal case, or it can be on another node.
The service proxy chooses an endpoint each time a connection is established.
