// TODO -  possibly delete this file
// Or does it add actual value?

// Module included in the following assemblies:
//
// * networking/cluster-network-operator.adoc
// * installing/installing_aws/installing-aws-network-customizations.adoc
// * installing/installing_azure/installing-azure-network-customizations.adoc
// * installing/installing_bare_metal/installing-bare-metal-network-customizations.adoc
// * installing/installing_vsphere/installing-vsphere-network-customizations.adoc
// * installing/installing_vsphere/installing-vsphere-installer-provisioned-network-customizations.adoc
// * installing/installing_gcp/installing-gcp-network-customizations.adoc
// * installing/installing_azure_stack_hub/installing-azure-stack-hub-network-customizations.adoc

[id="nw-network-config_{context}"]
= Network configuration phases

There are two phases prior to {product-title} installation where you can customize the network configuration.

Phase 1:: You can customize the following network-related fields in the `install-config.yaml` file before you create the manifest files:
+
* `networking.networkType`
* `networking.clusterNetwork`
* `networking.serviceNetwork`
* `networking.machineNetwork`
+
For more information on these fields, refer to _Installation configuration parameters_.
+
[NOTE]
====
Set the `networking.machineNetwork` to match the CIDR that the preferred NIC resides in.
====

Phase 2:: After creating the manifest files by running `openshift-install create manifests`, you can define a customized Cluster Network Operator manifest with only the fields you want to modify. You can use the manifest to specify advanced network configuration.

You cannot override the values specified in phase 1 in the `install-config.yaml` file during phase 2. However, you can further customize the cluster network provider during phase 2.
