// Module included in the following assemblies:
//
// * networking/network_policy/viewing-network-policy.adoc
// * post_installation_configuration/network-configuration.adoc

:name: network
:role: admin
ifeval::["{context}" == "configuring-multi-network-policy"]
:multi:
:name: multi-network
:role: cluster-admin
endif::[]

[id="nw-networkpolicy-view_{context}"]
= Viewing {name} policies

You can examine the {name} policies in a namespace.

ifndef::multi[]
[NOTE]
====
If you log in with a user with the `cluster-admin` role, then you can view any network policy in the cluster.
====
endif::multi[]

.Prerequisites

* You installed the OpenShift CLI (`oc`).
* You are logged in to the cluster with a user with `{role}` privileges.
* You are working in the namespace where the {name} policy exists.

.Procedure

* List {name} policies in a namespace:

** To view {name} policy objects defined in a namespace, enter the following
command:
+
[source,terminal,subs="attributes+"]
----
$ oc get {name}policy
----

** Optional: To examine a specific {name} policy, enter the following command:
+
[source,terminal,subs="attributes+"]
----
$ oc describe {name}policy <policy_name> -n <namespace>
----
+
--
where:

  `<policy_name>`:: Specifies the name of the {name} policy to inspect.
  `<namespace>`:: Optional: Specifies the namespace if the object is defined in a different namespace than the current namespace.
--
ifndef::multi[]
+
For example:
+
[source,terminal]
----
$ oc describe networkpolicy allow-same-namespace
----
+
.Output for `oc describe` command
[source,text]
----
Name:         allow-same-namespace
Namespace:    ns1
Created on:   2021-05-24 22:28:56 -0400 EDT
Labels:       <none>
Annotations:  <none>
Spec:
  PodSelector:     <none> (Allowing the specific traffic to all pods in this namespace)
  Allowing ingress traffic:
    To Port: <any> (traffic allowed to all ports)
    From:
      PodSelector: <none>
  Not affecting egress traffic
  Policy Types: Ingress
----
endif::multi[]

ifdef::multi[]
:!multi:
endif::multi[]
:!name:
:!role:
