// Module included in the following assemblies:
//
// * networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc

:_mod-docs-content-type: CONCEPT
[id="nw-ovn-kubernetes-session-affinity_{context}"]
= Session affinity

Session affinity is a feature that applies to Kubernetes `Service` objects. You can use _session affinity_ if you want to ensure that each time you connect to a <service_VIP>:<Port>, the traffic is always load balanced to the same back end. For more information, including how to set session affinity based on a client's IP address, see link:https://kubernetes.io/docs/reference/networking/virtual-ips/#session-affinity[Session affinity].


[id="nw-ovn-kubernetes-session-affinity-stickyness-timeout_{context}"]
== Stickiness timeout for session affinity

The OVN-Kubernetes network plugin for {product-title} calculates the stickiness timeout for a session from a client based on the last packet. For example, if you run a `curl` command 10 times, the sticky session timer starts from the tenth packet not the first. As a result, if the client is continuously contacting the service, then the session never times out. The timeout starts when the service has not received a packet for the amount of time set by the link:https://kubernetes.io/docs/reference/networking/virtual-ips/#session-stickiness-timeout[`timeoutSeconds`] parameter.
