// Module included in the following assemblies:
//
// * monitoring/using-rfhe.adoc

:_content-type: PROCEDURE
[id="nw-rfhe-installing-operator-web-console_{context}"]
= Installing the Baremetal Hardware Event Proxy Operator using the web console

As a cluster administrator, you can install the Baremetal Hardware Event Proxy Operator using the web console.

.Prerequisites

* A cluster that is installed on bare-metal hardware with nodes that have a RedFish-enabled Baseboard Management Controller (BMC).
* Log in as a user with `cluster-admin` privileges.

.Procedure

. Install the Baremetal Hardware Event Proxy Operator using the {product-title} web console:

.. In the {product-title} web console, click *Operators* -> *OperatorHub*.

.. Choose  *Baremetal Hardware Event Proxy Operator* from the list of available Operators, and then click *Install*.

.. On the *Install Operator* page, select or create a *Namespace*, select *baremetal-hardware-event-proxy-operator*, and then click *Install*.

.Verification

Optional: You can verify that the Operator installed successfully by performing the following check:

. Switch to the *Operators* -> *Installed Operators* page.

. Ensure that *Baremetal Hardware Event Proxy Operator* is listed in the project with a *Status* of *InstallSucceeded*.
+
[NOTE]
====
During installation an Operator might display a *Failed* status. If the installation later succeeds with an *InstallSucceeded* message, you can ignore the *Failed* message.
====

If the operator does not appear as installed, to troubleshoot further:

* Go to the *Operators* -> *Installed Operators* page and inspect the *Operator Subscriptions* and *Install Plans* tabs for any failure or errors under *Status*.
* Go to the *Workloads* -> *Pods* page and check the logs for pods in the project namespace.
