// Module filename: nw-scaling-ingress-controller.adoc
// Module included in the following assemblies:
// * networking/ingress-controller-configuration.adoc

:_mod-docs-content-type: PROCEDURE
[id="nw-ingress-controller-configuration_{context}"]
= Scaling an Ingress Controller

Manually scale an Ingress Controller to meeting routing performance or availability requirements such as the requirement to increase throughput. `oc` commands are used to scale the `IngressController` resource. The following procedure provides an example for scaling up the default `IngressController`.

[NOTE]
====
Scaling is not an immediate action, as it takes time to create the desired number of replicas.
====

.Prerequisites

* On {vmw-first}, bare-metal, and Nutanix installer-provisioned infrastructure, scaling up Ingress Controller pods does not improve external traffic performance. To improve performance, ensure that you complete the following prerequisites:
** You manually configured a user-managed load balancer for your cluster. 
** You ensured that the load balancer was configured for the cluster nodes that handle incoming traffic from the Ingress Controller.

.Procedure

. View the current number of available replicas for the default `IngressController`:
+
[source,terminal]
----
$ oc get -n openshift-ingress-operator ingresscontrollers/default -o jsonpath='{$.status.availableReplicas}'
----

. Scale the default `IngressController` to the desired number of replicas by using the `oc patch` command. The following example scales the default `IngressController` to 3 replicas.
+
[source,terminal]
----
$ oc patch -n openshift-ingress-operator ingresscontroller/default --patch '{"spec":{"replicas": 3}}' --type=merge
----

. Verify that the default `IngressController` scaled to the number of replicas that you specified:
+
[source,terminal]
----
$ oc get -n openshift-ingress-operator ingresscontrollers/default -o jsonpath='{$.status.availableReplicas}'
----
+
[TIP]
====
You can alternatively apply the following YAML to scale an Ingress Controller to three replicas:
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  replicas: 3               <1>
----
====
<1> If you need a different amount of replicas, change the `replicas` value.
