// Module included in the following assemblies:
//
// * networking/hardware_networks/installing-sriov-operator.adoc

[id="installing-sr-iov-operator_{context}"]
= Installing SR-IOV Network Operator

As a cluster administrator, you can install the SR-IOV Network Operator by using the {product-title} CLI or the web console.

[id="install-operator-cli_{context}"]
== CLI: Installing the SR-IOV Network Operator

As a cluster administrator, you can install the Operator using the CLI.

.Prerequisites

* A cluster installed on bare-metal hardware with nodes that have hardware that supports SR-IOV.
* Install the OpenShift CLI (`oc`).
* An account with `cluster-admin` privileges.

.Procedure

. To create the `openshift-sriov-network-operator` namespace, enter the following command:
+
[source,terminal]
----
$ cat << EOF| oc create -f -
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-sriov-network-operator
  annotations:
    workload.openshift.io/allowed: management
EOF
----

. To create an OperatorGroup CR, enter the following command:
+
[source,terminal]
----
$ cat << EOF| oc create -f -
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sriov-network-operators
  namespace: openshift-sriov-network-operator
spec:
  targetNamespaces:
  - openshift-sriov-network-operator
EOF
----

. Subscribe to the SR-IOV Network Operator.

.. Run the following command to get the {product-title} major and minor version. It is required for the `channel` value in the next
step.
+
[source,terminal]
----
$ OC_VERSION=$(oc version -o yaml | grep openshiftVersion | \
    grep -o '[0-9]*[.][0-9]*' | head -1)
----

.. To create a Subscription CR for the SR-IOV Network Operator, enter the following command:
+
[source,terminal]
----
$ cat << EOF| oc create -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sriov-network-operator-subscription
  namespace: openshift-sriov-network-operator
spec:
  channel: "${OC_VERSION}"
  name: sriov-network-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF
----

. To verify that the Operator is installed, enter the following command:
+
[source,terminal]
----
$ oc get csv -n openshift-sriov-network-operator \
  -o custom-columns=Name:.metadata.name,Phase:.status.phase
----
+
.Example output
[source,terminal]
----
Name                                        Phase
sriov-network-operator.4.9.0-202110121402   Succeeded
----

[id="install-operator-web-console_{context}"]
== Web console: Installing the SR-IOV Network Operator

As a cluster administrator, you can install the Operator using the web console.

[NOTE]
====
You must create the operator group by using the CLI.
====

.Prerequisites

* A cluster installed on bare-metal hardware with nodes that have hardware that supports SR-IOV.
* Install the OpenShift CLI (`oc`).
* An account with `cluster-admin` privileges.

.Procedure

. Create a namespace for the SR-IOV Network Operator:

.. In the {product-title} web console, click *Administration* -> *Namespaces*.

.. Click *Create Namespace*.

.. In the *Name* field, enter `openshift-sriov-network-operator`, and then click *Create*.

. Install the SR-IOV Network Operator:

.. In the {product-title} web console, click *Operators* -> *OperatorHub*.

.. Select *SR-IOV Network Operator* from the list of available Operators, and then click *Install*.

.. On the *Install Operator* page, under *A specific namespace on the cluster*, select *openshift-sriov-network-operator*.

.. Click *Install*.

. Verify that the SR-IOV Network Operator is installed successfully:

.. Navigate to the *Operators* -> *Installed Operators* page.

.. Ensure that *SR-IOV Network Operator* is listed in the *openshift-sriov-network-operator* project with a *Status* of *InstallSucceeded*.
+
[NOTE]
====
During installation an Operator might display a *Failed* status.
If the installation later succeeds with an *InstallSucceeded* message, you can ignore the *Failed* message.
====

+
If the operator does not appear as installed, to troubleshoot further:

+
* Inspect the *Operator Subscriptions* and *Install Plans* tabs for any failure or errors under *Status*.
* Navigate to the *Workloads* -> *Pods* page and check the logs for pods in the
`openshift-sriov-network-operator` project.
