// Module included in the following assemblies:
//
// * networking/understanding-networking.adoc

:_mod-docs-content-type: CONCEPT
[id="nw-understanding-networking-dns-terms_{context}"]
= Key DNS terms

* CoreDNS: CoreDNS is the DNS server and provides name resolution for services and pods.

* DNS names: Services are assigned DNS names based on their namespace and name. For example, a service named `my-service` in the `default` namespace would have the DNS name `my-service.default.svc.cluster.local`.

* Domain names: Domain names are the human-friendly names used to access websites and services, such as `example.com`.

* IP addresses: IP addresses are numerical labels assigned to each device connected to a computer network that uses IP for communication. An example of an IPv4 address is `192.0.2.1`. An example of an IPv6 address is `2001:0db8:85a3:0000:0000:8a2e:0370:7334`.

* DNS servers: DNS servers are specialized servers that store DNS records. These records map domain names to IP addresses. When you type a domain name into your browser, your computer contacts a DNS server to find the corresponding IP address.

* Resolution process: A DNS query is sent to a DNS resolver. The DNS resolver then contacts a series of DNS servers to find the IP address associated with the domain name. The resolver will try using the name with a series of domains, such as `<namespace>.svc.cluster.local`, `svc.cluster.local`, and `cluster.local`. This process stops at the first match. The IP address is returned to your browser and then connects to the web server using the IP address.
