// Module included in the following assemblies:
//
// * backup_and_restore/application_backup_and_restore/advanced-topics.adoc


:_mod-docs-content-type: CONCEPT
[id="oadp-backing-and-restoring-from-cluster-to-cluster_{context}"]
= Backing up data from one cluster and restoring it to another cluster

In general, you back up data from one {product-title} cluster and restore it on another {product-title} cluster in the same way that you back up and restore data to the same cluster. However, there are some additional prerequisites and differences in the procedure when backing up data from one {product-title} cluster and restoring it on another.

.Prerequisites

* All relevant prerequisites for backing up and restoring on your platform (for example, AWS, Microsoft Azure, {gcp-short}, and so on), especially the prerequisites for the Data Protection Application (DPA), are described in the relevant sections of this guide.

.Procedure

. Make the following additions to the procedures given for your platform:

** Ensure that the backup store location (BSL) and volume snapshot location have the same names and paths to restore resources to another cluster.
** Share the same object storage location credentials across the clusters.
** For best results, use OADP to create the namespace on the destination cluster.
** If you use the Velero `file-system-backup` option, enable the `--default-volumes-to-fs-backup` flag for use during backup by running the following command:
+
[source,terminal]
----
$ velero backup create <backup_name> --default-volumes-to-fs-backup <any_other_options>
----
+
[NOTE]
====
In OADP 1.2 and later, the Velero Restic option is called `file-system-backup`.
====

[IMPORTANT]
====
Before restoring a CSI back up, edit the `VolumeSnapshotClass` custom resource (CR), and set the  `snapshot.storage.kubernetes.io/is-default-class parameter` to false. 
Otherwise, the restore will partially fail due to the same value in the `VolumeSnapshotClass` in the target cluster for the same drive.
====