// Module included in the following assemblies:
//
// * backup_and_restore/oadp-1-5-release-notes.adoc
:_mod-docs-content-type: PROCEDURE

[id="verifying-upgrade-1-5-0_{context}"]
= Verifying the upgrade

[role="_abstract"]
You can verify the {oadp-first} upgrade by using the following procedure.

.Procedure

. Verify that the `DataProtectionApplication` (DPA) has been reconciled successfully:
+
[source,terminal]
----
$ oc get dpa dpa-sample -n openshift-adp
----
+
.Example output
[source,terminal]
----
NAME            RECONCILED   AGE
dpa-sample      True         2m51s
----
+
[NOTE]
====
The `RECONCILED` column must be `True`.
====

. Verify that the installation finished by viewing the {oadp-short} resources by running the following command:
+
[source,terminal]
----
$ oc get all -n openshift-adp
----
+
.Example output
[source,terminal]
----
NAME                                                    READY   STATUS    RESTARTS   AGE
pod/node-agent-9pjz9                                    1/1     Running   0          3d17h
pod/node-agent-fmn84                                    1/1     Running   0          3d17h
pod/node-agent-xw2dg                                    1/1     Running   0          3d17h
pod/openshift-adp-controller-manager-76b8bc8d7b-kgkcw   1/1     Running   0          3d17h
pod/velero-64475b8c5b-nh2qc                             1/1     Running   0          3d17h

NAME                                                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/openshift-adp-controller-manager-metrics-service   ClusterIP   172.30.194.192   <none>        8443/TCP   3d17h
service/openshift-adp-velero-metrics-svc                   ClusterIP   172.30.190.174   <none>        8085/TCP   3d17h

NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/node-agent   3         3         3       3            3           <none>          3d17h

NAME                                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/openshift-adp-controller-manager   1/1     1            1           3d17h
deployment.apps/velero                             1/1     1            1           3d17h

NAME                                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/openshift-adp-controller-manager-76b8bc8d7b   1         1         1       3d17h
replicaset.apps/openshift-adp-controller-manager-85fff975b8   0         0         0       3d17h
replicaset.apps/velero-64475b8c5b                             1         1         1       3d17h
replicaset.apps/velero-8b5bc54fd                              0         0         0       3d17h
replicaset.apps/velero-f5c9ffb66                              0         0         0       3d17h
----
+
[NOTE]
====
The `node-agent` pods are created only while using `restic` or `kopia` in `DataProtectionApplication` (DPA).
In {oadp-short} 1.4.0 and {oadp-short} 1.3.0 version, the `node-agent` pods are labeled as `restic`.
====

. Verify the backup storage location and confirm that the `PHASE` is `Available` by running the following command:
+
[source,terminal]
----
$ oc get backupstoragelocations.velero.io -n openshift-adp
----
+
.Example output
[source,terminal]
----
NAME           PHASE       LAST VALIDATED   AGE     DEFAULT
dpa-sample-1   Available   1s               3d16h   true
----
