// Module included in the following assemblies:
//
// 

:_mod-docs-content-type: CONCEPT
[id="oadp-self-service-admin-spec-enforcement_{context}"]
= {oadp-short} Self-Service administrator DPA spec enforcement

To ensure secure backup and restore, {oadp-short} Self-Service automatically excludes the following resources from being backed up or restored:

* Security Context Constraints (SCCs)
* Cluster roles
* Cluster role bindings
* Custom Resource Definitions (CRDs)
* `PriorityClasses`
* Virtual machine cluster instance types
* Virtual machine cluster preferences


The cluster administrator can also enforce a company, or a compliance policy by using the following fields in the `DataProtectionApplication` (DPA) CR:

* `enforceBSLSpec` to enforce the `NonAdminBackupStorageLocation` CR .
* `enforcedBackupSpec` on the `NonAdminBackup` CR.
* `enforcedRestoreSpec` on the `NonAdminRestore` CR.

utilizing templated NABSL's, NAB's and NAR's that require fields values to be set and conform to the administrator defined policy. Admin Enforceable fields are fields that the cluster administrator can enforce non cluster admin users to use. Restricted fields are automatically managed by OADP and cannot be modified by either administrators or users.