// Module included in the following assemblies:
//
// 

:_mod-docs-content-type: PROCEDURE
[id="oadp-self-service-creating-nar_{context}"]
= Creating a `NonAdminRestore` CR

As a non-admin user, to restore a backup you create a `NonAdminRestore` (NAR) CR. The backup is restored to your authorized namespace.

.Prerequisites

* You are logged in to the cluster as a non-admin user.
* The cluster administrator has installed the {oadp-short} Operator.
* The cluster administrator has configured the `DataProtectionApplication` to enable {oadp-short} Self-Service.
* The cluster administrator has created a namespace for you and has authorized you to operate from that namespace.
* You have a backup of your application by creating a `NonAdminBackup` (NAB) CR.

.Procedure

. To create a `NonAdminRestore` CR, create a YAML manifest file with the following configuration:
+
.Example `NonAdminRestore`
[source,yaml]
----
apiVersion: oadp.openshift.io/v1alpha1
kind: NonAdminRestore
metadata:
  name: test-nar # <1>
spec:
  restoreSpec:
    backupName: test-nab # <2>
----
1. Specify a name for the NAR CR. In this example, the name of the NAR CR is `test-nar`.
2. Specify the `NonAdminBackup` CR you to restore from. In this example, the NAB is `test-nab`.

. To create the NAR CR, run the following command:
+
[source,terminal]
----
$ oc apply -f <nar_cr_filename> # <1>
----
1. Specify the file name containing the NAR CR configuration.

.Verification

. To verify that the NAR CR is successfully created, run the following command:
+
[source,terminal]
----
oc get nar test-nar -o yaml
----
+
.Example output

The following annotated fields contain important information related to the NAR CR.
+
[source,yaml]
----
apiVersion: oadp.openshift.io/v1alpha1
kind: NonAdminRestore
metadata:
  creationTimestamp: "2025-02-11T13:50:51Z"
  finalizers:
  - nonadminrestore.oadp.openshift.io/finalizer
  generation: 2
  name: test-nar
  namespace: test-nac-ns
  resourceVersion: "167676"
  uid: 645788b1-998b-4ef7-b55c-cdfb5cba595b
spec:
  restoreSpec:
    backupName: test-nab
    hooks: {}
    itemOperationTimeout: 0s
status:
  conditions:
  - lastTransitionTime: "2025-02-11T13:50:51Z"
    message: restore accepted # <1>
    reason: RestoreAccepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2025-02-11T13:50:51Z"
    message: Created Velero Restore object # <2>
    reason: RestoreScheduled
    status: "True"
    type: Queued
  phase: Created # <3>
  queueInfo:
    estimatedQueuePosition: 0 # <4>
  veleroRestore:
    nacuuid: test-nac-test-nar-a10..210-73dd-427b-b94e-3f..948b # <5>
    name: test-nac-test-nar-a10...210-73dd-427b-b94e-3ff...48b # <6>
    namespace: openshift-adp
    status:
      completionTimestamp: "2025-02-11T13:51:24Z"
      hookStatus: {}
      phase: Completed # <7>
      progress:
        itemsRestored: 29
        totalItems: 29
      startTimestamp: "2025-02-11T13:50:51Z"
      warnings: 6
----
1. The `NonAdminController` (NAC) has reconciled and validated the NAR CR.
2. The NAC has created the `Velero` restore object.
3. The NAR CR is in the `Created` phase.
4. This field indicates the queue position of the NAR CR. There can be multiple NAR CRs in process and each NAR CR is assigned a queue position. When the restore is complete, the queue position is set to 0.
5. The NAC creates the `Velero` restore object and sets the `nacuuid`.
6. This is the name of the associated `Velero` restore object.
7. The `Velero` restore object is in the `Completed` phase and the restore is successful.

