// Module included in the following assemblies:
//
// * backup_and_restore/application_backup_and_restore/installing/configuring-backup-restore-pvc-datamover.adoc

:_mod-docs-content-type: PROCEDURE
[id="configuring-restore-pvc_{context}"]
= Configuring a restorePVC for a Data Mover restore

[role="_abstract"]
Configure restore persistent volume claim (PVC) settings in the `DataProtectionApplication` (DPA) to optimize Data Mover restore operations and enable parallel volume restores. This improves restore performance by distributing restore pods across nodes.

A `restorePVC` is an intermediate PVC that is used to write data during the Data Mover restore operation.

You can configure the `restorePVC` in the `DataProtectionApplication` (DPA) object by using the `ignoreDelayBinding` field. Setting the `ignoreDelayBinding` field to `true` allows the restore operation to ignore the `WaitForFirstConsumer` binding mode. The data movement restore operation then creates the restore pod and provisions the associated volume to an arbitrary node. 

The `ignoreDelayBinding` setting is helpful in scenarios where multiple volume restores are happening in parallel. With the `ignoreDelayBinding` field set to `true`, the restore pods can be spread evenly to all nodes.

.Prerequisites

* You have installed the {oadp-short} Operator.
* You have a created a Data Mover backup of an application.

.Procedure

* Configure the `restorePVC` section in the DPA as shown in the following example:
+
.Example Data Protection Application
[source,yaml]
----
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: ts-dpa
  namespace: openshift-adp
spec:
#  ...
  configuration:
    nodeAgent:
      enable: true
      uploaderType: kopia
    restorePVC:
      ignoreDelayBinding: true
----
+
where:
+
`restorePVC`:: Specifies the `restorePVC` section.
`ignoreDelayBinding`:: Set the `ignoreDelayBinding` field to `true`.