// Module included in the following assemblies:
//
// * backup_and_restore/application_backup_and_restore/troubleshooting/oadp-monitoring.adoc

:_mod-docs-content-type: PROCEDURE
[id="oadp-monitoring-setup-monitor_{context}"]
= OADP monitoring setup

[role="_abstract"]
Set up {oadp-short} monitoring by enabling User Workload Monitoring and configuring the {product-title} monitoring stack to retrieve Velero metrics. This helps you create alerting rules, query metrics, and optionally visualize data by using Prometheus-compatible tools such as Grafana.

Monitoring metrics requires enabling monitoring for the user-defined projects and creating a `ServiceMonitor` resource to scrape those metrics from the already enabled {oadp-short} service endpoint in the `openshift-adp` namespace.

[NOTE]
====
The {oadp-short} support for Prometheus metrics is offered on a best-effort basis and is not fully supported.
====

For more information about setting up the monitoring stack, see link:https://docs.redhat.com/en/documentation/monitoring_stack_for_red_hat_openshift/latest/html/configuring_user_workload_monitoring/preparing-to-configure-the-monitoring-stack-uwm[Configuring user workload monitoring].

.Prerequisites

* You have access to an {product-title} cluster using an account with `cluster-admin` permissions.
* You have created a cluster monitoring config map.

.Procedure

. Edit the `cluster-monitoring-config` `ConfigMap` object in the `openshift-monitoring` namespace by using the following command:
+
[source,terminal]
----
$ oc edit configmap cluster-monitoring-config -n openshift-monitoring
----

. Add or enable the `enableUserWorkload` option in the `data` section's `config.yaml` field by using the following command:
+
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
data:
  config.yaml: |
    enableUserWorkload: true
metadata:
# ...
----
+
where:

`enableUserWorkload`:: Add this option or set to `true`.

. Wait a short period to verify the User Workload Monitoring Setup by checking that the following components are up and running in the `openshift-user-workload-monitoring` namespace:
+
[source,terminal]
----
$ oc get pods -n openshift-user-workload-monitoring
----
+

[source,terminal]
----
NAME                                   READY   STATUS    RESTARTS   AGE
prometheus-operator-6844b4b99c-b57j9   2/2     Running   0          43s
prometheus-user-workload-0             5/5     Running   0          32s
prometheus-user-workload-1             5/5     Running   0          32s
thanos-ruler-user-workload-0           3/3     Running   0          32s
thanos-ruler-user-workload-1           3/3     Running   0          32s
----
+
. Verify the existence of the `user-workload-monitoring-config` ConfigMap in the `openshift-user-workload-monitoring`. If it exists, skip the remaining steps in this procedure.
+
[source,terminal]
----
$ oc get configmap user-workload-monitoring-config -n openshift-user-workload-monitoring
----
+

[source,terminal]
----
Error from server (NotFound): configmaps "user-workload-monitoring-config" not found
----
+
. Create a `user-workload-monitoring-config` `ConfigMap` object for the User Workload Monitoring, and save it under the `2_configure_user_workload_monitoring.yaml` file name:
+
[source,yaml]
+
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
----
+
. Apply the `2_configure_user_workload_monitoring.yaml` file by using the following command:
+
[source,terminal]
----
$ oc apply -f 2_configure_user_workload_monitoring.yaml
configmap/user-workload-monitoring-config created
----