// Module included in the following assemblies:
//
// * backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.adoc
// * backup_and_restore/application_backup_and_restore/installing/installing-oadp-azure.adoc
// * backup_and_restore/application_backup_and_restore/installing/installing-oadp-gcp.adoc
// * backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.adoc
// * backup_and_restore/application_backup_and_restore/installing/installing-oadp-ocs.adoc

:_mod-docs-content-type: PROCEDURE
[id="oadp-ssec-encrypted-backups_{context}"]
= OADP SSE-C encrypted backups

Amazon Web Services (AWS) S3 now applies server-side encryption with Amazon S3 managed keys (SSE-S3) as the base level of encryption for every bucket in Amazon S3. It is to note that OpenShift API for Data Protection (OADP) encrypt data via SSL/TLS, HTTPS, and the velero-repo-credentials secret while data is transferred off cluster to storage.

It is recommended to include an additional layer of encryption to prevent backed up data from being unencrypted in case of lost or stolen AWS credentials. The https://github.com/openshift/velero-plugin-for-aws/blob/konveyor-dev/backupstoragelocation.md[OpenShift velero-plugin-for-aws] provides several additional encryption methods, review the configuration options and consider implementing additional encryption.

SSE-C encryption provides Red Hat users server-side encryption with customer-provided keys (SSE-C), so that you can store your own encryption keys. This will provide required additional security if the AWS credentials have been exposed.

[WARNING]
====
it is strongly advised to secure cryptographic keys in a secure and safe manner. Encrypted data and backups will not be recoverable in the absence of the encryption key.
====

.Prerequisites / Known issues

You may receive `credentials not found` errors. To avoid this issue you can create a workaround by adding a volumeSnapshot configuration to your DPA without specifying a credential:
[source,yaml]
----
 snapshotLocations:
  - velero:
      config:
        profile: default
        region: <region>
      provider: aws
# ...
----

.Procedure

You can configure an SSE-C encryption to provide additional security by using following these steps.

. Create an encryption key by running the following command:
+
[source,terminal]
----
dd if=/dev/urandom bs=1 count=32 > sse.key
cat sse.key | base64 > sse_encoded.key
ln -s sse_encoded.key customer-key
----

. Create an OpenShift secret.

.. If you are initially installing and configuring OADP, you may create the aws credential and encryption key secret at the same time by running the following command:
+
[source,terminal]
----
$ oc create secret generic cloud-credentials --namespace openshift-adp --from-file cloud=<path>/openshift_aws_credentials,customer-key=<path>/sse_encoded.key
----

.. If you are updating an existing installation, edit the values of the `cloud-credential` `secret` block of the `DataProtectionApplication` CR manifest, as in the following example:
+
[source,yaml]
----
apiVersion: v1
data:
  cloud: W2Rfa2V5X2lkPSJBS0lBVkJRWUIyRkQ0TlFHRFFPQiIKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5P<snip>rUE1mNWVSbTN5K2FpeWhUTUQyQk1WZHBOIgo=
  customer-key: v+<snip>TFIiq6aaXPbj8dhos=
kind: Secret
# ...
----

. Edit the value of the `customerKeyEncryptionFile` attribute in the `backupLocations` block of `DataProtectionApplication` CR manifest, as in the following example:

+
[source,yaml]
----
spec:
  backupLocations:
    - velero:
        config:
          customerKeyEncryptionFile: /credentials/customer-key
          profile: default
# ...
----

[WARNING]
====
Existing installations require the Velero pod to be restarted to remount the secret credentials properly.
====

The installation is complete, and you can back up and restore OpenShift resources. The data saved in AWS s3 storage is encrypted with the new key and can not be downloaded via the AWS S3 console or API without the supplied encryption key.

.Verification

Test to verify that encrypted files cannot be downloaded without the extra key.

. Create a test file by running the following command:

+
[source,terminal]
----
$ echo "encrypt me please" > test.txt
----

. Upload the test file by running the following command:

+
[source,terminal]
----
$ aws s3api put-object \
  --bucket <bucket> \
  --key test.txt \
  --body test.txt \
  --sse-customer-key fileb://sse.key \
  --sse-customer-algorithm AES256
----
