// Module included in the following assemblies:
//
// 

:_mod-docs-content-type: CONCEPT
[id="oadp-self-service-overview_{context}"]
= {oadp-short} overview

In the earlier versions of {oadp-full}, you need to have cluster administrator privileges to perform {oadp-short} operations such as backing up and restoring an application, creating a backup storage location, and so on. With {oadp-short} 1.5.0 onward, you do not need to have cluster-wide administrator privileges to perform the backup and restore operations.

The {oadp-short} Self-Service feature provides secure self-service data protection capabilities while maintaining proper access controls.

As a non-admin user, you can back up, and restore applications deployed in your namespace on the cluster. This means, you need to have administrator access to your namespace created on the cluster.

The {oadp-short} cluster administrator creates a non-admin user and provides the necessary access controls to the non-admin user to perform {oadp-short} Self-Service actions.


== How do you benefit from the {oadp-short} Self-Service feature?

* As a cluster administrator:
** You allow namespace-scoped backup and restore operations to a non-admin user.
** You maintain cluster administrator control over non-administrator operations through templates and policies.

* As a non-administrator:
** As a non-admin user, you have secure access to backup logs and status information.
** As a non-admin user, you can create dedicated backup storage locations.


== Namespace-scoped back up and restore

With OADP self-service, regular users can now perform backup and restore operations within namespaces where they have appropriate permissions. OADP self-service enables regular OpenShift users to perform backup and restore operations within their authorized namespaces. This is achieved through custom resources that securely manage these operations while maintaining proper access controls and visibility. Users can:

* Create and manage backups of their authorized namespaces
* Restore data to their authorized namespaces


