// Module included in the following assemblies:
//
// * backup_and_restore/application_backup_and_restore/cli-tools/oadp-cli-plugin.adoc

:_mod-docs-content-type: REFERENCE
[id="oadp-cli-nonadmin-bsl_{context}"]
= Managing NonAdminBackupStorageLocations

You can use the {oadp-short} CLI to create and view `NonAdminBackupStorageLocations` (NABSLs) in your namespace. NABSLs define where your backup data is stored using object storage that you own and manage.

[NOTE]
====
Updating or deleting NABSLs after creation is not supported for non-admin users.
====

.Prerequisites

* The {oadp-short} CLI plugin is installed and configured in non-admin mode.
* You are logged in to the {product-title} cluster and your current namespace context is set to the target namespace.
* You have editor roles for `nonadminbackupstoragelocations.oadp.openshift.io` in your namespace.
* You have a Kubernetes `Secret` in your namespace containing credentials for your object storage provider.

.Creating a NonAdminBackupStorageLocation

* Create a non-admin backup storage location:
+
[source,terminal]
----
$ oc oadp nonadmin bsl create <bsl_name> [flags]
----
+
.Flags for `oc oadp nonadmin bsl create`
[cols="1,3",options="header"]
|===
|Flag |Description

|`--provider`
|Storage provider. Required. Examples: `aws`, `azure`, `gcp`.

|`--bucket`
|Object storage bucket name. Required.

|`--credential`
|Credential for this location in the format `SECRET_NAME=KEY`, where `SECRET_NAME` is the Kubernetes `Secret` name and `KEY` is the data key within the `Secret`. Required.

|`--prefix`
|Prefix for backup objects in the bucket.

|`--region`
|Storage region. Required for some providers such as AWS.

|`--config`
|Additional provider-specific configuration as `key=value` pairs.
|===
+
If the cluster administrator has enabled `requireApprovalForBSL`, the NABSL remains in a pending state until an administrator approves the request.
+
.Example
[source,terminal]
----
$ oc oadp nonadmin bsl create my-storage \
    --provider aws \
    --bucket my-velero-bucket \
    --prefix velero-backups \
    --credential cloud-credentials=cloud \
    --region us-east-1
----

[TIP]
====
After creating a BSL, run the following command to set it as the default and avoid specifying the storage location on each backup:

[source,terminal]
----
$ oc oadp client config set default-nabsl=<bsl_name>
----
====

.Listing NonAdminBackupStorageLocations

* List all non-admin backup storage locations in your current namespace:
+
[source,terminal]
----
$ oc oadp nonadmin bsl get [<bsl_name>] [flags]
----
+
.Flags for `oc oadp nonadmin bsl get`
[cols="1,3",options="header"]
|===
|Flag |Description

|`-o`
|Output format. Supported values: `json`, `yaml`.
|===
