// Module included in the following assemblies:
//
// * rosa_backing_up_and_restoring_applications/backing-up-applications.adoc

:_mod-docs-content-type: PROCEDURE
[id="oadp-installing-oadp-rosa-sts_{context}"]
= Installing OADP on {product-title} with AWS STS

AWS Security Token Service (AWS STS) is a global web service that provides short-term credentials for IAM or federated users. {product-title} (ROSA) with STS is the recommended credential mode for ROSA clusters. This document describes how to install OpenShift API for Data Protection (OADP) on (ROSA) with AWS STS.

[IMPORTANT]
====
Restic is not supported in the OADP on ROSA with AWS STS environment. Ensure the Restic service is disabled. Use native snapshots to backup volumes. See _Known Issues_ for more information.
====

.Prerequisites

* A {openshift-rosa} cluster with the required access and tokens. For instructions, see the procedure in "Preparing AWS credentials". If you plan to use two different clusters for backing up and restoring, you need to prepare AWS credentials, including `ROLE_ARN`, for each cluster.
* link:https://docs.openshift.com/container-platform/4.12/backup_and_restore/application_backup_and_restore/installing/installing-oadp-aws.html#oadp-creating-default-secret_installing-oadp-aws[A default Secret], if your backup and snapshot locations use the same credentials, or if you do not require a snapshot location.

.Procedure

. Create an OpenShift secret from your AWS token file by entering the following commands:

.. Create the credentials file:
+
[source, terminal]
----
$ cat <<EOF > ${SCRATCH}/credentials
[default]
role_arn = ${ROLE_ARN}
web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token
EOF
----

.. Create the OpenShift secret:
+
[source, terminal]
----
$ oc -n openshift-adp create secret generic cloud-credentials \
  --from-file=${SCRATCH}/credentials
----

. Install the OADP Operator.
.. In the {product-title} web console, navigate to Operators *->* OperatorHub.
.. Search for the OADP Operator, then click *Install*.

. Create AWS cloud storage using your AWS credentials:
+
[source,terminal]
----
$ cat << EOF | oc create -f -
apiVersion: oadp.openshift.io/v1alpha1
kind: CloudStorage
metadata:
  name: ${CLUSTER_NAME}-oadp
  namespace: openshift-adp
spec:
  creationSecret:
    key: credentials
    name: cloud-credentials
  enableSharedConfig: true
  name: ${CLUSTER_NAME}-oadp
  provider: aws
  region: $REGION
EOF
----

. Create the `DataProtectionApplication` resource, which is used to configure the connection to the storage where the backups and volume snapshots are stored:
+
[source,terminal]
----
$ cat << EOF | oc create -f -
apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: ${CLUSTER_NAME}-dpa
  namespace: openshift-adp
spec:
  backupLocations:
  - bucket:
      cloudStorageRef:
        name: ${CLUSTER_NAME}-oadp
      credential:
        key: credentials
        name: cloud-credentials
      default: true
  configuration:
    velero:
      defaultPlugins:
      - openshift
      - aws
      nodeAgent: <1>
        enable: false
        uploaderType: restic
  volumeSnapshots:
  - velero:
      config:
        credentialsFile: /tmp/credentials/openshift-adp/cloud-credentials-credentials <2>
        enableSharedConfig: "true" <3>
        region: ${REGION} <4>
      provider: aws
EOF
----
<1> See the first note below.
<2> The `credentialsFile` field is the mounted location of the bucket credential on the pod.
<3> The `enableSharedConfig` field allows the `snapshotLocations` to share or reuse the credential defined for the bucket.
<4> Specify `region` as your AWS region. This must be the same as the cluster region.
+
[NOTE]
====
The `enable` parameter of `restic` is set to `false` in this configuration because OADP does not support Restic in ROSA environments.
If you are using OADP 1.2, replace this configuration:
[source,terminal]
----
nodeAgent:
  enable: false
  uploaderType: restic
----
with the following:
[source,terminal]
----
restic:
  enable: false
----
====
+
You are now ready to backup and restore OpenShift applications, as described in the link:https://docs.openshift.com/container-platform/4.11/backup_and_restore/application_backup_and_restore/backing_up_and_restoring/backing-up-applications.html[OADP documentation].
+
[NOTE]
====
If you want to use two different clusters for backing up and restoring, the two clusters must have identical AWS S3 storage names in both the cloudstorage CR and the OADP `DataProtectionApplication` configuration.
====

== Known Issues
.Restic, Kopia, and DataMover are not supported or recommended

* link:https://issues.redhat.com/browse/OADP-1054[CloudStorage: openshift-adp-controller-manager crashloop seg fault with Restic enabled]
* link:https://issues.redhat.com/browse/OADP-1057[Cloudstorage API: CSI Backup of an app with internal images partially fails with plugin panicked error]
* (Affects OADP 1.1.x_ only): link:https://issues.redhat.com/browse/OADP-1055[CloudStorage: bucket is removed on CS CR delete, although it doesn't have "oadp.openshift.io/cloudstorage-delete": "true"]

[role="_additional-resources"]
.Additional resources

* link:https://docs.openshift.com/rosa/rosa_architecture/rosa-understanding.html[Understanding ROSA with STS]
* link:https://docs.openshift.com/rosa/rosa_getting_started/rosa-sts-getting-started-workflow.html[Getting started with ROSA STS]
* link:https://docs.openshift.com/rosa/rosa_install_access_delete_clusters/rosa-sts-creating-a-cluster-quickly.html[Creating a ROSA cluster with STS]
* link:https://docs.openshift.com/container-platform/4.12/backup_and_restore/application_backup_and_restore/installing/about-installing-oadp.html[About installing OADP]
* link:https://docs.openshift.com/container-platform/4.12/storage/container_storage_interface/persistent-storage-csi.html[Configuring CSI volumes]
* link:https://docs.openshift.com/rosa/rosa_architecture/rosa_policy_service_definition/rosa-service-definition.html#rosa-sdpolicy-storage_rosa-service-definition[ROSA storage options]
