// This module is included in the following assembly:
//
// * configuring/configuring-build-runs.adoc

:_mod-docs-content-type: REFERENCE
[id="ob-build-run-status_{context}"]
= Build run status

[role="_abstract"]
Monitor the progress and completion of your image builds by checking the status of the `BuildRun` custom resource (CR).
A `BuildRun` CR stores status information in the status.conditions field. This field includes the status, the reason for that status, and a descriptive message. For example, a `Succeeded` condition type means the build finished successfully.

The following examples show how to view the status of a specific BuildRun CR.

Unknown status::
An `Unknown` status indicates the build is still starting or in progress. The following example shows a `BuildRun` with `Unknown` status:

[source,terminal]
----
$ oc get buildrun buildah-buildrun-mp99r
----
Example output:
[source,terminal]
----
NAME                    SUCCEEDED   REASON    STARTTIME   COMPLETIONTIME
buildah-buildrun-mp99r  Unknown     Unknown      1s
----

True status::
A `True` status indicates that the build completed successfully. The following example shows a BuildRun` with `True` status:

[source,terminal]
----
$ oc get buildrun buildah-buildrun-mp99r
----
Example output:
[source,terminal]
----
NAME                   SUCCEEDED     REASON     STARTTIME   COMPLETIONTIME
buildah-buildrun-mp99r  True        Succeeded      29m       20m
----

A `BuildRun` CR stores the status-related information in the `status.conditions` field. For example, a condition with the type `Succeeded` indicates that resources have successfully completed their operation. The `status.conditions` field includes significant information like status, reason, and message for the `BuildRun` CR.
