// This module is included in the following assembly:
//
// * work-with-builds/using-builds.adoc

:_mod-docs-content-type: PROCEDURE
[id="ob-deleting-a-buildrun-resource_{context}"]
= Deleting a buildrun resource

You can delete a `BuildRun` resource if it is not required in your project.

.Prerequisites

* You have installed the `oc` CLI.
* Optional: You have installed the `shp` CLI.

.Procedure

. Delete a `BuildRun` resource by using one of the CLIs:
+
.. Using `oc` CLI
[source,terminal]
----
$ oc delete buildrun <buildrun_resource_name>
----
+
.. Using `shp` CLI
[source,terminal]
----
$ shp buildrun delete <buildrun_resource_name>
----
+
. Delete a `BuildRun` resource used by buildpacks by running the following command:
+
[IMPORTANT]
====
Buildpacks is a Technology Preview feature only. Technology Preview features are not supported with Red{nbsp}Hat production service level agreements (SLAs) and might not be functionally complete. Red{nbsp}Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red{nbsp}Hat Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
+
.Using `oc` CLI
[source,terminal]
----
$ oc delete buildrun <buildpacks_buildrun_resource_name>
----
+
.Using `shp` CLI
[source,terminal]
----
$ shp delete buildrun <buildpacks_buildrun_resource_name>
----