// This module is included in the following assembly:
//
// * configuring/configuring-openshift-builds.adoc

:_mod-docs-content-type: REFERENCE
[id="ob-defining-param-values_{context}"]
= Parameter values definition for a build

[role="_abstract"]
You can set build strategy parameters in your `Build` custom resource (CR). These settings control how your build runs. For every parameter, you must provide a value. You can provide the values directly or reference keys in `ConfigMaps` or `Secrets`. 

[NOTE]
====
You can only use `ConfigMaps` or `Secrets` if the parameter appears in a command, argument, or environment variable in the build strategy.
====

The following are the requirements of using parameters values definition for a build:

* Mapping: Every `spec.paramValues` name must match a parameter defined in the `BuildStrategy` CR.

* Reserved names: Do not use reserved names like `BUILDER_IMAGE`, `CONTEXT_DIR`, or any name starting with `shp-`.

* Resources: You can only use `ConfigMaps` or `Secrets` if the parameter is used in a command, argument, or environment variable.
