// This module is included in the following assembly:
//
// * installing/installing-openshift-builds.adoc

:_mod-docs-content-type: PROCEDURE
[id="ob-disabling-shipwrightBuilds-components_{context}"]
= Disabling ShipwrightBuilds components

[role="_abstract"]
If your organization does not require `ShipwrightBuilds` CR, you can disable the `ShipwrightBuilds` custom resource (CR). This action removes the `shipwright-build-controller` and `shipwright-build-webhook` pods from the `openshift-builds` namespace. It does not affect the Shared Resources Container Storage Interface (CSI) driver component or the `ShipwrightBuilds` custom resource definition (CRD) and optimizes your cluster's performance.

.Prerequisites

* You have installed the OpenShift CLI (`oc`).
* You are logged in to the {ocp-product-title} cluster as an administrator.
* You have installed the {builds-title}.

.Procedure

* Run the following command to disable the `shipwright-build-controller` and `shipwright-build-webhook` pods:
+
[source,terminal]
----
$ oc patch openshiftbuild cluster --type=merge -p '{"spec":{"shipwright":{"build":{"state":"Disabled"}}}}'
----
+
This command disables the `shipwright-build-controller` and `shipwright-build-webhook` pods but does not affect the `ShipwrightBuilds` CRD.

.Verification

* Run the following command to verify that the `shipwright-build-controller` and `shipwright-build-webhook` pods are disabled:
+
[source,terminal]
----
$ oc get pods -n openshift-builds
----
+
_Example output_
+
[source,terminal]
----
NAME                                                 READY   STATUS    RESTARTS   AGE
openshift-builds-operator-6f5c48c6b5-cvp2w           2/2     Running   0          13d
shared-resource-csi-driver-node-gbkqs                2/2     Running   0          13d
shared-resource-csi-driver-webhook-9d9bd48f4-d5ln6   1/1     Running   0          13d
----