// This module is included in the following assembly:
//
// * configuring/configuring-build-runs.adoc

:_mod-docs-content-type: REFERENCE
[id="ob-defining-retention-parameters-in-build-run_{context}"]
= Retention parameters definition for a build run

[role="_abstract"]
Specify how long a completed build run can exist in your `BuildRun` resource. Retention parameters let you clean `BuildRun` instances automatically. In your `BuildRun` custom resource (CR), use:

`retention.ttlAfterFailed`: Duration a failed build run exists
`retention.ttlAfterSucceeded`: Duration a successful build run exists

The following example shows how to define retention parameters in your `BuildRun` CR:
[source,yaml]
----
apiVersion: shipwright.io/v1beta1
kind: BuildRun
metadata:
  name: buidrun-retention-ttl
spec:
  build:
    name: build-retention-ttl
  retention:
    ttlAfterFailed: 10m
    ttlAfterSucceeded: 10m
----
[NOTE]
====
If you have defined a retention parameter in both `BuildRun` and `Build` CRs, the value defined in the `BuildRun` CR overrides the value of the retention parameter defined in the `Build` CR. 
====
