// This module is included in the following assembly:
//
// * configuring/configuring-build-strategies.adoc

:_content-type: REFERENCE
[id="ob-defining-volumes-and-volume-mounts_{context}"]
= Volumes and volume mounts definition

A build strategy includes the definition of volumes and volume mounts. The volumes defined in a build strategy support all of the usual `volumeSource` types. The build steps refer to the volumes by creating a volume mount.

[NOTE]
====
The volume mount defined in build steps allows you to access volumes defined in a `BuildStrategy`, `Build` or `BuildRun` resource.
====

Volumes in build strategy use an `overridable` boolean flag, which is set to `false` by default. If a `Build` or `BuildRun` resource tries to override the volumes defined in a `BuildStrategy` resource, it will fail because the default value of the `overridable` flag is `false`.

The following example shows a `BuildStrategy` resource that defines the `volumes` and `volumeMounts` fields:

[source,yaml]
----
apiVersion: shipwright.io/v1beta1
kind: BuildStrategy
metadata:
  name: buildah
spec:
  steps:
    - name: build
      image: quay.io/containers/buildah:v1.23.3
      # ...
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
  volumes:
    - name: varlibcontainers
      overridable: true
      emptyDir: {}
----
