// This module is included in the following assembly:
//
// * installing/installing-openshift-builds.adoc

:_mod-docs-content-type: PROCEDURE
[id="ob-disabling-shipwrightBuilds-components_{context}"]
= Disable `ShipwrightBuilds` custom resources

[role="_abstract"]
You can disable the `ShipwrightBuilds` custom resource to remove the `shipwright-build-controller` and `shipwright-build-webhook` pods without affecting the Shared Resources CSI driver or the CRD.

.Prerequisites

* You have installed the OpenShift CLI (`oc`).
* You are logged in to the {ocp-product-title} cluster as an administrator.
* You have installed the {builds-title}.

.Procedure

* Run the following command to disable the `shipwright-build-controller` and `shipwright-build-webhook` pods:
+
[source,terminal]
----
$ oc patch openshiftbuild cluster --type=merge -p '{"spec":{"shipwright":{"build":{"state":"Disabled"}}}}'
----
+
This command disables the `shipwright-build-controller` and `shipwright-build-webhook` pods but does not affect the `ShipwrightBuilds` CRD.

.Verification

* Run the following command to verify that the `shipwright-build-controller` and `shipwright-build-webhook` pods are disabled:
+
[source,terminal]
----
$ oc get pods -n openshift-builds
----
+
.Example output
[source,terminal]
----
NAME                                                 READY   STATUS    RESTARTS   AGE
openshift-builds-operator-6f5c48c6b5-cvp2w           2/2     Running   0          13d
shared-resource-csi-driver-node-gbkqs                2/2     Running   0          13d
shared-resource-csi-driver-webhook-9d9bd48f4-d5ln6   1/1     Running   0          13d
----