// This module is included in the following assemblies:
// * about/ob-release-notes.adoc

:_mod-docs-content-type: REFERENCE
[id="ob-release-notes-1-0_{context}"]
= Release notes for {builds-shortname} General Availability 1.0

{builds-shortname} General Availability (GA) 1.0 is now available on {ocp-product-title} 4.14.

[id="new-features-1-0_{context}"]
== New features

The following sections highlight what is new in {builds-shortname} 1.0.

[id="builds-new-features-1-0_{context}"]
=== Builds

* This release supports the `buildah` and `source-to-image` build strategies. The {builds-operator} automatically installs these strategies for use.
+
[NOTE]
====
The `buildpacks` build strategy is currently in link:https://access.redhat.com/support/offerings/devpreview[Developer Preview]. Red Hat plans to make this strategy generally available for use in a future release.
====

* With this release, you can define volume mounts in your `BuildStartegy` resource. When defining a strategy, you can declare volumes which can be shared across build steps and build runs. You can also declare the mount point for the volume which is fixed across all build steps. Volumes can either have a fixed volume source, or an overridable volume source that you can set in a `Build` or `BuildRun` resource.

* With this release, you can embed a complete build specification into your `BuildRun` resource by using the `spec.build.spec` field. By embedding specifications, you can build an image without creating and maintaining a dedicated `Build` resource.

* This release supports automated cleaning of completed build runs after a specific time or when a certain number of build runs is reached. By using retention parameters, you can specify the duration for which a completed build run can exist and the number of succeeded or failed build runs that can exist.

* With this release, you can configure a build by defining the source, build strategy, parameter values, builder or docker file, output, retention parameters, and volumes in a `Build` resource.

* With this release, you can configure a build strategy by defining strategy parameters, system parameters, step resources definitions, annotations, and volumes in a `BuildStrategy` or `ClusterBuildStrategy` resource.

* With this release, you can configure a build run by defining the build reference, build specification, parameter values, service account, output, retention parameters, and volumes.

* With this release, you can monitor your build resources by using build controller metrics.

* With this release, you can add an annotation `build.shipwright.io/referenced.secret: "true"` to a build secret. Based on this annotation, the build controller takes a reconcile action when an event, such as create, update, or delete triggers for the build secret.


[id="cli-new-features-1-0_{context}"]
=== CLI

* With this release, you can create, delete, list, or run a `Build` resource.
* With this release, you can create or list a `BuildRun` resource, or view its logs.
