// This module is included in the following assemblies:
// * about/ob-release-notes.adoc

:_mod-docs-content-type: REFERENCE
[id="ob-release-notes-1-6_{context}"]
= Release notes for {builds-shortname} 1.6

{builds-shortname} 1.6 is now available on {ocp-product-title} .

[id="new-features-1-6_{context}"]
== New features

The following sections highlight what is new in {builds-shortname} 1.5.

Buildpacks Strategy (Generally available)::
With this update, the `buildpacks` strategy feature is now generally available. You can use the following strategies on their corresponding applications:
* `buildpacks` strategy: Quarkus and Go
* `buildpacks-extender` strategy: Node.js and Python

[id="fixed-issues-1-6_{context}"]
== Fixed issues

The following list highlights fixed issues in {builds-shortname} 1.5.

Before this update, the {builds-operator} would automatically install the {pipelines-operator}. However, if an older version of the {pipelines-operator} was already installed, this could cause a conflict because the {builds-shortname} Operator would try to install another instance of the {pipelines-shortname} Operator. With this update, the {builds-shortname} Operator no longer installs the {pipelines-shortname} Operator automatically. You must now install the {pipelines-shortname} Operator before installing the {builds-shortname} Operator.