// Module included in the following assemblies:
//
// * installing/disconnected_install/installing-mirroring-disconnected.adoc
// * updating/updating_a_cluster/updating_disconnected_cluster/mirroring-image-repository.adoc

:_mod-docs-content-type: CONCEPT
[id="installation-oc-mirror-about_{context}"]
= About the oc-mirror plugin v1

You can use the oc-mirror OpenShift CLI (`oc`) plugin to mirror all required {product-title} content and other images to your mirror registry by using a single tool. It provides the following features:

* Provides a centralized method to mirror {product-title} releases, Operators, helm charts, and other images.

* Maintains update paths for {product-title} and Operators.

* Uses a declarative image set configuration file to include only the {product-title} releases, Operators, and images that your cluster needs.

* Performs incremental mirroring, which reduces the size of future image sets.

* Prunes images from the target mirror registry that were excluded from the image set configuration since the previous execution.

* Optionally generates supporting artifacts for OpenShift Update Service (OSUS) usage.

When using the oc-mirror plugin v1, you specify the content to mirror in an image set configuration file. This YAML file allows you to configure which {product-title} releases and Operators your cluster requires, reducing the amount of data to download and transfer. The plugin can also mirror helm charts and additional container images to facilitate workload synchronization onto mirror registries.

The first time you run the oc-mirror plugin v1, it populates your mirror registry with the necessary content for your disconnected cluster installation or update. To continue receiving updates, it's essential to keep your mirror registry updated. Running the oc-mirror plugin v1 with the same configuration as the initial run allows for referencing metadata from the storage backend and downloading only the releases since the last run, providing update paths for {product-title} and Operators, and performing necessary dependency resolution.

[id="installation-oc-mirror-workflow_{context}"]
== High level workflow

The following steps outline the high-level workflow on how to use the oc-mirror plugin v1 to mirror images to a mirror registry:

. Create an image set configuration file.

. Mirror the image set to the target mirror registry by using one of the following workflows:

** Mirror an image set directly to the target mirror registry.

** Mirror an image set to disk, transfer the image set to the target environment, then upload the image set to the target mirror registry.

. Configure your cluster to use the resources generated by the oc-mirror plugin v1.

. Repeat these steps to update your target mirror registry as necessary.

[IMPORTANT]
====
When using the oc-mirror CLI plugin to populate a mirror registry, any further updates to the target mirror registry must be made by using the oc-mirror plugin v1.
====
