// Module included in the following assemblies:
//
// * installing/disconnected_install/installing-mirroring-disconnected.adoc
// * updating/updating_a_cluster/updating_disconnected_cluster/mirroring-image-repository.adoc

:_mod-docs-content-type: PROCEDURE
[id="oc-mirror-creating-image-set-config_{context}"]
= Creating the image set configuration

To use the oc-mirror plugin to mirror image sets, you must create an `ImageSetConfiguration` file. This file specifies the following information:

* The {product-title} releases, Operators, and additional images for mirroring

* Various configuration settings for the oc-mirror plugin v1

.Prerequisites

* You have created a container image registry credentials file. For instructions, see "Configuring credentials that allow images to be mirrored".

.Procedure

. To create a template for the image set configuration, Uuse the `oc mirror init` command and save the informationit to a file called `imageset-config.yaml`. 
+
[source,terminal]
----
$ oc mirror init <--registry <storage_backend> > imageset-config.yaml <1>
----
<1> Replace `example.com/mirror/oc-mirror-metadata` with the location you have created for the storage backend image of oc-mirror on your mirror registry.

. Edit the file and adjust the settings as necessary:
+
[source,yaml,subs="attributes+"]
----
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 4                                                      <1>
storageConfig:                                                      <2>
  registry:
    imageURL: example.com/mirror/oc-mirror-metadata                 <3>
    skipTLS: false
mirror:
  platform:
    channels:
    - name: stable-{product-version}                                             <4>
      type: ocp
    graph: true                                                     <5>
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v{product-version}  <6>
    packages:
    - name: serverless-operator                                     <7>
      channels:
      - name: stable                                                <8>
  additionalImages:
  - name: registry.redhat.io/ubi9/ubi:latest                        <9>
  helm: {}
----
<1> For `archiveSize`, set the maximum size, in GiB, of each file within the image set.
<2> Set the back-end location where you will save the image set metadata. This location can be a registry or local directory. You must specify `storageConfig` values.
<3> Set the registry URL for the storage backend.
<4> Set the channel to retrieve the {product-title} images from.
<5> Add `graph: true` to build and push the graph-data image to the mirror registry. To create OpenShift Update Service (OSUS), you must have the graph-data image. The `graph: true` field generates the `UpdateService` custom resource manifest. The `oc` command-line interface (CLI) can use the `UpdateService` custom resource manifest to create OSUS. For more information, see "About the OpenShift Update Service" for further information.
<6> Set the Operator catalog to retrieve the {product-title} images from. This setting retrieves the latest version of all Operators of this catalog.
<7> Specify which Operator packages to include in the image set. To retrieve all packages in the catalog, remove this field.
<8> Specify which channels of the Operator packages to include in the image set. You must always include the default channel for the Operator package even if you do not use the bundles in that channel. Find the default channel by running the following command: `oc mirror list operators --catalog=<catalog_name> --package=<package_name>`.
<9> Specify any additional images to include in image set.
+
[NOTE]
====
The `graph: true` field also mirrors the `ubi-micro` image along with other mirrored images.
====
+
See "Image set configuration parameters" for the full list of parameters and "Image set configuration examples" for various mirroring use cases.

. Save the updated file.
+
When mirroring content with the oc mirror command , you must have this image set configuration file
