// Module included in the following assemblies:
//
// * installing/disconnected_install/installing-mirroring-disconnected.adoc
// * updating/updating_a_cluster/updating_disconnected_cluster/mirroring-image-repository.adoc

:_mod-docs-content-type: CONCEPT
[id="oc-mirror-updating-registry-about_{context}"]
= Updating your mirror registry content

To upgrade your disconnected OpenShift Container Platform cluster, you must update your mirror registry content with updated content from the Red Hat registries.

You can update your mirror registry content by updating the image set configuration file and mirroring the image set to the mirror registry. The next time that you run the oc-mirror plugin v1, an image set is generated that only contains new and updated images since the previous execution.

While updating the mirror registry, you must take into account the following considerations:

* Images are pruned from the target mirror registry if they are no longer included in the latest image set that was generated and mirrored. Therefore, ensure that you are updating images for the same combination of the following key components so that only a differential image set is created and mirrored:

** Image set configuration: Modify your existing ImageSetConfiguration file to update channels and version selections to align with the desired content in your disconnected registry after completing the mirror operation.

** Target mirror registry: If you specified a top-level namespace for the mirror registry during the initial image set creation, use the same namespace every time you run the oc-mirror plugin v1 for that mirror registry.

** Storage configuration: Retain the exact metadata, either container image or file directory, from your storageConfig across runs on the connected side.

* The images can be pruned in case of disk to mirror or mirror to mirror workflow.

* The generated image sets must be pushed to the target mirror registry in sequence. You can derive the sequence number from the file name of the generated image set archive file.

* Do not delete or modify the metadata image that is generated by the oc-mirror plugin v1.

* If you specified a top-level namespace for the mirror registry during the initial image set creation, then you must use this same namespace every time you run the oc-mirror plugin v1 for the same mirror registry.

For more information about the workflow to update the mirror registry content, see the "High level workflow" section.