// Module included in the following assemblies:
//
// * installing/disconnected_install/installing-mirroring-disconnected-v2.adoc

:_mod-docs-content-type: PROCEDURE
[id="mirror-to-disk-v2_{context}"]
== Mirroring from mirror to disk

You can use the oc-mirror plugin v2 to generate an image set and save the content to disk. You can then transfer the generated image set can to the disconnected environment and mirrored to the target registry.

oc-mirror plugin v2 retrieves the container images from the source specified in the image set configuration and packs them into a tar archive in a local directory.

.Procedure

* Mirror the images from the specified image set configuration to the disk by running the following command:
+
[source,terminal]
----
$ oc mirror -c isc.yaml file://<file_path> --v2 <1>
----
<1> Add the required file path. 

.Verification

. Navigate to the `<file_path>` directory that was generated.
. Verify that the archive files have been generated.

.Next steps

* Configure your cluster to use the resources generated by oc-mirror plugin v2.