// Module included in the following assemblies:
//
// * operators/admin/olm-managing-custom-catalogs.adoc

[id="olm-mirroring-package-manifest-catalog_{context}"]
= Mirroring a Package Manifest Format catalog image

Cluster administrators can mirror a custom Operator catalog image based on the Package Manifest Format into a registry and use a catalog source to load the content onto their cluster. For this example, the procedure uses a custom `redhat-operators` catalog image previously built and pushed to a supported registry.

.Prerequisites

* Workstation with unrestricted network access
* A custom Operator catalog image based on the Package Manifest Format pushed to a supported registry
* `oc` version 4.3.5+
* `podman` version 1.9.3+
* Access to mirror registry that supports link:https://docs.docker.com/registry/spec/manifest-v2-2/[Docker v2-2]
+
[IMPORTANT]
====
The internal registry of the {product-title} cluster cannot be used as the target registry because it does not support pushing without a tag, which is required during the mirroring process.
====
* If you are working with private registries, set the `REG_CREDS` environment variable to the file path of your registry credentials for use in later steps. For example, for the `podman` CLI:
+
[source,terminal]
----
$ REG_CREDS=${XDG_RUNTIME_DIR}/containers/auth.json
----

.Procedure

. The `oc adm catalog mirror` command extracts the contents of your custom Operator catalog image to generate the manifests required for mirroring. You can choose to either:
+
--
* Allow the default behavior of the command to automatically mirror all of the image content to your mirror registry after generating manifests, or
* Add the `--manifests-only` flag to only generate the manifests required for mirroring, but do not actually mirror the image content to a registry yet. This can be useful for reviewing what will be mirrored, and it allows you to make any changes to the mapping list if you only require a subset of the content. You can then use that file with the `oc image mirror` command to mirror the modified list of images in a later step.
--
+
On your workstation with unrestricted network access, run the following command:
+
[source,terminal]
----
$ oc adm catalog mirror \
    <registry_host_name>:<port>/olm/redhat-operators:v1 \ <.>
    <registry_host_name>:<port> \ <.>
    [-a ${REG_CREDS}] \ <.>
    [--insecure] \ <.>
    [--index-filter-by-os='<platform>/<arch>'] \ <.>
    [--manifests-only] <.>
----
<.> Specify your Operator catalog image.
<.> Specify the fully qualified domain name (FQDN) for the target registry.
<.> Optional: If required, specify the location of your registry credentials file.
<.> Optional: If you do not want to configure trust for the target registry, add the `--insecure` flag.
<.> Optional: Specify which platform and architecture of the catalog image to select when multiple variants are available. Images are passed as `'<platform>/<arch>[/<variant>]'`. This does not apply to images referenced by the catalog image. Valid values are `linux/amd64`, `linux/ppc64le`, and `linux/s390x`.
<.> Optional: Only generate the manifests required for mirroring and do not actually mirror the image content to a registry.
+
.Example output
[source,terminal]
----
using database path mapping: /:/tmp/190214037
wrote database to /tmp/190214037
using database at: /tmp/190214037/bundles.db <1>
...
----
<1> Temporary database generated by the command.
+
After running the command, a `manifests-<index_image_name>-<random_number>/` directory is created in the current directory and generates the following files:
+
--
* The `catalogSource.yaml` file is a basic definition for a `CatalogSource` object that is pre-populated with your catalog image tag and other relevant metadata. This file can be used as is or modified to add the catalog source to your cluster.
* The `imageContentSourcePolicy.yaml` file defines an `ImageContentSourcePolicy` object that can configure nodes to translate between the image references stored in Operator manifests and the mirrored registry.
+
[NOTE]
====
If your cluster uses an `ImageContentSourcePolicy` object to configure repository mirroring, you can use only global pull secrets for mirrored registries. You cannot add a pull secret to a project.
====
* The `mapping.txt` file contains all of the source images and where to map them in the target registry. This file is compatible with the `oc image mirror` command and can be used to further customize the mirroring configuration.
--

. If you used the `--manifests-only` flag in the previous step and want to mirror only a subset of the content:

.. Modify the list of images in your `mapping.txt` file to your specifications. If you are unsure of the exact names and versions of the subset of images you want to mirror, use the following steps to find them:

... Run the `sqlite3` tool against the temporary database that was generated by the `oc adm catalog mirror` command to retrieve a list of images matching a general search query. The output helps inform how you will later edit your `mapping.txt` file.
+
For example, to retrieve a list of images that are similar to the string `clusterlogging.4.3`:
+
[source,terminal]
----
$ echo "select * from related_image \
    where operatorbundle_name like 'clusterlogging.4.3%';" \
    | sqlite3 -line /tmp/190214037/bundles.db <1>
----
<1> Refer to the previous output of the `oc adm catalog mirror` command to find the path of the database file.
+
.Example output
[source,terminal]
----
image = registry.redhat.io/openshift4/ose-logging-kibana5@sha256:aa4a8b2a00836d0e28aa6497ad90a3c116f135f382d8211e3c55f34fb36dfe61
operatorbundle_name = clusterlogging.4.3.33-202008111029.p0

image = registry.redhat.io/openshift4/ose-oauth-proxy@sha256:6b4db07f6e6c962fc96473d86c44532c93b146bbefe311d0c348117bf759c506
operatorbundle_name = clusterlogging.4.3.33-202008111029.p0
...
----

... Use the results from the previous step to edit the `mapping.txt` file to only include the subset of images you want to mirror.
+
For example, you can use the `image` values from the previous example output to find that the following matching lines exist in your `mapping.txt` file:
+
.Matching image mappings in `mapping.txt`
[source,txt]
----
registry.redhat.io/openshift4/ose-logging-kibana5@sha256:aa4a8b2a00836d0e28aa6497ad90a3c116f135f382d8211e3c55f34fb36dfe61=<registry_host_name>:<port>/openshift4-ose-logging-kibana5:a767c8f0
registry.redhat.io/openshift4/ose-oauth-proxy@sha256:6b4db07f6e6c962fc96473d86c44532c93b146bbefe311d0c348117bf759c506=<registry_host_name>:<port>/openshift4-ose-oauth-proxy:3754ea2b
----
+
In this example, if you only want to mirror these images, you would then remove all other entries in the `mapping.txt` file and leave only the above two lines.

.. Still on your workstation with unrestricted network access, use your modified `mapping.txt` file to mirror the images to your registry using the `oc image mirror` command:
+
[source,terminal]
----
$ oc image mirror \
    [-a ${REG_CREDS}] \
    --filter-by-os='.*' \
    -f ./manifests-redhat-operators-<random_number>/mapping.txt
----
+
[WARNING]
====
If the `--filter-by-os` flag remains unset or set to any value other than `.*`, the command filters out different architectures, which changes the digest of the manifest list, also known as a _multi-arch image_. The incorrect digest causes deployments of those images and Operators on disconnected clusters to fail.
====

. Create the `ImageContentSourcePolicy` object:
+
[source,terminal]
----
$ oc create -f ./manifests-redhat-operators-<random_number>/imageContentSourcePolicy.yaml
----

You can now create a `CatalogSource` object to reference your mirrored content.
