// Module included in the following assemblies:
//
// * operators/admin/olm-creating-policy.adoc

:_mod-docs-content-type: REFERENCE
[id="olm-policy-fine-grained-permissions_{context}"]
= Fine-grained permissions

[role="_abstract"]
Operator Lifecycle Manager (OLM) uses the service account specified in the Operator group to restrict an Operator to a designated namespace. During Operator installation and updates, OLM uses this service account to manage cluster resources.

To restrict Operators to a designated namespace, grant the following permissions to the service account:

* `ClusterServiceVersion`
* `Subscription`
* `Secret`
* `ServiceAccount`
* `Service`
* `ClusterRole` and `ClusterRoleBinding`
* `Role` and `RoleBinding`

[NOTE]
====
The following role configuration is a generic example. Your Operator might require additional rules.
====

[source,yaml]
----
kind: Role
rules:
- apiGroups: ["operators.coreos.com"]
  resources: ["subscriptions", "clusterserviceversions"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["services", "serviceaccounts"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "watch", "get", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "watch", "get", "create", "update", "patch", "delete"]
----

Set permissions in the `rules.apiGroups` fields for `apps` and core `""` resources so the service account can create deployments and pods.

If an Operator specifies a pull secret, add the following permissions:

[source,yaml]
----
kind: ClusterRole
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
kind: Role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch"]
----

The `ClusterRole` object allows the service account to retrieve secrets from the OLM namespace.
