// Module included in the following assemblies:
//
// * disconnected/installing-mirroring-installation-images.adoc

:_mod-docs-content-type: REFERENCE
[id="olm-mirror-catalog-prerequisites_{context}"]
= Prerequisites

[role="_abstract"]
Mirroring Operator catalogs for use with disconnected clusters has the following prerequisites:

* Workstation with unrestricted network access.
* `podman` version 1.9.3 or later.
* If you want to filter, or _prune_, an existing catalog and selectively mirror only a subset of Operators, see "Installing the opm CLI" and "Updating or filtering a file-based catalog image".
ifndef::openshift-origin[]
* If you want to mirror a Red Hat-provided catalog, run the following command on your workstation with unrestricted network access to authenticate with `registry.redhat.io`:
+
[source,terminal]
----
$ podman login registry.redhat.io
----
endif::[]
* Access to a mirror registry that supports Docker v2-2.
* On your mirror registry, decide which repository, or namespace, to use for storing mirrored Operator content. For example, you might create an `olm-mirror` repository.
* If your mirror registry does not have internet access, connect removable media to your workstation with unrestricted network access.
* If you are working with private registries, including `registry.redhat.io`, set the `REG_CREDS` environment variable to the file path of your registry credentials for use in later steps. For example, for the `podman` CLI:
+
[source,terminal]
----
$ REG_CREDS=${XDG_RUNTIME_DIR}/containers/auth.json
----
