// Module included in the following assemblies:
//
// * applications/operators/olm-adding-operators-to-cluster.adoc

[id='olm-installing-from-operatorhub-using-web-console-{context}']
= Installing from the OperatorHub using the web console

This procedure uses the etcd Operator as an example to install and subscribe to
an Operator from the OperatorHub using the {product-title} web console.

.Prerequisites

- Access to an {product-title} cluster using an account with `cluster-admin`
permissions.

.Procedure

. Navigate in the web console to the *Catalog → Operator Hub* page.

. Choose the Operator you want to install from the list of available Operators (*etcd* for this example), and click *Install*. A pop-up window appears, warning you that you are installing a Community Operator.
+
[NOTE]
====
This Operator will be available under the *Red Hat* category in the GA release.
====
. Select *Continue* to acknowledge the Show Community Operator warning. The Install page appears.

. Read the information about the Operator and click *Install*.

. On the *Create Operator Subscription* page, select:
.. *A specific namespace on the cluster* under Installation Mode to choose a namespace in which the Operator will be available (*default* installs to all namespaces)
.. An *Update Channel* (if more than one is available)
.. *Automatic* or *Manual* Approval Strategy, as described earlier

. Select the *Subscribe* button to make the Operator available to the selected namespaces on this {product-title} cluster.

. Select *Catalog → Installed Operators* page to verify that the *etcd*
ClusterServiceVersion (CSV) eventually shows up and its *Status* ultimately
resolves to *InstallSucceeded*.
+
If it does not, switch to the *Catalog → Operator Management* page and inspect
the *Operator Subscriptions* and *Install Plans* tabs for any failure or errors
under *Status*. Then, check the logs in any Pods in the *openshift-operators*
project (on the *Workloads → Pods* page) that are reporting issues to
troubleshoot further.
