// Module included in the following assemblies:
// * lightspeed-docs-main/configure/ols-configuring-openshift-lightspeed.adoc

:_mod-docs-content-type: PROCEDURE
[id="ols-enabling-default-mcp-server_{context}"]
= Enabling the default MCP server

Enable the default MCP server so that the large language model (LLM) can provide answers to questions about Kubernetes objects that reside in your {ocp-short-name} cluster.

.Prerequisites

* You have installed the {ols-long} Operator.

* You have configured a large language model provider.

* You have deployed the {ols-long} service.

.Procedure

. Open the {ols-long} `OLSconfig` custom resource (CR) file by running the following command:
+
[source,terminal]
----
$ oc edit olsconfig cluster
----

. Add `MCPServer` to the `spec.ols.featureGates` specification file and include the MCP server information.
+
[source,yaml]
----
apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
  namespace: openshift-lightspeed
spec:
  llm:
    providers:
    - credentialsSecretRef:
        name: azure-credential
      apiVersion: 2024-12-01-preview
      models:
      - name: o3
      name: azure_openai
      deploymentName: 4o-jun24
      type: azure_openai
      url: "https://ols-test.openai.azure.com/"
  ols:
    introspectionEnabled: true
    defaultModel: o3
    defaultProvider: azure_openai
----

. Click *Save*. 
+
The save operation saves the file and applies the changes so that the MCP server is available to the {ols-long} service.