// This module is included in the following assemblies:
// * secure/using-tekton-chains-for-openshift-pipelines-supply-chain-security.adoc

:_mod-docs-content-type: PROCEDURE
[id="enabling-tekton-chains-to-operate-only-in-selected-namespaces_{context}"]
= Enable {tekton-chains} to operate only in selected namespaces

[role="_abstract"]
By default, the {tekton-chains} controller monitors resources in all namespaces. You can customize {tekton-chains} to run only in specific namespaces, which provides granular control over its operation.

.Prerequisites
* You logged in to your {OCP} cluster with `cluster-admin` privileges.

.Procedure

* In the `TektonConfig` CR, in the `chain` section, add the `--namespace=` argument to contain the namespaces that the controller should watch.
+
The following example shows the configuration for the {tekton-chains} controller to only watch resources within the `dev` and `test` namespaces, filtering `PipelineRun` and `TaskRun` objects so:
+
[source,yaml]
----
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  chain:
    disabled: false
    options:
      deployments:
        tekton-chains-controller:
          spec:
            template:
              spec:
                containers:
                - args:
                  - --namespace=dev, test
                  name: tekton-chains-controller
----
+
`--namespace`:: If you do not give the `--namespace` argument or leave it empty, the controller watches all namespaces by default.

.Verification

* Verify that the controller is configured to watch only the specified namespaces:
+
[source,bash]
----
$ oc get deployment tekton-chains-controller -n openshift-pipelines -o jsonpath='{.spec.template.spec.containers[?(@.name=="tekton-chains-controller")].args}'
----
+
The output displays the `--namespace=` argument with the configured namespaces.

[role="_additional-resources"]
.Additional resources

* xref:configuring-tekton-chains_{context}[Configuring {tekton-chains}]
* xref:supported-parameters-tekton-chains-configuration_{context}[Supported parameters for {tekton-chains} configuration]
