// Module included in the following assemblies:
//
// * cli_reference/tkn_cli/op-tkn-references.adoc

[id="op-tkn-pipeline-run_{context}"]
= Pipeline run commands


== pipelinerun
Manage pipeline runs.

.Example: Display help
[source,terminal]
----
$ tkn pipelinerun -h
----

== pipelinerun cancel
Cancel a pipeline run.

.Example: Cancel the `mypipelinerun` pipeline run from a namespace
[source,terminal]
----
$ tkn pipelinerun cancel mypipelinerun -n myspace
----

== pipelinerun delete
Delete a pipeline run.

.Example: Delete pipeline runs from a namespace
[source,terminal]
----
$ tkn pipelinerun delete mypipelinerun1 mypipelinerun2 -n myspace
----

.Example: Delete all pipeline runs from a namespace, except the five most recently executed pipeline runs
[source,terminal]
----
$ tkn pipelinerun delete -n myspace --keep 5 <1>
----
<1> Replace `5` with the number of most recently executed pipeline runs you want to retain.

.Example: Delete all pipelines
[source,terminal]
----
$ tkn pipelinerun delete --all
----

[NOTE]
====
Starting with {pipelines-title} 1.6, the `tkn pipelinerun delete --all` command does not delete any resources that are in the `RUNNING` state.
====

== pipelinerun describe
Describe a pipeline run.

.Example: Describe the `mypipelinerun` pipeline run in a namespace
[source,terminal]
----
$ tkn pipelinerun describe mypipelinerun -n myspace
----

== pipelinerun list
List pipeline runs.

.Example: Display a list of pipeline runs in a namespace
[source,terminal]
----
$ tkn pipelinerun list -n myspace
----

== pipelinerun logs
Display the logs of a pipeline run.

.Example: Display the logs of the `mypipelinerun` pipeline run with all tasks and steps in a namespace
[source,terminal]
----
$ tkn pipelinerun logs mypipelinerun -a -n myspace
----
