// Module included in the following assemblies:
//
// *  cli_reference/tkn_cli/op-tkn-reference.adoc

[id="op-tkn-hub-interaction_{context}"]
= Hub interaction commands

Interact with Tekton Hub.

== hub
Interact with hub.

.Example: Display help
[source,terminal]
----
$ tkn hub -h
----

.Example: Interact with hub API server
[source,terminal]
----
$ tkn hub --api-server https://api.hub.tekton.dev
----

[NOTE]
====
For each command examples given below, you can get the corresponding sub-commands and flags by executing `tkn hub <command> --help`.
====

== hub downgrade
Downgrade an installed resource

.Example: Downgrade an installed resource
[source,terminal]
----
$ tkn hub downgrade
----

== hub get
Get resource manifest by its name, kind, catalog, and version.

.Example: Get resource manifest
[source,terminal]
----
$ tkn hub get
----

== hub info
Display information about a resource by its name, kind, catalog, and version.

.Example: Display resource information
[source,terminal]
----
$ tkn hub info
----

== hub install
Install a resource from a catalog by its kind, name, and version.

.Example: Install a resource
[source,terminal]
----
$ tkn hub install
----

== hub reinstall
Reinstall a resource by its kind and name.

.Example: Reinstall a resource
[source,terminal]
----
$ tkn hub reinstall
----

== hub search
Search a resource by a combination of name, kind, and tags.

.Example: Search a resource
[source,terminal]
----
$ tkn hub search
----

== hub upgrade
Upgrade an installed resource.

.Example: Upgrade an installed resource
[source,terminal]
----
$ tkn hub upgrade
----
