// Module included in the following assemblies:
//
// * upgrading/upgrade-operator.adoc
// * cloud_service/upgrade-cloudsvc-operator.adoc
:_mod-docs-content-type: CONCEPT
[id="operator-upgrade-change-subscription-channel_{context}"]
= Changing the subscription channel

ifeval::["{context}" == "upgrade-cloudsvc-operator"]
:cloud-svc:
endif::[]

[role="_abstract"]
You can change the update channel for the {product-title-short} Operator by using the {ocp} web console or by using the command line. For upgrading to {product-title-short} 4.0 from {product-title-short} 3.74, you must change the update channel.

[IMPORTANT]
====
ifndef::cloud-svc[]
* You must change the subscription channel for all clusters where you installed the {product-title-short} Operator, including Central and all secured clusters.
* If you use Kubernetes, enter `kubectl` instead of `oc`.
endif::[]
ifdef::cloud-svc[]
* You must change the subscription channel for all secured clusters where you installed the {product-title-short} Operator.
* If you use Kubernetes, enter `kubectl` instead of `oc`.
endif::[]
====

ifeval::["{context}" == "upgrade-cloudsvc-operator"]
:!cloud-svc:
endif::[]