// Module included in the following assemblies:
//
// * adding_service_cluster/available-services.adoc
// * adding_service_cluster/rosa-available-services.adoc

[id="osd-rhoam_{context}"]
= Red Hat OpenShift API Management

The Red Hat OpenShift API Management (OpenShift API Management) service is available as an add-on to your {product-title} cluster. OpenShift API Management is a managed API traffic control and API program management solution that is based on the 3scale API Management platform.
OpenShift API Management includes an implementation of the Red Hat Single Sign-On to secure and protect your API and for API Management and not as a company-wide SSO solution.

This free OpenShift API Management entitlement tier provides:

* Availability to any cluster that meets the resource requirements listed in the {product-title} service definition.
* Full production-level support.
* No time limits - this is not a trial.
* 100 K quota, or calls per day. Customers have the option to pay for a OpenShift API Management subscription with higher quotas.

.Additional resources

* For more information, see the link:https://access.redhat.com/documentation/en-us/red_hat_openshift_api_management[Red Hat OpenShift API Management] documentation.
