// Module included in the following assemblies:
//
// * support/troubleshooting/troubleshooting-osd-gcp-cluster-deployment.adoc

:_mod-docs-content-type: CONCEPT
[id="osd-on-gcp-troubleshoot-cluster-install_{context}"]
= Troubleshooting {product-title} on {gcp-short} installation error codes

The following table lists {product-title} on {gcp-first} installation error codes and what you can do to resolve these errors.

.{product-title} on {gcp-short} installation error codes
[options="header",cols="3"]
|===
| Error code | Description | Resolution

| OCM3022
| Invalid {gcp-short} project ID.
| Verify the project ID in the Google cloud console and retry cluster creation.

| OCM3023
| {gcp-short} instance type not found.
| Verify the instance type and retry cluster creation.

For more information about {product-title} on {gcp-short} instance types, see _{gcp-full} instance types_ in the _Additional resources_ section.

| OCM3024
| {gcp-short} precondition failed.
| Verify the organization policy constraints and retry cluster creation.

For more information about organization policy constraints, see link:https://cloud.google.com/resource-manager/docs/organization-policy/org-policy-constraints[Organization policy constraints].

| OCM3025
| {gcp-short} SSD quota limit exceeded.
| Check your available persistent disk SSD quota either in the {gcp-full} console or in the `gcloud` CLI. There must be at least 896 GB of SSD available. Increase the SSD quota limit and retry cluster creation.

For more information about managing persistent disk SSD quota, see link:https://cloud.google.com/compute/resource-usage[Allocation quotas].

| OCM3026
| {gcp-short} compute quota limit exceeded.
| Increase your CPU compute quota and retry cluster installation.

For more information about the CPU compute quota, see link:https://cloud.google.com/compute/quotas-limits[Compute Engine quota and limits overview].

| OCM3027
| {gcp-short} service account quota limit exceeded.
| Ensure your quota allows for additional unused service accounts. Check your current usage for quotas in your {gcp-short} account and try again.

For more information about managing your quotas, see link:https://cloud.google.com/docs/quotas/view-manage#managing_your_quota_console[Manage your quotas using the console].

|===