// Module included in the following assemblies:
//
// * operators/operator_sdk/osdk-scorecard.adoc

:_mod-docs-content-type: PROCEDURE
[id="osdk-scorecard-run_{context}"]
= Running the scorecard tool

A default set of Kustomize files are generated by the Operator SDK after running the `init` command. The default `bundle/tests/scorecard/config.yaml` file that is generated can be immediately used to run the scorecard tool against your Operator, or you can modify this file to your test specifications.

.Prerequisites

* Operator project generated by using the Operator SDK

.Procedure

. Generate or regenerate your bundle manifests and metadata for your Operator:
+
[source,terminal]
----
$ make bundle
----
+
This command automatically adds scorecard annotations to your bundle metadata, which is used by the `scorecard` command to run tests.

. Run the scorecard against the on-disk path to your Operator bundle or the name of a bundle image:
+
[source,terminal]
----
$ operator-sdk scorecard <bundle_dir_or_image>
----
