// Module included in the following assemblies:
//
// * operators/operator_sdk/osdk-upgrading-projects.adoc

:osdk_ver: v1.10.1
:osdk_ver_n1: v1.8.0

[id="osdk-upgrading-v180-to-v1101_{context}"]
= Upgrading projects for Operator SDK {osdk_ver}

The following upgrade steps must be performed to upgrade an existing Operator project for compatibility with {osdk_ver}.

.Prerequisites

- Operator SDK {osdk_ver} installed
- Operator project that was previously created or maintained with Operator SDK {osdk_ver_n1}

.Procedure

* For Ansible-based Operator projects, update the command in the `Set pull policy` section of the `molecule/default/prepare.yml` file:
+
.`molecule/default/prepare.yml` file diff
[%collapsible]
====
[source,diff]
----
     - name: Set pull policy
-      command: '{{ "{{ kustomize }}" }} edit add patch pull_policy/{{ "{{ operator_pull_policy }}" }}.yaml'
+      command: '{{ "{{ kustomize }}" }} edit add patch --path pull_policy/{{ "{{ operator_pull_policy }}" }}.yaml'
----
====
+
Ansible projects are now scaffolded with Kustomize version 3.8.7. This version of Kustomize requires that the path to patch files be provided with the `--path` flag in the `add patch` command.

Your Operator project is now compatible with Operator SDK {osdk_ver}.

:!osdk_ver:
:!osdk_ver_n1:
