// Module included in the following assemblies:
//
// * operators/operator_sdk/golang/osdk-golang-tutorial.adoc
// * operators/operator_sdk/ansible/osdk-ansible-tutorial.adoc
// * operators/operator_sdk/helm/osdk-helm-tutorial.adoc
// * operators/operator_sdk/java/osdk-java-tutorial.adoc

ifeval::["{context}" == "osdk-golang-tutorial"]
:golang:
:type: Go
:app: memcached
endif::[]
ifeval::["{context}" == "osdk-ansible-tutorial"]
:ansible:
:type: Ansible
:app: memcached
endif::[]
ifeval::["{context}" == "osdk-helm-tutorial"]
:helm:
:type: Helm
:app: nginx
endif::[]
ifeval::["{context}" == "osdk-java-tutorial"]
:java:
:type: Java
:app: memcached
endif::[]

[id="osdk-project-file_{context}"]
= PROJECT file

Among the files generated by the `operator-sdk init` command is a Kubebuilder `PROJECT` file. Subsequent `operator-sdk` commands, as well as `help` output, that are run from the project root read this file and are aware that the project type is {type}. For example:

[source,yaml]
ifdef::golang[]
----
domain: example.com
layout:
- go.kubebuilder.io/v3
projectName: memcached-operator
repo: github.com/example-inc/memcached-operator
version: "3"
plugins:
  manifests.sdk.operatorframework.io/v2: {}
  scorecard.sdk.operatorframework.io/v2: {}
  sdk.x-openshift.io/v1: {}
----
endif::[]
ifdef::ansible[]
----
domain: example.com
layout:
- ansible.sdk.operatorframework.io/v1
plugins:
  manifests.sdk.operatorframework.io/v2: {}
  scorecard.sdk.operatorframework.io/v2: {}
  sdk.x-openshift.io/v1: {}
projectName: memcached-operator
version: "3"
----
endif::[]
ifdef::helm[]
----
domain: example.com
layout:
- helm.sdk.operatorframework.io/v1
plugins:
  manifests.sdk.operatorframework.io/v2: {}
  scorecard.sdk.operatorframework.io/v2: {}
  sdk.x-openshift.io/v1: {}
projectName: nginx-operator
resources:
- api:
    crdVersion: v1
    namespaced: true
  domain: example.com
  group: demo
  kind: Nginx
  version: v1
version: "3"
----
endif::[]
ifdef::java[]
----
domain: example.com
layout:
- quarkus.javaoperatorsdk.io/v1-alpha
projectName: memcached-operator
version: "3"
----
endif::[]

ifeval::["{context}" == "osdk-golang-tutorial"]
:!golang:
:!type:
:!app:
endif::[]
ifeval::["{context}" == "osdk-ansible-tutorial"]
:!ansible:
:!type:
:!app:
endif::[]
ifeval::["{context}" == "osdk-helm-tutorial"]
:!helm:
:!type:
:!app:
endif::[]
ifeval::["{context}" == "osdk-java-tutorial"]
:!java:
:!type:
:!app:
endif::[]