// Module included in the following assemblies:
//
// * service-mesh-docs-main/install/ossm-cert-manager-assembly.adoc

:_mod-docs-content-type: PROCEDURE
[id="verifying-cert-manager-installation_{context}"]
= Verifying cert-manager installation

//TP1 content influx. Title, etc may change.
//Content is very similar to 2.x content
//all kinds of formatting things to fix. want to see if a build will generate to have a look, and see how it fits structurally with the IA.

You can use the sample `httpbin` service and `sleep` application to check communication between the workloads. You can also check the workload certificate of the proxy to verify that the cert-manager tool is installed correctly.

.Procedure

. Create the `sample` namespace by running the following command:
+
[source, terminal]
----
$ oc new-project sample
----

. Find your active Istio revision by running the following command:
+
[source, terminal]
----
$ oc get istiorevisions
----

. Add the injection label for your active revision to the `sample` namespace by running the following command:
+
[source, terminal]
----
$ oc label namespace sample istio.io/rev=<your-active-revision-name> --overwrite=true
----

. Deploy the sample `httpbin` service by running the following command:
+
[source, terminal]
----
$ oc apply -n sample -f https://raw.githubusercontent.com/openshift-service-mesh/istio/refs/heads/master/samples/httpbin/httpbin.yaml
----

. Deploy the sample `sleep` application by running the following command:
+
[source, terminal]
----
$ oc apply -n sample -f https://raw.githubusercontent.com/istio/istio/refs/heads/master/samples/sleep/sleep.yaml
----

. Wait for both applications to become ready by running the following command:
+
[source, terminal]
----
$ oc rollout status -n sample deployment httpbin sleep
----

. Verify that `sleep` application can access the `httpbin` service by running the following command:
+
[source, terminal]
----
$ oc exec "$(oc get pod -l app=sleep -n sample \
     -o jsonpath={.items..metadata.name})" -c sleep -n sample -- \
     curl http://httpbin.sample:8000/ip -s -o /dev/null \
     -w "%{http_code}\n"
----
+
.Example of a successful output
[source, terminal]
----
200
----

. Run the following command to print the workload certificate for the `httpbin` service and verify the output:
+
[source, terminal]
----
$ istioctl proxy-config secret -n sample $(oc get pods -n sample -o jsonpath='{.items..metadata.name}' --selector app=httpbin) -o json | jq -r '.dynamicActiveSecrets[0].secret.tlsCertificate.certificateChain.inlineBytes' | base64 --decode | openssl x509 -text -noout
----
+
.Example output
[source, terminal]
----
...
Issuer: O = cert-manager + O = cluster.local, CN = istio-ca
...
X509v3 Subject Alternative Name:
  URI:spiffe://cluster.local/ns/sample/sa/httpbin
----