// Module included in the following assemblies:

// * service-mesh-docs-main/migrating/checklists/ossm-migrating-cluster-wide-assembly.adoc

:_mod-docs-content-type: Concept
[id="ossm-about-cluster-wide-migration_{context}"]
= About cluster-wide migration

[NOTE]
====
THIS CONTENT IS A VERY EARLY DRAFT THAT IS UNDERGOING A VARIETY OF CHANGES, INCLUDING STYLE CHANGES
====

There are three ways to migrate from OSSM 2 to 3:

* Migrating to 3.0 using the `istio.io/rev` label
* Migrating to 3.0 using the `istio-injection=enabled` label
* Simple migration using `istio-injection=enabled` label, which should not be used in a production environment.

During the migration process, there are two cluster-wide Istio control planes running in the same namespace. One control plane is associated with the 2.6 deployment and the other one is associated with the 3.0 deployment. Therefore, it is necessary to plan the migration steps in advance in order to avoid possible conflicts between the two control planes.

Several conditions must be true in order to successfully complete the migration.

== Control planes and root certificate

During the migration, the control plane associated with the 2.6 installation and the control plane associated with the 3.0 installation must share the same root certificate. This can be achieved by installing the 3.0 control plane to the same namespace as 2.6 control plane. The migration procedure below shows how to verify the root cert is shared.

== Control planes and namespace access

Both control planes must have access to all namespaces in the mesh.

During the migration, some proxies will be controlled by the 3.0 control plane while other proxies will remain controlled by the 2.6 control plane. To ensure that mesh communication works, both control planes must be aware of the same set of services. In the 3.0 mesh, Service discovery is provided by the `istiod`, which runs in the control plane namespace. 

You must verify that:

* No Network Policies block the traffic between `istiod` and proxies for both control planes.

OpenShift Service Mesh 2.6 is by default managing Network Policies which would be blocking traffic for 3.0 control plane. In the pre-migration checklist, we instruct users to disable this feature but users can still decide to re-create those Network Policies manually. In that case, newly created Network Policies must allow the traffic for both control planes. One example of problematic Network policy is the usage of maistra.io/member-of label which will be removed automatically when a dataplane namespace is migrated to 3.0. See Migration of Network Policies documentation for details.
+
[NOTE]
====
Incorrectly configured Network Policies will cause traffic disruptions and might be difficult to debug. Pay increased attention when creating Network Policies. See Network Policy migration for more details.
====

* Ensure that the `discoverySelectors` defined in your OpenShift Service Mesh 3.0 {istio} resource match the namespaces that comprise the OpenShift Service Mesh 2.6 mesh. You may have to add additional labels onto your OpenShift Service Mesh 2.6 application namespaces to ensure that they are captured by the OpenShift Service Mesh 3.0 Istio `discoverySelectors`. See Scoping the service mesh with DiscoverySelectors

== Control planes and sidecar injection

Oly one control plane will try to perform sidecar injection. This can be achieved by correct use of injection labels. Please see Installing the Sidecar for details.
+
[NOTE]
====
Due to specific behavior of OpenShift Service Mesh 2.6 it's necessary to disable 2.6 injector when migrating the data plane namespace. We will use maistra.io/ignore-namespace: "true" label in this guide.
====

== Additional considerations

For OpenShift Service Mesh 3.0, you must decide if you want to use the `istio.io/rev` or `istio-injection` labels to configure sidecar injection. See Installing the Sidecar for a full explanation of the two labels for configuring sidecar injection.

In the OpenShift Service Mesh 2.6 installation, the way member selection was configured in the `ServiceMeshMemberRoll` resource may also impact the choice of injection labels used with OpenShift Service Mesh 3.0.

By default, in a 2.6 installation, the `spec.memberSelectors` in the `ServiceMeshMemberRoll` resource is configured to match the `istio-injection=enabled` label. As a result, and all of the data plane namespaces in a 2.6 installation have the `istio-injection=enabled` label applied. If you are using the default 2.6 installation settings, you can keep using the label or switch to the `istio.io/rev` label.

If the `spec.memberSelectors` in the `ServiceMeshMemberRoll` resource is not configured to match the `istio-injection=enabled` label and the 2.6 data plane namespaces use a different label you must add add either the `istio.io/rev` or `istio-injection` label during the migration. The labels defined in the `spec.memberSelectors` in the `ServiceMeshMemberRoll `resource have no effect on injection in the OpenShift Service Mesh 3 installation

In the 2.6 installation, if projects were added to the mesh using either label selectors or by using the `ServiceMeshMember` resource you must add either the `istio.io/rev` or `istio-injection` label during the migration.
