// Module included in the following assemblies:
//
// * service-mesh-docs-main/kiali/ossm-kiali-assembly.adoc

:_mod-docs-content-type: PROCEDURE
[id="ossm-config-otel-kiali_{context}"]
= Configuring {DTProductName} with {KialiProduct}

After {KialiProduct} is integrated with {DTProductName}, you can view distributed traces in the Kiali console. Viewing these traces can provide insight into the communication between services within the service mesh, helping you understand how requests are flowing through your system and where potential issues might be.

.Prerequisites

* You installed {SMProductName}.

* You configured {DTShortName} with {SMProductName}.

.Procedure

. Update the `Kiali` resource `spec` configuration for tracing:
+
.Example `Kiali` resource `spec` configuration for tracing
[source,yaml]
----
spec:
  external_services:
    tracing:
      enabled: true #<1>
      provider: tempo
      use_grpc: false
      in_cluster_url: http://tempo-sample-query-frontend.tempo:3200
      url: https://tempo-sample-query-frontend-tempo.apps-crc.testing #<2>
----
<1> Enable tracing.
<2> The {ocp-short-name} route for Jaeger UI must be created in the Tempo namespace. You can either manually create it for the `tempo-sample-query-frontend` service, or update the `Tempo` custom resource with `.spec.template.queryFrontend.jaegerQuery.ingress.type: route`.

. Save the updated `spec` in `kiali_cr.yaml`.

. Run the following command to apply the configuration:
+
[source, terminal]
----
$ oc patch -n istio-system kiali kiali --type merge -p "$(cat kiali_cr.yaml)"
----
+
.Example output:
+
[source, terminal]
----
 kiali.kiali.io/kiali patched
----

.Verification

. Run the following command to get the Kiali route:
+
[source, terminal]
----
$ oc get route kiali ns istio-system
----

. Navigate to the Kiali UI.

. Navigate to *Workload* → *Traces* tab to see traces in the Kiali UI.

//Notes 10/30/2024:
//Grafana info removed for TP1. Requires further discussion for GA on the best user path, in addition to changes coming from Tempo that may or may not be ready when OSSM 3.0 GA's.

//Note for later: there are things in here, like Kiali UI, that may need attributes. Attributes will be updated prior to GA.
//Note that "Kiali UI" is not the same as "Kiali Operator provided by Red Hat", and there currently is only 1 attribute related to Kiali, and it is for "Kiali Operator provided by Red Hat".
//