// Module included in the following assemblies:

// * service-mesh-docs-main/install/ossm-istio-ambient-mode.adoc

:_mod-docs-content-type: CONCEPT
[id="ossm-about-istio-ambient-mode_{context}"]
= About Istio ambient mode

To understand the {istio} ambient mode architecture, see the following definitions:

ZTunnel proxy:: A per-node proxy that manages secure, transparent Transmission Control Protocol (TCP) connections for all workloads on the node. It operates at Layer 4 (L4), offloading mutual Transport Layer Security (mTLS) and L4 policy enforcement from application pods.

Waypoint proxy:: An optional proxy that runs per service account or namespace to provide advanced Layer 7 (L7) features such as traffic management, policy enforcement, and observability. You can apply L7 features  selectively to avoid the overhead of sidecars for every service.

Istio CNI plugin:: Redirects traffic to the Ztunnel proxy on each node, enabling transparent interception without requiring modifications to application pods.

{Istio} ambient mode offers the following benefits:

* *Simplified operations* that remove the need to manage sidecar injection, reducing the complexity of mesh adoption and operations.

* *Reduced resource consumption* with a per-node Ztunnel proxy that provides L4 service mesh features and an optional `waypoint` proxy that reduces resource overhead per pod.

* *Incremental adoption* that enables workloads to join the mesh with the L4 features like mutual Transport Layer Security (mTLS) and basic policies with optional `waypoint` proxies added later to use L7 service mesh features, such as HTTP(L7) traffic management.
+
[NOTE]
====
The L7 features require deploying `waypoint` proxies, which introduces minimal additional overhead for the selected services.
====

* *Enhanced security* that provides a secure, zero-trust network foundation with mTLS by default for all meshed workloads.

[NOTE]
====
Ambient mode is a newer architecture and may involve different operational considerations than traditional sidecar models.
====

While well-defined discovery selectors allow a service mesh deployed in ambient mode alongside a mesh in sidecar mode, this scenario has not been thoroughly validated. To avoid potential conflicts, install {istio} ambient mode only on clusters that do not have an existing {SMProductName} installation. Ambient mode remains a Technology Preview feature.

[IMPORTANT]
====
{istio} ambient mode is not compatible with clusters that use {SMProductName} 2.6 or earlier. You must not install or use them together.
====