// Module included in the following assemblies:
// * service_mesh/v2x/ossm-deployment-models.adoc

:_mod-docs-content-type: PROCEDURE
[id="ossm-excluding-namespaces-from-cluster-wide-mesh-cli_{context}"]
= Including and excluding namespaces from a cluster-wide mesh by using the CLI

By default, the {SMProductName} Operator uses discovery selectors to identify the namespaces that make up the mesh. Namespaces that do not contain the label defined in the `ServiceMeshMemberRoll` resource are not matched by the discovery selector and are excluded from the mesh.  
 
.Prerequisites

* You have installed the {SMProductName} Operator.
* You have deployed a `ServiceMeshControlPlane` resource.
* You are logged in as a user with the `cluster-admin` role. If you use {product-dedicated}, you are logged in as a user with the `dedicated-admin` role.

.Procedure

. Log in to the {product-title} CLI.

. Open the `ServiceMeshControlPlane` resource as a YAML file by running the following command:
+
[source,terminal]
----
$ oc -n istio-system edit smcp <name> <1>
----
<1> `<name>` represents the name of the `ServiceMeshControlPlane` resource.

. Modify the YAML file so that the `spec.discoverySelectors` field of the `ServiceMeshMemberRoll` resource includes the discovery selector. The following example uses `istio-discovery: enabled`:
+
[source,yaml]
----
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata: 
  name: basic
spec: 
  mode: ClusterWide
  meshConfig: 
    discoverySelectors:
    - matchLabels: 
        istio-discovery: enabled <1>
    - matchExpressions:
      - key: kubernetes.io/metadata.name <2>
        operator: NotIn
        values:
        - bookinfo
        - httpbin
----
<1> Ensures that the mesh discovers namespaces that contain the label `istio-discovery: enabled`. The mesh does not discover namespaces that do not contain the label.
<2> Ensures that the mesh does not discover namespaces `bookinfo` and `httpbin`.

. Save the file and exit the editor.