// Module included in the following assemblies:
//
// * service-mesh-docs-main/migrating/cluster-wide/ossm-migrating-cluster-wide.adoc

ifeval::["{context}" == "cw-injection"]
:ossm-cluster-wide-istio-injection:
endif::[]
ifeval::["{context}" == "cw-injection-cm"]
:ossm-cert-manager-istio-injection:
endif::[]

:_mod-docs-content-type: PROCEDURE
[id="ossm-migrating-a-cluster-wide-deployment-using-the-istio-injection-label_{context}"]
ifdef::ossm-cluster-wide-istio-injection[= Migrating a cluster-wide deployment by using the Istio injection label]
ifdef::ossm-cert-manager-istio-injection[= Migrating a cluster-wide deployment by using the Istio injection label with cert-manager]

[role="_abstract"]

You can perform a canary upgrade with the gradual migration of data plane namespaces for a cluster-wide deployment by using the `istio-injection=enabled` label and the `default` revision tag.

You must re-label all of the data plane namespaces. However, it is safe to restart any of the workloads at any point during the migration process.

The `bookinfo` application is used as an example for the `{istio}` resource. For more information about configuration differences between the {SMProduct} 2 `ServiceMeshControlPlane` resource and the {SMProduct} 3 `{istio}` resource, see "ServiceMeshControlPlane resource to Istio resource fields mapping".

.Prerequisites

* You have deployed {ocp-product-title} 4.14 or later.
* You have logged in to the {ocp-product-title} web console as a user with the `cluster-admin` role.
* You have completed the premigration checklists.
* You have the {SMProduct} {SMv2Version} Operator installed.
* You have the {SMProduct} 3 Operator installed.
* You have created an `IstioCNI` resource.
* You have installed the `istioctl` tool.
ifdef::ossm-cluster-wide-istio-injection[]
* You are running a cluster-wide Service Mesh control plane resource.
endif::[]
ifdef::ossm-cert-manager-istio-injection[]
* You are using the cert-manager and istio-csr tools in a cluster-wide deployment.
* Your {SMProduct} {SMv2Version} `ServiceMeshControlPlane` resource is configured with the cert-manager tool
endif::[]
* You have installed the `bookinfo` application.

.Procedure

ifdef::ossm-cert-manager-istio-injection[]
. Confirm that your {SMProduct} 2 `ServiceMeshControlPlane` resource is configured with the cert-manager tool.
+
You can see the following example configuration for reference:
+
[source,yaml]
----
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  ...
  security:
    certificateAuthority:
      cert-manager:
        address: cert-manager-istio-csr.istio-system.svc:443
      type: cert-manager
    dataPlane:
      mtls: true
    identity:
      type: ThirdParty
    manageNetworkPolicy: false
----

. Update the `istio-csr` deployment to include your {SMProduct} 3 control plane by running the following command:
+
[source,terminal]
----
  helm upgrade cert-manager-istio-csr jetstack/cert-manager-istio-csr \
      --install \
      --reuse-values \
      --namespace istio-system \
      --wait \
      --set "app.istio.revisions={basic,ossm-3-v1-24-3}"
----
+
where:
+
`app.istio.revisions`:: This field must include your {SMProduct} 3.0 control plane revision _before_ you create your `{istio}` resource so that proxies can properly communicate with the {SMProduct} 3.0 control plane. 
endif::[]

. Identify the namespaces that contain a 2.6 control plane by running the following command:
+
[source,terminal]
----
$ oc get smcp -A
----
+
*Example output:*
+
[source,terminal]
----
NAMESPACE      NAME                   READY   STATUS            PROFILES      VERSION   AGE
istio-system   install-istio-system   6/6     ComponentsReady   ["default"]   2.6.6     115m
----

. Create a YAML file named `ossm-3.yaml`. This procedure creates the {istio} resource for the 3.0 installation in the same namespace as the `ServiceMeshControlPlane` resource for the 2.6 installation.
+
[NOTE]
====
In the following example configuration, the {istio} control plane has access to all namespaces on the cluster. If you want to limit the namespaces the control plan has access to, you must define discovery selectors. You must match all the data plane namespaces that you plan to migrate from version 2.6.
====
+
You can see the following example configuration for reference:
+
[source,yaml,subs="attributes,verbatim"]
----
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: ossm-3
spec:
  updateStrategy:
    type: RevisionBased
  namespace: istio-system
  version: v1.24.3
  values:
    meshConfig:
      extensionProviders:
        - name: prometheus
          prometheus: {}
        - name: otel
          opentelemetry:
            port: 4317
            service: otel-collector.opentelemetrycollector-3.svc.cluster.local
----
* `metadata.name` specifies the name of the `IstioRevision` resource. The `updateStrategy` and `version` fields specify how the resource is updated. For more information, see "Identifying the revision name".
* `spec.namespace` specifies the namespace where the 3.0 and 2.6 control planes must run.
* `spec.values` specifies the configuration values for the 3.0 control plane. If you are migrating metrics and tracing, update the `extensionProviders` fields according to your tracing and metrics configurations.
+
[NOTE]
====
To prevent the {SMProduct} 3.0 control plane from injecting proxies in the namespaces that have the `istio-injection=enabled` label applied and are still managed by {SMProduct} 2.6 control plane, do not use the `default` name for the {istio} resource, and do not create the `default` revision tag in the following steps. You create the `default` revision tag later in this procedure.
====

. Apply the YAML file by running the following command:
+
[source,terminal]
----
$ oc apply -f ossm-3.yaml
----

.Verification

. Verify that the new `istiod` resource uses the existing root certificate by running the following command:
+
[source,terminal]
----
$ oc logs deployments/istiod-ossm-3-v1-24-3 -n istio-system | grep 'Load signing key and cert from existing secret'
----
+
*Example output:*
+
[source,terminal]
----
2024-12-18T08:13:53.788959Z	info	pkica	Load signing key and cert from existing secret istio-system/istio-ca-secret
----

ifeval::["{context}" == "cw-injection"]
:!ossm-cluster-wide-istio-injection:
endif::[]
ifeval::["{context}" == "cw-injection-cm"]
:!ossm-cert-manager-istio-injection:
endif::[]