// Module included in the following assemblies:
// * service_mesh/v2x/ossm-deployment-models.adoc

// * ossm-deployment-models.adoc ?

:_content-type: CONCEPT
[id="ossm-infrastructure-node-deployment-model_{context}"]
= Infrastructure node deployment model

Infrastructure nodes provide a way to isolate infrastructure workloads for two primary purposes:

* To prevent incurring billing costs against subscription counts
* To separate maintenance and management.

Therefore, deploying the SMCP to an infrastructure node provides advantages for multi-tenant configurations that use a singe mesh to provide functionality across the cluster or for cluster-wide deployments. Deploying a service mesh operator to an infrastructure node is very similar to deploying to a worker node. After installing the operator on a worker node, you must move it to an infrastructure node, create SMCP then add the code snippet Marko provided 



For more information about infrastructure nodes, refer to
https://docs.openshift.com/container-platform/4.12/nodes/nodes/nodes-nodes-creating-infrastructure-nodes.html



{SMProductName} installs a `ServiceMeshControlPlane` that is configured for multitenancy by default. {SMProductName} uses a multitenant Operator to manage the {SMProductShortName} control plane lifecycle. Within a mesh, namespaces are used for tenancy.

{SMProductName} uses `ServiceMeshControlPlane` resources to manage mesh installations, whose scope is limited by default to namespace that contains the resource. You use `ServiceMeshMemberRoll` and `ServiceMeshMember` resources to include additional namespaces into the mesh. A namespace can only be included in a single mesh, and multiple meshes can be installed in a single OpenShift cluster.

Typical service mesh deployments use a single {SMProductShortName} cont



[NOTE]
====
When using the Infrastructure node deployment model, you install the service mesh operator and deploy the control plane as outlined in the product documentation. Then, you move the operator to an infrastructure node.
====
