// Module included in the following assemblies:
// install/ossm-installing-openshift-service-mesh.adoc

:_mod-docs-content-type: PROCEDURE
[id="ossm-accessing-bookinfo-application-using-istio-gateway-injection_{context}"]
= Accessing the Bookinfo application by using Istio gateway injection

Gateway injection uses the same mechanisms as {istio} sidecar injection to create a gateway from a `Deployment` resource that is paired with a `Service` resource. The `Service` resource can be made accessible from outside an {ocp-product-title} cluster.

.Prerequisites

* You are logged in to the {ocp-product-title} web console as `cluster-admin`.

* The {SMProductName} Operator must be installed.

* The {istio} resource must be deployed.

.Procedure

. Create the `istio-ingressgateway` deployment and service by running the following command:
+
[source,terminal]
----
$ oc apply -n bookinfo -f ingress-gateway.yaml
----
+
[NOTE]
====
This example uses a sample `ingress-gateway.yaml` https://raw.githubusercontent.com/istio-ecosystem/sail-operator/main/chart/samples/ingress-gateway.yaml[file] that is available in the Istio community repository.
====

. Configure the `bookinfo` application to use the new gateway. Apply the gateway configuration by running the following command:
+
[source,terminal]
----
$ oc apply -f https://raw.githubusercontent.com/openshift-service-mesh/istio/release-1.24/samples/bookinfo/networking/bookinfo-gateway.yaml -n bookinfo
----
+
[NOTE]
====
To configure gateway injection with the `bookinfo` application, this example uses a sample gateway configuration file that must be applied in the namespace where the application is installed.
====

. Use a route to expose the gateway external to the cluster by running the following command:
+
[source,terminal]
----
$ oc expose service istio-ingressgateway -n bookinfo
----

. Modify the YAML file to automatically scale the pod when ingress traffic increases.
+
.Example configuration
[source,yaml]
----
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    istio: ingressgateway
    release: istio
  name: ingressgatewayhpa
  namespace: bookinfo
spec:
  maxReplicas: 5 <1>
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-ingressgateway
----
<1> This example sets the the maximum replicas to `5` and the minimum replicas to `2`. It also creates another replica when utilization reaches 80%.

. Specify the minimum number of pods that must be running on the node.
+
.Example configuration
[source,yaml]
----
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    istio: ingressgateway
    release: istio
  name: ingressgatewaypdb
  namespace: bookinfo
spec:
  minAvailable: 1 <1>
  selector:
    matchLabels:
      istio: ingressgateway
----
<1> This example ensures one replica is running if a pod gets restarted on a new node.

. Obtain the gateway host name and the URL for the product page by running the following command:
+
[source,terminal]
----
$ HOST=$(oc get route istio-ingressgateway -n bookinfo -o jsonpath='{.spec.host}')
----

. Verify that the `productpage` is accessible from a web browser by running the following command:
+
[source,terminal]
----
$ echo productpage URL: http://$HOST/productpage
----