// Module included in the following assemblies:
// about/ossm-about-concepts-assembly.adoc

:_mod-docs-content-type: CONCEPT
[id="ossm-about-concepts-cert-manager_{context}"]
= {SMProductName} and cert-manager

The cert-manager tool is a solution for X.509 certificate management on Kubernetes. It delivers a unified API to integrate applications with private or public key infrastructure (PKI), such as Vault, Google Cloud Certificate Authority Service, Let's Encrypt, and other providers.

The cert-manager tool ensures that the certificates are valid and up-to-date by attempting to renew the certificates at a configured time before they expire.

For Istio users, cert-manager also provides integration with `istio-csr`, which is a certificate authority (CA) server that handles certificate signing requests (CSR) from Istio proxies. The server then delegates signing to cert-manager, which forwards CSRs to the configured CA server.

//TP1 content. IA influx, likely everything will change for GA.