// Module included in the following assemblies:
//
// * install/ossm-installing-openshift-service-mesh.adoc

:_mod-docs-content-type: CONCEPT
[id="ossm-about-service-mesh-custom-resource-definitions_{context}"]
= About Service Mesh custom resource definitions

[role="_abstract"]

Installing the {SMProductName} Operator also installs custom resource definitions (CRD) that administrators can use to configure {istio} for {SMProductShortName} installations.

The {olm-first} installs two categories of CRDs: 

* {sail-operator} CRDs

* {istio} CRDs.

{sail-operator} CRDs define custom resources for installing and maintaining the {istio} components required to operate a service mesh. These custom resources belong to the `sailoperator.io` API group and include the `Istio`, `IstioRevision`, `IstioCNI`, and `ZTunnel` resource kinds.

You can use {istio} CRDs to configure the mesh and manage your services. These CRDs define custom resources in several `istio.io` API groups, such as `networking.istio.io` and `security.istio.io`. The CRDs also include various resource kinds, such as `AuthorizationPolicy`, `DestinationRule`, and `VirtualService`, that administrators use to configure a service mesh.