// Module included in the following assemblies:
//
// * service-mesh-docs-main/ossm-release-notes.adoc

:_mod-docs-content-type: REFERENCE
[id="ossm-release-3-2-known-issues_{context}"]
= {SMProductName} 3.2 known issues

[id="ambient-mode-not-supported-on-fips-enabled-openshift-clusters_{context}"]
== Ambient mode not supported on FIPS-enabled OpenShift clusters

{istio} ambient mode does not currently support {ocp-short-name} clusters running in Federal Information Processing Standards (FIPS) mode. Deployments that require FIPS compliance must continue using sidecar mode until support becomes available in a future release.

[id="limitation-due-to-ztunnel-concurrency-issue_{context}"]
== Limitation due to `ztunnel` concurrency issue

A concurrency issue in `ztunnel` limits throughput scalability in {istio} ambient mode. Performance remains comparable to sidecar mode in most scenarios, but the issue can limit the potential to scale throughput performance.

link:https://issues.redhat.com/browse/OSSM-11132[OSSM-11132]