// Module included in the following assemblies:
//
// * service-mesh-docs-main/install/ossm-cert-manager.adoc

:_mod-docs-content-type: PROCEDURE
[id="ossm-installing-cert-manager_{context}"]
= Integrating Service Mesh with the cert-manager Operator by using the istio-csr agent

[role="_abstract"]

Integrate the cert-manager Operator with {SMProduct} by deploying the `istio-csr` agent and configuring an `{istio}` resource to process certificate signing requests for workloads and the control plane.

.Prerequisites

* You have installed the {cert-manager-operator} version 1.18.0 or later.

* You have logged in to {ocp-product-title} 4.14 or later.

* You have installed the {SMProduct} Operator.

* You have a `IstioCNI` instance running in the cluster.

* If you use {istio} ambient mode, you have installed the `ztunnel` namespace and resource. For more information, see _Installing {istio} ambient mode_ in this guide.

* You have installed the `istioctl` command.


.Procedure

. Create the `istio-system` namespace by running the following command:
+
[source, terminal]
----
$ oc create namespace istio-system
----

. Create the root certificate authority (CA) issuer by creating an `Issuer` object for the `istio-csr` agent:

.. Create a new project to install the `istio-csr` agent by running the following command:
+
[source, terminal]
----
$ oc new-project istio-csr
----

.. Define an `Issuer` object similar to the following example:
+
[NOTE]
====
The `selfSigned` issuer serves demonstration purposes, testing, or proof-of-concept environments. For production deployments, use a secure and trusted CA.
====
+
[source, yaml]
----
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: istio-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: istio-system
spec:
  isCA: true
  duration: 87600h
  secretName: istio-ca
  commonName: istio-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    organizations:
      - cluster.local
      - cert-manager
  issuerRef:
    name: selfsigned
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: istio-ca
  namespace: istio-system
spec:
  ca:
    secretName: istio-ca
----

.. Create the objects by running the following command:
+
[source, terminal]
+
----
$ oc apply -f issuer.yaml
----

.. Wait for the `istio-ca` certificate to contain the "Ready" status condition by running the following command:
+
[source, terminal]
----
$ oc wait --for=condition=Ready certificates/istio-ca -n istio-system
----

. Deploy the `istio-csr` agent:

.. Define the `IstioCSR` custom resource as shown in the following example:
+
[source, yaml]
----
apiVersion: operator.openshift.io/v1alpha1
kind: IstioCSR
metadata:
  name: default
  namespace: istio-csr
spec:
  istioCSRConfig:
    certManager:
      issuerRef:
        name: istio-ca
        kind: Issuer
        group: cert-manager.io
    istiodTLSConfig:
      trustDomain: cluster.local
    istio:
      namespace: istio-system
----

.. Run the following command to apply the custom resource configuration and deploy the `istio-csr` agent:
+
[source, terminal]
+
----
$ oc create -f istioCSR.yaml
----

.. Verify that the `istio-csr` deployment is ready by running the following command:
+
[source, terminal]
+
----
$ oc get deployment -n istio-csr
----

. Install the `{istio}` resource:
+
[NOTE]
====
The configuration disables the built-in CA server for {istio} and forwards certificate signing requests from `istiod` to the `istio-csr` agent. The `istio-csr` agent obtains certificates for both `istiod` and mesh workloads from the cert-manager Operator. The `istio-csr` agent generates the `istiod` TLS certificate, and the system mounts it into the pod at a known location.
====

.. Define the `istio` object to delegate certificate signing to the `istio-csr` agent. Refer to the following example:
+
[source, yaml]
----
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  namespace: istio-system
  values:
    global:
      caAddress: cert-manager-istio-csr.istio-csr.svc:443
----
+
[NOTE]
====
If you use {istio} ambient mode, remember to add the previous `caAddress` configuration to your `istiod` configuration.
====

.. Create the `{istio}` resource by running the following command:
+
[source, terminal]
+
----
$ oc apply -f istio.yaml
----

.. Verify that the `{istio}` resource displays the "Ready" status condition by running the following command:
+
[source, terminal]
----
$ oc wait --for=condition=Ready istios/default -n istio-system
----