// Module included in the following assemblies:
//
// * service_mesh/v1x/threescale_adapter/threescale-adapter.adoc
// * service_mesh/v2x/threescale_adapter/threescale-adapter.adoc

:_mod-docs-content-type: PROCEDURE
[id="ossm-threescale-istio-adapter-verification_{context}"]
= 3scale Istio adapter verification

You might want to check whether the 3scale Istio adapter is working as expected. If your adapter is not working, use the following steps to help troubleshoot the problem.

.Procedure

. Ensure the _3scale-adapter_ pod is running in the {SMProductShortName} control plane namespace:
+
[source,terminal]
----
$ oc get pods -n istio-system
----
. Check that the _3scale-adapter_ pod has printed out information about itself booting up, such as its version:
+
[source,terminal]
----
$ oc logs istio-system
----
. When performing requests to the services protected by the 3scale adapter integration, always try requests that lack the right credentials and ensure they fail. Check the 3scale adapter logs to gather additional information.
