////
This CONCEPT module included in the following assemblies:
-service_mesh/v1x/ossm-architecture.adoc
-service_mesh/v2x/ossm-architecture.adoc
////

[id="ossm-kiali-features_{context}"]
= Kiali features
//In the title include nouns or noun phrases that are used in the body text.
//Do not start the title of concept modules with a verb..

The Kiali console is integrated with Red Hat Service Mesh and provides the following capabilities:

* *Health* – Quickly identify issues with applications, services, or workloads.

* *Topology* – Visualize how your applications, services, or workloads communicate via the Kiali graph.

* *Metrics* – Predefined metrics dashboards let you chart service mesh and application performance for Go, Node.js. Quarkus, Spring Boot, Thorntail and Vert.x. You can also create your own custom dashboards.

* *Tracing* – Integration with Jaeger lets you follow the path of a request through various microservices that make up an application.

* *Validations* – Perform advanced validations on the most common Istio objects (Destination Rules, Service Entries, Virtual Services, and so on).

* *Configuration* – Optional ability to create, update and delete Istio routing configuration using wizards or directly in the YAML editor in the Kiali Console.
