// Module included in the following assemblies:
// * service_mesh/v2x/-ossm-troubleshooting-istio.adoc

[id="ossm-troubleshooting-operators_{context}"]
= Troubleshooting Operators

If you experience Operator issues, verify your Operator subscription status.  Also verify that you did not inadvertently install a community Operator.

The Operator installation steps include verifying the Operator status in the OpenShift console.  You can also verify the Operator pods are available and running in the `openshift-operators` namespace with the following command:
[source,terminal]
----
$ oc get pods -n openshift-operators
----
You should see something similar to the following:
[source,terminal]
----
NAME                               READY   STATUS    RESTARTS   AGE
istio-operator-bb49787db-zgr87     1/1     Running   0          15s
jaeger-operator-7d5c4f57d8-9xphf   1/1     Running   0          2m42s
kiali-operator-f9c8d84f4-7xh2v     1/1     Running   0          64s
----
//Does Elasticsearch not have an operator pod?

You can view Operator logs by using the `oc logs` command.  Red Hat may request logs to help resolve support cases.
[source,terminal]
----
$ oc logs -n openshift-operators <podName>
----
For example,
[source,terminal]
----
$ oc logs -n openshift-operators istio-operator-bb49787db-zgr87
----

//If your pod is failing to start, you may need to use the `--previous` option to see the logs of the last attempt.
