// Module included in the following assemblies:
//
// * service_mesh/service_mesh_install/installing-ossm.adoc

[id="ossm-member-roll_{context}"]
= Configure the {ProductName} member roll

You must create a `ServiceMeshMemberRoll` resource named `default` associated with the {ProductShortName} in the same project as the `ServiceMeshControlPlane`.

[WARNING]
====
If Container Network Interface (CNI) plugin is enabled, manual sidecar injection will work, but pods will not be able to communicate with the control plane unless those pods are specified in the `ServiceMeshMemberRoll` resource.
====

[NOTE]
====
The member projects are only updated if the {ProductShortName} control plane installation succeeds.
====

* You can add any number of projects, but a project can only belong to *one* `ServiceMeshMemberRoll` resource.

The `ServiceMeshMemberRoll` resource is deleted when its corresponding `ServiceMeshControlPlane` resource is deleted.

[id="ossm-member-roll-console_{context}"]
== Configure the member roll from the {product-title} web console

Follow this procedure to add the Bookinfo project to the {ProductShortName} member roll by using the web console.

.Prerequisites
* An installed, verified {ProductName} Operator.

.Procedure

. Log in to the {product-title} web console.

. Click to *Home* -> *Projects*.

. Click *Create Project*.

. Enter a *Project Name* (for example, *bookinfo*), a *Display Name*, and a *Description*, then click *Create*.

. Click *Catalog* -> *Installed Operators*.

. Click the *Project* menu and choose `istio-system` from the list.

. Click the *Istio Service Mesh Member Roll* link under *Provided APIs* for the *{ProductName}* Operator.

. Click on *All Instances*, click *Create New*, and then click *Create Istio Service Mesh Member Roll*.
+
[NOTE]
====
It can take a short time for the Operator to finish creating the projects, therefore you may need to refresh the screen before the web console presents the *Create Istio Service Mesh Member Roll* button.
====

. Edit the default Service Mesh Member Roll YAML and add *bookinfo* to the *members* list.

. Click *Create* to save the updated Service Mesh Member Roll.


[id="ossm-member-roll-cli_{context}"]
== Configure the member roll from the CLI

This example joins the Bookinfo project to the {ProductShortName} from the CLI.

.Prerequisites

* An installed, verified {ProductShortName} Operator.
* Name of the project with the `ServiceMeshMemberRoll` resource.
* Access to the {product-title} Command-line Interface (CLI) also known as `oc`.

.Procedure

. Log in to the {product-title} CLI.

. Create `ServiceMeshMemberRoll` resource in the same project as the `ServiceMeshControlPlane` resource.

. Name the resource `default`.

. Add the Bookinfo project to the member list in the `ServiceMeshMemberRoll`. In this example, the `bookinfo` project is joined to the {ProductShortName} deployed in the same project as the `ServiceMeshMembereRoll` resource.
+
.Project configuration example

[source,yaml]
----
  apiVersion: maistra.io/v1
  kind: ServiceMeshMemberRoll
  metadata:
    name: default
  spec:
    members:
    # a list of projects joined into the service mesh
    - bookinfo
----

