// Module included in the following assemblies:
//
// * service_mesh/service_mesh_install/preparing-ossm-install.adoc

[id="ossm-supported-configurations_{context}"]
= {ProductName} supported configurations

The following are the only supported configurations for the {ProductName} {ProductVersion}:

* Red Hat {product-title} version 4.1.

[NOTE]
====
OpenShift Online and OpenShift Dedicated are not supported for {ProductName} {ProductVersion}.
====

* The deployment must be contained to a single {product-title} cluster that is not federated.
* This release of {ProductName} is only available on {product-title} x86_64.
* {ProductName} is only suited for {product-title} Software Defined Networking (SDN) configured as a flat network with no external providers.
* This release only supports configurations where all {ProductShortName} components are contained in the OpenShift cluster in which it operates. It does not support management of microservices that reside outside of the cluster, or in a multi-cluster scenario.
* The Kiali observability console is only supported on the two most recent releases of the Chrome, Edge, Firefox, or Safari browsers.
