// Module included in the following assemblies:
//
// * service-mesh-docs-main/about/ossm-migrating-assembly.adoc

//Start of an overall Migrating section.
//Section is most likely to be reworked/restructured with OSSM 2 to OSSM 3 migration guides for GA. Unknown how many migration guides there are at this time (11/11/2024). It would be beneficial to be able to link from differences to the relevent migration guide so that users A) understand the change, esp significant changes like new operator, installing tracing and Kiali separately, gateways, etc.

:_mod-docs-content-type: CONCEPT
[id="ossm-migrating-read-me-observability-integrations_{context}"]
= Independent Red{nbsp}Hat OpenShift Observability component integrations and configurations

A significant change in {SMProductName} 3 is that the Operator no longer installs and manages observability components such as Prometheus and Grafana with the Istio control plane. It also no longer installs and manages {DTProductName} components such as {TempoShortName} and {OTELName} (previously Jaeger and Elasticsearch), or Kiali.

The {SMProduct} 3 Operator limits its scope to Istio-related resources, with observability components supported and managed by the independent Operators that make up Red{nbsp}Hat OpenShift Observability, such as the following:

//Note to add Observability attributes. Adding attributes is being handled by a different Jira issue, and is outside the scope of this PR.

* Logging
* User workload monitoring
* {DTProductName}

Kiali and the {SMPlugin} are still supported with the {KialiProduct}.

This simplification greatly reduces the footprint and complexity of {SMProduct} 3, while providing better, production-grade support for observability through Red{nbsp}Hat OpenShift Observability components.