// Module included in the following assemblies:
//
// * service-mesh-docs-main/metrics/ossm-metrics.adoc

:_mod-docs-content-type: PROCEDURE
[id="ossm-config-openshift-monitoring-only_{context}"]
= Configuring OpenShift Monitoring with Service Mesh

// This is WITHOUT Kiali.
// TP1 content. TP banner is persistent and handled by Tim O'Keefe in a different PR.
// Possible file name may change
// Possible assembly file may change
// Assemblies, topic map info needs to be worked out still for 3.0.

You can integrate {SMProductName} with user-workload monitoring to enable observability in your service mesh. User-workload monitoring provides access to essential built-in tools and is required to run Kiali, the dedicated console for {istio}.

.Prerequisites

* {SMProductName} is installed.

* User-workload monitoring is enabled. See link:https://docs.openshift.com/container-platform/4.16/observability/monitoring/enabling-monitoring-for-user-defined-projects.html[Enabling monitoring for user-defined projects].

.Procedure

. Create a YAML file named `servicemonitor.yml` to monitor the {istio} control plane:
+
.Example `ServiceMonitor` object
[source,yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod-monitor
  namespace: istio-system
spec:
  targetLabels:
  - app
  selector:
    matchLabels:
      istio: pilot
  endpoints:
  - port: http-monitoring
    interval: 30s
----

. Apply the YAML file by running the following command:
+
[source,terminal]
----
$ oc apply -f servicemonitor.yml
----

. Create a YAML file named `podmonitor.yml` to collect metrics from the {istio} proxies:
+
.Example `PodMonitor` object
[source,yaml]
----
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxies-monitor
  namespace: istio-system # <1>
spec:
  selector:
    matchExpressions:
    - key: istio-prometheus-ignore
      operator: DoesNotExist
  podMetricsEndpoints:
  - path: /stats/prometheus
    interval: 30s
    relabelings:
    - action: keep
      sourceLabels: ["__meta_kubernetes_pod_container_name"]
      regex: "istio-proxy"
    - action: keep
      sourceLabels: ["__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape"]
    - action: replace
      regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
      replacement: '[$2]:$1'
      sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_port","__meta_kubernetes_pod_ip"]
      targetLabel: "__address__"
    - action: replace
      regex: (\d+);((([0-9]+?)(\.|$)){4})
      replacement: '$2:$1'
      sourceLabels: ["__meta_kubernetes_pod_annotation_prometheus_io_port","__meta_kubernetes_pod_ip"]
      targetLabel: "__address__"
    - sourceLabels: ["__meta_kubernetes_pod_label_app_kubernetes_io_name","__meta_kubernetes_pod_label_app"]
      separator: ";"
      targetLabel: "app"
      action: replace
      regex: "(.+);.*|.*;(.+)"
      replacement: "${1}${2}"
    - sourceLabels: ["__meta_kubernetes_pod_label_app_kubernetes_io_version","__meta_kubernetes_pod_label_version"]
      separator: ";"
      targetLabel: "version"
      action: replace
      regex: "(.+);.*|.*;(.+)"
      replacement: "${1}${2}"
    - sourceLabels: ["__meta_kubernetes_namespace"]
      action: replace
      targetLabel: namespace
    - action: replace
      replacement: "the-mesh-identification-string" # <2>
      targetLabel: mesh_id
----
<1> Specifies that the `PodMonitor` object must be applied in all mesh namespaces, including the Istio control plane namespace, because {ocp-product-title} monitoring ignores the `namespaceSelector` spec in `ServiceMonitor` and `PodMonitor` objects.
<2> Specify the actual mesh ID.

. Apply the YAML file by running the following command:
+
[source,terminal]
----
$ oc apply -f podmonitor.yml
----

. On the {ocp-short-name} Console go to **Observe** -> **Metrics**, and run the query `istio_requests_total`.
+
[NOTE]
====
The **Metrics** implementation can take a few minutes for the query to return results.
====
