// Module included in the following assemblies:

// update/ossm-updating-openshift-service-mesh.adoc

:_mod-docs-content-type: PROCEDURE
[id="ossm-updating-istio-cni-resource-version_{context}"]
= Updating the Istio CNI resource version

You can update the Istio CNI resource version by changing the version in the resource. Then, the {SMProductShortName} Operator deploys a new version of the CNI plugin that replaces the old version of the CNI plugin. The `istio-cni-node` pods automatically reconnect to the new CNI plugin.

.Prerequisites

* You are logged in to {ocp-product-title} as a user with the `cluster-admin` role.
* You installed the {SMProductName} Operator and deployed {istio}.
* You installed the {istio} CNI plugin with the desired version. In the following example, the `IstioCNI` resource named `default` is deployed in the `istio-cni` namespace.

.Procedure

. Change the version in the `{istio}` resource. For example, to update to {istio} `1.24.4`, set the `spec.version` field to `v1.24.4` by running the following command:
+
[source,terminal]
----
$ oc patch istiocni default -n istio-cni --type='merge' -p '{"spec":{"version":"v1.24.4"}}'
----

. Confirm that the new version of the CNI plugin is ready by running the following command:
+
[source,terminal]
----
$ oc get istiocni default
----
+
.Example Output
+
[source,terminal]
----
NAME      READY   STATUS    VERSION   AGE
default   True    Healthy   v1.24.4   91m
----