// Module included in the following assemblies:
// update/ossm-updating-openshift-service-mesh-in-ambient-mode.adoc

:_mod-docs-content-type: PROCEDURE
[id="ossm-verifying-l7-features-with-authorization-policies_{context}"]
= Verifying Layer 7 (L7) features with authorization policies

[role="_abstract"]
After updating the waypoint proxies, verify that the Layer 7 (L7) authorization policies are enforced correctly. In this example, the `AuthorizationPolicy` resource named `productpage-waypoint` allows only requests from the `default/sa/curl` service account to send `GET` requests to the `productpage` service.

.Prerequisites

* You have updated the waypoint proxies.

* You have created an application pod using the described service account in the `AuthorizationPolicy` resource.

* You have created an `AuthorizationPolicy` resource.

.Procedure

. Optional: Create the `AuthorizationPolicy` resource if it does not already exist by running the following command:
+
[source,terminal]
----
$ oc apply -f - <<EOF
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: productpage-waypoint
  namespace: bookinfo
spec:
  targetRefs:
  - kind: Service
    group: ""
    name: productpage
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/default/sa/curl
    to:
    - operation:
        methods: ["GET"]
EOF
----

. Verify that services not included in the allow list, such as the ratings service, are denied access by running the following command:
+
[source,terminal]
----
$ oc exec "$(
  kubectl get pod \
    -l app=ratings \
    -n bookinfo \
    -o jsonpath='{.items[0].metadata.name}'
)" \
-c ratings \
-n bookinfo -- \
curl -sS productpage:9080/productpage
----
+
The request will be denied because the `ratings` service is not included in the authorization policy’s `allow` list. Only the `curl` pod using the `default/curl` service account can access `productpage` service.

. Verify that the `curl` service can access the `productpage` service with `GET` requests by running the following command:
+
[source,terminal]
----
oc exec "$(
  kubectl get pod \
    -l app=curl \
    -n default \
    -o jsonpath='{.items[0].metadata.name}'
)" \
-c curl \
-n default -- \
curl -sS http://productpage.bookinfo:9080/productpage | grep -o "<title>.*</title>"
----
+
The request will succeed because the `curl` service meets the authorization policy rules. It uses the `cluster.local/ns/default/sa/curl` principal and performs a `GET` operation, both allowed by the policy. The successful response containing the page title confirms that the waypoint proxy correctly enforces L7 authorization rules and allows valid traffic.