// Module included in the following assemblies:
// install/ossm-deploying-multiple-service-meshes-on-single-cluster.adoc

:_mod-docs-content-type: Procedure
[id="ossm-deploy-application-workloads-in-each-mesh_{context}"]
= Deploy application workloads in each mesh
:context: ossm-deploy-application-workloads-in-each-mesh

This procedure explains how to configure a cluster to host two control planes, each managing independent service mesh data planes. The configuration involves creating separate `{istio}` resources with unique names in independent {istio} system namespaces. Eah `{istio}` resource will use a unique `revision` name, which identifies the control planes, workloads, or namespaces associated with it. These `revision` names, applied using injection or `istio.io/rev` labels, enable sidecar injection while also indicating the corresponding control plane.

Each `{istio}` resource must also configure `discoverySelectors` to specify which namespaces the {istio} control plane observes. Only namespaces with labels that match the configured `discoverySelectors` can join the mesh.

When adding an additional {istio} control plane to a cluster with an existing control plane, ensure that the existing `{istio}` instance has `discoverySelectors` configured to avoid overlapping with the new control plane. Run the following command to check for existing `{istio}` instances.

This procedure may be extended to support more than two control planes. The primary limitation on the number of service meshes in a single cluster is the availability of cluster resources.

[NOTE]
====
There is only one `IstioCNI` resource shared by all control planes in the cluster, and it must be updated independently.
====

[source,terminal]
----
$ oc get istios
----


.Procedure

. Create an application namespace called `app-ns-1`:
+
[source,terminal]
----
$ oc create namespace app-ns-1
----

. Add the `usergroup=usergroup-1` label to ensure that the namespace is discovered by the first control plane and the `istio.io/rev=mesh-1` to enable sidecar injection in the namespace by default.
+
[source,terminal]
----
$ oc label namespace app-ns-1 usergroup=usergroup-1 istio.io/rev=mesh-1
----
+
[NOTE]
====
You can verify the `mesh-1` revision name by running the following command:
[source,terminal]
----
$ oc get istiorevisions
----
====

. Deploy the `sleep` and `httpbin` applications:
+
[source,terminal]
----
$ oc apply -f https://raw.githubusercontent.com/openshift-service-mesh/istio/release-1.23/samples/sleep/sleep.yaml -n app-ns-1
----
+
[source,terminal]
----
$ oc apply -f https://raw.githubusercontent.com/openshift-service-mesh/istio/release-1.23/samples/httpbin/httpbin.yaml -n app-ns-1
----

. Wait for the `httpbin` and `sleep` pods to run with sidecars injected:
+
[source,terminal]
----
$ oc get pods -n app-ns-1
----
+
You should see output similar to the following example:
+
.Example output
[source,terminal]
----
NAME                       READY   STATUS    RESTARTS   AGE
httpbin-7f56dc944b-kpw2x   2/2     Running   0          2m26s
sleep-5577c64d7c-b5wd2     2/2     Running   0          91m
----

. Create two more namespaces called `app-ns-2` and `app-ns-3`:
+
[source,terminal]
----
$ oc create namespace app-ns-2
----
+
[source,terminal]
----
$ oc create namespace app-ns-3
----

. Add both the namespaces to the second control plane with the discovery selector `usergroup=usergroup-2` and the revision label with the value `mesh-2`:
+
[source,terminal]
----
$ oc label namespace app-ns-2 usergroup=usergroup-2 istio.io/rev=mesh-2
----
+
[source,terminal]
----
$ oc label namespace app-ns-3 usergroup=usergroup-2 istio.io/rev=mesh-2
----

. Deploy the `sleep` and `httbin` applications to both namespaces:
+
[source,terminal]
----
$ oc apply -n app-ns-2 \
   -f https://raw.githubusercontent.com/openshift-service-mesh/istio/release-1.23/samples/sleep/sleep.yaml \
   -f https://raw.githubusercontent.com/openshift-service-mesh/istio/release-1.23/samples/httpbin/httpbin.yaml
----
+
[source,terminal]
----
$ oc apply -n app-ns-3 \
   -f https://raw.githubusercontent.com/openshift-service-mesh/istio/release-1.23/samples/sleep/sleep.yaml \
   -f https://raw.githubusercontent.com/openshift-service-mesh/istio/release-1.23/samples/httpbin/httpbin.yaml

[NOTE]
====
You can use the following command to wait for deployment to be ready:
[source,terminal]
----
$ oc wait deployment/sleep -n app-ns-1 --for=condition=Available
----
====

.Verification

After deploying the applications, use the `istioctl ps` command to verify that each application workload is managed by its assigned control plane.

.. Run the following procedure to verify the first control plane deployed in `istio-system-1`:
[source,terminal]
----
$ istioctl ps -i istio-system-1
----
You should see output similar to the following example:

.Example output
[source,terminal]
----
NAME                                  CLUSTER        CDS              LDS              EDS              RDS              ECDS        ISTIOD                            VERSION
httpbin-7f56dc944b-vwfm5.app-ns-1     Kubernetes     SYNCED (11m)     SYNCED (11m)     SYNCED (11m)     SYNCED (11m)     IGNORED     istiod-mesh-1-b69646b6f-kxrwk     1.23.0
sleep-5577c64d7c-d675f.app-ns-1       Kubernetes     SYNCED (11m)     SYNCED (11m)     SYNCED (11m)     SYNCED (11m)     IGNORED     istiod-mesh-1-b69646b6f-kxrwk     1.23.0
----

.. Run the following procedure to verify the first control plane deployed in `istio-system-2`:
[source,terminal]
----
$ istioctl ps -i istio-system-2
----
You should see output similar to the following example:

.Example output
[source,terminal]
----
NAME                                  CLUSTER        CDS                LDS                EDS                RDS                ECDS        ISTIOD                            VERSION
httpbin-7f56dc944b-54gjs.app-ns-3     Kubernetes     SYNCED (3m59s)     SYNCED (3m59s)     SYNCED (3m59s)     SYNCED (3m59s)     IGNORED     istiod-mesh-2-8666fdfc6-mqp45     1.23.0
httpbin-7f56dc944b-gnh72.app-ns-2     Kubernetes     SYNCED (4m1s)      SYNCED (4m1s)      SYNCED (3m59s)     SYNCED (4m1s)      IGNORED     istiod-mesh-2-8666fdfc6-mqp45     1.23.0
sleep-5577c64d7c-k9mxz.app-ns-2       Kubernetes     SYNCED (4m1s)      SYNCED (4m1s)      SYNCED (3m59s)     SYNCED (4m1s)      IGNORED     istiod-mesh-2-8666fdfc6-mqp45     1.23.0
sleep-5577c64d7c-m9hvm.app-ns-3       Kubernetes     SYNCED (4m1s)      SYNCED (4m1s)      SYNCED (3m59s)     SYNCED (4m1s)      IGNORED     istiod-mesh-2-8666fdfc6-mqp45     1.23.0
----

Use the following procedure to verify that application connectivity is restricted to workloads within their respective user groups:

. Send a request from the `sleep` pod in `app-ns-1` to the `httpbin` service in `app-ns-2`. The communication should fail:
+
[source,terminal]
----
$ oc -n app-ns-1 exec "$(oc -n app-ns-1 get pod -l app=sleep -o jsonpath={.items..metadata.name})" -c sleep -- curl -sIL http://httpbin.app-ns-2.svc.cluster.local:8000
----
+
You should see output similar to the following example:
+
.Example output
[source,terminal]
----
HTTP/1.1 503 Service Unavailable
content-length: 95
content-type: text/plain
date: Wed, 16 Oct 2024 12:05:37 GMT
server: envoy
----

. Send a request from the `sleep` pod in `app-ns-2` managed by `mesh-2` to the `httpbin` service in `app-ns-3` also managed by `mesh-2`. The communication should work:
+
[source,terminal]
----
oc -n app-ns-2 exec "$(oc -n app-ns-2 get pod -l app=sleep -o jsonpath={.items..metadata.name})" -c sleep -- curl -sIL http://httpbin.app-ns-3.svc.cluster.local:8000
----
+
You should see output similar to the following example:
+
.Example output
[source,terminal]
----
HTTP/1.1 200 OK
access-control-allow-credentials: true
access-control-allow-origin: *
content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' camo.githubusercontent.com
content-type: text/html; charset=utf-8
date: Wed, 16 Oct 2024 12:06:30 GMT
x-envoy-upstream-service-time: 8
server: envoy
transfer-encoding: chunked
----