//Module included in the following assemblies:
//
// * observability/otel/otel-forwarding-data.adoc

:_mod-docs-content-type: PROCEDURE
[id="otel-forwarding-data-to-third-party-systems_{context}"]
= Forwarding telemetry data to third-party systems

The OpenTelemetry Collector exports telemetry data by using the OTLP exporter via the OpenTelemetry Protocol (OTLP) that is implemented over the gRPC or HTTP transports. If you need to forward telemetry data to your third-party system and it does not support the OTLP or other supported protocol in the {OTELShortName}, then you can deploy an unsupported custom OpenTelemetry Collector that can receive telemetry data via the OTLP and export it to your third-party system by using a custom exporter.

[WARNING]
====
Red{nbsp}Hat does not support custom deployments.
====

.Prerequisites

* You have developed your own unsupported custom exporter that can export telemetry data via the OTLP to your third-party system.

.Procedure

* Deploy a custom Collector either through the OperatorHub or manually:

** If your third-party system supports it, deploy the custom Collector by using the OperatorHub.

** Deploy the custom Collector manually by using a config map, deployment, and service.
+
.Example of a custom Collector deployment
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-otel-collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      debug: {}
      prometheus:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug] # <1>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-otel-collector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: otel-collector
  template:
    metadata:
      labels:
        component: otel-collector
    spec:
      containers:
      - name: opentelemetry-collector
        image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest # <2>
        command:
        - "/otelcol-contrib"
        - "--config=/conf/otel-collector-config.yaml"
        ports:
        - name: otlp
          containerPort: 4317
          protocol: TCP
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
          readOnly: true
      volumes:
      - name: otel-collector-config-vol
        configMap:
          name: custom-otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: custom-otel-collector-service # <3>
  labels:
    component: otel-collector
spec:
  type: ClusterIP
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  selector:
    component: otel-collector
----
<1> Replace `debug` with the required exporter for your third-party system.
<2> Replace the image with the required version of the OpenTelemetry Collector that has the required exporter for your third-party system.
<3> The service name is used in the Red Hat build of OpenTelemetry Collector CR to configure the OTLP exporter.
