// Module included in the following assemblies:
//
// * observability/otel/otel-collector/otel-collector-connectors.adoc

:_mod-docs-content-type: REFERENCE
[id="otel-connectors-routing-connector_{context}"]
= Routing Connector

[role="_abstract"]
The Routing Connector routes logs, metrics, and traces to specified pipelines according to resource attributes and their routing conditions, which are written as OpenTelemetry Transformation Language (OTTL) statements.

:FeatureName: The Routing Connector
include::snippets/technology-preview.adoc[]

.OpenTelemetry Collector custom resource with an enabled Routing Connector
[source,yaml]
----
# ...
  config:
    connectors:
      routing:
        table: # <1>
          - statement: route() where attributes["X-Tenant"] == "dev" # <2>
            pipelines: [traces/dev] # <3>
          - statement: route() where attributes["X-Tenant"] == "prod"
            pipelines: [traces/prod]
        default_pipelines: [traces/dev] # <4>
        error_mode: ignore # <5>
        match_once: false # <6>
    service:
      pipelines:
        traces/in:
          receivers: [otlp]
          exporters: [routing]
        traces/dev:
          receivers: [routing]
          exporters: [otlp/dev]
        traces/prod:
          receivers: [routing]
          exporters: [otlp/prod]
# ...
----
<1> Connector routing table.
<2> Routing conditions written as OTTL statements.
<3> Destination pipelines for routing the matching telemetry data.
<4> Destination pipelines for routing the telemetry data for which no routing condition is satisfied.
<5> Error-handling mode: The `propagate` value is for logging an error and dropping the payload. The `ignore` value is for ignoring the condition and attempting to match with the next one. The `silent` value is the same as `ignore` but without logging the error. The default is `propagate`.
<6>  When set to `true`, the payload is routed only to the first pipeline whose routing condition is met. The default is `false`.
