// Module included in the following assemblies:
//
// * observability/otel/otel-troubleshooting.adoc

:_mod-docs-content-type: PROCEDURE
[id="troubleshooting-instrumentation_{context}"]
= Troubleshooting instrumentation

You can troubleshoot instrumentation issues as follows.

.Procedure

. Check the instrumentation object is created:
+
[source,console]
----
oc get instrumentation -n <your-project>
----

. Confirm that the application pods you wish to instrument are labeled correctly and the appropriate auto-instrumentation settings have been applied. For example, if you are instrumenting a Python application, you can check that the pods have the `instrumentation.opentelemetry.io/inject-python='true'` label:
+

[source,console]
----
oc get pods -n <your-project> -o jsonpath='{range .items[?(@.metadata.annotations["instrumentation.opentelemetry.io/inject-python"]=="true")]}{.metadata.name}{"\n"}{end}'
----

You should double-check the annotation applied to the instrumentation object is the correct one for the language you are instrumenting.

When defining a Deployment, remember that annotations can be added in either {{spec.metadata.annotations}} or {{spec.template.metadata.annotations}}. Ensure that the auto-instrumentation annotation is added to {{spec.template.metadata.annotations}}.

. Verify the endpoint that the instrumentation is transmitting data to:
+
[source,console]
----
oc get instrumentation <instrumentation-name> -n <your-project> -o jsonpath='{.spec.endpoint}'
----

By default, the endpoint is `http://localhost:4317`. This will work if you deployed the OpenTelemetry Collector as a sidecar container in your application pod. If you are using a different endpoint, you can update it by editing the instrumentation object and redeploying your application.

. Inspect your application logs for error messages that might suggest that the instrumentation is malfunctioning:
+
[source,console]
----
oc logs <application-pod> -n <your-project>
----

Some common errors include:
* Unable to automatically infer a package for instrumentation
* Unsupported application framework or version

You should be able to reproduce them without the usage of the operator and just using the OpenTelemetry SDK directly.

. Verify that the resources were deployed in the correct order

Deploy the Instrumentation resource before the application to ensure auto-instrumentation works correctly.

When the pod starts, the operator checks for the annotation to know if it needs to inject an instrumentation. It will check for an Instrumentation and inject auto-instrumentation into the pod based on the settings specified in the annotation. Generally, this process adds an init-container to the application’s pod, which is responsible for injecting the auto-instrumentation into the app container and some environment variables.

If the Instrumentation resource is not available when the application is deployed, the operator will not inject the auto-instrumentation. When you want to update the instrumentation settings, you need to delete the instrumentation object and redeploy the application.

To verify that the {{opentelemetry-auto-instrumentation}} init-container has successfully started, execute the following command:

[source,console]
----
oc get events -n <your-project>
----

You should see something like this:

[source,console]
----
... Created container opentelemetry-auto-instrumentation
... Started container opentelemetry-auto-instrumentation
----

If those messages are missing, then it means that was an issue while injecting the auto-instrumentation.

. Inspect for the operator logs for instrumentation errors:

[source,console]
----
oc logs -l app.kubernetes.io/name=opentelemetry-operator --container manager -n openshift-opentelemetry-operator --follow
----
