// Module included in the following assemblies:
//
// * observability/otel/otel-collector/otel-collector-extensions.adoc

:_mod-docs-content-type: REFERENCE
[id="otel-extensions-bearertokenauth-extension_{context}"]
= BearerTokenAuth Extension

[role="_abstract"]
The BearerTokenAuth Extension is an authenticator for receivers and exporters that are based on the HTTP and the gRPC protocol.
You can use the `OpenTelemetryCollector` custom resource to configure client authentication and server authentication for the BearerTokenAuth Extension on the receiver and exporter side.
This extension supports traces, metrics, and logs.

The following `OpenTelemetryCollector` custom resource configures client and server authentication for the BearerTokenAuth Extension:

[source,yaml]
----
# ...
  config:
    extensions:
      bearertokenauth:
        scheme: "Bearer"
        token: "<token>"
        filename: "<token_file>"

    receivers:
      otlp:
        protocols:
          http:
            auth:
              authenticator: bearertokenauth
    exporters:
      otlp_grpc:
        auth:
          authenticator: bearertokenauth

    service:
      extensions: [bearertokenauth]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp_grpc]
# ...
----
where:

`scheme`:: You can configure the BearerTokenAuth Extension to send a custom `scheme`. The default is `Bearer`.
`token`:: You can add the BearerTokenAuth Extension token as metadata to identify a message.
`filename`:: Path to a file that contains an authorization token that is transmitted with every message.
`http.auth.authenticator`:: You can assign the authenticator configuration to an OTLP Receiver.
`otlp.auth.authenticator`:: You can assign the authenticator configuration to an OTLP Exporter.
