// Module included in the following assemblies:
//
// * observability/otel/otel-collector/otel-collector-processors.adoc

:_mod-docs-content-type: REFERENCE
[id="otel-processors-cumulative-to-delta-processor_{context}"]
= Cumulative-to-Delta Processor

[role="_abstract"]
The Cumulative-to-Delta Processor converts monotonic, cumulative-sum, and histogram metrics to monotonic delta metrics.

You can filter metrics by using the `include:` or `exclude:` fields and specifying the `strict` or `regexp` metric name matching.

Because this processor calculates delta by storing the previous value of a metric, you must set up the metric source to send the metric data to a single stateful Collector instance rather than a deployment of multiple Collectors.

This processor does not convert non-monotonic sums and exponential histograms.

:FeatureName: The Cumulative-to-Delta Processor
include::snippets/technology-preview.adoc[]

The following is an example of an OpenTelemetry Collector custom resource with an enabled Cumulative-to-Delta Processor:

[source,yaml]
----
# ...
mode: sidecar
config:
  processors:
    cumulativetodelta:
      include:
        match_type: strict
        metrics:
        - <metric_1_name>
        - <metric_2_name>
      exclude:
        match_type: regexp
        metrics:
        - "<regular_expression_for_metric_names>"
# ...
----
where:

`mode`:: To tie the Collector's lifecycle to the metric source, you can run the Collector as a sidecar to the application that emits the cumulative temporality metrics.
`include`:: Optional: You can limit which metrics the processor converts by explicitly defining which metrics you want converted in this stanza. If you omit this field, the processor converts all metrics, except the metrics that are listed in the `exclude` field.
`match_type`:: Defines the value that you provided in the `metrics` field as an exact match by using the `strict` parameter or a regular expression by using the `regex` parameter.
`metrics`:: Lists the names of the metrics that you want to convert. The processor converts exact matches or matches for regular expressions. If a metric matches both the `include` and `exclude` filters, the `exclude` filter takes precedence.
`exclude`:: Optional: You can exclude certain metrics from conversion by explicitly defining them here.
