// Module included in the following assemblies:
//
// * networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.adoc

:_mod-docs-content-type: PROCEDURE
[id="patching-ovnk-address-ranges_{context}"]
= Patching OVN-Kubernetes address ranges

OVN-Kubernetes reserves the following IP address ranges:

* `100.64.0.0/16`. This IP address range is used for the `internalJoinSubnet` parameter of OVN-Kubernetes by default. 
* `100.88.0.0/16`. This IP address range is used for the `internalTransSwitchSubnet` parameter of OVN-Kubernetes by default.

If OpenShift SDN has been configured to use either of these IP address ranges, you must patch them to use a different IP address range before initiating the limited live migration.

.Prerequisites

* You have access to the cluster as a user with the `cluster-admin` role.

.Procedure

. Enter the following command to retrieve the names of nodes in your cluster along with the IP address ranges that those nodes use:
+
[source,terminal]
----
$ oc get nodes -o jsonpath='{range.items[*]}{.metadata.name}{"\t"}{.metadata.annotations.k8s\.ovn\.org/node-gateway-router-lrp-ifaddr}{"\n"}'
----
+
.Example output
+
[source,terminal]
----
---
<node_name> {"ipv4":"100.64.0.0/16"}
<node_name> {"ipv4":"100.88.0.0/16"}
---
----

. If the `100.64.0.0/16` IP address range is already in use, enter the following command to patch it to a different range. The following example uses  `100.63.0.0/16`.
+
[source,terminal]
----
$ oc patch network.operator.openshift.io cluster --type='merge' -p='{"spec":{"defaultNetwork":{"ovnKubernetesConfig":{"ipv4":{"internalJoinSubnet": "100.63.0.0/16"}}}}}'
----

. If the `100.88.0.0/16` IP address range is already in use, enter the following command to patch it to a different range. The following example uses  `100.99.0.0/16`.
+
[source,terminal]
----
$ oc patch network.operator.openshift.io cluster --type='merge' -p='{"spec":{"defaultNetwork":{"ovnKubernetesConfig":{"ipv4":{"internalTransitSwitchSubnet": "100.99.0.0/16"}}}}}'
----

