// Module included in the following assemblies:
//
// * storage/container_storage_interface/persistent-storage-csi-ibm-cloud-vpc-block.adoc

:_mod-docs-content-type: CONCEPT
[id="persistent-storage-csi-ibm-vpc-block-overview_{context}"]
= Overview of {ibm-cloud-name} VPC Block CSI Driver Operator

[role="_abstract"]
You can dynamically provision block storage volumes on {ibm-cloud-name} Virtual Private Cloud (VPC) infrastructure by using the Container Storage Interface (CSI) driver, which supports multiple IOPS tiers to match your workload performance requirements.

Familiarity with persistent storage and configuring CSI volumes is recommended when working with a CSI Operator and driver. For more information, see "Understanding persistent storage" and "Configuring CSI volumes".

To create CSI-provisioned PVs that mount to {ibm-cloud-name} VPC Block storage assets, {product-title} installs the {ibm-cloud-name} VPC Block CSI Driver Operator and the {ibm-cloud-name} VPC Block CSI driver by default in the `openshift-cluster-csi-drivers` namespace.

{ibm-cloud-name} VPC Block CSI Driver Operator::
The {ibm-cloud-name} VPC Block CSI Driver Operator provides three storage classes named `ibmc-vpc-block-10iops-tier` (default), `ibmc-vpc-block-5iops-tier`, and `ibmc-vpc-block-custom` for different tiers that you can use to create persistent volume claims (PVCs). The {ibm-cloud-name} VPC Block CSI Driver Operator supports dynamic volume provisioning by allowing storage volumes to be created on-demand, eliminating the need for cluster administrators to pre-provision storage. You can disable this default storage class if necessary (see "Managing the default storage class").

{ibm-cloud-name} VPC Block CSI driver::
The {ibm-cloud-name} VPC Block CSI driver enables you to create and mount {ibm-cloud-name} VPC Block PVs.
