// Module included in the following assemblies:
//
// * storage/container_storage_interface/persistent-storage-csi-migration.adoc

:_content-type: CONCEPT
[id="persistent-storage-csi-migration-automatic-ga_{context}"]
= Automatic migration of in-tree volumes to CSI

{product-title} supports automatic and seamless migration for the following in-tree volume types to their Container Storage Interface (CSI) driver counterpart:

* Azure Disk

* OpenStack Cinder

CSI migration for these volume types is considered generally available (GA), and requires no manual intervention.

For new {product-title} 4.11, and later, installations, the default storage class is the CSI storage class. All volumes provisioned using this storage class are CSI persistent volumes (PVs).

For clusters upgraded from 4.10, and earlier, to 4.11, and later, the CSI storage class is created, and is set as the default if no default storage class was set prior to the upgrade. In the very unlikely case that there is a storage class with the same name, the existing storage class remains unchanged. Any existing in-tree storage classes remain, and might be necessary for certain features, such as volume expansion to work for existing in-tree PVs. While storage class referencing to the in-tree storage plugin will continue working, we recommend that you switch the default storage class to the CSI storage class.
