// Module included in the following assemblies:
//
// * storage/container_storage_interface/persistent-storage-csi-secrets-store.adoc
//

:_mod-docs-content-type: PROCEDURE
[id="persistent-storage-csi-secrets-store-driver-uninstall_{context}"]
= Uninstalling the {secrets-store-operator}

.Prerequisites
* Access to the {product-title} web console.

* Administrator access to the cluster.

.Procedure

To uninstall the {secrets-store-operator}:

. Stop all application pods that use the `secrets-store.csi.k8s.io` provider.
. Remove any third-party provider plug-in for your chosen secret store.
. Remove the Container Storage Interface (CSI) driver and associated manifests:
.. Click *Administration* → *CustomResourceDefinitions* → *ClusterCSIDriver*.
.. On the *Instances* tab, for *secrets-store.csi.k8s.io*, on the far left side, click the drop-down menu, and then click *Delete ClusterCSIDriver*.
.. When prompted, click *Delete*.
. Verify that the CSI driver pods are no longer running.
. Uninstall the {secrets-store-operator}:
+
[NOTE]
====
Before you can uninstall the Operator, you must remove the CSI driver first.
====
+
.. Click *Ecosystem* -> *Installed Operators*.
.. On the *Installed Operators* page, scroll or type "Secrets Store CSI" into the *Search by name* box to find the Operator, and then click it.
.. On the upper, right of the *Installed Operators* > *Operator details* page, click *Actions* → *Uninstall Operator*.
.. When prompted on the *Uninstall Operator* window, click the *Uninstall* button to remove the Operator from the namespace. Any applications deployed by the Operator on the cluster need to be cleaned up manually.
+
After uninstalling, the {secrets-store-operator} is no longer listed in the *Installed Operators* section of the web console.
