// Module included in the following assemblies:
//
// * storage/container_storage_interface/persistent-storage-csi.adoc

[id="csi-drivers-supported_{context}"]
= CSI drivers supported by {product-title}

{product-title} supports certain CSI drivers that give users storage options that are not possible with in-tree volume plug-ins.

To create CSI-provisioned persistent volumes that mount to these supported storage assets, you can install and configure the CSI driver Operator, which will install the necessary CSI driver and storage class. For more details about installing the Operator and driver, see the documentation for the specific CSI Driver Operator.

The following table describes the CSI drivers that are available with {product-title} and which CSI features they support, such as volume snapshots, cloning, and resize.

.Supported CSI drivers and features in {product-title}
[cols=",^v,^v,^v", width="100%",options="header"]
|===
|CSI driver  |CSI volume snapshots  |CSI cloning  |CSI resize

|AWS EBS (Tech Preview) | ✅ | - | ✅
|OpenStack Manila | ✅ | ✅ | ✅
|===

[IMPORTANT]
====
If your CSI driver is not listed in the preceding table, you must follow the installation instructions provided by your CSI storage vendor to use their supported CSI features.
====
