// Module included in the following assemblies:
//
// * storage/container_storage_interface/persistent-storage-csi-migration.adoc

:_content-type: CONCEPT
[id="persistent-storage-csi-migration-overview_{context}"]
= Overview

Volumes provisioned by using in-tree storage plug-ins supported by this feature are migrated to their counterpart Container Storage Interface (CSI) drivers. This process does not involve any data migration, {product-title} only translates the persistent volume object in memory. As a result, the translated persistent volume object is not stored on disk, nor is its contents changed.

CSI automatic migration should be seamless. This feature does not change how you use all existing API objects: for example, `PersistentVolumes`, `PersistentVolumeClaims`, and `StorageClasses`.

Enabling CSI automatic migration for in-tree persistent volumes (PVs) or persistent volume claims (PVCs) does not enable any new CSI driver features, such as snapshots or expansion if the original in-tree storage plug-in did not support it.
