// Module included in the following assemblies:
//
// * storage/persistent_storage/persistent-storage-csi-snapshots.adoc

[id="persistent-storage-csi-snapshots-create_{context}"]
= Creating a volume snapshot

When you create a VolumeSnapshot object, {product-title} creates a volume snapshot.

.Prerequisites
* Logged in to a running {product-title} cluster.
* A PVC created using a CSI driver that supports VolumeSnapshot objects.
* A storage class to provision the storage backend.

.Procedure

To dynamically create a volume snapshot:

. Create a file with the VolumeSnapshotClass object described by the following YAML:

+
.volumesnapshotclass.yaml
[source,yaml]
----
apiVersion: snapshot.storage.k8s.io
kind: VolumeSnapshotClass <1>
metadata:
  name: csi-hostpath-snap
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true" <2>
driver: hostpath.csi.k8s.io
deletionPolicy: Delete
----
<1> Allows you to specify different attributes belonging to a VolumeSnapshot.
<2> Optional. This annotation can be used to create a default VolumeSnapshotClass. This object will be used when VolumeSnapshot does not specify any explicit volumeSnapshotClassName.

+
. Create the object you saved in the previous step by running the following command:
+
----
$ oc create -f volumesnapshotclass.yaml
----

. Create a VolumeSnapshot object:

+
.volumesnapshot-dynamic.yaml
[source,yaml]
----
apiVersion: snapshot.storage.k8s.io
kind: VolumeSnapshot
metadata:
  name: mysnap
spec:
  volumeSnapshotClassName: csi-hostpath-snap <1>
  source:
    persistentVolumeClaimName: myclaim <2>
----

<1> The request for a particular class by the volume snapshot. If the parameter is not specified, the default class is used.
+
[NOTE]
====
If no default class is set and `volumeSnapshotClassName` is empty, then no snapshot is created.
====
+
<2> The name of the PersistentVolumeClaim object bound to a persistent volume. This defines what you want to create a snapshot of. Required for dynamically provisioning a snapshot.

+
. Create the object you saved in the previous step:
+
----
$ oc create -f volumesnapshot.yaml
----


To manually provision a snapshot:

. Provide a value for the volumeSnapshotContentName parameter as the source for the snapshot, in addition to defining volume snapshot class as shown above.
+
.volumesnapshot-manual.yaml
[source,yaml]
----
apiVersion: snapshot.storage.k8s.io
kind: VolumeSnapshot
metadata:
  name: snapshot-demo
spec:
  source:
    volumeSnapshotContentName: mycontent <1>
----
<1> The volumeSnapshotContentName parameter is required for pre-provisioned snapshots.

. Create the object you saved in the previous step:
+
----
$ oc create -f volumesnapshot.yaml
----

After the snapshot has been created in the cluster, additional details about the snapshot are available.

. Display details about the volume snapshot that was created by running the following command:
+
----
$ oc describe volumesnapshot mysnap
----

The following example displays details about the `mysnap` volume snapshot:

.volumesnapshot.yaml
[source,yaml]
----
apiVersion: snapshot.storage.k8s.io
kind: VolumeSnapshot
metadata:
  name: mysnap
spec:
  source:
    persistentVolumeClaimName: myclaim
  volumeSnapshotClassName: csi-hostpath-snap
status:
  boundVolumeSnapshotContentName: snapcontent-1af4989e-a365-4286-96f8-d5dcd65d78d6 <1>
  creationTime: "2020-01-29T12:24:30Z" <2>
  readyToUse: true <3>
  restoreSize: 500Mi
----
<1> The pointer to the actual storage content that was created by the controller.
<2> The time when the snapshot was created. The snapshot contains the volume content that was available at this indicated time.
<3> If the value is set to `true`, the snapshot can be used to restore as a new PVC.
  +
If the value is set to `false`, the snapshot was created. However, the storage backend needs to perform additional tasks to make the snapshot usable so that it can be restored as a new volume. For example, Amazon Elastic Block Store data might be moved to a different, less expensive location, which can take several minutes.

To verify that the volume snapshot was created automatically, run the following command:

----
$ oc get volumesnapshotcontent
----

The pointer to the actual content is displayed. When the `boundVolumeSnapshotContentName` field is populated, it means that there is a corresponding VolumeSnapshotContent.

To verify that the snapshot is ready, confirm that the VolumeSnapshot has `readyToUse: true`.
