// Module included in the following assemblies:
//
// * storage/container_storage_interface/persistent-storage-csi-vol-populators.adoc

:_mod-docs-content-type: PROCEDURE
[id="persistent-storage-csi-vol-populator-procedure_{context}"]
= Creating prepopulated volumes using volume populators

[role="_abstract"]
To create volumes that are automatically filled with data when provisioned, define a Custom Resource Definition (CRD) as a data source and reference it when creating the persistent volume claim (PVC).

The following procedure explains how to create a prepopulated PVC using the example `hellos.hello.example.com` CRD created previously. 

In this example, rather than using an actual data source, you are creating a file called "example.txt" that contains the string "Hello, world!" in the root directory of the volume. For a real-world implementation, you need to create your own volume populator.

.Prerequisites
* You are logged in to a running {product-title} cluster.
* There is an existing CRD for volume populators.
* {product-title} does not ship with any volume populators. You *must* create your own volume populator.

.Procedure
. Create a Custom Resource (CR) instance of the `Hello` CRD with the text "Hello, World!" passed in as `fileContents` parameter by running the following command:
+
[source,terminal]
----
$ oc apply -f  - <<EOF
apiVersion: hello.example.com/v1alpha1
kind: Hello
metadata:
  name: example-hello
spec:
  fileName: example.txt
  fileContents: Hello, world!
EOF
----

. Create a PVC that references the Hello CR similar to the following example file:
+
.Example PVC YAML file
[source,yaml]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  dataSourceRef:
    apiGroup: hello.example.com
    kind: Hello
    name: example-hello
  volumeMode: Filesystem
----
+
* `spec.dataSourceRef`: Specifies the data source for the PVC.
* `spec.dataSourceRef.name`: Specifies the name of the CR that you are using as the data source. In this example, it is 'example-hello'.

.Verification
. After a few minutes, ensure that the PVC is created and in the `Bound` status by running the following command:
+
[source,terminal]
----
$ oc get pvc example-pvc -n hello
----
+
In this example, the name of the PVC is `example-pvc`.
+
.Example output
[source,terminal]
----
NAME          STATUS    VOLUME        CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
example-pvc   Bound     my-pv         10Mi       ReadWriteOnce  gp3-csi        <unset>                 14s
----

. Create a job that reads from the PVC to verify that the data source information was applied using the following example file:
+
.Example job YAML file
[source,yaml]
----
apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    spec:
      containers:
        - name: example-container
          image: busybox:latest
          command:
            - cat
            - /mnt/example.txt
          volumeMounts:
            - name: vol
              mountPath: /mnt
      restartPolicy: Never
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: example-pvc
----
+
* `spec.template.spec.containers.command`: Specifies the location and name of the file with the "Hello, world!" text. In this example, the location is "/mnt/example.txt".
* `spec.template.spec.volumes.persistentVolumeClaim`: Specifies the name of the PVC you created in Step 2. In this example, it is `example-pvc`.

. Start the job by running the following command:
+
[source,terminal]
----
$ oc run example-job --image=busybox --command -- sleep 30 --restart=OnFailure
----
+
.Example output
[source,terminal]
----
pod/example-job created
----

. Wait for the job, and all of its dependencies, to finish by running the following command:
+
[source,terminal]
----
$ oc wait --for=condition=Complete pod/example-job
----

. Verify the contents collected by the job by running the following command:
+
[source,terminal]
----
$ oc logs job/example-job
----
+
.Example expected output
[source,terminal]
----
Hello, world!
----
