// Module included in the following assemblies:
//
// * storage/container_storage_interface/persistent-storage-csi-gcp-pd.adoc

:_mod-docs-content-type: CONCEPT
[id="persistent-storage-csi-gcp-images-snapshot-class-overview_{context}"]
= Volume snapshot class csi-gce-pd-vsc-images

[role="_abstract"]
By default, you cannot restore more than six volumes per snapshot per hour. So in Kubevirt environments, you normally cannot create more than six VMs per hour from a "golden image" (templates saved as snapshots).

For Google Cloud Platform (GCP) persistent disk (PD) storage  CSI, there is a non-default `VolumeSnapshotClass`, named `csi-gce-pd-vsc-images`, that uses the `snapshot-type`: `images` parameter. When using KubeVirt, it allows you overcome the six VMs per hour restriction, so that you can create VMs from "golden images". 

[NOTE]
====
Snapshots using the images snapshot class are strictly limited to ReadWriteOnce (RWO) sources, but you can restore them to ReadWriteMany (RWX)  hyperdisk-balanced disks.
====

For more information, see, under _Additional Resources_, Section _Volume snapshots CRD: VolumeSnapshotClass_.
