// Module included in the following assemblies:

// * power_monitoring/installing-power-monitoring.adoc

:_mod-docs-content-type: PROCEDURE
[id="power-monitoring-installing-pmo_{context}"]
= Installing the {PM-operator}

[role="_abstract"]
Install the {PM-operator} from the software catalog using the {ocp} web console to enable power consumption monitoring capabilities on your cluster.

The {PM-operator} manages the deployment and configuration of {pm-Kepler}, which collects real-time power metrics from cluster nodes.

[WARNING]
====
You must remove any previously installed versions of the {PM-operator} before installation.
====

.Prerequisites
* You have access to the {ocp} web console.
* You are logged in as a user with the `cluster-admin` role.

.Procedure

. In the web console, go to *Ecosystem* -> *Software Catalog*.

. Search for `{PM-shortname}`, click the *{product-title}* tile, and then click *Install*.
//. On the *Install Operator* page:
//.. Select an *Update channel*.
//.. Select a {PM-shortname} *Version* to install.
// This can be included once the user has options there to choose. Not needed for now.

. Click *Install* again to install the {PM-operator}.
+
{product-title} is now available in all namespaces of the {ocp} cluster.

.Verification

. Verify that the {PM-operator} is listed in *Ecosystem* -> *Installed Operators*. The *Status* should resolve to *Succeeded*.
