// Module included in the following assemblies:
//
// * develop/rhcl-api-management.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-rhcl-enable-rhdh-plugin_{context}"]
= Enabling the {prodname} {rhdh} console plugin

[role="_abstract"]
If you have a subscription to {rhdh}, you can use the web console as your internal developer portal. You must enable the {prodname} {rhdh} plugin in the `Kuadrant` custom resource (CR) you created during installation before you can use {rhdh}.

You can skip this procedure if you enabled the {rhdh} plugin during {prodname} installation.

.Prerequisites

* You installed {prodname}.
* You have a {rhdh} subscription.
* You are logged into {ocp} as a cluster administrator.
* You are using a supported configuration of {ocp} and required components.
* You installed the {oc-first}.

.Procedure

. If you have a {rhdh} subscription, update your {prodname} CR with the {rhdh} plugin enabled by using the following example:
+
[source,yaml]
----
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
#...
spec:
  components:
    developerPortal:
      enabled: true
#...
----

. Apply the CR by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc apply -f _<kuadrant.yaml>_
----
+
Replace `_<kuadrant.yaml>_` with the name of your {prodname} deployment YAML.

.Verification

. Check the status of the {prodname} CR generation by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc wait kuadrant/kuadrant --for="condition=Ready=true" -n _<kuadrant_system>_ --timeout=300s
----
+
Replace `_<kuadrant_system>_` with the namespace you used.
+
.Example output
[source,text]
----
kuadrant.kuadrant.io/kuadrant Ready
----

. Check that the {rhdh} pod is ready by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ oc wait pod -n _<kuadrant_system>_ -l app=developer-portal-controller --for=condition=Ready --timeout=120s
----
+
Replace `_<kuadrant_system>_` with the namespace you used.
+
.Example output
[source,text]
----
pod/developer-portal-controller-7f8d69bc7b-x4z2q condition met
----
+
The exact random string at the end of the pod name varies based on your deployment replica set.
