
// Module included in the following assemblies:
//
// *observability/observability.adoc

:_mod-docs-content-type: PROCEDURE
[id="rhcl-enable-observability-monitor_{context}"]
= Enable observability monitoring in {prodname}

[role="_abstract"]
By enabling observability monitoring, you can view context, historical trends, and alerts based on the metrics you configure. After you have configured your monitoring stack, use this step to expose metrics endpoints, deploy monitoring resources, and configure the Envoy gateway.

When you enable observability monitoring, the following events occur:

* {prodname} creates `ServiceMonitor` and `PodMonitor` custom resource definitions (CRDs) for its components in the namespace where {prodname} is.
* A single set of monitors is created in each gateway namespace to scrape metrics from any gateways.
* Monitors also scrape metrics from the corresponding gateway system namespace, generally the `istio-system` namespace.

You can delete and re-create monitors as required. Monitors are only ever created or deleted, and not updated or reverted. The following procedure is optional. You can create your own `ServiceMonitor` or `PodMonitor` definitions, or configure `prometheus` metrics directly.

[IMPORTANT]
====
To use {prodname} observability dashboards, you must enable observability on each {ocp} cluster that {prodname} runs on.
====

.Prerequisites

* You installed {prodname}.
* You have administrator access to your {ocp} cluster.
* You configured observability metrics.

.Procedure

* To enable default observability for {prodname} and any gateways, set `spec.observability.enable` parameter value to `true` in your `Kuadrant` custom resource (CR):
+
.Example `Kuadrant` CR
[source,yaml]
----
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant-sample
spec:
  observability:
    enable: true
# ...
----
+
You can also set the `spec.observability.enable` to `false` and create your own `ServiceMonitor` or `PodMonitor` definitions, or configure Prometheus directly.

.Verification

* Check the created monitors by running the following command:
+
[source,terminal]
----
$ oc get servicemonitor,podmonitor -A -l kuadrant.io/observability=true
----
//Q: example output?
