// Module included in the following assemblies:
//
// * hardware_enablement/psap-node-feature-discovery-operator.adoc

ifeval::["{context}" == "operator-reference"]
:operators:
endif::[]
ifeval::["{context}" == "node-feature-discovery-operator"]
:perf:
endif::[]
:_mod-docs-content-type: CONCEPT
[id="about-node-feature-discovery-operator_{context}"]
ifdef::operators[]
= Node Feature Discovery Operator

endif::operators[]
ifdef::perf[]
= About the Node Feature Discovery Operator

endif::perf[]
The Node Feature Discovery Operator (NFD) manages the detection of hardware features and configuration in an {product-title} cluster by labeling the nodes with hardware-specific information. NFD labels the host with node-specific attributes, such as PCI cards, kernel, operating system version, and so on.

The NFD Operator can be found on the Operator Hub by searching for “Node Feature Discovery”.
ifdef::operators[]

== Project

link:https://github.com/openshift/cluster-nfd-operator[cluster-nfd-operator]
endif::operators[]
