// Module included in the following assemblies:
//
// * operating/visualizing-external-entities.adoc
:_mod-docs-content-type: REFERENCE
[id="querying-external-entities-using-api_{context}"]
= Querying external IP addresses by using the API

[role="_abstract"]
You can get information about the external IP addresses associated with a specific cluster by using the following endpoints:

* `/v1/networkgraph/cluster/{clusterId}/externalentities`: This endpoint returns a list of external entities for a given cluster ID. Each entity includes the following information:
+
** *Name*: The name of the external entity.
** *CIDR block*: The CIDR block associated with the entity.
** *Default entity*: Indicates that the entity is a CIDR-block definition provided by the system.
** *Discovered*: If `true`, indicates that the external IP address does not match any specified CIDR block.
* `/v1/networkgraph/cluster/{clusterId}/externalentities/flows/{deploymentId}`: This endpoint reports the flows to and from external entities for a given cluster ID and deployment ID. Use this endpoint to analyze network traffic patterns and gain insights into the interactions between your cluster and external entities.
