// Module included in the following assemblies:
//
// * installing/acs-recommended-requirements.adoc
:_mod-docs-content-type: CONCEPT
[id="recommended-requirements-central-services_{context}"]
= Central services (self-managed)

[NOTE]
====
If you are using {rh-rhacscs-first}, you do not need to review the requirements for Central services, because they are managed by Red Hat. You only need to look at the requirements for secured cluster services.
====

Central services contain the following components:

* Central
* Scanner
+
[NOTE]
====
For default resource requirements for the scanner, see the default resource requirements page.
====

[id="recommended-requirements-central-services-central_{context}"]
== Central

[discrete]
== Memory and CPU requirements

The following table lists the minimum memory and CPU values required to run Central for one secured cluster. The table includes the number of concurrent web portal users.

|===
| Deployments | Concurrent web portal users | CPU | Memory

| < 25,000
| 1 user
| 2 cores
| 8 GiB

| < 25,000
| < 5 users
| 6 cores
| 12 GiB

| < 50,000
| 1 user
| 2 cores
| 12 GiB

| < 50,000
| < 5 users
| 6 cores
| 16 GiB
|===

[id="recommended-requirements-central-services-scanner_{context}"]
== Scanner

[discrete]
== Memory and CPU requirements

The following table lists the minimum memory and CPU values required for the scanner deployment in the Central cluster. The table includes the number of unique images deployed in all secured clusters.

|===
| Unique Images | Replicas | CPU | Memory

| < 100
| 1 replica
| 1 core
| 1.5 GiB

| < 500
| 1 replica
| 2 cores
| 2.5 GiB

| < 2000
| 2 replicas
| 2 cores
| 2.5 GiB

| < 5000
| 3 replicas
| 2 cores
| 2.5 GiB
|===
