// Module included in the following assemblies:
//
// * registry/configuring-registry-operator.adoc


[id="registry-operator-config-resources-storage-credentials_{context}"]
= Configuring storage credentials for the Image Registry Operator

In addition to the `configs.imageregistry.operator.openshift.io` and ConfigMap
resources, storage credential configuration is provided to the Operator by a separate secret
resource located within the `openshift-image-registry` namespace.

The `image-registry-private-configuration-user` secret provides
credentials needed for storage access and management. It overrides the default
credentials used by the Operator, if default credentials were found.

.Procedure

* Create an {product-title} secret that contains the required keys.
+
[source,subs="attributes+"]
----
$ oc create secret generic image-registry-private-configuration-user --from-file=KEY1=value1 --from-literal=KEY2=value2 --namespace openshift-image-registry
----


// Undefine the attribute to catch any errors at the end
:!KEY1:
