// Module included in the following assemblies:
//
// * registry/configuring_registry_storage/configuring-registry-storage-baremetal.adoc
// * registry/configuring_registry_storage/configuring-registry-storage-vsphere.adoc
// * registry/configuring_registry_storage/configuring-registry-storage-nutanix.adoc
// * registry/configuring_registry_storage/configuring-registry-storage-rhodf.adoc

:_mod-docs-content-type: PROCEDURE
[id="registry-configuring-registry-storage-s3-redirect_{context}"]
= Configuring Image Registry Operator redirects for S3-compatible storage

[role="_abstract"]
You can configure the Image Registry Operator `disableRedirect` parameter to control whether clients pull image data directly from S3-compatible object storage or through the registry. The default value is `false`, which redirects clients to the storage endpoint.

By default, the Image Registry Operator redirects clients such as cluster nodes and external container tools to pull image layers directly from the object storage back end. Redirects reduce load on the registry. If clients cannot reach, resolve, or trust that storage endpoint, image pulls fail.

[IMPORTANT]
====
If you set the `spec.storage.s3.regionEndpoint` field to a cluster-internal service DNS name, for example `s3.openshift-storage.svc` or `rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local`, and you leave `spec.disableRedirect` set to `false`, the registry redirects clients to that service hostname. Cluster nodes and external clients cannot resolve `.svc` hostnames, so image pulls fail with DNS errors such as `no such host`.

To prevent these failures, set `spec.disableRedirect` to `true` so that the registry proxies the traffic, or configure `regionEndpoint` to a hostname that clients can resolve, such as an object storage route.
====

[NOTE]
====
Setting `disableRedirect` to `true` increases the network bandwidth and other resources that the image registry requires, because all image data passes through the registry.
====

.Prerequisites

* You have access to the cluster as a user with the `cluster-admin` role.
* You installed the `oc` CLI.
* You configured the image registry to use S3-compatible object storage.

.Procedure

* To configure the image registry to proxy traffic instead of redirecting clients to the S3 storage endpoint, set the `spec.disableRedirect` field in the `configs.imageregistry.operator.openshift.io` object to `true` by running the following command:
+
[source,terminal]
----
$ oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"disableRedirect":true}}'
----

.Verification

* Verify that `disableRedirect` is set to `true` by running the following command:
+
[source,terminal]
----
$ oc get configs.imageregistry.operator.openshift.io cluster -o jsonpath='{.spec.disableRedirect}{"\n"}'
----
+
.Example output
[source,terminal]
----
true
----
