// Module included in the following assemblies:
//
//
// GCP assemblies:
// * installing/installing_gcp/installing-gcp-customizations.adoc
// * installing/installing_gcp/installing-gcp-network-customizations.adoc
// * installing/installing_gcp/installing-restricted-networks-gcp-installer-provisioned.adoc
// * installing/installing_gcp/installing-gcp-vpc.adoc
// * installing/installing_gcp/installing-gcp-shared-vpc.adoc
// * installing/installing_gcp/installing-gcp-private.adoc

:_mod-docs-content-type: PROCEDURE
[id="restricting-sa-impersonation-compute-sa-gcp_{context}"]
= Restricting service account impersonation to the compute service account

[role="_abstract"]
After you use the Cloud Credential Operator utility (`ccoctl`) to create the resources that the cluster requires, you can reduce the scope of the service account impersonation permission.
You can apply the {gcp-first} `iam.serviceAccounts.actAs` permission to only the Machine API compute service account instead of having it apply at the project level.

The `ccoctl` utility assigns custom and {gcp-short} predefined roles to  {product-title} components service accounts.
To reduce the scope of the `iam.serviceAccounts.actAs` permission, you identify the custom role for the Machine API controller and replace it with a role that has a more restricted set of permissions.
To allow this component to work, you then grant it the Service Account User role for the service account of the compute node instead.

.Prerequisites

* You have configured an account with the cloud platform that hosts your cluster.
* You have used the `ccoctl` utility to create the cloud provider resources for your cluster and moved the manifest files that the utility created to the correct directories for the installation program.
* You have access to your `install-config.yaml` file.
* You have logged in to the {gcp-full} CLI (`gcloud`) as a user with permissions to manage service accounts and roles.

.Procedure

. Obtain the following values from your `install-config.yaml` file:

** The {gcp-short} project name.
In the YAML file, this is the value of the `platform.gcp.projectID` parameter.

** The cluster name.
In the YAML file, this is the value of the `metadata.name` parameter.

. In the {gcp-full} CLI, select the {gcp-short} project where you plan to deploy {product-title}.

. List the identity and access management (IAM) roles in your project by running the following command:
+
[source,terminal]
----
$ gcloud iam roles list --project=<project_name>
----
+
where `<project_name>` is the {gcp-short} project name specified in the `install-config.yaml` file.

. In the output, identify the custom role for the Machine API controller.
The role name format is `<project_prefix>_openshiftmachineapigcp`, where `<project_prefix>` is a simplified version of the project name.
+
For example, the project name `my-openshift-project` might become the prefix `myopenshiftproject` and the resulting role name would be `myopenshiftproject_openshiftmachineapigcp`.

. Identify the custom role permissions for the Machine API controller by running the following command:
+
[source,terminal]
----
$ gcloud iam roles describe <machine_api_role> --project <project_name>
----
+
where `<machine_api_role>` is the custom role for the Machine API controller.
+
.Example output
[source,text]
----
etag: <etag_value>
includedPermissions:
- compute.acceleratorTypes.get
- compute.acceleratorTypes.list
- compute.disks.create
- compute.disks.createTagBinding
...
- compute.zones.get
- compute.zones.list
- iam.serviceAccounts.actAs
- iam.serviceAccounts.get
- iam.serviceAccounts.list
- resourcemanager.tagValues.get
- resourcemanager.tagValues.list
- serviceusage.quotas.get
- serviceusage.services.get
- serviceusage.services.list
name: projects/<project_name>/roles/<machine_api_role>
stage: GA
title: <cluster_name>-openshift-machine-api-gcp
----
+
where `<cluster_name>` is the cluster name specified in the `install-config.yaml` file.
+
[NOTE]
====
This truncated list might not match the list for your cluster.
====

. Create a custom role that includes all of the permissions from your output except for the `iam.serviceAccounts.actAs` permission by running a command similar to the following:
+
[source,terminal]
----
gcloud iam roles create <project_prefix>_openshiftmachineapigcp_without_actas \
--project=<project_name> \
--title=<project_prefix>_openshiftmachineapigcp_without_actas \
--description="Required permissions for the Machine API controller without the iam.serviceAccounts.actAs permission" \
--permissions=compute.acceleratorTypes.get,\
compute.acceleratorTypes.list,\
compute.disks.create,\
compute.disks.createTagBinding,\
// ...\
compute.zones.get,\
compute.zones.list,\
iam.serviceAccounts.get,\
iam.serviceAccounts.list,\
resourcemanager.tagValues.get,\
resourcemanager.tagValues.list,\
serviceusage.quotas.get,\
serviceusage.services.get,\
serviceusage.services.list
----
+
[IMPORTANT]
====
This truncated list might not match the list for your cluster.
You must use the list of permissions from the output of the command on your cluster.
====

. List the service accounts in your project by running the following command:
+
[source,terminal]
----
$ gcloud iam service-accounts list
----
. In the output, identify the service account for the Machine API controller.
The service account name format is `<account_string>@<project_name>.iam.gserviceaccount.com`.
+
#In Jianli's example, this is `ci-op-47h68z-openshift-m-9bcp6@openshift-qe.iam.gserviceaccount.com`. How do we know that the `ci-op-47h68z-openshift-m-9bcp6` string is the one for the MAPI controller account? Or is that example SA irrelevant here?#

. Remove the custom role that includes the `iam.serviceAccounts.actAs` permission from the Machine API controller service account by running the following command:
+
[source,terminal]
----
$ gcloud projects remove-iam-policy-binding <project_name> \
  --member "serviceAccount:<machine_api_controller_service_account>" \
  --role "projects/<project_name>/roles/<project_prefix>_openshiftmachineapigcp"
----
+
where `<machine_api_controller_service_account>` is the Machine API controller service account.

. Grant the custom role that excludes the `iam.serviceAccounts.actAs` permission to the Machine API controller service account by running the following command:
+
[source,terminal]
----
$ gcloud projects add-iam-policy-binding openshift-qe \
  --member "serviceAccount:<machine_api_controller_service_account>" \
  --role "projects/<project_name>/roles/<project_prefix>_openshiftmachineapigcp_without_actas
----

. Grant the Machine API controller service account the Service Account User role for the service account of the compute node by running the following command:
+
[source,terminal]
----
$ gcloud iam service-accounts add-iam-policy-binding <compute_service_account>@<project_name>.iam.gserviceaccount.com \
  --member="serviceAccount:<machine_api_controller_service_account>" \
  --role=roles/iam.serviceAccountUser
----
+
where `<compute_service_account>` is the service account for your compute nodes.
+
#Not clear how to find this one exactly or what it looks like.#