// Module included in the following assemblies:
//
// * operating/manage-vulnerabilities/scan-rhcos-node-host.adoc

:_mod-docs-content-type: CONCEPT
[id="rhcos-node-scanning-overview_{context}"]
= {op-system} node scanning overview

[role="_abstract"]
{product-title-short} scans {op-system} RPMs installed on node hosts for known vulnerabilities by analyzing components and matching them against security data streams.

{product-title-short} scans {op-system} RPMs installed on the node host, as part of the {op-system} installation, for any known vulnerabilities.

First, {product-title-short} analyzes and detects {op-system} components. Then it matches vulnerabilities for identified components by using {op-system-base} and the following data streams:

* OpenShift 4.X Open Vulnerability and Assessment Language (OVAL) v2 security data streams if you use StackRox Scanner for node scanning.
* Red{nbsp}Hat Common Security Advisory Framework (CSAF) Vulnerability Exploitability eXchange (VEX) if you use Scanner V4 for node scanning.

[NOTE]
====
* If you installed {product-title-short} by using the `roxctl` CLI, you must manually enable the {op-system} node scanning features. When you use Helm or Operator installation methods on {ocp}, the feature enables by default.
====
