// Module included in the following assemblies:
//
// * rosa_getting_started_sts/rosa-sts-aws-prereqs.adoc

[id="rosa-setting-the-aws-security-token-version_{context}"]
= Setting the AWS security token version

If you want to create a {product-title} (ROSA) cluster with the AWS Security Token Service (STS) in an AWS opt-in region, you must set the security token version to version 2 in your AWS account.

.Prerequisites

* You have installed and configured the latest AWS CLI on your installation host.

.Procedure

. List the ID of the AWS account that is defined in your AWS CLI configuration:
+
[source,terminal]
----
$ aws sts get-caller-identity --query Account --output json
----
+
Ensure that the output matches the ID of the relevant AWS account.

. List the security token version that is set in your AWS account:
+
[source,terminal]
----
$ aws iam get-account-summary --query SummaryMap.GlobalEndpointTokenVersion --output json
----
+
.Example output
+
[source,terminal]
----
1
----

. To update the security token version to version 2 for all regions in your AWS account, run the following command:
+
[source,terminal]
----
$ aws iam set-security-token-service-preferences --global-endpoint-token-version v2Token
----
+
[IMPORTANT]
====
Updating to security token version 2 can impact the systems that store the tokens, due to the increased token length. For more information, see link:https://docs.aws.amazon.com/cli/latest/reference/iam/set-security-token-service-preferences.html[the AWS documentation on setting STS preferences].
====
