// Module included in the following assemblies:
//
// * observability/logging/rosa-forwarding-control-plane-logs.adoc
:_mod-docs-content-type: PROCEDURE
[id="rosa-edit-cluster-log-forwarding-ui_{context}"]
= Edit a {product-title} cluster with log forwarding

[role="_abstract"]
You can verify the status of log forwarding for a cluster and edit the log forwarding configurations.

.Procedure

. In the {hybrid-console}, go to *Clusters* -> *Cluster List*, then click the name of your cluster.
. Go to the *Settings* tab then the *Control plane log forwarding* section.
. To add to your log forwarding, click the *Add configuration* dropdown button.
.. You can add a `CloudWatch` or `Amazon S3` configuration.
. To make changes to your existing log forwarding, click the three dots within your `CloudWatch` or `Amazon S3` log forwarding configuration, then select *Edit configuration* or *Delete configuration*.
. When you click *Edit configuration* for `Amazon S3` log forwarding, you see your configuration and can make changes to the following:
* *Bucket Name*
* *Bucket Prefix*
* *Select groups and applications*
. When you click *Edit configuration* for `CloudWatch` log forwarding, you see your configuration and can make changes to the following:
* *Log group name*
* *Role ARN*
* *Select groups and applications*
. Make the changes to your configuration, then click *Save*.

.Verification

. In the *Settings* tab -> *Control plane log forwarding* section, verify that you see the changes you made to your configuration. The changes you made instantly go through and appear in this section.
