// Module included in the following assembles
//
// * rosa_hcp/terraform/rosa-hcp-config-aws-spot-instances-terraform.adoc

:_mod-docs-content-type: PROCEDURE

[id="rosa-hcp-config-spot-instance-terraform-create-cluser_{context}"]
= Using Terraform to create a new {product-title} cluster with Spot instances (Day-0)

[role="_abstract"]
After you create or update your Terrform variables file, you can add the cluster resource to your main file and initiate Terraform. The process for simple mode and enhanced mode differ by the omission or inclusion respectively of the `termination_handler_queue_url` attribute. The machine pool configuration is identical for both simple and enhanced modes.

.Procedure

. Add the cluster resouce to your `main.tf` file:
+
[source,text]
----
resource "rhcs_cluster_rosa_hcp" "cluster" {
  name                          = var.cluster_name
  cloud_region                  = var.aws_region
  aws_account_id                = var.aws_account_id
  operator_role_arn             = var.operator_role_arn
  termination_handler_queue_url = aws_sqs_queue.spot_termination.url # Enhanced mode only
}
----

. Add a Spot machine pool resource to your `main.tf` file:
+
[source,text]
----
resource "rhcs_hcp_machine_pool" "spot_pool" {
  cluster       = rhcs_cluster_rosa_hcp.cluster.id
  name          = "spot-workers"
  instance_type = "m5.xlarge"

  autoscaling {
    enabled      = true
    min_replicas = 2
    max_replicas = 10
  }

  spot_market_options {
    max_price = "0.75"
  }
}
----
+
[IMPORTANT]
====
The `spot_market_options` block is immutable after creation. You cannot add this block to an existing on-demand machine pool, or remove it from a Spot machine pool. You must create a new machine pool with the desired configuration and remove the old machine pool resource from your Terraform configuration.
====

. Apply the configuration:
+
[source,termina]
----
$ terraform init && terraform plan && terraform apply -auto-approve
----
+
The AWS Node Termination Handler is automatically created in the hosted control plane namespace once the cluster is ready and at least one Spot NodePool exists.
