// Module included in the following assemblies:
//
// * maps/jobs/rosa-classic-plan-cluster-upgrades.adoc

:_mod-docs-content-type: CONCEPT
[id="rosa-classic-plan-cluster-upgrades_{context}"]
= Plan cluster upgrades

[role="_abstract"]
Plan your {product-title} cluster upgrades by reviewing the update life cycle policy, available upgrade channels, and how to switch channels to view upgrade options.

//Content from modules/rosa-upgrading-lifecycle-policy.adoc
The "{product-title} update life cycle" page, linked in the _Additional resources_, includes release definitions, support and update requirements, installation policy information and life cycle dates.

You can use update channels to decide which {product-title} minor version to update your clusters to. {product-title} supports updates through the `stable-4.y`, `eus-4.y`, and `fast-4.y` channels.

[role="_additional-resources"]
.Additional resources
* link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws_classic_architecture/4/html-single/introduction_to_rosa/index#rosa-life-cycle[{product-title} update life cycle]
* link:https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/updating_clusters/understanding-openshift-updates-1#understanding-update-channels-releases[Understanding update channels and releases]
