// Module included in the following assemblies:
//
// * rosa_architecture/rosa-sts-about-iam-resources.adoc
// * rosa_planning/rosa-sts-ocm-role.adoc
:_mod-docs-content-type: CONCEPT
[id="rosa-sts-aws-requirements-attaching-boundary-policy_{context}"]
= Permission boundaries for the installer role

[role="_abstract"]
You can apply a policy as a _permissions boundary_ on an installer role. You can use an AWS-managed policy or a customer-managed policy to set the boundary for an Amazon Web Services (AWS) Identity and Access Management (IAM) entity (user or role).

The combination of policy and boundary policy limits the maximum permissions for the user or role. {product-title} includes a set of three prepared permission boundary policy files, with which you can restrict permissions for the installer role since changing the installer policy itself is not supported.

[NOTE]
====
This feature is only supported on {rosa-classic-title} clusters.
====

The permission boundary policy files are as follows:

* The _Core_ boundary policy file contains the minimum permissions needed for {product-title} installer to install an {product-title} cluster.
The installer does not have permissions to create a virtual private cloud (VPC) or PrivateLink (PL). A VPC needs to be provided.
* The _VPC_ boundary policy file contains the minimum permissions needed for {product-title} installer to create or manage the VPC. It does not include permissions for PL or core installation. If you need to install a cluster with enough permissions for the installer to install the cluster and create or manage the VPC, but you do not need to set up PL, then use the core and VPC boundary files together with the installer role.
* The _PrivateLink (PL)_ boundary policy file contains the minimum permissions needed for {product-title} installer to create the AWS PL with a cluster. It does not include permissions for VPC or core installation. Provide a pre-created VPC for all PL clusters during installation.

When using the permission boundary policy files, the following combinations apply:

* No permission boundary policies means that the full installer policy permissions apply to your cluster.
* *Core* only sets the most restricted permissions for the installer role. The VPC and PL permissions are not included in the *Core only* boundary policy.
** Installer cannot create or manage the VPC or PL.
** You must have a customer-provided VPC, and PrivateLink (PL) is not available.
* *Core + VPC* sets the core and VPC permissions for the installer role.
** Installer cannot create or manage the PL.
** Assumes you are not using custom/BYO-VPC.
** Assumes the installer will create and manage the VPC.
* *Core + PrivateLink (PL)* means the installer can provision the PL infrastructure.
** You must have a customer-provided VPC.
** This is for a private cluster with PL.

== Examples of permission boundary policy files

.Example `sts_installer_core_permission_boundary_policy.json`
[source,json]
----
include::https://raw.githubusercontent.com/openshift/managed-cluster-config/refs/heads/master/resources/sts/4.21/sts_installer_core_permission_boundary_policy.json[]
----

.Example `sts_installer_privatelink_permission_boundary_policy.json`
[source,json]
----
include::https://raw.githubusercontent.com/openshift/managed-cluster-config/refs/heads/master/resources/sts/4.21/sts_installer_privatelink_permission_boundary_policy.json[]
----

.Example `sts_installer_vpc_permission_boundary_policy.json`
[source,json]
----
include::https://raw.githubusercontent.com/openshift/managed-cluster-config/refs/heads/master/resources/sts/4.21/sts_installer_vpc_permission_boundary_policy.json[]
----
