// Module included in the following assemblies:
//
// * rosa_getting_started_sts/rosa-sts-deleting-cluster.adoc

[id="rosa-deleting-aws-resources-cli_{context}"]
= Deleting the AWS resources by using the CLI

After deleting a {product-title} (ROSA) cluster, you can delete the AWS Security Token Service (STS) resources by using the CLI.

[IMPORTANT]
====
Account-wide Identity Access Management (IAM) roles and policies might be used by other ROSA clusters in the same AWS account. You must only remove the resources if they are not required by other clusters.
====

.Prerequisites

* You have installed and configured the latest AWS CLI on your installation host.
* You have deleted your ROSA cluster. For more information, see the _Deleting a cluster_ section.
+
[IMPORTANT]
====
You must delete the cluster before you remove the IAM roles and policies. The account-wide roles and policies are required to delete the resources created by the installer. The Operator roles and policies are required to clean-up the resources created by the OpenShift Operators.
====

.Procedure

. Delete the OpenID Connect (OIDC) provider that you created for Operator authentication in your cluster:
+
[source,terminal]
----
$ aws iam delete-open-id-connect-provider --open-id-connect-provider-arn <oidc_provider_arn> <1>
----
<1> Replace `<oidc_provider_arn>` with the Amazon Resource Name (ARN) of the OpenID Connect (OIDC) resource that you created to authenticate the cluster Operators. You can run `$ aws iam list-open-id-connect-providers` to list the OIDC providers in your account.

. Delete the cluster-specific Operator IAM roles:
.. List the account-wide Operator policy that is attached to one of the cluster-specific IAM roles:
+
[source,terminal]
----
$ aws iam list-attached-role-policies --role-name <operator_role_name> <1>
----
<1> Replace `<operator_role_name>` with the name of a cluster-specific Operator role that you created for the cluster. Specify the role name and not the full ARN. You can run `$ aws iam list-roles` to list the roles in your account.
+
[TIP]
====
The IAM role and policy names include the role prefix that is specified when the STS resources are created. The default prefix is `ManagedOpenShift`.
====
+
.. Detach the policy from role:
+
[source,terminal]
----
$ aws iam detach-role-policy --role-name <operator_role_name> --policy-arn <operator_policy_arn> <1>
----
<1> Replace `<operator_policy_arn>` with the ARN of the attached Operator policy.
+
.. Delete the role:
+
[source,terminal]
----
$ aws iam delete-role --role-name <operator_role_name>
----
+
.. Repeat the steps to delete each of the cluster-specific Operator roles for the cluster.

. Delete the account-wide Operator policies that you created for ROSA deployments that use STS. The following command deletes a single policy:
+
[source,terminal]
----
$ aws iam delete-policy --policy-arn <operator_policy_arn>  <1>
----
<1> Replace `<operator_policy_arn>` with the ARN of one of the Operator policies. You can list the policies in your account by running `$ aws iam list-policies`.
+
Repeat this step to delete each of the Operator policies.

. Delete the account-wide IAM roles and inline policies that you created for ROSA deployments that use STS:
.. List the inline policy for one of the account-wide IAM roles:
+
[source,terminal]
----
$ aws iam list-role-policies --role-name <account_wide_role_name> <1>
----
<1> Replace `<account_wide_role_name>` with the name of one of the account-wide IAM roles. Specify the role name and not the full ARN. You can run `$ aws iam list-roles` to list the roles in your account.
+
.. Delete the inline policy:
+
[source,terminal]
----
$ aws iam delete-role-policy --role-name <account_wide_role_name> --policy-name <inline_role_policy_name><1>
----
<1> Replace `<inline_role_policy_name>` with the policy name that is included in the output of the preceding command.
+
.. Delete the role:
+
[source,terminal]
----
$ aws iam delete-role --role-name <account_wide_role_name>
----
+
.. Repeat the steps to delete each of the account-wide roles.
