// Module included in the following assemblies:
//
// * rosa_install_access_delete_clusters/rosa-sts-deleting-cluster.adoc
// *rosa_hcp/rosa-hcp-deleting-cluster.adoc

ifeval::["{context}" == "rosa-hcp-deleting-cluster"]
:hcp:
endif::[]

:_mod-docs-content-type: PROCEDURE
[id="rosa-deleting-sts-resources-account-wide_{context}"]
= Deleting the account-wide IAM resources

After you have deleted all {product-title} clusters that depend on the account-wide AWS Identity and Access Management (IAM) resources, you can delete the account-wide resources.

If you no longer need to install a {product-title} cluster by using {cluster-manager-first}, you can also delete the {cluster-manager} and user IAM roles.

[IMPORTANT]
====
The account-wide IAM roles and policies might be used by other {product-title} clusters in the same AWS account. Only remove the resources if they are not required by other clusters.

The {cluster-manager} and user IAM roles are required if you want to install, manage, and delete other {product-title} clusters in the same AWS account by using {cluster-manager}. Only remove the roles if you no longer need to install {product-title} clusters in your account by using {cluster-manager}. For more information about repairing your cluster if these roles are removed before deletion, see "Repairing a cluster that cannot be deleted" in _Troubleshooting cluster deployments_.
====