// Module included in the following assemblies:
//
// * rosa_upgrading/rosa-upgrading.adoc

[id="rosa-upgrade-ocm_{context}"]
= Upgrading manually using the console


There are three methods that can be used to upgrade {product-title} clusters. This procedure describes manually upgrading using the OpenShift Cluster Manager (OCM) console.

.Procedure

. Log in to the link:https://cloud.redhat.com/openshift[OCM console].
. Select a cluster to upgrade.
. Click the *Update settings* tab.
. In the _Update Strategy_ pane, click *Manual*.
+
The scheduling options are displayed.
. Select the day of the week and the time for upgrades to occur.
. In the _Node draining_ pane, select a grace period interval from the drop-down list to allow the nodes to gracefully drain before forcing the pod eviction. Default: `1 hour`
. In the _Update Status_ pane, review the `Update available` information.
. Click *Update*. This button is enabled only when an upgrade is available.
+
The cluster is scheduled for an immediate upgrade to the latest version. This action can take an hour or longer, depending on your workload configuration, such as PodDisruptionBudgets.
+
The status is displayed in the _Update Status_ pane.
