// Module included in the following assemblies:
//
// security/certificate_types_descriptions/etcd-certificates.adoc

:_mod-docs-content-type: PROCEDURE
[id="rotating-certificate-authority_{context}"]
= Rotating the etcd certificate

Rotate the `etcd` certificate before it expires.

.Procedure

. Verify the remaining lifetime of the new signer certificate by running the following command:
+
[source,terminal]
----
$ oc get secret -n openshift-etcd etcd-signer -ojsonpath='{.metadata.annotations.auth\.openshift\.io/certificate-not-after}'
----

. If the remaining lifetime is close to the current date, re-create the signer by deleting the signer and wait for the static pod roll out.
* Delete the signer by running the following command:
+
[source,terminal]
----
$ oc delete secret -n openshift-etcd etcd-signer
----

* Wait for the static pod roll out by running the following command:
+
[source,terminal]
----
$ oc wait --for=condition=Progressing=False --timeout=15m clusteroperator/etcd
----

. After `etcd` restarts, switch the original CA in the `openshift-config` namespace with the new, rotated one in `openshift-etcd` by running the following command:
+
[source,terminal]
----
$ oc get secret etcd-signer -n openshift-etcd -ojson | jq 'del(.metadata["namespace","creationTimestamp","resourceVersion","selfLink","uid"])' | oc apply -n openshift-config -f -
----

. Wait for the cluster Operators to roll out and stabilize by running the following command:
+
[source,terminal]
----
$ oc adm wait-for-stable-cluster --minimum-stable-period 2m
----
