// Module included in the following assemblies:
//
// * architecture/networking.adoc

[id='route-types-{context}']
= Route types
Routes can be either secured or unsecured. Secure routes provide the ability to
use several types of TLS termination to serve certificates to the client.
Routers support edge, passthrough, and re-encryption termination.

Unsecured routes are simplest to configure, as they require no key
or certificates, but secured routes offer security for connections to
remain private.

A secured route is one that specifies the TLS termination of the route.

[id='path-based-routes-{context}']
== Path-based routes
Path based routes specify a path component that can be compared against
a URL (which requires that the traffic for the route be HTTP based) such
that multiple routes can be served using the same host name, each with a
different path. Routers should match routes based on the most specific
path to the least; however, this depends on the router implementation.
The host name and path are passed through to the backend server so it should be
able to successfully answer requests for them.
For example: a request to http://example.com/foo/ that goes to the router will
result in a pod seeing a request to http://example.com/foo/.

The following table shows example routes and their accessibility:

.Route availability
[cols="3*", options="header"]
|===
|Route |When Compared to |Accessible

.2+|_www.example.com/test_ |_www.example.com/test_ |Yes

|_www.example.com_ |No

.2+|_www.example.com/test_ and _www.example.com_ |_www.example.com/test_ |Yes

|_www.example.com_ |Yes

.2+|_www.example.com_ |_www.example.com/test_ |Yes (Matched by the host, not the route)

|_www.example.com_ |Yes
|===

[NOTE]
====
Path-based routing is not available when using passthrough TLS, as
the router does not terminate TLS in that case and cannot read the contents
of the request.
====

[id='secured-routes-{context}']
== Secured Routes
Secured routes specify the TLS termination of the route and, optionally,
provide a key and certificate(s).

[NOTE]
====
TLS termination in {product-title} relies on
link:https://en.wikipedia.org/wiki/Server_Name_Indication[SNI] for serving
custom certificates. Any non-SNI traffic received on port 443 is handled with
TLS termination and a default certificate (which may not match the requested
host name, resulting in validation errors).
====

Secured routes can use any of the following three types of secure TLS
termination.

.Edge termination

With edge termination, TLS termination occurs at the router, prior to proxying
traffic to its destination. TLS certificates are served by the front end of the
router, so they must be configured into the route, otherwise the
router's default certificate will be used for TLS termination.

Because TLS is terminated at the router, connections from the router to
the endpoints over the internal network are not encrypted.

.Passthrough Termination

With passthrough termination, encrypted traffic is sent straight to the
destination without the router providing TLS termination. Therefore no
key or certificate is required.

The destination pod is responsible for serving certificates for the
traffic at the endpoint. This is currently the only method that can support
requiring client certificates (also known as two-way authentication).

[NOTE]
====
Passthrough routes can also have an `insecureEdgeTerminationPolicy`. The only
valid values are `None` (or empty, for disabled) or `Redirect`.
====

.Re-encryption Termination

Re-encryption is a variation on edge termination where the router terminates
TLS with a certificate, then re-encrypts its connection to the endpoint which
may have a different certificate. Therefore the full path of the connection
is encrypted, even over the internal network. The router uses health
checks to determine the authenticity of the host.

If the `destinationCACertificate` field is left empty, the router
automatically leverages the certificate authority that is generated for service
serving certificates, and is injected into every pod as
`/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt`. This allows new
routes that leverage end-to-end encryption without having to generate a
certificate for the route. This is useful for custom routers or the F5 router,
which might not allow the `destinationCACertificate` unless the administrator
has allowed it.

[NOTE]
====
Re-encrypt routes can have an `insecureEdgeTerminationPolicy` with all of the
same values as edge-terminated routes.
====
