// Module included in the following assemblies:
//
// * openshift_images/configuring_samples_operator.adoc


[id="samples-operator-overview_{context}"]
= Understanding the Samples Operator

During installation, the Operator creates the default configuration object for
itself and then creates the sample imagestreams and templates, including
quickstart templates.

The Samples Operator copies the pull secret that is captured by the installation
program into the OpenShift namespace and names the secret,
`samples-registry-credentials`, to facilitate imagestream imports from
`registry.redhat.io`. Additionally, to facilitate imagestream imports from other
registries that require credentials, a cluster administrator can create any
additional secrets that contain the content of a Docker `config.json` file in
the OpenShift namespace needed to facilitate image import.

The Samples Operator configuration is a cluster-wide resource, and the deployment
is contained within the `openshift-cluster-samples-operator` namespace.

The image for the Samples Operator contains imagestream and template definitions
for the associated {product-title} release. When each sample is created or updated,
the Samples Operator includes an annotation that denotes the version of
{product-title}. The Operator uses this annotation to ensure that each sample
matches the release version. Samples outside of its inventory are ignored, as
are skipped samples. Modifications to any samples that are managed by the
Operator, where that version annotation is modified or deleted, will be reverted
automatically.

[NOTE]
====
The Jenkins images are part of the image payload from
installation and are tagged into the imagestreams directly.
====

The Samples Operator configuration resource includes a finalizer which cleans up
the following upon deletion:

* Operator managed imagestreams.
* Operator managed templates.
* Operator generated configuration resources.
* Cluster status resources.
* The `samples-registry-credentials` secret.

Upon deletion of the samples resource, the Samples Operator recreates the
resource using the default configuration.

[id="samples-operator-bootstrapped"]
== Samples Operator's use of management state

The Samples Operator is bootstrapped as `Managed` by default or if global proxy is configured. In the `Managed` state, the Samples Operator is actively managing its resources and keeping the component active in order to pull sample imagestreams and images from the registry and ensure that the requisite sample templates are installed.

Certain circumstances will result in the Samples Operator bootstrapping itself as `Removed` including:

* If the Samples Operator cannot reach link:https://registry.redhat.io[registry.redhat.io] after three minutes on initial start-up after a clean installation.
* If the Samples Operator detects it is on an IPv6 network.

However, if Samples Operator also detects a OpenShift Global Proxy is configured, it bypasses those checks.

[IMPORTANT]
====
IPv6 installations are not currently supported by link:https://registry.redhat.io[registry.redhat.io]. The Samples Operator pulls most of the sample imagestreams and images from link:https://registry.redhat.io[registry.redhat.io].
====

Boostrapping as `Removed` when unable to access `registry.redhat.io` among other things facilitates restricted
network installs [ED NOTE add link to restricted network installs here] when the network restriction is already in place.
In particular, not installing the samples out
of the gate when network access is restricted allows the cluster administrator more time to decide if samples are
desired before submitting alerts that sample imagestream imports are failing, which it will start doing 2 hours after
initial installation.

Conversely, if a cluster which is intended to be restricted network or disconnected cluster is first installed while
network access exists, the samples operator will install the content from `registry.redhat.io` since it can access it.
If you would like the samples operator to still bootstrap as `Removed` in order to defer samples installation until
you have decided which samples if any are desired, set up image mirrors, etc., then follow the instructions at
https://docs.openshift.com/container-platform/4.5/installing/install_config/installing-customizing.html [ED NOTE, fix
this link] to override the Samples Operator default configuration, and initially come up as `Removed`.  The additional
yaml file your would put in the `openshift` directory created by `openshift-install create manifest` is:

```yaml
apiVersion: samples.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  architectures:
  - x86_64
  managementState: Removed
```

[id="samples-operator-retries"]
== Samples Operator's tracking and error recovery of imagestream imports

As touched upon in the [ED NOTE, add link to configuring-samples-operator Conditions secdtion], after creation or update
of a samples imagestream, the Samples Operator will monitor the progress of each imagestreamtag's image import.

If an import fails, the Samples Operator will retry the import via the imagestream image import API (the same API
used by the `oc import-image` command) approximately every 15 minutes until it sees the import succeed, or if
samples operator's configuration is changed such that either a) the imagestream is added to the skippedImagestream list, or
b) the management state is changed to `Removed`.
