//Module included in the following assemblies:
//
// * sandboxed_containers/deploying_sandboxed_containers.adoc

[id="sandboxed-containers-installing-operator-cli_{context}"]
= Installing the {sandboxed-containers-operator} using the CLI

You can install the {sandboxed-containers-operator} using the {product-title} CLI.

.Prerequisites

* You have {product-title} {product-version} installed on your cluster.
* You have installed the OpenShift CLI (`oc`).
* You have access to the cluster as a user with the `cluster-admin` role.
* You have subscribed to the {sandboxed-containers-first} catalog.
+
[NOTE]
====
Subscribing to the {sandboxed-containers-first} catalog provides `openshift-sandboxed-containers-operator` namespace access to the {sandboxed-containers-operator}.
====

.Procedure

. Create a YAML file that contains the following manifest:
+
[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-sandboxed-containers-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-sandboxed-containers-operator
  namespace: openshift-sandboxed-containers-operator
spec:
  targetNamespaces:
  - openshift-sandboxed-containers-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-sandboxed-containers-operator
  namespace: openshift-sandboxed-containers-operator
spec:
  channel: "preview-1.1"
  installPlanApproval: Automatic
  name: sandboxed-containers-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: sandboxed-containers-operator.v1.1.0
----
+
[NOTE]
====
Using the *preview-1.1* channel ensures that you install the version of {sandboxed-containers-first} that is compatible with your {product-title} version.
====

. Create the required `Namespace`, `OperatorGroup`, and `Subscription` objects for {sandboxed-containers-first}:
+
[source,terminal]
----
$ oc create -f <file name>.yaml
----

. Ensure that the Operator is correctly installed:
+
[source,terminal]
----
$ oc get csv -n openshift-sandboxed-containers-operator
----
+
.Example output
+
----
NAME                             DISPLAY                                  VERSION  REPLACES                    PHASE
openshift-sandboxed-containers   openshift-sandboxed-containers-operator  1.0.0    <csv-of-previous-version>   Succeeded
----
. View the available deployments:
+
[source,terminal]
----
$ oc get deployments -n openshift-sandboxed-containers-operator
----
+
.Example output
----
NAME                                        READY  UP-TO-DATE   AVAILABLE   AGE
openshift-sandboxed-containers-operator                         1/111       9m48s
----

.Verification

* Verify that the Operator is up and running, so you can create the `KataConfig` resource to trigger the installation.
+
[source,terminal]
----
$ oc get deployments -n openshift-sandboxed-containers-operator
----
+
.Example output
+
[source,terminal]
----
NAME                                                READY   UP-TO-DATE   AVAILABLE   AGE
openshift-sandboxed-containers-controller-manager   1/1     1            1           40d
----
