// Module included in the following assemblies:
//
// * sandboxed_containers/troubleshooting-sandboxed-containers.adoc

//This file contains UI elements and/or package names that need to be updated.

[id="sandboxed-containers-collecting-data_{context}"]
= About collecting {sandboxed-containers-first} data

You can use the `oc adm must-gather` CLI command to collect information about your cluster. The following features and objects are associated with {sandboxed-containers-first}:

* All namespaces and their child objects that belong to any {sandboxed-containers-first}
resources
* All {sandboxed-containers-first} custom resource definitions (CRDs)

The `oc adm must-gather` CLI command collects the following component logs:

* QEMU logs
* Audit logs
* {sandboxed-containers-first} logs
* CRI-O logs

These component logs are collected as long as there is at least one pod running with the `kata` runtime.

To collect {sandboxed-containers-first} data with `must-gather`, you must specify the
{sandboxed-containers-first} image:
[source,terminal]
----
--image=registry.redhat.io/openshift-sandboxed-containers-tech-preview/osc-must-gather-rhel8:1.1.0
----
