// Module included in the following assemblies:
//
// * cli/image-scanning-by-using-the-roxctl-cli.adoc

:_mod-docs-content-type: PROCEDURE
[id="scanning-images-remote-cluster-procedure_{context}"]
= Scanning images by using a remote cluster

[role="_abstract"]
You can scan images from cluster local registries by delegating the scan to a remote cluster.

.Procedure

* Run the following command to scan the specified image in a remote cluster:
+
[source,terminal,subs="+quotes"]
----
$ roxctl image scan \
  --image=_<image_registry>_/_<image_name>_ \
  --cluster=_<cluster_detail>_ \
  [flags]
----
+
where:
+
--
`<image_registry>`:: Specifies the registry that stores the image, for example, `image-registry.openshift-image-registry.svc:5000/`.
`image_name`:: Specifies the name of the image that you want to scan.
`<cluster_detail>`:: Specifies the name or ID of the remote cluster. For example, specify the name `remote`.
`[flags]`:: Specifies the parameters to modify the behavior of the command. This is optional.
--
+
The following is an example output:
+
[source,text,subs=attributes+]
----
{
  "Id": "sha256:3f439d7d71adb0a0c8e05257c091236ab00c6343bc44388d091450ff58664bf9",
  "name": {
    "registry": "image-registry.openshift-image-registry.svc:5000",
    "remote": "default/image-stream",
    "tag": "latest",
    "fullName": "image-registry.openshift-image-registry.svc:5000/default/image-stream:latest"
  },
[...]
----
+
--
* `Id` is a unique identifier for the image that serves as a fingerprint for the image. It helps ensure the integrity and authenticity of the image.
* `registry` is the location of the image registry that stores the image.
* `remote` is the remote path to the image.
* `tag` is the version or tag associated with this image.
* `fullName` is the complete name of the image, combining the registry, remote path, and tag.
--
