// Module included in the following assemblies:
//
// * operating/search-filter.adoc

:_mod-docs-content-type: CONCEPT
[id="search-syntax_{context}"]
= Search syntax

[role="_abstract"]
A search query consists of an attribute that identifies the resource type and a search term that finds the matching resource.

* An attribute that identifies the resource type you want to search for.
* A search term that finds the matching resource.

For example, to find all violations in the `visa-processor` deployment, the search query is `Deployment:visa-processor`. In this search query, `Deployment` is the attribute and `visa-processor` is the search term.

[NOTE]
====
You must select an attribute before you can use search terms. However, in some views, such as the *Risk* view and the *Violations* view, {product-title} automatically applies the relevant attribute based on the search term you enter.
====

* You can use many attributes in your query. When you use more than one attribute, the results only include the items that match all attributes.
+
When you search for `Namespace:frontend CVE:CVE-2018-11776`, it returns only those resources that violate CVE-2018-11776 in the `frontend` namespace.

* You can use more than one search term with each attribute. When you use more than one search term, the results include all items that match any of the search terms.
+
If you use the search query `Namespace: frontend backend`, it returns matching results from the namespace `frontend` or `backend`.

* You can combine many attribute and search term pairs.
+
The search query `Cluster:production Namespace:frontend CVE:CVE-2018-11776` returns all resources that violate CVE-2018-11776 in the `frontend` namespace in the `production` cluster.

* Search terms can be part of a word, in which case {product-title} returns all matching results.
+
If you search for `Deployment:def`, the results include all deployments starting with `def`.

* To explicitly search for a specific term, use the search terms inside quotes.
+
When you search for `Deployment:"def"`, the results only include the deployment `def`.

* You can also use regular expressions by using `r/` before your search term.
+
When you search for `Namespace:r/st.*x`, the results include matches from namespace `stackrox` and `stix`.

* Use `!` to indicate the search terms that you do not want in results.
+
If you search for `Namespace:!stackrox`, the results include matches from all namespaces except the `stackrox` namespace.

* Use the comparison operators `>`, `<`, `=`, `>=`, or `\<=` to match a specific value or range of values.
+
If you search for `CVSS:>=6`, the results include all vulnerabilities with Common Vulnerability Scoring System (CVSS) score 6 or higher.