// Module included in the following assemblies:
//
// * dir/filename.adoc
:_module-type: CONCEPT
[id="secured-cluster-services-config_{context}"]
= Configuration parameters

|===
| Parameter | Description

| `clusterName`
| Name of your cluster.

| `centralEndpoint`
| Address of the Central endpoint, including the port number.
If you are using a non-gRPC capable LoadBalancer, use the WebSocket protocol by prefixing the endpoint address with `wss://`.

| `sensor.endpoint`
| Address of the Sensor endpoint including port number.

| `image.main.name`
| The name of the `main` image.

| `image.collector.name`
| The name of the Collector image.

| `image.main.registry`
| Address of the registry you are using for the main image.

| `image.collector.registry`
| Address of the registry you are using for the Collector image.

| `image.main.pullPolicy`
| Image pull policy for `main` images.

| `image.collector.pullPolicy`
| Image pull policy for the Collector images.

| `image.main.tag`
| Tag of `main` image to use.

| `image.collector.tag`
| Tag of `collector` image to use.

| `collector.collectionMethod`
| Either `EBPF`, `KERNEL_MODULE`, or `NO_COLLECTION`.

| `admissionControl.listenOnCreates`
| This setting controls whether Kubernetes is configured to contact {product-title} with `AdmissionReview` requests for workload creation events.

| `admissionControl.listenOnUpdates`
| When you keep it as `false`, {product-title} creates the `ValidatingWebhookConfiguration` in a way that causes the Kubernetes API server not to send object update events.
Since the volume of object updates is usually higher than the object creates, leaving this as `false` limits the load on the admission control service and decreases the chances of a malfunctioning admission control service.

| `admissionControl.listenOnEvents`
| This setting controls whether the cluster is configured to contact {product-title} with `AdmissionReview` requests for Kubernetes `exec` and `portforward` events.
{product-title} does not support this feature on {ocp}.

| `admissionControl.dynamic.enforceOnCreates`
| This setting controls whether {product-title} evaluates policies;
if it is disabled, all AdmissionReview requests are automatically accepted.

| `admissionControl.dynamic.enforceOnUpdates`
| This setting controls the behavior of the admission control service.
You must specify `listenOnUpdates` as `true` for this to work.

| `admissionControl.dynamic.scanInline`
| If you set this option to `true`, the admission control service requests an image scan before making an admission decision.
Since image scans take several seconds, enable this option only if you can ensure that all images used in your cluster are scanned before deployment (for example, by a CI integration during image build).
This option corresponds to the *Contact image scanners* option in the RHACS Portal.

| `admissionControl.dynamic.disableBypass`
| Set it to `true` to disable bypassing the Admission Controller.
//TODO: Link to admission controller docs

| `admissionControl.dynamic.timeout`
| The maximum time, in seconds, {product-title} should wait while evaluating admission review requests.
Use this to set request timeouts when you enable image scanning.
If the image scan runs longer than the specified time, {product-title} accepts the request.

| `registryOverride`
| Use this parameter to override the default `docker.io` registry.
Specify the name of your registry if you are using some other registry.

| `collector.disableTaintTolerations`
| If you specify `false`, tolerations are applied to Collector, and the Collector pods can schedule onto all nodes with taints.
If you specify it as `true`, no tolerations are applied, and the Collector pods are not scheduled onto nodes with taints.

| `createUpgraderServiceAccount`
| Specify `true` to create the `sensor-upgrader` account.
By default, {product-title} creates a service account called `sensor-upgrader` in each secured cluster.
This account is highly privileged but is only used during upgrades.
If you do not create this account, you must complete future upgrades manually if the Sensor does not have enough permissions.
//TODO: Link to Enable automatic upgrades for secured clusters topic.

| `createSecrets`
| Specify `false` to skip the orchestrator secret creation for the Sensor, Collector, and Admission Controller.

| `collector.slimMode`
| Specify `true` if you want to use a slim Collector image for deploying Collector.
Using slim Collector images requires Central to provide the matching kernel module or eBPF probe.
If you are running {product-title} in offline mode, you must download a kernel support package from link:https://install.stackrox.io/collector/support-packages/index.html[stackrox.io] and upload it to Central for slim Collectors to function.
Otherwise, you must ensure that Central can access the online probe repository hosted at link:https://collector-modules.stackrox.io/[https://collector-modules.stackrox.io/].
//TODO: Change these links when new links are alive.

| `sensor.resources`
| Resource specification for Sensor.

| `admissionControl.resources`
| Resource specification for Admission Controller.

| `collector.resources`
| Resource specification for Collector.

| `collector.complianceResources`
| Resource specification for Collector's Compliance container.

| `exposeMonitoring`
| If you set this option to `true`,  {product-title} exposes Prometheus metrics endpoints on port number 9090 for the Sensor, Collector, and the Admission Controller.
|===

[id="secured-cluster-services-environment-variables_{context}"]
== Environment variables

You can specify environment variables for Sensor and Admission Controller in the following format:

[source,yaml]
----
customize:
  envVars:
    ENV_VAR1: "value1"
    ENV_VAR2: "value2"
----

The `customize` setting allows you to specify custom Kubernetes metadata (labels and annotations) for all objects created by this Helm chart and additional pod labels, pod annotations, and container environment variables for workloads.

The configuration is hierarchical, in the sense that metadata defined at a more generic scope (for example, for all objects) can be overridden by metadata defined at a narrower scope (for example, only for the Sensor deployment).
