// Module included in the following assemblies:
//
// * security/container_security/security-compliance.adoc
// * understanding-sandboxed-containers.adoc

[id="security-compliance-nist_{context}"]
= Understanding compliance and risk management

ifeval::["{context}" == "understanding-sandboxed-containers"]
{sandboxed-containers-first} can be used on FIPS enabled clusters.

When running in FIPS mode, {sandboxed-containers-first} components, VMs, and VM images are adapted to comply with FIPS.
endif::[]

ifndef::openshift-origin[]
FIPS compliance is one of the most critical components required in
highly secure environments, to ensure that only supported cryptographic
technologies are allowed on nodes.

[IMPORTANT]
====
The use of FIPS Validated / Modules in Process cryptographic libraries is only supported on {product-title} deployments on the `x86_64` architecture.
====
endif::openshift-origin[]

To understand Red Hat's view of {product-title} compliance frameworks, refer
to the Risk Management and Regulatory Readiness chapter of the
link:https://access.redhat.com/articles/5059881[OpenShift Security Guide Book].
