// Module is included in the following assemblies:
//
// * /serverless/monitor/serverless-monitoring-services-default-metrics

:_mod-docs-content-type: PROCEDURE
[id="serverless-viewing-knative-service-metrics-web-console_{context}"]
= Viewing Knative service metrics in the web console

[role="_abstract"]
The following procedure describes how to view and query Knative service and application metrics by using the {ocp-product-title} web console.

.Prerequisites

* You have logged in to the {ocp-product-title} web console.
* You have installed the {ServerlessOperatorName} and Knative Serving.

.Procedure

. Optional: Run requests against your application that you will be able to see in the metrics:
+
[source,terminal]
----
$ hello_route=$(oc get ksvc helloworld-go -n ns1 -o jsonpath='{.status.url}') && \
    curl $hello_route
----
+
You get an output similar to the following example:
+
[source,terminal]
----
Hello Go Sample v1!
----

. In the web console, navigate to the *Observe* -> *Metrics* interface.

. In the input field, enter the query for the metric you want to observe, for example:
+
[source]
----
revision_app_request_count{namespace="ns1", job="helloworld-go-sm"}
----
+
Another example:
+
[source]
----
myapp_processed_ops_total{namespace="ns1", job="helloworld-go-sm"}
----

. Observe the visualized metrics.
