[id="serverless-service-mesh-resources_{context}"]
= Creating necessary {ProductShortName} resources

To use custom domains with {ProductShortName}, you must first create some necessary {ProductShortName} resources.

.Procedure

. Create an Istio gateway to accept traffic:
+
[source,yaml]
----
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: <namespace> <1>
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
----
<1> The namespace where your Knative services have been created. This namespace must be a member of the Service Mesh member roll.
. Apply the `Gateway` resource:
+
[source,terminal]
----
$ oc apply -f <filename>
----
. Create an Istio virtual service to rewrite the host header:
+
[source,yaml]
----
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello
spec:
  hosts:
  - custom-ksvc-domain.example.com
  gateways:
  - default-gateway
  http:
  - rewrite:
      authority: hello.default.svc <1>
    route:
    - destination:
        host: hello.default.svc <1>
        port:
          number: 80
----
<1> Your Knative service in the format `<service_name>.<namespace>.svc`.
. Apply the `VirtualService` resource:
+
[source,terminal]
----
$ oc apply -f <filename>
----

. Create an Istio service entry. This is required for {ServerlessProductName} because Kourier is outside of the {ProductShortName}:
+
[source,yaml]
----
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: hello.default.svc
spec:
  hosts:
  - hello.default.svc <1>
  location: MESH_EXTERNAL
  endpoints:
  - address: kourier-internal.knative-serving-ingress.svc
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
----
<1> Your Knative service in the format `<service_name>.<namespace>.svc`.
. Apply the `ServiceEntry` resource:
+
[source,terminal]
----
$ oc apply -f <filename>
----

. Create an {product-title} route that points to the `VirtualService` object:
+
[source,yaml]
----
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello
  namespace: istio-system <1>
spec:
  host: custom-ksvc-domain.example.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: istio-ingressgateway
----
<1> The {product-title} route must be created in the same namespace as the
`ServiceMeshControlPlane`. In this example, the `ServiceMeshControlPlane` is
deployed in the `istio-system` namespace.
. Apply the `Route` resource:
+
[source,terminal]
----
$ oc apply -f <filename>
----
