// Module included in the following assemblies:
//
// * /serverless/integrations/serverless-ossm-setup.adoc

:_content-type: PROCEDURE
[id="serverless-ossm-enabling-serving-metrics_{context}"]
= Enabling Knative Serving and Knative Eventing metrics when using Service Mesh with mTLS

If Service Mesh is enabled with Mutual Transport Layer Security (mTLS), metrics for Knative Serving and Knative Eventing are disabled by default, because Service Mesh prevents Prometheus from scraping metrics. You can enable Knative Serving and Knative Eventing metrics when using Service Mesh and mTLS.

.Prerequisites

* You have one of the following permissions to access the cluster: 
** Cluster administrator permissions on {ocp-product-title}
** Cluster administrator permissions on {rosa-product-title}
** Dedicated administrator permissions on {dedicated-product-title}
* You have installed the OpenShift CLI (`oc`).
* You have access to a project with the appropriate roles and permissions to create applications and other workloads.
* You have installed the {ServerlessOperatorName}, Knative Serving, and Knative Eventing on your cluster.
* You have installed {SMProductName} with the mTLS functionality enabled.

.Procedure

. Specify `prometheus` as the `metrics.backend-destination` in the `observability` spec of the Knative Serving custom resource (CR):
+
[source,yaml]
----
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    observability:
      metrics.backend-destination: "prometheus"
...
----
+
This step prevents metrics from being disabled by default.
+
[NOTE]
====
When you configure `ServiceMeshControlPlane` with `manageNetworkPolicy: false`, you must use the annotation on KnativeEventing to ensure proper event delivery.
====

+ 
The same mechanism is used for Knative Eventing. To enable metrics for Knative Eventing, you need to specify `prometheus` as the `metrics.backend-destination` in the `observability` spec of the Knative Eventing custom resource (CR) as follows: 
+
[source,yaml]
----
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  config:
    observability:
      metrics.backend-destination: "prometheus"
...
----

. Modify and reapply the default Service Mesh control plane in the `istio-system` namespace, so that it includes the following spec:
+
[source,yaml]
----
...
spec:
  proxy:
    networking:
      trafficControl:
        inbound:
          excludedPorts:
          - 8444
...
----
