// Module included in the following assemblies:
// * about/serverless-logic-overview.adoc


:_mod-docs-content-type: CONCEPT
[id="serverless-logic-overview-jq-expressions_{context}"]
= JQ expressions

[role="_abstract"]
Each workflow instance uses a data model. The data model consists of a JSON object, regardless of whether the workflow file uses `YAML` or `JSON`. The initial content of the JSON object depends on how you start the workflow. If you start the workflow by using a `CloudEvent`, the workflow reads content from the data property. If you start the workflow through an HTTP POST request, the workflow reads content from the request body.

JSON Query (JQ) expressions interact with the data model. The system supports `JsonPath` and JQ expression languages, and JQ serves as the default. You can change the expression language to `JsonPath` by using the `expressionLang` property.

[source,json]
----
{
      "name": "max",
      "type": "expression",
      "operation": "{max: .numbers | max_by(.x), min: .numbers | min_by(.y)}"
    }
----
