:_content-type: PROCEDURE
[id="serverless-ossm-installing-and-configuring-openshift-serverless_{context}"]
= Installing and configuring {ServerlessProductShortName}

After installing {SMProductShortName}, you need to install {ServerlessProductShortName} with a specific configuration.

.Procedure

. Install Knative Serving with the following `KnativeServing` custom resource, which enables the Istio integration:
+
.Example `knative-serving-config.yaml` configuration file
[source,yaml]
----
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    istio:
      enabled: true <1>
  deployments: <2>
  - name: activator
    annotations:
      "sidecar.istio.io/inject": "true"
      "sidecar.istio.io/rewriteAppHTTPProbers": "true"
  - name: autoscaler
    annotations:
      "sidecar.istio.io/inject": "true"
      "sidecar.istio.io/rewriteAppHTTPProbers": "true"
  config:
    istio: <3>
      gateway.knative-serving.knative-ingress-gateway: istio-ingressgateway.<your-istio-namespace>.svc.cluster.local
      local-gateway.knative-serving.knative-local-gateway: knative-local-gateway.<your-istio-namespace>.svc.cluster.local
----
<1> Enable Istio integration.
<2> Enable sidecar injection for Knative Serving data plane pods.
<3> If your istio is not running in the `istio-system` namespace, you need to set these two flags with the correct namespace.

. Apply the `KnativeServing` resource:
+
[source,terminal]
----
$ oc apply -f knative-serving-config.yaml
----

. Install Knative Eventing with the following `KnativeEventing` object, which enables the Istio integration:
+
.Example `knative-eventing-config.yaml` configuration file
[source,yaml]
----
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  config:
    features:
      istio: enabled <1>
  workloads: <2>
  - name: pingsource-mt-adapter
    annotations:
      "sidecar.istio.io/inject": "true"
      "sidecar.istio.io/rewriteAppHTTPProbers": "true"
  - name: imc-dispatcher
    annotations:
      "sidecar.istio.io/inject": "true"
      "sidecar.istio.io/rewriteAppHTTPProbers": "true"
  - name: mt-broker-ingress
    annotations:
      "sidecar.istio.io/inject": "true"
      "sidecar.istio.io/rewriteAppHTTPProbers": "true"
  - name: mt-broker-filter
    annotations:
      "sidecar.istio.io/inject": "true"
      "sidecar.istio.io/rewriteAppHTTPProbers": "true"
----
<1> Enable Eventing Istio controller to create a `DestinationRule` for each `InMemoryChannel` or `KafkaChannel` service.
<2> Enable sidecar injection for Knative Eventing pods.

. Apply the `KnativeEventing` resource:
+
[source,terminal]
----
$ oc apply -f knative-eventing-config.yaml
----

. Install Knative Kafka with the following `KnativeKafka` custom resource, which enables the Istio integration:
+
.Example `knative-kafka-config.yaml` configuration file
[source,yaml]
----
apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: knative-kafka
  namespace: knative-eventing
spec:
  channel:
    enabled: true
    bootstrapServers: <bootstrap_servers> <1>
  source:
    enabled: true
  broker:
    enabled: true
    defaultConfig:
      bootstrapServers: <bootstrap_servers> <1>
      numPartitions: <num_partitions>
      replicationFactor: <replication_factor>
    sink:
      enabled: true
  workloads: <2>
  - name: kafka-controller
    annotations:
      "sidecar.istio.io/inject": "true"
      "sidecar.istio.io/rewriteAppHTTPProbers": "true"
  - name: kafka-broker-receiver
    annotations:
      "sidecar.istio.io/inject": "true"
      "sidecar.istio.io/rewriteAppHTTPProbers": "true"
  - name: kafka-broker-dispatcher
    annotations:
      "sidecar.istio.io/inject": "true"
      "sidecar.istio.io/rewriteAppHTTPProbers": "true"
  - name: kafka-channel-receiver
    annotations:
      "sidecar.istio.io/inject": "true"
      "sidecar.istio.io/rewriteAppHTTPProbers": "true"
  - name: kafka-channel-dispatcher
    annotations:
      "sidecar.istio.io/inject": "true"
      "sidecar.istio.io/rewriteAppHTTPProbers": "true"
  - name: kafka-source-dispatcher
    annotations:
      "sidecar.istio.io/inject": "true"
      "sidecar.istio.io/rewriteAppHTTPProbers": "true"
  - name: kafka-sink-receiver
    annotations:
      "sidecar.istio.io/inject": "true"
      "sidecar.istio.io/rewriteAppHTTPProbers": "true"
----
<1> The Apache Kafka cluster URL, for example `my-cluster-kafka-bootstrap.kafka:9092`.
<2> Enable sidecar injection for Knative Kafka pods.

. Apply the `KnativeEventing` object:
+
[source,terminal]
----
$ oc apply -f knative-kafka-config.yaml
----

. Install `ServiceEntry` to inform {SMProductShortName} of the communication between `KnativeKafka` components and an Apache Kafka cluster:
+
.Example `kafka-cluster-serviceentry.yaml` configuration file
[source,yaml]
----
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: kafka-cluster
  namespace: knative-eventing
spec:
  hosts: <1>
    - <bootstrap_servers_without_port>
  exportTo:
    - "."
  ports: <2>
    - number: 9092
      name: tcp-plain
      protocol: TCP
    - number: 9093
      name: tcp-tls
      protocol: TCP
    - number: 9094
      name: tcp-sasl-tls
      protocol: TCP
    - number: 9095
      name: tcp-sasl-tls
      protocol: TCP
    - number: 9096
      name: tcp-tls
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: NONE
----
<1> The list of Apache Kafka cluster hosts, for example `my-cluster-kafka-bootstrap.kafka`.
<2> Apache Kafka cluster listeners ports.
+
[NOTE]
====
The listed ports in `spec.ports` are example TPC ports. The actual values depend on how the Apache Kafka cluster is configured.
====

. Apply the `ServiceEntry` resource:
+
[source,terminal]
----
$ oc apply -f kafka-cluster-serviceentry.yaml
----
