// Module is included in the following assemblies:
//
// * serverless/monitor/serverless-tracing.adoc

[id="serverless-jaeger-config_{context}"]
= Configuring Jaeger for use with {ServerlessProductName}

.Prerequisites

To configure Jaeger for use with {ServerlessProductName}, you will need:

* Cluster administrator permissions on an {product-title} cluster.
* A current installation of {ServerlessOperatorName} and Knative Serving.
* A current installation of the Jaeger Operator.

.Procedure

. Create and apply a `Jaeger` custom resource (CR) that contains the following:
+
.Jaeger CR
[source,yaml]
----
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: default
----

. Enable tracing for Knative Serving, by editing the `KnativeServing` CR and adding a YAML configuration for tracing:
+
.Tracing YAML example
[source,yaml]
----
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    tracing:
      sample-rate: "0.1" <1>
      backend: zipkin <2>
      zipkin-endpoint: http://jaeger-collector.default.svc.cluster.local:9411/api/v2/spans <3>
      debug: "false" <4>
----
+
<1> The `sample-rate` defines sampling probability. Using `sample-rate: "0.1"` means that 1 in 10 traces will be sampled.
<2> `backend` must be set to `zipkin`.
<3> The `zipkin-endpoint` must point to your `jaeger-collector` service endpoint. To get this endpoint, substitute the namespace where the Jaeger CR is applied.
<4> Debugging should be set to `false`. Enabling debug mode by setting `debug: "true"` allows all spans to be sent to the server, bypassing sampling.

.Verification

You can access the Jaeger web console to see tracing data, by using the `jaeger` route.

. Get the `jaeger` route's hostname by entering the following command:
+
[source,terminal]
----
$ oc get route jaeger
----
+
.Example output
[source,terminal]
----
NAME     HOST/PORT                         PATH   SERVICES       PORT    TERMINATION   WILDCARD
jaeger   jaeger-default.apps.example.com          jaeger-query   <all>   reencrypt     None
----

. Open the endpoint address in your browser to view the console.
