// Module included in the following assemblies:
//
// * serverless/observability/admin-metrics/serverless-admin-metrics.adoc

:_mod-docs-content-type: REFERENCE
[id="serverless-knative-kafka-sink-metrics_{context}"]
= Knative Kafka sink metrics

[role="_abstract"]
You can use the following metrics to debug and visualize the performance of Kafka sinks.

[cols=5*,options="header"]
|===
|Metric name
|Description
|Type
|Tags
|Unit

|`kn_eventing_dispatch_latency_ms_count{job="kafka-sink-receiver-sm-service", namespace="knative-eventing"}`
|Number of events received by a Kafka sink
|Counter
a|
`kn_kafkasink_name`:: Kafka sink name
`kn_kafkasink_namespace`:: Kafka sink namespace
`cloudevents_type`:: CloudEvents type
`http_response_status_code`:: HTTP response code returned by the Kafka cluster
|Dimensionless

|`kn_eventing_dispatch_latency_ms_bucket{job="kafka-sink-receiver-sm-service", namespace="knative-eventing"}`
|The time spent dispatching an event to a Kafka cluster
|Histogram
a|
`kn_kafkasink_name`:: Kafka sink name
`kn_kafkasink_namespace`:: Kafka sink namespace
`cloudevents_type`:: CloudEvents type
`http_response_status_code`:: HTTP response code returned by the Kafka cluster
|Milliseconds

|===

[IMPORTANT]
====
Kafka sink metrics continue to use milliseconds (not seconds) for duration measurements.
====
