// Module included in the following assemblies:
//
// * knative-serving/debugging-serverless-applications.adoc

:_content-type: PROCEDURE
[id="serverless-applications-checking-revision-status_{context}"]
= Checking revision status

You might need to check the status of your revision to identify the issue with your Serverless application.

.Procedure

. If you configure your route with a `Configuration` object, get the name of the `Revision` object created for your deployment by running the following command:
+
[source,terminal]
----
$ oc get configuration <configuration_name> --output jsonpath="{.status.latestCreatedRevisionName}"
----
+
You can find the configuration name in the `Route.yaml` file, which specifies routing settings by defining an OpenShift `Route` resource.
+
If you configure your route with revision directly, look up the revision name in the `Route.yaml` file.

. Query for the status of the revision by running the following command:
+
[source,terminal]
----
$ oc get revision <revision-name> --output yaml
----
+
A ready revision should have the `reason: ServiceReady`, `status: "True"`, and `type: Ready` conditions in its status. If these conditions are present, you might want to check pod status or Istio routing. Otherwise, the resource status contains the error message.
