// Module included in the following assemblies:
//
// * serverless/cli_tools/kn-func-ref.adoc
// * serverless/functions/serverless-functions-getting-started.adoc

:_mod-docs-content-type: REFERENCE
[id="serverless-kn-func-run_{context}"]
= Running a function locally

[role="_abstract"]
You can run a function locally by using the `kn func` run command in the current directory or by specifying a directory with the `--path` flag.

If you run the function for the first time, or if you change the project files, the `kn func run` command builds the function before running it.

You can run a function in the current directory by using the following command:

[source,terminal]
----
$ kn func run
----

You can run a function in a specific directory by specifying the path with the `--path` flag:

[source,terminal]
----
$ kn func run --path=<directory_path>
----

You can also force a rebuild of an existing image before running the function, even if there have been no changes to the project files, by using the `--build` flag:

You can run a function and trigger a build by using the `--build` flag:

[source,terminal]
----
$ kn func run --build
----

If you set the `build` flag as false, this disables building of the image, and runs the function by using the previously built image:

You can run a function without building it by using the `--build=false` flag:

[source,terminal]
----
$ kn func run --build=false
----

You can use the help command to learn more about `kn func run` command options:

[source,terminal]
----
$ kn func help run
----
