// Module included in the following assemblies:
//

:_mod-docs-content-type: PROCEDURE
[id="serverless-logic-configuring-endpoint-url-openAPI-services_{context}"]
= Configuring the endpoint URL of OpenAPI services

After accessing the function definitions in workflow states, you can configure the endpoint URL of OpenAPI services.

.Prerequisites

* You have access to a {ServerlessLogicProductName} project with the appropriate roles and permissions to create applications and other workloads in {ocp-product-title}.
* You have created your {ServerlessLogicProductName} project.
* You have access to the OpenAPI specification files.
* You have defined the function definitions in the workflow.
* You have the access to the defined functions in the workflow states.


.Procedure

. Locate the OpenAPI specification file you want to configure. For example, `substraction.yaml`.

. Convert the file name into a valid configuration key by replacing special characters, such as `.`, with underscores and converting letters to lowercase. For example, change `substraction.yaml` to `substraction_yaml`.

. To define the configuration key, use the converted file name as the REST client configuration key. Set this key as an environment variable, as shown in the following example:
+
[source,sh]
----
quarkus.rest-client.subtraction_yaml.url=http://myserver.com
----

. To prevent hardcoding URLs in the `application.properties` file, use environment variable substitution, as shown in the following example: 
+
[source,sh]
----
quarkus.rest-client.subtraction_yaml.url=${SUBTRACTION_URL:http://myserver.com}
----
+ 
In this example:

* Configuration Key: `quarkus.rest-client.subtraction_yaml.url`
* Environment variable: SUBTRACTION_URL
* Fallback URL: `\http://myserver.com`

. Ensure that the `(SUBTRACTION_URL)` environment variable is set in your system or deployment environment. If the variable is not found, the application uses the fallback URL `(\http://myserver.com)`.

. Add the configuration key and URL substitution to the `application.properties` file:
+
[source,sh]
----
quarkus.rest-client.subtraction_yaml.url=${SUBTRACTION_URL:http://myserver.com}
----

. Deploy or restart your application to apply the new configuration settings.