// Module included in the following assemblies:
//
// * serverless/admin_guide/serverless-admin-monitoring.adoc

[id="serverless-admin-monitoring-serving-cpu-memory_{context}"]
= Monitoring Knative Serving revision CPU and memory usage

You can use the {product-title} monitoring dashboards to view revision CPU and memory usage metrics for Knative Serving components.

.Prerequisites

* You have cluster administrator permissions, and access to the *Administrator* perspective in the {product-title} web console.
* You have installed the {ServerlessOperatorName}, as well as the Knative Serving component.
* The {product-title} monitoring stack is enabled on your cluster. You can enable monitoring for {ServerlessProductName} during installation by checking the box to *Enable operator recommended cluster monitoring on this namespace* when installing the {ServerlessOperatorName}.

.Procedure

. In the *Administrator* perspective, navigate to *Observe* -> *Dashboards*.
. Select the *Knative Serving - Source CPU and Memory Usage* dashboard in the *Dashboard* drop-down list to view the following metrics:
** Total CPU Usage (rate per minute)
** Total Memory Usage (bytes)
** Total Network I/O (rate per minute)
** Total Network Errors (rate per minute)
. Optional: You can filter this dashboard by *Namespace*, *Configuration*, or *Revision*, by selecting an option from the drop-down list.
