// Module included in the following assemblies:
//
// * rosa_cluster_admin/rosa-configuring-pid-limits.adoc
// * osd_cluster_admin/osd-configuring-pid-limits.adoc

:_mod-docs-content-type: PROCEDURE
[id="setting-higher-pid-limit-on-existing-cluster-ocm_{context}"]
= Setting the process IDs limit using OpenShift Cluster Manager

You can set the process IDs (PIDs) limit on an existing {product-title} cluster by using {cluster-manager}.

[IMPORTANT]
====
Changing the PIDs limit on an existing cluster will trigger non-control plane nodes in the cluster to reboot one at a time. Make this change outside of peak usage hours for your cluster and avoid upgrading or hibernating your cluster until all nodes have rebooted.
====

ifdef::openshift-dedicated[]
.Prerequisites
* You have an {product-title} cluster with the Customer Cloud Subscription (CCS) model.
endif::openshift-dedicated[]

.Procedure

. Navigate to {cluster-manager-url} and select your cluster.

. Under the *Machine pools* tab, click *Edit machine configuration*.

. Adjust the PIDs limit, and then click *Save changes*.
+
A cluster-wide rolling reboot of worker nodes is triggered.
