// Module included in the following assemblies:
//
// * security/security_profiles_operator/spo-seccomp.adoc
// * security/security_profiles_operator/spo-selinux.adoc

ifeval::["{context}" == "spo-seccomp"]
:seccomp:
:type: seccomp
:kind: SeccompProfile
endif::[]
ifeval::["{context}" == "spo-selinux"]
:selinux:
:type: SELinux
:kind: SelinuxProfile
endif::[]

:_content-type: PROCEDURE
[id="spo-recording-profiles_{context}"]
= Recording profiles from workloads

The Security Profiles Operator can record system calls with `ProfileRecording` objects, making it easier to create baseline profiles for applications.

When using the log enricher for recording {type} profiles, verify the log enricher feature is enabled. See _Additional resources_ for more information.

[NOTE]
====
A container with `privileged: true` security context restraints prevents log-based recording. Privileged containers are not subject to {type} policies, and log-based recording makes use of a special {type} profile to record events.
====

.Procedure

. Label the namespace with `enable-recording=true` by running the following command:
+
[source,terminal]
----
$ oc label ns my-namespace spo.x-k8s.io/enable-recording=true
----

. Create a `ProfileRecording` object containing a `recorder: logs` variable:
+
[source,yaml,subs="attributes+"]
----
apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: ProfileRecording
metadata:
  name: test-recording
spec:
  kind: {kind}
  recorder: logs
  podSelector:
    matchLabels:
      app: my-app
----

. Create a workload to record:
+
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    - name: nginx
      image: quay.io/security-profiles-operator/test-nginx-unprivileged:1.21
      ports:
        - containerPort: 8080
    - name: redis
      image: quay.io/security-profiles-operator/redis:6.2.1
----

. Confirm the pod is in a `Running` state by entering the following command:
+
[source,terminal]
----
$ oc -n openshift-security-profiles get pods
----
+
.Example output
[source,terminal]
----
NAME     READY   STATUS    RESTARTS   AGE
my-pod   2/2     Running   0          18s
----

. Confirm the enricher indicates that it receives audit logs for those containers:
+
[source,terminal]
----
$ oc -n openshift-security-profiles logs --since=1m --selector name=spod -c log-enricher
----
+
.Example output
[source,terminal]
----
…
I0705 12:08:18.729660 1843190 enricher.go:136] log-enricher "msg"="audit"  "container"="redis" "executable"="/usr/local/bin/redis-server" "namespace"="default" "node"="127.0.0.1" "pid"=1847839 "pod"="my-pod" "syscallID"=232 "syscallName"="epoll_wait" "timestamp"="1625486870.273:187492" "type"="{type}"
----

.Verification

. Remove the pod:
+
[source,terminal]
----
$ oc -n openshift-security-profiles delete pod my-pod
----

. Confirm the Security Profiles Operator reconciles the two {type} profiles:
+
[source,terminal]
----
$ oc -n openshift-security-profiles get sp
----
+
.Example output
[source,terminal]
----
NAME                   STATUS      AGE
test-recording-nginx   Installed   15s
test-recording-redis   Installed   15s
----

ifeval::["{context}" == "spo-seccomp"]
:!seccomp:
:!type:
:!kind:
endif::[]
ifeval::["{context}" == "spo-selinux"]
:!selinux:
:!type:
:!kind:
endif::[]