// Module included in the following assemblies:
//
// * networking/hardware_networks/configuring-sriov-ipam.adoc

:_mod-docs-content-type: REFERENCE
[id="sriov-ipam-configure-dual-stack_{context}"]
= Configure dual-stack IP addressing

[role="_abstract"]
Configure an SR-IOV network to assign both IPv4 and IPv6 addresses using Whereabouts or static configuration.

== Dual-stack with Whereabouts

Configure Whereabouts to allocate both IPv4 and IPv6 addresses automatically:

. Create an SR-IOV network with dual-stack Whereabouts configuration:
+
[source,yaml]
----
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov-network-dual-stack
  namespace: openshift-sriov-network-operator
spec:
  resourceName: intelnics
  networkNamespace: default
  vlan: 0
  ipam: |
    {
      "type": "whereabouts",
      "ipRanges": [                              
        {
          "range": "192.168.1.0/24",
          "range_start": "192.168.1.10",
          "range_end": "192.168.1.100",
          "gateway": "192.168.1.1"
        },
        {
          "range": "fd00:192:168:1::/64",        
          "range_start": "fd00:192:168:1::10",
          "range_end": "fd00:192:168:1::100",
          "gateway": "fd00:192:168:1::1"
        }
      ]
    }
----
 Use `ipRanges` array to specify multiple IP address ranges.
 IPv6 range configuration.

. Create the SR-IOV network:
+
[source,terminal]
----
$ oc create -f sriov-network-dual-stack.yaml
----

. Create a pod that uses dual-stack addressing:
+
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: pod-dual-stack
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-network-dual-stack
spec:
  containers:
  - name: test
    image: registry.access.redhat.com/ubi9/ubi:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      requests:
        openshift.io/intelnics: "1"
      limits:
        openshift.io/intelnics: "1"
----

. Create the pod:
+
[source,terminal]
----
$ oc create -f pod-dual-stack.yaml
----

.Verification

. Verify the pod received both IPv4 and IPv6 addresses:
+
[source,terminal]
----
$ oc exec -it pod-dual-stack -- ip addr show net1
----
+
.Example output
[source,terminal]
----
3: net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 3c:fd:fe:b8:7f:f8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.10/24 brd 192.168.1.255 scope global net1
    inet6 fd00:192:168:1::10/64 scope global
    inet6 fe80::3efd:feff:feb8:7ff8/64 scope link
----
+
The interface should have both an IPv4 address and an IPv6 address from your configured ranges.

== Dual-stack with static IPs

Configure specific IPv4 and IPv6 addresses for a pod using static assignment:

. Create an SR-IOV network without IPAM configuration:
+
[source,yaml]
----
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov-network-static-dual
  namespace: openshift-sriov-network-operator
spec:
  resourceName: intelnics
  networkNamespace: default
  vlan: 0
----

. Create a pod with static dual-stack IP addresses:
+
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: pod-static-dual-stack
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [{
        "name": "sriov-network-static-dual",
        "ips": [                                    
          "192.168.1.10/24",
          "fd00:192:168:1::10/64"
        ],
        "gateway": ["192.168.1.1", "fd00:192:168:1::1"]  
      }]
spec:
  containers:
  - name: test
    image: registry.access.redhat.com/ubi9/ubi:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      requests:
        openshift.io/intelnics: "1"
      limits:
        openshift.io/intelnics: "1"
----
 Array of IP addresses including both IPv4 and IPv6.
 Array of gateways for IPv4 and IPv6.

.Verification

. Verify both IP addresses are configured:
+
[source,terminal]
----
$ oc exec -it pod-static-dual-stack -- ip addr show net1
----

. Test IPv4 connectivity:
+
[source,terminal]
----
$ oc exec -it pod-static-dual-stack -- ping -c 4 192.168.1.1
----

. Test IPv6 connectivity:
+
[source,terminal]
----
$ oc exec -it pod-static-dual-stack -- ping6 -c 4 fd00:192:168:1::1
----

[NOTE]
====
DHCP can also provide dual-stack addressing if your DHCP server is configured to provide both IPv4 and IPv6 addresses. The configuration is the same as single-stack DHCP - the DHCP server determines which IP addresses are assigned.
====
