// Module included in the following assemblies:
//
// * storage/understanding-persistent-storage.adoc

:_content-type: PROCEDURE
[id="storage-skip-selinux-relabeling_{context}"]
= Skip SELinux Relabeling using the spc_t SELinux context

The SELinux Super Privileged Container type, `spc_t`, defines a container that will not be constrained by SELinux policies.

If a pod `securityContext` has `type: spc_t` set, it will be inherited by containers that have no `type` specified. When this option is configured, CRI-O will skip the SELinux relabel process.

[WARNING]
====
If a pod is running with an SCC with the `runAsUser` attribute set to `runAsAny`, an unconstrained container process might be able to overwrite files on the host.
====

.Prerequisites

* You have access to the cluster as a user with the `cluster-admin` role.

.Procedure

. Create a custom SCC called `custom_scc.yaml`:
+
[source,yaml]
----
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups:
- system:authenticated
kind: SecurityContextConstraints
metadata:
  name: custom
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
----

. Assign the custom SCC to the service account and namespace:
+
[source,terminal]
----
$ oc adm policy add-scc-to-user custom -z <service-account> -n <namespace>
----

. Add the following changes to the `Deployment` object in the `securityContext` attribute:
+
[source,yaml]
----
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        seLinuxOptions:
          type: spc_t
----

[id="automating-selinux-cro_{context}"]
== Automating SELinux Relabeling using the Cluster Resource Override Operator

The Cluster Resource Override Operator (CRO) has been extended to allow for users to automate applying the `spc_t` label. The CRO Operator applies the `spc_t` SELinux context per namespace when the CRO is configured with the `forceSelinuxRelabel` attribute set to `true`.

.Procedure

. Install the CRO Operator:

.. In the {product-title} web console, navigate to *Home* -> *Projects*

... Click *Create Project*.

... Specify `clusterresourceoverride-operator` as the name of the project.

... Click *Create*.

.. Navigate to *Operators* -> *OperatorHub*.

... Choose  *ClusterResourceOverride Operator* from the list of available Operators and click *Install*.

... On the *Install Operator* page, make sure *A specific Namespace on the cluster* is selected for *Installation Mode*.

... Make sure *clusterresourceoverride-operator* is selected for *Installed Namespace*.

... Select an *Update Channel* and *Approval Strategy*.

... Click *Install*.

.. On the *Installed Operators* page, click *ClusterResourceOverride*.

... On the *ClusterResourceOverride Operator* details page, click *Create Instance*.

... On the *Create ClusterResourceOverride* page, edit the YAML template to set the overcommit values as needed:
+
[source,yaml]
----
apiVersion: operator.autoscaling.openshift.io/v1
kind: ClusterResourceOverride
metadata:
  name: cluster <1>
spec:
  podResourceOverride:
    spec:
      memoryRequestToLimitPercent: 50 <2>
      cpuRequestToLimitPercent: 25 <3>
      limitCPUToMemoryPercent: 200 <4>
      forceSelinuxRelabel: true <5>
----
<1> The name must be `cluster`.
<2> Optional. Specify the percentage to override the container memory limit, if used, between 1-100. The default is 50.
<3> Optional. Specify the percentage to override the container CPU limit, if used, between 1-100. The default is 25.
<4> Optional. Specify the percentage to override the container memory limit, if used. Scaling 1Gi of RAM at 100 percent is equal to 1 CPU core. This is processed prior to overriding the CPU request, if configured. The default is 200.
<5> Forces the SELinux relabeling policy.

... Click *Create*.
+
The CRO is now installed and configured.

. Configure the Security Context Constraint (SCC):

.. Save the following to the `cro-selinux-context-scc.yaml` file to create the SCC called `custom`:
+
[source,yaml]
----
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups:
- system:authenticated
kind: SecurityContextConstraints
metadata:
  name: custom
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
----

. Create a namespace file called `cro-selinux-context-ns.yaml` with the following contents:
+
[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
 name: selinux-relabel
 labels:
   clusterresourceoverrides.admission.autoscaling.openshift.io/enabled: "true"
   forceselinuxrelabel.admission.node.openshift.io/enabled: "true"
----

. Run the following command to create the namespace:
+
[source,terminal]
----
 $ oc create -f cro-selinux-context-ns.yaml
----

.. Create the SCC in the global namespace:
+
[source,terminal]
----
 $ oc create -f cro-selinux-context-scc.yaml
----

.. Apply the SCC to the `selinux-relabel` namespace:
+
[source,terminal]
----
 $ oc adm policy add-scc-to-user custom -z default -n selinux-relabel
----