// Module included in the following assemblies
//
// * storage/expanding-persistent-volumes.adoc
//* microshift_storage/expanding-persistent-volumes-microshift.adoc

:_mod-docs-content-type: PROCEDURE
[id="expanding-recovering-from-failure_{context}"]
= Recovering from failure when expanding volumes

If a resize request fails or remains in a pending state, you can try again by entering a different resize value in `.spec.resources.requests.storage` for the persistent volume claim (PVC). The new value must be larger than the original volume size.

If you are still having issues, use the following procedure to recover.

.Procedure
If entering another smaller resize value in `.spec.resources.requests.storage` for the PVC does not work, do the following:

. Mark the persistent volume (PV) that is bound to the PVC with the `Retain` reclaim policy. Change `persistentVolumeReclaimPolicy` to `Retain`.

. Delete the PVC.

. Manually edit the PV and delete the `claimRef` entry from the PV specs to ensure that the newly created PVC can bind to the PV marked `Retain`. This marks the PV as `Available`.

. Re-create the PVC in a smaller size, or a size that can be allocated by the underlying storage provider.

. Set the `volumeName` field of the PVC to the name of the PV. This binds the PVC to the provisioned PV only.

. Restore the reclaim policy on the PV.
