// Be sure to set the :provider: value in each assembly
// on the line before the include statement for this module.
// For example:
// :provider: AWS
//
// Module included in the following assemblies:
//
// * storage/persistent_storage-aws.adoc
// * storage/persistent_storage-gce.adoc

:_mod-docs-content-type: CONCEPT
[id="volume-format-{provider}_{context}"]
= Volume format

[role="_abstract"]
You can use unformatted {provider} volumes as persistent volumes, because {product-title} automatically formats the device before mounting it to a container.

Before {product-title} mounts the volume and passes it to a container, it checks that the volume contains a file system as specified by the `fsType` parameter in the persistent volume definition. If the device is not formatted with the file system, all data from the device is erased and the device is automatically formatted with the given file system.

// Undefined {provider} attribute, so that any mistakes are easily spotted
:!provider:
