// Module included in the following assemblies:
//
// * storage/persistent_storage-aws.adoc

:_mod-docs-content-type: PROCEDURE
[id="creating-volume-claim_{context}"]
= Creating the persistent volume claim

[role="_abstract"]
You can create a persistent volume claim by using the {product-title} web console to request storage resources for your applications by specifying the storage class, access mode, and size.

.Prerequisites

* Storage exists in the underlying infrastructure.

.Procedure

. In the {product-title} web console, click *Storage* -> *Persistent Volume Claims*.

. In the persistent volume claims overview, click *Create Persistent Volume Claim*.

. Define the required options on the page that is displayed.

.. Select the previously-created storage class from the drop-down menu.

.. Enter a unique name for the storage claim.

.. Select the access mode. This selection determines the read and write access for the storage claim.

.. Define the size of the storage claim.

. Click *Create* to create the persistent volume claim and generate a persistent
volume.
