// Module included in the following assemblies:
//
// * support/index.adoc

:_mod-docs-content-type: CONCEPT
[id="support-gather-data-cluster_{context}"]
= Cluster data collection

[role="_abstract"]
Diagnostic tools and system logs provide the critical debugging information that Red Hat Support requires to troubleshoot and resolve cluster issues.

A cluster administrator can use the following to gather data about your cluster:

* *must-gather tool*: Use the `must-gather` tool to collect information about your cluster and to debug the issues.
* *sosreport*:  Use the `sosreport` tool to collect configuration details, system information, and diagnostic data for debugging purposes.
* *Cluster ID*: Obtain the unique identifier for your cluster, when providing information to Red Hat Support.
ifndef::openshift-rosa,openshift-rosa-hcp,openshift-dedicated[]
* *Bootstrap node journal logs*: Gather `bootkube.service` `journald` unit logs and container logs from the bootstrap node to troubleshoot bootstrap-related issues.
endif::openshift-rosa,openshift-rosa-hcp,openshift-dedicated[]
* *Cluster node journal logs*: Gather `journald` unit logs and logs within `/var/log` on individual cluster nodes to troubleshoot node-related issues.
* *Network trace*: Provide a network packet trace from a specific {product-title} cluster node or a container to Red Hat Support to help troubleshoot network-related issues.
