// Module included in the following assemblies:
//
// * networking/networking_operators/aws-load-balancer-operator.adoc

:_mod-docs-content-type: PROCEDURE
[id="tagging-aws-vpc-subnets_{context}"]
= Tag the AWS VPC and subnets

[role="_abstract"]
To prepare your environment for the AWS Load Balancer Operator, tag your AWS Virtual Private Cloud (VPC) resources. This configuration ensures that the Operator can correctly identify and manage your network resources.

.Prerequisites

* You have installed the AWS CLI (`aws`).
* You have installed the {oc-first}.

.Procedure

. Optional: Set up environment variables for AWS VPC resources.
+
[source,terminal]
----
$ export VPC_ID=<vpc_id>
----
+
[source,terminal]
----
$ export PUBLIC_SUBNET_IDS="<public_subnet_a_id> <public_subnet_b_id> <public_subnet_c_id>"
----
+
[source,terminal]
----
$ export PRIVATE_SUBNET_IDS="<private_subnet_a_id> <private_subnet_b_id> <private_subnet_c_id>"
----

. Tag your VPC to associate it with your cluster:
+
[source,terminal]
----
$ aws ec2 create-tags --resources ${VPC_ID} --tags Key=kubernetes.io/cluster/${CLUSTER_NAME},Value=owned --region ${REGION}
----

. Tag your public subnets to allow changes by elastic load balancing roles, and tag your private subnets to allow changes by internal elastic load balancing roles:
+
[source,bash]
----
cat <<EOF > "${SCRATCH}/tag-subnets.sh"
#!/bin/bash

aws ec2 create-tags \
     --resources ${PUBLIC_SUBNET_IDS} \
     --tags Key=kubernetes.io/role/elb,Value='' \
     --region ${REGION}

aws ec2 create-tags \
     --resources ${PRIVATE_SUBNET_IDS} \
     --tags Key=kubernetes.io/role/internal-elb,Value='' \
     --region ${REGION}

EOF
----

. Run the script: 
+
[source,bash]
----
bash ${SCRATCH}/tag-subnets.sh
----
