// Module included in the following assemblies:
//
// * scalability_and_performance/telco-hub-rds.adoc

:_mod-docs-content-type: CONCEPT
[id="telco-hub-networking_{context}"]
= Networking

The reference hub cluster is designed to operate in a disconnected networking environment where direct access to the internet is not possible.
As with all {product-title} clusters, the hub cluster requires access to an image registry hosting all OpenShift and Day 2 Operator Lifecycle Manager (OLM) images.

The hub cluster supports dual-stack networking support for IPv6 and IPv4 networks.
IPv6 is typical in edge or far-edge network segments, while IPv4 is more prevalent for use with legacy equipment in the data center.

Limits and requirements::
+
--
* Regardless of the installation method, the following network types must be configured for the hub cluster:
** `clusterNetwork`
** `serviceNetwork`
** `machineNetwork`

* The following IP addresses must be configured for the hub cluster:
** `apiVIP`
** `ingressVIP` - Some values are required or can be auto-assigned depending on the chosen architecture and DHCP configuration

* The default {product-title} network provider, OVN Kubernetes, must be used

* Networking between the managed cluster and hub cluster must meet the requirements listed in link:https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.12/html/clusters/cluster_mce_overview#mce-network-configuration[Network configuration], including setting the following:
** Hub cluster access to managed cluster API service, Ironic Python Agent and BMC port
** Managed cluster access to hub cluster API service, ingress IP and control plane node IP addresses
** Managed cluster BMC access to hub cluster control plane node IP addresses
* An image registry must be accessible throughout the lifetime of the hub cluster
** All required container images must be mirrored to the disconnected registry
** The hub cluster must be configured to use a disconnected registry.
** The hub cluster cannot host its own image registry.
For example, the registry must be available in case of an unanticipated power failure occurs affecting all cluster nodes.
--

Engineering considerations::
* When deploying a hub cluster, ensure appropriately sized CIDR range definitions are defined.
For more information about cluster networking, refer to the following:
