// Module included in the following assemblies:
//
// * scalability_and_performance/ztp_far_edge/telco_core_ref_design_specs/telco-core-ref-crs.adoc

:_mod-docs-content-type: REFERENCE
[id="storage-crs_{context}"]
= Storage reference CRs

.Storage CRs
[cols="4*", options="header", format=csv]
|====
Component,Reference CR,Optional,New in this release
External {rh-storage-first} configuration,xref:../../../scalability_and_performance/ztp_far_edge/telco_core_ref_design_specs/telco-core-ref-crs.adoc#telco-core-odfns-yaml[odfNS.yaml],No,No
External {rh-storage} configuration,xref:../../../scalability_and_performance/ztp_far_edge/telco_core_ref_design_specs/telco-core-ref-crs.adoc#telco-core-odfopergroup-yaml[odfOperGroup.yaml],No,No
External {rh-storage} configuration,xref:../../../scalability_and_performance/ztp_far_edge/telco_core_ref_design_specs/telco-core-ref-crs.adoc#telco-core-odfsubscription-yaml[odfSubscription.yaml],No,No
External {rh-storage} configuration,xref:../../../scalability_and_performance/ztp_far_edge/telco_core_ref_design_specs/telco-core-ref-crs.adoc#telco-core-01-rook-ceph-external-cluster-details.secret-yaml[01-rook-ceph-external-cluster-details.secret.yaml],No,No
External {rh-storage} configuration,xref:../../../scalability_and_performance/ztp_far_edge/telco_core_ref_design_specs/telco-core-ref-crs.adoc#telco-core-02-ocs-external-storagecluster-yaml[02-ocs-external-storagecluster.yaml],No,No
|====
