// Module included in the following assemblies:
//
// *
:_mod-docs-content-type: CONCEPT
[id="telco-ref-design-overview_{context}"]
= Reference design specifications for telco 5G deployments

Red Hat and certified partners offer deep technical expertise and support for networking and operational capabilities required to run telco applications on {product-title} {product-version} clusters.

Red Hat's telco partners require a well-integrated, well-tested, and stable environment that can be replicated at scale for enterprise 5G solutions.
The telco core and RAN DU reference design specifications (RDS) outline the recommended solution architecture based on a specific version of {product-title}.
Each RDS describes a tested and validated platform configuration for telco core and RAN DU use models.
The RDS ensures an optimal experience when running your applications by defining the set of critical KPIs for telco 5G core and RAN DU.
Following the RDS minimizes high severity escalations and improves application stability.

5G use cases are evolving and your workloads are continually changing.
Red Hat is committed to iterating over the telco core and RAN DU RDS to support evolving requirements based on customer and partner feedback.
