// Module included in the following assemblies:
//
// support/remote_health_monitoring/opting-out-of-telemetry.adoc

[id="telemetry-consequences-of-disabling-telemetry_{context}"]
= Consequences of disabling remote health reporting

In {product-title}, customers can opt out of reporting health and usage information. However, connected clusters allow Red Hat to react more quickly to problems and better support our customers, as well as better understand how product upgrades impact clusters.

Red Hat strongly recommends leaving health and usage reporting enabled for pre-production and test clusters even if it is necessary to opt out for production clusters. This allows Red Hat to be a participant in qualifying {product-title} in your environments and react more rapidly to product issues.

Some of the consequences of opting out of having a connected cluster are:

* Red Hat will not be able to monitor the success of product upgrades or the health of your clusters without a support case being opened.
* Red Hat will not be able to use anonymized configuration data to better triage customer support cases and identify which configurations our customers find important.
* The {cloud-redhat-com} will not show data about your clusters including health and usage information.
* Your subscription entitlement information must be manually entered via cloud.redhat.com without the benefit of automatic usage reporting.

In restricted networks, Telemetry and Insights data can still be reported through appropriate configuration of your proxy.
