// Module included in the following assemblies:
//
// * machine_management/cluster_api_machine_management/cluster-api-troubleshooting.adoc

:_mod-docs-content-type: PROCEDURE
[id="ts-capi-migrate-unexpected-deletion-behavior_{context}"]
= Unexpected resource deletion behavior

When you delete a compute machine set, the machines that it created become _unmanaged_.
You can determine whether a machine is unmanaged by checking the value of the `.metadata.ownerReferences` parameter.
The machine specification for an unmanaged machine has no value set for this parameter.
Machine sets do not have a `.metadata.ownerReferences` parameter and are therefore also considered unmanaged.

On clusters that support migrating resources between the Machine API and the Cluster API, users might experience unexpected behavior when deleting unmanaged Cluster API resources on a cluster where the Machine API is authoritative.

Cause::

For any resource that uses the authoritative API, the two-way synchronization controller creates and maintains corresponding unmanaged resources that do not use the current authoritative API.
+
The deletion behavior for unmanaged resources depends on which API is authoritative.
+
--
* When you delete an unmanaged Cluster API resource on a cluster where the Machine API is authoritative, the synchronization controller deletes the corresponding Machine API resource.

* When you delete an unmanaged Machine API resource on a cluster where the Cluster API is authoritative, the synchronization controller does not delete the corresponding Cluster API resource.
--
+
This behavior occurs when deleting resources directly and when performing scale-down operations.

Consequence::

This different behavior depending on which API is authoritative has the following consequences:
+
--
* For clusters on which the Cluster API is authoritative, you can remove unmanaged Machine API resources with no impact to the corresponding Cluster API resources.

* For clusters on which the Machine API is authoritative, you cannot remove unmanaged Cluster API resources without also deleting the corresponding Machine API resources.
--

Workaround::

For clusters on which the Machine API is authoritative, do not delete any unmanaged Cluster API resource unless you want to delete the corresponding Machine API resource.
