// Module included in the following assemblies:
//
// * support/troubleshooting/diagnosing-oc-issues.adoc

:_mod-docs-content-type: CONCEPT
[id="understanding-oc-log-levels_{context}"]
= Understanding OpenShift CLI (`oc`) log levels

With the OpenShift CLI (`oc`), you can create applications and manage {product-title} projects from a terminal.

If `oc` command-specific issues arise, increase the `oc` log level to output API request, API response, and `curl` request details generated by the command. This provides a granular view of a particular `oc` command's underlying operation, which in turn might provide insight into the nature of a failure.

`oc` log levels range from 1 to 10. The following table provides a list of `oc` log levels, along with their descriptions.

.OpenShift CLI (`oc`) log levels
[cols="1,4",options="header"]
|===
| Log level | Description

| 1 to 5
| No additional logging to stderr.

| 6
| Log API requests to stderr.

| 7
| Log API requests and headers to stderr.

| 8
| Log API requests, headers, and body, plus API response headers and body to stderr.

| 9
| Log API requests, headers, and body, API response headers and body, plus `curl` requests to stderr.

| 10
| Log API requests, headers, and body, API response headers and body, plus `curl` requests to stderr, in verbose detail.
|===
