// Module included in the following assemblies:
//
// * operating/manage-vulnerabilities/common-vuln-management-tasks.adoc

:_mod-docs-content-type: PROCEDURE
[id="unsnooze-cves-vm20_{context}"]
= Unsnoozing platform and node CVEs

[role="_abstract"]
You can unsnooze platform and node CVEs that you have previously snoozed.

[NOTE]
====
The ability to snooze a CVE is not enabled by default in the web portal or in the API. To enable the ability to snooze CVEs, set the runtime environment variable `ROX_VULN_MGMT_LEGACY_SNOOZE` to `true`.
====

.Procedure

. In the {product-title-short} portal, do any of the following tasks:
* To view the list of platform CVEs, click *Vulnerability Management* -> *Platform CVEs*.
* To view the list of node CVEs, click *Vulnerability Management* -> *Node CVEs*.
. To view the list of snoozed CVEs, click *Show snoozed CVEs* in the header view.
. Select one or more CVEs from the list of snoozed CVEs.
. Select the appropriate method to unsnooze the CVE:
* If you selected a single CVE, click the overflow menu, {kebab}, and then select *Unsnooze CVE*.
* If you selected multiple CVEs, click *Bulk actions* -> *Unsnooze CVEs*.
. Click *Unsnooze CVEs* again.
+
You receive a confirmation that you have requested to unsnooze the CVEs.
