// Module included in the following assemblies:
//
// * updating/updating-restricted-network-cluster.adoc

[id="update-restricted_{context}"]
= Upgrading the restricted network cluster

Update the restricted network cluster to the {product-title} version that you downloaded the release images for.

//TODO: Add xrefs in the following note when functionality is enabled.

[NOTE]
====
If you have a local OpenShift Update Service, you can update by using the connected web console or CLI instructions instead of this procedure.
====

.Prerequisites

* You mirrored the images for the new release to your registry.
* You applied the release image signature ConfigMap for the new release to your cluster.
* You obtained the sha256 sum value for the release from the image signature ConfigMap.
* Install the OpenShift CLI (`oc`).
* Pause all `MachineHealthCheck` resources.

.Procedure

* Update the cluster:
+
[source,terminal]
----
$ oc adm upgrade --allow-explicit-upgrade --to-image ${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}<sha256_sum_value> <1>
----
<1> The `<sha256_sum_value>` value is the sha256 sum value for the release from the image signature ConfigMap, for example, `@sha256:81154f5c03294534e1eaf0319bef7a601134f891689ccede5d705ef659aa8c92`
+
If you use an `ImageContentSourcePolicy` for the mirror registry, you can use the canonical registry name instead of `LOCAL_REGISTRY`.
+
[NOTE]
====
You can only configure global pull secrets for clusters that have an `ImageContentSourcePolicy` object. You cannot add a pull secret to a project.
====
