// Module included in the following assemblies:
//
// * updating/updating-restricted-network-cluster.adoc

[id="update-configuring-image-signature"]
= Creating an image signature ConfigMap manually

Create and apply the image signature ConfigMap to the cluster that you want to update.

[NOTE]
====
You must perform following steps each time that you update a cluster.
====

.Procedure

. Review the link:https://access.redhat.com/solutions/4583231[{product-title} upgrade paths] knowledge base article to determine a valid upgrade path for your cluster.

. Add the version to the `OCP_RELEASE_NUMBER` environment variable:
+
----
$ OCP_RELEASE_NUMBER=<release_version> <1>
----
<1> For `<release_version>`, specify the tag that corresponds to the version of {product-title} you want
to update the cluster, such as `4.4.0`.

. Add the system architecture for your cluster to `ARCHITECTURE` environment variable:
+
----
$ ARCHITECTURE=<server_architecture> <11>
----
<1> For `server_architecture`, specify the architecture of the server, such as `x86_64`.

. Get the release image digest from link:https://quay.io/[Quay]:
+
----
$ DIGEST="$(oc adm release info quay.io/openshift-release-dev/ocp-release:${OCP_RELEASE_NUMBER}-${ARCHITECTURE} | sed -n 's/Pull From: .*@//p')"
----

. Set the digest algorithm:
+
----
$ DIGEST_ALGO="${DIGEST%%:*}"
----

. Set the digest signature:
+
----
$ DIGEST_ENCODED="${DIGEST#*:}"
----

. Get the image signature from link:https://mirror.openshift.com/pub/openshift-v4/signatures/openshift/release[mirror.openshift.com] website.
+
----
$ SIGNATURE_BASE64=$(curl -s "https://mirror.openshift.com/pub/openshift-v4/signatures/openshift/release/${DIGEST_ALGO}=${DIGEST_ENCODED}/signature-1" | base64 -w0 && echo)
----

. Create the ConfigMap:
+
----
$ cat >checksum-${OCP_RELEASE_NUMBER}.yaml <<EOF
 apiVersion: v1
 kind: ConfigMap
 metadata:
   name: release-image-${OCP_RELEASE_NUMBER}
   namespace: openshift-config-managed
   labels:
     release.openshift.io/verification-signatures: ""
 binaryData:
   ${DIGEST_ALGO}-${DIGEST_ENCODED}: ${SIGNATURE_BASE64}
 EOF
----

. Apply the ConfigMap to the cluster to update:
+
----
$ oc apply -f checksum-${OCP_RELEASE_NUMBER}.yaml
----
