// Module included in the following assemblies:
//
// * updating/updating_a_cluster/updating-cluster-cli.adoc

:_mod-docs-content-type: PROCEDURE
[id="update-upgrading-oc-adm-upgrade-status_{context}"]
= Gathering cluster update status using oc adm upgrade status (Technology Preview)

When updating your cluster, the `oc adm upgrade` command returns returns limited information about the status of your update. You can use the `oc adm upgrade status` command to decouple status information from the `oc adm upgrade` command and return specific information regarding a cluster update, including the status of the control plane and worker node updates.

The `oc adm upgrade status` command is read-only and does not alter any state in your cluster. 

:FeatureName: The `oc adm upgrade status` command
include::snippets/technology-preview.adoc[]

The `oc adm upgrade status` command can be used for clusters from version 4.12 up to the latest supported release. 

[NOTE]
====
Your cluster does not need to be a Technology Preview-enabled cluster in order for you to use the `oc adm upgrade status` command. 
====

.Procedure 

. Set the `OC_ENABLE_CMD_UPGRADE_STATUS` environment variable to `true` by running the following command:
+
[source,terminal]
----
$ export OC_ENABLE_CMD_UPGRADE_STATUS=true
----
. Run the `oc adm upgrade status` command:
+
[source,terminal]
----
$ oc adm upgrade status
----
+
.Example output for an update progressing successfully

[source,terminal]
----
= Control Plane =
Assessment:      Progressing
Target Version:  4.17.1 (from 4.17.0)
Updating:        machine-config
Completion:      97% (32 operators updated, 1 updating, 0 waiting)
Duration:        54m (Est. Time Remaining: <10m)
Operator Status: 32 Healthy, 1 Unavailable

Control Plane Nodes
NAME                                        ASSESSMENT    PHASE      VERSION   EST    MESSAGE
ip-10-0-53-40.us-east-2.compute.internal    Progressing   Draining   4.17.0    +10m
ip-10-0-30-217.us-east-2.compute.internal   Outdated      Pending    4.17.0    ?
ip-10-0-92-180.us-east-2.compute.internal   Outdated      Pending    4.17.0    ?

= Worker Upgrade =

WORKER POOL   ASSESSMENT    COMPLETION   STATUS
worker        Progressing   0% (0/2)     1 Available, 1 Progressing, 1 Draining
infra         Progressing   50% (1/2)    1 Available, 1 Progressing, 1 Draining

Worker Pool Nodes: Worker
NAME                                       ASSESSMENT    PHASE      VERSION   EST    MESSAGE
ip-10-0-4-159.us-east-2.compute.internal   Progressing   Draining   4.17.0    +10m 
ip-10-0-99-40.us-east-2.compute.internal   Outdated      Pending    4.17.0    ?

Worker Pool Nodes: infra
NAME                                             ASSESSMENT    PHASE      VERSION   EST    MESSAGE
ip-10-0-4-159-infra.us-east-2.compute.internal   Progressing   Draining   4.17.0    +10m
ip-10-0-20-162.us-east-2.compute.internal        Completed     Updated    4.17.1    - 

= Update Health =
SINCE   LEVEL   IMPACT   MESSAGE
54m4s   Info    None     Update is proceeding well
----