// Module included in the following assemblies:
//
// * configuration/enable-offline-mode.adoc

:_mod-docs-content-type: CONCEPT
[id="updating-scanner-definitions-offline-overview_{context}"]
= Updating Scanner definitions in offline mode

[role="_abstract"]
Scanner maintains a database of vulnerabilities. When {rh-rhacs-first} runs in normal mode, Central retrieves the latest vulnerability data from the internet, and Scanner retrieves vulnerability data from Central.

However, if you are using {product-title-short} in offline mode, you must manually update the vulnerability data. To manually update the vulnerability data, you must upload a definitions file to Central, and Scanner then retrieves the vulnerability data from Central.

In both online and offline mode, Scanner checks for new data from Central every 5 minutes by default. In online mode, Central also checks for new data from the internet approximately every 5-20 minutes.

The offline data source is updated approximately every 3 hours. After the data has been uploaded to Central, Scanner downloads the data and updates its local vulnerability database.

To update the definitions in offline mode, you must download the definitions and then upload them to Central.
