// Module included in the following assemblies:
//
// * authentication/managing-security-context-constraints.adoc

:_content-type: PROCEDURE
[id="secure-computing-using_{context}"]
= Using secure computing profiles

You can use secure computing (seccomp) profiles by using the OpenShift CLI (`oc`).

.Prerequisites

* Install the OpenShift CLI (`oc`).
* Log in to the cluster as a user with the `cluster-admin` role.

.Procedure

. Copy the seccomp profile to your local host by running the following command:
+
[source,terminal]
----
$ oc debug node/<nodename>
----
+
.Example output
[source,terminal]
----
sh-4.4# oc cp default/abcd-06224-s52nc-control-plane-2-debug:host/etc/crio/seccomp.json ./seccomp-nostat.json
----

. Remove the stat call from the profile by running the following command.

. Rename the profile to `seccomp-nostat.json` by running the following command.

. Copy the profile to the node where you are creating the pod by running the following command.

. Create a JSON file named `seccomp-example.json` by running the following command:
+
[source,terminal]
----
$ oc create -f seccomp-example.json
----
+
.Example output
[source,json]
----
echo '{
 "kind": "Pod",
 "apiVersion": "v1",
 "metadata": {
 "name": "seccompon",
 "annotations": {
 "seccomp.security.alpha.kubernetes.io/pod": "localhost/seccomp-nostat.json"
 }
 },
 "spec": {
 "containers": [
 {
 "name": "seccomptest",
 "image": "docker.io/library/fedora:latest",
 "command": ["/bin/ls", "/"],
 "resources": {},
 "terminationMessagePath": "/dev/termination-log",
 "imagePullPolicy": "IfNotPresent",
 "securityContext": {
 "capabilities": {},
 "privileged": false
 }
 }
 ],
 "nodeName": "weinliu43stage-bc4xw-control-plane-2"
 }
 }
----
