// Module included in the following assemblies:
//
// * operating/verify-image-signatures.adoc

:_mod-docs-content-type: CONCEPT
[id="verify-image-signatures-overview_{context}"]
= Image signature verification overview

[role="_abstract"]
You can create policies to block unsigned images and images that do not have a verified signature. You can also enforce the policy by using the {product-title-short} admission controller to stop unauthorized deployment creation.

[NOTE]
====
* {product-title-short} supports Cosign signature verification by using Cosign public keys, Cosign certificates, or both.
* For Cosign signature verification, {product-title-short} supports communication with the transparency log.
* For Cosign signature verification, you can use keyless verification with {product-title-short}. If you want to host the key infrastructure yourself, you can do this by using {rh-rhtas-first}.
* {product-title-short} supports discovering Cosign signatures by using the OCI 1.1 referrers API and the tag-based discovery method.
* You must configure signature integration with at least 1 Cosign verification method for signature verification.
* For all deployed and watched images:
** {product-title-short} fetches and verifies the signatures every 4 hours.
** {product-title-short} verifies the signatures whenever you change or update your signature integration verification data.
====

[role="_additional-resources"]
.Additional resources
* link:https://docs.sigstore.dev/cosign/signing/overview/[Overview (Sigstore documentation)]
* link:https://docs.sigstore.dev/logging/overview/[Rekor (Sigstore documentation)]
* link:https://github.com/opencontainers/distribution-spec/blob/v1.1.1/spec.md#listing-referrers[OCI 1.1 referrers API]
* link:https://github.com/sigstore/cosign/blob/v3.1.3/specs/SIGNATURE_SPEC.md[Tag-based discovery method]


//Securing container images by using signature integration
