// Module included in the following assemblies:
//
// * manage-compliance/manage-compliance.adoc

:_mod-docs-content-type: PROCEDURE
[id="viewing-the-compliance-status-for-namespaces_{context}"]
= Viewing the compliance status for namespaces

By viewing the compliance status for namespaces, you can monitor and ensure that each namespace adheres to the required compliance standards. 

You can view the compliance status for all namespaces or a single namespace in the compliance dashboard.

.Procedure

* To view the compliance status for all namespaces in your environment:
** In the {product-title-short} portal, go to the *Compliance -> Dashboard -> namespaces* tab.

* To view the compliance status for a specific namespace in your environment, perform the following steps:
** In the {product-title-short} portal, go to the *Compliance -> Dashboard -> namespaces* tab.
** In the *Namespaces* table, click on a namespace. A side panel opens on the right.
** In the side panel, click on the name of the namespace to view its compliance status.