// Module included in the following assemblies:
//
// * virt/vm_networking/virt-connecting-vm-to-physical-network-ovs-bridge.adoc

:_mod-docs-content-type: CONCEPT
[id="virt-about-localnet-topology_{context}"]
= About localnet topology

[role="_abstract"]
You can connect a virtual machine (VM) to the physical network infrastructure by configuring an OVN-Kubernetes secondary user-defined network (UDN) with the localnet topology.

A localnet topology connects the secondary network to the physical network. This enables both east-west cluster traffic and access to services running outside the cluster, but it requires additional configuration of the underlying Open vSwitch (OVS) bridge on cluster nodes.

To configure a localnet UDN, use the following steps:

. Install the Kubernetes NMState Operator, which provides a state-driven network configuration across cluster nodes.

. Use the `NodeNetworkConfigurationPolicy` custom resource (CR) to configure OVS bridges and add the appropriate bridge mappings on the nodes.

. Use the `ClusterUserDefinedNetwork` CR from the UDN API to attach your workload to the physical network through the OVS bridges that you configured in the previous step.
