// Module included in the following assemblies:
//
// * virt/install/installing-virt.adoc

:_mod-docs-content-type: PROCEDURE
[id="virt-deploying-operator-cli_{context}"]
= Deploying the {VirtProductName} Operator by using the CLI

You can deploy the {VirtProductName} Operator by using the `oc` CLI.

.Prerequisites

* Subscribe to the {VirtProductName} catalog in the `{CNVNamespace}` namespace.
* Log in as a user with `cluster-admin` privileges.
// required for ROSA/OSD
ifdef::openshift-rosa,openshift-dedicated[]
* Create a machine pool based on a bare metal compute node instance type.
endif::openshift-rosa,openshift-dedicated[]

.Procedure

. Create a YAML file that contains the following manifest:
+
[source,yaml,subs="attributes+"]
----
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: {CNVNamespace}
spec:
----

. Deploy the {VirtProductName} Operator by running the following command:
+
[source,terminal]
----
$ oc apply -f <file_name>.yaml
----

.Verification

* Ensure that {VirtProductName} deployed successfully by watching the `PHASE` of the cluster service version (CSV) in the `{CNVNamespace}` namespace. Run the following command:
+
[source,terminal,subs="attributes+"]
----
$ watch oc get csv -n {CNVNamespace}
----
+
The following output displays if deployment was successful:
+
.Example output
[source,terminal,subs="attributes+"]
----
NAME                                      DISPLAY                    VERSION   REPLACES   PHASE
kubevirt-hyperconverged-operator.v{HCOVersion}   {VirtProductName}   {HCOVersion}                Succeeded
----

