// Module included in the following assemblies:
//
// *

:_mod-docs-content-type: PROCEDURE
[id="virt-configuring-whereabouts-network-plugin_{context}"]
= Configuring the Whereabouts network plug-in

Cross-cluster live migration requires that the clusters be connected in the same network. Specifically, virt-handler pods must be able to communicate.

Using the Dynamic Host Configuration Protocol Container Network Interface (DHCP CNI) plug-in can be advantageous in a cross-cluster live migration setting in that it removes the need to manually assign IP addresses and other network configuration settings.

If the Dynamic Host Configuration Protocol Container Network Interface (DHCP CNI) plug-in is not available on the two clusters, configure the Whereabouts network plug-in to segment the ranges for each cluster.

.Procedure

. Create a network attachment definition in the {VirtProductName} namespace for the first cluster, as shown in the following example:
+
[source,yaml]
----
$ cat <<EOF | oc apply -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lm-network
  namespace: openshift-cnv
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "lm-network",
    "type": "macvlan",
    "master": "eno2",
    "mode": "bridge",
    "ipam": {
      "type": "whereabouts",
      "range": "192.168.111.0/24",
      "exclude": [
        "192.168.111.0/25"
      ]
    }
  }'
EOF
----
+
where:
+
* The `range` and `exclude` parameters specify that the cluster secures addresses in the range of `192.168.111.128` to `192.168.111.255`.

. Create a network attachment definition in the {VirtProductName} namespace for the second cluster, as shown in the following example:
+
[source,yaml]
----
$ cat <<EOF | oc apply -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lm-network
  namespace: openshift-cnv
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "lm-network",
    "type": "macvlan",
    "master": "eno2",
    "mode": "bridge",
    "ipam": {
      "type": "whereabouts",
      "range": "192.168.111.0/24",
      "exclude": [
        "192.168.111.128/25"
      ]
    }
  }'
EOF
----
+
where:
+
* The `range` and `exclude` parameters specify that the cluster secures addresses in the range of `192.168.111.0` to `192.168.111.127`.
