// Module included in the following assemblies:
//
// * virt/vm_networking/virt-connecting-vm-to-primary-udn.adoc

:_mod-docs-content-type: PROCEDURE
[id="virt-creating-a-primary-cluster-udn_{context}"]
= Creating a primary cluster-scoped user-defined network by using the CLI

[role="_abstract"]
You can connect multiple namespaces to the same primary user-defined network (UDN) to achieve native tenant isolation by using the CLI.

.Prerequisites

* You have access to the cluster as a user with `cluster-admin` privileges.
* You have installed the {oc-first}.

.Procedure

. Create a `ClusterUserDefinedNetwork` object to specify the custom network configuration.
+
Example `ClusterUserDefinedNetwork` manifest:
+
[source,yaml]
----
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: cudn-l2-net
spec:
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values: ["red-namespace", "blue-namespace"]
  network:
    topology: Layer2
    layer2:
      role: Primary
      ipam:
        lifecycle: Persistent
      subnets:
        - 203.203.0.0/16
----
** `metadata.name` specifies the name of the `ClusterUserDefinedNetwork` custom resource.
** `spec.namespaceSelector` specifies the set of namespaces that the cluster UDN applies to. The namespace selector must not point to `default`, an `openshift-*` namespace, or any global namespaces that are defined by the Cluster Network Operator (CNO).
** `spec.namespaceSelector.matchExpressions` specifies the type of selector. In this example, the `matchExpressions` selector selects objects that have the label `kubernetes.io/metadata.name` with the value `red-namespace` or `blue-namespace`.
** `spec.namespaceSelector.matchExpressions.operator` specifies the type of operator. Possible values are `In`, `NotIn`, and `Exists`.
** `spec.network.topology` specifies the topological configuration of the network. The required value is `Layer2`. A `Layer2` topology creates a logical switch that is shared by all nodes.
** `spec.network.layer2.role` specifies whether the UDN is primary or secondary. The `Primary` role means that the UDN acts as the primary network for the VM and all default traffic passes through this network.

. Apply the `ClusterUserDefinedNetwork` manifest by running the following command:
+
[source,terminal]
----
$ oc apply -f --validate=true <filename>.yaml
----
