// Module included in the following assemblies:
//
// * virt/advanced_vm_management/virt-configuring-usb-host-passthrough.adoc

:_mod-docs-content-type: PROCEDURE
[id="virt-configuring-VM-use-usb-device_{context}"]
= Configuring a virtual machine connection to a USB device

You can configure virtual machine (VM) access to a USB device. Doing so allows a guest to connect to actual USB hardware that is attached to an {product-title} node, as if the hardware and VM are physically connected.

.Prerequisites

* A cluster admin must enable the `hostDevices` feature gate on the HyperConverged (HCO) custom resource (CR).

.Procedure

. Locate the USB device by running the following command:
+
[source,terminal]
----
$ oc /dev/serial/by-id/usb-VENDOR_device_name
----

. Open the HCO CR by running the following commmand:
+
[source,terminal]
----
$ oc edit hyperconverged kubevirt-hyperconverged -n openshift-cnv
----

. Edit the CR by adding a USB device, as shown in the following example:
+
.Example configuration
[source, yaml]
----
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-usb
  name: vmi-usb <1>
spec:
  domain:
    devices:
      hostDevices:
      - deviceName: kubevirt.io/peripherals
        name: local-peripherals
# ...
----
<1> The name of the USB device.

