// Module included in the following assemblies:
//
// * virt/support/virt-troubleshooting.adoc

[id="virt-analyzing-datavolume-conditions-and-events_{context}"]
= Analyzing data volume conditions and events

By inspecting the `Conditions` and `Events` sections generated by the `describe`
command, you determine the state of the data volume
in relation to persistent volume claims (PVCs), and whether or
not an operation is actively running or completed. You might also receive messages
that offer specific details about the status of the data volume, and how
it came to be in its current state.

There are many different combinations of conditions. Each must be evaluated in its unique context.

Examples of various combinations follow.

* `Bound` - A successfully bound PVC displays in this example.
+
Note that the `Type` is `Bound`, so the `Status` is `True`.
If the PVC is not bound, the `Status` is `False`.
+
When the PVC is bound, an event is generated stating that the PVC is bound.
In this case, the `Reason` is `Bound` and `Status` is `True`.
The `Message` indicates which PVC owns the data volume.
+
`Message`, in the `Events` section, provides further details including how
long the PVC has been bound (`Age`) and by what resource (`From`),
in this case `datavolume-controller`:
+
.Example output
[source,terminal]
----
Status:
  Conditions:
    Last Heart Beat Time:  2020-07-15T03:58:24Z
    Last Transition Time:  2020-07-15T03:58:24Z
    Message:               PVC win10-rootdisk Bound
    Reason:                Bound
    Status:                True
    Type:                  Bound
...
  Events:
    Type     Reason     Age    From                   Message
    ----     ------     ----   ----                   -------
    Normal   Bound      24s    datavolume-controller  PVC example-dv Bound
----

* `Running` - In this case, note that `Type` is `Running` and `Status` is `False`,
indicating that an event has occurred that caused an attempted
operation to fail, changing the Status from `True` to `False`.
+
However, note that `Reason` is `Completed` and the `Message` field indicates
`Import Complete`.
+
In the `Events` section, the `Reason` and `Message` contain additional
troubleshooting information about the failed operation. In this example,
the `Message` displays an inability to connect due to a `404`, listed in the
`Events` section's first `Warning`.
+
From this information, you conclude that an import operation was running,
creating contention for other operations that are
attempting to access the data volume:
+
.Example output
[source,terminal]
----
Status:
  Conditions:
    Last Heart Beat Time:  2020-07-15T04:31:39Z
    Last Transition Time:  2020-07-15T04:31:39Z
    Message:               Import Complete
    Reason:                Completed
    Status:                False
    Type:                  Running
...
  Events:
    Type     Reason       Age                From                   Message
    ----     ------       ----               ----                   -------
    Warning  Error        12s (x2 over 14s)  datavolume-controller  Unable to connect
    to http data source: expected status code 200, got 404. Status: 404 Not Found
----

* `Ready` – If `Type` is `Ready` and `Status` is `True`, then the data volume is ready
to be used, as in the following example. If the data volume is not ready to be
used, the `Status` is `False`:
+
.Example output
[source,terminal]
----
Status:
  Conditions:
    Last Heart Beat Time: 2020-07-15T04:31:39Z
    Last Transition Time:  2020-07-15T04:31:39Z
    Status:                True
    Type:                  Ready
----
