// Module included in the following assemblies:
//
// * virt/about-virt.adoc
// * virt/virt_release_notes/virt-2-4-release-notes.adoc

[id="virt-what-you-can-do-with-virt_{context}"]
= What you can do with {VirtProductName}

{VirtProductName} is a feature of {product-title} that you can use to run and manage virtual machine workloads alongside container workloads.

{VirtProductName} adds new objects into your {product-title} cluster via Kubernetes
custom resources to enable virtualization tasks. These tasks include:

* Creating and managing Linux and Windows virtual machines
* Connecting to virtual machines through a variety of consoles and CLI tools
* Importing and cloning existing virtual machines
* Managing network interface controllers and storage disks attached to virtual machines
* Live migrating virtual machines between nodes

An enhanced web console provides a graphical portal to manage these virtualized
resources alongside the {product-title} cluster containers and infrastructure.

// A line about support for OVN and OpenShiftSDN network providers has been moved to the `about-virt` assembly due to xrefs.
// If you are re-using this module, you might also want to include that line in your assembly.
