// Module included in the following assemblies:
//
// * virt/support/virt-support-overview.adoc

:_mod-docs-content-type: PROCEDURE
[id="opening-support-tickets_{context}"]
= Opening support tickets

If you have encountered an issue that requires immediate assistance from Red Hat Support, you can submit a support case.

If you want to report a bug, you can create a Jira issue directly.

[id="submitting-support-case_{context}"]
== Submitting a support case

To request support from Red Hat Support, follow xref:../../support/getting-support.adoc#support-submitting-a-case_getting-support[the instructions for submitting a support case].

It is helpful to collect debugging data to provide the data with your request for support.

[id="collecting-data-for-red-hat-support_{context}"]
=== Collecting data for Red Hat Support

You can gather debugging information by performing the following steps:

xref:../../virt/support/virt-collecting-virt-data.adoc#virt-collecting-data-about-your-environment_virt-collecting-virt-data[Collecting data about your environment]::
Configure Prometheus and Alertmanager and collect `must-gather` data for {product-title} and {VirtProductName}.

xref:../../virt/support/virt-collecting-virt-data.adoc#virt-collecting-data-about-vms_virt-collecting-virt-data[Collecting data about VMs]::
Collect `must-gather` data and memory dumps from VMs.

// must-gather not supported for ROSA/OSD, per Dustin Row
ifndef::openshift-rosa,openshift-dedicated[]
xref:../../virt/support/virt-collecting-virt-data.adoc#virt-using-virt-must-gather_virt-collecting-virt-data[`must-gather` tool for {VirtProductName}]::
Configure and use the `must-gather` tool.
endif::openshift-rosa,openshift-dedicated[]

[id="virt-creating-jira-issue_{context}"]
== Creating a Jira issue

If you want to report a bug, you can create a Jira issue directly by filling out the form on the link:https://issues.redhat.com/secure/CreateIssueDetails!init.jspa?pid=12323181&issuetype=1&priority=10200[*Create Issue*] page.





