// Module included in the following assemblies:
//
// * virt/install/preparing-cluster-for-virt.adoc
ifndef::openshift-rosa,openshift-dedicated[]
:_mod-docs-content-type: CONCEPT
[id="virt-aws-bm_{context}"]
= {VirtProductName} on AWS bare metal

You can run {VirtProductName} on an Amazon Web Services (AWS) bare-metal {product-title} cluster.

[NOTE]
====
{VirtProductName} is also supported on {product-rosa} (ROSA) Classic clusters, which have the same configuration requirements as AWS bare-metal clusters.
====
endif::openshift-rosa,openshift-dedicated[]

ifdef::openshift-rosa,openshift-dedicated[]
:_mod-docs-content-type: CONCEPT
[id="virt-aws-bm_{context}"]
= {VirtProductName} on {product-title}

ifdef::openshift-rosa[]
You can run {VirtProductName} on a {product-rosa} (ROSA) Classic cluster.
endif::openshift-rosa[]
ifdef::openshift-dedicated[]
You can run {VirtProductName} on a {product-dedicated} cluster.
endif::openshift-dedicated[]
endif::openshift-rosa,openshift-dedicated[]

Before you set up your cluster, review the following summary of supported features and limitations:

Installing::
--
*  You can install the cluster by using installer-provisioned infrastructure, ensuring that you specify bare-metal instance types for the worker nodes. For example, you can use the `c5n.metal` type value for a machine based on x86_64 architecture.
ifndef::openshift-rosa[]
You specify bare-metal instance types by editing the `install-config.yaml` file.
endif::openshift-rosa[]
+
For more information, see the {product-title} documentation about installing on AWS.
--

Accessing virtual machines (VMs)::
--
* There is no change to how you access VMs by using the `virtctl` CLI tool or the {product-title} web console.
* You can expose VMs by using a `NodePort` or `LoadBalancer` service.
** The load balancer approach is preferable because {product-title} automatically creates the load balancer in AWS and manages its lifecycle. A security group is also created for the load balancer, and you can use annotations to attach existing security groups. When you remove the service, {product-title} removes the load balancer and its associated resources.
--

Networking::
// Hiding the following in ROSA/OSD because SR-IOV is not supported.
ifndef::openshift-rosa,openshift-dedicated[]
--
* You cannot use Single Root I/O Virtualization (SR-IOV) or bridge Container Network Interface (CNI) networks, including virtual LAN (VLAN). If your application requires a flat layer 2 network or control over the IP pool, consider using OVN-Kubernetes secondary overlay networks.
--
endif::openshift-rosa,openshift-dedicated[]
ifdef::openshift-rosa,openshift-dedicated[]
--
* If your application requires a flat layer 2 network or control over the IP pool, consider using OVN-Kubernetes secondary overlay networks.
--
endif::openshift-rosa,openshift-dedicated[]

Storage::
--
* You can use any storage solution that is certified by the storage vendor to work with the underlying platform.
+
[IMPORTANT]
====
AWS bare-metal and ROSA clusters might have different supported storage solutions. Ensure that you confirm support with your storage vendor.
====
* Using Amazon Elastic File System (EFS) or Amazon Elastic Block Store (EBS) with {VirtProductName} might cause performance and functionality limitations as shown in the following table:
+
.EFS and EBS performance and functionality limitations
[cols="1,1,1,1,1,1",options="header"]
|===
|Feature
3+^|EBS volume
|EFS volume
|Shared storage solutions

|
^s|gp2
^s|gp3
^s|io2
|
|

|VM live migration
^|Not available
^|Not available
^|Available
|Available
|Available

|Fast VM creation by using cloning
3+^|Available
|Not available
|Available

|VM backup and restore by using snapshots
3+^|Available
|Not available
|Available

|===
+
Consider using CSI storage, which supports ReadWriteMany (RWX), cloning, and snapshots to enable live migration, fast VM creation, and VM snapshots capabilities.
--

ifndef::openshift-dedicated,openshift-rosa[]
Hosted control planes (HCPs)::
--
* HCPs for {VirtProductName} are not currently supported on AWS infrastructure.
--
endif::openshift-dedicated,openshift-rosa[]