// Module included in the following assemblies:
//
// * virt/install/virt-install-ibm-cloud-bm-nodes.adoc

:_mod-docs-content-type: PROCEDURE 
[id="virt-install-ibm-cloud-config-new-cluster_{context}"]
= Configuring {ibm-cloud-title} for the new cluster

[role="_abstract"]
Configure and provision the {ibm-cloud-title} environment to establish the operational framework and nodes for your {VirtProductName} cluster.

.Procedure
. Create a new virtual server instance in {ibm-cloud-title} at link:https://cloud.ibm.com/gen1/infrastructure/provision/vs[Virtual Server for Classic] to be the Bastion server. This instance is used to run the installation and provide environment services. 

. Change the default properties of the new virtual server instance to the following values. Use the provided defaults for all other values.
+
* *Type of virtual server:* Public
* *Operating system:* CentOS
* Your public SSH RSA key

. Note the private VLAN and subnet the virtual server instance is assigned to at link:https://cloud.ibm.com/classic/network/vlans[VLANs].

. Provision 6 bare-metal nodes in {ibm-cloud-title} at link:https://cloud.ibm.com/gen1/infrastructure/provision/bm[Bare metal server provision]. Use the following values when provisioning the nodes:

* *Domain*: A subdomain you can add records to.
* *Quantity*: 6
* *Location*: The same location as the virtual server instance.
* *Storage disks*: RAID 1
* *Network Interface*: Private
* *Private VLAN*: The same as noted for the virtual server instance.

. Confirm all nodes are provisioned and ready at link:https://cloud.ibm.com/gen1/infrastructure/devices[Device list].

. Rename the control plane nodes to `control0-<domain-name>`, `control1-<domain-name>`, and `control2-<domain-name>`. Replace `<domain-name>` with the domain used when provisioning the nodes.

. Rename the compute nodes to `compute0-<domain-name>`, `compute1-<domain-name>`, and `compute2-<domain-name>`. Replace `<domain-name>` with the domain used when provisioning the nodes.

. Configure the Bastion virtual server instance as a default network gateway.

. Configure DHCP by editing `/etc/dhcp/dhcpd.conf` on the Bastion virtual server instance. For example:
+
[source,text]
----
# Set DNS name and DNS server's IP address or hostname
option domain-name  <dns_domain_name>;
option domain-name-servers  <dns_ip_addresses>;

# Declare DHCP Server
authoritative;

# The default DHCP lease time
default-lease-time <default_lease_value>;

# Set the maximum lease time
max-lease-time <max_lease_value>;

# Set Network address, subnet mask and gateway

subnet <subnet_ip_address> netmask <subnet_mask> {
  # Range of IP addresses to allocate
  range dynamic-bootp <dynamic_boot_lower_address> <dynamic_boot_upper_address>;
  # Provide broadcast address
  option broadcast-address <broadcast_ip_address>;
  # Set default gateway
  option routers <default_gateway_ip_address>;
----
+
where:

<dns_domain_name>:: The default domain name for DNS clients.
<dns_ip_addresses>:: A comma-seperated list of DNS server IP addresses.
<default_lease_value>:: The default number of seconds a client keeps an assigned address.
<max_lease_value>:: The maximum number of seconds a client keeps an assigned address.
<subnet_ip_address>:: The start of the subnet IP address range.
<subnet_mask>:: The subnet mask of the subnet IP address range.
<broad_ip_address>:: The broadcast IP address to use when to use sending a message to every device on the subnet.
<default_gateway_ip_address>:: The default gateway of the subnet.

. Restart DHCP on the Bastion virtual server instance:
+
[source,terminal]
----
$ systemctl restart dhcpd
----

. Enable IP forwarding on the Bastion virtual server instance:
+
[source,terminal]
----
$ sysctl -w net.ipv4.ip_forward=1
----

. Verify IP forwarding is enabled on the Bastion virtual server instance:
+
[source,terminal]
----
$ sysctl -p /etc/sysctl.conf
----

. Restart the network service on the Bastion virtual server instance:
+
[source,terminal]
----
$ service network restart
----

. Verify if `firewalld` is enabled on the Bastion virtual server instance:
+
[source,terminal]
----
$ firewall-cmd --state
----

. If the `firewalld` service is not enabled on the Bastion virtual server instance, enable the service:
+
[source,terminal]
----
$ systemctl enable firewalld
----

. Start the `firewalld` service:
+
[source,terminal]
----
$ systemctl start firewalld
----


. Add network address translation (NAT) rules to the `firewalld` service:
+
[source,terminal]
----
$ firewall-cmd --add-masquerade --permanent
----

. Restart the `firewalld` service:
+
[source,terminal]
----
$ firewall-cmd --reload
----