// Module included in the following assemblies:
//
// * list assemblies

:_mod-docs-content-type: PROCEDURE
[id="virt-create-aws-li-windows-vm-web-console_{context}"]
= Creating an AWS EC2 Windows LI compliant VM by using the web console

[role="_abstract"]
You can create license-compliant Windows virtual machines (VMs) by using dedicated preferences. In the {product-title} web console, you can create a compliant VM by selecting from a list of available bootable volumes.

// .Prerequisites
// TODO: Any prereqs we need to call out here?

.Procedure

. In the {product-title} web console, go to *Virtualization* -> *Catalog*. The *InstanceTypes* tab opens by default.

. Click *Add volume* to create a Windows boot source. You can create a Windows boot source by uploading a new volume or by using an existing persistent volume claim (PVC), a volume snapshot, or a `containerDisk` volume.

. In the *Volume metadata* section, select a preference with a name that begins with `windows` and ends with `dedicated`. For example, `windows.11.virtio.dedicated`. Click *Save*.

. Select a bootable volume from the list. If the list is truncated, click *Show all* to display the entire list. The bootable volume table contains the previously uploaded boot source.

. Optional: You can mount a Windows driver disk by completing the following steps.
.. Click *Customize VirtualMachine*.
.. On the *VirtualMachine details* page, click *Storage*.
.. Select the *Mount Windows drivers* disk checkbox.

. Click *Create VirtualMachine*.
