// Module included in the following assembly:
//
// * virt/virtual_machines/virt-automatic-bootsource-updates.adoc
//

:_content-type: PROCEDURE
[id="virt-configuring-storage-class-bootsource-update_{context}"]
= Configuring a storage class for custom boot source updates

Specify a new default storage class in the `HyperConverged` custom resource (CR).

[IMPORTANT]
====
Boot sources are created from storage using the default storage class. If your cluster does not have a default storage class, you must define one before configuring automatic updates for custom boot sources.
====

.Procedure

. Open the `HyperConverged` CR in your default editor by running the following command:
+
[source,terminal,subs="attributes+"]
----
$ oc edit hyperconverged kubevirt-hyperconverged -n {CNVNamespace}
----

. Define a new storage class by entering a value in the `storageClassName` field:
+
[source,yaml]
----
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
spec:
  dataImportCronTemplates:
  - metadata:
      name: rhel8-image-cron
    spec:
      template:
        spec:
          storageClassName: <new_storage_class> <1>
#...
----
<1> Define the storage class.

. Remove the `storageclass.kubernetes.io/is-default-class` annotation from the current default storage class.
.. Retrieve the name of the current default storage class by running the following command:
+
[source,terminal]
----
$ oc get storageclass
----
+
.Example output
[source,text]
----
NAME PROVISIONER RECLAIMPOLICY VOLUMEBINDINGMODE ALLOWVOLUMEEXPANSION AGE
csi-manila-ceph manila.csi.openstack.org Delete Immediate false 11d
hostpath-csi-basic (default) kubevirt.io.hostpath-provisioner Delete WaitForFirstConsumer false 11d <1>
...
----
+
<1> In this example, the current default storage class is named `hostpath-csi-basic`.

.. Remove the annotation from the current default storage class by running the following command:
+
[source,terminal]
----
$ oc patch storageclass <current_default_storage_class> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}' <1>
----
<1> Replace `<current_default_storage_class>` with the `storageClassName` value of the default storage class.

. Set the new storage class as the default by running the following command:
+
[source,terminal]
----
$ oc patch storageclass <new_storage_class> -p '{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}' <1>
----
<1> Replace `<new_storage_class>` with the `storageClassName` value that you added to the `HyperConverged` CR.