// Module included in the following assemblies:
//
// * virt/virtual_machines/virtual_disks/virt-cloning-a-datavolume-using-smart-cloning.adoc

:_content-type: PROCEDURE
[id="virt-cloning-a-datavolume_{context}"]
= Smart-cloning a PVC by using the command line

You can smart-clone a persistent volume claim (PVC) by using the command line to create a `DataVolume` object.

.Prerequisites

* Your storage provider must support snapshots.
* The source and target PVCs must have the same storage provider and volume mode.
* The value of the `driver` key of the `VolumeSnapshotClass` object must match the value of the `provisioner` key of the `StorageClass` object as shown in the following example:
+
.Example `VolumeSnapshotClass` object
[source,yaml]
----
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
driver: openshift-storage.rbd.csi.ceph.com
# ...
----
+
.Example `StorageClass` object
[source,yaml]
----
kind: StorageClass
apiVersion: storage.k8s.io/v1
# ...
provisioner: openshift-storage.rbd.csi.ceph.com
----

.Procedure

. Create a YAML file for a `DataVolume` object as shown in the following example:
+
[source,yaml]
----
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: <datavolume> <1>
spec:
  source:
    pvc:
      namespace: "<source_namespace>" <2>
      name: "<my_vm_disk>" <3>
  storage:
    storageClassName: <storage_class> <4>
----
<1> Specify the name of the new data volume.
<2> Specify the namespace of the source PVC.
<3> Specify the name of the source PVC.
<4> Optional: If the storage class is not specified, the default storage class is used.

. Create the data volume by running the following command:
+
[source,terminal]
----
$ oc create -f <datavolume>.yaml
----
+
[NOTE]
====
Data volumes prevent a virtual machine from starting before the PVC is prepared. You can create a virtual machine that references the new data volume while the PVC is being cloned.
====
