// Module included in the following assemblies:
//
// * virt/logging_events_monitoring/virt-running-cluster-checkups.adoc

:_mod-docs-content-type: CONCEPT
[id="virt-about-cluster-checkup-framework_{context}"]
= About the {product-title} cluster checkup framework

A _checkup_ is an automated test workload that allows you to verify if a specific cluster functionality works as expected. The cluster checkup framework uses native Kubernetes resources to configure and execute the checkup.

By using predefined checkups, cluster administrators can improve cluster maintainability, troubleshoot unexpected behavior, minimize errors, and save time. They can also review the results of the checkup and share them with experts for further analysis. Vendors can write and publish checkups for features or services that they provide and verify that their customer environments are configured correctly.

Running a predefined checkup in the cluster involves setting up the namespace and service account for the framework, creating the `ClusterRole` and `ClusterRoleBinding` objects for the service account, enabling permissions for the checkup, and creating the input config map and the checkup job. You can run a checkup multiple times.

[IMPORTANT]
====
You must always:

* Verify that the checkup image is from a trustworthy source before applying it.
* Review the checkup permissions before creating the `ClusterRole` objects.
* Verify the names of the `ClusterRole` objects in the config map. This is because the framework automatically binds these permissions to the checkup instance.
====
