:_newdoc-version: 2.18.5
:_template-generated: 2025-09-11
:_mod-docs-content-type: PROCEDURE

[id="virt-inserting-a-cd-rom-in-a-vm-by-using-the-web-console_{context}"]
= Inserting a CD-ROM in a VM by using the web console

[role="_abstract"]
To make data on a CD-ROM storage device available to a virtual machine (VM) in {product-title}, create a virtual CD-ROM drive in the VM and insert the CD-ROM into the drive as an ISO image.

Setting up a virtual CD-ROM drive requires rebooting the VM, but you can insert and eject ISO images in the drive while the VM is running.

[IMPORTANT]
====
CD-ROMs are currently provided as a Technology Preview in {product-title}. For more information, see link:https://access.redhat.com/support/offerings/techpreview/?extIdCarryOver=true&sc_cid=RHCTG0180000371695[Technology Preview features - Scope of Support] in Red Hat Knowledgebase.
====

.Prerequisites

* The `DeclarativeHotplugVolumes` feature gate must be enabled. To ensure this, the `HyperConverged` CR must contain the `declarativeHotplugVolumes: true` line in the `spec.featureGates` configuration section:

+
[source,yaml]
----
spec:
    featureGates:
        declarativeHotplugVolumes: true
----
+
[Warning]
====
The `DeclarativeHotplugVolumes` feature gate is incompatible with the `HotplugVolumes` feature gate, which is required for using ephemeral volumes. To use `DeclarativeHotplugVolumes`, you must also disable `HotplugVolumes` in the `HyperConverged` CR.
====

.Procedure

. In the {product-title} web console, go to `Virtualization` → `VirtualMachines`.

. Click the name of the VM in which you want to insert the CD-ROM.

. On the VM details page, click the `Configuration` tab.

. Open the `Storage` pane.

. Click `Add`.
+
A drop-down menu opens.

. Click `CD-ROM`.

. In the `Name` field, add a name for the CD-ROM drive device.

. Optional: To upload a new ISO file and insert it into the CD-ROM drive after it is created, do the following:

.. Ensure that the `Upload a new ISO file to the cluster` line is checked.
.. Click `Upload`, and select the ISO image that you want to upload.

. Click `Add`.
+
The CD-ROM drive is added to the `Storage` list.

. If the VM is running, shut it down.

. To insert a CD-ROM device into the VM, click...[TODO]
+
[NOTE]
====
You can also do this when the VM is running.
====

. To eject the CD-ROM from the VM, click ... [TODO]



// .Next steps


// [role="_additional-resources"]
// .Additional resources
// * TBA?

