// Module included in the following assemblies:
//
// * virt/virtual_machines/virt-automating-windows-sysprep.adoc

<<<<<<< HEAD
:_content-type: PROCEDURE
[id="virt-generalizing-windows-sysprep_{context}"]
= Generalizing a Windows VM using sysprep

Generalizing an image allows that image to remove all system-specific configuration data when the image is deployed on a virtual machine.

Before generalizing the VM, you must ensure the `sysprep` tool cannot detect an answer file after the unattended Windows installation.

.Procedure

. Remove the `sysprep` disk.
.. In the web console, select *Virtualization* -> *Virtual Machines*, and select the relevant VM.
.. Click *Disks*.
.. Click the Options menu {kebab} for the `sysprep` disk, then click *Delete*.
.. Click *Detach* in the *Detach sysprep disk* dialog.
. Rename `C:\Windows\Panther\unattend.xml` to avoid detection by the `sysprep` tool.

. Start the `sysprep` program by running the following command:
=======
[id="virt-generalizing-windows-sysprep_{context}"]
= Generalizing a Windows VM using Sysprep

Generalizing an image will allow that image to remove all system-specific configuration data when deployed on a virtual machine.

Prior to generalizing the VM, you must ensure the `sysprep` tool cannot detect an answer file after the unattended Windows installation.

.Procedure

. Remove the sysprep disk.
.. In the web console, select *Virtualization* -> *Virtual Machines*, and select the relevant VM.
.. Click *Disks*.
.. Click the Options menu {kebab} for the `sysprep` disk, then click *Delete*.
.. Click *Detach* in the pop up box.
. Rename `C:\Windows\Panther\unattend.xml` to avoid detection by the sysprep tool.

. Run the sysprep tool using the command below:
>>>>>>> tmp
+
[source,terminal]
----
%WINDIR%\System32\Sysprep\sysprep.exe /generalize /shutdown /oobe /mode:vm
----
<<<<<<< HEAD
. After the `sysprep` tool completes, the Windows VM shuts down. The disk image of the VM is now available to use as an installation image for Windows VMs.
=======
. Once the sysprep tool is complete, the Windows VM will shutdown. The disk image of the VM is now available to use as an installation image for Windows VMs.
>>>>>>> tmp

You can now specialize the VM.
