// Module included in the following assemblies:
//
// * virt/post_installation_configuration/virt-platform-autopilot.adoc

:_mod-docs-content-type: PROCEDURE
[id="virt-unmanaged-autopilot-resources_{context}"]
= Stop reconciliation of a managed resource

[role="_abstract"]
You can stop the `virt-platform-autopilot` controller entirely from reconciling a resource after it is created, by setting the `platform.kubevirt.io/mode=unmanaged` annotation for that resource.

include::snippets/virt-unmanaged-resource-note.adoc[]

.Prerequisites

* You have installed the {oc-first}.
* You have logged in to the cluster as a user with `cluster-admin` privileges.
* The `virt-platform-autopilot` controller is enabled on the cluster.
* The `platform.kubevirt.io/ignore-fields` and `platform.kubevirt.io/patch` annotations must not be present on the resource.

.Procedure

. Set the `platform.kubevirt.io/mode` annotation for the resource to `unmanaged`.
+
For example, to stop the `virt-platform-autopilot` controller from managing the descheduler configuration, run the following command:
+
[source,terminal]
----
$ oc annotate kubedescheduler cluster \
  platform.kubevirt.io/mode=unmanaged \
  -n openshift-kube-descheduler-operator
----

. Optional: To restore `virt-platform-autopilot` controller management for a resource, remove the `platform.kubevirt.io/mode` annotation.
+
For example, to restore `virt-platform-autopilot` controller management for the descheduler configuration, run the following command:
+
[source,terminal]
----
$ oc annotate kubedescheduler cluster \
  platform.kubevirt.io/mode- \
  -n openshift-kube-descheduler-operator
----
