// Module included in the following assemblies:
//
// * windows_containers/understanding-windows-container-workloads.adoc

[id="windows-workload-requirements_{context}"]
= Windows container workload requirements

The following section details the requirements for Windows Container Workloads. In addition to these requirements, consult the cloud provider-specific sections that may be relevant.

.General requirements

* Installer-Provisioned Infrastructure (IPI) installation method is used. User-Provisioned Infrastructure (UPI) is not supported.
* OVNKubernetes networking is used. OpenShiftSDN is not supported.
* Cloud Providers supported:
** Amazon Web Services (AWS)
** Microsoft Azure
** VMware vSphere
* The following Windows Server operating systems are supported for {product-title} {product-version}:
** Windows Server Long-Term Servicing Channel (LTSC): Windows Server 2019

.VMware vSphere requirements

The following requirements pertain to vSphere only, and do not apply to the other supported cloud providers.

* Specify a custom VXLAN port. The custom port can be any open port excluding the default 4789 port.
