// Module included in the following assemblies:
//
// * security/zer_trust_workload_identity_manager/zero-trust-manager.adoc

:_mod-docs-content-type: PROCEDURE
[id="zero-trust-manager-configure-cert-vault_{context}"]
= Configuring the vault plugin

This procedure outlines the steps required to configure a SPIRE server to obtain its intermediate signing certificates from vault. The plugin supports the following methodes for authenticating to Vault:

* Client Certificate Authentication

* Token Authentication

* AppRole Authentication

* Kubernetes Authentication

.Prerequisites

* A running and accessible HashiCorp Vault server is available.

* A PKI secret engine must be enabled and configured in Vault at the specified `pki_mount_point`.

* A role within the Vault PKI engine must be configured to allow issuing of intermediate CA certificates.

* The Vault token or authentication method used by the plugin must have the necessary permissions.

* The `ca_ttl` configured in your SPIRE server configuration must be less than or equal to the cofigured `max_lease_ttl` of the Vault PKI secret engine role that the plugin uses.



.Procedure