// Module included in the following assemblies:
//
// * security/zero_trust_workload_identity_manageer/zero-trust-manager-oidc-federation.adoc

:_mod-docs-content-type: CONCEPT
[id="zero-trust-manager-config-entra-oidc_{context}"]
= How to configure the Entra ID OIDC

Integrating Entra ID OIDC with SPIRE provides workloads with automatic, short-lived cryptographic identities. The SPIRE-issued identities are sent to Entra ID to securely authenticate the service without any static secrets.

== Configure external certificate for the managed OIDC discovery provider route

The managed route uses the External Route Certificate feature to set the `tls.externalCertificate` field to an externally managed Transfer Layer Security (TLS) secret's name.

.Prerequisites

* {zero-trust-full} 0.2.0 is installed.

* Operands are deployed.

* cert manager Operator is installed. For more information, link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html-single/security_and_compliance/index#cert-manager-operator-install[Installing the cert-manager Operator for Red{nbsp}Hat OpenShift].

* An ACME issuer is installed. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html-single/security_and_compliance/index#cert-manager-operator-issuer-acme[Configuring an ACME issuer]

.Procedure

. Create the Role-Based Access Control (RBAC) resources to give the router permission to read the referenced secret.
+
[source,terminal]
----
$ oc create role secret-reader \
  --verb=get,list,watch \
  --resource=secrets \
  --resource-name=$TLS_SECRET_NAME \
  -n zero-trust-workload-identity-manager
----

. Create a `rolebinding` secret
+
[source,terminal]
----
$ oc create rolebinding secret-reader-binding \
  --role=secret-reader \
  --serviceaccount=openshift-ingress:router \
  -n zero-trust-workload-identity-manager
----

. Configure the `SpireOIDCDIscoveryProvider` Custom Resource (CR) object to reference the Secret generated in the previous step.
+
[source,terminal]
----
$ oc patch SpireOIDCDiscoveryProvider cluster --type=merge -p="
spec:
  externalSecretRef: ${TLS_SECRET_NAME}
"
----

. In the `SpireOIDCDiscoveryProvider` CR, set the `ManagedRouteReady` condition to 'True'.
+
[source,terminal]
----
$ oc wait --for=jsonpath='{.status.conditions[?(@.type=="ManagedRouteReady")].status}'=True SpireOIDCDiscoveryProvider/cluster --timeout=120s
----

.Verification
To verify that the OIDC endpoint can be accessed securely via HTTPS, run the following command:
+
[source,terminal]
----
curl https://$JWT_ISSUER_ENDPOINT/.well-known/openid-configuration

{
  "issuer": "https://$JWT_ISSUER_ENDPOINT",
  "jwks_uri": "https://$JWT_ISSUER_ENDPOINT/keys",
  "authorization_endpoint": "",
  "response_types_supported": [
    "id_token"
  ],
  "subject_types_supported": [],
  "id_token_signing_alg_values_supported": [
    "RS256",
    "ES256",
    "ES384"
  ]
}%
----

== Disabling a managed route

If you want to manually manage the OIDC Discovery Provider, you can disable the `managedRoute` parameter.

.Procedure

. To manually configure the OIDC Discovery Provider, set `managedRoute` to `false`.
+
[source,terminal]
----
$ oc patch SpireOIDCDiscoveryProvider cluster --type=merge -p='
spec:
  managedRoute: "false"
'
----

. Delete the managed route manually to avoid any conflicts, by running the following command:
+
[source,terminal]
----
$ oc delete route spire-oidc-discovery-provider -n zero-trust-workload-identity-manager
'
----
