// Module included in the following assemblies:
//
// * security/zero_trust_workload_identity_manageer/zero-trust-manager-oidc-federation.adoc

:_mod-docs-content-type: PROCEDURE
[id="zero-trust-manager-configure-azure-blob_{context}"]
= Configuring Azure blob storage

[role="_abstract"]
Create a new {azure-first} storage account and container to provide a dedicated location for your content. Configuring this storage ensures that the {zero-trust-full} can successfully store and retrieve blobs for your environment.

.Procedure

. Create a new storage account that is used to store content by running the following command:
+
[source,terminal]
----
$ az storage account create \
  --name ${STORAGE_ACCOUNT} \
  --resource-group ${RESOURCE_GROUP} \
  --location ${LOCATION} \
  --encryption-services blob
----

. Obtain the storage ID for the newly created storage account by running the following command:
+
[source,terminal]
----
$ export STORAGE_ACCOUNT_ID=$(az storage account show -n ${STORAGE_ACCOUNT} -g ${RESOURCE_GROUP} --query id --out tsv)
----

. Create a storage container inside the newly created storage account to provide a location to support the storage of blobs by running the following command:
+
[source,terminal]
----
$ az storage container create \
  --account-name ${STORAGE_ACCOUNT} \
  --name ${STORAGE_CONTAINER} \
  --auth-mode login
----