// Module included in the following assemblies:
//
// * release_notes/ocp-4-14-release-notes.adoc

:_mod-docs-content-type: REFERENCE
[id="zstream-4-14-70-bug-fixes_{context}"]
= RHSA-2026:43253 - {product-title} {product-version}.70 bug fix and security update

Issued: 30 July 2026

[role="_abstract"]
{product-title} release {product-version}.70 is now available. The list of fixed issues that are included in the update is documented in the link:https://access.redhat.com/errata/RHSA-2026:43253[RHSA-2026:43253] advisory. The RPM packages that are included in the update are provided by the link:https://access.redhat.com/errata/RHBA-2026:43251[RHBA-2026:43251] advisory.

Space precluded documenting all of the container images for this release in the advisory.

You can view the container images in this release by running the following command:

[source,terminal]
----
$ oc adm release info 4.14.70 --pullspecs
----

[id="zstream-4-14-70-fixed_issues_{context}"]
== Fixed issues

There are no notable fixed issues in this release.

[id="zstream-4-14-70-updating_{context}"]
== Updating

To update an {product-title} 4.14 cluster to this latest release, see xref:../updating/updating_a_cluster/updating-cluster-cli.adoc#updating-cluster-cli[Updating a cluster using the CLI].
