// Module included in the following assemblies:
//
// * release_notes/ocp-4-19-release-notes.adoc

:_mod-docs-content-type: REFERENCE
[id="ocp-4-19-0-ga_{context}"]
= RHSA-2024:11038 - {product-title} {product-version}.0 image release, bug fix, and security update advisory

[role="_abstract"]
Issued: 17 June 2025

{product-title} release {product-version}.0, which includes security updates, is now available. The list of bug fixes that are included in the update is documented in the link:https://access.redhat.com/errata/RHSA-2024:11038[RHSA-2024:11038] advisory. The RPM packages that are included in the update are provided by the link:https://access.redhat.com/errata/RHEA-2025:2851[RHEA-2025:2851] advisory.

Space precluded documenting all of the container images for this release in the advisory.

You can view the container images in this release by running the following command:

[source,terminal]
----
$ oc adm release info 4.19.0 --pullspecs
----

[id="ocp-4-19-0-updating_{context}"]
== Updating
To update an {product-title} 4.19 cluster to this latest release, see xref:../updating/updating_a_cluster/updating-cluster-cli.adoc#updating-cluster-cli[Updating a cluster using the CLI].
