// Module included in the following assemblies:
//
// *scalability_and_performance/ztp-deploying-disconnected.adoc

:_content-type: PROCEDURE
[id="ztp-upgrading-gitops-ztp_{context}"]
= Upgrading GitOps ZTP

You can upgrade the Gitops zero touch provisioning (ZTP) infrastructure independently from the underlying cluster, {rh-rhacm-first}, and {product-title} version running on the spoke clusters. This procedure guides you through the upgrade process to avoid impact on the spoke clusters. However, any changes to the content or settings of policies, including adding recommended content, results in changes that must be rolled out and reconciled to the spoke clusters.

.Prerequisites

* This procedure assumes that you have a fully operational hub cluster running the earlier version of the GitOps ZTP infrastructure.

.Procedure

At a high level, the strategy for upgrading the GitOps ZTP infrastructure is:

. Label all existing clusters with the `ztp-done` label.
. Stop the ArgoCD applications.
. Install the new tooling.
. Update required content and optional changes in the Git repository.
. Update and restart the application configuration.
