// Module included in the following assemblies:
//
// * edge_computing/ztp-migrate-clusterinstance.adoc

:_mod-docs-content-type: PROCEDURE
[id="ztp-preparing-git-repo-clusterinstance_{context}"]
= Preparing the git repository for migration

To migrate your managed cluster to using `ClusterInstance` CRs, you must restructure your existing git repository to mirror existing configuration data from the `SiteConfig` CR and assoicated resources. 

To migrate from `SiteConfig` CRs to `ClusterInstance` CRs at scale, you can use the `siteconfig-converter` tool. For more information, see "Migrating SiteConfig CRs to ClusterInstance CRs with the siteconfig-converter tool".

.Prerequisites

* You created a Git repository where you manage your custom site configuration data.
* You deleted the ArgoCD application for the target cluster.

.Procedure

. Create a folder in your git repository for the target cluster's new `ClusterInstance` CR and associated resources. This example uses a `migrate-clusters` folder, which uses subfolders for each cluster. Within each cluster subfolder, you can define the `ClusterInstance` CR and other cluster-specific resources such as the target cluster's namespace and bare-metal host secrets:
+
[source,text]
----
install/
├── clusterinstance/
│   ├── example-3node.yaml
│   ├── example-sno.yaml
│   ├── example-standard.yaml
│   ├── kustomization.yaml
│   ├── migrate-clusters
│   │   └── sno/
│   │       ├── sno1.yaml <1>
│   │       ├── kustomization.yaml <2>
│   │       ├── secrets.yaml <3>
│   │       └── ns.yaml <4>
----
<1> `sno1.yaml` is the `ClusterInstance` CR for the target cluster.
<2> `kustomization.yaml` is the file that defines the resources for the target cluster.
<3> `secrets.yaml` is the file that defines the secrets for the target cluster.
<4> `ns.yaml` is the file that defines the namespace for the target cluster.
+
[NOTE]
====
If required, you can define multiple clusters in the same directory.
====

. Modify the example `ClusterInstance` CR for the cluster type that you want to migrate to. For example, copy `example-sno.yaml` to `migrate-clusters/sno/sno1.yaml` and modify the CR to match the configuration details of the existing SiteConfig CR:
+
.Example `sno1.yaml` file
[source,yaml]
----
# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-ai-sno
---
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: "example-ai-sno"
  namespace: "example-ai-sno"
spec:
  baseDomain: "example.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "openshift-4.20"
  sshPublicKey: "ssh-rsa AAAA..."
  clusterName: "example-ai-sno"
  networkType: "OVNKubernetes"
  # installConfigOverrides is a generic way of passing install-config
  # parameters through the siteConfig.  The 'capabilities' field configures
  # the composable openshift feature.  In this 'capabilities' setting, we
  # remove all the optional set of components.
  # Notes:
  # - OperatorLifecycleManager is needed for 4.15 and later
  # - NodeTuning is needed for 4.13 and later, not for 4.12 and earlier
  # - Ingress is needed for 4.16 and later
  installConfigOverrides: |
    {
      "capabilities": {
        "baselineCapabilitySet": "None",
        "additionalEnabledCapabilities": [
          "NodeTuning",
          "OperatorLifecycleManager",
          "Ingress"
        ]
      }
    }
  # Include references to extraManifest ConfigMaps.
  extraManifestsRefs:
    - name: sno-extra-manifest-configmap
  extraLabels:
    ManagedCluster:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples
      du-profile: "latest"
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
      common: true
      # ../policygentemplates/group-du-sno-ranGen.yaml will apply to all clusters with 'group-du-sno: ""'
      group-du-sno: ""
      # ../policygentemplates/example-sno-site.yaml will apply to all clusters with 'sites: "example-sno"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      sites : "example-sno"
  clusterNetwork:
    - cidr: 1001:1::/48
      hostPrefix: 64
  machineNetwork:
    - cidr: 1111:2222:3333:4444::/64
  serviceNetwork:
    - cidr: 1001:2::/112
  additionalNTPSources:
    - 1111:2222:3333:4444::2
  # Initiates the cluster for workload partitioning. Setting specific reserved/isolated CPUSets is done via PolicyTemplate
  # please see Workload Partitioning Feature for a complete guide.
  cpuPartitioningMode: AllNodes
  templateRefs:
    - name: ai-cluster-templates-v1
      namespace: open-cluster-managememt
  nodes:
    - hostName: "example-node1.example.com"
      role: "master"
      bmcAddress: "idrac-virtualmedia+https://[1111:2222:3333:4444::bbbb:1]/redfish/v1/Systems/System.Embedded.1"
      bmcCredentialsName:
        name: "example-node1-bmh-secret"
      bootMACAddress: "AA:BB:CC:DD:EE:11"
      # Use UEFISecureBoot to enable secure boot, UEFI to disable.
      bootMode: "UEFISecureBoot"
      rootDeviceHints:
        deviceName: "/dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0"
      # disk partition at `/var/lib/containers` with ignitionConfigOverride. Some values must be updated. See DiskPartitionContainer.md in argocd folder for more details
      ignitionConfigOverride: |
        {
          "ignition": {
            "version": "3.2.0"
          },
          "storage": {
            "disks": [
              {
                "device": "/dev/disk/by-path/pci-0000:01:00.0-scsi-0:2:0:0",
                "partitions": [
                  {
                    "label": "var-lib-containers",
                    "sizeMiB": 0,
                    "startMiB": 250000
                  }
                ],
                "wipeTable": false
              }
            ],
            "filesystems": [
              {
                "device": "/dev/disk/by-partlabel/var-lib-containers",
                "format": "xfs",
                "mountOptions": [
                  "defaults",
                  "prjquota"
                ],
                "path": "/var/lib/containers",
                "wipeFilesystem": true
              }
            ]
          },
          "systemd": {
            "units": [
              {
                "contents": "# Generated by Butane\n[Unit]\nRequires=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\nAfter=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\n\n[Mount]\nWhere=/var/lib/containers\nWhat=/dev/disk/by-partlabel/var-lib-containers\nType=xfs\nOptions=defaults,prjquota\n\n[Install]\nRequiredBy=local-fs.target",
                "enabled": true,
                "name": "var-lib-containers.mount"
              }
            ]
          }
        }
      nodeNetwork:
        interfaces:
          - name: eno1
            macAddress: "AA:BB:CC:DD:EE:11"
        config:
          interfaces:
            - name: eno1
              type: ethernet
              state: up
              ipv4:
                enabled: false
              ipv6:
                enabled: true
                address:
                # For SNO sites with static IP addresses, the node-specific,
                # API and Ingress IPs should all be the same and configured on
                # the interface
                - ip: 1111:2222:3333:4444::aaaa:1
                  prefix-length: 64
          dns-resolver:
            config:
              search:
              - example.com
              server:
              - 1111:2222:3333:4444::2
          routes:
            config:
            - destination: ::/0
              next-hop-interface: eno1
              next-hop-address: 1111:2222:3333:4444::1
              table-id: 254
      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management
----
+
[IMPORTANT]
====
When you transfer the cluster configuration values from the deprecated `SiteConfig` CR to the `ClusterInstance` CR, you must ensure values are the same for all matching cluster fields, for example MAC addresses, network configuration, root disk, and so on. Otherwise, the SiteConfig controller fails to validate the rendered deployment manifests.

The following fields are required for the migration. You must include them in the `ClusterInstance` CR even if the values are empty:

* `spec.extraManifestsRefs`

// Any more?
====

. Reference the resouces in the `kustomization.yaml` file:
+
.Example `kustomization.yaml` file
[source,yaml]
----
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - secrets.yaml
  - sno1.yaml
----

. Optionally, you can define extra manifests in a extra-manifests folder in the same directory as the `ClusterInstance` CR:

.. Create the extra manifests folder in the same directory as the `ClusterInstance` CR:
+
[source,bash]
----
$ mkdir extra-manifests
----

.. Define the extra manifests in the `extra-manifests` folder. The following example uses a `MachineConfig` CR to change the password for the `core` user:
+
.Example `extra-manifests/core-password.yaml` file
[source,yaml]
----
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: core-password
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - name: core-password.service
          enabled: true
          contents: |
            [Unit]
            Description=Changes core password
            [Service]
            Type=oneshot
            ExecStart=/bin/bash -c "echo <USER>:<PASSWORD> | chpasswd"
            [Install]
            WantedBy=multi-user.target
----

.. Configure the `kustomization.yaml` file to include the extra manifests:
+
.Example `kustomization.yaml` file
[source,yaml]
----
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - secrets.yaml
  - sno1.yaml

configMapGenerator:
  - files:
    - extra-manifests/core-password.yaml
    name: extra-manifests-cm
    namespace: sno1

generatorOptions:
  disableNameSuffixHash: true
----
