// Module included in the following assemblies:
//
// * scalability_and_performance/ztp_far_edge/ztp-deploying-far-edge-sites.adoc

:_mod-docs-content-type: CONCEPT
[id="ztp-ztp-building-blocks_{context}"]
= Overview of deploying managed clusters with {ztp}

[role="_abstract"]
{rh-rhacm-first} uses {ztp-first} to deploy single-node {product-title} clusters, three-node clusters, and standard clusters. You manage site configuration data as {product-title} custom resources (CRs) in a Git repository. {ztp} uses a declarative GitOps approach for a develop once, deploy anywhere model to deploy the managed clusters.

The deployment of the clusters includes:

* Installing the host operating system (RHCOS) on a blank server

* Deploying {product-title}

* Creating cluster policies and site subscriptions

* Making the necessary network configurations to the server operating system

* Deploying profile Operators and performing any needed software-related configuration, such as performance profile, PTP, and SR-IOV

[NOTE]
====
To deploy clusters with virtualized control planes running on {VirtProductName} VMs instead of physical servers, you can use KubeVirt Redfish to expose VMs as Redfish endpoints.
For more information, see "Virtualized control planes".
====
