// Module included in the following assemblies:
//
// *scalability_and_performance/ztp-zero-touch-provisioning.adoc

[id="ztp-prerequisites-for-deploying-the-ztp-pipeline_{context}"]
= Prerequisites for deploying the ZTP pipeline

* Openshift cluster version 4.8 or higher and Red Hat GitOps Operator is installed.
* {rh-rhacm-first} version 2.3 or above is installed.
* For disconnected environments, make sure your source data Git repository and `ztp-site-generator` container image are accessible from the hub cluster.
* If you want additional custom content, such as extra install manifests or custom resources (CR) for policies, add them to the `/usr/src/hook/ztp/source-crs/extra-manifest/` directory. Similarly, you can add additional configuration CRs, as referenced from a `PolicyGenTemplate`, to the `/usr/src/hook/ztp/source-crs/` directory.
** Create a `Containerfile` that adds your additional manifests to the Red Hat provided image, for example:
+
[source,yaml]
----
FROM <registry fqdn>/ztp-site-generator:latest <1>
COPY myInstallManifest.yaml /usr/src/hook/ztp/source-crs/extra-manifest/
COPY mySourceCR.yaml /usr/src/hook/ztp/source-crs/
----
+
<1> <registry fqdn> must point to a registry containing the `ztp-site-generator` container image provided by Red Hat.

** Build a new container image that includes these additional files:
+
[source,terminal]
----
$> podman build Containerfile.example
----
