// CNF-1500 ZTP - preparing to install ACM
// Module included in the following assemblies:
//
// scalability_and_performance/ztp-deploying-disconnected.adoc
[id="ztp-acm-preparing-to-install-disconnected-acm_{context}"]
= Preparing the disconnected environment

Before you can provision distributed units (DU) at scale, you must install {rh-rhacm-first}, which handles the provisioning of the DUs.

{rh-rhacm} is deployed as an Operator on the {product-title} hub cluster. It controls clusters and applications from a single console with built-in security policies. {rh-rhacm} provisions and manage your DU hosts. To install {rh-rhacm} in a disconnected environment, you create a mirror registry that mirrors the Operator Lifecycle Manager (OLM) catalog that contains the required Operator images. OLM manages, installs, and upgrades Operators and their dependencies in the cluster.

You also use a disconnected mirror host to serve the {op-system} ISO and RootFS disk images that provision the DU bare-metal host operating system.

