// Module included in the following assemblies:
// * scalability_and_performance/ztp-image-based-upgrade.adoc

:_mod-docs-content-type: PROCEDURE
[id="ztp-image-based-upgrade-with-talm_{context}"]
= Upgrading the {sno} cluster with {lcao} and GitOps ZTP

You can upgrade your managed {sno} cluster with the image-based upgrade through GitOps ZTP.

[IMPORTANT]
====
During the Developer Preview of this feature, when upgrading a cluster, any custom trusted certificates configured on the cluster will be lost. As a temporary workaround, to preserve these certificates, you must use a seed image from a seed cluster that trusts the certificates.
====

.Prerequisites

* Install {rh-rhacm} 2.10 or later version.
* Install {cgu-operator} 4.16 or later version.
* Update GitOps ZTP to the latest version.
* Provision one or more managed clusters with GitOps ZTP.
* Log in as a user with `cluster-admin` privileges.
* Generate a seed image from a compatible seed cluster.
* Create an S3-compatible storage solution and a ready-to-use bucket with proper credentials configured. For more information, see _Additional resources_.
* Create a backup and restore resources.
* Create a separate partition on the target cluster for the container images that is shared between stateroots. For more information about, see _Additional resources_.
* Deploy a version of {lcao} that is compatible with the version used with the seed image.

[id="ztp-image-based-upgrade-prep-gitops_{context}"]
== Preparing the {sno} cluster for the image-based upgrade with GitOps ZTP

When you deploy the {lcao} on a cluster, an `ImageBasedUpgrade` CR is automatically created. You update this CR to specify the image repository of the seed image and to move through the different stages.

.Procedure

. Create policies for the `ConfigMap` objects that are used during the upgrade. For more information about how to create the `ConfigMap` objects, see _Additional resources_.

.. Create a policy for the OADP `ConfigMap`, named `oadp-cm-common-policies`.

.. (Optional) Create a policy for the `ConfigMap` of your user-specific extra manifests that are not part of the seed image. The {lcao} does not automatically extract these extra manifests from the seed cluster, so you can add a `ConfigMap` resource of your user-specific extra manifests in the `spec.extraManifests` field in the `ImageBasedUpgrade` CR.

. Create a `PolicyGenTemplate` CR that contains policies for the `Prep` and `Upgrade` stages.
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: group-ibu
  namespace: "ztp-group"
spec:
  bindingRules:
    group-du-sno: ""
  mcp: "master"
  evaluationInterval: <1>
    compliant: 10s
    noncompliant: 10s
  sourceFiles:
    - fileName: ibu/ImageBasedUpgrade.yaml
      policyName: "prep-policy"
      spec:
        stage: Prep
        seedImageRef: <2>
          version: "4.15.0"
          image: "quay.io/user/lca-seed:4.15.0"
          pullSecretRef:
            name: "<seed_pull_secret>"
        oadpContent: <3>
        - name: "oadp-cm-example"
          namespace: "openshift-adp"
      status:
        conditions:
          - reason: Completed
            status: "True"
            type: PrepCompleted
    - fileName: ibu/ImageBasedUpgrade.yaml
      policyName: "upgrade-policy"
      spec:
        stage: Upgrade
      status:
        conditions:
          - reason: Completed
            status: "True"
            type: UpgradeCompleted
----
<1> The policy evaluation interval for compliant and non-compliant policies. Set them to `10s` to ensure that the policies status accurately reflects the current upgrade status.
<2> Define the seed image, {product-title} version, and pull secret for the upgrade in the `Prep` stage.
<3> Define the OADP `ConfigMap` resources required for backup and restore in the `Prep` stage.

. Create a `PolicyGenTemplate` CR for the default set of extra manifests:
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: sno-ibu
spec:
  bindingRules:
    sites: "example-sno"
    du-profile: "4.15.0"
  mcp: "master"
  sourceFiles:
    - fileName: SriovNetwork.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nw-du-fh"
        labels:
          lca.openshift.io/target-ocp-version: "4.15.0" <1>
      spec:
        resourceName: du_fh
        vlan: 140
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nnp-du-fh"
        labels:
          lca.openshift.io/target-ocp-version: "4.15.0" <1>
      spec:
        deviceType: netdevice
        isRdma: false
        nicSelector:
          pfNames: ["ens5f0"]
        numVfs: 8
        priority: 10
        resourceName: du_fh
    - fileName: SriovNetwork.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nw-du-mh"
        labels:
          lca.openshift.io/target-ocp-version: "4.15.0" <1>
      spec:
        resourceName: du_mh
        vlan: 150
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nnp-du-mh"
        labels:
          lca.openshift.io/target-ocp-version: "4.15.0" <1>
      spec:
        deviceType: vfio-pci
        isRdma: false
        nicSelector:
          pfNames: ["ens7f0"]
        numVfs: 8
        priority: 10
        resourceName: du_mh
----
<1> Ensure that the `lca.openshift.io/target-ocp-version` label matches the target {product-title} version that is specified in the `seedImageRef.version` field of the `ImageBasedUpgrade` CR. The {lcao} only applies the CRs that match the specified version.

. Commit, and push the created CRs to the git repository.

.. Verify that the stage and status policies are created:
+
--
[source,terminal]
----
$ oc get policies -n spoke1 | grep -E "group-ibu"
----

.Example output
[source,terminal]
----
ztp-group.group-ibu-prep-policy          inform               NonCompliant          31h
ztp-group.group-ibu-upgrade-policy       inform               NonCompliant          31h
----
--

. To reflect the target platform version, update the `du-profile` or the corresponding policy-binding label in the `SiteConfig` CR.
+
--
[source,yaml]
----
apiVersion: ran.openshift.io/v1
kind: SiteConfig
[...]
spec:
  [...]
    clusterLabels:
      du-profile: "4.15.0"
----

[IMPORTANT]
====
Updating the labels to the target platform version unbinds the existing set of policies.
====
--

. Commit and push the updated `SiteConfig` CR to the git repository.

. When you are ready to move to the `Prep` stage, create the `ClusterGroupUpgrade` CR with the `Prep` and OADP `ConfigMap` policies:
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-ibu-prep
  namespace: default
spec:
  clusters:
  - spoke1
  enable: true
  managedPolicies:
  - oadp-cm-common-policies
  - group-ibu-prep-policy
  remediationStrategy:
    canaries:
      - spoke1
    maxConcurrency: 1
    timeout: 240
----

. Apply the `Prep` policy:
+
[source,terminal]
----
$ oc apply -f cgu-ibu-prep.yml
----

.. Monitor the status and wait for the `cgu-ibu-prep` `ClusterGroupUpgrade` to report `Completed`.
+
--
[source,terminal]
----
$ oc get cgu -n default
----

.Example output
[source,terminal]
----
NAME                    AGE   STATE       DETAILS
cgu-ibu-prep            31h   Completed   All clusters are compliant with all the managed policies
----
--

[id="ztp-image-based-upgrade-upgrade-gitops_{context}"]
== Upgrading the {sno} cluster with GitOps ZTP

Once you completed the `Prep` stage, you can upgrade the target cluster. During the upgrade process, the OADP Operator creates a backup of the artifacts specified in the OADP CRs, then the {lcao} upgrades the cluster.

If the upgrade fails or stops, an automatic rollback is initiated. If you have an issue after the upgrade, you can initiate a manual rollback. For more information about manual rollback, see "(Optional) Initiating a rollback with Lifecycle Agent and GitOps ZTP".

.Prerequisites

* Complete the `Prep` stage.

.Procedure

. When you are ready to move to the `Upgrade` stage, create the `ClusterGroupUpgrade` CR that references the `Upgrade` policy:
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-ibu-upgrade
  namespace: default
spec:
  actions:
    beforeEnable:
      addClusterAnnotations:
        import.open-cluster-management.io/disable-auto-import: "true" <1>
    afterCompletion:
      removeClusterAnnotations:
      - import.open-cluster-management.io/disable-auto-import <2>
  clusters: 
  - spoke1
  enable: true
  managedPolicies: 
  - group-ibu-upgrade-policy
  remediationStrategy: 
    canaries: 
      - spoke1
    maxConcurrency: 1 
    timeout: 240
----
<1> Applies the `disable-auto-import` annotation to the managed cluster before starting the upgrade. This annotation ensures the automatic importing of managed cluster is disabled during the upgrade stage until the cluster is ready.
<2> Removes the `disable-auto-import` annotation after the upgrade is complete.

. Apply the `Upgrade` policy:
+
[source,terminal]
----
$ oc apply -f cgu-ibu-upgrade.yml
----

.. Monitor the status and wait for the `cgu-ibu-upgrade` `ClusterGroupUpgrade` to report `Completed`.
+
--
[source,terminal]
----
$ oc get cgu -n default
----

.Example output
[source,terminal]
----
NAME                    AGE   STATE       DETAILS
cgu-ibu-prep            31h   Completed   All clusters are compliant with all the managed policies
cgu-ibu-upgrade         31h   Completed   All clusters are compliant with all the managed policies
----
--

[id="ztp-image-based-upgrade-finalize-gitops_{context}"]
== Finalizing the image-based upgrade with GitOps ZTP

. When you are satisfied with the changes and ready to finalize the upgrade, create the `PolicyGenTemplate` to finalize the upgrade:
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: group-ibu
  namespace: "ztp-group"
spec:
  bindingRules:
    group-du-sno: ""
  mcp: "master"
  evaluationInterval:
    compliant: 10s
    noncompliant: 10s
  sourceFiles:
    - fileName: ibu/ImageBasedUpgrade.yaml
      policyName: "finalize-policy"
      spec:
        stage: Idle
      status:
        conditions:
          - status: "True"
            type: Idle
----

. Create a `ClusterGroupUpgrade` CR that references the policy that finalizes the upgrade:
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-ibu-finalize
  namespace: default
spec:
  actions:
    beforeEnable:
      removeClusterAnnotations:
      - import.open-cluster-management.io/disable-auto-import
  clusters: 
  - spoke1
  enable: true
  managedPolicies: 
  - group-ibu-finalize-policy
  remediationStrategy: 
    canaries: 
      - spoke1
    maxConcurrency: 1 
    timeout: 240
----

[IMPORTANT]
====
Ensure that no other `ClusterGroupUpgrade` CRs are in progress because this causes TALM to continuously reconcile them. Delete all "In-Progress" `ClusterGroupUpgrade` CRs before applying the `cgu-ibu-finalize.yaml`. 
====

. Apply the policy:
+
[source,terminal]
----
$ oc apply -f cgu-ibu-finalize.yaml
----

.. Monitor the status and wait for the `cgu-ibu-upgrade` `ClusterGroupUpgrade` to report `Completed`.
+
--
[source,terminal]
----
$ oc get cgu -n default
----

.Example output
[source,terminal]
----
NAME                    AGE   STATE       DETAILS
cgu-ibu-finalize        30h   Completed   All clusters are compliant with all the managed policies
cgu-ibu-prep            31h   Completed   All clusters are compliant with all the managed policies
cgu-ibu-upgrade         31h   Completed   All clusters are compliant with all the managed policies
----
--

[id="ztp-image-based-upgrade-with-talm-rollback_{context}"]
== (Optional) Initiating a rollback with {lcao} and GitOps ZTP

If you encounter an issue after upgrade, you can start a manual rollback.

.Procedure

. Revert the `du-profile` or the corresponding policy-binding label to the original platform version in the `SiteConfig` CR:
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1
kind: SiteConfig
[...]
spec:
  [...]
    clusterLabels:
      du-profile: "4.14.x"
----

. When you are ready to move to the `Rollback` stage, create a `PolicyGenTemplate` CR for the `Rollback` policies:
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: group-ibu
  namespace: "ztp-group"
spec:
  bindingRules:
    group-du-sno: ""
  mcp: "master"
  evaluationInterval:
    compliant: 10s
    noncompliant: 10s
  sourceFiles:
    - fileName: ibu/ImageBasedUpgrade.yaml
      policyName: "rollback-policy"
      spec:
        stage: Rollback
      status:
        conditions:
          - message: Rollback completed
            reason: Completed
            status: "True"
            type: RollbackCompleted
----

. Create a `ClusterGroupUpgrade` CR that references the `Rollback` policies:
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-ibu-rollback
  namespace: default
spec:
  actions:
    beforeEnable:
      removeClusterAnnotations:
      - import.open-cluster-management.io/disable-auto-import
  clusters: 
  - spoke1
  enable: true
  managedPolicies: 
  - group-ibu-rollback-policy
  remediationStrategy: 
    canaries: 
      - spoke1
    maxConcurrency: 1 
    timeout: 240
----

. Apply the `Rollback` policy:
+
[source,terminal]
----
$ oc apply -f cgu-ibu-rollback.yml
----

. When you are satisfied with the changes and you are ready to finalize the rollback, create the `PolicyGenTemplate` CR:
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: group-ibu
  namespace: "ztp-group"
spec:
  bindingRules:
    group-du-sno: ""
  mcp: "master"
  evaluationInterval:
    compliant: 10s
    noncompliant: 10s
  sourceFiles:
    - fileName: ImageBasedUpgrade.yaml
      policyName: "finalize-policy"
      spec:
        stage: Idle
      status:
        conditions:
          - status: "True"
            type: Idle
----

. Create a `ClusterGroupUpgrade` CR that references the policy that finalizes the upgrade:
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-ibu-finalize
  namespace: default
spec:
  actions:
    beforeEnable:
      removeClusterAnnotations:
      - import.open-cluster-management.io/disable-auto-import
  clusters: 
  - spoke1
  enable: true
  managedPolicies: 
  - group-ibu-finalize-policy
  remediationStrategy: 
    canaries: 
      - spoke1
    maxConcurrency: 1 
    timeout: 240
----

. Apply the policy:
+
[source,terminal]
----
$ oc apply -f cgu-ibu-finalize.yml
----