// Module included in the following assemblies:
//
// * edge_computing/ztp-advanced-policy-config.adoc
// * edge_computing/ztp-advanced-policygenerator-config.adoc

:_mod-docs-content-type: PROCEDURE
[id="ztp-creating-hwevents-amqp_{context}"]
= Configuring bare-metal events that use AMQP transport

You can configure bare-metal events that use AMQP transport on managed clusters that you deploy with the {ztp-first} pipeline.

include::snippets/ptp-amq-interconnect-eol.adoc[]

.Prerequisites

* You have installed the OpenShift CLI (`oc`).

* You have logged in as a user with `cluster-admin` privileges.

* You have created a Git repository where you manage your custom site configuration data.

.Procedure

. To configure the AMQ Interconnect Operator and the {redfish-operator} Operator, add the following YAML to `{rangen-yaml-path}` in the `{policy-prefix}common-ranGen.yaml` file:
+
[source,yaml]
----
ifeval::["{policy-gen-cr}" == "PolicyGenTemplate"]
include::snippets/pgt-ztp-creating-hwevents-amqp.yaml[]
endif::[]
ifeval::["{policy-gen-cr}" == "PolicyGenerator"]
include::snippets/pg-ztp-creating-hwevents-amqp.yaml[]
endif::[]
----

. Add the `Interconnect` CR to `{rangen-yaml-path}` in the site configuration file, for example, the `{policy-prefix}example-sno-site.yaml` file:
+
[source,yaml]
----
ifeval::["{policy-gen-cr}" == "PolicyGenTemplate"]
- fileName: AmqInstance.yaml
  policyName: "config-policy"
endif::[]
ifeval::["{policy-gen-cr}" == "PolicyGenerator"]
- path: source-crs/AmqInstance.yaml
endif::[]
----

. Add the `HardwareEvent` CR to `{rangen-yaml-path}` in your specific group configuration file, for example, in the `{policy-prefix}group-du-sno-ranGen.yaml` file:
+
ifeval::["{policy-gen-cr}" == "PolicyGenTemplate"]
include::snippets/ztp-creating-hwevents-amqp-hardware-event.adoc[]
endif::[]
ifeval::["{policy-gen-cr}" == "PolicyGenerator"]
include::snippets/ztp-creating-hwevents-amqp-hardware-event.adoc[]
endif::[]
+
[NOTE]
====
Each baseboard management controller (BMC) requires a single `HardwareEvent` resource only.
====

. Commit the `{policy-gen-cr}` change in Git, and then push the changes to your site configuration repository to deploy bare-metal events monitoring to new sites using {ztp}.

. Create the Redfish Secret by running the following command:
+
[source,terminal]
----
$ oc -n openshift-bare-metal-events create secret generic redfish-basic-auth \
--from-literal=username=<bmc_username> --from-literal=password=<bmc_password> \
--from-literal=hostaddr="<bmc_host_ip_addr>"
----
