#image:
#  file: .gitpod.Dockerfile
  
tasks:
  - name: Dev Server
    # before: npm install --global http-server
    init: |
      rvm install 2.7.6
      gem install asciidoctor asciidoctor-diagram ascii_binder
#      pip3 install aura.tar.gz
    command: |
      asciibinder build --distro=openshift-enterprise
      BR="$(git branch --show-current)"
      cd _preview/openshift-enterprise/$BR
      ln -s welcome/index.html index.html
      python -m http.server