repository: openshift-docs
variants:
 - name: openshift-container-platform
   attributes:
    - _attributes/ocp-attributes.adoc
    - _attributes/common-attributes.adoc
   nav: _artifacts/toc.yml
   build: true
   files:
     included:
       - _attributes/*.adoc
       - applications/**/*.adoc
       - architecture/**/*.adoc
       - authentication/**/*.adoc
       - backup_and_restore/**/*.adoc
       - cicd/**/*.adoc
       - cli_reference/**/*.adoc
       - distr_tracing/**/*.adoc
       - getting_started/**/*.adoc
       - hardware_enablement/**/*.adoc
       - images/*.jpg
       - images/*.png
       - images/*.svg
       - installing/**/*.adoc
       - logging/**/*.adoc
       - machine_management/**/*.adoc
       - migrating_from_ocp_3_to_4/**/*.adoc
       - migration_toolkit_for_containers/**/*.adoc
       - modules/**/*.adoc
       - monitoring/**/*.adoc
       - networking/**/*.adoc
       - nodes/**/*.adoc
       - openshift_images/**/*.adoc
       - operators/**/*.adoc
       - post_installation_configuration/**/*.adoc
       - registry/**/*.adoc
       - release_notes/**/*.adoc
       - rest_api/**/*.adoc
       - sandboxed_containers/**/*.adoc
       - scalability_and_performance/**/*.adoc
       - security/**/*.adoc
       - serverless/**/*.adoc
       - service_mesh/**/*.adoc
       - snippets/*.adoc
       - storage/**/*.adoc
       - support/**/*.adoc
       - updating/**/*.adoc
       - virt/**/*.adoc
       - web_console/**/*.adoc
       - welcome/**/*.adoc
       - windows_containers/**/*.adoc
     excluded:
       - _images/**/*.*
       - _javascript/**/*.*
       - _package/**/*.*
       - _preview/**/*.*
       - _stylesheets/**/*.*
       - _templates/**/*.*
       - _topic_maps/**/*.*
       - _unused_topics/**/*.adoc
       - .git/**/*.*
       - .github/**/*.*
       - .s2i/**/*.*
       - adding_service_cluster/**/*.adoc
       - administering_a_cluster/**/*.adoc
       - applications_and_projects/**/*.adoc
       - cloud_providers/**/*.adoc
       - contributing_to_docs/**/*.adoc
       - identity_providers/**/*.adoc
       - jaeger/**/*.adoc
       - masters/**/*.adoc
       - metering/**/*.adoc
       - metrics/**/*.adoc
       - mod_docs_guide/**/*.adoc
       - ocm/**/*.adoc
       - osd_architecture/**/*.adoc
       - osd_cluster_create/**/*.adoc
       - osd_notifications/**/*.adoc
       - osd_planning/**/*.adoc
       - osd_policy/**/*.adoc
       - osd_private_connections/**/*.adoc
       - osd_quickstart/**/*.adoc
       - planning/**/*.adoc
       - rosa_architecture/**/*.adoc
       - rosa_cli/**/*.adoc
       - rosa_cluster_admin/**/*.adoc
       - rosa_getting_started/**/*.adoc
       - rosa_glossary/**/*.adoc
       - rosa_planning/**/*.adoc
       - rosa_policy/**/*.adoc
       - rosa_quickstart/**/*.adoc
       - rosa_release_notes/**/*.adoc
       - rosa_support/**/*.adoc
       - router/**/*.adoc
       - scripts/**/*.*
       - upgrading/**/*.adoc
       - whats_new/**/*.adoc
       - networking/external_dns_operator/nw-installing-external-dns-operator-on-cloud-providers.adoc
       - networking/external_dns_operator/nw-creating-dns-records-on-azure.adoc
       - networking/external_dns_operator/nw-creating-dns-records-on-aws.adoc
       - networking/external_dns_operator/nw-configuration-parameters.adoc
       - networking/external_dns_operator/nw-creating-dns-records-on-gcp.adoc
       - updating/updating-cluster-prepare.adoc
       - service_mesh/v1x/ossm-config.adoc
 - name: openshift-dedicated
   attributes:
    - _attributes/osd-attributes.adoc
    - _attributes/attributes-openshift-dedicated.adoc
   build: false
   files:
     included:
       - adding_service_cluster/**/*.adoc
       - administering_a_cluster/**/*.adoc
       - applications/**/*.adoc
       - authentication/**/*.adoc
       - identity_providers/**/*.adoc
       - images/*.jpg
       - images/*.png
       - images/*.svg
       - modules/**/*.adoc
       - monitoring/**/*.adoc
       - networking/**/*.adoc
       - nodes/**/*.adoc
       - ocm/**/*.adoc
       - osd_architecture/**/*.adoc
       - osd_cluster_create/**/*.adoc
       - osd_notifications/**/*.adoc
       - osd_planning/**/*.adoc
       - osd_policy/**/*.adoc
       - osd_private_connections/**/*.adoc
       - osd_quickstart/**/*.adoc
       - serverless/**/*.adoc
       - snippets/*.adoc
       - storage/**/*.adoc
       - support/**/*.adoc
       - upgrading/**/*.adoc
       - welcome/**/*.adoc
     excluded:
       - _images/**/*.*
       - _javascript/**/*.*
       - _package/**/*.*
       - _preview/**/*.*
       - _stylesheets/**/*.*
       - _templates/**/*.*
       - _topic_maps/**/*.*
       - _unused_topics/**/*.adoc
       - .git/**/*.*
       - .github/**/*.*
       - .s2i/**/*.*
       - applications_and_projects/**/*.adoc
       - architecture/**/*.adoc
       - backup_and_restore/**/*.adoc
       - cicd/**/*.adoc
       - cli_reference/**/*.adoc
       - cloud_providers/**/*.adoc
       - contributing_to_docs/**/*.adoc
       - distr_tracing/**/*.adoc
       - getting_started/**/*.adoc
       - hardware_enablement/**/*.adoc
       - installing/**/*.adoc
       - jaeger/**/*.adoc
       - logging/**/*.adoc
       - machine_management/**/*.adoc
       - masters/**/*.adoc
       - metering/**/*.adoc
       - metrics/**/*.adoc
       - migrating_from_ocp_3_to_4/**/*.adoc
       - migration_toolkit_for_containers/**/*.adoc
       - mod_docs_guide/**/*.adoc
       - openshift_images/**/*.adoc
       - operators/**/*.adoc
       - planning/**/*.adoc
       - post_installation_configuration/**/*.adoc
       - registry/**/*.adoc
       - release_notes/**/*.adoc
       - rest_api/**/*.adoc
       - rosa_architecture/**/*.adoc
       - rosa_cli/**/*.adoc
       - rosa_cluster_admin/**/*.adoc
       - rosa_getting_started/**/*.adoc
       - rosa_glossary/**/*.adoc
       - rosa_planning/**/*.adoc
       - rosa_policy/**/*.adoc
       - rosa_quickstart/**/*.adoc
       - rosa_release_notes/**/*.adoc
       - rosa_support/**/*.adoc
       - router/**/*.adoc
       - sandboxed_containers/**/*.adoc
       - scalability_and_performance/**/*.adoc
       - scripts/**/*.*
       - security/**/*.adoc
       - service_mesh/**/*.adoc
       - updating/**/*.adoc
       - virt/**/*.adoc
       - web_console/**/*.adoc
       - whats_new/**/*.adoc
       - windows_containers/**/*.adoc
 - name: openshift-rosa
   attributes:
    - _attributes/rosa-attributes.adoc
    - _attributes/attributes-openshift-dedicated.adoc
   build: false
   files:
     included:
       - adding_service_cluster/**/*.adoc
       - applications/**/*.adoc
       - authentication/**/*.adoc
       - images/*.jpg
       - images/*.png
       - images/*.svg
       - modules/**/*.adoc
       - networking/**/*.adoc
       - ocm/**/*.adoc
       - rosa_architecture/**/*.adoc
       - rosa_cli/**/*.adoc
       - rosa_cluster_admin/**/*.adoc
       - rosa_getting_started/**/*.adoc
       - rosa_planning/**/*.adoc
       - rosa_support/**/*.adoc
       - storage/**/*.adoc
       - upgrading/**/*.adoc
       - welcome/**/*.adoc
     excluded:
       - _images/**/*.*
       - _javascript/**/*.*
       - _package/**/*.*
       - _preview/**/*.*
       - _stylesheets/**/*.*
       - _templates/**/*.*
       - _topic_maps/**/*.*
       - _unused_topics/**/*.adoc
       - .git/**/*.*
       - .github/**/*.*
       - .s2i/**/*.*
       - administering_a_cluster/**/*.adoc
       - applications_and_projects/**/*.adoc
       - architecture/**/*.adoc
       - backup_and_restore/**/*.adoc
       - cicd/**/*.adoc
       - cli_reference/**/*.adoc
       - cloud_providers/**/*.adoc
       - contributing_to_docs/**/*.adoc
       - distr_tracing/**/*.adoc
       - getting_started/**/*.adoc
       - hardware_enablement/**/*.adoc
       - identity_providers/**/*.adoc
       - installing/**/*.adoc
       - jaeger/**/*.adoc
       - logging/**/*.adoc
       - machine_management/**/*.adoc
       - masters/**/*.adoc
       - metering/**/*.adoc
       - metrics/**/*.adoc
       - migrating_from_ocp_3_to_4/**/*.adoc
       - migration_toolkit_for_containers/**/*.adoc
       - mod_docs_guide/**/*.adoc
       - monitoring/**/*.adoc
       - nodes/**/*.adoc
       - openshift_images/**/*.adoc
       - operators/**/*.adoc
       - osd_architecture/**/*.adoc
       - osd_cluster_create/**/*.adoc
       - osd_notifications/**/*.adoc
       - osd_planning/**/*.adoc
       - osd_policy/**/*.adoc
       - osd_private_connections/**/*.adoc
       - osd_quickstart/**/*.adoc
       - planning/**/*.adoc
       - post_installation_configuration/**/*.adoc
       - registry/**/*.adoc
       - release_notes/**/*.adoc
       - rest_api/**/*.adoc
       - rosa_glossary/**/*.adoc
       - rosa_policy/**/*.adoc
       - rosa_quickstart/**/*.adoc
       - rosa_release_notes/**/*.adoc
       - router/**/*.adoc
       - sandboxed_containers/**/*.adoc
       - scalability_and_performance/**/*.adoc
       - scripts/**/*.*
       - security/**/*.adoc
       - serverless/**/*.adoc
       - service_mesh/**/*.adoc
       - snippets/*.adoc
       - support/**/*.adoc
       - updating/**/*.adoc
       - virt/**/*.adoc
       - web_console/**/*.adoc
       - whats_new/**/*.adoc
       - windows_containers/**/*.adoc
