FROM registry.access.redhat.com/ubi8/ruby-27

ENV LANG=en_US.UTF-8

COPY . /src/

WORKDIR /src/

USER root

RUN gem install listen:3.0.8 ascii_binder asciidoctor asciidoctor-diagram rouge

RUN yum install python3 python3-pip python3-devel -y && yum clean all

RUN pip3 install pyyaml aura.tar.gz

RUN set -x && make test-portal-build
