FROM registry.access.redhat.com/ubi8/ruby-27

ENV LANG=en_US.UTF-8

COPY . /src/

WORKDIR /src/

USER root

RUN gem install asciidoctor asciidoctor-diagram rouge

RUN set -x && make test-asciidoc-source
