# these are defaults.  Let's skip all builds by default!
# docs for this are here:  https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds

[build]
  ignore = "/bin/true"

# we can override per context - deploy-preview is PR's ONLY
[context.deploy-preview]
  ignore = "/bin/false"
