:_mod-docs-content-type: ASSEMBLY
[id="sd-managed-resources"]
= Red{nbsp}Hat managed resources
include::_attributes/attributes-openshift-dedicated.adoc[]
:context: sd-managed-resources

toc::[]

[id="sd-managed-resources-overview_{context}"]
== Overview

The following covers all {product-title} resources that are managed or protected by the Service Reliability Engineering Platform (SRE-P) Team. Customers must not modify these resources because doing so can lead to cluster instability.

[id="sd-managed-resources-all_{context}"]
ifdef::openshift-rosa,openshift-dedicated[]
== Hive managed resources

The following list displays the {product-title} resources managed by OpenShift Hive, the centralized fleet configuration management system. These resources are in addition to the OpenShift Container Platform resources created during installation. OpenShift Hive continually attempts to maintain consistency across all {product-title} clusters. Changes to {product-title} resources should be made through {cluster-manager} so that {cluster-manager} and Hive are synchronized. Contact `ocm-feedback@redhat.com` if {cluster-manager} does not support modifying the resources in question.

.List of Hive managed resources
endif::openshift-rosa,openshift-dedicated[]
ifdef::openshift-rosa-hcp[]
== Red{nbsp}Hat managed resources

The following resources are created and managed by the management cluster, which is managed by Red{nbsp}Hat.

.List of Red{nbsp}Hat managed resources
endif::openshift-rosa-hcp[]
[%collapsible]
====
[source,yaml]
----
include::https://raw.githubusercontent.com/openshift/managed-cluster-config/master/resources/managed/all-osd-resources.yaml[]
----
====
//endif::openshift-rosa,openshift-dedicated[]

[id="sd-core-namespaces_{context}"]
== {product-title} core namespaces

{product-title} core namespaces are installed by default during cluster installation.

ifdef::openshift-rosa,openshift-dedicated[]
.List of core namespaces
[%collapsible]
====
[source,yaml]
----
include::https://raw.githubusercontent.com/openshift/managed-cluster-config/master/deploy/osd-managed-resources/ocp-namespaces.ConfigMap.yaml[]
----
====
endif::openshift-rosa,openshift-dedicated[]
ifdef::openshift-rosa-hcp[]
.List of core namespaces
[%collapsible]
====
[source,yaml]
----
default
kube-node-lease
kube-public
kube-system
open-cluster-management-agent
open-cluster-management-agent-addon
openshift
openshift-apiserver
openshift-apiserver-operator
openshift-authentication
openshift-authentication-operator
openshift-backplane
openshift-backplane-cee
openshift-backplane-cse
openshift-backplane-csm
openshift-backplane-lpsre
openshift-backplane-managed-scripts
openshift-backplane-mcs-tier-two
openshift-backplane-mobb
openshift-backplane-srep
openshift-backplane-tam
openshift-cloud-controller-manager
openshift-cloud-credential-operator
openshift-cloud-network-config-controller
openshift-cluster-csi-drivers
openshift-cluster-machine-approver
openshift-cluster-node-tuning-operator
openshift-cluster-samples-operator
openshift-cluster-storage-operator
openshift-cluster-version
openshift-config
openshift-config-managed
openshift-config-operator
openshift-console
openshift-console-operator
openshift-console-user-settings
openshift-controller-manager
openshift-controller-manager-operator
openshift-customer-monitoring
openshift-deployment-validation-operator
openshift-dns
openshift-dns-operator
openshift-etcd
openshift-host-network
openshift-image-registry
openshift-infra
openshift-ingress
openshift-ingress-canary
openshift-ingress-operator
openshift-insights
openshift-kube-apiserver
openshift-kube-apiserver-operator
openshift-kube-controller-manager
openshift-kube-controller-manager-operator
openshift-kube-scheduler
openshift-kube-scheduler-operator
openshift-kube-storage-version-migrator
openshift-kube-storage-version-migrator-operator
openshift-logging
openshift-machine-api
openshift-machine-config-operator
openshift-marketplace
openshift-monitoring
openshift-multus
openshift-must-gather-operator
openshift-network-console
openshift-network-diagnostics
openshift-network-node-identity
openshift-network-operator
openshift-node
openshift-operator-lifecycle-manager
openshift-operators
openshift-operators-redhat
openshift-ovn-kubernetes
openshift-package-operator
openshift-route-controller-manager
openshift-service-ca
openshift-service-ca-operator
openshift-user-workload-monitoring
----
====
endif::openshift-rosa-hcp[]

ifdef::openshift-rosa,openshift-dedicated[]
[id="sd-add-on-managed-namespaces_{context}"]
== {product-title} add-on namespaces

{product-title} add-ons are services available for installation after cluster installation. These additional services include AWS CloudWatch, {openshift-dev-spaces-productname}, Red{nbsp}Hat OpenShift API Management, and Cluster Logging Operator. Any changes to resources within the following namespaces might be overridden by the add-on during upgrades, which can lead to unsupported configurations for the add-on functionality.

.List of add-on managed namespaces
[%collapsible]
====
[source,yaml]
----
include::https://raw.githubusercontent.com/openshift/managed-cluster-config/master/resources/addons-namespaces/main.yaml[]
----
====
endif::openshift-rosa,openshift-dedicated[]

[id="sd-validating-webhooks_{context}"]
== {product-title} validating webhooks

{product-title} validating webhooks are a set of dynamic admission controls maintained by the OpenShift SRE team. These HTTP callbacks, also known as webhooks, are called for various types of requests to ensure cluster stability. The webhooks evaluate each request and either accept or reject them. The following list describes the various webhooks with rules containing the registered operations and resources that are controlled. Any attempt to circumvent these validating webhooks could affect the stability and supportability of the cluster.

.List of validating webhooks
[%collapsible]
====
[source,json]
----
include::https://raw.githubusercontent.com/openshift/managed-cluster-validating-webhooks/master/docs/webhooks.json[]
----
====
