// Module included in the following assemblies:
// * installing/installing_gcp/installing-gcp-customizations.adoc

:_content-type: CONCEPT
[id="installing-gcp-user-defined-tags_{context}"]
= Configuring the user-defined tags for GCP

In {product-title}, you can use the tags for grouping, organizing and for managing resources created for a particular {product-title} cluster. 

You can define labels & tags on the GCP resources only during cluster creation that is available from {product-title} version {product-version}. User-defined tags are not supported for {product-title} clusters upgraded to {product-title} version {product-version}.

User-defined and {product-title} specific tags are applied only to resources created by {product-title} installer and its core operators such as `machine-api-provider-gcp`, `cluster-image-registry-operator`, `gcp-filestore-csi-driver-operator`, g`cp-pd-csi-driver-operator` and not on the resources created by any other operators or the kubernetes in-tree components that creates resources for example the ingress load balancers.

User-defined tags are attached to resources created by {product-title} installer and its core operators such as `cluster-image-registry-operator` and not on the resources created by any other operators or the kubernetes in-tree components. In {product-title} version {product-version}, resources created by `machine-api-provider-gcp`, `gcp-filestore-csi-driver-operator`, `gcp-pd-csi-driver-operator` are not tagged.

[NOTE]
====
Labels & tags once defined during the install-config creation phase cannot be modified or updated with new labels & tags after cluster creation.
====

Support for user-defined labels & tags for GCP resources is available in {product-title} version {product-version} as Technology Preview (TP).

Service Account used for cluster creation must have the `TagUser` role assigned to it, required for tags defined at both organization and project level.

You can use `.platform.gcp.userLabels` and `platform.gcp.userTags` fields to define the list of desired labels & tags in `install-config.yaml`. `.platform.gcp.userLabels` and `.platform.gcp.userTags` fields are a yaml array of objects type.

.Sample `install-config.yaml` file
[source,yaml]
----
apiVersion: v1
featureSet: TechPreviewNoUpgrade
platform:
  gcp:
    userLabels:
    - key: <label_key>
      value: <label_value>
    userTags:
    - parentID: <OrganizationID/ProjectID>
      key: <tag_key_short_name>
      value: <tag_value_short_name>
----

The user-defined labels have the following requirements:

* A label key and value must have a minimum of 1 character and can have a maximum of 63 characters.
* A label key and value must contain only lowercase letters, numeric characters, underscores, and dashes.
* A label key must start with a lowercase letter.
* Each resource can have multiple labels, up to a maximum of 32.
* You can configure a maximum of 64 labels per resource. 
* The number of user-defined labels are restricted to 32 and reserved to 32 for {product-title}'s internal use.

The user-defined tags have the following requirements:

* Tag Keys and Tag Values must already exist and will not be created by {product-title}.
* A tag `parentID` can be either `OrganizationID` or `ProjectID`. 
* An `OrganizationID` must consist of decimal numbers, and cannot have leading zeros.
* A `ProjectID` must be 6 to 30 characters in length, can only contain lowercase letters, numbers, and hyphens, and must start with a letter, and cannot end with a hyphen.
* A tag key and value must have a minimum of 1 character and can have a maximum of 63 characters.
* A tag key must contain only uppercase and lowercase alphanumeric characters, hyphens, underscores, and periods.
* A tag value must contain only uppercase and lowercase alphanumeric characters, hyphens, underscores, periods, at signs, percent signs, equals signs, plusses, colons, commas, asterisks, pound signs, ampersands, parentheses, square braces, curly braces, and spaces.
* A tag key and value must begin and end with an alphanumeric character.
* Tag key must already exist.
* Tag value is of type scalar and must be one of the pre-defined values for the key.
* You can configure a maximum of 50 tags.
* There should be no tag key with the same value as any of the existing tag keys on a resource(inherited from parent resource).

For more information about identifying the `OrganizationID` or `ProjectID`, see link:https://cloud.google.com/resource-manager/docs/creating-managing-organization#retrieving_your_organization_id[OrganizationID]
and link:https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects[ProjectID].

After creating {product-title} cluster, you can access the list of the labels and tags defined for the GCP resources. You can refer to the new fields `.status.platformStatus.gcp.resourceLabels` and `.status.platformStatus.gcp.resourceTags` present in `infrastructures.config.openshift.io/cluster` object.

.Sample 
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: Infrastructure
metadata:
  name: cluster
spec:
  platformSpec:
    type: GCP
status:
  infrastructureName: <cluster_id>
  platform: GCP
  platformStatus:
    gcp:
      resourceLabels:
      - key: <label_key>
        value: <label_value>
      resourceTags:
      - key: <tag_key_short_name>
        parentID: <OrganizationID/ProjectID>
        value: <tag_value_short_name>
    type: GCP
----

Along with the user-defined labels, resources will also have a label defined by the {product-title}. The format of the {product-title} labels is `kubernetes-io-cluster-<cluster_id>:owned`. The `cluster_id` parameter is the value of `.status.infrastructureName` present in `infrastructures.config.openshift.io/cluster`.

User-defined and {product-title} labels can be present in the following GCP resoucres:

* Compute Instance
* Compute Disk
* Compute Forwarding Rule
* Compute Image
* DNS Managed Zone
* Filestore Instance
* Storage Bucket

User-defined tags can be found added to the following GCP resources:

* Compute Instance
* Storage Bucket

The following are the limitations for the user-defined tags:

* Tags will not be attached to worker compute instances created by `machine-api-provider-gcp controlle`r, filesore instance resources created by `gcp-filestore-csi-driver-operator` and disk, image resources created by `gcp-pd-csi-driver-operator`.
* Tags are not supported for buckets located in the `us-east2` and `us-east3` regions.
* `cluster-image-registry-operator` will not throw any error but skips processing tags when the buckets are created in the tags unsupported region.
* Tags must not be restricted to particular service accounts, since operators create and use service accounts with minimal roles.
* {product-title} will not create tag keys and value resources.
* {product-title} specific tags will not be added to any resource.
* Labels for `Compute Address` are supported in the GCP beta version and {product-title} does not add labels to the resource.

For more information about tags and labels, see link:https://cloud.google.com/storage/docs/tags-and-labels#tags[Tags and labels].