:_mod-docs-content-type: ASSEMBLY
[id="virt-automatic-bootsource-updates"]
= Automatic importing and updating of pre-defined boot sources
include::_attributes/common-attributes.adoc[]
:context: virt-automatic-bootsource-updates

toc::[]

You can use boot sources that are _system-defined_ and included with {VirtProductName} or _user-defined_, which you create. System-defined boot source imports and updates are controlled by the product feature gate. You can enable, disable, or re-enable updates using the feature gate. User-defined boot sources are not controlled by the product feature gate and must be individually managed to opt in or opt out of automatic imports and updates.

[IMPORTANT]
====
As of version 4.10, {VirtProductName} automatically imports and updates boot sources, unless you manually opt out or do not set a default storage class.

If you upgrade to version 4.10, you must manually enable automatic imports and updates for boot sources from version 4.9 or earlier.
====

include::modules/virt-enabling-bootsource-update.adoc[leveloffset=+1]

include::modules/virt-disable-bootsource-update.adoc[leveloffset=+1]

include::modules/virt-reenabling-bootsource-update.adoc[leveloffset=+1]

include::modules/virt-configuring-storage-class-bootsource-update.adoc[leveloffset=+1]

include::modules/virt-autoupdate-custom-bootsource.adoc[leveloffset=+1]

include::modules/virt-disable-individual-bootsource-update.adoc[leveloffset=+1]

include::modules/virt-verify-status-bootsource-update.adoc[leveloffset=+1]
