:_mod-docs-content-type: ASSEMBLY
include::_attributes/attributes-openshift-dedicated.adoc[]
[id="rosa-hcp-upgrading"]
= Upgrading {hcp-title} clusters
:context: rosa-hcp-upgrading

toc::[]

include::modules/rosa-hcp-upgrade-options.adoc[leveloffset=+1]

//This cannot be a module if we want to use the xrefs
[id="rosa-lifecycle-policy_{context}"]
== Life cycle policies and planning


The life cycle page includes release definitions, support and upgrade requirements, installation policy information and life cycle dates.

Upgrades are manually initiated or automatically scheduled. Red Hat Site Reliability Engineers (SREs) monitor upgrade progress and remedy any issues encountered.

//The following note should be removed when the entire HCP fleet is confirmed multi-arch
[NOTE]
====
If your control plane is not currently multi-architecture enabled, the upgrade process will first migrate the cluster to a multi-architecture image and then apply the version upgrade. Multi-architecture clusters are capable of running both x86-based and Arm-based workloads. Clusters created after 25 July, 2024 are multi-architecture enabled by default. 
====

include::modules/rosa-hcp-upgrading-cli-control-plane.adoc[leveloffset=+1]

include::modules/rosa-hcp-upgrading-cli-machinepool.adoc[leveloffset=+1]

[id="rosa-hcp-upgrading-cli-cluster_{context}"]
== Upgrading the whole cluster with the ROSA CLI

Upgrading the entire cluster involves upgrading both the hosted control plane and nodes in the machine pools. However, these components cannot be upgraded at the same time. They must be upgraded in sequence. This can be done in any order. However, to maintain compatibility between nodes in the cluster, nodes in machine pools cannot use a newer version than the hosted control plane. Therefore, if both the hosted control plane and the nodes in your machine pools require upgrade to the same OpenShift version, you must upgrade the hosted control plane first, followed by the machine pools.

[discrete]
=== Prerequisites
* You have installed and configured the latest version of the ROSA CLI.
* No other upgrades are in progress or scheduled to take place at the same time as this upgrade.

ifdef::context[:prevcontext: {context}]

:context: rosa-hcp-upgrading-whole-cluster

include::modules/rosa-hcp-upgrading-cli-control-plane.adoc[leveloffset=+2]

ifdef::prevcontext[:context: {prevcontext}]

ifdef::context[:prevcontext: {context}]

:context: rosa-hcp-upgrading-whole-cluster

include::modules/rosa-hcp-upgrading-cli-machinepool.adoc[leveloffset=+2]

ifdef::prevcontext[:context: {prevcontext}]
ifndef::prevcontext[:!context:]
