[[getting-started-devpreview-faq]]
= Developer Preview FAQ
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:

toc::[]

== Overview

During the {product-title} (Next Gen) Developer Preview, consult the following sections
for frequently asked questions and
xref:devpreview-current-usage-considerations[current usage considerations]
during the preview period.

[[devpreview-faq-product]]
== Product

HOW IS THE NEXT GEN DEVELOPER PREVIEW DIFFERENT THAN OPENSHIFT ONLINE?::
{product-title} currently runs on the {product-title} 2.X platform. The Next Gen
Developer Preview brings {product-title} 3, built on Docker and Kubernetes, to the public
cloud in a multi-tenant environment.
xref:../getting_started/online_v2_vs_v3.adoc#getting-started-online-v2-vs-v3[Learn more].

WHAT HAPPENS TO MY OPENSHIFT ONLINE (V2) ACCOUNT WHEN NEXT GEN (V3) GOES INTO PRODUCTION?::
At this time, the current (v2) and next generation (v3) platforms will be available in
parallel. As the {product-title} (Next Gen) platform matures, we will publish a sunset
plan for the current (v2) offering and provide you with adequate time to migrate your
applications to the new platform.

WHAT ARE THE RESOURCE LIMITS DURING THE DEVELOPER PREVIEW?::
Each user can create a single project with up to 2 GiB memory, 4 CPU cores, and 2 x 1
GiB persistent volumes. For more detailed limits, see the *Settings* tab on your
project's Overview page in the web console.

HOW LONG WILL I HAVE ACCESS TO THE ENVIRONMENT?::
You will have access to the {product-title} (Next Gen) Developer Preview environment for
30 days, at which point your account will expire.

WHAT HAPPENS WHEN MY ACCOUNT EXPIRES?::
Your account, applications, and data will be permanently deleted to free up
resources for other users when your account expires. This means that you will no
longer be able to log in to the web console, authenticate using the {product-title}
CLI tools, or access your applications and related data.

CAN I CREATE A NEW ACCOUNT AFTER MY ACCOUNT EXPIRES?::
If you are interested in trying the {product-title} (Next Gen) Developer Preview again,
just complete the registration form after your account expires and we will
provision a fresh set of resources for you as soon as they become available.

WHAT LANGUAGES AND DATABASE SERVICES ARE SUPPORTED?::
The {product-title} (Next Gen) Developer Preview currently supports a number of developer languages and database services, including JBoss Middleware services.

See the link:https://www.openshift.com/features/cartridges.html#online3[OpenShift features page] for the list of available languages and services.

CAN USERS RUN IMAGES FROM DOCKER HUB OR PUSH THEIR OWN IMAGES TO THE REGISTRY?::
Yes, but with a few caveats. For
https://docs.docker.com/engine/security/security/[security reasons], no images
that run processes as root are allowed. Additionally, any Dockerfile `VOLUME`
instruction must be mounted with either a persistent volume claim (PVC) or an
emptyDir at this time. See xref:devpreview-current-usage-considerations[more
considerations].

CAN I RUN PRODUCTION SERVICES ON THE DEVELOPER PREVIEW?::
The Developer Preview is a time bound environment which can be used for
prototyping or experimenting. We recommend that users do not deploy any
production workloads. However, you can deploy a copy of your production workload
to see how it performs in the environment.

[[devpreview-faq-pricing]]
== Pricing

HOW AM I BILLED?::
During our Developer Preview period, {product-title} (Next Gen) is FREE!

ARE PAID PLANS AVAILABLE FOR OPENSHIFT (NEXT GEN)?::
Not at this time. {product-title} (Next Gen) will offer paid tiers when the
offering becomes generally available.

[[devpreview-faq-operations]]
== Operations

WHAT IS YOUR SLA?::
During our Developer Preview period, we do not offer a Service Level Agreement
(SLA).

HOW CAN I FIND OUT ABOUT PRODUCT UPDATES AND SCHEDULED MAINTENANCE?::
Red Hat will provide updates via
http://status.preview.openshift.com[status.preview.openshift.com].

[[devpreview-faq-support]]
== Support

HOW CAN I RECEIVE SUPPORT FOR THE OFFERING?::
During the Developer Preview there are no paid or official support channels,
however, you can contact the Community Enablement team, create a bug report in
Bugzilla, or create a post in the {product-title} Forums.

HOW SHOULD I REACH THE COMMUNITY ENABLEMENT TEAM OR USER FORUMS?::
The best way to contact the community enablement team is to
https://developers.openshift.com/contact[log a request in the Developer Portal].
Make sure that you select "Developer Preview" in the Reason for contact drop
down.

If you would like to ask a larger group of people for help, including
{product-title} users, engineers, and operations team members, you can ask a
question using the
https://groups.google.com/forum/#!forum/openshift[{product-title} Forums].
Make sure to use the "dev-preview" tag when creating a new post.

WHAT SHOULD I DO WHEN I FIND A BUG?::
Red Hat's Bugzilla instance can be used to
https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Online&version=3.x[log
bug reports] (Product=OpenShift Online, Version=3.x). You can find a list of
https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=ON_DEV&bug_status=ON_QA&classification=Red%20Hat&known_name=Online%20v3&list_id=5138398&product=OpenShift%20Online&query_based_on=Online%20v3&query_format=advanced&version=3.x[known
and reported issues] in Red Hat's Bugzilla instance.

HOW DO I REPORT SECURITY FLAWS?::
Red Hat's Bugzilla instance can also be used to
https://bugzilla.redhat.com/enter_bug.cgi?product=OpenShift%20Online&version=3.x&groups=security[log
security sensitive bug reports] (Product=OpenShift Online, Version=3.X,
Groups=security) by selecting the "Security Sensitive Bug" flag (automatically
selected with the provided link).

[[devpreview-current-usage-considerations]]
== Current Usage Considerations

The {product-title} (Next Gen) Developer Preview offering scopes the inventory of images
it provides out of the box with a few considerations in mind, which also apply
to any images you choose to import into your project. These conditions are
enforced via the {product-title} xref:../dev_guide/compute_resources.adoc#dev-guide-compute-resources[quotas,
limit ranges, and compute resources] systems.

* A memory limit of 2 GiB is in place for a project. The 2 GiB is spread out
across the project's pods and containers. Individual pods and containers have a
limit of 1 GiB each.
* Maximum counts are in place for pods, replication controllers, services, and
secrets (though some amount of these secrets will be needed by the system's
build and deployer service accounts).
* Any Dockerfile `VOLUME` instruction must be mounted with either a persistent
volume claim (PVC) or an emptyDir at this time.
* The project associated with a user can allocate up to two PVCs of up to 1 GiB each.
* No images that run as *root* are allowed.
* Only the Source-to-Image (S2I) build strategy is allowed for any build
configurations imported into your project.

[[devpreview-access-internal-registry]]
HOW DO I ACCESS THE INTERNAL REGISTRY?::
The internal registry can be accessed at
*_https://registry.preview.openshift.com_*. See
xref:../dev_guide/managing_images.adoc#accessing-the-internal-registry[Accessing
the Internal Registry] for more information.

[[devpreview-checking-current-usage]]
HOW DO I CHECK MY CURRENT USAGE?::
To check your project's current resource usage, you can log in to the web console
and view them from the *Settings* tab of your project's *Overview*, or use the
following CLI command:

----
$ oc describe quota <your_project_quota_object_name>
----

[[devpreview-default-memory-limits]]
WHAT ARE THE DEFAULT MEMORY LIMITS?::
As part of providing a set of templates out of the box, various publicly
accessible templates have been updated with a memory limit template parameter
with a default setting for the deployments, with the 2 GiB memory limit in mind.

You can change the defaults when instantiating any given template as you see
fit, based on the needs of the specific scenario you want to try. However, you
must keep in mind the 2 GiB overall memory limit when adjusting the settings of
your various deployments.

See xref:../dev_guide/compute_resources.adoc#dev-limit-ranges[Limit Ranges] and
xref:../architecture/core_concepts/templates.adoc#parameters[Templates:
Parameters] for more information on these concepts.
