[id="network-openshift-io"]
= network.openshift.io
ifdef::product-title[]
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:
endif::[]

toc::[]

== ClusterNetwork [network.openshift.io/v1]

Description::
  ClusterNetwork describes the cluster network. There is normally only one object of this type, named "default", which is created by the SDN network plugin based on the master configuration when the cluster is brought up for the first time.

Type::
  `object`

== EgressNetworkPolicy [network.openshift.io/v1]

Description::
  EgressNetworkPolicy describes the current egress network policy for a Namespace. When using the 'redhat/openshift-ovs-multitenant' network plugin, traffic from a pod to an IP address outside the cluster will be checked against each EgressNetworkPolicyRule in the pod's namespace's EgressNetworkPolicy, in order. If no rule matches (or no EgressNetworkPolicy is present) then the traffic will be allowed by default.

Type::
  `object`

== HostSubnet [network.openshift.io/v1]

Description::
  HostSubnet describes the container subnet network on a node. The HostSubnet object must have the same name as the Node object it corresponds to.

Type::
  `object`

== NetNamespace [network.openshift.io/v1]

Description::
  NetNamespace describes a single isolated network. When using the redhat/openshift-ovs-multitenant plugin, every Namespace will have a corresponding NetNamespace object with the same name. (When using redhat/openshift-ovs-subnet, NetNamespaces are not used.)

Type::
  `object`

