// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="template-apis"]
= Template APIs
:toc: macro
:toc-title:

toc::[]

== BrokerTemplateInstance [template.openshift.io/v1]

Description::
+
--
BrokerTemplateInstance holds the service broker-related state associated with a TemplateInstance.  BrokerTemplateInstance is part of an experimental API.

Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).
--

Type::
  `object`

== PodTemplate [v1]

Description::
+
--
PodTemplate describes a template for creating copies of a predefined pod.
--

Type::
  `object`

== Template [template.openshift.io/v1]

Description::
+
--
Template contains the inputs needed to produce a Config.

Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).
--

Type::
  `object`

== TemplateInstance [template.openshift.io/v1]

Description::
+
--
TemplateInstance requests and records the instantiation of a Template. TemplateInstance is part of an experimental API.

Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).
--

Type::
  `object`

