[[dev-guide-application-ephemeral-storage-sizing]]
= Application ephemeral storage sizing
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:

toc::[]

== Overview

_NOTE: This only applies if your administrator has enabled the ephemeral-storage tech preview in {product-title} 3.10._

This page is intended to provide guidance to application developers using
{product-title} on:

. Determining the ephemeral storage and risk requirements of a containerized application
   component and configuring the container ephemeral storage parameters to suit those
   requirements.

. Configuring containerized application runtimes (for example, OpenJDK) to adhere
   optimally to the configured container ephemeral storage parameters.

. Diagnosing and resolving ephemeral storage-related error conditions associated with
   running in a container.

== Background

It is recommended to read fully the overview of how {product-title} manages
xref:compute_resources.adoc#dev-compute-resources[Compute Resources] before
proceeding.

For the purposes of sizing application ephemeral storage, the key points are:

* For each kind of resource (memory, cpu, storage, and ephemeral storage), {product-title} allows
  optional *request* and *limit* values to be placed on each container in a
  pod. For the purposes of this page, we are solely interested in ephemeral storage
  requests and limits.

* *Ephemeral Storage request*

  - The ephemeral storage request value, if specified, influences the {product-title}
    scheduler. The scheduler considers the ephemeral storage request when scheduling a
    container to a node, then fences off the requested ephemeral storage on the chosen node
    for the use of the container.

* *Ephemeral Storage limit*

  - The ephemeral storage limit value, if specified, provides a hard limit on the ephemeral storage
    that can be allocated across all the processes in a container.

  - If both ephemeral storage request and limit are specified, the ephemeral storage limit value must
    be greater than or equal to the ephemeral storage request.

* *Administration*

  - The cluster administrator may assign quota against the ephemeral storage request value,
    limit value, both, or neither.

  - The cluster administrator may assign default values for the ephemeral storage request
    value, limit value, both, or neither.

  - The cluster administrator may override the ephemeral storage request values that a
    developer specifies, in order to manage cluster overcommit. This occurs on
    OpenShift Online, for example.

== Strategy

The steps for sizing application ephemeral storage on {product-title} are as follows:

. *Determine expected container ephemeral usage*
+ If your administrator has enabled the ephemeral-storage tech preview in {product-title} 3.10, 
determine expected mean and peak container ephemeral storage usage, empirically if
necessary (for example, by separate extended). Remember to consider all the
processes that may potentially run in parallel in the container: for example,
does the main application spawn any ancillary scripts that may require local storage for work files or logging?

. *Determine risk appetite*
+
Determine risk appetite for eviction. If the risk appetite is low, the
container should request ephemeral storage according to the expected peak usage plus a
percentage safety margin. If the risk appetite is higher, it may be more
appropriate to request ephemeral storage according to the expected mean usage.

. *Set container ephemeral storage request*
+
Set container ephemeral storage request based on the above. The more accurately the
request represents the application ephemeral storage usage, the better. If the request is
too high, cluster and quota usage will be inefficient. If the request is too
low, the chances of application eviction increase.

. *Set container ephemeral storage limits, if required*
+
Set container ephemeral storage limits, if required. Setting a limit has the effect of
immediately killing a container process if the combined ephemeral storage usage of all
processes in the container exceeds the limit, and is therefore a mixed blessing.
On the one hand, it may make unanticipated excess ephemeral storage usage obvious early
("fail fast"); on the other hand it also terminates processes abruptly.
+
Note that some {product-title} clusters may require a limit value to be set;
some may override the request based on the limit; and some application images
rely on a limit value being set as this is easier to detect than a request
value.
+
If these limits are set, they should not be set to less than the expected peak
container resource usage plus a percentage safety margin.

. *Ensure application is tuned*
+
Ensure application is tuned with respect to configured request and limit values,
if appropriate. This step is particularly relevant to applications which pool
ephemeral storage.

== Diagnosing an Evicted Pod

{product-title} may evict a pod from its node when the node’s ephemeral storage is
exhausted. Depending on the extent of ephemeral storage exhaustion, the eviction may or
may not be graceful. Graceful eviction implies the main process (PID 1) of each
container receiving a SIGTERM signal, then some time later a SIGKILL signal if
the process hasn’t exited already. Non-graceful eviction implies the main
process of each container immediately receiving a SIGKILL signal.

An evicted pod will have phase *Failed* and reason *Evicted*. It will not be
restarted, regardless of the value of `restartPolicy`. However, controllers
such as the ReplicationController will notice the pod’s failed status and create
a new pod to replace the old one.

----
$ oc get pod test
NAME      READY     STATUS    RESTARTS   AGE
test      0/1       Evicted   0          1m

$ oc get pod test -o yaml
...
status:
  message: 'Pod The node was low on resource: [DiskPressure].'
  phase: Failed
  reason: Evicted
----
