// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="authentication-apis"]
= Authentication APIs
:toc: macro
:toc-title:

toc::[]

== TokenRequest [authentication.k8s.io/v1]

Description::
+
--
TokenRequest requests a token for a given service account.
--

Type::
  `object`

== TokenReview [authentication.k8s.io/v1]

Description::
+
--
TokenReview attempts to authenticate a token to a known user. Note: TokenReview requests may be cached by the webhook token authenticator plugin in the kube-apiserver.
--

Type::
  `object`

