kind: AlertingRule
apiVersion: loki.grafana.com/v1beta1
metadata:
  name: alertingrule-sample
  namespace: openshift-operators-redhat
spec:
  groups:
    - interval: 10m
      name: alerting-rules-group
      rules:
        - alert: HighPercentageError
          annotations:
            summary: High request latency
          expr: |
            sum(rate({app="foo", env="production"} |= "error" [5m])) by (job)
              /
            sum(rate({app="foo", env="production"}[5m])) by (job)
              > 0.05
          for: 10m
          labels:
            severity: page
        - alert: HttpCredentialsLeaked
          annotations:
            message: '{{ $labels.job }} is leaking http basic auth credentials.'
          expr: >-
            sum by (cluster, job, pod) (count_over_time({namespace="prod"} |~
            "http(s?)://(\\w+):(\\w+)@" [5m]) > 0)
          for: 10m
          labels:
            severity: critical
  tenantID: test-tenant
