:context: cluster-logging-upgrading
[id="cluster-logging-upgrading"]
= Updating cluster logging
include::modules/common-attributes.adoc[]

toc::[]



After updating the {product-title} cluster from 4.4 to 4.5, you can then update the Elasticsearch Operator and Cluster Logging Operator from 4.4 to 4.5.

Cluster logging 4.5 introduces a new Elasticsearch version, Elasticsearch 6.8.1, and an enhanced security plug-in, Open Distro for Elasticsearch. The new Elasticsearch version introduces a new Elasticsearch data model. With the new data model, data is no longer indexed by type (infrastructure and application) and project. Because of these new features, you need to update your Kibana index patterns and visualizations to match the new indices after updating.

[NOTE]
====
Because of the nature of these changes, you are not required to update your cluster logging to 4.5. However, when you update to {product-title} 4.6, you *must* update cluster logging to 4.6 at that time.
====

// The following include statements pull in the module files that comprise
// the assembly. Include any combination of concept, procedure, or reference
// modules required to cover the user story. You can also include other
// assemblies.

include::modules/cluster-logging-updating-logging.adoc[leveloffset=+1]
