apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - secret:
        name: elasticsearch
      syslog:
        rfc: RFC5424
      name: remote-elasticsearch
      type: elasticsearch
      url: 'remote.example.org:9200'
  pipelines:
    - inputRefs:
        - application
        - audit
        - infrastructure
      outputRefs:
        - default
      name: enable-default-log-store
    - inputRefs:
        - application
      outputRefs:
        - remote-elasticsearch
      name: forward-to-remote
