:context: efk-logging-configuring
[id='efk-logging-image']
= Setting the cluster logging component image
include::modules/common-attributes.adoc[]


toc::[]



Each cluster logging component uses an image.

By default, cluster logging uses the following images:

* *ELASTICSEARCH_IMAGE* deploys Elasticsearch, by default `docker.io/openshift/origin-logging-elasticsearch5:latest`.
* *FLUENTD_IMAGE* deploys Fluentd, by default `docker.io/openshift/origin-logging-fluentd:latest`.
* *KIBANA_IMAGE* deploys Kibana, by default `docker.io/openshift/origin-logging-kibana5:latest`.
* *CURATOR_IMAGE* deploys Curator, by default `docker.io/openshift/origin-logging-curator5:latest`.
* *OAUTH_PROXY_IMAGE* defines OAUTH for {product-title}, by default `docker.io/openshift/oauth-proxy:latest`.
* *RSYSLOG_IMAGE* deploys Rsyslog, by default `docker.io/viaq/rsyslog:latest`.
* *WATCH_NAMESPACE* allows cluster logging to view all namespaces in the cluster, by default `openshift-logging`.
* *OPERATOR_NAME* configures cluster logging to use the Cluster Logging Operator, by default `cluster-logging-operator`.


[NOTE]
====
The Rsyslog log collector is in Technology Preview.
====

// The following include statements pull in the module files that comprise
// the assembly. Include any combination of concept, procedure, or reference
// modules required to cover the user story. You can also include other
// assemblies.


*Specific information on changing the image through a separate PR*

include::modules/efk-logging-image-configuring.adoc[leveloffset=+1]



