kind: Elasticsearch
apiVersion: logging.openshift.io/v1
metadata:
  name: elasticsearch
  namespace: openshift-operators-redhat
spec:
  indexManagement:
    mappings:
      - aliases:
          - infra
          - logs.infra
        name: infra
        policyRef: infra-policy
    policies:
      - name: infra-policy
        phases:
          delete:
            minAge: 2d
            namespaceSpec:
              - minAge: 5h
                namespace: openshift-monitoring
            pruneNamespacesInterval: 24h
          hot:
            actions:
              rollover:
                maxAge: 8h
        pollInterval: 30m
  managementState: Managed
  nodeSpec:
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
  nodes:
    - nodeCount: 1
      roles:
        - client
        - data
        - master
      storage:
        size: 20G
  redundancyPolicy: ZeroRedundancy
