kind: Kibana
apiVersion: logging.openshift.io/v1
metadata:
  name: kibana
  namespace: openshift-operators-redhat
spec:
  managementState: Managed
  nodeSelector: {}
  replicas: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
