kind: RecordingRule
apiVersion: loki.grafana.com/v1beta1
metadata:
  name: recordingrule-sample
  namespace: openshift-operators-redhat
spec:
  groups:
    - interval: 10m
      name: recording-rules-group
      rules:
        - expr: |
            sum(rate({container="myservice"}[10m]))
          record: 'myservice:requests:rate10m'
        - expr: |
            sum(rate({container="otherservice"}[1m]))
          record: 'otherservice:requests:rate1m'
  tenantID: test-tenant
