kind: RulerConfig
apiVersion: loki.grafana.com/v1beta1
metadata:
  name: rulerconfig-sample
  namespace: openshift-operators-redhat
spec:
  alertmanager:
    discovery:
      enableSRV: true
      refreshInterval: 1m
    enableV2: true
    endpoints:
      - 'http://alertmanager-host1.mycompany.org'
      - 'http://alertmanager-host2.mycompany.org'
    externalLabels:
      environment: production
      region: us-east-2
    externalUrl: 'http://www.mycompany.org/alerts'
    notificationQueue:
      capacity: 1000
      forGracePeriod: 10m
      forOutageTolerance: 1h
      resendDelay: 1m
      timeout: 30s
  evaluationInterval: 1m
  pollInterval: 1m
  remoteWrite:
    client:
      authorization: basic
      authorizationSecretName: my-secret-resource
      name: remote-write-log-metrics
      proxyUrl: 'http://proxy-host.mycompany.org'
      relabelConfigs:
        - action: replace
          regex: ALERTS.*
          replacement: $1
          separator: ''
          sourceLabels:
            - labelc
            - labeld
          targetLabel: labelnew
      timeout: 30s
      url: 'http://remote-write-host.mycompany.org'
    enabled: true
    refreshPeriod: 10s
