:_mod-docs-content-type: ASSEMBLY
[id="microshift-deleting-resource-manifests"]
= Deleting resource manifests
include::_attributes/attributes-microshift.adoc[]
:context: microshift-deleting-resource-manifests

toc::[]

{microshift-short} supports the deletion of resource manifests in the following situations:

* Manifest removal: Manifests can be removed when you need to completely remove a resource from the cluster.
* Manifest upgrade: During an application upgrade, some resources might need to be removed while others are retained to preserve data.

When creating new manifests, you can use resource manifest deletion to remove or update old objects, ensuring there are no conflicts or issues.

[IMPORTANT]
====
Manifest files placed in the `delete` subdirectories are not automatically removed and require manual deletion.
====

include::modules/microshift-manifests-deletion-overview.adoc[leveloffset=+1]

[id="microshift-examples-of-usecase_{context}"]
== Use cases for resource manifest deletion

The following explains the use case in which the resource manifest deletion is used.

include::modules/microshift-manifests-removal-scenario-rpm.adoc[leveloffset=+2]

include::modules/microshift-manifests-removal-scenario-ostree.adoc[leveloffset=+2]

include::modules/microshift-manifests-upgrade-scenario-rpm.adoc[leveloffset=+2]

include::modules/microshift-manifests-upgrade-scenario-ostree.adoc[leveloffset=+2]