[id="understanding-sandboxed-containers"]
= Understanding OpenShift sandboxed containers
include::modules/common-attributes.adoc[]

:context: understanding-sandboxed-containers

toc::[]

[role="_abstract"]

{sandboxed-containers-first} support for {product-title} provides users with built-in support for running Kata Containers as an additional optional runtime. This is particularly useful for users who are wanting to perform the following tasks:

- Run privileged or untrusted workloads.
- Ensure kernel isolation for each workload.
- Share the same workload across tenants.
- Ensure proper isolation and sandboxing for testing software.
- Ensure default resource containment through VM boundaries.

Furthermore, {sandboxed-containers-first} provide an additional option for users to choose from the type of workload they want to run to cover a wide variety of use cases.

Sandboxed containers are only supported on bare metal.

{op-system-first} is the only supported operating system for {product-title} 4.8.

include::modules/sandboxed-containers-about-sandboxing.adoc[leveloffset=+1]
include::modules/sandboxed-containers-building-blocks.adoc[leveloffset=+1]
include::modules/sandboxed-containers-os-extensions.adoc[leveloffset=+1]
include::modules/sandboxed-containers-limitations.adoc[leveloffset=+1]
