
:context: nodes-nodes-resources-configuring
[id="nodes-nodes-resources-configuring"]
= Allocating resources for nodes in an {product-title} cluster
include::modules/common-attributes.adoc[]

toc::[]


To provide more reliable scheduling and minimize node resource overcommitment,
each node can reserve a portion of its resources for use by all underlying node
components (such as kubelet, kube-proxy) and the remaining system
components (such as *sshd*, *NetworkManager*) on the host. Once specified, the
scheduler has more information about the resources (e.g., memory, CPU) a node
has allocated for pods.

// The following include statements pull in the module files that comprise
// the assembly. Include any combination of concept, procedure, or reference
// modules required to cover the user story. You can also include other
// assemblies.

include::modules/nodes-nodes-resources-configuring-about.adoc[leveloffset=+1]

include::modules/nodes-nodes-resources-configuring-setting.adoc[leveloffset=+1]

////
== Additional resources

The ephemeral storage management feature is disabled by default. To enable this
feature, 

See /install_config/configuring_ephemeral.adoc#install-config-configuring-ephemeral-storage[configuring for
ephemeral storage].

See /dev_guide/compute_resources.adoc#dev-guide-compute-resources[Compute Resources] for more
details.

#update these links when the links become available#

////
