[[device-manager]]
= Device Manager
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:

toc::[]

[[what-device-manager-does]]
== What Device Manager Does

[IMPORTANT]
====
Device Manager is a Technology Preview feature.
ifdef::openshift-enterprise[]
Technology Preview features are not supported with Red Hat production service
level agreements (SLAs), might not be functionally complete, and Red Hat does
not recommend to use them for production. These features provide early access to
upcoming product features, enabling customers to test functionality and provide
feedback during the development process.

For more information on Red Hat Technology Preview features support scope, see
https://access.redhat.com/support/offerings/techpreview/.
endif::[]
====

Device Manager is a Kubelet feature which provides a mechanism for advertising
specialized node HW resources with the help of Kubelet plugins i.e device plugins.

Any vendor can implemenent a device plugin to advertise his/her specialized
HW without requiring any upstream code changes.

Device Manager advertises devices as `Extended Resources`. User pod can consume
devices, advertised by Device Manager, using the same `Limit/Request` mechanism
which is used for requesting any other `Extended Resource`.


[[enable-device-manager]]
== How to enable Device Manager

Enable Device manager support on the target node/nodes:
----
# cat /etc/origin/node/node-config.yaml
...
kubeletArguments:
...
  feature-gates:
  - DevicePlugins=true

# systemctl restart atomic-openshift-node
----
TIP: A quick check to ensure that Device Manager has got actually enabled is to look for the
      creation of `/var/lib/kubelet/device-plugins/kubelet.sock` on the node. This is the unix domain socket
      on which Device Manager gRPC server listens for new plugin registrations and this sock file gets created on Kubelet start only if Device Manager is enabled.

[[device-plugin]]
== What is a Device Plugin
Device Plugin is a gRPC service running on the nodes (external to atomic-openshift-node.service) and is responsible for managing specific HW resources.
Any Device Plugin must support following RPCs:

[source,golang]
----
service DevicePlugin {
      // ListAndWatch returns a stream of List of Devices
      // Whenever a Device state change or a Device disappears, ListAndWatch
      // returns the new list
      rpc ListAndWatch(Empty) returns (stream ListAndWatchResponse) {}

      // Allocate is called during container creation so that the Device
      // Plugin can run device specific operations and instruct Kubelet
      // of the steps to make the Device available in the container
      rpc Allocate(AllocateRequest) returns (AllocateResponse) {}
}
----

[[registration]]
=== Registration
On start, Device Plugin registers itself with Device Manager invoking `Register` on the `/var/lib/kubelet/device-plugins/kubelet.sock` and starts a gRPC service at `/var/lib/kubelet/device-plugins/<plugin>.sock` for serving Device Manager requests.

[[device-discovery-monitoring]]
=== Device Discovery and Health Monitoring
Device Manager, while processing a new registration request, invokes `ListAndWatch` RPC at Device Plugin service. In response, Device Manger gets a list of `Device` objects from Plugin over a `gRPC stream`. Manager will keep watching on the stream for new updates from the Plugin. On the Plugin side, plugin will also keep the stream open and whenever there is a change in the state of any of the devices, a new device list is sent to the Manager over the same streaming connection.

[[device-allocation]]
=== Device Allocation
While handling a new pod admission request, Kubelet passes requested `Extended Resources` to the Device Manager for Device allocation. Device Manager checks in its database to verify if a corresponding Plugin exists or not. If Plugin exists and there are free allocatable devices as well as per local cache, `Allocate` RPC is invoked at that particular device plugin.


Additionally Device Plugins may also perform several other device specific operations as well such as driver installation, device initialization, device resets etc. These functionalities may vary from implementation to implementation. 

[[example-device-plugin]]
=== Example Device Plugins

* link:https://github.com/GoogleCloudPlatform/container-engine-accelerators/tree/master/cmd/nvidia_gpu[Nvidia GPU device plugin for COS based OS] 
* link:https://github.com/NVIDIA/k8s-device-plugin[Nvidia official GPU device plugin]
* link:https://github.com/vikaschoudhary16/sfc-device-plugin[Solarflare device plugin]
* link:https://github.com/kubevirt/kubernetes-device-plugins[KubeVirt Device Plugins: vfio and kvm]

TIP: For a simplest Device Plugin reference implementation, there is a stub device plugin in the Device Manager code, `vendor/k8s.io/pkg/kubelet/cm/deviceplugin/stub_device_plugin.go` 

[[plugin-deployment]]
== How to deploy a Device Plugin

* xref:../../dev_guide/daemonsets.adoc#dev-guide-daemonsets[Daemonsets]
is the recommended approach for device plugin deployments.
* Device Plugin on start will try to create a unix domain socket at `/var/lib/kubelet/device-plugin/` on the node to serve RPCs from Device Manager
* Since Device Plugins need to deal with HW resources and access host file system as well for socket creation, must be run in a privileged security context
* More specific details regarding deployement steps should be found with each Device Plugin implementation.


