== Design on Masters

On an {product-title} master, OpenShift SDN maintains a registry of nodes,
stored in *etcd*. When the system administrator registers a node,
OpenShift SDN allocates an unused subnet from the cluster network and
stores this subnet in the registry. When a node is deleted, OpenShift SDN
deletes the subnet from the registry and considers the subnet available to be
allocated again.

In the default configuration, the cluster network is the *10.128.0.0/14* network
(i.e. *10.128.0.0* - *10.131.255.255*), and nodes are allocated */23* subnets
(i.e., *10.128.0.0/23*, *10.128.2.0/23*, *10.128.4.0/23*, and so on). This means
that the cluster network has 512 subnets available to assign to nodes, and a
given node is allocated 510 addresses that it can assign to the containers
running on it. The size and address range of the cluster network are
configurable, as is the host subnet size.

[NOTE]
====
If the subnet extends into the next higher octet, it is rotated so that the
subnet bits with 0s in the shared octet are allocated first. For example, if the
network is 10.1.0.0/16, with `hostsubnetlength=6`, then the subnet of
10.1.0.0/26 and 10.1.1.0/26, through to 10.1.255.0/26 are allocated before
10.1.0.64/26, 10.1.1.64/26 are filled. This ensures that the subnet is easier to
follow.
====

Note that the OpenShift SDN on a master does not configure the local (master)
host to have access to any cluster network. Consequently, a master host does not
have access to pods via the cluster network, unless it is also running as a
node.

When using the *ovs-multitenant* plug-in, the OpenShift SDN master also
watches for the creation and deletion of projects, and assigns VXLAN VNIDs to
them, which are later used by the nodes to isolate traffic correctly.