[id="imagecontentsourcepolicy-operator-openshift-io-v1alpha1"]
= ImageContentSourcePolicy [operator.openshift.io/v1alpha1]
ifdef::product-title[]
include::modules/common-attributes.adoc[]
endif::[]

toc::[]


Description::
  ImageContentSourcePolicy holds cluster-wide information about how to handle registry mirror rules. When multiple policies are defined, the outcome of the behavior is defined on each field.

Type::
  `object`

Required::
  - `spec`


== Specification

[cols="1,1,1",options="header"]
|===
| Property | Type | Description

| `.apiVersion`
| `string`
| APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

| `.kind`
| `string`
| Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

| `.metadata`
| xref:../objects/index.adoc#objectmeta-meta-v1[`ObjectMeta meta/v1`]
| Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata

| `.spec`
| `object`
| spec holds user settable values for configuration

|===
..spec
Description::
  spec holds user settable values for configuration

Type::
  `object`




[cols="1,1,1",options="header"]
|===
| Property | Type | Description

| `repositoryDigestMirrors`
| `array`
| repositoryDigestMirrors allows images referenced by image digests in pods to be pulled from alternative mirrored repository locations. The image pull specification provided to the pod will be compared to the source locations described in RepositoryDigestMirrors and the image may be pulled down from any of the mirrors in the list instead of the specified repository allowing administrators to choose a potentially faster mirror. Only image pull specifications that have an image disgest will have this behavior applied to them - tags will continue to be pulled from the specified repository in the pull spec. 
 Each “source” repository is treated independently; configurations for different “source” repositories don’t interact. 
 When multiple policies are defined for the same “source” repository, the sets of defined mirrors will be merged together, preserving the relative order of the mirrors, if possible. For example, if policy A has mirrors `a, b, c` and policy B has mirrors `c, d, e`, the mirrors will be used in the order `a, b, c, d, e`.  If the orders of mirror entries conflict (e.g. `a, b` vs. `b, a`) the configuration is not rejected but the resulting order is unspecified.

| `repositoryDigestMirrors[]`
| `object`
| RepositoryDigestMirrors holds cluster-wide information about how to handle mirros in the registries config. Note: the mirrors only work when pulling the images that are referenced by their digests.

|===
..spec.repositoryDigestMirrors
Description::
  repositoryDigestMirrors allows images referenced by image digests in pods to be pulled from alternative mirrored repository locations. The image pull specification provided to the pod will be compared to the source locations described in RepositoryDigestMirrors and the image may be pulled down from any of the mirrors in the list instead of the specified repository allowing administrators to choose a potentially faster mirror. Only image pull specifications that have an image disgest will have this behavior applied to them - tags will continue to be pulled from the specified repository in the pull spec. 
 Each “source” repository is treated independently; configurations for different “source” repositories don’t interact. 
 When multiple policies are defined for the same “source” repository, the sets of defined mirrors will be merged together, preserving the relative order of the mirrors, if possible. For example, if policy A has mirrors &#x60;a, b, c&#x60; and policy B has mirrors &#x60;c, d, e&#x60;, the mirrors will be used in the order &#x60;a, b, c, d, e&#x60;.  If the orders of mirror entries conflict (e.g. &#x60;a, b&#x60; vs. &#x60;b, a&#x60;) the configuration is not rejected but the resulting order is unspecified.

Type::
  `array`




..spec.repositoryDigestMirrors[]
Description::
  RepositoryDigestMirrors holds cluster-wide information about how to handle mirros in the registries config. Note: the mirrors only work when pulling the images that are referenced by their digests.

Type::
  `object`

Required::
  - `source`



[cols="1,1,1",options="header"]
|===
| Property | Type | Description

| `mirrors`
| `array (string)`
| mirrors is one or more repositories that may also contain the same images. The order of mirrors in this list is treated as the user's desired priority, while source is by default considered lower priority than all mirrors. Other cluster configuration, including (but not limited to) other repositoryDigestMirrors objects, may impact the exact order mirrors are contacted in, or some mirrors may be contacted in parallel, so this should be considered a preference rather than a guarantee of ordering.

| `source`
| `string`
| source is the repository that users refer to, e.g. in image pull specifications.

|===
