[id="operator-apis"]
= Operator APIs
ifdef::product-title[]
include::modules/common-attributes.adoc[]
endif::[]

toc::[]

== Authentication [operator.openshift.io/v1]

Description::
  Authentication provides information to configure an operator to manage authentication.

Type::
  `object`

== CloudCredential [operator.openshift.io/v1]

Description::
  CloudCredential provides a means to configure an operator to manage CredentialsRequests.

Type::
  `object`

== ClusterCSIDriver [operator.openshift.io/v1]

Description::
  ClusterCSIDriver object allows management and configuration of a CSI driver operator installed by default in OpenShift. Name of the object must be name of the CSI driver it operates. See CSIDriverName type for list of allowed values.

Type::
  `object`

== Console [operator.openshift.io/v1]

Description::
  Console provides a means to configure an operator to manage the console.

Type::
  `object`

== Config [operator.openshift.io/v1]

Description::
  Config provides information to configure the config operator.

Type::
  `object`

== Config [imageregistry.operator.openshift.io/v1]

Description::
  Config is the configuration object for a registry instance managed by the registry operator

Type::
  `object`

== Config [samples.operator.openshift.io/v1]

Description::
  Config contains the configuration and detailed condition status for the Samples Operator.

Type::
  `object`

== CSISnapshotController [operator.openshift.io/v1]

Description::
  CSISnapshotController provides a means to configure an operator to manage the CSI snapshots. `cluster` is the canonical name.

Type::
  `object`

== DNS [operator.openshift.io/v1]

Description::
  DNS manages the CoreDNS component to provide a name resolution service for pods and services in the cluster. 
 This supports the DNS-based service discovery specification: https://github.com/kubernetes/dns/blob/master/docs/specification.md 
 More details: https://kubernetes.io/docs/tasks/administer-cluster/coredns

Type::
  `object`

== DNSRecord [ingress.operator.openshift.io/v1]

Description::
  DNSRecord is a DNS record managed in the zones defined by dns.config.openshift.io/cluster .spec.publicZone and .spec.privateZone. 
 Cluster admin manipulation of this resource is not supported. This resource is only for internal communication of OpenShift operators.

Type::
  `object`

== Etcd [operator.openshift.io/v1]

Description::
  Etcd provides information to configure an operator to manage kube-apiserver.

Type::
  `object`

== ImageContentSourcePolicy [operator.openshift.io/v1alpha1]

Description::
  ImageContentSourcePolicy holds cluster-wide information about how to handle registry mirror rules. When multiple policies are defined, the outcome of the behavior is defined on each field.

Type::
  `object`

== ImagePruner [imageregistry.operator.openshift.io/v1]

Description::
  ImagePruner is the configuration object for an image registry pruner managed by the registry operator.

Type::
  `object`

== IngressController [operator.openshift.io/v1]

Description::
  IngressController describes a managed ingress controller for the cluster. The controller can service OpenShift Route and Kubernetes Ingress resources. 
 When an IngressController is created, a new ingress controller deployment is created to allow external traffic to reach the services that expose Ingress or Route resources. Updating this resource may lead to disruption for public facing network connections as a new ingress controller revision may be rolled out. 
 https://kubernetes.io/docs/concepts/services-networking/ingress-controllers 
 Whenever possible, sensible defaults for the platform are used. See each field for more details.

Type::
  `object`

== KubeAPIServer [operator.openshift.io/v1]

Description::
  KubeAPIServer provides information to configure an operator to manage kube-apiserver.

Type::
  `object`

== KubeControllerManager [operator.openshift.io/v1]

Description::
  KubeControllerManager provides information to configure an operator to manage kube-controller-manager.

Type::
  `object`

== KubeScheduler [operator.openshift.io/v1]

Description::
  KubeScheduler provides information to configure an operator to manage scheduler.

Type::
  `object`

== KubeStorageVersionMigrator [operator.openshift.io/v1]

Description::
  KubeStorageVersionMigrator provides information to configure an operator to manage kube-storage-version-migrator.

Type::
  `object`

== Network [operator.openshift.io/v1]

Description::
  Network describes the cluster's desired network configuration. It is consumed by the cluster-network-operator.

Type::
  `object`

== OpenShiftAPIServer [operator.openshift.io/v1]

Description::
  OpenShiftAPIServer provides information to configure an operator to manage openshift-apiserver.

Type::
  `object`

== OpenShiftControllerManager [operator.openshift.io/v1]

Description::
  OpenShiftControllerManager provides information to configure an operator to manage openshift-controller-manager.

Type::
  `object`

== OperatorPKI [network.operator.openshift.io/v1]

Description::
  OperatorPKI is a simple certificate authority. It is not intended for external use - rather, it is internal to the network operator. The CNO creates a CA and a certificate signed by that CA. The certificate has both ClientAuth and ServerAuth extended usages enabled. 
  More specifically, given an OperatorPKI with <name>, the CNO will manage: - A Secret called <name>-ca with two data keys:   - tls.key - the private key   - tls.crt - the CA certificate - A ConfigMap called <name>-ca with a single data key:   - cabundle.crt - the CA certificate(s) - A Secret called <name>-cert with two data keys:   - tls.key - the private key   - tls.crt - the certificate, signed by the CA 
 The CA certificate will have a validity of 10 years, rotated after 9. The target certificate will have a validity of 6 months, rotated after 3 
 The CA certificate will have a CommonName of "<namespace>_<name>-ca@<timestamp>", where <timestamp> is the last rotation time.

Type::
  `object`

== ServiceCA [operator.openshift.io/v1]

Description::
  ServiceCA provides information to configure an operator to manage the service cert controllers

Type::
  `object`

== Storage [operator.openshift.io/v1]

Description::
  Storage provides a means to configure an operator to manage the cluster storage operator. `cluster` is the canonical name.

Type::
  `object`

