// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="flow-control-apis"]
= Flow Control APIs
:toc: macro
:toc-title:

toc::[]

== FlowSchema [flowcontrol.apiserver.k8s.io/v1beta3]

Description::
+
--
FlowSchema defines the schema of a group of flows. Note that a flow is made up of a set of inbound API requests with similar attributes and is identified by a pair of strings: the name of the FlowSchema and a "flow distinguisher".
--

Type::
  `object`

== PriorityLevelConfiguration [flowcontrol.apiserver.k8s.io/v1beta3]

Description::
+
--
PriorityLevelConfiguration represents the configuration of a priority level.
--

Type::
  `object`

