= Ruby
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:

toc::[]

== Overview
Our OpenShift https://github.com/openshift/sti-ruby/tree/master/2.0[Ruby] image repository contains the sources and Dockerfiles for building various versions of Ruby platform images. The resulting images can be run either by Docker or using https://github.com/openshift/source-to-image[STI].

== Versions
Current supported versions of Ruby:

* https://github.com/openshift/sti-ruby/tree/master/2.0[2.0]

== Base Images

* RHEL-7
* CentOS-7

[NOTE]
====
RHEL-7 image is not available as trusted build in https://index.docker.io[Docker Index]. In order to perform build or test action on a RHEL-7 based Ruby image, you need to run the build on properly subscribed RHEL-7 machine.
====

== Installation
To build Ruby image, choose between CentOS7 or RHEL7 base image:

=== RHEL-7 base image

----
$ git clone https://github.com/openshift/sti-ruby.git
$ cd sti-ruby
$ make build TARGET=rhel7 VERSION=2.0
----

=== CentOS-7 base image

----
$ git clone https://github.com/openshift/sti-ruby.git
$ cd sti-ruby
$ make build VERSION=2.0
----

[NOTE]
====
By omitting the `VERSION` parameter, the build/test action will be performed on all the supported versions of Ruby. Since we are now supporting only version `2.0`, you can omit this parameter
====

== Usage
Building simple https://github.com/openshift/sti-ruby/tree/master/2.0/test/test-app[ruby-sample-app] application, using standalone https://github.com/openshift/source-to-image[STI] and running the resulting image by http://docker.io[Docker]

=== RHEL-7 base image

----
$ sti build https://github.com/openshift/sti-ruby.git --contextDir=/2.0/test/test-app/ openshift/ruby-20-rhel7 ruby-sample-app
$ docker run -p 9292:9292 ruby-sample-app
----

=== CentOS-7 base image

----
$ sti build https://github.com/openshift/sti-ruby.git --contextDir=/2.0/test/test-app/ openshift/ruby-20-centos7 ruby-sample-app
$ docker run -p 9292:9292 ruby-sample-app
----

To access and test if the application is running run:
----
$ curl 127.0.0.1:9292
----

== Test
OpenShift https://github.com/openshift/sti-ruby/tree/master/2.0[STI-Ruby] repository also provides STI test framework, which launches test to check functionality of a simple ruby application built on top of sti-ruby image.

=== RHEL-7 base image

----
$ cd sti-ruby
$ make test TARGET=rhel7 VERSION=2.0
----

=== CentOS-7 base image

----
$ cd sti-ruby
$ make test VERSION=2.0
----

[NOTE]
====
By omitting the `VERSION` parameter, the build/test action will be performed on all the supported versions of Ruby. Since we are now supporting only version `2.0`, you can omit this parameter
====

== Repository organization

* `/ruby-version/`
** `Dockerfile` - CentOS7 based Dockerfile.
** `Dockerfile.rhel7` - RHEL7 based Dockerfile.
** `.sti/bin/` - This folder contains scripts that are run by https://github.com/openshift/source-to-image[STI]:
*** `assemble` - Is used to install the sources into location from where the application  will be run and prepare the application for deployment (eg. installing modules using npm, etc..).
*** `run` - This script is responsible for running the application, by using the application web server.
** `ruby/` - This folder contains file with commonly used modules.
** `test/` - This folder is containing STI test framework with simple Rack server echo server.
*** `test-app/` - Simple Rack server used for testing purposes in the STI test framework.
*** `run` - Script that runs the STI test framework.
* `hack/` - Folder contains scripts which are responsible for build and test actions performed by the `Makefile`.
* `Makefile` - Make utility for simplifying image build and test actions.

== Image name structure

*Structure: `openshift/<platform_name>-<platform_version>-<base_builder_image>`*

. Platform_name - Refers to the STI platform; `ruby` is one example
. Platform_version - The version of the referenced platform, without dots (like `20` for Ruby 2.0)
. Base_builder_image - The base OS, like `rhel7` or `centos7`

Examples: 

* openshift/ruby-20-centos7
* openshift/ruby-20-rhel7

== Environment variables

* *RACK_ENV* - This variable specifies in what environment should the ruby application be deployed - `production`, `development`, `test`. Each level has different behavior in terms of logging verbosity, error pages, ruby gem installation, etc.
** *Note* : The application assets are going to be compiled only if the RACK_ENV is set to production

* *RAILS_ENV* - This variable specifies in what environment should the Ruby on Rails application be deployed - `production`, `development`, `test`. Each level has different behavior in terms of logging verbosity, error pages, ruby gem installation, etc.
** *Note* : The application assets are going to be compiled only if the RAILS_ENV is set to production

* *DISABLE_ASSET_COMPILATION* - This variable indicates that the process of asset compilation will be skipped. Since the process of asset compilation takes place only when the application runs in production environment, it should be used when assets are already compiled.
