// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="autoscale-apis"]
= Autoscale APIs
:toc: macro
:toc-title:

toc::[]

== ClusterAutoscaler [autoscaling.openshift.io/v1]

Description::
+
--
ClusterAutoscaler is the Schema for the clusterautoscalers API
--

Type::
  `object`

== MachineAutoscaler [autoscaling.openshift.io/v1beta1]

Description::
+
--
MachineAutoscaler is the Schema for the machineautoscalers API
--

Type::
  `object`

== HorizontalPodAutoscaler [autoscaling/v2]

Description::
+
--
HorizontalPodAutoscaler is the configuration for a horizontal pod autoscaler, which automatically manages the replica count of any resource implementing the scale subresource based on the metrics specified.
--

Type::
  `object`

== Scale [autoscaling/v1]

Description::
+
--
Scale represents a scaling request for a resource.
--

Type::
  `object`

