:_mod-docs-content-type: ASSEMBLY
[id="exposing-binding-data-from-a-service"]
= Exposing binding data from a service
include::_attributes/common-attributes.adoc[]
include::_attributes/servicebinding-document-attributes.adoc[]
:context: exposing-binding-data-from-a-service

toc::[]

[role="_abstract"]
Application developers need access to backing services to build and connect workloads. Connecting workloads to backing services is always a challenge because each service provider requires a different way to access their secrets and consume them in a workload.

The {servicebinding-title} enables application developers to easily bind workloads together with operator-managed backing services, without any manual procedures to configure the binding connection. For the {servicebinding-title} to provide the binding data, as an Operator provider or user who creates backing services, you must expose the binding data to be automatically detected by the {servicebinding-title}. Then, the {servicebinding-title} automatically collects the binding data from the backing service and shares it with a workload to provide a consistent and predictable experience.

include::modules/sbo-methods-of-exposing-binding-data.adoc[leveloffset=+1]
include::modules/sbo-data-model.adoc[leveloffset=+1]
include::modules/sbo-setting-annotations-mapping-optional.adoc[leveloffset=+1]
include::modules/sbo-rbac-requirements.adoc[leveloffset=+1]
include::modules/sbo-categories-of-exposable-binding-data.adoc[leveloffset=+1]

[role="_additional-resources"]
[id="additional-resources_exposing-binding-data"]
== Additional resources
// * link:https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md[OLM Descriptor Reference].
// When OLM descriptors are supported again, add this additional resource.
ifndef::openshift-rosa,openshift-dedicated[]
* xref:../../operators/operator_sdk/osdk-generating-csvs.adoc#osdk-generating-csvs[Defining cluster service versions (CSVs)].
endif::openshift-rosa,openshift-dedicated[]
* xref:../../applications/connecting_applications_to_services/projecting-binding-data.adoc#projecting-binding-data[Projecting binding data].
