:_mod-docs-content-type: ASSEMBLY
[id="monitoring-argo-cd-custom-resource-workloads"]
= Monitoring Argo CD custom resource workloads
include::_attributes/common-attributes.adoc[]
:context: monitoring-argo-cd-custom-resource-workloads

toc::[]

[role="_abstract"]
With {gitops-title}, you can monitor the availability of Argo CD custom resource workloads for specific Argo CD instances. By monitoring Argo CD custom resource workloads, you have the latest information about the state of your Argo CD instances by enabling alerts for them. When the component workload pods such as application-controller, repo-server, or server of the corresponding Argo CD instance are unable to come up for certain reasons and there is a drift between the number of ready replicas and the number of desired replicas for a certain period of time, the Operator then triggers the alerts.

You can enable and disable the setting for monitoring Argo CD custom resource workloads.

// Prerequisites for monitoring Argo CD custom resource workloads
[discrete]
== Prerequisites

* You have access to the cluster as a user with the `cluster-admin` role.
* {gitops-title} is installed in your cluster.
* The monitoring stack is configured in your cluster in the `openshift-monitoring` project. In addition, the Argo CD instance is in a namespace that you can monitor through Prometheus.
* The `kube-state-metrics` service is running in your cluster.
* Optional: If you are enabling monitoring for an Argo CD instance already present in a user-defined project, ensure that the monitoring is xref:../../observability/monitoring/enabling-monitoring-for-user-defined-projects.adoc#enabling-monitoring-for-user-defined-projects_enabling-monitoring-for-user-defined-projects[enabled for user-defined projects] in your cluster.
+
[NOTE]
====
If you want to enable monitoring for an Argo CD instance in a namespace that is not watched by the default `openshift-monitoring` stack, for example, any namespace that does not start with `openshift-*`, then you must enable user workload monitoring in your cluster. This action enables the monitoring stack to pick up the created PrometheusRule.
====

//Enabling Monitoring for Argo CD custom resource workloads
include::modules/gitops-enabling-monitoring-for-argo-cd-custom-resource-workloads.adoc[leveloffset=+1]

//Disabling Monitoring for Argo CD custom resource workloads
include::modules/gitops-disabling-monitoring-for-argo-cd-custom-resource-workloads.adoc[leveloffset=+1]

[role="_additional-resources"]
[id="additional-resources_monitoring-argo-cd-custom-resource-workloads"]
== Additional resources
* xref:../../observability/monitoring/enabling-monitoring-for-user-defined-projects.adoc#enabling-monitoring-for-user-defined-projects[Enabling monitoring for user-defined projects]
