// Module included in the following assemblies:
// * service_mesh/v2x/upgrading-ossm.adoc

:_mod-docs-content-type: REFERENCE
[id="ossm-upgrade-known-issues_{context}"]
= Known issues that may affect upgrade

Known issues that may affect your upgrade include:

* When upgrading an Operator, custom configurations for Jaeger or Kiali might be reverted. Before upgrading an Operator, note any custom configuration settings for the Jaeger or Kiali objects in the {SMProductShortName} production deployment so that you can recreate them.

* {SMProductName} does not support the use of `EnvoyFilter` configuration except where explicitly documented. This is due to tight coupling with the underlying Envoy APIs, meaning that backward compatibility cannot be maintained. If you are using Envoy Filters, and the configuration generated by Istio has changed due to the lastest version of Envoy introduced by upgrading your `ServiceMeshControlPlane`, that has the potential to break any `EnvoyFilter` you may have implemented.

* https://issues.redhat.com/browse/OSSM-1505[OSSM-1505] `ServiceMeshExtension` does not work with {product-title} version 4.11. Because `ServiceMeshExtension` has been deprecated in {SMProductName} 2.2, this known issue will not be fixed and you must migrate your extensions to `WasmPluging`

* https://issues.redhat.com/browse/OSSM-1396[OSSM-1396] If a gateway resource contains the `spec.externalIPs` setting, rather than being recreated when the `ServiceMeshControlPlane` is updated, the gateway is removed and never recreated.

//Keep OSSM-1052 in RN - Closed as documented.
* https://issues.redhat.com/browse/OSSM-1052[OSSM-1052] When configuring a Service `ExternalIP` for the ingressgateway in the {SMProductShortName} control plane, the service is not created. The schema for the SMCP is missing the parameter for the service.
+
Workaround: Disable the gateway creation in the SMCP spec and manage the gateway deployment entirely manually (including Service, Role and RoleBinding).
