// Module included in the following assemblies:
//
// * observability/logging/cluster-logging-support.adoc

[id="cluster-logging-maintenance-support-list_{context}"]
= Unsupported configurations

You must set the Red{nbsp}Hat OpenShift Logging Operator to the `Unmanaged` state to modify the following components:

* The `Elasticsearch` custom resource (CR)

* The Kibana deployment

* The `fluent.conf` file

* The Fluentd daemon set

You must set the OpenShift Elasticsearch Operator to the `Unmanaged` state to modify the Elasticsearch deployment files.

Explicitly unsupported cases include:

* *Configuring default log rotation*. You cannot modify the default log rotation configuration.

* *Configuring the collected log location*. You cannot change the location of the log collector output file, which by default is `/var/log/fluentd/fluentd.log`.

* *Throttling log collection*. You cannot throttle down the rate at which the logs are read in by the log collector.

* *Configuring the logging collector using environment variables*. You cannot use environment variables to modify the log collector.

* *Configuring how the log collector normalizes logs*. You cannot modify default log normalization.
