:_mod-docs-content-type: ASSEMBLY
[id="olm-deleting-operators-from-a-cluster"]
= Deleting Operators from a cluster
include::../includes/common-attributes.adoc[]
:context: olm-deleting-operators-from-a-cluster


The following describes how to delete, or uninstall, Operators that were previously installed using Operator Lifecycle Manager (OLM) on your {product-title} cluster.

[IMPORTANT]
====
You must successfully and completely uninstall an Operator prior to attempting to reinstall the same Operator. Failure to fully uninstall the Operator properly can leave resources, such as a project or namespace, stuck in a "Terminating" state and cause "error resolving resource" messages to be observed when trying to reinstall the Operator.

ifndef::openshift-dedicated,openshift-rosa[]
For more information, see xref:../../operators/admin/olm-troubleshooting-operator-issues.adoc#olm-reinstall_olm-troubleshooting-operator-issues[Reinstalling Operators after failed uninstallation].
endif::openshift-dedicated,openshift-rosa[]
====

include::../includes/olm-deleting-operators-from-a-cluster-using-web-console.adoc[leveloffset=+1]
include::../includes/olm-deleting-operators-from-a-cluster-using-cli.adoc[leveloffset=+1]
include::../includes/olm-refresh-subs.adoc[leveloffset=+1]
