:_mod-docs-content-type: ASSEMBLY
[id="virt-configuring-storage-profile"]
= Configuring storage profiles
include::../includes/common-attributes.adoc[]
:context: virt-configuring-storage-profile


A storage profile provides recommended storage settings based on the associated storage class. A storage profile is allocated for each storage class.

If the Containerized Data Importer (CDI) does not recognize your storage provider, you must configure storage profiles.

For recognized storage types, CDI provides values that optimize the creation of PVCs.  However, you can configure automatic settings for a storage class if you customize the storage profile.

ifndef::openshift-rosa,openshift-dedicated[]
[IMPORTANT]
====
When using {VirtProductName} with {rh-storage-first}, specify RBD block mode persistent volume claims (PVCs) when creating virtual machine disks. RBD block mode volumes are more efficient and provide better performance than Ceph FS or RBD filesystem-mode PVCs.

To specify RBD block mode PVCs, use the 'ocs-storagecluster-ceph-rbd' storage class and `VolumeMode: Block`.
====
endif::openshift-rosa,openshift-dedicated[]

include::../includes/virt-customizing-storage-profile.adoc[leveloffset=+1]
