// Module included in the following assemblies:
// * service_mesh/v2x/upgrading-ossm.adoc

[id="ossm-upgrade-considerations_{context}"]
= Upgrade considerations

The `maistra.io/` label or annotation should not be used on a user-created custom resource, because it indicates that the resource was generated by and should be managed by the {SMProductName} Operator.

[WARNING]
====
During the upgrade, the Operator makes changes, including deleting or replacing files, to resources that include the following labels or annotations that indicate that the resource is managed by the Operator.
====

Before upgrading check for user-created custom resources that include the following labels or annotations:

* `maistra.io/` AND the `app.kubernetes.io/managed-by` label set to `maistra-istio-operator` ({SMProductName})

* `kiali.io/` (Kiali)

* `jaegertracing.io/` ({JaegerName})

* `logging.openshift.io/` (Red Hat Elasticsearch)

Before upgrading, check your user-created custom resources for labels or annotations that indicate they are Operator managed. Remove the label or annotation from custom resources that you do not want to be managed by the Operator.

When upgrading to version 2.0, the Operator only deletes resources with these labels in the same namespace as the SMCP.

When upgrading to version 2.1, the Operator deletes resources with these labels in all namespaces.
