:_mod-docs-content-type: ASSEMBLY
[id="virt-creating-vms-from-rh-images-overview"]
= Creating virtual machines from Red Hat images overview
include::../../includes/common-attributes.adoc[]
:context: virt-creating-vms-from-rh-images-overview


Red Hat images are xref:virt-about-golden-images_virt-creating-vms-from-rh-images-overview[golden images]. They are published as container disks in a secure registry. The Containerized Data Importer (CDI) polls and imports the container disks into your cluster and stores them in the `openshift-virtualization-os-images` project as snapshots or persistent volume claims (PVCs).

Red Hat images are automatically updated. You can disable and re-enable automatic updates for these images. See xref:managing-rh-boot-source-updates_virt-automatic-bootsource-updates[Managing Red Hat boot source updates].

Cluster administrators can enable automatic subscription for {op-system-base-full} virtual machines in the {VirtProductName} xref:overview-settings-cluster_virt-web-console-overview[web console].

You can create virtual machines (VMs) from operating system images provided by Red Hat by using one of the following methods:

* xref:virt-creating-vms-from-templates[Creating a VM from a template by using the web console]

* xref:virt-creating-vms-from-instance-types[Creating a VM from an instance type by using the web console]

* xref:virt-creating-vms-from-cli[Creating a VM from a `VirtualMachine` manifest by using the command line]

[IMPORTANT]
====
Do not create VMs in the default `openshift-*` namespaces. Instead, create a new namespace or use an existing namespace without the `openshift` prefix.
====

include::../../includes/virt-golden-images.adoc[leveloffset=+1]

include::../../includes/virt-about-vms-and-boot-sources.adoc[leveloffset=+1]
