:_mod-docs-content-type: ASSEMBLY
[id="virt-backup-restore-snapshots"]
= Backup and restore by using VM snapshots
include::../includes/common-attributes.adoc[]
:context: virt-backup-restore-snapshots


You can back up and restore virtual machines (VMs) by using snapshots. Snapshots are supported by the following storage providers:

// Hiding in ROSA/OSD as not supported
ifndef::openshift-rosa,openshift-dedicated[]
* {rh-storage-first}
* Any other cloud storage provider with the Container Storage Interface (CSI) driver that supports the Kubernetes Volume Snapshot API
endif::openshift-rosa,openshift-dedicated[]
ifdef::openshift-rosa,openshift-dedicated[]
* Any cloud storage provider with the Container Storage Interface (CSI) driver that supports the Kubernetes Volume Snapshot API
endif::openshift-rosa,openshift-dedicated[]

Online snapshots have a default time deadline of five minutes (`5m`) that can be changed, if needed.

[IMPORTANT]
====
Online snapshots are supported for virtual machines that have hot plugged virtual disks. However, hot plugged disks that are not in the virtual machine specification are not included in the snapshot.
====

To create snapshots of an online (Running state) VM with the highest integrity, install the QEMU guest agent if it is not included with your operating system. The QEMU guest agent is included with the default Red Hat templates.

The QEMU guest agent takes a consistent snapshot by attempting to quiesce the VM file system as much as possible, depending on the system workload. This ensures that in-flight I/O is written to the disk before the snapshot is taken. If the guest agent is not present, quiescing is not possible and a best-effort snapshot is taken. The conditions under which the snapshot was taken are reflected in the snapshot indications that are displayed in the web console or CLI.

include::../includes/virt-about-vm-snapshots.adoc[leveloffset=+1]

[id="creating-snapshots_virt-backup-restore-snapshots"]
== Creating snapshots

You can create snapshots of virtual machines (VMs) by using the {product-title} web console or the command line.

include::../includes/virt-creating-vm-snapshot-web.adoc[leveloffset=+2]

include::../includes/virt-creating-vm-snapshot-cli.adoc[leveloffset=+2]

include::../includes/virt-verifying-online-snapshot-creation-with-snapshot-indications.adoc[leveloffset=+1]

[id="restoring-vms-from-snapshots_virt-backup-restore-snapshots"]
== Restoring virtual machines from snapshots

You can restore virtual machines (VMs) from snapshots by using the {product-title} web console or the command line.

include::../includes/virt-restoring-vm-from-snapshot-web.adoc[leveloffset=+2]

include::../includes/virt-restoring-vm-from-snapshot-cli.adoc[leveloffset=+2]

[id="deleting-snapshots_virt-backup-restore-snapshots"]
== Deleting snapshots

You can delete snapshots of virtual machines (VMs) by using the {product-title} web console or the command line.

include::../includes/virt-deleting-vm-snapshot-web.adoc[leveloffset=+2]

include::../includes/virt-deleting-vm-snapshot-cli.adoc[leveloffset=+2]

// Hiding in ROSA/OSD as not supported
ifndef::openshift-rosa,openshift-dedicated[]
[role="_additional-resources-snapshots"]
== Additional resources

* xref:../../storage/container_storage_interface/persistent-storage-csi-snapshots.adoc#persistent-storage-csi-snapshots[CSI Volume Snapshots]
endif::openshift-rosa,openshift-dedicated[]
