// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="autoscaling-apis"]
= Autoscaling APIs
:toc: macro
:toc-title:

toc::[]

== Scale [autoscaling/v1]

Description::
+
--
Scale represents a scaling request for a resource.
--

Type::
  `object`

== HorizontalPodAutoscaler [autoscaling/v2]

Description::
+
--
HorizontalPodAutoscaler is the configuration for a horizontal pod autoscaler, which automatically manages the replica count of any resource implementing the scale subresource based on the metrics specified.
--

Type::
  `object`

