// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="api-extensions-apis"]
= API Extensions APIs
:toc: macro
:toc-title:

toc::[]

== CustomResourceDefinition [apiextensions.k8s.io/v1]

Description::
+
--
CustomResourceDefinition represents a resource that should be exposed on the API server.  Its name MUST be in the format <.spec.name>.<.spec.group>.
--

Type::
  `object`

