// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="storage-version-migration-apis"]
= Storage Version Migration APIs
:toc: macro
:toc-title:

toc::[]

== StorageVersionMigration [migration.k8s.io/v1alpha1]

Description::
+
--
StorageVersionMigration represents a migration of stored data to the latest storage version.
--

Type::
  `object`

