// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="topolvm-apis"]
= TopoLVM APIs
:toc: macro
:toc-title:

toc::[]

== LogicalVolume [topolvm.io/v1]

Description::
+
--
LogicalVolume is the Schema for the logicalvolumes API
--

Type::
  `object`

