// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="discovery-apis"]
= Discovery APIs
:toc: macro
:toc-title:

toc::[]

== EndpointSlice [discovery.k8s.io/v1]

Description::
+
--
EndpointSlice represents a subset of the endpoints that implement a service. For a given service there may be multiple EndpointSlice objects, selected by labels, which must be joined to produce the full set of endpoints.
--

Type::
  `object`

