// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="coordination-apis"]
= Coordination APIs
:toc: macro
:toc-title:

toc::[]

== Lease [coordination.k8s.io/v1]

Description::
+
--
Lease defines a lease concept.
--

Type::
  `object`

