// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="api-registration-apis"]
= API Registration APIs
:toc: macro
:toc-title:

toc::[]

== APIService [apiregistration.k8s.io/v1]

Description::
+
--
APIService represents a server for a particular GroupVersion. Name must be "version.group".
--

Type::
  `object`

