:_mod-docs-content-type: ASSEMBLY
[id="power-monitoring-release-notes"]
include::_attributes/common-attributes.adoc[]
= {PM-title-c} release notes
:context: power-monitoring-release-notes

toc::[]

:FeatureName: Power monitoring
include::snippets/technology-preview.adoc[leveloffset=+2]

{PM-title-c} enables you to monitor the power usage of workloads and identify the most power-consuming namespaces running in an {product-title} cluster with key power consumption metrics, such as CPU or DRAM, measured at container level.

These release notes track the development of {PM-title} in the {product-title}.

For an overview of the {PM-operator}, see xref:../power_monitoring/power-monitoring-overview.adoc#power-monitoring-about-power-monitoring_power-monitoring-overview[About {PM-shortname}].

[id="power-monitoring-release-notes-0-1"]
== {PM-shortname-c} 0.1 (Technology Preview)

This release introduces a Technology Preview version of {PM-title}. The following advisory is available for {PM-shortname} 0.1:

* link:https://access.redhat.com/errata/RHEA-2024:0078[RHEA-2024:0078]

[id="power-monitoring-release-notes-0-1-features"]
=== Features
* Deployment and deletion of {PM-kepler} 
* Power usage metrics from Intel-based bare-metal deployments
* Dashboards for plotting power usage

