// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="extension-apis"]
= Extension APIs
:toc: macro
:toc-title:

toc::[]

== APIService [apiregistration.k8s.io/v1]

Description::
+
--
APIService represents a server for a particular GroupVersion. Name must be "version.group".
--

Type::
  `object`

== CustomResourceDefinition [apiextensions.k8s.io/v1]

Description::
+
--
CustomResourceDefinition represents a resource that should be exposed on the API server.  Its name MUST be in the format <.spec.name>.<.spec.group>.
--

Type::
  `object`

== MutatingWebhookConfiguration [admissionregistration.k8s.io/v1]

Description::
+
--
MutatingWebhookConfiguration describes the configuration of and admission webhook that accept or reject and may change the object.
--

Type::
  `object`

== ValidatingWebhookConfiguration [admissionregistration.k8s.io/v1]

Description::
+
--
ValidatingWebhookConfiguration describes the configuration of and admission webhook that accept or reject and object without changing it.
--

Type::
  `object`

