:_mod-docs-content-type: ASSEMBLY
include::_attributes/common-attributes.adoc[]
[id="virt-backing-up-vms"]
= Backing up virtual machines
:context: virt-backing-up-vms

toc::[]

You back up virtual machines (VMs) by creating an OpenShift API for Data Protection (OADP) xref:../../virt/backup_restore/virt-backing-up-vms.adoc#oadp-creating-backup-cr_virt-backing-up-vms[`Backup` custom resource (CR)].

The `Backup` CR performs the following actions:

// Hiding MOG from ROSA/OSD as not supported
ifndef::openshift-rosa,openshift-dedicated[]
* Backs up {VirtProductName} resources by creating an archive file on S3-compatible object storage, such as xref:../../backup_and_restore/application_backup_and_restore/installing/installing-oadp-mcg.adoc#installing-oadp-mcg[Multicloud Object Gateway], Noobaa, or Minio.
endif::openshift-rosa,openshift-dedicated[]
ifdef::openshift-rosa,openshift-dedicated[]
* Backs up {VirtProductName} resources by creating an archive file on S3-compatible object storage, such as Noobaa or Minio.
endif::openshift-rosa,openshift-dedicated[]

// Hiding Backup/Restore link until 68901 is merged
ifndef::openshift-rosa,openshift-dedicated[]
* Backs up VM disks by using one of the following options:

** xref:../../virt/backup_restore/virt-backing-up-vms.adoc#oadp-backing-up-pvs-csi_virt-backing-up-vms[Container Storage Interface (CSI) snapshots] on CSI-enabled cloud storage, such as Ceph RBD or Ceph FS.
** xref:../../backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-backing-up-applications-restic-doc.adoc#backing-up-applications[Backing up applications with File System Backup: Kopia or Restic] on object storage.
endif::openshift-rosa,openshift-dedicated[]
ifdef::openshift-rosa,openshift-dedicated[]
* Backs up VM disks by using one of the following options:

** xref:../../virt/backup_restore/virt-backing-up-vms.adoc#oadp-backing-up-pvs-csi_virt-backing-up-vms[Container Storage Interface (CSI) snapshots] on CSI-enabled cloud storage, such as Ceph RBD or Ceph FS.
** Backing up applications with File System Backup: Kopia or Restic on object storage.
endif::openshift-rosa,openshift-dedicated[]

[NOTE]
====
OADP provides backup hooks to freeze the VM file system before the backup operation and unfreeze it when the backup is complete.

The `kubevirt-controller` creates the `virt-launcher` pods with annotations that enable Velero to run the `virt-freezer` binary before and after the backup operation.

The `freeze` and `unfreeze` APIs are subresources of the VM snapshot API. See xref:../../virt/backup_restore/virt-backup-restore-snapshots.adoc#virt-about-vm-snapshots_virt-backup-restore-snapshots[About virtual machine snapshots] for details.
====

ifndef::openshift-rosa,openshift-dedicated[]
You can add xref:../../backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-creating-backup-hooks-doc.adoc#backing-up-applications[hooks] to the `Backup` CR to run commands on specific VMs before or after the backup operation.

You schedule a backup by creating a xref:../../backup_and_restore/application_backup_and_restore/backing_up_and_restoring/oadp-scheduling-backups-doc.adoc#backing-up-applications[`Schedule` CR] instead of a `Backup` CR.
endif::openshift-rosa,openshift-dedicated[]
ifdef::openshift-rosa,openshift-dedicated[]
You can add hooks to the `Backup` CR to run commands on specific VMs before or after the backup operation.

You schedule a backup by creating a `Schedule` CR instead of a `Backup` CR.
endif::openshift-rosa,openshift-dedicated[]

include::modules/oadp-creating-backup-cr.adoc[leveloffset=+1]
include::modules/oadp-backing-up-pvs-csi.adoc[leveloffset=+2]
include::modules/oadp-backing-up-applications-restic.adoc[leveloffset=+2]
include::modules/oadp-creating-backup-hooks.adoc[leveloffset=+2]

ifndef::openshift-rosa,openshift-dedicated[]
[id="additional-resources_virt-backing-up-vms"]
== Additional resources

* xref:../../storage/container_storage_interface/persistent-storage-csi-snapshots.adoc#persistent-storage-csi-snapshots-overview_persistent-storage-csi-snapshots[Overview of CSI volume snapshots]
endif::openshift-rosa,openshift-dedicated[]
