// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="apps-apis"]
= Apps APIs
:toc: macro
:toc-title:

toc::[]

== ControllerRevision [apps/v1]

Description::
+
--
ControllerRevision implements an immutable snapshot of state data. Clients are responsible for serializing and deserializing the objects that contain their internal state. Once a ControllerRevision has been successfully created, it can not be updated. The API Server will fail validation of all requests that attempt to mutate the Data field. ControllerRevisions may, however, be deleted. Note that, due to its use by both the DaemonSet and StatefulSet controllers for update and rollback, this object is beta. However, it may be subject to name and representation changes in future releases, and clients should not depend on its stability. It is primarily for internal use by controllers.
--

Type::
  `object`

== DaemonSet [apps/v1]

Description::
+
--
DaemonSet represents the configuration of a daemon set.
--

Type::
  `object`

== Deployment [apps/v1]

Description::
+
--
Deployment enables declarative updates for Pods and ReplicaSets.
--

Type::
  `object`

== ReplicaSet [apps/v1]

Description::
+
--
ReplicaSet ensures that a specified number of pod replicas are running at any given time.
--

Type::
  `object`

== StatefulSet [apps/v1]

Description::
+
--
StatefulSet represents a set of pods with consistent identities. Identities are defined as:
  - Network: A single stable DNS and hostname.
  - Storage: As many VolumeClaims as requested.

The StatefulSet guarantees that a given network identity will always map to the same storage identity.
--

Type::
  `object`

