include::modules/serverless-document-attributes.adoc[]
[id="gpu-resources"]
= Using NVIDIA GPU resources with serverless applications
:context: gpu-resources
include::modules/common-attributes.adoc[]

toc::[]

NVIDIA supports experimental use of GPU resources on {product-title}.

// new module
[id="gpu-resources-set-requirement_{context}"]
= Specifying GPU resource requirements for a Knative service

After GPU resources are enabled for your {product-title} cluster, you can specify GPU requirements for a Knative service using the `kn` CLI.

[NOTE]
====
Services do not share GPU resources. Any other services that require GPU resources must wait until the GPU resource is no longer in use.
====

.Prerequisites
* Set up GPU resources on {product-title}. See link:https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/index.html[{product-title} on NVIDIA GPU accelerated clusters].
* Install the `kn` CLI. See xref:../../serverless/installing_serverless/installing-kn.adoc#installing-kn[Installing the Knative CLI].

.Procedure

You can specify a GPU resource requirement when you create a Knative service using `kn`.

* Create a service and set the GPU resource requirement:
+
[source,terminal]
----
$ kn service create <service_name> --image <image_url> --limit <gpu_resource_requirement>
----
+
You can set the GPU resource requirement limit to `1` by using `nvidia.com/gpu=1`.
+
.Example command
[source,terminal]
----
$ kn service create event-display --image quay.io/openshift-knative/knative-eventing-sources-event-display:latest --limit nvidia.com/gpu=1
----
+
A GPU resource requirement limit of `1` means that the service has 1 GPU resource dedicated, and that applications exceeding usage of 1 GPU resource are restricted.
+
If a service requests more than 1 GPU resource, it is deployed on a node where the GPU resource requirements can be met.

// new module
[id="gpu-resources-update-requirement_{context}"]
= Updating GPU resource requirements for a Knative service

You can update the GPU resource requirement for a Knative service using `kn`.

.Procedure
* Update the service:
+
[source,terminal]
----
$ kn service update <service_name> --limit <new_gpu_reesource_requirement>
----

.Example
Change the GPU resource requirement limit to `3` by using `nvidia.com/gpu=3`:

[source,terminal]
----
$ kn service update event-display --limit nvidia.com/gpu=3
----

== Additional resources
* For more information about limits, see xref:../../applications/quotas/quotas-setting-per-project.adoc[Setting resource quotas for extended resources].
