[id="image-scanning-by-using-the-roxctl-cli"]
:_mod-docs-content-type: ASSEMBLY
= Image scanning by using the roxctl CLI
include::modules/common-attributes.adoc[]
:context: image-scanning-by-using-the-roxctl-cli

toc::[]

[role="_abstract"]
You can scan images stored in image registries, including cluster local registries such as the {ocp} integrated image registry by using the `roxctl` CLI.

[id="scanning-images-by-using-a-remote-cluster_{context}"]
== Scanning images by using a remote cluster

By specifying the appropriate cluster in the delegated scanning configuration or through the cluster parameter described in the following procedure, you can scan images from cluster local registries by using a remote cluster.

[IMPORTANT]
====
For more information about how to configure delegated image scanning, see xref:../operating/examine-images-for-vulnerabilities.adoc#configuring-delegated-image-scanning_examine-images-for-vulnerabilities[Configuring delegated image scanning].
====

.Procedure

* Run the following command to scan the specified image in a remote cluster:
+
[source,terminal,subs="+quotes"]
----
$ roxctl image scan \
  --image=_<image_registry>_/_<image_name>_ \// <1>
  --cluster=_<cluster_detail>_ \// <2>
  [flags] <3>
----
+
--
<1> For `<image_registry>`, specify the registry where the image is located, for example, `image-registry.openshift-image-registry.svc:5000/`.
For `<image_name>`, specify the name of the image you want to scan, for example, `default/image-stream:latest`.
<2> For `<cluster_detail>`, specify the name or ID of the remote cluster. For example, specify the name `remote`.
<3> Optional: For `[flags]`, you can specify parameters to modify the behavior of the command.
+
For more information about optional parameters, see xref:../cli/image-scanning-by-using-the-roxctl-cli.adoc#roxctl-image-scan-command-options_image-scanning-by-using-the-roxctl-cli[roxctl image scan command options].
--
+
.Example output
+
[source,text,subs=attributes+]
----
{
  "Id": "sha256:3f439d7d71adb0a0c8e05257c091236ab00c6343bc44388d091450ff58664bf9", <1>
  "name": { <2>
    "registry": "image-registry.openshift-image-registry.svc:5000", <3>
    "remote": "default/image-stream", <4>
    "tag": "latest", <5>
    "fullName": "image-registry.openshift-image-registry.svc:5000/default/image-stream:latest" <6>
  },
[...]
----
+
--
<1> A unique identifier for the image that serves as a fingerprint for the image. It helps ensure the integrity and authenticity of the image.
<2> Contains specific details about the image.
<3> The location of the image registry where the image is stored.
<4> The remote path to the image.
<5> The version or tag associated with this image.
<6> The complete name of the image, combining the registry, remote path, and tag.
--

//roxctl image scan command options
include::modules/roxctl-image-scan-command-options.adoc[leveloffset=+1]