[id="installing-openshift-serverless"]
= Installing {ServerlessProductName}
include::modules/common-attributes.adoc[]
include::modules/serverless-document-attributes.adoc[]
:context: installing-openshift-serverless

toc::[]

[NOTE]
====
{ServerlessProductName} is not tested or supported for installation in a restricted network environment.
====

// Cluster sizing requirements
include::modules/serverless-cluster-sizing-requirements.adoc[leveloffset=+1]

.Additional resources
For more information on using the MachineSet API, read about xref:../machine_management/creating_machinesets/creating-machineset-aws.adoc[Creating MachineSets].


// Add or remove an instance of a machine in a MachineSet
include::modules/machineset-manually-scaling.adoc[leveloffset=+2]

// Installing Serverless Operator
[id="installing-serverless-operator_{context}"]
== Installing the {ServerlessOperatorName}

The {ServerlessOperatorName} can be installed using the {product-title} instructions for installing Operators.

You can install the {ServerlessOperatorName} in the host cluster by following the {product-title} instructions on installing an Operator.

[NOTE]
====
The {ServerlessOperatorName} only works for {product-title} versions 4.1.13 and later.
====

For details, see the {product-title} documentation on xref:../operators/olm-adding-operators-to-cluster.adoc[adding Operators to a cluster].

// Installing Knative Serving
include::modules/serverless-installing-knative-serving.adoc[leveloffset=+1]

// Uninstalling Knative Serving
include::modules/serverless-uninstalling-knative-serving.adoc[leveloffset=+1]

// Deleting Serverless Operator
[id="deleting-openshift-serverless-operator_{context}"]
== Deleting the {ServerlessOperatorName}

You can remove the {ServerlessOperatorName} from the host cluster by following the {product-title} instructions on deleting an Operator.

For details, see the {product-title} documentation on xref:../operators/olm-deleting-operators-from-cluster.adoc[deleting Operators from a cluster].


// Deleting Knative Serving
include::modules/serverless-deleting-knative-serving-crds.adoc[leveloffset=+1]
