[id="jaeger-config-ref"]
= Jaeger configuration reference
include::modules/ossm-document-attributes.adoc[]
:context: distributed-tracing-config-reference

toc::[]

When the {ProductShortName} Operator deploys the `ServiceMeshControlPlane` resource, it can also create the resources for distributed tracing. {ProductShortName} uses distributed-tracing for distributed tracing.

include::modules/ossm-enabling-distributed-tracing.adoc[leveloffset=+1]

include::modules/ossm-configuring-distributed-tracing.adoc[leveloffset=+1]

include::modules/ossm-deploying-distributed-tracing.adoc[leveloffset=+1]

include::modules/ossm-configuring-external-distributed-tracing.adoc[leveloffset=+1]

include::modules/distributed-tracing-deployment-best-practices.adoc[leveloffset=+2]

include::modules/distributed-tracing-config-default.adoc[leveloffset=+2]

include::modules/distributed-tracing-config-collector.adoc[leveloffset=+2]

include::modules/distributed-tracing-config-sampling.adoc[leveloffset=+2]

include::modules/distributed-tracing-config-storage.adoc[leveloffset=+2]

For more information about configuring Elasticsearch with {product-title}, see xref:../../logging/config/cluster-logging-log-store.adoc[Configuring the log store] or xref:../../distributed_tracing/distributed_tracing_install/distributed-tracing-deploying.adoc[Configuring and deploying distributed tracing platform].
////
For information about connecting to an external Elasticsearch instance, see xref:../../jaeger/jaeger_install/rhbjaeger-deploying.adoc#jaeger-config-external-es_jaeger-deploying[Connecting to an existing Elasticsearch instance].

For information about connecting to an external Elasticsearch instance, see xref:../../distributed_tracing/distributed_tracing_install/distributed-tracing-deploying.adoc#jaeger-config-external-es_jaeger-deploying[Connecting to an existing Elasticsearch instance].
////

include::modules/distributed-tracing-config-query.adoc[leveloffset=+2]

include::modules/distributed-tracing-config-ingester.adoc[leveloffset=+2]
