[id="respond-to-violations"]
= Responding to violations
include::modules/common-attributes.adoc[]
:context: respond-to-violations

toc::[]

[role="_abstract"]
Using {product-title} you can view policy violations, drill down to the actual cause of the violation, and take corrective actions.

{product-title} built-in policies identify a variety of security findings, including vulnerabilities (CVEs), violations of DevOps best practices, high-risk build and deployment practices, and suspicious runtime behaviors.
Whether you use the default out-of-box security policies or use your own custom policies, {product-title} reports a violation when an enabled policy fails.

include::modules/violations-view.adoc[leveloffset=+1]

[id="view-violation-details"]
== Viewing violation details
When you select a violation in the *Violations* view, the *Violation Details* panel opens on the right.

The *Violation Details* panel shows detailed information grouped by multiple tabs.

include::modules/violation-view-violation-tab.adoc[leveloffset=+2]

include::modules/violation-view-enforcement-tab.adoc[leveloffset=+2]

include::modules/violations-view-deployment-tab.adoc[leveloffset=+2]

include::modules/violation-view-policy-tab.adoc[leveloffset=+2]
