[id="use-admission-controller-enforcement"]
= Using admission controller enforcement
include::modules/common-attributes.adoc[]
:context: use-admission-controller-enforcement

toc::[]

[role="_abstract"]
{product-title} works with link:https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/[Kubernetes admission controllers] and link:https://docs.openshift.com/container-platform/4.11/architecture/admission-plug-ins.html[{ocp} admission plug-ins] to allow you to enforce security policies before Kubernetes or {ocp} creates workloads, for example, deployments, daemon sets or jobs.
The {product-title} admission controller prevents users from creating workloads that violate policies you configure in {product-title}.
Beginning from the {product-title} version 3.0.41, you can also configure the admission controller to prevent updates to workloads that violate policies.

{product-title} uses the `ValidatingAdmissionWebhook` controller to verify that the resource being provisioned complies with the specified security policies.
To handle this, {product-title} creates a `ValidatingWebhookConfiguration` which contains multiple webhook rules.
When the Kubernetes or {ocp} API server receives a request that matches one of the webhook rules, the API server sends an `AdmissionReview` request to {product-title}.
{product-title} then accepts or rejects the request based on the configured security policies.

[NOTE]
====
To use admission controller enforcement on {ocp}, you need the {product-title}  version 3.0.49 or newer.
====

include::modules/understand-admission-controller-enforcement.adoc[leveloffset=+1]

include::modules/enable-admission-controller-enforcement.adoc[leveloffset=+1]

include::modules/bypass-admission-controller-enforcement.adoc[leveloffset=+1]

include::modules/disable-admission-controller-enforcement.adoc[leveloffset=+1]

include::modules/disable-associated-policies.adoc[leveloffset=+2]

include::modules/disable-the-webhook.adoc[leveloffset=+2]

include::modules/validatingwebhookconfiguration-yaml-changes.adoc[leveloffset=+1]
