:_mod-docs-content-type: ASSEMBLY
include::_attributes/common-attributes.adoc[]
[id="install-disconnected"]
= Installing {kueue-name} in a disconnected environment
:context: install-disconnected

toc::[]

Before you can install {kueue-name} on a disconnected {product-title} cluster, you must enable {olm-first} in disconnected environments by completing the following steps:

* Disable the default remote OperatorHub sources for OLM.
* Use a workstation with full internet access to create and push local mirrors of the OperatorHub content to a mirror registry.
* Configure OLM to install and manage Operators from local sources on the mirror registry instead of the default remote sources.

After enabling OLM in a disconnected environment, you can continue to use your unrestricted workstation to keep your local OperatorHub sources updated as newer versions of Operators are released.

For full documentation on completing these steps, see the {product-title} documentation on xref:../../disconnected/using-olm.adoc#olm-restricted-networks[Using Operator Lifecycle Manager in disconnected environments].

include::modules/kueue-compatible-environments.adoc[leveloffset=+1]

include::modules/kueue-install-kueue-operator.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources
* xref:../../security/cert_manager_operator/cert-manager-operator-install.adoc#installing-the-cert-manager-operator-for-red-hat-openshift[Installing the {cert-manager-operator}]

include::modules/kueue-create-kueue-cr.adoc[leveloffset=+1]

include::modules/kueue-label-namespaces.adoc[leveloffset=+1]
