// Module included in the following assemblies:
//
// * authentication/using-service-accounts.adoc

[id="service-accounts-enabling-authentication_{context}"]
= Enabling service account authentication

Service accounts authenticate to the API using tokens signed by a private RSA
key. The authentication layer verifies the signature using a matching public RSA
key.

.Procedure

* To enable service account token generation, update the `serviceAccountConfig`
stanza in the *_/etc/origin/master/master-config.yml_* file on the master to
specify a `privateKeyFile` (for signing), and a matching public key file in
the `publicKeyFiles` list:
+
[source,yaml]
----
serviceAccountConfig:
  ...
  masterCA: ca.crt <1>
  privateKeyFile: serviceaccounts.private.key <2>
  publicKeyFiles:
  - serviceaccounts.public.key <3>
  - ...
----
<1> CA file to validate the API server's serving certificate.
<2> Private RSA key file for token signing.
<3> Public RSA key files for token verification. If you provide private key
files, then the public key component is used. You can specify multiple public
key files, and a token is accepted if it can be validated by one of the
public keys. This allows rotation of the signing key while still accepting
tokens generated by the previous signer.
