[[admin-guide-allocating-node-resources]]
= Allocating Node Resources
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:

toc::[]

== Overview

To provide more reliable scheduling and minimize node resource overcommitment,
each node can reserve a portion of its resources for use by all underlying
xref:../architecture/infrastructure_components/kubernetes_infrastructure.adoc#node[node
components] (e.g., kubelet, kube-proxy, Docker) and the remaining system
components (e.g., *sshd*, *NetworkManager*) on the host. Once specified, the
scheduler has more information about the resources (e.g., memory, CPU) a node
has allocated for pods.

[[allocating-node-settings]]
== Configuring Nodes for Allocated Resources

Resources reserved for node components are based on two node settings:

[options="header",cols="1,2"]
|===

|Setting |Description

|`*kube-reserved*`
| Resources reserved for node components. Default is none.

|`*system-reserved*`
| Resources reserved for the remaining system components. Default is none.
|===

You can set these in the `*kubeletArguments*` section of the
xref:../install_config/master_node_configuration.adoc#node-configuration-files[node
configuration file] (the *_/etc/origin/node/node-config.yaml_* file by default)
using a set of `<resource_type>=<resource_quantity>` pairs (e.g.,
*cpu=200m,memory=512Mi*). Add the section if it does not already exist:

.Node Allocatable Resources Settings
====
[source,yaml]
----
kubeletArguments:
  kube-reserved:
    - "cpu=200m,memory=512Mi"
  system-reserved:
    - "cpu=200m,memory=512Mi"
----
====

Currently, the `*cpu*` and `*memory*` resource types are supported. For `*cpu*`,
the resource quantity is specified in units of cores (e.g., 200m, 0.5, 1).
For `*memory*`, it is specified in units of bytes (e.g., 200Ki, 50Mi, 5Gi).

See xref:../dev_guide/compute_resources.adoc#dev-guide-compute-resources[Compute Resources] for more
details.

If a flag is not set, it defaults to *0*. If none of the flags are set, the
allocated resource is set to the node's capacity as it was before the
introduction of allocatable resources.

[[computing-allocated-resources]]
== Computing Allocated Resources

An allocated amount of a resource is computed based on the following formula:

----
[Allocatable] = [Node Capacity] - [kube-reserved] - [system-reserved]
----

If `[Allocatable]` is negative, it is set to *0*.

[[viewing-node-allocatable-resources-and-capacity]]
== Viewing Node Allocatable Resources and Capacity

To see a node's current capacity and allocatable resources, you can run:

====
----
$ oc get node/<node_name> -o yaml
...
status:
...
  allocatable:
    cpu: "4"
    memory: 8010948Ki
    pods: "110"
  capacity:
    cpu: "4"
    memory: 8010948Ki
    pods: "110"
...
----
====

[[system-resources-reported-by-node]]
== System Resources Reported by Node

Starting with {product-title}
ifdef::openshift-enterprise[]
3.3,
endif::[]
ifdef::openshift-origin[]
1.3,
endif::[]
each node reports system resources utilized by the container runtime and kubelet.
To better aid your ability to configure `*--system-reserved*` and `*--kube-reserved*`,
you can introspect corresponding node's resource usage using the node summary API,
which is accessible at *_<master>/api/v1/nodes/<node>/proxy/stats/summary_*.

For instance, to access the resources from *cluster.node22* node, you can run:

----
$ curl <certificate details> https://<master>/api/v1/nodes/cluster.node22/proxy/stats/summary
{
    "node": {
        "nodeName": "cluster.node22",
        "systemContainers": [
            {
                "cpu": {
                    "usageCoreNanoSeconds": 929684480915,
                    "usageNanoCores": 190998084
                },
                "memory": {
                    "rssBytes": 176726016,
                    "usageBytes": 1397895168,
                    "workingSetBytes": 1050509312
                },
                "name": "kubelet"
            },
            {
                "cpu": {
                    "usageCoreNanoSeconds": 128521955903,
                    "usageNanoCores": 5928600
                },
                "memory": {
                    "rssBytes": 35958784,
                    "usageBytes": 129671168,
                    "workingSetBytes": 102416384
                },
                "name": "runtime"
            }
        ]
    }
}
----

See xref:../rest_api/index.adoc#rest-api-index[REST API Overview] for more details about certificate details.

[[allocating-node-scheduler]]
== Scheduler

The scheduler now uses the value of `*node.Status.Allocatable*` instead of
`*node.Status.Capacity*` to decide if a node will become a candidate for pod
scheduling.

By default, the node will report its machine capacity as fully schedulable by
the cluster.
