= Configuring Authentication
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:

toc::[]

== Overview
The OpenShift
link:../architecture/infrastructure_components/kubernetes_infrastructure.html#master[master]
includes a built-in
link:../architecture/additional_concepts/authentication.html#oauth[OAuth
server]. Developers and administrators obtain
link:../architecture/additional_concepts/authentication.html#api-authentication[OAuth
access tokens] to authenticate themselves to the API.

As an administrator, you can configure OAuth using a
link:master_node_configuration.html[master configuration file] to specify an
link:#identity-providers[identity provider]. If you installed OpenShift using
the
ifdef::openshift-enterprise[]
link:install/quick_install.html[Quick Installation] or
endif::[]
link:install/advanced_install.html[Advanced Installation] method, the
link:#DenyAllPasswordIdentityProvider[Deny All] identity provider is used by
default, which denies access for all user names and passwords. To allow access,
you must choose a different identity provider and configure the master
configuration file appropriately (located at
*_/etc/openshift/master/master-config.yaml_* by default).

When running a master without a configuration file, the
link:#AllowAllPasswordIdentityProvider[Allow All] identity provider is used by
default, which allows any non-empty user name and password to log in. This is
useful for testing purposes. To use other identity providers, or to modify any
link:#token-options[token], link:#grant-options[grant], or
link:#session-options[session options], you must run the master from a
configuration file.

[[identity-providers]]

== Identity Providers
You can configure the master for authentication using your desired identity
provider by modifying the link:master_node_configuration.html[master
configuration file]. The following sections detail the identity providers
supported by OpenShift.

There are three parameters common to all identity providers:

[cols="2a,8a",options="header"]
|===
|Parameter     | Description
.^|`name`      | The provider name is prefixed to provider user names to form an
identity name.
.^|`challenge` | When `true`, unauthenticated token requests from non-web
clients (like the CLI) are sent a `WWW-Authenticate` challenge header. Not
supported by all identity providers.

[NOTE]
====
To prevent CSRF attacks against browser clients, Basic authentication
challenges are only sent if a `X-CSRF-Token` header is present on the request.
Clients that expect to receive Basic `WWW-Authenticate` challenges should set
this header to a non-empty value.
====

.^|`login`     | When `true`, unauthenticated token requests from web clients
(like the web console) are redirected to a login page backed by this provider.
Not supported by all identity providers.
|===

[[AllowAllPasswordIdentityProvider]]

=== Allow All
Set *AllowAllPasswordIdentityProvider* in the `*identityProviders*` stanza to
allow any non-empty user name and password to log in. This is the default
identity provider when running OpenShift without a
link:master_node_configuration.html[master configuration file].

.Master Configuration Using *AllowAllPasswordIdentityProvider*
====

----
oauthConfig:
  ...
  identityProviders:
  - name: my_allow_provider <1>
    challenge: true <2>
    login: true <3>
    provider:
      apiVersion: v1
      kind: AllowAllPasswordIdentityProvider
----
<1> This provider name is prefixed to provider user names to form an identity
name.
<2> When *true*, unauthenticated token requests from non-web clients (like
the CLI) are sent a `WWW-Authenticate` challenge header for this provider.
<3> When *true*, unauthenticated token requests from web clients (like the web
console) are redirected to a login page backed by this provider.
====

[[DenyAllPasswordIdentityProvider]]

=== Deny All
Set *DenyAllPasswordIdentityProvider* in the `*identityProviders*` stanza to
deny access for all user names and passwords.

.Master Configuration Using *DenyAllPasswordIdentityProvider*
====

----
oauthConfig:
  ...
  identityProviders:
  - name: my_deny_provider <1>
    challenge: true <2>
    login: true <3>
    provider:
      apiVersion: v1
      kind: DenyAllPasswordIdentityProvider
----
<1> This provider name is prefixed to provider user names to form an identity
name.
<2> When *true*, unauthenticated token requests from non-web clients (like the
CLI) are sent a `WWW-Authenticate` challenge header for this provider.
<3> When *true*, unauthenticated token requests from web clients (like the web
console) are redirected to a login page backed by this provider.
====

[[HTPasswdPasswordIdentityProvider]]

=== HTPasswd

Set *HTPasswdPasswordIdentityProvider* in the `*identityProviders*` stanza to
validate user names and passwords against a flat file generated using
http://httpd.apache.org/docs/2.4/programs/htpasswd.html[`htpasswd`].

Only MD5 and SHA encryption types are supported. MD5 encryption is recommended,
and is the default for `htpasswd`. Plaintext, crypt, and bcrypt hashes are not
currently supported.

The flat file is re-read if its modification time changes, without requiring a
server restart.

To create the file, run:

----
$ htpasswd -c </path/to/users.htpasswd> <user_name>
----

To add or update a login to the file, run:

----
$ htpasswd </path/to/users.htpasswd> <user_name>
----

To remove a login from the file, run:

----
$ htpasswd </path/to/users.htpasswd> -D <user_name>
----

.Master Configuration Using *HTPasswdPasswordIdentityProvider*
====

----
oauthConfig:
  ...
  identityProviders:
  - name: my_htpasswd_provider <1>
    challenge: true <2>
    login: true <3>
    provider:
      apiVersion: v1
      kind: HTPasswdPasswordIdentityProvider
      file: /path/to/users.htpasswd <4>
----
<1> This provider name is prefixed to provider user names to form an identity
name.
<2> When *true*, unauthenticated token requests from non-web clients (like the
CLI) are sent a `WWW-Authenticate` challenge header for this provider.
<3> When *true*, unauthenticated token requests from web clients (like the web
console) are redirected to a login page backed by this provider.
<4> File generated using
http://httpd.apache.org/docs/2.4/programs/htpasswd.html[`htpasswd`].
====

[[LDAPPasswordIdentityProvider]]

=== LDAP Authentication

Set *LDAPPasswordIdentityProvider* in the `*identityProviders*` stanza to
validate user names and passwords against an LDAPv3 server, using simple bind
authentication.

During authentication, the LDAP directory is searched for an entry that matches
the provided user name. If a single unique match is found, a simple bind is
attempted using the distinguished name (DN) of the entry plus the provided
password. Here are the steps taken:

. Generate a search filter by combining the attribute and filter in the
configured `*url*` with the user-provided user name.
. Search the directory using the generated filter. If the search does not return
exactly one entry, deny access.
. Attempt to bind to the LDAP server using the DN of the entry retrieved from
the search, and the user-provided password.
. If the bind is unsuccessful, deny access.
. If the bind is successful, build an identity using the configured attributes
as the identity, email address, display name, and preferred user name.

[[ldap-url]]
The configured `*url*` is an RFC 2255 URL, which specifies the LDAP host and
search parameters to use. The syntax of the URL is:

----
ldap://host:port/basedn?attribute?scope?filter
----

For the above example:

[cols="2a,8a",options="header"]
|===
|URL Component | Description
.^|`ldap`      | For regular LDAP, use the string `ldap`. For secure LDAP
(LDAPS), use `ldaps` instead.
.^|`host:port` | The name and port of the LDAP server. Defaults to
`localhost:389` for ldap and `localhost:636` for LDAPS.
.^|`basedn`    | The DN of the branch of the directory where all searches should
start from. At the very least, this must be the top of your directory tree, but
it could also specify a subtree in the directory.
.^|`attribute` | The attribute to search for. Although RFC 2255 allows a
comma-separated list of attributes, only the first attribute will be used, no
matter how many are provided. If no attributes are provided, the default is to
use `uid`. It is recommended to choose an attribute that will be unique across
all entries in the subtree you will be using.
.^|`scope`     | The scope of the search. Can be either either `one` or `sub`.
If the scope is not provided, the default is to use a scope of `sub`.
.^|`filter`    | A valid LDAP search filter. If not provided, defaults to
`(objectClass=*)`
|===

When doing searches, the attribute, filter, and provided user name are combined
to create a search filter that looks like:

----
(&(<filter>)(<attribute>=<username>))
----

For example, consider a URL of:

====
----
ldap://ldap.example.com/o=Acme?cn?sub?(enabled=true)
----
====

When a client attempts to connect using a user name of `bob`, the resulting
search filter will be `(&(enabled=true)(cn=bob))`.

If the LDAP directory requires authentication to search, specify a `bindDN` and
`bindPassword` to use to perfom the entry search.

.Master Configuration Using *LDAPPasswordIdentityProvider*
====
----
oauthConfig:
  ...
  identityProviders:
  - name: "my_ldap_provider" <1>
    challenge: true <2>
    login: true <3>
    provider:
      apiVersion: v1
      kind: LDAPPasswordIdentityProvider
      attributes:
        id: <4>
        - dn
        email: <5>
        - mail
        name: <6>
        - cn
        preferredUsername: <7>
        - uid
      bindDN: "" <8>
      bindPassword: "" <9>
      ca: my-ldap-ca-bundle.crt <10>
      insecure: false <11>
      url: "ldap://ldap.example.com/ou=users,dc=acme,dc=com?uid" <12>
----
<1> This provider name is prefixed to the returned user ID to form an identity
name.
<2> When *true*, unauthenticated token requests from non-web clients (like the
CLI) are sent a `WWW-Authenticate` challenge header for this provider.
<3> When *true*, unauthenticated token requests from web clients (like the web
console) are redirected to a login page backed by this provider.
<4> List of attributes to use as the identity. First non-empty attribute is
used. At least one attribute is required. If none of the listed attribute have a
value, authentication fails.
<5> List of attributes to use as the email address. First non-empty attribute is
used.
<6> List of attributes to use as the display name. First non-empty attribute is
used.
<7> List of attributes to use as the preferred user name when provisioning a
user for this identity. First non-empty attribute is used.
<8> Optional DN to use to bind during the search phase.
<9> Optional password to use to bind during the search phase.
<10> Certificate bundle to use to validate server certificates for the
configured URL. If empty, system trusted roots are used. Only applies if
*insecure: false*.
<11> When *true*, no TLS connection is made to the server. When *false*,
`ldaps://` URLs connect using TLS, and `ldap://` URLs are upgraded to TLS.
<12> An RFC 2255 URL which specifies the LDAP host and search parameters to use,
link:#ldap-url[as described above].
====

[[BasicAuthPasswordIdentityProvider]]

=== Basic Authentication (Remote)

Set *BasicAuthPasswordIdentityProvider* in the `*identityProviders*` stanza to
validate user names and passwords against a remote server using a
server-to-server Basic authentication request. User names and passwords are
validated against a remote URL that is protected by Basic authentication and
returns JSON.

A `401` response indicates failed authentication.

A non-`200` status, or the presence of a non-empty "error" key, indicates an
error:

----
{"error":"Error message"}
----

A `200` status with a `sub` (subject) key indicates success:

----
{"sub":"userid"} <1>
----
<1> The subject must be unique to the authenticated user and must not be able to
be modified.

A successful response may optionally provide additional data, such as:

* A display name using the `name` key. For example:
+
----
{"sub":"userid", "name": "User Name", ...}
----
+
* An email address using the `email` key. For example:
+
----
{"sub":"userid", "email":"user@example.com", ...}
----
+
* A preferred user name using the `preferred_username` key. This is useful when
the unique, unchangeable subject is a database key or UID, and a more
human-readable name exists. This is used as a hint when provisioning the
OpenShift user for the authenticated identity. For example:
+
----
{"sub":"014fbff9a07c", "preferred_username":"bob", ...}
----

.Master Configuration Using *BasicAuthPasswordIdentityProvider*
====

----
oauthConfig:
  ...
  identityProviders:
  - name: my_remote_basic_auth_provider <1>
    challenge: true <2>
    login: true <3>
    provider:
      apiVersion: v1
      kind: BasicAuthPasswordIdentityProvider
      url: https://www.example.com/remote-idp <4>
      ca: /path/to/ca.file <5>
      certFile: /path/to/client.crt <6>
      keyFile: /path/to/client.key <7>
----
<1> This provider name is prefixed to the returned user ID to form an identity
name.
<2> When *true*, unauthenticated token requests from non-web clients (like the
CLI) are sent a `WWW-Authenticate` challenge header for this provider.
<3> When *true*, unauthenticated token requests from web clients (like the web
console) are redirected to a login page backed by this provider.
<4> URL accepting credentials in Basic authentication headers.
<5> Optional: Certificate bundle to use to validate server certificates for the
configured URL.
<6> Optional: Client certificate to present when making requests to the
configured URL.
<7> Key for the client certificate. Required if `*certFile*` is specified.
====

[[RequestHeaderIdentityProvider]]

=== Request Header

Set *RequestHeaderIdentityProvider* in the `*identityProviders*` stanza to
identify users from request header values, such as `X-Remote-User`. It is
typically used in combination with an authenticating proxy, which sets the
request header value. This is similar to how
link:https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/Deployment_Guide/Configuring_OpenShift_Enterprise_Authentication.html[the
remote user plug-in in OpenShift Enterprise 2] allowed administrators to
provide Kerberos, LDAP, and many other forms of enterprise authentication.


.Master Configuration Using *RequestHeaderIdentityProvider*
====

----
oauthConfig:
  ...
  identityProviders:
  - name: my_request_header_provider <1>
    challenge: false <2>
    login: false <3>
    provider:
      apiVersion: v1
      kind: RequestHeaderIdentityProvider
      clientCA: /path/to/client-ca.file <4>
      headers: <5>
      - X-Remote-User
      - SSO-User
----
<1> This provider name is prefixed to the user name in the request header to
form an identity name.
<2> *RequestHeaderIdentityProvider* cannot be used to send `WWW-Authenticate`
challenges.
<3> *RequestHeaderIdentityProvider* cannot be used to back a login page.
<4> Optional: PEM-encoded certificate bundle. If set, a valid client certificate
must be presented and validated against the certificate authorities in the
specified file before the request headers are checked for user names.
<5> Header names to check, in order, for user names. The first header containing
a value is used as the user name. Required, case-insensitive.
====

.Apache Authentication Using *RequestHeaderIdentityProvider*
====

This example configures an authentication proxy on the same host as the master.
Apache is not strictly required and this can serve as a reference configuration
for other proxies. Having the proxy and master on the same host is merely a
convenience and may not be suitable for your environment. For example, if you
were already running the router on the master, then port 443 would not be
available.

Install the prerequisites:

----
# yum install -y httpd mod_ssl
----

Generate a CA for validating requests that submit the trusted header. This CA
should be used as the file name for `*clientCA*` in the
link:#requestheader-master-ca-config[master's identity provider configuration].

----
# oadm create-signer-cert \
  --cert='/etc/openshift/master/proxyca.crt' \
  --key='/etc/openshift/master/proxyca.key' \
  --name='openshift-proxy-signer@1432232228' \
  --serial='/etc/openshift/master/proxyca.serial.txt'
----

Generate a client certificate for the proxy. This can be done using any x509
certificate tooling. For convenience, the `oadm` tool can be used:

----
# oadm create-api-client-config \
  --certificate-authority='/etc/openshift/master/proxyca.crt' \
  --client-dir='/etc/openshift/master/proxy' \
  --signer-cert='/etc/openshift/master/proxyca.crt' \
  --signer-key='/etc/openshift/master/proxyca.key' \
  --signer-serial='/etc/openshift/master/proxyca.serial.txt' \
  --user='system:proxy' <1>

# pushd /etc/openshift/master
# cp master.server.crt /etc/pki/tls/certs/localhost.crt <2>
# cp master.server.key /etc/pki/tls/private/localhost.key
# cp ca.crt /etc/pki/CA/certs/ca.crt
# cat proxy/system\:proxy.crt \
  proxy/system\:proxy.key > \
  /etc/pki/tls/certs/authproxy.pem
# popd
----
<1> The user name can be anything, however it is useful to give it a descriptive
name as it will appear in logs.
<2> When running the authentication proxy on a different host name than the
master, it is important to generate a certificate that matches the host name
instead of using the default master certificate as shown above. The value for
`*masterPublicURL*` in the *_/etc/openshift/master/master-config.yaml_* file
must be included in the `X509v3 Subject Alternative Name` in the certificate
that is specified for `*SSLCertificateFile*`. If a new certificate needs to be
created, the `oadm create-server-cert` command can be used.

*Apache Configuration*

Unlike OpenShift Enterprise 2, this proxy does not need to reside on the same
host as the master. It uses a client certificate to connect to the master, which
is configured to trust the `X-Remote-User` header.

----
# Nothing needs to be served over HTTP.  This virtual host simply redirects to
# HTTPS.
<VirtualHost *:80>
  DocumentRoot /var/www/html
  RewriteEngine              On
  RewriteRule     ^(.*)$     https://%{HTTP_HOST}$1 [R,L]
</VirtualHost>

<VirtualHost *:443>
  ServerName ose3-master.example.com
  DocumentRoot /var/www/html
  SSLEngine on
  SSLCertificateFile /etc/pki/tls/certs/localhost.crt
  SSLCertificateKeyFile /etc/pki/tls/private/localhost.key
  SSLCACertificateFile /etc/pki/CA/certs/ca.crt

  SSLProxyEngine on
  SSLProxyCACertificateFile /etc/pki/CA/certs/ca.crt
  SSLProxyMachineCertificateFile /etc/pki/tls/certs/authproxy.pem

  # Needed for efficient log watching
  SetEnv proxy-sendchunked 1

  # The value here will be important to tune for your performance needs.  At
  # some point Apache has to clean up stale connections.  The proxy is unable
  # to differenciate stale connections with say 'oc log -f' on a pod that
  # simply isn't outputing anything.  There are likely many other ProxyPass
  # settings that will need to be adjusted for Production workloads.
  ProxyTimeout 60

  # Insert your backend server name/ip here.
  ProxyPass / https://ose3-master.example.com:8443/
  ProxyPassReverse / https://ose3-master.example.com:8443/

  # Requests should be able to access /oauth/token/request and
  # /oauth/token/display without authentication.  In the case of
  # /outh/token/display OpenShift will check one of the
  # ORIGIN_AUTH_REQUEST_HANDLERS to see if the request is authenticated.
  # Technically it would require authentication for /oauth/token/display simply
  # by modifying these two ProxyMatch stanzas.
  <ProxyMatch /oauth/token/.*>
    Allow from all
  </ProxyMatch>

  # /oauth/authorize and /oauth/approve should be protected by Apache.
  <ProxyMatch /oauth/a.*>
    AuthUserFile /etc/openshift/htpasswd
    AuthType basic

    # For ldap:
    # AuthBasicProvider ldap
    # AuthLDAPURL "ldap://ldap.example.com:389/ou=People,dc=my-domain,dc=com?uid?sub?(objectClass=*)"

    # For Kerberos remove "AuthType basic" and insert the following:
    # AuthType Kerberos
    # KrbMethodNegotiate on
    # KrbMethodK5Passwd off
    # KrbServiceName Any
    # KrbAuthRealms EXAMPLE.COM
    # Krb5Keytab /path/to/keytab
    # KrbSaveCredentials off

    AuthName openshift
    Require valid-user
    RequestHeader set X-Remote-User %{REMOTE_USER}s
  </ProxyMatch>

  # All other requests should use Bearer tokens.  These can only be verified by
  # OpenShift so we need to let these requests pass through.
  <Proxy *>
    SetEnvIfNoCase Authorization Bearer passthrough
    Allow from env=passthrough

    Order Deny,Allow
    Deny from all
    Satisfy any
  </Proxy>
</VirtualHost>

RequestHeader unset X-Remote-User
----

At this point, you can create the users in the system Apache is using to store
accounts information. In this example, file-backed authentication is used:

----
# yum -y install httpd-tools
# touch /etc/openshift/htpasswd
# htpasswd -c /etc/openshift/htpasswd <user_name>
----

*Master Configuration*

In the *_/etc/openshift/master/master-config.yaml_* file, all instances of
`*masterPublicURL*` and `*assetPublicURL*` must match the host name and port for
the Apache VirtualHost:

----
    masterPublicURL: https://ose3-master.example.com:443
    assetPublicURL: https://ose3-master.example.com:443/console/
    publicURL: https://ose3-master.example.com:443/console/
----

[[requestheader-master-ca-config]]The `*identityProviders*` stanza in the
*_/etc/openshift/master/master-config.yaml_* file must be updated as well:

----
  identityProviders:
  - name: requestheader
    challenge: false
    login: false
    provider:
      apiVersion: v1
      kind: RequestHeaderIdentityProvider
      clientCA: /etc/openshift/master/proxyca.crt
      headers:
      - X-Remote-User
----

Now restart everything:

----
# systemctl restart httpd
# systemctl restart openshift-master
----

*Verification*

Test by bypassing the proxy. You should be able to request a token if you supply
the correct client certificate and header:

----
# curl -L -k -H "X-Remote-User: joe" \
  --cert /etc/pki/tls/certs/authproxy.pem \
  https://ose3-master.example.com:8443/oauth/token/request
----

If you do not supply the client certificate, the request should be denied:

----
# curl -L -k -H "X-Remote-User: joe" \
  https://ose3-master.example.com:8443/oauth/token/request
----

*Handling Logouts from the Web Console*

The link:../architecture/infrastructure_components/web_console.html[web
console] manages its own sessions. When a user authenticates to Apache, in this
case there is another session at play. By default if the user clicks the logout
link from the web console, it only clears out the session cookie and delete the
token. However, Apache still thinks the user is logged in and immediately
triggers another log in.

To handle this case, the web console's Asset Server has a setting that allows
admins to specify a logout URL:

----
assetConfig:
  logoutURL: "https://ose3-master.example.com/logout"
----

This page could be another `<Location>` in Apache that loads a static page for
clearing the form of authentication that is in use. This is especially useful
when using `mod_auth_form` in Apache 2.4. Basic Authentication logouts can be
challenging to support across all browsers, so it may simply be useful to
redirect to a page instructing the user to clear their authentication cache or
perhaps run `kdestroy` in the case of Kerberos.

====

[[GitHub]]

=== GitHub

Set *GitHubIdentityProvider* in the `*identityProviders*` stanza to use
https://github.com/[GitHub] as an identity provider, using the
https://developer.github.com/v3/oauth/[OAuth integration].

[NOTE]
====
Using GitHub as an identity provider requires users to get a token using
`<master>/oauth/token/request` to use with command-line tools.
====

.Master Configuration Using *GitHubIdentityProvider*
====

----
oauthConfig:
  ...
  identityProviders:
  - name: github <1>
    challenge: false <2>
    login: true <3>
    provider:
      apiVersion: v1
      kind: GitHubIdentityProvider
      clientID: ... <4>
      clientSecret: ... <5>
----
<1> This provider name is prefixed to the GitHub numeric user ID to form an
identity name. It is also used to build the callback URL.
<2> *GitHubIdentityProvider* cannot be used to send `WWW-Authenticate`
challenges.
<3> When *true*, unauthenticated token requests from web clients (like the web
console) are redirected to GitHub to log in.
<4> The client ID of a
link:https://github.com/settings/applications/new[registered GitHub OAuth
application]. The application must be configured with a callback URL of
`<master>/oauth2callback/<identityProviderName>`.
<5> The client secret issued by GitHub.
====

[[Google]]

=== Google

Set *GoogleIdentityProvider* in the `*identityProviders*` stanza to use Google
as an identity provider, using
https://developers.google.com/identity/protocols/OpenIDConnect[Google's OpenID
Connect integration].

[NOTE]
====
Using Google as an identity provider requires users to get a token using
`<master>/oauth/token/request` to use with command-line tools.
====

.Master Configuration Using *GoogleIdentityProvider*
====

----
oauthConfig:
  ...
  identityProviders:
  - name: google <1>
    challenge: false <2>
    login: true <3>
    provider:
      apiVersion: v1
      kind: GoogleIdentityProvider
      clientID: ... <4>
      clientSecret: ... <5>
      hostedDomain: "" <6>
----
<1> This provider name is prefixed to the Google numeric user ID to form an
identity name. It is also used to build the redirect URL.
<2> *GoogleIdentityProvider* cannot be used to send `WWW-Authenticate`
challenges.
<3> When *true*, unauthenticated token requests from web clients (like the web
console) are redirected to Google to log in.
<4> The client ID of a link:https://console.developers.google.com/[registered
Google project]. The project must be configured with a redirect URI of
`<master>/oauth2callback/<identityProviderName>`.
<5> The client secret issued by Google.
<6> Optional
link:https://developers.google.com/identity/protocols/OpenIDConnect#hd-param[hosted
domain] to restrict sign-in accounts to. If empty, any Google account is allowed
to authenticate.
====

[[OpenID]]

=== OpenID Connect

Set *OpenIDIdentityProvider* in the `*identityProviders*` stanza to integrate
with an OpenID Connect identity provider using an
link:http://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth[Authorization
Code Flow].

[NOTE]
====
*ID Token* and *UserInfo* decryptions are not supported.
====

By default, the *openid* scope is requested. If required, extra scopes can be
specified in the `*extraScopes*` field.

Claims are read from the JWT `id_token` returned from the OpenID identity
provider and, if specified, from the JSON returned by the `*UserInfo*` URL.

At least one claim must be configured to use as the user's identity. The
link:http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims[standard
identity claim] is `sub`.

You can also indicate which claims to use as the user's preferred user name,
display name, and email address. If multiple claims are specified, the first one
with a non-empty value is used. The
link:http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims[standard
claims] are:

[horizontal]
`sub`:: The user identity.
`preferred_username`:: The preferred user name when provisioning a user.
`email`:: Email address.
`name`:: Display name.

[NOTE]
====
Using an OpenID Connect identity provider requires users to get a token using
`<master>/oauth/token/request` to use with command-line tools.
====

.Standard Master Configuration Using *OpenIDIdentityProvider*
====

----
oauthConfig:
  ...
  identityProviders:
  - name: my_openid_connect <1>
    challenge: false <2>
    login: true <3>
    provider:
      apiVersion: v1
      kind: OpenIDIdentityProvider
      clientID: ... <4>
      clientSecret: ... <5>
      claims:
        id:
        - sub <6>
        preferredUsername:
        - preferred_username
        name:
        - name
        email:
        - email
      urls:
        authorize: https://myidp.example.com/oauth2/authorize <7>
        token: https://myidp.example.com/oauth2/token <8>
----
<1> This provider name is prefixed to the value of the identity claim to form an
identity name. It is also used to build the redirect URL.
<2> *OpenIDIdentityProvider* cannot be used to send `WWW-Authenticate`
challenges.
<3> When *true*, unauthenticated token requests from web clients (like the web
console) are redirected to the authorize URL to log in.
<4> The client ID of a client registered with the OpenID provider. The client
must be allowed to redirect to `<master>/oauth2callback/<identityProviderName>`.
<5> The client secret.
<6> Use the value of the `sub` claim in the returned `id_token` as the user's
identity.
<7> link:http://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint[Authorization Endpoint]
described in the OpenID spec. Must use `https`.
<8> link:http://openid.net/specs/openid-connect-core-1_0.html#TokenEndpoint[Token Endpoint]
described in the OpenID spec. Must use `https`.
====

A custom certificate bundle, extra scopes, extra authorization request
parameters, and `*userInfo*` URL can also be specified:

.Full Master Configuration Using *OpenIDIdentityProvider*
====

----
oauthConfig:
  ...
  identityProviders:
  - name: my_openid_connect
    challenge: false
    login: true
    provider:
      apiVersion: v1
      kind: OpenIDIdentityProvider
      clientID: ...
      clientSecret: ...
      ca: my-openid-ca-bundle.crt <1>
      extraScopes: <2>
      - email
      - profile
      extraAuthorizeParameters: <3>
        include_granted_scopes: "true"
      claims:
        id: <4>
        - custom_id_claim
        - sub
        preferredUsername: <5>
        - preferred_username
        - email
        name: <6>
        - nickname
        - given_name
        - name
        email: <7>
        - custom_email_claim
        - email
      urls:
        authorize: https://myidp.example.com/oauth2/authorize
        token: https://myidp.example.com/oauth2/token
        userInfo: https://myidp.example.com/oauth2/userinfo <8>
----
<1> Certificate bundle to use to validate server certificates for the configured
URLs. If empty, system trusted roots are used.
<2> Optional list of scopes to request, in addition to the *openid* scope,
during the authorization token request.
<3> Optional map of extra parameters to add to the authorization token request.
<4> List of claims to use as the identity. First non-empty claim is used. At
least one claim is required. If none of the listed claims have a value,
authentication fails.
<5> List of claims to use as the preferred user name when provisioning a user
for this identity. First non-empty claim is used.
<6> List of claims to use as the display name. First non-empty claim is used.
<7> List of claims to use as the email address. First non-empty claim is used.
<8> link:http://openid.net/specs/openid-connect-core-1_0.html#UserInfo[UserInfo
Endpoint] described in the OpenID spec. Must use `https`.
====

[[token-options]]

== Token Options

The OAuth server generates two kinds of tokens:

[horizontal]
Access tokens:: Longer-lived tokens that grant access to the API.
Authorize codes:: Short-lived tokens whose only use is to be exchanged for
an access token.

Use the `*tokenConfig*` stanza to set token options:

.Master Configuration Token Options
====

----
oauthConfig:
  ...
  tokenConfig:
    accessTokenMaxAgeSeconds: 86400 <1>
    authorizeTokenMaxAgeSeconds: 300 <2>
----
<1> Set `*accessTokenMaxAgeSeconds*` to control the lifetime of access tokens.
The default lifetime is 24 hours.
<2> Set `*authorizeTokenMaxAgeSeconds*` to control the lifetime of authorize
codes. The default lifetime is five minutes.
====

[[grant-options]]

== Grant Options

To configure how the OAuth server responds to token requests for a client the
user has not previously granted permission, set the `*method*` value in the
`*grantConfig*` stanza. Valid values for `*method*` are:

[horizontal]
`auto`:: Auto-approve the grant and retry the request.
`prompt`:: Prompt the user to approve or deny the grant.
`deny`:: Auto-deny the grant and return a failure error to the client.

.Master Configuration Grant Options
====

----
oauthConfig:
  ...
  grantConfig:
    method: auto
----
====

[[session-options]]

== Session Options

The OAuth server uses a signed and encrypted cookie-based session during login
and redirect flows.

Use the `*sessionConfig*` stanza to set session options:

.Master Configuration Session Options
====

----
oauthConfig:
  ...
  sessionConfig:
    sessionMaxAgeSeconds: 300 <1>
    sessionName: ssn <2>
    sessionSecretsFile: "..." <3>
----
<1> Controls the maximum age of a session; sessions auto-expire once a token
request is complete. If link:#grant-options[auto-grant] is not enabled, sessions
must last as long as the user is expected to take to approve or reject a client
authorization request.
<2> Name of the cookie used to store the session.
<3> File name containing serialized `*SessionSecrets*` object. If empty, a
random signing and encryption secret is generated at each server start.
====

If no `*sessionSecretsFile*` is specified, a random signing and encryption
secret is generated at each start of the master server. This means that any
logins in progress will have their sessions invalidated if the master is
restarted. It also means that if multiple masters are configured, they will not
be able to decode sessions generated by one of the other masters.

To specify the signing and encryption secret to use, specify a
`*sessionSecretsFile*`. This allows you separate secret values from the
configuration file and keep the configuration file distributable, for example
for debugging purposes.

Multiple secrets can be specified in the `*sessionSecretsFile*` to enable
rotation. New sessions are signed and encrypted using the first secret in the
list. Existing sessions are decrypted and authenticated by each secret until one
succeeds.

.Session Secret Configuration:
====

----
apiVersion: v1
kind: SessionSecrets
secrets: <1>
- authentication: "..." <2>
  encryption: "..." <3>
- authentication: "..."
  encryption: "..."
...
----
<1> List of secrets used to authenticate and encrypt cookie sessions. At least
one secret must be specified. Each secret must set an authentication and
encryption secret.
<2> Signing secret, used to authenticate sessions using HMAC. Recommended to use
a secret with 32 or 64 bytes.
<3> Encrypting secret, used to encrypt sessions. Must be 16, 24, or 32
characters long, to select AES-128, AES-192, or AES-256.
====
