= Managing Security Context Constraints
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:

toc::[]

== Overview
You can manage
link:../architecture/additional_concepts/authorization.html#security-context-constraints[security context constraints]
in your instance via the `oc` command as a normal API objects.

== Listing Security Context Constraints

[options="nowrap"]
----
$ oc get scc
NAME         PRIV      CAPS      HOSTDIR   SELINUX     RUNASUSER
privileged   true      []        true      RunAsAny    RunAsAny
restricted   false     []        false     MustRunAs   MustRunAsRange
----

== Creating New Security Context Constraints

Creating a new SCC is accomplished with the `oc create` command.  First, define the SCC in a json
or yaml file and then run `oc create` passing the file.

[options="nowrap"]
----
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-admin
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
groups:
- system:serviceaccounts

$ oc create -f scc_admin.json
securitycontextconstraints/scc-admin
$ oc get scc
NAME         PRIV      CAPS      HOSTDIR   SELINUX     RUNASUSER
privileged   true      []        true      RunAsAny    RunAsAny
restricted   false     []        false     MustRunAs   MustRunAsRange
scc-admin    true      []        false     RunAsAny    RunAsAny
----

== Deleting New Security Context Constraints

[options="nowrap"]
----
$ oc delete scc scc-admin
securitycontextconstraints/scc-admin
----

NOTE: If you delete the default security context constraints they will not be regenerated upon
restart unless you delete all security context constraints.  If any constraint already exists
within the system no generation will take place.

== Updating Security Context Constraints

[options="nowrap"]
----
$ oc edit scc privileged
----

== How Do I?

*Grant Access to the Privileged SCC*

In some cases an administrator would like to allow users or groups outside the admin group access
to create more privileged pods.  In this case you may:

1.  Determine the user or group you would like to have access to the SCC
1.  oc edit scc <name>
1.  Add the user or group to the user or group field of the scc

For example, if we would like to allow the e2e-user access to the privileged scc we would add
their user:


====
----
$ oc edit scc privileged

allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
apiVersion: v1
groups:
- system:cluster-admins
- system:nodes
kind: SecurityContextConstraints
metadata:
  creationTimestamp: 2015-06-15T20:44:53Z
  name: privileged
  resourceVersion: "58"
  selfLink: /api/v1/securitycontextconstraints/privileged
  uid: 602a0838-139f-11e5-8aa4-080027c5bfa9
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:openshift-infra:build-controller
- e2e-user <1>
----

<1> The e2e-user added to the users section.

====

*Enable Images to Run With USER in the Dockerfile*

If you would like to relax the security in your cluster so that images are not forced to
run as a pre-allocted UID without granting everyone access to the privileged SCC you may
edit the restricted SCC and change the `runAsUser` strategy.

1.  oc edit scc restricted
1.  change `runAsUser.Type` to `RunAsAny`

Please note that this will allow images to run as the root UID if no USER is specified
in the Dockerfile.

*Use `--mount-host` On the Registry*

It is recommended that persistent volumes be used for registry deployments.  If you are testing
and would like to use the `--mount-host` option the recommended way to do so is

1.  Create a new service account
1.  Add the service account user name to privileged SCC using `oc edit scc privileged` (please note that a fully qualified service account user name is in the form of
system:serviceaccount:<namesapce>:<name>).
1.  Set the service account using `--service-account=<name>` in the `oadm registry` command


