[[admin-guide-pruning-resources]]
= Pruning Objects
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:

toc::[]

ifdef::openshift-dedicated[]
include::admin_guide/osd_request.adoc[]
endif::[]


== Overview
Over time, xref:../architecture/core_concepts/index.adoc#architecture-core-concepts-index[API objects] created
in {product-title} can accumulate in the
xref:../architecture/infrastructure_components/kubernetes_infrastructure.adoc#master[etcd
data store] through normal user operations, such as when building and deploying
applications.

As an administrator, you can periodically prune older versions of objects from
your {product-title} instance that are no longer needed. For example, by pruning
images you can delete older images and layers that are no longer in use, but are
still taking up disk space.

[[prune-operations]]

== Basic Prune Operations
The CLI groups prune operations under a common parent command.

----
$ oadm prune <object_type> <options>
----

This specifies:

- The `<object_type>` to perform the action on, such as `builds`,
`deployments`, or `images`.
- The `<options>` supported to prune that object type.

[[pruning-deployments]]

== Pruning Deployments

In order to prune deployments that are no longer required by the system due to
age and status, administrators may run the following command:

----
$ oadm prune deployments [<options>]
----

.Prune Deployments CLI Configuration Options
[cols="4,8",options="header"]
|===

|Option |Description

.^|`--confirm`
|Indicate that pruning should occur, instead of performing a dry-run.

.^|`--orphans`
|Prune all deployments whose deployment config no longer exists, status is
complete or failed, and replica count is zero.

.^|`--keep-complete=<N>`
|Per deployment config, keep the last N deployments whose status is complete and
replica count is zero. (default `5`)

.^|`--keep-failed=<N>`
|Per deployment config, keep the last N deployments whose status is failed and
replica count is zero. (default `1`)

.^|`--keep-younger-than=<duration>`
|Do not prune any object that is younger than `<duration>` relative to the
current time. (default `60m`)
|===

To see what a pruning operation would delete:

----
$ oadm prune deployments --orphans --keep-complete=5 --keep-failed=1 \
    --keep-younger-than=60m
----

To actually perform the prune operation:

----
$ oadm prune deployments --orphans --keep-complete=5 --keep-failed=1 \
    --keep-younger-than=60m --confirm
----

[[pruning-builds]]

== Pruning Builds

In order to prune builds that are no longer required by the system due to age
and status, administrators may run the following command:

----
$ oadm prune builds [<options>]
----

.Prune Builds CLI Configuration Options
[cols="4,8",options="header"]
|===

|Option |Description

.^|`--confirm`
|Indicate that pruning should occur, instead of performing a dry-run.

.^|`--orphans`
|Prune all builds whose build config no longer exists, status is complete,
failed, error, or canceled.

.^|`--keep-complete=<N>`
|Per build config, keep the last N builds whose status is complete. (default
`5`)

.^|`--keep-failed=<N>`
|Per build config, keep the last N builds whose status is failed, error, or
canceled (default `1`)

.^|`--keep-younger-than=<duration>`
|Do not prune any object that is younger than `<duration>` relative to the
current time. (default `60m`)
|===

To see what a pruning operation would delete:

----
$ oadm prune builds --orphans --keep-complete=5 --keep-failed=1 \
    --keep-younger-than=60m
----

To actually perform the prune operation:

----
$ oadm prune builds --orphans --keep-complete=5 --keep-failed=1 \
    --keep-younger-than=60m --confirm
----

[NOTE]
====
Developers can enable xref:../../dev_guide/advanced_build_operations.adoc#build-pruning[automatic build pruning]
by modifying their build configuration.
====

[[pruning-images]]

== Pruning Images

In order to prune images that are no longer required by the system due to age,
status, or exceed limits, administrators may run the following command:

----
$ oadm prune images [<options>]
----

[NOTE]
====
Currently, to prune images you must first
xref:../cli_reference/get_started_cli.adoc#basic-setup-and-login[log in to the
CLI] as a user with an
xref:../architecture/additional_concepts/authentication.adoc#oauth[access
token]. The user must also have the
xref:../architecture/additional_concepts/authorization.adoc#roles[cluster role]
*system:image-pruner* or greater (for example, *cluster-admin*).
====

ifdef::openshift-enterprise,openshift-origin[]
[NOTE]
====
Pruning images removes data from the integrated registry. For this operation to work
properly, ensure your
xref:../install_config/registry/extended_registry_configuration.adoc#docker-registry-configuration-reference-storage[registry is configured] with `*storage:delete:enabled*` set to *true*.
====
endif::[]

[NOTE]
====
Pruning images with the `--namespace` flag does not remove images, only image
streams. Images are non-namespaced resources. Therefore, limiting pruning to a
particular namespace makes it impossible to calculate their current usage.
====

.Prune Images CLI Configuration Options
[cols="4,8",options="header"]
|===

|Option |Description

.^|`--certificate-authority`
|The path to a certificate authority file to use when communicating with the
{product-title}-managed registries. Defaults to the certificate authority data
from the current user's config file.

.^|`--confirm`
|Indicate that pruning should occur, instead of performing a dry-run.

.^|`--keep-tag-revisions=<N>`
|For each image stream, keep up to at most N image revisions per tag. (default
`3`)

.^|`--keep-younger-than=<duration>`
|Do not prune any image that is younger than `<duration>` relative to the
current time. Do not prune any image that is referenced by any other object that
is younger than `<duration>` relative to the current time. (default *60m*)

.^|`--prune-over-size-limit`
|Prune each image that exceeds the smallest xref:limits.adoc#image-limits[limit]
defined in the same project. This flag cannot be combined with `--keep-tag-revisions`
nor `--keep-younger-than`.
|===

{product-title} uses the following logic to determine which images and layers to
prune:

[[image-prune-conditions]]
*Image Prune Conditions*

* Remove any image "managed by {product-title}" (images with the annotation
`*openshift.io/image.managed*`) that was created at least
`--keep-younger-than` minutes ago and is not currently referenced by:
- any pod created less than `--keep-younger-than` minutes ago.
- any image stream created less than `--keep-younger-than` minutes ago.
- any running pods.
- any pending pods.
- any replication controllers.
- any deployment configurations.
- any build configurations.
- any builds.
- the `--keep-tag-revisions` most recent items in
 `*stream.status.tags[].items*`.

* Remove any image "managed by {product-title}" (images with the annotation
`*openshift.io/image.managed*`) that is exceeding the smallest xref:limits.adoc#image-limits[limit]
defined in the same project and is not currently referenced by:
- any running pods.
- any pending pods.
- any replication controllers.
- any deployment configurations.
- any build configurations.
- any builds.

* There is no support for pruning from external registries.

* When an image is pruned, all references to the image are removed from all
image streams that have a reference to the image in `*status.tags*`.

* Image layers that are no longer referenced by any images are removed as well.

[NOTE]
====
`--prune-over-size-limit` cannot be combined with `--keep-tag-revisions` nor
`--keep-younger-than` flags. Doing so will return an information that this
operation is not allowed.
====

To see what a pruning operation would delete:

. Keeping up to three tag revisions, and keeping resources (images, image
streams and pods) younger than sixty minutes:
+
====
----
$ oadm prune images --keep-tag-revisions=3 --keep-younger-than=60m
----
====

. Pruning every image that exceeds defined limits:
+
====
----
$ oadm prune images --prune-over-size-limit
----
====

To actually perform the prune operation for the previously mentioned options
accordingly:

----
$ oadm prune images --keep-tag-revisions=3 --keep-younger-than=60m --confirm

$ oadm prune images --prune-over-size-limit --confirm
----

[[image-pruning-problems]]
=== Image Pruning Problems

If your images keep accumulating and the `prune` command removes just a small
portion of what you expect, ensure that you understand
xref:image-prune-conditions[the conditions] that must apply for an image to be
considered a candidate for pruning.

Especially ensure that images you want removed occur at higher positions in each
xref:../architecture/core_concepts/builds_and_image_streams.adoc#image-stream-tag[tag
history] than your chosen tag revisions threshold. For example, consider an old
and obsolete image named `sha:abz`. By running the following command in
namespace `N`, where the image is tagged, you will see the image is tagged three
times in a single image stream named `myapp`:

----
$ image_name="sha:abz"
$ oc get is -n N -o go-template='{{range $isi, $is := .items}}{{range $ti, $tag := $is.status.tags}}'\
  '{{range $ii, $item := $tag.items}}{{if eq $item.image "'"${image_name}"\
  $'"}}{{$is.metadata.name}}:{{$tag.tag}} at position {{$ii}} out of {{len $tag.items}}\n'\
  '{{end}}{{end}}{{end}}{{end}}'
myapp:v2 at position 4 out of 5
myapp:v2.1 at position 2 out of 2
myapp:v2.1-may-2016 at position 0 out of 1
----

When default options are used, the image will not ever be pruned because it
occurs at position `0` in a history of `myapp:v2.1-may-2016` tag. For an image to
be considered for pruning, the administrator must either:

. Specify `--keep-tag-revisions=0` with the `oadm prune images` command.
+
[CAUTION]
====
This action will effectively remove all the tags from all the namespaces with
underlying images, unless they are younger or they are referenced by objects
younger than the specified threshold.
====

. Delete all the
xref:../architecture/core_concepts/builds_and_image_streams.adoc#image-stream-tag[_istags_]
where the position is below the revision threshold, which means
`myapp:v2.1` and `myapp:v2.1-may-2016`.

. Move the image further in the history, either by running new builds pushing to
the same _istag_, or by tagging other image. Unfortunately, this is not always
desirable for old release tags.

Tags having a date or time of a particular image's build in their names should
be avoided, unless the image needs to be preserved for undefined amount of time.
Such tags tend to have just one image in its history, which effectively prevents
them from ever being pruned.
xref:../dev_guide/managing_images.adoc#tag-naming[Learn more about _istag_
naming.]
