:_content-type: ASSEMBLY
[id="zero-trust-networking"]
= Zero trust networking
include::_attributes/common-attributes.adoc[]
:context: zero-trust-networking

toc::[]


Zero trust is an approach to designing security architectures based on the premise that every interaction begins in an untrusted state. This contrasts with traditional architectures, which may determine trustworthiness based on whether communication starts inside a firewall. More specifically, zero trust attempts to close gaps in security architectures that rely on implicit trust models and one-time authentication.

Explore the following targeted capabilies of zero trust networking.

[discrete]
== Observability for constant, and retrospective, evaluation

The ability to observe and verify all of the things that make up zero trust networking. This important for intrusion detection, forensics, and is helpful for operational load management.

Leverage:

* xref:../network_observability/network-observability-overview.adoc#network-observability-overview[Network Observability Operator]
* Istio
* Istio Ambient Mesh
* Service Mesh
* Service Interconnect
* Red Hat Advanced Cluster Security for Kubernetes
* 3Scale (API Gateway)
* link:https://catalog.redhat.com/software/container-stacks/detail/5ec54a5c78e79e6a879fa271[Red Hat OpenShift distributed tracing platform]
* Kiali

[discrete]
== Risk assessment

The ability to examine policies to make it easier for people to understand and develop.

Leverage:

* Kubernetes Network Policy
* Red Hat Advanced Cluster Security for Kubernetes

[discrete]
== Identification and authentication

Establishing a trust relationship by verification of the identity of the other end of a connection. Management of certificate lifecycles to limit use if compromised.

Leverage:

* Istio and Envoy (pod-to-pod)
* cert-manager
* Istio
* Istio Ambient Mesh
* Service Mesh
* Service Interconnect
* Kuadrant’s Authorino
* Red Hat SSO
* OpenShift service certificates

[discrete]
== Inter-service authorization

The ability to control access to services based on request identity.

Leverage:

* Kubernetes Network Policy
* Admin Network Policy
* Istio
* Istio Ambient Mesh
* Service Mesh
* Kuadrant’s Authorino

[discrete]
== Traffic authentication and encryption

The ability to ensure that traffic on-the-wire is encrypted and that the source is identifiable. An example of this is Mutual TLS, or mTLS, which is a method for mutual authentication.

Leverage: 

* Kubernetes Network Policy
* Admin Network Policy
* IPsec (North to South)
* IPsec (East to West, node-to-node)
* Istio
* Istio Ambient Mesh
* Service Mesh


[discrete]
== Endpoint security

Enabling trust of remote endpoint connections to, for example, ensure certified images are run on trusted hardware and policies controlling an endpoint can be established based on endpoint characteristics.

Leverage:

* OpenShift service certificates

[discrete]
== Session validation and session validity expiration (current session only)

The ability to issue short-lived tokens, perhaps even single-use tokens, so that tokens from a compromised pod are useless elsewhere.

Leverage:

* OpenShift service certificates
* Istio
* Kuadrant’s Authorino
* Insights

[discrete]
== Transaction-level verification

The ability to identify and authenticate individual transactions. This can include rate-limiting by source, observability, and semantic validation that a transaction is well formed.

Leverage:

* Istio
* Istio Ambient Mesh
* Service Mesh
* Kuadrant’s Authorino
* Kuadrant’s Limitador

[discrete]
== Sitewide Policy enforcement and distribution

The ability to apply and govern site-wide policies. This should allow for delegation of some permissions to users and cluster administrators within defined bounds.

Leverage:

* Kubernetes Network Policy
* Admin Network Policy
* Istio
* Istio Ambient Mesh
* Service Mesh
* Red Hat Advanced Cluster Management for Kubernetes
* Kuadrant’s Multi-cluster GW Controller Gateway API
* RBAC