// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="core-apis"]
= Core APIs
:toc: macro
:toc-title:

toc::[]

== Binding [v1]

Description::
+
--
Binding ties one object to another; for example, a pod is bound to a node by a scheduler. Deprecated in 1.7, please use the bindings subresource of pods instead.
--

Type::
  `object`

== ComponentStatus [v1]

Description::
+
--
ComponentStatus (and ComponentStatusList) holds the cluster validation info. Deprecated: This API is deprecated in v1.19+
--

Type::
  `object`

== ConfigMap [v1]

Description::
+
--
ConfigMap holds configuration data for pods to consume.
--

Type::
  `object`

== Endpoints [v1]

Description::
+
--
Endpoints is a collection of endpoints that implement the actual service. Example:

	 Name: "mysvc",
	 Subsets: [
	   {
	     Addresses: [{"ip": "10.10.1.1"}, {"ip": "10.10.2.2"}],
	     Ports: [{"name": "a", "port": 8675}, {"name": "b", "port": 309}]
	   },
	   {
	     Addresses: [{"ip": "10.10.3.3"}],
	     Ports: [{"name": "a", "port": 93}, {"name": "b", "port": 76}]
	   },
	]
--

Type::
  `object`

== Event [v1]

Description::
+
--
Event is a report of an event somewhere in the cluster.  Events have a limited retention time and triggers and messages may evolve with time.  Event consumers should not rely on the timing of an event with a given Reason reflecting a consistent underlying trigger, or the continued existence of events with that Reason.  Events should be treated as informative, best-effort, supplemental data.
--

Type::
  `object`

== LimitRange [v1]

Description::
+
--
LimitRange sets resource usage limits for each kind of resource in a Namespace.
--

Type::
  `object`

== Namespace [v1]

Description::
+
--
Namespace provides a scope for Names. Use of multiple namespaces is optional.
--

Type::
  `object`

== Node [v1]

Description::
+
--
Node is a worker node in Kubernetes. Each node will have a unique identifier in the cache (i.e. in etcd).
--

Type::
  `object`

== PersistentVolume [v1]

Description::
+
--
PersistentVolume (PV) is a storage resource provisioned by an administrator. It is analogous to a node. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes
--

Type::
  `object`

== PersistentVolumeClaim [v1]

Description::
+
--
PersistentVolumeClaim is a user's request for and claim to a persistent volume
--

Type::
  `object`

== Pod [v1]

Description::
+
--
Pod is a collection of containers that can run on a host. This resource is created by clients and scheduled onto hosts.
--

Type::
  `object`

== PodTemplate [v1]

Description::
+
--
PodTemplate describes a template for creating copies of a predefined pod.
--

Type::
  `object`

== ReplicationController [v1]

Description::
+
--
ReplicationController represents the configuration of a replication controller.
--

Type::
  `object`

== ResourceQuota [v1]

Description::
+
--
ResourceQuota sets aggregate quota restrictions enforced per namespace
--

Type::
  `object`

== Secret [v1]

Description::
+
--
Secret holds secret data of a certain type. The total bytes of the values in the Data field must be less than MaxSecretSize bytes.
--

Type::
  `object`

== Service [v1]

Description::
+
--
Service is a named abstraction of software service (for example, mysql) consisting of local port (for example 3306) that the proxy listens on, and the selector that determines which pods will answer requests sent through the proxy.
--

Type::
  `object`

== ServiceAccount [v1]

Description::
+
--
ServiceAccount binds together: * a name, understood by users, and perhaps by peripheral systems, for an identity * a principal that can be authenticated and authorized * a set of secrets
--

Type::
  `object`

