:_mod-docs-content-type: ASSEMBLY
[id="understanding-the-cluster-compare-plugin"]
= Understanding the cluster-compare plugin
include::_attributes/common-attributes.adoc[]
:context: understanding-cluster-compare

toc::[]

The `cluster-compare` plugin compares a cluster configuration with a reference configuration. The plugin reports configuration differences while suppressing expected variations by using configurable validation rules and templates. 

Use the `cluster-compare` plugin in development, production, and support scenarios to ensure cluster compliance with a reference configuration, and to quickly identify and troubleshoot relevant configuration differences.

include::modules/cluster-compare-overview.adoc[leveloffset=+1]

include::modules/understanding-a-reference-config.adoc[leveloffset=+1]


[role="_additional-resources"]
== Additional resources

* This section is optional.
* Provide a bulleted list of links to other closely-related material. These links can include `link:` and `xref:` macros.
* Use an unnumbered bullet (*) if the list includes only one step.



