[id="about-openshift-sdn"]
= About the OpenShift SDN default CNI network provider
include::modules/common-attributes.adoc[]
:context: about-openshift-sdn

toc::[]

{product-title} uses a software-defined networking (SDN) approach to provide a
unified cluster network that enables communication between pods across the
{product-title} cluster. This pod network is established and maintained by the
OpenShift SDN, which configures an overlay network using Open vSwitch (OVS).

ifdef::openshift-enterprise,openshift-webscale,openshift-origin[]
OpenShift SDN provides three SDN modes for configuring the pod network:

* The _network policy_ mode allows project administrators to configure their own
isolation policies using xref:../../networking/network_policy/about-network-policy.adoc#about-network-policy[NetworkPolicy objects].
Network policy is the default mode in {product-title} {product-version}.

* The _multitenant_ mode provides project-level isolation for pods and services.
pods from different projects cannot send packets to or receive packets from pods
and services of a different project. You can disable isolation for a project,
allowing it to send network traffic to all pods and services in the entire
cluster and receive network traffic from those pods and services.

* The _subnet_ mode provides a flat pod network where every pod can
communicate with every other pod and service. The network policy mode provides
the same functionality as the subnet mode.
endif::[]
ifdef::openshift-dedicated[]
OpenShift SDN supports only the _network policy_ mode, which allows project
administrators to configure their own isolation policies by using
xref:../../networking/network_policy/about-network-policy.adoc#about-network-policy[NetworkPolicy objects].
endif::[]

// flipped table for OpenShift SDN
include::modules/nw-ovn-kubernetes-matrix.adoc[leveloffset=+1]
