:_content-type: ASSEMBLY
[id="installing-mirroring-disconnected"]
= Mirroring images for a disconnected installation using the oc-mirror plugin
include::_attributes/common-attributes.adoc[]
:context: installing-mirroring-disconnected

toc::[]

////
General to do list:
* Confirm that no new content was added since I did the reorg of the disconnected install assemblies (up to date as of 2/13)
* Add info about mirroring to a namespace
* Test and get some actual example output
* Use cases for changing image set config between runs
////

You can ensure your clusters only use container images that satisfy your organizational controls on external content. Before you install a cluster on infrastructure that you provision in a restricted network, you must mirror the required container images into that environment. To mirror container images, you must have a registry for mirroring.

You can use the oc-mirror OpenShift CLI (`oc`) plugin to mirror images to a mirror registry in your fully or partially disconnected environments.

:FeatureName: Mirroring images for disconnected environments using the oc-mirror plugin
include::snippets/technology-preview.adoc[leveloffset=+1]

The following steps outline the high-level workflow on how to use the oc-mirror plugin to mirror images to a mirror registry:

. Create an image set configuration file.
. Mirror the image set to the mirror registry.
. Install the `ImageContentSourcePolicy` and `CatalogSource` resources that were generated by oc-mirror into the cluster.
. Repeat these steps to update your mirror registry as necessary.

// About the oc-mirror plugin
include::modules/oc-mirror-about.adoc[leveloffset=+1]

// TODO: Check the content of this module to make sure it's accurate for oc-mirror
include::modules/installation-about-mirror-registry.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* For information about viewing the CRI-O logs to view the image source, see xref:../../installing/validating-an-installation.adoc#viewing-the-image-pull-source_validating-an-installation[Viewing the image pull source].

// TODO: Copied this prereq section + about mirror registry from the orig section. Review/update as necessary
[id="prerequisites_installing-mirroring-disconnected"]
== Prerequisites

* You must have a container image registry that supports link:https://docs.docker.com/registry/spec/manifest-v2-2[Docker v2-2] in the location that will host the {product-title} cluster, such as Red Hat Quay.
+
[NOTE]
====
If you use Red Hat Quay, you must use version 3.6 or later with the oc-mirror plugin. If you have an entitlement to Red Hat Quay, see the documentation on deploying Red Hat Quay link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.6/html/deploy_red_hat_quay_for_proof-of-concept_non-production_purposes/[for proof-of-concept purposes] or link:https://access.redhat.com/documentation/en-us/red_hat_quay/3.6/html/deploy_red_hat_quay_on_openshift_with_the_quay_operator/[by using the Quay Operator]. If you need additional assistance selecting and installing a registry, contact your sales representative or Red Hat Support.
====
+
If you do not already have an existing solution for a container image registry, subscribers of {product-title} are provided a xref:../../installing/disconnected_install/installing-mirroring-creating-registry.adoc#installing-mirroring-creating-registry[mirror registry for Red Hat OpenShift]. The _mirror registry for Red Hat OpenShift_ is included with your subscription and is a small-scale container registry that can be used to mirror the required container images of {product-title} in disconnected installations.

[id="mirroring-preparing-your-hosts"]
== Preparing your mirror hosts

Before you can use the oc-mirror plugin to mirror images, you must install the plugin and create a container image registry credentials file to allow the mirroring from Red Hat to your mirror.

// Installing the oc-mirror OpenShift CLI plugin
include::modules/oc-mirror-installing-plugin.adoc[leveloffset=+2]

[role="_additional-resources"]
.Additional resources

* xref:../../cli_reference/openshift_cli/extending-cli-plugins.adoc#cli-installing-plugins_cli-extend-plugins[Installing and using CLI plugins]

// Configuring credentials that allow images to be mirrored
include::modules/installation-adding-registry-pull-secret.adoc[leveloffset=+2]

// Creating the image set configuration
include::modules/oc-mirror-creating-image-set-config.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* xref:../../installing/disconnected_install/installing-mirroring-disconnected.adoc#oc-mirror-imageset-config-params_installing-mirroring-disconnected[Image set configuration parameters]
* xref:../../installing/disconnected_install/installing-mirroring-disconnected.adoc#oc-mirror-image-set-examples_installing-mirroring-disconnected[Image set configuration examples]

[id="mirroring-image-set"]
== Mirroring an image set to a mirror registry

You can use the oc-mirror CLI plugin to mirror images to a mirror registry in a xref:../../installing/disconnected_install/installing-mirroring-disconnected.adoc#mirroring-image-set-partial[partially disconnected environment] or in a xref:../../installing/disconnected_install/installing-mirroring-disconnected.adoc#mirroring-image-set-full[fully disconnected environment].

These procedures assume that you already have your mirror registry set up.

[id="mirroring-image-set-partial"]
=== Mirroring an image set in a partially disconnected environment

In a partially disconnected environment, you can mirror an image set directly to the target mirror registry.

// Mirroring from mirror to mirror
include::modules/oc-mirror-mirror-to-mirror.adoc[leveloffset=+3]

[id="mirroring-image-set-full"]
=== Mirroring an image set in a fully disconnected environment

To mirror an image set in a fully disconnected environment, you must first xref:../../installing/disconnected_install/installing-mirroring-disconnected.adoc#oc-mirror-mirror-to-disk_installing-mirroring-disconnected[mirror the image set to disk], then xref:../../installing/disconnected_install/installing-mirroring-disconnected.adoc#oc-mirror-disk-to-mirror_installing-mirroring-disconnected[mirror the image set file on disk to a mirror].

// Mirroring from mirror to disk
include::modules/oc-mirror-mirror-to-disk.adoc[leveloffset=+3]

// Mirroring from disk to mirror in a disconnected environment
include::modules/oc-mirror-disk-to-mirror.adoc[leveloffset=+3]

// Installing the ImageContentSourcePolicy and CatalogSource resources into the cluster
include::modules/oc-mirror-updating-cluster-manifests.adoc[leveloffset=+1]

// TODO: Consider whether we want any sort of reference module on how to use `oc mirror` (the 3 ways etc)
// Maybe consider adding the blurb just to the beginning of the procedure modules (the combo of params?)

// Updating your mirror registry with differential updates
include::modules/oc-mirror-differential-updates.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* xref:../../installing/disconnected_install/installing-mirroring-disconnected.adoc#mirroring-image-set-partial[Mirroring an image set in a partially disconnected environment]
* xref:../../installing/disconnected_install/installing-mirroring-disconnected.adoc#mirroring-image-set-full[Mirroring an image set in a fully disconnected environment]
* xref:../../installing/disconnected_install/installing-mirroring-disconnected.adoc#oc-mirror-updating-cluster-manifests_installing-mirroring-disconnected[Installing the ImageContentSourcePolicy and CatalogSource resources into the cluster]

// Image set configuration parameters
include::modules/oc-mirror-imageset-config-params.adoc[leveloffset=+1]

// Image set configuration examples
include::modules/oc-mirror-image-set-config-examples.adoc[leveloffset=+1]

// TODO: Add an additional resources section to link to the non-TP assembly?
