:_mod-docs-content-type: ASSEMBLY
[id="installing-mirroring-disconnected-v2"]
= Mirroring images for a disconnected installation using the oc-mirror plugin V2
include::_attributes/common-attributes.adoc[]
:context: installing-mirroring-disconnected

toc::[]

Running your cluster in a restricted network without direct internet connectivity is possible by installing the cluster from a mirrored set of {product-title} container images in a private registry. This registry must be running at all times provided that the cluster is running. See the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html/installing/disconnected-installation-mirroring#prerequisites_installing-mirroring-disconnected[Prerequisites] section for more information.

You can use the oc-mirror OpenShift CLI (`oc`) plugin to mirror images to a mirror registry in your fully or partially disconnected environments. You must run oc-mirror from a system with internet connectivity in order to download the required images from the official Red Hat registries.

[id="installation-oc-mirror-workflow_{context}"]
== High level workflow
The following steps outline the high-level workflow on how to use the oc-mirror plugin to mirror images to a mirror registry:

. Create an image set configuration file.
. Mirror the image set to the mirror registry by using one of the following methods:
** Mirror an image set directly to the mirror registry.
** Mirror an image set to disk, transfer the image set to the target environment, then upload the image set to the target mirror registry.
. Configure your cluster to use the resources generated by the oc-mirror plugin.
. Repeat these steps to update your mirror registry as necessary.

// About the oc-mirror plugin
include::modules/oc-mirror-about.adoc[leveloffset=+1]

// About V2
include::modules/oc-mirror-v2-about.adoc[leveloffset=+1]

// oc-mirror compatibility and support
include::modules/oc-mirror-support.adoc[leveloffset=+1]

// About the mirror registry
include::modules/installation-about-mirror-registry.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* For information about viewing the CRI-O logs to view the image source, see xref:../../installing/validating-an-installation.adoc#viewing-the-image-pull-source_validating-an-installation[Viewing the image pull source].

[id="prerequisites_installing-mirroring-disconnected"]
== Prerequisites

* You must have a container image registry that supports link:https://docs.docker.com/registry/spec/manifest-v2-2[Docker v2-2] in the location that will host the {product-title} cluster, such as Red Hat Quay.
+
[NOTE]
====
If you use Red Hat Quay, you must use version 3.6 or later with the oc-mirror plugin. If you have an entitlement to Red Hat Quay, see the documentation on deploying Red Hat Quay link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/deploy_red_hat_quay_for_proof-of-concept_non-production_purposes/[for proof-of-concept purposes] or link:https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/deploying_the_red_hat_quay_operator_on_openshift_container_platform/index[by using the Red Hat Quay Operator]. If you need additional assistance selecting and installing a registry, contact your sales representative or Red Hat Support.
====
+
If you do not already have an existing solution for a container image registry, subscribers of {product-title} are provided a link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html/installing/disconnected-installation-mirroring#installing-mirroring-creating-registry[mirror registry for Red Hat OpenShift]. The _mirror registry for Red Hat OpenShift_ is included with your subscription and is a small-scale container registry that can be used to mirror the required container images of {product-title} in disconnected installations.

* Save the file as `$XDG_RUNTIME_DIR/containers/auth.json`.

[id="using-oc-mirror"]
== Using oc-mirror

The instructions in this section will show how to prepare the environment and use oc-mirror.

.Environment Preparation

Setting up the credentials for pulling/pushing container images: In order to be able to pull the container images from the container registry, it is necessary to download the pull secret and place it in the correct path.
The default podman credentials location (`$XDG_RUNTIME_DIR/containers/auth`) is used for authenticating to the registries. The docker location `~/.docker/config.json` for credentials is also supported.
* [Optional step] Running a local registry to be used as a destination:
----
$ podman run -dt -p 6000:5000 -e REGISTRY_STORAGE_DELETE_ENABLED=true --name local-registry docker.io/library/registry:2
----

[id="building-image-set-config-v2"]
== Building the image set configuration
The Image Set Configuration is the input file used by oc-mirror to discover which images are necessary to be mirrored.
Below is an example which included an Openshift Release (version 4.13.10), an operator catalog with only 3 operators and some additional images (ubi8 and ubi9):

[source,yaml]
----
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.13
      minVersion: 4.13.10
      maxVersion: 4.13.10
    graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.15
      packages:
       - name: aws-load-balancer-operator
       - name: 3scale-operator
       - name: node-observability-operator
  additionalImages:
   - name: registry.redhat.io/ubi8/ubi:latest
   - name: registry.redhat.io/ubi9/ubi@sha256:20f695d2a91352d4eaa25107535126727b5945bff38ed36a3e59590f495046f0
----

* More Image Set Configuration examples can be found in the additional resources.

[id="oc-mirror-workflows"]
== oc-mirror workflows

This section will explain all the workflows supported by oc-mirror currently.

.Mirror to Disk
Pulls the container images from the source specified in the image set configuration and pack them into a `tar` archive on disk (local directory).
----
$ oc-mirror -c isc.yaml <file path> --v2
----

.Disk to Mirror
Copies the container images from the `tar` archive to a container registry (--from flag is required on this workflow).
----
$ oc-mirror -c isc.yaml --from file:///home/<user>/oc-mirror/mirror1 docker://localhost:6000 --v2
----

.Mirror To Mirror

Copies the container images from the source specified in the image set configuration to the destination (container registry).
----
$ oc-mirror -c isc.yaml --workspace file:///home/<user>/oc-mirror/mirror1 docker://localhost:6000 --v2
----

[id="oc-mirror-use-cases"]
== Use cases

include::modules/command-reference-v2.md[leveloffset=+1]