:_newdoc-version: 2.18.4
:_template-generated: 2025-05-20
:_mod-docs-content-type: PROCEDURE

[id="deploying-a-clusterlogforwarder-observability-custom-resource_{context}"]
= Deploying a ClusterLogForwarder observability custom resource

Deploy a ClusterLogForwarder observability custom resource (CR) by using the {oc-first} command. The following procedure demonstrates using Lokistack as the log store.

.Prerequisites
* You have administrator permissions.
* You installed the {oc-first}.
* You have created a service account.
* You have installed LokiStack.

.Procedure
. Create a ClusterLogForwarder observability custom resource (CR).
+
[source,yaml]
----
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: collector
  namespace: openshift-logging
spec:
  serviceAccount:
    name: <Name_of_service_account>
  outputs:
  - name: default-lokistack
    type: lokiStack
    lokiStack:
      target:
        name: <Name_of_LokiStack>
        namespace: openshift-logging
      authentication:
        token:
          from: serviceAccount
    tls:
      ca:
        key: service-ca.crt
        configMapName: openshift-service-ca.crt
  pipelines:
  - name: default-logstore
    inputRefs:
    - application
    - infrastructure
    outputRefs:
    - default-lokistack
----

. Deply the CR by running the following command:
+
[source,terminal]
----
oc create -f <file_name>.yaml
----

////
.Verification
Delete this section if it does not apply to your module. Provide the user with verification methods for the procedure, such as expected output or commands that confirm success or failure.

* Provide an example of expected command output or a pop-up window that the user receives when the procedure is successful.
* List actions for the user to complete, such as entering a command, to determine the success or failure of the procedure.
* Make each step an instruction.
* Use an unnumbered bullet (*) if the verification includes only one step.

////