= Installing Client Tools on openSUSE
{product-author}
{product-version}
:data-uri:
:icons:
:toc:
:toc-placement!:
:toc-title: Topics Covered

toc::[]

== Overview
Installing the client tools on openSUSE requires sudoer or root access and comprises three steps:

*Step 1*: Install *_Ruby_* + 
*Step 2*: Install *_RubyGems_* + 
*Step 3*: Install *_Git_* + 
*Step 4*: Install the client tools

[NOTE]
====  
The +sudo+ command only works if the particular user is listed in the _sudoers_ file. As an alternative to sudo access, you can activate a root terminal with the +su+ command and the root password. If you activate a root terminal, omit +sudo+ from the commands shown in the examples. Be sure to close the root terminal after the installation completes. 
==== 

== Install Ruby

From terminal, run the following command to install Ruby:

----
$ sudo zypper install ruby
----

Run the following command to verify that Ruby has installed correctly:

----
$ ruby -e 'puts "Welcome to Ruby"'
Welcome to Ruby
----

== Install RubyGems

Run the following command to install RubyGems:

----
$ sudo zypper install rubygems
----

== Install Git 

Run the following command to install Git version control:

----
$ sudo zypper install git-core
----

After installation completes, run the following command to verify that Git has installed correctly:

----
$ git --version
git version 1.7.11.1
----

This command returns the Git version number that was installed. 


== Install the Client Tools

When the required software has been successfully installed, run the following command to install the client tools:

----
$ sudo gem install rhc
----

When the installation completes, proceed to link:configuring_client_tools.html[configure] the client tools using the interactive setup wizard. 
