:_content-type: ASSEMBLY
[id="cpmso-getting-started"]
= Getting started with the Control Plane Machine Set Operator
include::_attributes/common-attributes.adoc[]
:context: cpmso-getting-started

toc::[]

For AWS, {product-title} clusters that are created with version 4.12 or later use the Control Plane Machine Set Operator by default. 

To use this Operator on AWS clusters that are upgraded to {product-title} version 4.12 or later from an earlier version, you must xref:../../machine_management/control_plane_machine_management/cpmso-getting-started.adoc#cpmso-activating_cpmso-getting-started[activate the Operator].

For Azure and VMware vSphere clusters, you must xref:../../machine_management/control_plane_machine_management/cpmso-getting-started.adoc#cpmso-creating-cr_cpmso-getting-started[create a `ControlPlaneMachineSet` custom resource (CR)] and then xref:../../machine_management/control_plane_machine_management/cpmso-getting-started.adoc#cpmso-activating_cpmso-getting-started[activate the Operator].

.Control Plane Machine Set Operator implementation matrix
[cols="<.^3,^.^2,^.^2"]
|====
|Cloud provider |Generated CR provided |Manual CR required

|Amazon Web Services (AWS)
|X ^[1]^
|

|Microsoft Azure
|
|X

|VMware vSphere
|
|X ^[2]^
|====
[.small]
--
1. Clusters installed prior to version 4.12 require Operator activation.
2. This provider does not support failure domains.
--

//Activating the Control Plane Machine Set Operator
include::modules/cpmso-activating.adoc[leveloffset=+1]

//Creating a control plane machine set custom resource
include::modules/cpmso-creating-cr.adoc[leveloffset=+1]