////
Module included in the following assemblies:

install_config/configuring_gce.adoc
////

[id='configuring-gcp-permissions_{context}']
= Configuring authorization for Google Cloud Platform

*Roles*

Configuring GCP for {product-title} requires the following GCP role:

[cols='1,3']
|===

|`roles/owner`
|Needed for creating service accounts, cloud storage, instances, images,
templates, Cloud DNS entries, and to deploy load balancers and health checks.
|===

`delete` permissions might also be required if the user is expected to redeploy the environment during testing phases.

You can also create a service account to avoid using personal users when
deploying GCP objects.

See link:https://cloud.google.com/iam/docs/understanding-roles[the Understanding roles section of the GCP documentation] for more information, including steps for how to configure roles.

*Scopes and service accounts*

GCP uses scopes to determine if an authenticated identity is authorized to
perform operations within a resource. For example, if application A with a
read-only scope access token can only read, while application B with a
read-write scope access token can read and modify data.

The scopes are defined at the GCP API level as `https://www.googleapis.com/auth/compute.readonly`.

You can specify scopes using the `--scopes=[SCOPE,...]` option when creating
instances, or you can use the `--no-scopes` option to create the instance
without scopes if you don't want the instance accessing the GCP API.

See
link:https://cloud.google.com/compute/docs/access/service-accounts#accesscopesiam[the Scopes section of the GCP documentation] for more information.

All GCP projects include a default
`[PROJECT_NUMBER]-compute@developer.gserviceaccount.com` service account with
project editor permissions.

By default, a newly created instance is automatically enabled to run as
the default service account with the following access scopes:

* https://www.googleapis.com/auth/devstorage.read_only
* https://www.googleapis.com/auth/logging.write
* https://www.googleapis.com/auth/monitoring.write
* https://www.googleapis.com/auth/pubsub
* https://www.googleapis.com/auth/service.management.readonly
* https://www.googleapis.com/auth/servicecontrol
* https://www.googleapis.com/auth/trace.append
* https://www.googleapis.com/auth/bigquery
* https://www.googleapis.com/auth/cloud-platform
* https://www.googleapis.com/auth/compute.readonly
* https://www.googleapis.com/auth/compute
* https://www.googleapis.com/auth/datastore
* https://www.googleapis.com/auth/logging.write
* https://www.googleapis.com/auth/monitoring
* https://www.googleapis.com/auth/monitoring.write
* https://www.googleapis.com/auth/servicecontrol
* https://www.googleapis.com/auth/service.management.readonly
* https://www.googleapis.com/auth/sqlservice.admin
* https://www.googleapis.com/auth/devstorage.full_control
* https://www.googleapis.com/auth/devstorage.read_only
* https://www.googleapis.com/auth/devstorage.read_write
* https://www.googleapis.com/auth/taskqueue
* https://www.googleapis.com/auth/userinfo.email

You can specify another service account with the
`--service-account=SERVICE_ACCOUNT` option when creating the instance, or
explicitly disabling service accounts for the instance using the
`--no-service-account` option using the `gcloud` CLI.

See the link:https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances[Creating a new service account section of the GCP documentation] for more information.

