[[osp-sdns]]
=== {product-title} SDN

The default {product-title} SDN is
xref:../architecture/networking/sdn.adoc#architecture-additional-concepts-sdn[OpenShiftSDN].
There is another option: use xref:../install_config/configuring_kuryrsdn.adoc#kuryr-sdn-and-openshift[Kuryr SDN].


[[kuryr-sdn]]
=== Kuryr SDN

Kuryr is a CNI plug-in that uses Neutron and Octavia to provide networking for pods
and services. It is primarily designed for {product-title} clusters that run on
OpenStack virtual machines. Kuryr improves the network performance by plugging
{product-title} pods into OpenStack SDN. In addition it provides
interconnectivity between {product-title} pods and OpenStack virtual instances.

Kuryr is recommended for {product-title} deployments on encapsulated OpenStack
tenant networks in order to avoid double encapsulation, such as running an
encapsulated OpenShift SDN over an OpenStack network. Kuryr is recommended
whenever VXLAN, GRE, or GENEVE are required.

Conversely, implementing Kuryr does not make sense in the following cases:

* You use provider networks, tenant VLANs, or a third party commercial SDN such as
Cisco ACI or Juniper Contrail.
* The deployment will use many services on a few hypervisors,
or {product-title} virtual machine nodes. Each {product-title} service
creates an Octavia Amphora virtual machine in OpenStack that hosts a
required load balancer.

To enable Kuryr SDN, your environment must meet the following requirements:

* Running OpenStack 13 or later
* Overcloud with Octavia
* Neutron Trunk ports extension enabled
* If ML2/OVS Neutron driver is used the OpenvSwitch firewall driver must be
used, instead of the ovs-hybrid one.
