[[dev-guide-build-strategy-options]]
= Build Strategy Options
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:

toc::[]


ifdef::openshift-online[]
[IMPORTANT]
====
The Docker build strategy is not supported in {product-title}.
====
endif::[]
[[source-to-image-strategy-options]]
== Source-to-Image Strategy Options

The following options are specific to the
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#source-build[S2I
build strategy].

[[s2i-force-pull]]
=== Force Pull

By default, if the builder image specified in the build configuration is
available locally on the node, that image will be used. However, to override the
local image and refresh it from the registry to which the image stream points,
create a `BuildConfig` with the `forcePull` flag set to *true*:

[source,yaml]
----
strategy:
  sourceStrategy:
    from:
      kind: "ImageStreamTag"
      name: "builder-image:latest" <1>
    forcePull: true <2>
----
<1> The builder image being used, where the local version on the node may not be
up to date with the version in the registry to which the image stream points.
<2> This flag causes the local builder image to be ignored and a fresh version
to be pulled from the registry to which the image stream points. Setting
`forcePull` to *false* results in the default behavior of honoring the image
stored locally.

[[incremental-builds]]
=== Incremental Builds

S2I can perform incremental builds, which means it reuses artifacts from
previously-built images. To create an incremental build, create a
`BuildConfig` with the following modification to the strategy definition:

[source,yaml]
----
strategy:
  sourceStrategy:
    from:
      kind: "ImageStreamTag"
      name: "incremental-image:latest" <1>
    incremental: true <2>
----
<1> Specify an image that supports incremental builds. Consult the
documentation of the builder image to determine if it supports this behavior.
<2> This flag controls whether an incremental build is attempted. If the builder
image does not support incremental builds, the build will still succeed, but you
will get a log message stating the incremental build was not successful because
of a missing *_save-artifacts_* script.

[NOTE]
====
See the xref:../../creating_images/s2i.adoc#creating-images-s2i[S2I Requirements] topic for information
on how to create a builder image supporting incremental builds.
====

[[override-builder-image-scripts]]
=== Overriding Builder Image Scripts

You can override the *_assemble_*, *_run_*, and *_save-artifacts_*
xref:../../creating_images/s2i.adoc#s2i-scripts[S2I scripts] provided by the
builder image in one of two ways. Either:

1. Provide an *_assemble_*, *_run_*, and/or *_save-artifacts_* script in the
*_.s2i/bin_* directory of your application source repository, or

2. Provide a URL of a directory containing the scripts as part of the strategy
definition. For example:

[source,yaml]
----
strategy:
  sourceStrategy:
    from:
      kind: "ImageStreamTag"
      name: "builder-image:latest"
    scripts: "http://somehost.com/scripts_directory" <1>
----
<1> This path will have *_run_*, *_assemble_*, and *_save-artifacts_* appended
to it. If any or all scripts are found they will be used in place of the same
named script(s) provided in the image.

[NOTE]
====
Files located at the `scripts` URL take precedence over files located in
*_.s2i/bin_* of the source repository. See the
xref:../../creating_images/s2i.adoc#creating-images-s2i[S2I Requirements] topic and the
link:https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md#sti-scripts[S2I
documentation] for information on how S2I scripts are used.
====

[[configuring-the-source-environment]]
=== Environment Variables

There are two ways to make environment variables available to the
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#source-build[source build]
process and resulting image. xref:environment-files[Environment files] and
xref:buildconfig-environment[*BuildConfig* environment] values. Variables provided will
be present during the build process and in the output image.

[[environment-files]]
==== Environment Files
Source build enables you to set environment values (one per line) inside your
application, by specifying them in a *_.s2i/environment_* file in the source
repository. The environment variables specified in this file are present during
the build process and in the output image. The complete list of supported
environment variables is available in the
xref:../../using_images/index.adoc#using-images-index[documentation] for each image.

If you provide a *_.s2i/environment_* file in your source repository, S2I reads
this file during the build. This allows customization of the build behavior as
the *_assemble_* script may use these variables.

For example, if you want to disable assets compilation for your Rails
application, you can add `DISABLE_ASSET_COMPILATION=true` in the
*_.s2i/environment_* file to cause assets compilation to be skipped during the
build.

In addition to builds, the specified environment variables are also available in
the running application itself. For example, you can add
`RAILS_ENV=development` to the *_.s2i/environment_* file to cause the Rails
application to start in `development` mode instead of `production`.

[[buildconfig-environment]]
==== BuildConfig Environment

You can add environment variables to the `sourceStrategy` definition of the
`BuildConfig`. The environment variables defined there are visible during the
*_assemble_* script execution and will be defined in the output image, making
them also available to the *_run_* script and application code.

For example disabling assets compilation for your Rails application:

[source,yaml]
----
sourceStrategy:
...
  env:
    - name: "DISABLE_ASSET_COMPILATION"
      value: "true"
----

The xref:../../dev_guide/builds/build_environment.adoc#dev-guide-build-build-environment[Build Environment]
section provides more advanced instructions.

You can also manage environment variables defined in the `BuildConfig` with the
xref:../../dev_guide/environment_variables.adoc#dev-guide-environment-variables[`oc set env`] command.

[[adding-secrets-to-source-strategy-build-configs]]
=== Adding Secrets via Web Console

To add a secret to your build configuration so that it can access a private
repository:

. Create a new {product-title} project.

. xref:../../dev_guide/secrets.adoc#dev-guide-secrets[Create a secret] that contains
credentials for accessing a private source code repository.

. Create a
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#source-build[Source-to-Image (S2I)
build configuration].

. On the build configuration editor page or in the `create app from builder image` page of the
xref:../../architecture/infrastructure_components/web_console.adoc#architecture-infrastructure-components-web-console[web
console], set the *Source Secret*.

. Click the *Save* button.

[[adding-secrets-enabling-pulling-and-pushing]]
==== Enabling Pulling and Pushing

Enable pulling to a private registry by setting the `Pull Secret` in the build
configuration and enable pushing by setting the `Push Secret`.

[[ignoring-source-files]]
=== Ignoring Source Files
Source to image supports a `.s2iignore` file, which contains a list of file
patterns that should be ignored. Files in the build working directory, as
provided by the various xref:../../dev_guide/builds/build_inputs.adoc#dev-guide-build-inputs[input
sources], that match a pattern found in the `.s2iignore` file will not be made
available to the `assemble` script.

For more details on the format of the `.s2iignore` file, see the link:https://github.com/openshift/source-to-image#build-workflow[source-to-image documentation].

ifndef::openshift-online[]
[[docker-strategy-options]]
== Docker Strategy Options

The following options are specific to the
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#docker-build[Docker
build strategy].


[[docker-strategy-from]]
=== FROM Image

The `FROM` instruction of the *_Dockerfile_* will be replaced by the `from` of the `BuildConfig`:

[source,yaml]
----
strategy:
  dockerStrategy:
    from:
      kind: "ImageStreamTag"
      name: "debian:latest"
----

[[dockerfile-path]]
=== Dockerfile Path

By default, Docker builds use a Dockerfile (named *_Dockerfile_*) located at the
root of the context specified in the `BuildConfig.spec.source.contextDir`
field.

The `dockerfilePath` field allows the build to use a different path to
locate your Dockerfile, relative to the `BuildConfig.spec.source.contextDir`
field. It can be simply a different file name other than the default
*_Dockerfile_* (for example, *_MyDockerfile_*), or a path to a Dockerfile in a
subdirectory (for example, *_dockerfiles/app1/Dockerfile_*):

[source,yaml]
----
strategy:
  dockerStrategy:
    dockerfilePath: dockerfiles/app1/Dockerfile
----

[[no-cache]]
=== No Cache

Docker builds normally reuse cached layers found on the host performing the
build. Setting the `noCache` option to *true* forces the build to ignore
cached layers and rerun all steps of the *_Dockerfile_*:

[source,yaml]
----
strategy:
  dockerStrategy:
    noCache: true
----

[[docker-force-pull]]
=== Force Pull

By default, if the builder image specified in the build configuration is
available locally on the node, that image will be used. However, to override the
local image and refresh it from the registry to which the image stream points,
create a `BuildConfig` with the `forcePull` flag set to *true*:

[source,yaml]
----
strategy:
  dockerStrategy:
    forcePull: true <1>
----
<1> This flag causes the local builder image to be ignored, and a fresh version
to be pulled from the registry to which the image stream points. Setting
`forcePull` to *false* results in the default behavior of honoring the image
stored locally.

[[docker-strategy-environment]]
=== Environment Variables

To make environment variables available to the
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#docker-build[Docker build]
process and resulting image, you can add environment variables to the
`dockerStrategy` definition of the `BuildConfig`.

The environment variables defined there are inserted as a single `ENV`
Dockerfile instruction right after the `FROM` instruction, so that it can be
referenced later on within the Dockerfile.

The variables are defined during build and stay in the output image, therefore
they will be present in any container that runs that image as well.

For example, defining a custom HTTP proxy to be used during build and runtime:

[source,yaml]
----
dockerStrategy:
...
  env:
    - name: "HTTP_PROXY"
      value: "http://myproxy.net:5187/"
----

ifdef::openshift-enterprise,openshift-origin[]
Cluster administrators can also
xref:../../install_config/http_proxies.adoc#configuring-hosts-for-proxies-using-ansible[configure
global build settings using Ansible].
endif::[]

You can also manage environment variables defined in the `BuildConfig` with the
xref:../../dev_guide/environment_variables.adoc#dev-guide-environment-variables[`oc set env`] command.

[[adding-secrets-to-docker-strategy-build-configs]]
=== Adding Secrets via Web Console

To add a secret to your build configuration so that it can access a private
repository"

. Create a new {product-title} project.

. xref:../../dev_guide/secrets.adoc#dev-guide-secrets[Create a secret] that contains
credentials for accessing a private source code repository.

. Create a
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#docker-build[docker
build configuration].

. On the build configuration editor page or in the *fromimage* page of the
xref:../../architecture/infrastructure_components/web_console.adoc#architecture-infrastructure-components-web-console[web
console], set the *Source Secret*.

. Click the *Save* button.


[[docker-strategy-build-args]]
=== Docker Build Arguments

To set link:http://docs.docker.com/v1.7/reference/api/hub_registry_spec/#docker-registry-1-0[Docker build arguments], add entries to the `BuildArgs` array, which is located in the `dockerStrategy` definition of the `BuildConfig`. For example:

====
[source,yaml]
----
dockerStrategy:
...
  buildArgs:
    - name: "foo"
      value: "bar"
----
====

The build arguments will be passed to Docker when a build is started.

==== Enabling Pulling and Pushing

Enable pulling to a private registry by setting the `Pull Secret` in the build
configuration and enable pushing by setting the `Push Secret`.

[[custom-strategy-options]]
== Custom Strategy Options

The following options are specific to the
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#custom-build[Custom
build strategy].

[[custom-strategy-from]]
=== FROM Image

Use the `customStrategy.from` section to indicate the image to use for the
custom build:

[source,yaml]
----
strategy:
  customStrategy:
    from:
      kind: "DockerImage"
      name: "openshift/sti-image-builder"
----

[[expose-docker-socket]]
=== Exposing the Docker Socket

In order to allow the running of Docker commands and the building of container
images from inside the container, the build container must be bound to an
accessible socket. To do so, set the `exposeDockerSocket` option to *true*:

[source,yaml]
----
strategy:
  customStrategy:
    exposeDockerSocket: true
----

[[custom-secrets]]
=== Secrets

In addition to xref:../../dev_guide/secrets.adoc#dev-guide-secrets[secrets] for
xref:build_inputs.adoc#source-clone-secrets[source] and
xref:build_inputs.adoc#using-docker-credentials-for-private-registries[images] that can
be added to all build types, custom strategies allow adding an arbitrary list of
secrets to the builder pod.

Each secret can be mounted at a specific location:

[source,yaml]
----
strategy:
  customStrategy:
    secrets:
      - secretSource: <1>
          name: "secret1"
        mountPath: "/tmp/secret1" <2>
      - secretSource:
          name: "secret2"
        mountPath: "/tmp/secret2"
----
<1> `secretSource` is a reference to a secret in the same namespace as the
build.
<2> `mountPath` is the path inside the custom builder where the secret should
be mounted.

[[adding-secrets-to-custom-strategy-build-configs]]
==== Adding Secrets via Web Console

To add a secret to your build configuration so that it can access a private
repository:

. Create a new {product-title} project.

. xref:../../dev_guide/secrets.adoc#dev-guide-secrets[Create a secret] that contains
credentials for accessing a private source code repository.

. Create a
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#custom-build[custom
build configuration].

. On the build configuration editor page or in the *fromimage* page of the
xref:../../architecture/infrastructure_components/web_console.adoc#architecture-infrastructure-components-web-console[web
console], set the *Source Secret*.

. Click the *Save* button.

[[enabling-pulling-and-pushing]]
==== Enabling Pulling and Pushing

Enable pulling to a private registry by setting the `Pull Secret` in the build
configuration and enable pushing by setting the `Push Secret`.

[[custom-force-pull]]
=== Force Pull

By default, when setting up the build pod, the build controller checks if the
image specified in the build configuration is available locally on the node. If
so, that image will be used. However, to override the local image and refresh
it from the registry to which the image stream points, create a `BuildConfig`
with the `forcePull` flag set to *true*:

[source,yaml]
----
strategy:
  customStrategy:
    forcePull: true <1>
----
<1> This flag causes the local builder image to be ignored, and a fresh version
to be pulled from the registry to which the image stream points. Setting
`forcePull` to *false* results in the default behavior of honoring the image
stored locally.

[[custom-strategy-environment]]
=== Environment Variables

To make environment variables available to the
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#custom-build[Custom build]
process, you can add environment variables to the `customStrategy` definition
of the `BuildConfig`.

The environment variables defined there are passed to the pod that runs the
custom build.

For example, defining a custom HTTP proxy to be used during build:

[source,yaml]
----
customStrategy:
...
  env:
    - name: "HTTP_PROXY"
      value: "http://myproxy.net:5187/"

----

ifdef::openshift-enterprise,openshift-origin[]
Cluster administrators can also
xref:../../install_config/http_proxies.adoc#configuring-hosts-for-proxies-using-ansible[configure
global build settings using Ansible].
endif::[]

You can also manage environment variables defined in the `BuildConfig` with the
xref:../../dev_guide/environment_variables.adoc#dev-guide-environment-variables[`oc set env`] command.
endif::[]

[[pipeline-strategy-options]]
== Pipeline Strategy Options

The following options are specific to the
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#pipeline-build[Pipeline build strategy].

[[jenkinsfile]]
=== Providing the Jenkinsfile

You can provide the Jenkinsfile in one of two ways:

1. Embed the Jenkinsfile in the build configuration.
2. Include in the build configuration a reference to the
   Git repository that contains the Jenkinsfile.

.Embedded Definition
[source,yaml]
----
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('agent') {
          stage 'build'
          openshiftBuild(buildConfig: 'ruby-sample-build', showBuildLogs: 'true')
          stage 'deploy'
          openshiftDeploy(deploymentConfig: 'frontend')
        }
----

.Reference to Git Repository
[source,yaml]
----
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/openshift/ruby-hello-world"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: some/repo/dir/filename <1>
----
<1> The optional `jenkinsfilePath` field specifies the name of the
    file to use, relative to the source `contextDir`.
    If `contextDir` is omitted, it defaults to the root of the repository.
    If `jenkinsfilePath` is omitted, it defaults to *_Jenkinsfile_*.

[[jenkins-pipeline-strategy-environment]]
=== Environment Variables

To make environment variables available to the
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#pipeline-build[Pipeline build]
process, you can add environment variables to the `jenkinsPipelineStrategy` definition
of the `BuildConfig`.

Once defined, the environment variables will be set as parameters for any Jenkins job associated with the `BuildConfig`.

For example:

[source,yaml]
----
jenkinsPipelineStrategy:
...
  env:
    - name: "FOO"
      value: "BAR"

----

[NOTE]
====
You can also manage environment variables defined in the `BuildConfig` with the
xref:../../dev_guide/environment_variables.adoc#dev-guide-environment-variables[`oc set env`] command.
====

[[mapping-buildconfig-jenkins]]
==== Mapping Between BuildConfig Environment Variables and Jenkins Job Parameters

When a Jenkins job is created or updated based on changes to a Pipeline
strategy `BuildConfig`, any environment variables in the `BuildConfig` are
mapped to Jenkins job parameters definitions, where the default values for the
Jenkins job parameters definitions are the current values of the associated
environment variables.

After the Jenkins job's initial creation, you can still add additional
parameters to the job from the Jenkins console. The parameter names differ from
the names of the environment variables in the `BuildConfig`. The parameters are
honored when builds are started for those Jenkins jobs.

How you start builds for the Jenkins job dictates how the parameters are set. If
you start with `oc start-build`, the values of the environment variables in the
`BuildConfig` are the parameters set for the corresponding job instance. Any
changes you make to the parameters' default values from the Jenkins console are
ignored. The `BuildConfig` values take precedence.

If you start with `oc start-build -e`, the values for the environment variables
specified in the `-e` option take precedence. And if you specify an environment
variable not listed in the `BuildConfig`, they will be added as a Jenkins job
parameter definitions. Also any changes you make from the Jenkins console
to the parameters corresponding to the environment variables are ignored. The
`BuildConfig` and what you specify with `oc start-build -e` takes precedence.

If you start the Jenkins job via the Jenkins console, then you can control the
setting of the parameters via the Jenkins console as part of starting a build
for the job.
