include::modules/serverless-document-attributes.adoc[]
[id="serverless-tracing"]
= Tracing requests using Jaeger
:context: serverless-tracing
include::modules/common-attributes.adoc[]

toc::[]

Using Jaeger with {ServerlessProductName} allows you to enable _distributed tracing_ for your serverless applications on {product-title}.

Distributed tracing records the path of a request through the various services that make up an application.

It is used to tie information about different units of work together, to understand a whole chain of events in a distributed transaction.
The units of work might be executed in different processes or hosts.

Developers can visualize call flows in large architectures with distributed tracing. which is useful for understanding serialization, parallelism, and sources of latency.

For more information about distributed tracing, see xref:../../distr_tracing/distr_tracing_arch/distr-tracing-architecture.adoc#distributed-tracing-architecture[distributed tracing architecture] and xref:../../distr_tracing/distr_tracing_install/distr-tracing-installing.adoc#install-distributed-tracing[Installing distributed tracing].

// Serverless specific modules
include::modules/serverless-jaeger-config.adoc[leveloffset=+1]
