[[install-config-adding-hosts-to-cluster]]
= Adding Hosts to an Existing Cluster
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:
:context: adding-hosts-to-cluster

toc::[]


include::admin_guide/topics/proc_adding-hosts.adoc[leveloffset=+1]

[[adding-etcd-hosts-to-existing-cluster]]
== Adding etcd Hosts to existing cluster
You can add new etcd hosts to your cluster by running the _etcd scaleup_
playbook. This playbook queries the master, generates and distributes new
certificates for the new hosts, and then runs the configuration playbooks on the
new hosts only. Before running the etcd *_scaleup.yml_* playbook, complete all
prerequisite
xref:../install/host_preparation.adoc#install-config-install-host-preparation[host
preparation] steps.

[WARNING]
====
These steps will synchronize the settings in the Ansible inventory with the cluster. Ensure that any local changes are shown in the Ansible inventory.
====

To add an etcd host to an existing cluster:

. Ensure you have the latest playbooks by updating the *openshift-ansible* package:
+
----
# yum update openshift-ansible
----

. Edit your *_/etc/ansible/hosts_* file, add *new_<host_type>* to the
*[OSEv3:children]* group and add hosts under the *new_<host_type>* group. For
example, to add a new etcd, add *new_etcd*:
+
----
[OSEv3:children]
masters
nodes
etcd
new_etcd

[etcd]
etcd1.example.com
etcd2.example.com

[new_etcd]
etcd3.example.com
----

. Change to the playbook directory and run the *_openshift_node_group.yml_*
playbook. If your inventory file is located somewhere other than the default of
*_/etc/ansible/hosts_*, specify the location with the `-i` option:
+
----
$ cd /usr/share/ansible/openshift-ansible
$ ansible-playbook [-i /path/to/file] \
  playbooks/openshift-master/openshift_node_group.yml
----
+
This creates the ConfigMap for the new node groups, and ultimately, the
configuration file of the node on the host.
+
[NOTE]
====
Running the *_openshift_node_group.yaml_* playbook only updates new nodes. It cannot be run to update existing nodes in a cluster.
====

. Run the etcd *_scaleup.yml_* playbook. If your inventory file is located somewhere other than the default of *_/etc/ansible/hosts_*, specify the location with the `-i` option:
+
----
$ ansible-playbook [-i /path/to/file] \
  playbooks/openshift-etcd/scaleup.yml
----

. After the playbook completes successfully,
xref:../install/running_install.adoc#advanced-verifying-the-installation[verify the installation].


[[replacing-existing-masters]]
== Replacing existing masters with etcd colocated

Follow these steps when you are migrating your machines to a different data
center and the network and IPs assigned to it will change.

. Back up the primary xref:../day_two_guide/host_level_tasks.adoc#etcd-backup_deprecating-etcd[etcd]
and xref:../day_two_guide/host_level_tasks.adoc#creating-master-backup_deprecating-etcd[master] nodes.
+
[IMPORTANT]
====
Ensure that you back up the *_/etc/etcd/_* directory, as noted in the
xref:../day_two_guide/host_level_tasks.adoc#backing-up-etcd_deprecating-etcd[etcd backup]
instructions.
====

. Provision as many new machines as there are masters to replace.

. Add or expand the cluster. For example, if you want to add 3 masters with etcd
colocated, scale up 3 master nodes.

[IMPORTANT]
====
In the initial release of {product-title} version 3.11, the *_scaleup.yml_*
playbook does not scale up etcd. This is fixed in {product-title} 3.11.59 and
later.
====

.. Add a xref:../install_config/adding_hosts_to_existing_cluster.adoc#adding-cluster-hosts_adding-hosts-to-cluster[master].
In step 3 of that process, add the
host of the new data center in `[new_masters]` and `[new_nodes]`, run the
*_openshift_node_group.yml_* playbook, and run the master *_scaleup.yml_*
playbook.

.. Put the same host in the xref:adding-etcd-hosts-to-existing-cluster[etcd]
section, run the *_openshift_node_group.yml_* playbook, and run the etcd
*_scaleup.yml_* playbook.

.. Verify that the host was added:
+
----
# oc get nodes
----

.. Verify that the master host IP was added:
+
----
# oc get ep kubernetes
----

.. Verify that etcd was added. The value of `ETCDCTL_API` depends on the version
being used:
+
----
# source /etc/etcd/etcd.conf
# ETCDCTL_API=2 etcdctl --cert-file=$ETCD_PEER_CERT_FILE --key-file=$ETCD_PEER_KEY_FILE \
  --ca-file=/etc/etcd/ca.crt --endpoints=$ETCD_LISTEN_CLIENT_URLS member list
----

.. Copy  *_/etc/origin/master/ca.serial.txt_* from the *_/etc/origin/master_*
directory to the new master host that is listed first in your inventory file. By
default, this is *_/etc/ansible/hosts_*.

. Remove the etcd hosts.

.. Copy the *_/etc/etcd/ca_* directory to the new etcd host that is listed first in
your inventory file. By default, this is *_/etc/ansible/hosts_*.

.. Remove the old etcd clients from the *_master-config.yaml_* file:
+
----
# grep etcdClientInfo -A 11 /etc/origin/master/master-config.yaml
----

.. Restart the masters:
+
----
# master-restart api
# master-restart controllers
----

.. Remove the old etcd members from the cluster. The value of `ETCDCTL_API` depends
on the version being used:
+
----
# source /etc/etcd/etcd.conf
# ETCDCTL_API=2 etcdctl --cert-file=$ETCD_PEER_CERT_FILE --key-file=$ETCD_PEER_KEY_FILE \
  --ca-file=/etc/etcd/ca.crt --endpoints=$ETCD_LISTEN_CLIENT_URLS member list
----

.. Take the IDs from the output of the command above and remove the old members
using the IDs:
+
----
# etcdctl --cert-file=$ETCD_PEER_CERT_FILE --key-file=$ETCD_PEER_KEY_FILE \
  --ca-file=/etc/etcd/ca.crt --endpoints=$ETCD_LISTEN_CLIENT_URL member remove 1609b5a3a078c227
----

.. Stop the etcd services on the old etcd hosts by
removing the etcd pod definition:
+
----
# mkdir -p /etc/origin/node/pods-stopped
# mv /etc/origin/node/pods/* /etc/origin/node/pods-stopped/
----

. Shut down old master API and controller services by moving definition files out of the static pods dir /etc/origin/node/pods:
+
----
# mkdir -p /etc/origin/node/pods/disabled
# mv /etc/origin/node/pods/controller.yaml /etc/origin/node/pods/disabled/:
----

. Remove the master nodes from the HA proxy configuration, which was installed as
a load balancer by default during the native installation process.

. Decommission the machine.

.. Stop the node service on the
master to be removed by removing the pod definition and rebooting the host:
+
----
# mkdir -p /etc/origin/node/pods-stopped
# mv /etc/origin/node/pods/* /etc/origin/node/pods-stopped/
# reboot
----

.. Delete the node resource:
+
----
# oc delete node
----

[[migrating-the-nodes]]
== Migrating the nodes

You can migrate nodes individually or in groups (of 2, 5, 10, and so on),
depending on what you are comfortable with and how the services on the node are
run and scaled.

. For the migration node or nodes, provision new VMs for the node's use in the new
data center.

. To add the new node, xref:../install_config/adding_hosts_to_existing_cluster.adoc#adding-cluster-hosts_adding-hosts-to-cluster[scale up the infrastructure].
Ensure the labels for the new node are set properly and that your new API
servers are added to your load balancer and successfully serving traffic.

. Evaluate and scale down.

.. Mark the current node (in the old data center)
xref:../admin_guide/manage_nodes.adoc#marking-nodes-as-unschedulable-or-schedulable[unscheduled].

.. xref:../admin_guide/manage_nodes.adoc#evacuating-pods-on-nodes[Evacuate the
node], so that pods on it are scheduled to other nodes.

.. Verify that the evacuated services are running on the new nodes.

. Remove the node.

.. Verify that the node is empty and does not have running processes.

.. Stop the service or delete the node.
