[[install-config-certificate-customization]]
= Configuring Custom Certificates
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:

toc::[]

== Overview
Administrators can configure custom serving certificates for the public host
names of the {product-title} API and
xref:../architecture/infrastructure_components/web_console.adoc#architecture-infrastructure-components-web-console[web console].
This can be done during an
xref:../install_config/install/advanced_install.adoc#advanced-install-custom-certificates[advanced installation] or configured after installation.

[[ansible-configuring-custom-certificates]]
== Configuring Custom Certificates with Ansible

During
xref:../install_config/install/advanced_install.adoc#install-config-install-advanced-install[advanced installations],
custom certificates can be configured using the
`openshift_master_named_certificates` and
`openshift_master_overwrite_named_certificates` parameters, which are
configurable in the inventory file. More details are available about
xref:../install_config/install/advanced_install.adoc#advanced-install-custom-certificates[configuring custom certificates with Ansible].

.Example Custom Certificate Configuration with Ansible
----
# Configure custom named certificates
# NOTE: openshift_master_named_certificates is cached on masters and is an
# additive fact, meaning that each run with a different set of certificates
# will add the newly provided certificates to the cached set of certificates.
#
# An optional CA may be specified for each named certificate. CAs will
# be added to the OpenShift CA bundle which allows for the named
# certificate to be served for internal cluster communication.
#
# If you would like openshift_master_named_certificates to be overwritten with
# the provided value, specify openshift_master_overwrite_named_certificates.
openshift_master_overwrite_named_certificates=true
#
# Provide local certificate paths which will be deployed to masters
openshift_master_named_certificates=[{"certfile": "/path/on/host/to/custom1.crt", "keyfile": "/path/on/host/to/custom1.key", "cafile": "/path/on/host/to/custom-ca1.crt"}]
#
# Detected names may be overridden by specifying the "names" key
#openshift_master_named_certificates=[{"certfile": "/path/on/host/to/custom1.crt", "keyfile": "/path/on/host/to/custom1.key", "names": ["public-master-host.com"], "cafile": "/path/on/host/to/custom-ca1.crt"}]
----

[[configuring-custom-certificates]]
== Configuring Custom Certificates

In the
xref:../install_config/master_node_configuration.adoc#master-configuration-files[master
configuration file] you can list the `namedCertificates` section in the
`assetConfig.servingInfo` section so the custom certificate serves up for the
web console, and in the `servingInfo` section so the custom certificate serves
up for the CLI and other API calls. Multiple certificates can be configured this
way and each certificate may be associated with multiple host names or
wildcards.

A default certificate must be configured in the `servingInfo.certFile` and
`servingInfo.keyFile` configuration sections in addition to
`namedCertificates`.

[NOTE]
====
The `namedCertificates` section should only be configured for the host name
associated with the `masterPublicURL`, `assetConfig.publicURL`, and
`oauthConfig.assetPublicURL` settings. Using a custom serving certificate for
the host name associated with the `masterURL` will result in TLS errors as
infrastructure components will attempt to contact the master API using the
internal `masterURL` host.
====

.Custom Certificates Configuration
----
servingInfo:
  ...
  namedCertificates:
  - certFile: custom.crt
    keyFile: custom.key
    names:
    - "customhost.com"
    - "api.customhost.com"
    - "console.customhost.com"
  ...
----

Relative paths are resolved relative to the master configuration file. Restart
the server to pick up the configuration changes.

For the master API or web console, wildcard names are accepted.

[[configuring-custom-certificates-lb]]
== Configuring a Custom Certificate for a Load Balancer

If your {product-title} cluster uses the default load balancer or an enterprise-level load balancer, 
you can use custom certificates to make the web console and API available externally using a publicly-signed custom certificate. leaving the existing internal certificates for 
the internal endpoints.

To configure {product-title} to use custom certificates in this way:

. Edit the `servingInfo` section of the xref:../install_config/master_node_configuration.adoc#master-configuration-files[master configuration file]:
+
----
servingInfo:
  logoutURL: ""
  masterPublicURL: https://openshift.example.com:8443
  publicURL: https://openshift.example.com:8443/console/
  namedCertificates:
    bindAddress: 0.0.0.0:8443
    bindNetwork: tcp4
    certFile: master.server.crt
    clientCA: ""
    keyFile: master.server.key
    maxRequestsInFlight: 0
    requestTimeoutSeconds: 0
    namedCertificates:
      - certFile: wildcard.example.com.crt <1>
        keyFile: wildcard.example.com.key <2>
        names:
          - "openshift.example.com"
  metricsPublicURL: "https://metrics.os.example.com/hawkular/metrics"
----
+
<1> Path to the certificate file for the web console.
+
<2> Path to the key file for the web console.
+
[NOTE]
====
Configure the  `namedCertificates` section for only the host name associated with the `masterPublicURL` and `oauthConfig.assetPublicURL` settings.  
Using a custom serving certificate for the host name associated with the `masterURL` causes in TLS errors as infrastructure components 
attempt to contact the master API using the internal masterURL host.
====

. Specify the `openshift_master_cluster_public_hostname` and `openshift_master_cluster_hostname` paramaters in the Ansible inventory file, by default *_/etc/ansible/hosts_*. 
These values must be different. If they are the same, the named certificates will fail.
+
----
# Native HA with External LB VIPs
openshift_master_cluster_hostname=paas.example.com <1>
openshift_master_cluster_public_hostname=public.paas.example.com <2>
----
+
<1> The FQDN for internal load balancer configured for SSL passthrough.
+
<2> The FQDN for external the load balancer with custom (public) certificate.

For information specific to your load balancer environment, refer to link:https://access.redhat.com/documentation/en-us/reference_architectures/?category=openshift%2520container%2520platform&version=current%2520release[the {product-title} Reference Architecture for your provider] and link:http://v1.uncontained.io/playbooks/installation/load_balancing.html#custom-certificate-ssl-termination-production[Custom Certificate SSL Termination (Production)].

