[[install-config-provisioners]]
= Deploying External Persistent Volume Provisioners
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:

toc::[]

== Overview

An external provisioner is an application that enables dynamic provisioning for
a particular storage provider. External provisioners can run alongside the
provisioner plug-ins provided by {product-title} and are configured in a similar
way as the *_StorageClass_* objects are configured, as described in the  xref:../install_config/persistent_storage/dynamically_provisioning_pvs.adoc#install-config-persistent-storage-dynamically-provisioning-pvs[Dynamic Provisioning and Creating Storage Classes] section.
Since these provisioners are external, you can deploy and update them
independently of {product-title}.

[[provisioners-before-you-begin]]
== Before You Begin

[NOTE]
====
Before proceeding, familiarize yourself with the
xref:../install/configuring_inventory_file.adoc#advanced-install-cluster-metrics[Configuring Cluster Metrics] and the xref:../install/configuring_inventory_file.adoc#advanced-install-cluster-logging[Configuring Cluster Logging] sections.
====

[[provisioners-ansible-role]]
=== External Provisioners Ansible Role

The OpenShift Ansible `openshift_provisioners` role configures and deploys
external provisioners using the variables from the
xref:../install/configuring_inventory_file.adoc#configuring-ansible[Ansible]
inventory file. You must specify which provisioners to install by overriding
their respective `install` variables to `true`.

[[provisioners-ansible-variables]]
=== External Provisioners Ansible Variables

Following is a list of role variables that apply to all provisioners for
which the `install` variable is `true`.

.Ansible Variables
[options="header"]
|===

|Variable |Description

|`openshift_provisioners_install_provisioners`
|If `true`, deploy all provisioners that have their respective `install` variables set as `true`, otherwise, remove them.

|`openshift_provisioners_image_prefix`
|The prefix for the component images.
ifdef::openshift-origin[]
For example, with `openshift/origin-efs-provisioner:v1.0.0`, set prefix
`openshift/origin-`.
endif::[]
ifdef::openshift-enterprise[]
Defaults to `registry.access.redhat.com/openshift3/`, set it to a different
value if you are using an alternative registry.
endif::[]

|`openshift_provisioners_image_version`
|The version for the component images.
ifdef::openshift-origin[]
For example, with `openshift/origin-efs-provisioner:v1.0.0`, set version  as
`v1.0.0`.
endif::[]
ifdef::openshift-enterprise[]
Defaults to `latest`.
endif::[]

|`openshift_provisioners_project`
|The project to deploy provisioners in. Defaults to `openshift-infra`.

|===

[[provisioners-efs-ansible-variables]]
=== AWS EFS Provisioner Ansible Variables

The AWS EFS provisioner dynamically provisions
xref:../install_config/persistent_storage/persistent_storage_nfs.adoc#install-config-persistent-storage-persistent-storage-nfs[NFS PVs]
backed by dynamically created directories in a given EFS file system's
directory. You must satisfy the following requirements before the AWS EFS
Provisioner Ansible variables can be configured:

* An IAM user assigned with the *_AmazonElasticFileSystemReadOnlyAccess_* policy (or better).
* An EFS file system in your cluster's region.
* link:http://docs.aws.amazon.com/efs/latest/ug/accessing-fs.html[Mount targets] and link:http://docs.aws.amazon.com/efs/latest/ug/accessing-fs-create-security-groups.html[security groups] such that any node (in any zone in the cluster's region) can mount the EFS file system by its link:http://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-dns-name.html[File system DNS name].

.Required EFS Ansible Variables
[options="header"]
|===

|Variable |Description

|`openshift_provisioners_efs_fsid`
|The link:http://docs.aws.amazon.com/efs/latest/ug/gs-step-two-create-efs-resources.html[File system ID] of the EFS file system, for example: `fs-47a2c22e`

|`openshift_provisioners_efs_region` |The Amazon EC2 region for the EFS file
system.

|`openshift_provisioners_efs_aws_access_key_id` |The AWS access key of the IAM
user (to check that the specified EFS file system exists).

|`openshift_provisioners_efs_aws_secret_access_key` |The AWS secret access key
of the IAM user (to check that the specified EFS file system exists).

|===

.Optional EFS Ansible Variables
[options="header"]
|===

|Variable |Description

|`openshift_provisioners_efs` | If `true`, the AWS EFS provisioner is installed
or uninstalled according to whether
`openshift_provisioners_install_provisioners` is `true` or `false`,
respectively. Defaults to `false`.

|`openshift_provisioners_efs_path` | The path of the directory in the EFS file
system, in which the EFS provisioner will create a directory to back each PV it
creates. It must exist and be mountable by the EFS provisioner. Defaults to
`/persistentvolumes`.

|`openshift_provisioners_efs_name` | The `provisioner` name that
*_StorageClasses_* specify. Defaults to `openshift.org/aws-efs`.

|`openshift_provisioners_efs_nodeselector` | A map of labels to select the nodes
where the pod will land. For example: `{"node":"infra","region":"west"}`.

|`openshift_provisioners_efs_supplementalgroup` | The supplemental group to give
the pod, in case it is needed for permission to write to the EFS file system.
Defaults to `65534`.

|===

[[deploying-the-provisioners]]
== Deploying the Provisioners

You can deploy all provisioners at once or one provisioner at a time according
to the configuration specified in the OpenShift Ansible variables. The following
example shows you how to deploy a given provisioner and then create and
configure a corresponding xref:../install_config/persistent_storage/dynamically_provisioning_pvs.adoc#install-config-persistent-storage-dynamically-provisioning-pvs[_StorageClass_].

[[deploying-the-aws-efs-provisioner]]
=== Deploying the AWS EFS Provisioner
The following command sets the directory in the EFS volume to
`/data/persistentvolumes`. This directory must exist in the file system and must
be mountable and writeable by the provisioner pod.

----
$ ansible-playbook -v -i <inventory_file> \
    /usr/share/ansible/openshift-ansible/playbooks/openshift-provisioners/config.yml \
   -e openshift_provisioners_install_provisioners=True \
   -e openshift_provisioners_efs=True \
   -e openshift_provisioners_efs_fsid=fs-47a2c22e \
   -e openshift_provisioners_efs_region=us-west-2 \
   -e openshift_provisioners_efs_aws_access_key_id=AKIAIOSFODNN7EXAMPLE \
   -e openshift_provisioners_efs_aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY \
   -e openshift_provisioners_efs_path=/data/persistentvolumes
----

[[nfs-selinux-2]]
==== SELinux
For information on allowing the provisioner pod to write to EFS directory (which is a remote NFS directory), see the xref:../install_config/persistent_storage/persistent_storage_nfs.adoc#nfs-selinux[SELinux] section of NFS Volume Security topic. The same information applies for allowing other pods to consume the NFS volumes provisioned by the provisioner pod.

[[aws-efs]]
==== AWS EFS Object Definition

.aws-efs-storageclass.yaml

[source,yaml]
----
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: slow
provisioner: openshift.org/aws-efs <1>
parameters:
  gidMin: "40000" <2>
  gidMax: "50000" <3>
----

<1> Set this value same as the value of `openshift_provisioners_efs_name`
variable, which defaults to `openshift.org/aws-efs`.
<2> The minimum value of
GID range for the *_StorageClass_*. (Optional)
<3> The maximum value of GID
range for the *_StorageClass_*. (Optional)

Each dynamically provisioned volume's corresponding NFS directory is assigned a
unique GID owner from the range `gidMin`-`gidMax`. If it is not specified,
`gidMin` defaults to `2000` and `gidMax` defaults to `2147483647`. Any pod that
consumes a provisioned volume via a claim automatically runs with the needed GID
as a supplemental group and is able to read & write to the volume. Other
mounters that do not have the supplemental group (and are not running as root)
will not be able to read or write to the volume. For more information on using
the supplemental groups to manage NFS access, see the xref:../install_config/persistent_storage/persistent_storage_nfs.adoc#nfs-supplemental-groups[Group IDs] section of NFS Volume Security topic.

[[provisioners-cleanup]]
== Cleanup

You can remove everything deployed by the OpenShift Ansible `openshift_provisioners` role
by running the following command:

----
$ ansible-playbook -v -i <inventory_file> \
    /usr/share/ansible/openshift-ansible/playbooks/openshift-provisioners/config.yml \
   -e openshift_provisioners_install_provisioners=False
----
