:_mod-docs-content-type: ASSEMBLY
[id="using-tekton-chains-for-openshift-pipelines-supply-chain-security"]
= Using Tekton Chains for {pipelines-shortname} supply chain security
include::_attributes/common-attributes.adoc[]
:context: using-tekton-chains-for-openshift-pipelines-supply-chain-security

toc::[]

[role="_abstract"]
{tekton-chains} is a Kubernetes Custom Resource Definition (CRD) controller. You can use it to manage the supply chain security of the tasks and pipelines created using {pipelines-title}.

By default, {tekton-chains} observes all task run executions in your {product-title} cluster. When the task runs complete, {tekton-chains} takes a snapshot of the task runs. It then converts the snapshot to one or more standard payload formats, and finally signs and stores all artifacts.

To capture information about task runs, {tekton-chains} uses `Result` objects. When the objects are unavailable, {tekton-chains} the URLs and qualified digests of the OCI images.

[id="tc-key-features"]
== Key features
* You can sign task runs, task run results, and OCI registry images with cryptographic keys that are generated by tools such as `cosign` and `skopeo`.
* You can use attestation formats such as `in-toto`.
* You can securely store signatures and signed artifacts using OCI repository as a storage backend.

include::modules/op-configuring-tekton-chains.adoc[leveloffset=+1]

include::modules/op-supported-parameters-tekton-chains-configuration.adoc[leveloffset=+2]

include::modules/op-signing-secrets-in-tekton-chains.adoc[leveloffset=+1]
include::modules/op-chains-signing-secrets-cosign.adoc[leveloffset=+2]
include::modules/op-chains-signing-secrets-skopeo.adoc[leveloffset=+2]
include::modules/op-chains-resolving-existing-secret.adoc[leveloffset=+2]

include::modules/op-authenticating-to-an-oci-registry.adoc[leveloffset=+1]

include::modules/op-creating-and-verifying-task-run-signatures-without-any-additional-authentication.adoc[leveloffset=+1]
=== Additional resources

* xref:signing-secrets-in-tekton-chains_{context}[]
* xref:configuring-tekton-chains_{context}[]

include::modules/op-using-tekton-chains-to-sign-and-verify-image-and-provenance.adoc[leveloffset=+1]

[role="_additional-resources"]
[id="additional-resources-tekton-chains"]
== Additional resources

* xref:../../cicd/pipelines/installing-pipelines.adoc#installing-pipelines[Installing {pipelines-shortname}]
