[[supported-configurations]]
= Supported configurations

The following are the only supported configurations for {ProductName} {ProductVersion}:

* Red Hat OpenShift Container Platform version 3.10
+
[NOTE]
====
OpenShift Online and OpenShift Dedicated are not supported for {ProductName} {ProductVersion}.
====
+

* The deployment should be contained to a single {product-title} cluster (no federation).
*  This release of {ProductName} is only available on {product-title} x86_64.
*  {ProductName} is only suited for OpenShift Container Platform Software Defined Networking (SDN) configured as a flat network with no external providers.
* This release only supports configurations where all Service Mesh components are contained in the OpenShift cluster in which it operates.  It does not support management of microservices which reside outside of the cluster, or in a multi-cluster scenario.
////
TODO - Update once the article link goes live.
For more information about support for this technology preview, see this https://access.redhat.com/articles/3580021[Red Hat Knowledge Base article]
////
