[id="ossm-observability"]
= Data visualization and observability 
include::modules/ossm-document-attributes.adoc[]
:context: observability

toc::[]

You can view your application's topology, health and metrics with using the Kiali operator you installed as part of your {ProductName} installation. 

If your service is having issues, Kiali offers ways to visualize the data flowing through your service. Kiali offers insights about the mesh components at different levels, including abstract applications, services, and workloads. It also provides an interactive graph view of your namespace in real time. 

.Prerequisites

* You can observe data flowing through a working service if you install the xref:../../service_mesh/service_mesh_day_two/ossm-example-bookinfo.html#ossm-tutorial-bookinfo-overview_ossm-bookinfo-tutorial[Bookinfo sample application]. 

To send traffic to the mesh, enter the following command a few times:

----
$ curl http://$GATEWAY_URL/productpage
----

If your sample application is configured correctly, this command simulates a user visiting the `productpage` microservice of the application.

include::modules/ossm-observability-access.adoc[leveloffset=+1]

include::modules/ossm-observability-visual.adoc[leveloffset=+1]

