= Installation
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:

toc::[]

== Overview
ifdef::openshift-origin[]
The following sections detail the available installation methods for OpenShift. Choose a method that works best for you. Before continuing, ensure that you have gone through the link:setup.html[Setup] topic, which includes installing and configuring Docker properly.
endif::[]

ifdef::openshift-enterprise[]
During the Beta 1 phase, you can install OpenShift using RPMs. Before continuing, ensure that you have gone through the link:setup.html[Setup] topic, which includes installing and configuring Docker properly.
endif::[]

ifdef::openshift-origin[]
== Running in a Docker Container
You can quickly get OpenShift running in a Docker container using images from Docker Hub.

*Installing and Starting an All-in-One Server*

. Launch the server in a Docker container:
+
----
$ sudo docker run -d --name "openshift-origin" --net=host --privileged \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /tmp/openshift:/tmp/openshift \
openshift/origin start
----
+
NOTE: The `/tmp/openshift` directory must be created the first time.
+
This command:
+
* starts OpenShift listening on all interfaces (https://0.0.0.0:8443),
* starts the Management Console listening on all interfaces (https://0.0.0.0:8443),
* launches an [sysitem]#etcd# server to store persistent data, and
* launches the Kubernetes system components.

. After the container is started, you can open a console inside the container:
+
----
$ sudo docker exec -it openshift-origin bash
----

. Because OpenShift services are secured by TLS, clients must accept the server certificates and present their own client certificate. These certificates are generated when the master server is started. You must point `osc` and `curl` at the appropriate CA bundle and client key and certificate to connect to OpenShift. Set the following environment variables:
+
----
# export KUBECONFIG=/var/lib/openshift/openshift.local.certificates/admin/.kubeconfig
# export CURL_CA_BUNDLE=/var/lib/openshift/openshift.local.certificates/admin/root.crt
----
+
NOTE: When running as a user other than `root`, you would also need to make the private client key readable by that user. However, this is just for example purposes; in a production environment, developers would generate their own keys and not have access to the system keys.

. You can see more about the commands available in the link:../using_openshift/cli.html[CLI] (the `osc` command) with:
+
----
# osc help
----

*What's Next?*

Now that you have OpenShift successfully running in your environment, link:try_it_out.html[try it out] by walking through a sample application lifecycle.
endif::[]

ifdef::openshift-origin[]
== Downloading the Binary
Red Hat periodically publishes binaries to GitHub, which you can download on the OpenShift Origin repository's https://github.com/openshift/origin/releases[Releases] page. These are Linux, Windows, or Mac OS X 64-bit binaries; note that the Mac and Windows versions are for the CLI only.

The `tar` file for each platform contains a single binary, `openshift`, which is an all-in-one OpenShift installation. The file also contains the link:../using_openshift/cli.html[CLI] (the `osc` command).

*Installing and Running an All-in-One Server*

. Download and untar the binary from the https://github.com/openshift/origin/releases[Releases] page on your local system.

. Launch the server:
+
----
$ sudo ./openshift start
----
+
This command:
+
* starts OpenShift listening on all interfaces (https://0.0.0.0:8443),
* starts the Management Console listening on all interfaces (https://0.0.0.0:8443),
* launches an [sysitem]#etcd# server to store persistent data, and
* launches the Kubernetes system components.
+
The server runs in the foreground until you terminate the process.
+
NOTE: This command requires `root` access to create services due to the need to modify `iptables`. See https://github.com/GoogleCloudPlatform/kubernetes/issues/1859[this Issue] for more information.

. You can see more about the commands available in the binary with:
+
----
$ ./openshift help
----

. Because OpenShift services are secured by TLS, clients must accept the server certificates and present their own client certificate. These certificates are generated when the master server is started. You must point `osc` and `curl` at the appropriate CA bundle and client key and certificate to connect to OpenShift. Set the following environment variables:
+
----
$ export KUBECONFIG=`pwd`/openshift.local.certificates/admin/.kubeconfig
$ export CURL_CA_BUNDLE=`pwd`/openshift.local.certificates/admin/root.crt
$ sudo chmod +r `pwd`/openshift.local.certificates/admin/.kubeconfig
----
+
NOTE: This is just for example purposes; in a production environment, developers would generate their own keys and not have access to the system keys.

. You can see more about the commands available in the CLI with:
+
----
$ ./osc help
----
+
Or connect from another system with:
+
----
$ ./osc -h <server_hostname_or_IP> [...]
----

*What's Next?*

Now that you have OpenShift successfully running in your environment, link:try_it_out.html[try it out] by walking through a sample application lifecycle.

== Building from Source
You can build OpenShift from source locally or using https://www.vagrantup.com/[Vagrant]. See the OpenShift Origin repository https://github.com/openshift/origin#start-developing[README] on GitHub for more information.
endif::[]

== Installing RPMs

ifdef::openshift-origin[]
Installation packages for OpenShift Origin will be made available soon.
endif::[]

ifdef::openshift-enterprise[]
To install using RPM packages, consult your Red Hat account representative for more details on gaining access to the appropriate repositories during the OpenShift Enterprise 3.0 Beta period.
endif::[]
