= Install and Configure NodeJS Image
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:

toc::[]

== Overview
The OpenShift https://github.com/openshift/sti-nodejs/tree/master/0.10[NodeJS]
image repository contains the sources and Dockerfiles for building various
versions of NodeJS platform images. The resulting images can be run either by
Docker or using https://github.com/openshift/source-to-image[STI].

== Versions
Currently, OpenShift only provides version https://github.com/openshift/sti-nodejs/tree/master/0.10[0.10] of NodeJS.

== Base Images

The following base images are currently available:

* RHEL 7
* CentOS 7

[NOTE]
====
In order to run the build or test action on a RHEL 7 based NodeJS image, you
need to run the build on properly subscribed RHEL 7 machine.
=======

== Installation
To build NodeJS image, use one of the following procedures, depending on your
base image:

*RHEL 7 Base Image*

To build a RHEL 7 based NodeJS image, run the build on a properly subscribed
RHEL machine:

. Clone the following repository:
+
****
`$ git clone https://github.com/openshift/sti-nodejs.git`
****
. Navigate into the directory you just created:
+
****
`$ cd sti-nodejs`
****
. Build the image:
+
****
`$ make build TARGET=rhel7 VERSION=0.10`
****

*CentOS 7 Base Image*

This image is available on DockerHub. To download it:

****
`$ docker pull openshift/nodejs-010-centos7`
****

Alternatively, you can build a CentOS 7 based NodeJS image:

. Clone the following repository:
+
****
`$ git clone https://github.com/openshift/sti-nodejs.git`
****
. Navigate into the directory you just created:
+
****
`$ cd sti-nodejs`
****
. Build the image:
+
****
`$ make build VERSION=0.10`
****

[NOTE]
====
If you omit the `VERSION` parameter, the build/test action is performed on all
provided versions of NodeJS. Since version `0.10` is the only version provided,
you can omit this parameter.
====

== Usage
To build a simple https://github.com/openshift/sti-nodejs/0.10/test/test-app/[nodejs-sample-app]
NodeJS application, use one of the following procedures, depending on your base image:

*RHEL 7 Base Image*

To build a RHEL 7 based image, run the build on a properly subscribed
RHEL machine:

. Build the image using https://github.com/openshift/source-to-image[STI]:
+
****
`$ $ sti build https://github.com/openshift/sti-nodejs.git --contextDir=0.10/test/test-app/ openshift/nodejs-010-rhel7 nodejs-sample-app`
****
. Run the resulting image using http://docker.io[Docker]:
+
****
`$ docker run -p 8080:8080 nodejs-sample-app`
****

*CentOS 7 Base Image*

To build a CentOS 7 based image:

. Build the image using https://github.com/openshift/source-to-image[STI]:
+
****
`$ sti build https://github.com/openshift/sti-nodejs.git --contextDir=0.10/test/test-app/ openshift/nodejs-010-centos7 nodejs-sample-app`
****
. Run the resulting image using http://docker.io[Docker]:
+
****
`$ docker run -p 8080:8080 nodejs-sample-app`
****

To access and test if the application is running:

****
`$ curl 127.0.0.1:8080`
****

== Testing

This repository also provides a STI test framework which checks basic functionality
of the NodeJS image.

Select whether the NodeJS image you are testing is RHEL based or CentOS based.

*RHEL 7 Base Image*

To test a RHEL 7 based NodeJS image, run the test on a properly subscribed RHEL
machine.

. Navigate into the *_sti-nodejs_* directory:
+
****
`$ cd sti-nodejs`
****
. Test the image:
+
****
`$ make test TARGET=rhel7 VERSION=0.10`
****

*CentOS 7 Base Image*

To test a CentOS 7 based NodeJS image:

. Navigate into the *_sti-nodejs_* directory:
+
****
`$ cd sti-nodejs`
****
. Test the image:
+
****
`$ make test VERSION=0.10`
****

[NOTE]
====
If you omit the `VERSION` parameter, the build/test action is performed on all
provided versions of NodeJS. Since version `0.10` is the only version provided,
you can omit this parameter.
====

== Repository Organization

.Repository Organization
[cols=".^2,.^2,8",options="header"]
|===

|Location |File |Description

|`/nodejs-version/`
|[filename]#Dockerfile#
|CentOS 7 based Dockerfile.

|`/nodejs-version/`
|[filename]#Dockerfile.rhel7#
|RHEL 7 based Dockerfile.

|`/nodejs-version/.sti/bin/`
|
|This folder contains scripts that are run by https://github.com/openshift/source-to-image[STI].

|`/nodejs-version/.sti/bin/`
|[filename]#assemble#
|Installs the sources into the location from which the application will be run, and prepares the application for deployment; for example, installing modules using npm.

|`/nodejs-version/.sti/bin/`
|[filename]#run#
|This script is responsible for using the application web server to run the application.

|`/nodejs-version/.sti/bin/`
|[filename]#usage#
|This script prints the usage of this image.

|`nodejs-version/contrib/`
|
|This folder contains files with commonly used modules.

|`nodejs-version/test/`
|
|This folder contains STI test framework with a simple node.js echo server.

|`nodejs-version/test/test-app/`
|
|Simple node.js echo server used for testing within the STI test framework.

|`nodejs-version/test/`
|[filename]#run#
|Script that runs the STI test framework.

|
|[filename]#Makefile#
|Creates a utility for simplifying image build and test actions.

|`hack/`
|
|This folder contains scripts responsible for building and testing actions performed by the [filename]#Makefile#.
|===

== Image Name Structure

Use the following image name structure:

****
`openshift/[replaceable]#<platform_name>#-[replaceable]#<platform_version>#-[replaceable]#<base_builder_image>#`
****

Where:

. [replaceable]#<platform_name># - Refers to the STI platform; for example, `nodejs`
. [replaceable]#<platform_version># - The version of the referenced platform, without dots; for example, `010` for NodeJS 0.10
. [replaceable]#<Base_builder_image># - The base OS, such as `rhel7` or `centos7`

.Example image names:
====

----
openshift/nodejs-010-centos7
openshift/nodejs-010-rhel7
----
====
