[[install-config-configuring-authentication-github]]
= Configuring the GitHub Identity Provider
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:


toc::[]

== Overview

You can configure the {product-title} master configuration file to use GitHub authentication in your cluster.


== Configuring GitHub Authentication 

Set `GitHubIdentityProvider` in the `identityProviders` stanza to use
link:https://github.com/[GitHub] as an identity provider, using the
link:https://developer.github.com/v3/oauth/[OAuth integration].

[NOTE]
====
Using GitHub as an identity provider requires users to get a token using
`<master>/oauth/token/request` to use with command-line tools.
====

[WARNING]
====
Using GitHub as an identity provider allows any GitHub user to authenticate to your server.
You can limit authentication to members of specific GitHub organizations with the
`organizations` configuration attribute, as shown below.
====

To configure the GitHub identity provider:

. Edit the master configuration file:
+
----
/etc/origin/master/master-config.yaml
----

. Set the `challenge` parameter to `false`.
+
----
oauthConfig:
  ...
  identityProviders:
  - challenge: false
    login: true
----
+
The GitHub identity provider cannot be used to send `WWW-Authenticate` challenges.

. Set the `login` parameter to `true`.

. Specify the `mappingMethod` parameter to determine how identities are mapped to users.
include::install_config/authentication/configuring_authentication_allow_all.adoc[tag=configuring_authentication_common_steps2]

. Set the `name` parameter to an appropriate string. 
+
----
name: github
----
+
This provider name is prefixed to the GitHub numeric user ID to form an identity name. It is also used to build the callback URL.

. Specify the following values to configure GitHub authentication:
+
[[github-auth-example-config]]
.Master Configuration Using `GitHubIdentityProvider`
====

----
oauthConfig:
  ...
  identityProviders:
  - challenge: false
    login: true
    mappingMethod: claim
    name: github
    provider:
      apiVersion: v1
      kind: GitHubIdentityProvider
      clientID: ... <1>
      clientSecret: ... <2>
      organizations: <3>
      - myorganization1
      - myorganization2
      teams: <4>
      - myorganization1/team-a
      - myorganization2/team-b
----
<1> The client ID of a
link:https://github.com/settings/applications/new[registered GitHub OAuth
application]. The application must be configured with a callback URL of
`<master>/oauth2callback/<identityProviderName>`.
<2> The client secret issued by GitHub. This value may also be provided in an
xref:../../install_config/master_node_configuration.adoc#master-node-configuration-passwords-and-other-data[environment
variable, external file, or encrypted file].
<3> Optional list of organizations. If specified, only GitHub users that are members of
at least one of the listed organizations will be allowed to log in. If the GitHub OAuth
application configured in `clientID` is not owned by the organization, an organization
owner must grant third-party access in order to use this option. This can be done during
the first GitHub log in by the organization's administrator, or from the GitHub organization settings.
Cannot be used in combination with the `teams` field.
<4> Optional list of teams. If specified, only GitHub users that are members of
at least one of the listed teams will be allowed to log in. If the GitHub OAuth
application configured in `clientID` is not owned by the team's organization, an organization
owner must grant third-party access in order to use this option. This can be done during
the first GitHub login by the organization's administrator, or from the GitHub organization settings.
Cannot be used in combination with the `organizations` field.
====

include::install_config/authentication/configuring_authentication_allow_all.adoc[tag=restart-after-config-master]
