// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="scheduling-apis"]
= Scheduling APIs
:toc: macro
:toc-title:

toc::[]

== PriorityClass [scheduling.k8s.io/v1]

Description::
+
--
PriorityClass defines mapping from a priority class name to the priority integer value. The value can be any valid integer.
--

Type::
  `object`

