:_mod-docs-content-type: ASSEMBLY
include::_attributes/common-attributes.adoc[]
[id="virt-running-cluster-checkups"]
= {VirtProductName} cluster checkup framework

:context: virt-running-cluster-checkups

toc::[]

[role="_abstract"]
A _checkup_ is an automated test workload that allows you to verify if a specific cluster functionality works as expected. The cluster checkup framework uses native Kubernetes resources to configure and execute the checkup.

:FeatureName: The {VirtProductName} cluster checkup framework
include::snippets/technology-preview.adoc[]

As a developer or cluster administrator, you can use predefined checkups to improve cluster maintainability, troubleshoot unexpected behavior, minimize errors, and save time. You can review the results of the checkup and share them with experts for further analysis. Vendors can write and publish checkups for features or services that they provide and verify that their customer environments are configured correctly.

[id="virt-running-cluster-checkups-latency"]
== Running predefined latency checkups

You can use a latency checkup to verify network connectivity and measure latency between two virtual machines (VMs) that are attached to a secondary network interface. The predefined latency checkup uses the ping utility.

[IMPORTANT]
=====
Before you run a latency checkup, you must first xref:../../virt/vm_networking/virt-connecting-vm-to-linux-bridge.adoc#virt-connecting-vm-to-linux-bridge[create a bridge interface] on the cluster nodes to connect the VM's secondary interface to any interface on the node. If you do not create a bridge interface, the VMs do not start and the job fails.
=====

include::snippets/virt-about-running-checkups.adoc[]

include::modules/virt-latency-checkup-web-console.adoc[leveloffset=+2]

include::modules/virt-measuring-latency-vm-secondary-network.adoc[leveloffset=+2]

[id="virt-running-cluster-checkups-storage"]
== Running predefined storage checkups

You can use a storage checkup to verify that the cluster storage is optimally configured for {VirtProductName}.

include::snippets/virt-about-running-checkups.adoc[]

include::modules/virt-retain-storage-checkup-resources.adoc[leveloffset=+2]

include::modules/virt-storage-checkup-web-console.adoc[leveloffset=+2]

include::modules/virt-checking-storage-configuration.adoc[leveloffset=+2]

include::modules/virt-troubleshoot-storage-checkup.adoc[leveloffset=+2]

[role="_additional-resources"]
.Additional resources
* xref:../../virt/support/virt-collecting-virt-data.adoc#virt-collecting-virt-data[Collecting data for Red{nbsp}Hat Support]
* xref:../../virt/support/virt-collecting-virt-data.adoc#virt-using-virt-must-gather_virt-collecting-virt-data[Using the `must-gather` tool for {VirtProductName}]

include::modules/virt-troubleshoot-storage-checkup-error-codes.adoc[leveloffset=+2]

ifndef::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]
[role="_additional-resources"]
[id="additional-resources_running-cluster-checkups"]
== Additional resources

endif::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]
ifndef::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]
* xref:../../virt/vm_networking/virt-connecting-vm-to-linux-bridge.adoc#virt-connecting-vm-to-linux-bridge[Connecting a virtual machine to a Linux bridge network]
endif::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]
