// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="security-internal-apis"]
= Security Internal APIs
:toc: macro
:toc-title:

toc::[]

== RangeAllocation [security.internal.openshift.io/v1]

Description::
+
--
RangeAllocation is used so we can easily expose a RangeAllocation typed for security group This is an internal API, not intended for external consumption.
 Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).
--

Type::
  `object`

