// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="node-apis"]
= Node APIs
:toc: macro
:toc-title:

toc::[]

== Node [v1]

Description::
+
--
Node is a worker node in Kubernetes. Each node will have a unique identifier in the cache (i.e. in etcd).
--

Type::
  `object`

== PerformanceProfile [performance.openshift.io/v2]

Description::
+
--
PerformanceProfile is the Schema for the performanceprofiles API
--

Type::
  `object`

== Profile [tuned.openshift.io/v1]

Description::
+
--
Profile is a specification for a Profile resource.
--

Type::
  `object`

== RuntimeClass [node.k8s.io/v1]

Description::
+
--
RuntimeClass defines a class of container runtime supported in the cluster. The RuntimeClass is used to determine which container runtime is used to run all containers in a pod. RuntimeClasses are manually defined by a user or cluster provisioner, and referenced in the PodSpec. The Kubelet is responsible for resolving the RuntimeClassName reference before running the pod.  For more details, see https://kubernetes.io/docs/concepts/containers/runtime-class/
--

Type::
  `object`

== Tuned [tuned.openshift.io/v1]

Description::
+
--
Tuned is a collection of rules that allows cluster-wide deployment of node-level sysctls and more flexibility to add custom tuning specified by user needs.  These rules are translated and passed to all containerized Tuned daemons running in the cluster in the format that the daemons understand. The responsibility for applying the node-level tuning then lies with the containerized Tuned daemons. More info: https://github.com/openshift/cluster-node-tuning-operator
--

Type::
  `object`

