:_mod-docs-content-type: ASSEMBLY
[id="otel-collector-connectors"]
= Connectors
include::_attributes/common-attributes.adoc[]
:context: otel-collector-connectors

toc::[]

A connector connects two pipelines. It consumes data as an exporter at the end of one pipeline and emits data as a receiver at the start of another pipeline. It can consume and emit data of the same or different data type. It can generate and emit data to summarize the consumed data, or it can merely replicate or route data.

[id="routing-connector_{context}"]
== Routing Connector

The Routing Connector routes logs, metrics, and traces to specified pipelines according to resource attributes and their routing conditions, which are written as OpenTelemetry Transformation Language (OTTL) statements.

:FeatureName: The Routing Connector
include::snippets/technology-preview.adoc[]

.OpenTelemetry Collector custom resource with an enabled Routing Connector
[source,yaml]
----
  config: |
    connectors:
      routing:
        table: # <1>
          - statement: route() where attributes["X-Tenant"] == "dev" # <2>
            pipelines: [traces/dev] # <3>
          - statement: route() where attributes["X-Tenant"] == "prod"
            pipelines: [traces/prod]
        default_pipelines: [traces/dev] # <4>
        error_mode: ignore # <5>
        match_once: false # <6>
    service:
      pipelines:
        traces/in:
          receivers: [otlp]
          exporters: [routing]
        traces/dev:
          receivers: [routing]
          exporters: [otlp/dev]
        traces/prod:
          receivers: [routing]
          exporters: [otlp/prod]
----
<1> Connector routing table.
<2> Routing conditions written as OTTL statements.
<3> Destination pipelines for routing the matching telemetry data.
<4> Destination pipelines for routing the telemetry data for which no routing condition is satisfied.
<5> Error-handling mode: The `propagate` value is for logging an error and dropping the payload. The `ignore` value is for ignoring the condition and attempting to match with the next one. The `silent` value is the same as `ignore` but without logging the error. The default is `propagate`.
<6>  When set to `true`, the payload is routed only to the first pipeline whose routing condition is met. The default is `false`.

[id="forward-connector_{context}"]
== Forward Connector

The Forward Connector merges two pipelines of the same type.

:FeatureName: The Forward Connector
include::snippets/technology-preview.adoc[]

.OpenTelemetry Collector custom resource with an enabled Forward Connector
[source,yaml]
----
# ...
receivers:
  otlp:
    protocols:
      grpc:
  jaeger:
    protocols:
      grpc:
processors:
  batch:
exporters:
  otlp:
    endpoint: tempo-simplest-distributor:4317
    tls:
      insecure: true
connectors:
  forward:
service:
  pipelines:
    traces/regiona:
      receivers: [otlp]
      processors: []
      exporters: [forward]
    traces/regionb:
      receivers: [jaeger]
      processors: []
      exporters: [forward]
    traces:
      receivers: [forward]
      processors: [batch]
      exporters: [otlp]
# ...
----

[id="spanmetrics-connector_{context}"]
== Spanmetrics Connector

The Spanmetrics Connector aggregates Request, Error, and Duration (R.E.D) OpenTelemetry metrics from span data.

:FeatureName: The Spanmetrics Connector
include::snippets/technology-preview.adoc[]

.OpenTelemetry Collector custom resource with an enabled Spanmetrics Connector
[source,yaml]
----
# ...
  config: |
    connectors:
      spanmetrics:
        metrics_flush_interval: 15s # <1>
    service:
      pipelines:
        traces:
          exporters: [spanmetrics]
        metrics:
          receivers: [spanmetrics]
# ...
----
<1> Defines the flush interval of the generated metrics. Defaults to `15s`.

[role="_additional-resources"]
[id="additional-resources_otel-collector-connectors_{context}"]
== Additional resources
* link:https://opentelemetry.io/docs/specs/otlp/[OpenTelemetry Protocol (OTLP) documentation]
