// Module included in the following assemblies:
//
// * rosa_architecture/rosa_policy_service_definition/rosa-life-cycle.adoc
// * rosa_architecture/rosa_policy_service_definition/rosa-hcp-life-cycle.adoc
// * osd_architecture/osd_policy/osd-life-cycle.adoc

:_mod-docs-content-type: REFERENCE
[id="sd-life-cycle-dates_{context}"]
= Life cycle dates

[role="_abstract"]
The following table lists the general availability, maintenance support end date, and Extended Update Support Add-On - Term 1 end date for each supported {product-title} version.

[options="header"]
|===
|Version    |General availability   |Maintenance support ends  |Extended Update Support Add-On - Term 1 ends
|4.20       |Oct 21, 2025           |Apr 21, 2027              |Oct 21, 2027
|4.19       |Jun 17, 2025           |Dec 17, 2026              |
|4.18       |Feb 25, 2025           |Aug 25, 2026              |Feb 25, 2027
|4.17       |Oct 1, 2024            |Apr 1, 2026               |
|4.16       |Jun 27, 2024           |Dec 27, 2025              |Jun 27, 2026
|4.15       |Feb 27, 2024           |Aug 27, 2025              |
|===

The Extended Update Support Add-On - Term 1 is now available for {product-title} customers using even-numbered versions, starting with 4.16, and is included at no additional cost with your {product-title} subscription.

The Extended Update Support Add-On - Term 1 provides the key benefit of extending the support lifecycle for an eligible minor release from 18 months to a total of 24 months. This 6-month extension allows organizations to maintain stability for mission-critical applications, meet complex regulatory validation schedules, and manage limited maintenance windows by providing continued access to critical and important security updates and urgent-priority bug fixes without requiring a full version upgrade.

To apply Extended Update Support Add-On - Term 1 to your {product-title} cluster, you must update the channel group to `eus`.
ifdef::openshift-rosa-hcp,openshift-rosa[]
For more information about updating your cluster channel group, see _edit cluster_ in the _Additional resources_ section.
endif::openshift-rosa-hcp,openshift-rosa[]
For more information about Extended Update Support Add-On - Term 1, see link:https://access.redhat.com/support/policy/updates/openshift#eus[Extended Update Support Add-On].

//Conditionalizing the admonition below as the ability to have separate version control for CPs and MPs are a feature of ROSA w/HCP only
ifdef::openshift-rosa-hcp[]
[IMPORTANT]
=====
Before upgrading your cluster from version 4.16 to version 4.18, confirm that your control plane and machines pools are using version 4.16.
See _Upgrade options for {product-title} clusters_ in the _Additional resources_ section for more information.
=====
endif::openshift-rosa-hcp[]
ifdef::openshift-rosa-hcp,openshift-rosa[]
[id="govcloud-life-cycle-dates_{context}"]
= Life cycle dates for {product-title} GovCloud

{product-title} GovCloud is subject to FedRAMP high security controls which require the use of cryptographic modules that have received a validation status of active or implementation under test from the Cryptographic Module Validation Program (CMVP). As a result, OpenSSL which is the module that is applicable to RHEL CoreOS in an OpenShift implementation is the determining factor for what OpenShift versions ROSA GovCloud offers, which may create drift from the standard OpenShift support lifecycle.

[options="header"]
|===
|Version    |General availability   |End of life
|4.15       |May 9, 2025           |Dec 1, 2025
|4.16       |Oct 20, 2025           |Dec 27, 2025
|===
endif::openshift-rosa-hcp,openshift-rosa[]