// Module included in the following assemblies:
//
// * nodes/scheduling/descheduler/nodes-descheduler-release-notes.adoc

// This release notes module is allowed to contain xrefs. It must only ever be included from one assembly.

:_mod-docs-content-type: REFERENCE
[id="descheduler-operator-release-notes-5.3.0_{context}"]
= Release notes for {descheduler-operator} 5.3.0

[role="_abstract"]
Review the release notes for {descheduler-operator} 5.3.0 to learn what is new and updated with this release.

Issued: 29 October 2025

The following advisory is available for the {descheduler-operator} 5.3.0:

* link:https://access.redhat.com/errata/RHBA-2025:19249[RHBA-2025:19249]

[id="descheduler-operator-5.3.0-new-features_{context}"]
== New features and enhancements

* The descheduler profile `DevKubeVirtRelieveAndMigrate` has been renamed to `KubeVirtRelieveAndMigrate` and is now generally available. The updated profile improves VM eviction stability during live migrations by enabling background evictions and reducing oscillatory behavior. This profile is only available for use with {VirtProductName}.
+
For more information, see xref:../../../virt/managing_vms/advanced_vm_management/virt-enabling-descheduler-evictions.adoc#virt-configuring-descheduler-evictions_virt-enabling-descheduler-evictions[Configuring descheduler evictions for virtual machines].

* This release of the {descheduler-operator} updates the Kubernetes version to 1.33.

// No bug fixes or CVEs to list
// [id="descheduler-operator-5.3.0-bug-fixes_{context}"]
// === Bug fixes
//
// * This release of the {descheduler-operator} addresses several Common Vulnerabilities and Exposures (CVEs).

// No known issues to list
// [id="descheduler-operator-5.3.0-known-issues_{context}"]
// === Known issues
//
// * TODO
