// Module included in the following assemblies:
// * service_mesh/v2x/ossm-route-migration.adoc

:_mod-docs-content-type: PROCEDURE
[id="ossm-migrating-from-ior-to-explicitly-managed-routes_{context}"]
= Migrating from Istio OpenShift Routing to explicitly-managed routes

This procedure explains how to disable Istio OpenShift Routing (IOR) in {SMProductName}, and how to continue to use and manage Routes that were originally created using IOR. This procedure also provides an example of how to explicitly create a new Route targeting an existing gateway `Service` object.

.Prerequisites

* Before migrating to explicitly-managed routes, export the existing route configurations managed by Istio OpenShift Routing (IOR) to files. Save the files so that in the future you can recreate the route configurations without requiring IOR.

.Procedure

* Modify the `ServiceMeshControlPlane` resource to disable IOR:
+
[source,yaml]
----
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
spec:
  gateways:
    openshiftRoute:
      enabled: false
----
+
You can continue to use the old routes that were previously created using IOR or you can create routes that explicitly target the ingress gateway `Service` object. The following example specifies how to create routes that explicitly target the ingress gateway `Service` object:
+
[source,yaml]
----
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: example-gateway
  namespace: istio-system <1>
spec:
  host: www.example.com
  to:
    kind: Service
    name: istio-ingressgateway <2>
    weight: 100
  port:
    targetPort: http2
  wildcardPolicy: None
----
<1> Specify new routes in the same namespace as the ingress gateway `Service` object.
<2> Use the name of ingress gateway `Service` object that is the target. 