// Module included in the following assemblies:
//
// * nodes/pods/run_once_duration_override/run-once-duration-override-install.adoc

:_mod-docs-content-type: PROCEDURE
[id="rodoo-install-operator_{context}"]
= Installing the {run-once-operator}

You can use the web console to install the {run-once-operator}.

.Prerequisites

* You have access to the cluster with `cluster-admin` privileges.
* You have access to the {product-title} web console.

.Procedure

. Log in to the {product-title} web console.

. Create the required namespace for the {run-once-operator}.
.. Navigate to *Administration* -> *Namespaces* and click *Create Namespace*.
.. Enter `openshift-run-once-duration-override-operator` in the *Name* field and click *Create*.

. Install the {run-once-operator}.
.. Navigate to *Ecosystem* -> *Software Catalog*.
.. Enter *{run-once-operator}* into the filter box.
.. Select the *{run-once-operator}* and click *Install*.
.. On the *Install Operator* page:
... The *Update channel* is set to *stable*, which installs the latest stable release of the {run-once-operator}.
... Select *A specific namespace on the cluster*.
... Choose *openshift-run-once-duration-override-operator* from the dropdown menu under *Installed namespace*.
... Select an *Update approval* strategy.
+
* The *Automatic* strategy allows Operator Lifecycle Manager (OLM) to automatically update the Operator when a new version is available.
* The *Manual* strategy requires a user with appropriate credentials to approve the Operator update.
... Click *Install*.

. Create a `RunOnceDurationOverride` instance.
.. From the *Ecosystem* -> *Installed Operators* page, click *{run-once-operator}*.
.. Select the *Run Once Duration Override* tab and click *Create RunOnceDurationOverride*.
.. Edit the settings as necessary.
+
Under the `runOnceDurationOverride` section, you can update the `spec.activeDeadlineSeconds` value, if required. The predefined value is `3600` seconds, or 1 hour.

.. Click *Create*.


.Verification

. Log in to the OpenShift CLI.

. Verify all pods are created and running properly.
+
[source,terminal]
----
$ oc get pods -n openshift-run-once-duration-override-operator
----
+
.Example output
[source,terminal]
----
NAME                                                   READY   STATUS    RESTARTS   AGE
run-once-duration-override-operator-7b88c676f6-lcxgc   1/1     Running   0          7m46s
runoncedurationoverride-62blp                          1/1     Running   0          41s
runoncedurationoverride-h8h8b                          1/1     Running   0          41s
runoncedurationoverride-tdsqk                          1/1     Running   0          41s
----
