:_mod-docs-content-type: REFERENCE
[id="telco-hub-acm-observability_{context}"]
= {rh-rhacm} Observability

Cluster Observability is provided by the multicluster engine and {rh-rhacm-first}.

* Observability storage needs several `PV` resources and an S3 compatible bucket storage for long term retention of the metrics.
* Storage requirements calculation is complex and dependent on the specific workloads and characteristics of managed clusters.
Requirements for `PV` resources and the S3 bucket depend on many aspects including data retention, the number of managed clusters, managed cluster workloads, and so on.
* Estimate the required storage for observability by using the observability sizing calculator in the {rh-rhacm} capacity planning repository.
See the Red Hat Knowledgebase article link:https://access.redhat.com/articles/7103886[Calculating storage need for MultiClusterHub Observability on telco environments] for an explanation of using the calculator to estimate observability storage requirements.
The below table uses inputs derived from the telco RAN DU RDS and the hub cluster RDS as representative values.

[NOTE]
====
The following numbers are estimated.
Tune the values for more accurate results.
Add an engineering margin, for example +20%, to the results to account for potential estimation inaccuracies.
====

.Cluster requirements
[cols="42%,42%,16%",options="header"]
|====
|Capacity planner input
|Data source
|Example value

|Number of control plane nodes
|Hub cluster RDS (scale) and telco RAN DU RDS (topology)
|3500

|Number of additional worker nodes
|Hub cluster RDS (scale) and telco RAN DU RDS (topology)
|0

|Days for storage of data
|Hub cluster RDS
|15

|Total number of pods per cluster
|Telco RAN DU RDS
|120

|Number of namespaces (excluding {product-title})
|Telco RAN DU RDS
|4

|Number of metric samples per hour
|Default value
|12

|Number of hours of retention in receiver persistent volume (PV)
|Default value
|24
|====

With these input values, the sizing calculator as described in the Red Hat Knowledgebase article link:https://access.redhat.com/articles/7103886[Calculating storage need for MultiClusterHub Observability on telco environments] indicates the following storage needs:

.Storage requirements
[options="header"]
|====
2+|`alertmanager` PV 2+|`thanos receive` PV 2+|`thanos compact` PV

|*Per replica* |*Total* |*Per replica* |*Total* 2+|*Total*

|10 GiB |30 GiB |10 GiB |30 GiB 2+|100 GiB
|====

.Storage requirements
[options="header"]
|====
2+|`thanos rule` PV 2+|`thanos store` PV 2+|Object bucket^[1]^

|*Per replica* |*Total* |*Per replica* |*Total* |*Per day* |*Total*

|30 GiB |90 GiB |100 GiB |300 GiB |15 GiB |101 GiB
|====
[1] For the object bucket, it is assumed that downsampling is disabled, so that only raw data is calculated for storage requirements.
