:_content-type: ASSEMBLY
[id="virt-edit-vms"]
= Editing virtual machines
include::_attributes/common-attributes.adoc[]
:context: virt-edit-vms

toc::[]

You can update a virtual machine (VM) configuration by using the {product-title} web console. You can update the xref:../../virt/getting_started/virt-web-console-overview.adoc#virtualmachine-details-yaml_virt-web-console-overview[YAML file] or the xref:../../virt/getting_started/virt-web-console-overview.adoc#virtualmachine-details-page_virt-web-console-overview[*VirtualMachine details* page].

You can also edit a VM by using the command line.

include::modules/virt-editing-vm-cli.adoc[leveloffset=+1]

include::modules/virt-add-disk-to-vm.adoc[leveloffset=+1]

To configure storage class defaults, use storage profiles. For more information, see xref:../../virt/virtual_machines/virtual_disks/virt-creating-data-volumes.adoc#virt-customizing-storage-profile_virt-creating-data-volumes[Customizing the storage profile].

include::modules/virt-storage-wizard-fields-web.adoc[leveloffset=+2]

include::modules/virt-adding-secret-configmap-service-account-to-vm.adoc[leveloffset=+1]

[discrete]
[id="additional-resources-configmaps"]
[role="_additional-resources"]
=== Additional resources for config maps, secrets, and service accounts
* xref:../../nodes/pods/nodes-pods-configmaps.adoc#nodes-pods-configmap-overview_builds-configmaps[Understanding config maps]
* xref:../../nodes/pods/nodes-pods-secrets.adoc#nodes-pods-secrets-about[Providing sensitive data to pods]
* xref:../../authentication/understanding-and-creating-service-accounts.adoc#service-accounts-overview[Understanding and creating service accounts]

