[id="virt-create-vms"]
= Creating virtual machines
include::modules/virt-document-attributes.adoc[]
:context: virt-create-vms

toc::[]

Use one of these procedures to create a virtual machine:

* Quick Start guided tour
* Running the wizard
* Pasting a pre-configured YAML file with the virtual machine wizard
* Using the CLI

[WARNING]
====
Do not create virtual machines in `openshift-*` namespaces.
Instead, create a new namespace or use an existing namespace without the `openshift` prefix.
====

When you create virtual machines from the web console, select a virtual machine template that is configured with a boot source. Virtual machine templates with a boot source are labeled as *Available boot source* or they display a customized label text. Using templates with an available boot source expedites the process of creating virtual machines.

Templates without a boot source are labeled as *Boot source required*. You can use these templates if you complete the steps for xref:../../virt/vm_templates/virt-creating-vm-template.adoc#virt-adding-a-boot-source-web_virt-creating-vm-template[adding a boot source to the virtual machine].

[IMPORTANT]
====
Due to differences in storage behavior, some virtual machine templates are incompatible with SNO. To ensure compatibility, do not set the `evictionStrategy` field for any templates or virtual machines that use data volumes or storage profiles.
====

include::modules/virt-creating-vm-quick-start-web.adoc[leveloffset=+1]
include::modules/virt-creating-vm-wizard-web.adoc[leveloffset=+1]

Refer to the virtual machine wizard fields section when running the web console wizard.

:virtualmachine:
include::modules/virt-vm-wizard-fields-web.adoc[leveloffset=+2]

Enable the xref:../../scalability_and_performance/using-cpu-manager.adoc#using-cpu-manager[CPU Manager] to use the high-performance workload profile.

include::modules/virt-networking-wizard-fields-web.adoc[leveloffset=+2]
include::modules/virt-storage-wizard-fields-web.adoc[leveloffset=+2]
include::modules/virt-cloud-init-fields-web.adoc[leveloffset=+2]

For more information on the `kubevirt-storage-class-defaults` config map, see xref:../../virt/virtual_machines/virtual_disks/virt-storage-defaults-for-datavolumes.adoc#virt-storage-defaults-for-datavolumes[
Storage defaults for data volumes].

include::modules/virt-creating-vm-yaml-web.adoc[leveloffset=+1]
include::modules/virt-creating-vm.adoc[leveloffset=+1]

:virtualmachine!:

include::modules/virt-vm-storage-volume-types.adoc[leveloffset=+1]
include::modules/virt-about-runstrategies-vms.adoc[leveloffset=+1]

[id="additional-resources_virt-create-vms_{context}"]
== Additional resources

* The `VirtualMachineSpec` definition in the link:https://kubevirt.io/api-reference/{KubeVirtVersion}/definitions.html#_v1_virtualmachinespec[KubeVirt {KubeVirtVersion} API Reference] provides broader context for the parameters and hierarchy of the virtual machine specification.

+
[NOTE]
====
The KubeVirt API Reference is the upstream project reference and might contain parameters that are not supported in {VirtProductName}.
====

* See xref:../../virt/virtual_machines/virtual_disks/virt-using-container-disks-with-vms.adoc#virt-using-container-disks-with-vms[Prepare a container disk] before adding it to a virtual machine as a `containerDisk` volume.
* See xref:../../machine_management/deploying-machine-health-checks.adoc#machine-health-checks-about_deploying-machine-health-checks[Deploying machine health checks] for further details on deploying and enabling machine health checks.
* See xref:../../installing/installing_bare_metal_ipi/ipi-install-overview.adoc#ipi-install-overview[Installer-provisioned infrastructure overview] for further details on installer-provisioned infrastructure.
* See xref:../../virt/virtual_machines/vm_networking/virt-configuring-sriov-device-for-vms.adoc#virt-configuring-sriov-device-for-vms[Configuring the SR-IOV Network Operator] for further details on the SR-IOV Network Operator.
* xref:../../virt/virtual_machines/virtual_disks/virt-creating-data-volumes.adoc#virt-customizing-storage-profile_virt-creating-data-volumes[Customizing the storage profile]
