= Create an Application
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc:
:toc-placement!:
:toc-title: Topics Covered

toc::[]

When you have completed the link:preliminary_steps.html[preliminary steps] and configured the client tools with the interactive wizard, you are ready to create an application. You should already have a domain created under which you will create the new application.

You can create a new application with either the management console or the client tools.

== Create Application with Management Console
. Log into your account from the management console.
. From the btn:[Applications] tab, click btn:[Add Application].
. Click on the web framework cartridge you want to create.
. Enter the name for your application, select whether to make it scalable, and choose the number of gears.
. Click btn:[Create Application].

After the application is created, you can view it with the public URL in the form _<app_name>-<domain>.rhcloud.com_. 

When you create an application with the management console, the application's source code repository is not automatically copied to your workstation. Therefore, you must manually copy it so that you can modify the code and deploy the application to suit your requirements.

From the directory where you want to clone the application's source code repository to, run the following command:

----
$ git clone <git_url> 
----

//If you did not create a domain during the link:../client_tools_install_guide/configuring_client_tools.html[initial configuration] of the client tools, you must create one before you can create an application.

//Create a domain with the following command:

//----
//$ rhc domain create <domain_name>
//----

== Create Application with Client Tools (CLI)
From the directory where you want the application created, run the following command:

----
$ rhc app create <app_name> <cartridge> 
----

If multiple versions of the application are supported, you must specify the version of the cartridge:

----
$ rhc app create <app_name> <cartridge-version>
----

In the following example, because multiple versions of Python are supported we have specified the most current version.

.Creating a Python Application
====

----
$ rhc app create mypython python-3.3
Application Options
-------------------
Domain:     mydomain
Cartridges: python-3.3
Gear Size:  default
Scaling:    no

Creating application 'mypython' ... done


Waiting for your DNS name to be available ... done

Cloning into 'mypython'...
Warning: Permanently added 'mypython-mydomain.rhcloud.com' (RSA) to the list of known hosts.

Your application 'mypython' is now available.

  URL:        http://mypython-mydomain.rhcloud.com/
  SSH to:     54052e482587c84787000ad7@mypython-mydomain.rhcloud.com
  Git remote: ssh://54052e482587c84787000ad7@mypython-mydomain.rhcloud.com/~/git/mypython.git/
  Cloned to:  /home/User/mypython

Run 'rhc show-app mypython' for more details about your app.
----
====

When you create a new application with the client tools, a copy of the application's source code repository is automatically downloaded to the directory on your workstation where you created the application.

After the application is created, you can view it with the public URL in the form _<app_name>-<domain>.example.com_. For the application we created in the example the public URL is mypython-mydomain.rhcloud.com.