#!/usr/bin/env python3
"""
Generated by Claude Code v2.1.39 with Sonnet 4.5 on 2026.02.11
Tested by jrouth@redhat.com
Reviewed by dchadwic@redhat.com

Pre-GA PR Cleanup Script

This script automates the process of updating PRs in the openshift-docs repository
that are labeled for a GA release to also include the latest development version label.

Do not use this script unless directed as part of pre-GA preparation activities.
"""

import subprocess
import json
import sys
import time
from typing import List, Dict, Optional


# Constants
REPO = "openshift/openshift-docs"
BASE_BRANCH = "main"
MILESTONE = "Continuous release"
MAX_SEARCH_LIMIT = 1000
API_SLEEP_DELAY = 1 # Seconds to wait between API calls


def run_gh_command(args: List[str]) -> tuple[bool, str]:
    """
    Execute a gh CLI command and return success status and output.

    Args:
        args: List of command arguments to pass to gh

    Returns:
        Tuple of (success: bool, output: str)
    """
    try:
        result = subprocess.run(
            ["gh"] + args,
            capture_output=True,
            text=True,
            check=False
        )
        return (result.returncode == 0, result.stdout if result.returncode == 0 else result.stderr)
    except FileNotFoundError:
        print("Error: 'gh' CLI not found. Please install GitHub CLI: https://cli.github.com/")
        sys.exit(1)


def get_user_values() -> Dict[str, str]:
    """
    Prompt the user for the required values.

    Returns:
        Dictionary with branch-label-ga, branch-label-latest, and version-latest
    """
    print("=" * 80)
    print("Pre-GA PR Cleanup Script")
    print("=" * 80)
    print()
    print("╔═══════════════════════════════════╗")
    print("║             IMPORTANT             ║")
    print("╠═══════════════════════════════════╣")
    print("║                                   ║")
    print("║   Do not use this script unless   ║")
    print("║   directed during GA preparation  ║")
    print("║                                   ║")
    print("╚═══════════════════════════════════╝")
    print()
    print("Please provide the following values:")
    print()

    branch_label_ga = input("GA branch label (e.g., branch/enterprise-4.21): ").strip()
    branch_label_latest = input("Latest branch label (e.g., branch/enterprise-4.22): ").strip()
    version_latest = input("Latest version name (e.g., 4.22): ").strip()

    if not all([branch_label_ga, branch_label_latest, version_latest]):
        print("\nError: All values are required.")
        sys.exit(1)

    return {
        "branch-label-ga": branch_label_ga,
        "branch-label-latest": branch_label_latest,
        "version-latest": version_latest
    }


def verify_permissions() -> bool:
    """
    Verify that the user has write permissions to the repository.

    Returns:
        True if user has write permissions, False otherwise
    """
    print("\nVerifying repository permissions...")

    success, output = run_gh_command([
        "api",
        f"repos/{REPO}",
        "--jq", ".permissions.push"
    ])

    if success and output.strip() == "true":
        print("✓ Write permissions verified")
        return True
    else:
        print(f"✗ Error: You do not have write permissions to {REPO}")
        return False


def search_prs(values: Dict[str, str]) -> tuple[Optional[str], Optional[List[Dict]]]:
    """
    Search for PRs matching the criteria.

    Args:
        values: Dictionary containing the user-specified values

    Returns:
        Tuple of (search_query: str, prs: List[Dict]) or (search_query, None) if no PRs found
    """
    branch_label_ga = values["branch-label-ga"]
    branch_label_latest = values["branch-label-latest"]

    # Construct the search query for display purposes
    query = f"repo:{REPO} is:open is:pr base:{BASE_BRANCH} label:{branch_label_ga} -label:{branch_label_latest}"

    print(f"\nSearching for PRs...")

    success, output = run_gh_command([
        "pr", "list",
        "--repo", REPO,
        "--json", "number,title,url,state,labels,baseRefName,milestone",
        "--limit", str(MAX_SEARCH_LIMIT),
        "--state", "open",
        "--base", BASE_BRANCH,
        "--label", branch_label_ga
    ])

    if not success:
        print(f"✗ Error searching for PRs: {output}")
        sys.exit(1)

    prs = json.loads(output)

    # Filter out PRs that already have the latest label
    # We do this in Python because 'gh pr list' does not support excluding labels natively
    prs = [
        pr for pr in prs
        if branch_label_latest not in [label["name"] for label in pr.get("labels", [])]
    ]

    if not prs:
        return query, None

    return query, prs


def format_pr_table(prs: List[Dict]) -> str:
    """
    Format the PR list as a text table.

    Args:
        prs: List of PR dictionaries

    Returns:
        Formatted table string
    """
    # Calculate column widths
    url_width = max(len(pr["url"]) for pr in prs) if prs else 10
    status_width = 6
    branch_width = 6
    milestone_width = max(
        len(pr.get("milestone", {}).get("title", "(none)") if pr.get("milestone") else "(none)")
        for pr in prs
    ) if prs else 10
    milestone_width = max(milestone_width, 18)  # Minimum for header
    labels_width = 40

    # Header
    header = f"{'URL':<{url_width}} | {'Status':<{status_width}} | {'Branch':<{branch_width}} | {'Current Milestone':<{milestone_width}} | {'Labels':<{labels_width}}"
    separator = "-" * len(header)

    lines = [separator, header, separator]

    # Rows
    for pr in prs:
        url = pr["url"]
        status = pr["state"]
        branch = pr["baseRefName"]
        milestone = pr.get("milestone", {}).get("title", "(none)") if pr.get("milestone") else "(none)"
        labels = ", ".join([label["name"] for label in pr.get("labels", [])])
        if len(labels) > labels_width:
            labels = labels[:labels_width-3] + "..."

        line = f"{url:<{url_width}} | {status:<{status_width}} | {branch:<{branch_width}} | {milestone:<{milestone_width}} | {labels:<{labels_width}}"
        lines.append(line)

    lines.append(separator)

    return "\n".join(lines)


def generate_comment(values: Dict[str, str]) -> str:
    """
    Generate the comment text with substituted values.

    Args:
        values: Dictionary containing the user-specified values

    Returns:
        Comment text with values substituted
    """
    template = f"""The `{values['branch-label-latest']}` label has been added to this PR.

This is because your PR targets the `main` branch and is labeled for {values['branch-label-ga']}. And any PR going into `main` must also target the latest version branch ({values['branch-label-latest']}).

If the update in your PR does NOT apply to version {values['version-latest']} onward, please re-target this PR to go directly into the appropriate `enterprise-` version branch or branches instead of `main`."""

    return template


def get_user_confirmation(query: str, comment: str, prs: List[Dict], values: Dict[str, str]) -> List[Dict]:
    """
    Get user confirmation and allow PR removal.

    Args:
        query: The search query used
        comment: The comment that will be added
        prs: List of PRs to potentially process
        values: Dictionary containing the user-specified values

    Returns:
        Final list of PRs to process (may be empty if user cancels)
    """
    while True:
        print("\n" + "=" * 80)
        print("CONFIRMATION")
        print("=" * 80)
        print(f"\nSearch query used:\n{query}")
        print(f"\nComment that will be added to each PR:")
        print("-" * 80)
        print(comment)
        print("-" * 80)
        print(f"\nFound {len(prs)} PR(s) matching criteria:")
        print()
        print(format_pr_table(prs))
        print()
        print("Options:")
        print("  1. Confirm all - Process all PRs listed above")
        print("  2. Confirm none - Exit without making changes")
        print("  3. Remove specific PRs - Specify PR numbers to exclude (comma-separated)")
        print()

        choice = input("Enter your choice (1/2/3): ").strip()

        if choice == "1":
            return prs
        elif choice == "2":
            print("\nNo changes made. Exiting.")
            sys.exit(0)
        elif choice == "3":
            pr_numbers_input = input("\nEnter PR numbers to exclude (comma-separated, e.g., 1234,5678): ").strip()

            try:
                exclude_numbers = {int(num.strip()) for num in pr_numbers_input.split(",") if num.strip()}
            except ValueError:
                print("✗ Invalid input. Please enter PR numbers as comma-separated integers.")
                continue

            # Filter out the excluded PRs
            prs = [pr for pr in prs if pr["number"] not in exclude_numbers]

            if not prs:
                print("\n✗ All PRs have been excluded. Exiting.")
                sys.exit(0)

            print(f"\n{len(exclude_numbers)} PR(s) removed from the list.")
            # Loop will repeat to show updated list
        else:
            print("✗ Invalid choice. Please enter 1, 2, or 3.")


def process_prs(prs: List[Dict], values: Dict[str, str], comment: str) -> List[Dict]:
    """
    Process the confirmed PRs by adding labels, setting milestone, and adding comment.

    Args:
        prs: List of PRs to process
        values: Dictionary containing the user-specified values
        comment: The comment to add to each PR

    Returns:
        List of failure dictionaries
    """
    print("\n" + "=" * 80)
    print(f"Processing {len(prs)} PR(s)...")
    print("=" * 80)

    failures = []
    branch_label_latest = values["branch-label-latest"]

    for i, pr in enumerate(prs, 1):
        pr_number = pr["number"]
        pr_url = pr["url"]
        print(f"\n[{i}/{len(prs)}] Processing PR #{pr_number}...")

        pr_failures = []

        # Add label
        print(f"  Adding label '{branch_label_latest}'...")
        success, output = run_gh_command([
            "pr", "edit", str(pr_number),
            "--repo", REPO,
            "--add-label", branch_label_latest
        ])
        if not success:
            print(f"  ✗ Failed to add label: {output.strip()}")
            pr_failures.append(f"add label '{branch_label_latest}'")
        else:
            print(f"  ✓ Label added")

        # Set milestone
        print(f"  Setting milestone to '{MILESTONE}'...")
        success, output = run_gh_command([
            "pr", "edit", str(pr_number),
            "--repo", REPO,
            "--milestone", MILESTONE
        ])
        if not success:
            print(f"  ✗ Failed to set milestone: {output.strip()}")
            pr_failures.append(f"set milestone to '{MILESTONE}'")
        else:
            print(f"  ✓ Milestone set")

        # Add comment
        print(f"  Adding comment...")
        success, output = run_gh_command([
            "pr", "comment", str(pr_number),
            "--repo", REPO,
            "--body", comment
        ])
        if not success:
            print(f"  ✗ Failed to add comment: {output.strip()}")
            pr_failures.append("add comment")
        else:
            print(f"  ✓ Comment added")

        if pr_failures:
            failures.append({
                "number": pr_number,
                "url": pr_url,
                "failed_actions": pr_failures
            })

        # Avoid rate limiting
        time.sleep(API_SLEEP_DELAY)

    return failures


def display_results(prs: List[Dict], failures: List[Dict]):
    """
    Display the final results including links to all PRs and any failures.

    Args:
        prs: List of all processed PRs
        failures: List of failure dictionaries
    """
    print("\n" + "=" * 80)
    print("RESULTS")
    print("=" * 80)
    print(f"\nProcessed {len(prs)} PR(s). You can review them at the following links:")
    print()

    for pr in prs:
        print(f"  • {pr['url']}")

    if failures:
        print("\n" + "=" * 80)
        print("FAILURES")
        print("=" * 80)
        print(f"\n{len(failures)} PR(s) had failures that require manual follow-up:")
        print()

        for failure in failures:
            print(f"PR #{failure['number']} ({failure['url']}):")
            for action in failure["failed_actions"]:
                print(f"  ✗ Failed to: {action}")
            print()
    else:
        print("\n✓ All PRs processed successfully with no failures.")


def main():
    """Main script execution."""
    # Step 1: Get user values
    values = get_user_values()

    # Step 2: Verify permissions
    if not verify_permissions():
        sys.exit(1)

    # Step 3: Search for PRs
    query, prs = search_prs(values)

    if prs is None:
        print(f"\nNo PRs found matching the criteria.")
        print(f"\nSearch query used:\n{query}")
        sys.exit(0)

    # Step 4: Generate comment
    comment = generate_comment(values)

    # Step 5: Get user confirmation
    confirmed_prs = get_user_confirmation(query, comment, prs, values)

    # Step 6: Process PRs
    failures = process_prs(confirmed_prs, values, comment)

    # Step 7-8: Display results and failures
    display_results(confirmed_prs, failures)


if __name__ == "__main__":
    main()
