// Module included in the following assemblies:
//
// * nodes/nodes-pods-autoscaling-custom.adoc

:_content-type: PROCEDURE
[id="nodes-pods-autoscaling-custom-creating-trigger-auth_{context}"]
= Using trigger authentications

You use trigger authentications and cluster trigger authentications by using a custom resource to create the authentication,  then add a reference to a scaled object or scaled job.

.Prerequisites

* The Custom Metrics Autoscaler Operator must be installed. 

* If you are using a secret, the `Secret` object must exist, for example:
+
.Example secret
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  user-name: <base64_username>
  password: <base64_password>
----

.Procedure

. Create the `TriggerAuthentication` or  `ClusterTriggerAuthentication` object.

.. Create a YAML file that defines the object:
+
.Example trigger authentication with a secret
[source,yaml]
----
kind: TriggerAuthentication
apiVersion: keda.sh/v1alpha1
metadata:
  name: prom-triggerauthentication
  namespace: my-namespace
spec:
  secretTargetRef:
  - parameter: user-name
    name: my-secret
    key: USER_NAME
  - parameter: password
    name: my-secret
    key: PASSWORD
----

.. Create the `TriggerAuthentication` object:
+
[source,terminal]
----
$ oc create -f <file-name>.yaml
----

. Create or edit a `ScaledObject` YAML file:
+
.Example scaled object
[source,yaml,options="nowrap"]
----
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scaledobject
  namespace: my-namespace
spec:
  scaleTargetRef:
    name: example-deployment
  maxReplicaCount: 100
  minReplicaCount: 0
  pollingInterval: 30
  triggers:
  - authenticationRef:  
    type: prometheus
    metadata:
      serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
      namespace: kedatest # replace <NAMESPACE>
      metricName: http_requests_total
      threshold: '5'
      query: sum(rate(http_requests_total{job="test-app"}[1m]))
      authModes: "basic"
    - authenticationRef: <1>
        name: prom-triggerauthentication
      metadata:
        name: prom-triggerauthentication
      type: object
    - authenticationRef: <2>
        name: prom-cluster-triggerauthentication
        kind: ClusterTriggerAuthentication
      metadata:
        name: prom-cluster-triggerauthentication
      type: object
----
<1> Optional: Specify a trigger authentication.
<2> Optional: Specify a cluster trigger authentication. You must include the `kind: ClusterTriggerAuthentication` parameter.
+
[NOTE]
====
It is not necessary to specify both a namespace trigger authentication and a cluster trigger authentication.
====

. Create the object. For example:
+
[source,terminal]
----
$ oc apply -f <file-name>
----

