// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="oauth-apis"]
= OAuth APIs
:toc: macro
:toc-title:

toc::[]

== OAuthAccessToken [oauth.openshift.io/v1]

Description::
+
--
OAuthAccessToken describes an OAuth access token. The name of a token must be prefixed with a `sha256~` string, must not contain "/" or "%" characters and must be at least 32 characters long.

The name of the token is constructed from the actual token by sha256-hashing it and using URL-safe unpadded base64-encoding (as described in RFC4648) on the hashed result.

Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).
--

Type::
  `object`

== OAuthAuthorizeToken [oauth.openshift.io/v1]

Description::
+
--
OAuthAuthorizeToken describes an OAuth authorization token

Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).
--

Type::
  `object`

== OAuthClientAuthorization [oauth.openshift.io/v1]

Description::
+
--
OAuthClientAuthorization describes an authorization created by an OAuth client

Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).
--

Type::
  `object`

== OAuthClient [oauth.openshift.io/v1]

Description::
+
--
OAuthClient describes an OAuth client

Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).
--

Type::
  `object`

== UserOAuthAccessToken [oauth.openshift.io/v1]

Description::
+
--
UserOAuthAccessToken is a virtual resource to mirror OAuthAccessTokens to the user the access token was issued for
--

Type::
  `object`

