:_mod-docs-content-type: ASSEMBLY
[id="logging-ui-plugin"]
= Logging UI plugin
include::_attributes/common-attributes.adoc[]
:context: logging-ui-plugin

toc::[]

:FeatureName: The {coo-full}
include::snippets/technology-preview.adoc[leveloffset=+2]


The logging UI plugin surfaces logging data in the {product-title} web console on the *Observe* -> *Logs* page. 
You can specify filters, queries, time ranges and refresh rates, with the results displayed as a list of collapsed logs, which can then be expanded to show more detailed information for each log.

When you have also deployed the Troubleshooting UI plugin on {product-title} version 4.16+, it connects to the Korrel8r service and adds direct links from the Administration perspective, from the **Observe** -> **Logs** page, to the **Observe** -> **Metrics** page with a correlated PromQL query. It also adds a **See Related Logs** link from the Administration perspective alerting detail page, at **Observe** -> **Alerting**,  to the **Observe** -> **Logs** page with a correlated filter set selected.

The features of the plugin are categorized as:

dev-console::	Adds the logging view to the Developer perspective.
alerts::	Merges the web console alerts with log-based alerts defined in the Loki ruler. Adds a log-based metrics chart in the alert detail view.
dev-alerts::	Merges the web console alerts with log-based alerts defined in the Loki ruler. Adds a log-based metrics chart in the alert detail view for the Developer perspective.


For {coo-first} versions, the support for these features in {product-title} versions is shown in the following table:

[cols="1,1,3", options="header"]
|===
| COO version   | OCP versions   | Features

| 0.3.0+        | 4.12           | `dev-console`
| 0.3.0+        | 4.13           | `dev-console`, `alerts`
| 0.3.0+        | 4.14+          | `dev-console`, `alerts`, `dev-alerts`
|===

include::modules/coo-logging-ui-plugin-install.adoc[leveloffset=+1]