:_mod-docs-content-type: ASSEMBLY
[id="observability-ui-plugins-overview"]
= Observability UI plugins overview
include::_attributes/common-attributes.adoc[]
:context: observability-ui-plugins-overview

toc::[]

:FeatureName: The {coo-full}
include::snippets/technology-preview.adoc[leveloffset=+2]

You can use the {coo-first} to install and manage UI plugins to enhance the observability capabilities of the {product-title} web console.
The plugins extend the default functionality, providing new UI features for monitoring, troubleshooting, distributed tracing, and cluster logging.

["dashboards_{context}"]
== Dashboards

The dashboard UI plugin supports enhanced dashboards in the {product-title} web console at *Observe* -> *Dashboards*.
You can add other Prometheus data sources from the cluster to the default dashboards, in addition to the in-cluster data source.
This results in a unified observability experience across different data sources.

For more information, see the xref:../../../observability/cluster_observability_operator/ui_plugins/dashboard-ui-plugin.adoc#dashboard-ui-plugin[dashboard UI plugin] page.

["troubleshooting_{context}"]
== Troubleshooting

The troubleshooting panel UI plugin for {product-title} version 4.16+ provides observability signal correlation, powered by the open source Korrel8r project.
You can use the troubleshooting panel available from the *Observe* -> *Alerting* page to easily correlate metrics, logs, alerts, netflows, and additional observability signals and resources, across different data stores.
Users of {product-title} version 4.17+ can also access the troubleshooting UI panel from the Application Launcher {launch}.

The output of Korrel8r is displayed as an interactive node graph. When you click on a node, you are automatically redirected to the corresponding web console page with the specific information for that node, for example, metric, log, or pod.

For more information, see the xref:../../../observability/cluster_observability_operator/ui_plugins/troubleshooting-ui-plugin.adoc#troubleshooting-ui-plugin[troubleshooting UI plugin] page.

["distributed-tracing_{context}"]
== Distributed tracing

The distributed tracing UI plugin adds tracing-related features to the web console on the *Observe* -> *Traces* page.
You can follow requests through the front end and into the backend of microservices, helping you identify code errors and performance bottlenecks in distributed systems.
You can select a supported `TempoStack` or `TempoMonolithic` multi-tenant instance running in the cluster and set a time range and query to view the trace data.

For more information, see the xref:../../../observability/cluster_observability_operator/ui_plugins/distributed-tracing-ui-plugin.adoc#distributed-tracing-ui-plugin[distributed tracing UI plugin] page.


["cluster-logging_{context}"]
== Cluster logging

The logging UI plugin surfaces logging data in the web console on the  *Observe* -> *Logs* page. 
You can specify filters, queries, time ranges and refresh rates. The results displayed a list of collapsed logs, which can then be expanded to show more detailed information for each log.

For more information, see the xref:../../../observability/cluster_observability_operator/ui_plugins/logging-ui-plugin.adoc#logging-ui-plugin[logging UI plugin] page.
