// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="webhook-apis"]
= Webhook APIs
:toc: macro
:toc-title:

toc::[]

== MutatingWebhookConfiguration [admissionregistration.k8s.io/v1]

Description::
+
--
MutatingWebhookConfiguration describes the configuration of and admission webhook that accept or reject and may change the object.
--

Type::
  `object`

== ValidatingWebhookConfiguration [admissionregistration.k8s.io/v1]

Description::
+
--
ValidatingWebhookConfiguration describes the configuration of and admission webhook that accept or reject and object without changing it.
--

Type::
  `object`

