// Automatically generated by 'openshift-apidocs-gen'. Do not edit.
:_mod-docs-content-type: ASSEMBLY
[id="batch-apis"]
= Batch APIs
:toc: macro
:toc-title:

toc::[]

== CronJob [batch/v1]

Description::
+
--
CronJob represents the configuration of a single cron job.
--

Type::
  `object`

== Job [batch/v1]

Description::
+
--
Job represents the configuration of a single job.
--

Type::
  `object`

