:_mod-docs-content-type: ASSEMBLY
[id="compliance-operator-rhacs"]
= Using the Compliance Operator with {product-title}
include::modules/common-attributes.adoc[]
:context: compliance-operator-rhacs

toc::[]

[role="_abstract"]
You can configure {product-title-short} to use the Compliance Operator for compliance reporting and remediation with {ocp} clusters. Results from the Compliance Operator are reported in the {product-title-short} Compliance Dashboard.

The Compliance Operator automates the review of numerous technical implementations and compares them with certain aspects of industry standards, benchmarks, and baselines.

The Compliance Operator is not an auditor. To comply or certify to these various standards, you must engage an authorized auditor such as a Qualified Security Assessor (QSA), Joint Authorization Board (JAB), or other industry-recognized regulatory authority to assess your environment.

The Compliance Operator makes recommendations based on generally available information and practices that relate to such standards and can assist with remediation, but actual compliance is your responsibility. You are required to work with an authorized auditor to achieve compliance with a standard. 

For the latest updates, see the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{ocp-latest-version}/html/security_and_compliance/compliance-operator#compliance-operator-release-notes[Compliance Operator release notes].

include::modules/compliance-operator-install.adoc[leveloffset=+1]

include::modules/compliance-operator-configure-scanning.adoc[leveloffset=+1]

// See https://docs.openshift.com/container-platform/4.12/security/compliance_operator/compliance-scans.html#running-compliance-scans_compliance-operator-scans. 

Optional: If you installed the Compliance Operator _after_ installing {product-title-short}, restart Sensor in the secured cluster by performing one of the following options:

* Run the following command:
+
[source, terminal]
----
$ oc -n stackrox delete pod -lapp=sensor
----
* In the {ocp} web console, perform the following steps:
.. Change the active project to `stackrox`.
.. Navigate to *Workloads* -> *Pods*.
.. Locate the pod with the name starting with `sensor-`, and then click *Actions* -> *Delete Pod.* 

.Verification
After performing these steps, run a compliance scan in {product-title-short} and ensure that `ocp4-cis` and `ocp4-cis-node` results are displayed. See "Running a compliance scan" in the "Additional resources" section for more information.

.Additional resources
* xref:../../operating/manage-compliance.adoc#run-compliance-scan_manage-compliance[Running a compliance scan in {product-title-short}]