:_mod-docs-content-type: ASSEMBLY
[id="virt-disaster-recovery"]
= Disaster recovery
include::_attributes/common-attributes.adoc[]
:context: virt-about-dr

toc::[]

The disaster recovery documentation provides information for administrators on how to recover from certain disaster scenarios that might occur with an {product-title} cluster. As an administrator, you must plan your {VirtProductName} deployment in advance in order to take advantage of disaster recovery.

Metropolitan Disaster Recovery (Metro-DR)::
Metro-DR provides two-way synchronous data replication between managed {VirtProductName} clusters installed on primary and secondary sites. Use Metro-DR during a site disaster to fail applications from the primary to the secondary site, and to relocate the application back to the primary site after restoring the disaster site. This synchronous solution is only available to metropolitan distance data centers with a 10 millisecond latency or less. For more information, see https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.14/html-single/configuring_openshift_data_foundation_disaster_recovery_for_openshift_workloads/index#metro-dr-solution[Metro-DR solution for OpenShift Data Foundation].