[id='deploying-cam-4-2-4']
= Deploying the Cluster Application Migration tool
include::modules/common-attributes.adoc[]
:context: migrating-4-2-4
:migrating-4-2-4:

toc::[]

You can install the Cluster Application Migration Operator on your {product-title} {product-version} target cluster and 4.2 source cluster. The Cluster Application Migration Operator installs the Cluster Application Migration (CAM) tool on the target cluster by default.

[NOTE]
====
Optional: You can configure the Cluster Application Migration Operator to install the CAM tool link:https://access.redhat.com/articles/5064151[on an {product-title} 3 cluster or on a remote cluster].
====

In a restricted environment, you can install the Cluster Application Migration Operator from a local mirror registry.

After you have installed the Cluster Application Migration Operator on your clusters, you can launch the CAM tool.

== Installing the Cluster Application Migration Operator

You can install the Cluster Application Migration Operator with the Operation Lifecycle Manager (OLM) on an {product-title} {product-version} target cluster and on an {product-title} 4.1 source cluster.

:!migrating-4-2-4:

:context: target-4-2-4
:target-4-2-4:
include::modules/migration-installing-cam-operator-ocp-4.adoc[leveloffset=+2]
:target-4-2-4!:

:context: source-4-2-4
:source-4-2-4:
include::modules/migration-installing-cam-operator-ocp-4.adoc[leveloffset=+2]
:source-4-2-4!:

:context: disconnected-4-2-4
:disconnected-4-2-4:

== Installing the Cluster Application Migration Operator in a restricted environment

You can build a custom Operator catalog image for {product-title} 4, push it to a local mirror image registry, and configure OLM to install the Operator from the local registry.

.Additional resources

* xref:../../operators/olm-restricted-networks.adoc#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks]

include::modules/olm-building-operator-catalog-image.adoc[leveloffset=+2]
include::modules/olm-restricted-networks-configuring-operatorhub.adoc[leveloffset=+2]
:!disconnected-4-2-4:

:context: disconnected-target-4-2-4
:disconnected-target-4-2-4:
include::modules/migration-installing-cam-operator-ocp-4.adoc[leveloffset=+2]
:disconnected-target-4-2-4!:

:context: disconnected-source-4-2-4
:disconnected-source-4-2-4:
include::modules/migration-installing-cam-operator-ocp-4.adoc[leveloffset=+2]
:disconnected-source-4-2-4!:

:context: migrating-4-2-4
:migrating-4-2-4:
include::modules/migration-launching-cam.adoc[leveloffset=+1]
include::modules/migration-upgrading-migration-tool.adoc[leveloffset=+1]
:!migrating-4-2-4:
