= Builds and Image Streams
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:

toc::[]

ifdef::openshift-origin,openshift-online,openshift-enterprise,openshift-dedicated[]
== Builds
A link:../../dev_guide/builds.html[build] is the process of transforming input
parameters into a resulting object. Most often, the process is used to transform
input parameters or source code into a runnable image. A
link:../../dev_guide/builds.html#defining-a-buildconfig[BuildConfig] object is
the definition of the entire build process.

OpenShift leverages Kubernetes by creating Docker containers from build images
and pushing them to a
link:../../architecture/infrastructure_components/image_registry.html#integrated-openshift-registry[Docker registry].

Build objects share common characteristics: inputs for a build, the need to
complete a build process, logging the build process, publishing resources from
successful builds, and publishing the final status of the build. Builds take
advantage of resource restrictions, specifying limitations on resources such as
CPU usage, memory usage, and build or pod execution time.

The OpenShift build system provides extensible support for _build strategies_
that are based on selectable types specified in the build API. There are three
build strategies available:

- link:#docker-build[Docker build]
- link:#source-build[Source-to-Image (S2I) build]
- link:#custom-build[Custom build]

By default, Docker builds and S2I builds are supported.

The resulting object of a build depends on the builder used to create it. For
Docker and S2I builds, the resulting objects are runnable images. For Custom
builds, the resulting objects are whatever the builder image author has
specified.

For a list of build commands, see the
link:../../dev_guide/builds.html[Developer's Guide].

For more information on how OpenShift leverages Docker for builds, see the link:https://github.com/openshift/origin/blob/master/docs/builds.md#how-it-works[upstream documentation].

[[docker-build]]
=== Docker Build
The Docker build strategy invokes the plain
https://docs.docker.com/engine/reference/commandline/build/[docker build] command,
and it therefore expects a repository with a *_Dockerfile_* and all required
artifacts in it to produce a runnable image.

[[source-build]]
=== Source-to-Image (S2I) Build
link:../../creating_images/s2i.html[Source-to-Image (S2I)] is a tool for
building reproducible Docker images. It produces ready-to-run images by
injecting application source into a Docker image and assembling a new Docker
image.  The new image incorporates the base image (the builder) and built source
and is ready to use with the `docker run` command. S2I supports incremental
builds, which re-use previously downloaded dependencies, previously built
artifacts, etc.

The advantages of S2I include the following:

[horizontal]
Image flexibility:: S2I scripts can be written to inject application code into
almost any existing Docker image, taking advantage of the existing ecosystem.
Note that, currently, S2I relies on `tar` to inject application
source, so the image needs to be able to process tarred content.

Speed:: With S2I, the assemble process can perform a large number of complex
operations without creating a new layer at each step, resulting in a fast
process. In addition, S2I scripts can be written to re-use artifacts stored in a
previous version of the application image, rather than having to download or
build them each time the build is run.

Patchability:: S2I allows you to rebuild the application consistently if an
underlying image needs a patch due to a security issue.

Operational efficiency:: By restricting build operations instead of allowing
arbitrary actions, as a *_Dockerfile_* would allow, the PaaS operator can avoid
accidental or intentional abuses of the build system.

Operational security:: Building an arbitrary *_Dockerfile_* exposes the host
system to root privilege escalation. This can be exploited by a malicious user
because the entire Docker build process is run as a user with Docker privileges.
S2I restricts the operations performed as a root user and can run the scripts
as a non-root user.

User efficiency:: S2I prevents developers from performing arbitrary `yum
install` type operations, which could slow down development iteration, during
their application build.

Ecosystem:: S2I encourages a shared ecosystem of images where you can leverage
best practices for your applications.

[[custom-build]]
=== Custom Build
The Custom build strategy allows developers to define a specific builder image
responsible for the entire build process. Using your own builder image allows
you to customize your build process.

A link:../../creating_images/custom.html[Custom builder image] is a plain Docker
image embedded with build process logic, for example for building RPMs or base
Docker images. The `openshift/origin-custom-docker-builder` image is available
on the
https://registry.hub.docker.com/u/openshift/origin-custom-docker-builder[Docker
Hub] as an example implementation of a Custom builder image.

endif::[]
[[image-streams]]

== Image Streams

ifdef::openshift-origin,openshift-online,openshift-enterprise,openshift-dedicated[]
An _image stream_ can be used to automatically perform an action, such as
updating a deployment, when a new image, such as a new version of the base image
that is used in that deployment, is created.
endif::[]

An image stream comprises one or more
link:containers_and_images.html#docker-images[Docker images] identified by tags.
It presents a single virtual view of related images, similar to a Docker image
repository, and may contain images from any of the following:

. Its own image repository in OpenShift's integrated Docker Registry
. Other image streams
. Docker image repositories from external registries

ifdef::openshift-origin,openshift-online,openshift-enterprise,openshift-dedicated[]
OpenShift components such as builds and deployments can watch an image stream
to receive notifications when new images are added and react by performing
a build or a deployment.
endif::[]

.Image Stream Object Definition
====

[source,yaml]
----
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2016-01-29T13:33:49Z
  generation: 1
  labels:
    app: ruby-sample-build
    template: application-template-stibuild
  name: origin-ruby-sample
  namespace: test
  resourceVersion: "633"
  selfLink: /oapi/v1/namespaces/test/imagestreams/origin-ruby-sample
  uid: ee2b9405-c68c-11e5-8a99-525400f25e34
spec: {}
status:
  dockerImageRepository: 172.30.56.218:5000/test/origin-ruby-sample
  tags:
  - items:
    - created: 2016-01-29T13:40:11Z
      dockerImageReference: 172.30.56.218:5000/test/origin-ruby-sample@sha256:47463d94eb5c049b2d23b03a9530bf944f8f967a0fe79147dd6b9135bf7dd13d
      generation: 1
      image: sha256:47463d94eb5c049b2d23b03a9530bf944f8f967a0fe79147dd6b9135bf7dd13d
    tag: latest
----

====

[[image-stream-mappings]]

=== Image Stream Mappings
When the integrated OpenShift Docker Registry receives a new image, it creates
and sends an `*ImageStreamMapping*` to OpenShift. This informs OpenShift of the
image's namespace, name, tag, and Docker metadata. OpenShift uses this
information to create a new image (if it does not already exist) and to tag the
image into the image stream.  OpenShift stores complete metadata about each
image (e.g., command, entrypoint, environment variables, etc.). Note that images
in OpenShift are immutable. Also, note that the maximum name length is 63
characters.

The example `*ImageStreamMapping*` below results in an image being tagged as
`test/origin-ruby-sample:latest`.


.Image Stream Mapping Object Definition
====

[source,yaml]
----
apiVersion: v1
kind: ImageStreamMapping
metadata:
  creationTimestamp: null
  name: origin-ruby-sample
  namespace: test
tag: latest
image:
  dockerImageLayers:
  - name: sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
    size: 0
  - name: sha256:ee1dd2cb6df21971f4af6de0f1d7782b81fb63156801cfde2bb47b4247c23c29
    size: 196634330
  - name: sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
    size: 0
  - name: sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
    size: 0
  - name: sha256:ca062656bff07f18bff46be00f40cfbb069687ec124ac0aa038fd676cfaea092
    size: 177723024
  - name: sha256:63d529c59c92843c395befd065de516ee9ed4995549f8218eac6ff088bfa6b6e
    size: 55679776
  - name: sha256:92114219a04977b5563d7dff71ec4caa3a37a15b266ce42ee8f43dba9798c966
    size: 11939149
  dockerImageMetadata:
    Architecture: amd64
    Config:
      Cmd:
      - /usr/libexec/s2i/run
      Entrypoint:
      - container-entrypoint
      Env:
      - RACK_ENV=production
      - OPENSHIFT_BUILD_NAMESPACE=test
      - OPENSHIFT_BUILD_SOURCE=https://github.com/openshift/ruby-hello-world.git
      - EXAMPLE=sample-app
      - OPENSHIFT_BUILD_NAME=ruby-sample-build-1
      - PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - STI_SCRIPTS_URL=image:///usr/libexec/s2i
      - STI_SCRIPTS_PATH=/usr/libexec/s2i
      - HOME=/opt/app-root/src
      - BASH_ENV=/opt/app-root/etc/scl_enable
      - ENV=/opt/app-root/etc/scl_enable
      - PROMPT_COMMAND=. /opt/app-root/etc/scl_enable
      - RUBY_VERSION=2.2
      ExposedPorts:
        8080/tcp: {}
      Labels:
        build-date: 2015-12-23
        io.k8s.description: Platform for building and running Ruby 2.2 applications
        io.k8s.display-name: 172.30.56.218:5000/test/origin-ruby-sample:latest
        io.openshift.build.commit.author: Ben Parees <bparees@users.noreply.github.com>
        io.openshift.build.commit.date: Wed Jan 20 10:14:27 2016 -0500
        io.openshift.build.commit.id: 00cadc392d39d5ef9117cbc8a31db0889eedd442
        io.openshift.build.commit.message: 'Merge pull request #51 from php-coder/fix_url_and_sti'
        io.openshift.build.commit.ref: master
        io.openshift.build.image: centos/ruby-22-centos7@sha256:3a335d7d8a452970c5b4054ad7118ff134b3a6b50a2bb6d0c07c746e8986b28e
        io.openshift.build.source-location: https://github.com/openshift/ruby-hello-world.git
        io.openshift.builder-base-version: 8d95148
        io.openshift.builder-version: 8847438ba06307f86ac877465eadc835201241df
        io.openshift.expose-services: 8080:http
        io.openshift.s2i.scripts-url: image:///usr/libexec/s2i
        io.openshift.tags: builder,ruby,ruby22
        io.s2i.scripts-url: image:///usr/libexec/s2i
        license: GPLv2
        name: CentOS Base Image
        vendor: CentOS
      User: "1001"
      WorkingDir: /opt/app-root/src
    Container: 86e9a4a3c760271671ab913616c51c9f3cea846ca524bf07c04a6f6c9e103a76
    ContainerConfig:
      AttachStdout: true
      Cmd:
      - /bin/sh
      - -c
      - tar -C /tmp -xf - && /usr/libexec/s2i/assemble
      Entrypoint:
      - container-entrypoint
      Env:
      - RACK_ENV=production
      - OPENSHIFT_BUILD_NAME=ruby-sample-build-1
      - OPENSHIFT_BUILD_NAMESPACE=test
      - OPENSHIFT_BUILD_SOURCE=https://github.com/openshift/ruby-hello-world.git
      - EXAMPLE=sample-app
      - PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - STI_SCRIPTS_URL=image:///usr/libexec/s2i
      - STI_SCRIPTS_PATH=/usr/libexec/s2i
      - HOME=/opt/app-root/src
      - BASH_ENV=/opt/app-root/etc/scl_enable
      - ENV=/opt/app-root/etc/scl_enable
      - PROMPT_COMMAND=. /opt/app-root/etc/scl_enable
      - RUBY_VERSION=2.2
      ExposedPorts:
        8080/tcp: {}
      Hostname: ruby-sample-build-1-build
      Image: centos/ruby-22-centos7@sha256:3a335d7d8a452970c5b4054ad7118ff134b3a6b50a2bb6d0c07c746e8986b28e
      OpenStdin: true
      StdinOnce: true
      User: "1001"
      WorkingDir: /opt/app-root/src
    Created: 2016-01-29T13:40:00Z
    DockerVersion: 1.8.2.fc21
    Id: 9d7fd5e2d15495802028c569d544329f4286dcd1c9c085ff5699218dbaa69b43
    Parent: 57b08d979c86f4500dc8cad639c9518744c8dd39447c055a3517dc9c18d6fccd
    Size: 441976279
    apiVersion: "1.0"
    kind: DockerImage
  dockerImageMetadataVersion: "1.0"
  dockerImageReference: 172.30.56.218:5000/test/origin-ruby-sample@sha256:47463d94eb5c049b2d23b03a9530bf944f8f967a0fe79147dd6b9135bf7dd13d
----
====

[[referencing-images-in-image-streams]]

=== Referencing Images in Image Streams

When defining tags in an image stream, you can decide if the tag should
be imported or just referenced from an image stream. This is achieved by
setting `reference`. By default `reference` is `false`, which means tag's
metadata will be imported during the import. Setting it to `true` on the
other hand, will mark the tag as a reference.

An `*ImageStreamTag*` is used to reference or retrieve an image for a given
image stream and tag. It uses the following convention for its name: `<image
stream name>:<tag>`.

An `*ImageStreamImage*` is used to reference or retrieve an image for a given
image stream and image name. It uses the following convention for its name:
`<image stream name>@<name>`.

A `*DockerImage*` is used to reference or retrieve an image for a given
external registry. It uses standard docker _pull specification_ for its name,
eg `openshift/ruby-20-centos7:2.0`. When no tag is specified it is assumed
the `latest` will be used.

[NOTE]
====
When looking at example image stream definitions, such as the
link:https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json[example
CentOS image streams], you may notice they contain definitions of
`*ImageStreamTags*` and references to `*DockerImages*`, but nothing related to
`*ImageStreamImages*`. This is because the `*ImageStreamImage*` objects are
automatically created in OpenShift whenever you import or tag an image into the
image stream. You should never have to explicitly define an `*ImageStreamImage*`
object in any image stream definition that you use to create image streams.
====

The sample image below is from the *ruby* image stream and was
retrieved by asking for the `*ImageStreamImage*` with the name
*ruby@3a335d7*:

.Definition of an Image Object retrieved via ImageStreamImage
====

[source,yaml]
----
apiVersion: v1
image:
  dockerImageLayers:
  - name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 0
  - name: sha256:ee1dd2cb6df21971f4af6de0f1d7782b81fb63156801cfde2bb47b4247c23c29
    size: 196634330
  - name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 0
  - name: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
    size: 0
  - name: sha256:ca062656bff07f18bff46be00f40cfbb069687ec124ac0aa038fd676cfaea092
    size: 177723024
  - name: sha256:63d529c59c92843c395befd065de516ee9ed4995549f8218eac6ff088bfa6b6e
    size: 55679776
  dockerImageMetadata:
    Architecture: amd64
    Author: SoftwareCollections.org <sclorg@redhat.com>
    Config:
      Cmd:
      - /bin/sh
      - -c
      - $STI_SCRIPTS_PATH/usage
      Entrypoint:
      - container-entrypoint
      Env:
      - PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - STI_SCRIPTS_URL=image:///usr/libexec/s2i
      - STI_SCRIPTS_PATH=/usr/libexec/s2i
      - HOME=/opt/app-root/src
      - BASH_ENV=/opt/app-root/etc/scl_enable
      - ENV=/opt/app-root/etc/scl_enable
      - PROMPT_COMMAND=. /opt/app-root/etc/scl_enable
      - RUBY_VERSION=2.2
      ExposedPorts:
        8080/tcp: {}
      Image: d9c3abc5456a9461954ff0de8ae25e0e016aad35700594714d42b687564b1f51
      Labels:
        build-date: 2015-12-23
        io.k8s.description: Platform for building and running Ruby 2.2 applications
        io.k8s.display-name: Ruby 2.2
        io.openshift.builder-base-version: 8d95148
        io.openshift.builder-version: 8847438ba06307f86ac877465eadc835201241df
        io.openshift.expose-services: 8080:http
        io.openshift.s2i.scripts-url: image:///usr/libexec/s2i
        io.openshift.tags: builder,ruby,ruby22
        io.s2i.scripts-url: image:///usr/libexec/s2i
        license: GPLv2
        name: CentOS Base Image
        vendor: CentOS
      User: "1001"
      WorkingDir: /opt/app-root/src
    ContainerConfig: {}
    Created: 2016-01-26T21:07:27Z
    DockerVersion: 1.8.2-el7
    Id: 57b08d979c86f4500dc8cad639c9518744c8dd39447c055a3517dc9c18d6fccd
    Parent: d9c3abc5456a9461954ff0de8ae25e0e016aad35700594714d42b687564b1f51
    Size: 430037130
    apiVersion: "1.0"
    kind: DockerImage
  dockerImageMetadataVersion: "1.0"
  dockerImageReference: centos/ruby-22-centos7@sha256:3a335d7d8a452970c5b4054ad7118ff134b3a6b50a2bb6d0c07c746e8986b28e
  metadata:
    creationTimestamp: 2016-01-29T13:17:45Z
    name: sha256:3a335d7d8a452970c5b4054ad7118ff134b3a6b50a2bb6d0c07c746e8986b28e
    resourceVersion: "352"
    uid: af2e7a0c-c68a-11e5-8a99-525400f25e34
kind: ImageStreamImage
metadata:
  creationTimestamp: null
  name: ruby@3a335d7
  namespace: openshift
  selfLink: /oapi/v1/namespaces/openshift/imagestreamimages/ruby@3a335d7
----
====

[[importing-tag-and-image-metadata]]

=== Importing Tag and Image Metadata

An image stream can be configured to import tag and image metadata from an image
repository in an external Docker image registry. See
link:../infrastructure_components/image_registry.html[Image Registry] for more
details.

[[adding-tag]]

=== Adding Tag

An image stream can also be configured so that a tag "tracks" another one. For
example, you can configure the *latest* tag to always refer to the current image
for the tag "2.0":

====
----
$ oc tag ruby:latest ruby:2.0
----
====

[[tag-removal]]

=== Tag Removal

You can stop tracking a tag by removing it. For example, you can stop tracking
the *latest* tag you set above:

====
----
$ oc tag -d ruby:latest
----
====

[IMPORTANT]
====
The above command removes the tag from the image stream spec, but not from the
image stream status. The image stream spec is user-defined, whereas the image
stream status reflects the information the system has from the specification. To
remove a tag completely from an image stream:

----
$ oc delete istag/ruby:latest
----
====

[[insecure-registries]]

=== Importing Images from Insecure Registries

An image stream can be configured to import tag and image metadata from insecure
image registries, such as those signed with a self-signed certificate or using
plain HTTP instead of HTTPS.

To configure this, add the `*openshift.io/image.insecureRepository*` annotation
and set it to *true*. This setting bypasses certificate validation when
connecting to the registry:

====
[source,yaml]
----
kind: ImageStream
apiVersion: v1
metadata:
  name: ruby
  annotations:
    openshift.io/image.insecureRepository: "true" <1>
  spec:
    dockerImageRepository: my.repo.com:5000/myimage
----
<1> Set the `*openshift.io/image.insecureRepository*` annotation to *true*
====

ifdef::openshift-enterprise,openshift-origin[]
[IMPORTANT]
====
The above definition only affects importing tag and image metadata. For this
image to be used in the cluster (e.g., to be able to do a `docker pull`), each
node must have Docker configured with the `--insecure-registry` flag. See
link:../../install_config/install/prerequisites.html#host-preparation[Host
Preparation] for information.
====
endif::[]

Additionally there is an option to specify single tag use insecure repository.
To do that set `.importPolicy.insecure` in tag's definition to *true*:

====
[source,yaml]
----
kind: ImageStream
apiVersion: v1
metadata:
  name: ruby
  tags:
  - from:
      kind: DockerImage
      name: my.repo.com:5000/myimage
    name: mytag
    importPolicy:
      insecure: "true" <1>
----
<1> Set tag ruby:mytag to use insecure connection to that registry.
====

[[private-registries]]

=== Importing Images from Private Registries

An image stream can be configured to import tag and image metadata from private
image registries, requiring authentication.

To configure this, you need to create a link:../dev_guide/secrets.html[`*secret*`]
which is used to store your credentials.

. Create the `*secret*` first before importing image from the private repository:

====
----
$ oc secrets new-dockercfg SECRET --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD --docker-email=DOCKER_EMAIL
----
====

For other options consult with `oc secrets new --help`.

Once the secret is configured proceed with creating new Image Stream or using
`oc import-image` command. During the import process OpenShift will pick up the
secrets and provide to the remote party.

[[image-pull-policy]]

=== Image Pull Policy

Each container in a pod has a Docker image. Once you have created an image and
pushed it to a registry, you can then refer to it in the pod.

When OpenShift creates containers, it uses the container's `*imagePullPolicy*`
to determine if the image should be pulled prior to starting the container.
There are three possible values for `*imagePullPolicy*`:

- `*Always*` - always pull the image.
- `*IfNotPresent*` - only pull the image if it does not already exist on the node.
- `*Never*` - never pull the image.

If a container's `*imagePullPolicy*`
parameter is not specified, OpenShift sets it based on the image's tag:

. If the tag is *latest*, OpenShift defaults `*imagePullPolicy*` to `*Always*`.
. Otherwise, OpenShift defaults `*imagePullPolicy*` to `*IfNotPresent*`.
