[id="3061-release-notes"]
=  Red Hat Advanced Cluster Security for Kubernetes version 3.0.61
include::modules/common-attributes.adoc[]
:context: 3061-release-notes

toc::[]

[role="_abstract"]
{product-title} 3.0.61 includes feature enhancements, bug fixes, scale improvements, and other changes.

//To upgrade to this release from a previous version, see the link:/docs/upgrade-stackrox/[Upgrade]section.

*Release date:* June 10, 2021

[id="new-features"]
== New features

* *ROX-6639*: {product-title} includes a new policy criteria for vulnerabilities severity score in an image's contents.
It provides a more accurate reflection of risk than a CVSS score.

[id="important-bug-fixes"]
== Important bug fixes

* *ROX-6991 and ROX-7058*: Previously, CSV exports of security risks were inconsistent with the RHACS user interface.

* *ROX-7004*: Previously, CVE-2016-4074 was reported as a false positive when images contained the component `jq 1.6-r0` or `jq 1.6-r1`.

* *ROX-7270*: Previously, under certain conditions, searched images would not correctly index and display.

* *ROX-7276*: Previously, improper handling of very short-lived tokens caused the GitLab OIDC authentication provider to prematurely log users out.

[id="resolved-in-version-30611"]
=== Resolved in version 3.0.61.1

Release date: June 21, 2021

* *ROX-7387*: Previously, in deployments using non-standard namespaces, admission controller failed to enforce or monitor deploy time policies.

[id="important-system-changes"]
== Important system changes

* *ROX-6639*: {product-title} includes a new default policy to flag fixable high or important severity vulnerabilities in images.
* *ROX-7133*: {product-title} now calculates the image risk using a score assigned to the severity rating of a vulnerability rather than the CVSS score.
Doing this provides a more accurate reflection of an image's risk.

[id="image-versions"]
== Image versions

|===
| Image | Description | Current version

| Main
| It includes Central, Sensor, Admission Controller, and Compliance.
It also includes `roxctl` for use in  CI (continuous integration) systems.
| stackrox.io/main:3.0.61.1

| Scanner
| Scans images and nodes.
| stackrox.io/scanner:2.15.2

| Scanner DB
| Stores image scan results and vulnerability definitions.
| stackrox.io/scanner-db:2.15.2

| Collector
| Collects runtime activity in Kubernetes or {ocp} clusters.
| collector.stackrox.io/collector:3.1.25-latest
|===
