:_mod-docs-content-type: ASSEMBLY
[id="release-notes-43"]
= {product-title} 4.3
include::modules/common-attributes.adoc[]
:context: release-notes-43

toc::[]

{rh-rhacs-first} is an enterprise-ready, Kubernetes-native container security solution that protects your vital applications across the build, deploy, and runtime stages of the application lifecycle.
{product-title} deploys into your infrastructure and integrates with your DevOps tools and workflows. This integration provides better security and compliance, enabling DevOps and InfoSec teams to operationalize security.

.Release dates
[options="header"]
|====

|{product-title-short} version |Released on

|`4.3.0` | 15 November 2023
|`4.3.1` | 11 December 2023
|`4.3.2` | 8 January 2024
|`4.3.3` | 16 January 2024
|`4.3.4` | 22 January 2024
|`4.3.5` | 13 March 2024
|`4.3.6` | 27 March 2024
|`4.3.7` | 13 May 2024
|`4.3.8` | 11 June 2024

|====

[id="about-this-release_{context}"]
== About this release

{product-title-short} 4.3 adds new features, improvements, and updates.

[id="new-features_{context}"]
== New features

This release adds improvements related to the following components and concepts.

[id="hardware-software-support_{context}"]
=== Increased support for hardware and software

{product-title-short} support has been increased for the following hardware and software:

* {rh-ibm-cloud}: You can now protect {rh-ibm-cloud} by using {product-title-short}. With this release, you can run secured clusters on {rh-ibm-cloud}.
* {ibm-power} and {ibm-z}: {product-title-short} Central Services are now supported on {ibm-power} and {ibm-z}.
* {product-rosa}: {product-title-short} is supported on {product-rosa-short} hosted control plane (HCP) enabled clusters.
* {osp}: This release is supported with {ocp} 4.14.

For more information, see the https://access.redhat.com/articles/7045053[Red Hat Advanced Cluster Security for Kubernetes Support Matrix].

[id="vuln-report20-ga_{context}"]
=== Vulnerability reporting 2.0 is generally available

With this release, the *Vulnerability Reporting* option under the *Vulnerability Management (2.0)* menu is generally available. Several enhancements have been made to vulnerability reporting, including the ability to customize email templates that are used when reports are sent. For more information, see xref:../operating/manage-vulnerabilities/vulnerability-management.adoc#vulnerability-reporting-vuln-mgt2[Vulnerability Reporting].

[NOTE]
====
Reports created in the *Vulnerability Management 1.0* -> *Reporting* page are automatically migrated. For more information, see xref:../operating/manage-vulnerabilities/vulnerability-management.adoc#vulnerability-management-migration_acs-operating-manage-vulnerabilities[Migration of vulnerability reports when upgrading to {product-title-short} version 4.3 and later].
====

[id="watch-images-vm20_{context}"]
=== Watch and scan images in Vulnerability Management 2.0

The ability to mark an image as _watched_ has been migrated from the *Vulnerability Management (1.0)* menu item to *Vulnerability Management 2.0*. Watched images are still scanned for vulnerabilities even when not in use by an active deployment.

For more information, see xref:../operating/examine-images-for-vulnerabilities.adoc#scan-inactive-images_examine-images-for-vulnerabilities[Scanning inactive images].

[id="view-admin-events_{context}"]
=== View administration events information

With this release, {product-title-short} introduces an administration events dashboard that allows you to efficiently manage and troubleshoot events within your {product-title-short} instance and significantly improves the reliability and security of your {product-title-short} instance.

For more information, see xref:../operating/using-the-administration-events-page.adoc#using-the-administration-events-page[Using the administration events page].

[id="scan-images-using-roxctl_{context}"]
=== Scan images by using the roxctl CLI

You can now scan images stored in image registries, including cluster local registries such as the {ocp} integrated image registry, by using the `roxctl` CLI.

For more information, see xref:../cli/image-scanning-by-using-the-roxctl-cli.adoc#image-scanning-by-using-the-roxctl-cli[Image scanning by using the `roxctl` CLI].

[id="invite-users-rhacs-instance_{context}"]
=== Invite users to your RHACS instance

You can now invite users and define their roles to ensure accurate access control and improve the security of your {product-title-short} instance.

For more information, see xref:../configuration/inviting-users-to-your-rhacs-instance.adoc#inviting-users-to-your-rhacs-instance[Inviting users to your {product-title-short} instance].


[id="notable-technical-changes_{context}"]
== Notable technical changes

* When audit logging is enabled, audit log messages now include the source IP address of the audit log request. For more information, see xref:..//configuration/configure-audit-logging.adoc#enable-audit-log_configure-audit-logging[Enabling audit logging].
* The default policy "Iptables Executed in Privileged Container" has been renamed to "Iptables or nftables Executed in Privileged Container" and now also detects the `nft` process that is used by `nftables`.
* Risk reprocessing has been changed from potentially being computed every 15 seconds to 10 minutes. This improves system performance by debouncing expensive risk calculations. To use the earlier value for risk reprocessing, set the environment variable ROX_RISK_REPROCESSING_INTERVAL to `15s`.

[id="upcoming-changes_{context}"]
== Notice of upcoming changes to RHACS vulnerability management

In the past several {product-title-short} releases, we have optimized and enhanced {product-title-short} features and functionality available in the *Vulnerability Management (1.0)* menu item and migrated them to the *Vulnerability Management (2.0)* menu item.

The existing page for *Risk Acceptance* in the *Vulnerability Management (1.0)* menu item will be migrated to the *Vulnerability Management (2.0)* menu item in an upcoming release. It will be renamed *Vulnerability Exception Management*.

We invite you to review the existing features in the *Vulnerability Management (2.0)* menu item and give us feedback by clicking the red *Feedback* button in the {product-title-short} web portal.

[id="deprecated-and-removed-features_{context}"]
== Deprecated and removed features

Some features available in earlier releases have been deprecated or removed.

Deprecated functionality is still included in {product-title-short} and continues to be supported; however, it will be removed in a future release of this product and is not recommended for new deployments.
For the most recent list of major functionality deprecated and removed, see the following table.
Additional information about some removed or deprecated functionality is available after the table.

In the table, features are marked with the following statuses:

* GA: General Availability
* TP: Technology Preview
* DEP: Deprecated
* REM: Removed
* NA: Not applicable

.Deprecated and removed features tracker
[cols="3,1,1,1",options="header"]
|====
| Feature | {product-title-short} 4.1 |{product-title-short} 4.2 | {product-title-short} 4.3

| CIS Docker v1.2.0 Compliance Standard
| NA
| DEP
| DEP

| Custom Security Context Constraints (SCCs): `stackrox-collector`,`stackrox-admission-control`, and `stackrox-sensor`
| DEP
| DEP
| REM

| Examining images for Application-level dependencies for vulnerability reporting: `dotnet/shared/Microsoft.AspNetCore.App/` and `dotnet/shared/Microsoft.NETCore.App/`
| DEP
| DEP
| REM

| `Expiration` field in `Exclusion` proto
| DEP
| DEP
| REM

| `roxctl connectivity-map`
| NA
| DEP
| DEP

| `roxctl generate netpol`
| NA
| DEP
| DEP

| `/v1/clustercves/suppress` APIs
| NA
| NA
| DEP

| `/v1/clustercves/unsuppress` APIs
| NA
| NA
| DEP

| `/v1/cve/requests` APIs
| NA
| NA
| DEP

| `/v1/nodecves/suppress` APIs
| NA
| NA
| DEP

| `/v1/nodecves/unsuppress` APIs
| NA
| NA
| DEP

| `/v1/report` endpoint
| DEP
| DEP
| REM

| `/v1/serviceaccounts` endpoint
| DEP
| DEP
| REM

| *Vulnerability Management (1.0)* menu item
| GA
| GA
| DEP

| *Vulnerability Management (1.0)*: Image CVEs, Image Components, Images, Deployments, and Namespaces
| DEP
| DEP
| REM

| *Vulnerability Management (1.0)* -> *Vulnerability Reporting* page
| DEP
| DEP
| REM

| `Vulnerability Management Approver` permission
| DEP
| DEP
| REM

| `Vulnerability Report Creator` permission
| GA
| DEP
| DEP

| `Vulnerability Management Requester` permission
| DEP
| DEP
| REM

|====


[id="deprecated-features_{context}"]
=== Deprecated features

The following section provides additional information about deprecated features listed in the preceding table.

* The *Vulnerability Management (1.0)* menu item in the {product-title-short} web portal has been deprecated and future removal is planned. It is replaced by *Vulnerability Management (2.0)*.
* The `/v1/cve/requests` APIs have been deprecated and will be replaced by `/v2/vulnerability-exceptions/` APIs in the future.
Vulnerability deferral management for host (`/node`) and platform (`/cluster`) vulnerabilities has been deprecated and will be removed in the future. After deferral management is removed, deferrals cannot be created for host and platform vulnerabilities and the existing exceptions enforced on host and platform vulnerabilities will be reverted. The affected APIs are `/v1/nodecves/suppress`, `/v1/nodecves/unsuppress`, `/v1/clustercves/suppress`, and `/v1/clustercves/unsuppress`.

[id="removed-features_{context}"]
=== Removed features

* The *Vulnerability Reporting* page in the *Vulnerability Management (1.0)* menu item has been removed. Vulnerability reporting is available under the *Vulnerability Management (2.0)* menu item.
* The `/v1/report` APIs have been removed. Use the `/v2/reports/` APIs.

[id="bug-fixes_{context}"]
== Bug fixes

[id="resolved-in-version-430_{context}"]
=== Resolved in version 4.3.0

*Release date*: 15 November 2023

* Fixed the diagnostic bundle generation returning an incomplete .zip file when the connection to a secured cluster is lost.
* Fixed an issue with the Sensor upgrade tool failing to upgrade from earlier versions on {ocp} clusters.
* In some cases, Common Vulnerabilities and Exposures (CVEs) that were deferred and approved were not added to the list of snoozed CVEs. This behavior was caused by an issue with the `/v1/suppress` and `/v1/unsuppress` APIs and has been fixed.
* Fixed file search in the `ca-setup.sh` file that is used to configure additional Certificate Authorities (CAs). Previously, the script could not find any files in the directory, even with the correct .crt and .pem extensions.

[id="resolved-in-version-431_{context}"]
=== Resolved in version 4.3.1

*Release date* 11 December 2023

* Fixed an issue where a user could not log in if a role mapped to the user did not have at least `read` access for the `Access` permission.
* Fixed an issue with editing user-defined vulnerability reports in version 4.3 that were created in a previous version and linked to a specific report scope. When editing the report in version 4.3, the report scope reference was missing, and the system returned an error message.
* Updated and removed golang dependencies to address reported vulnerabilities, including false positives.

[id="resolved-in-version-432_{context}"]
=== Resolved in version 4.3.2

*Release date*: 8 January 2024

* Fixed an issue with manual delegated scanning that caused Central to crash.
* Fixed PostgreSQL vulnerabilities in `scanner-db` containers.

[id="resolved-in-version-433_{context}"]
=== Resolved in version 4.3.3

*Release date*: 16 January 2024

* This release contains updates to the versions of golang and go-git used in {product-title-short}.

[id="resolved-in-version-434_{context}"]
=== Resolved in version 4.3.4

*Release date*: 22 January 2024

This release contains the following bug fixes and enhancements.

The following fixes and enhancements for integration with Jira and Jira Cloud are implemented:

* The priority is now correctly set on Jira issues created by {product-title-short}.
* The {product-title-short} integration with Jira Cloud can successfully be created.
* The default priority mappings in the integration creation page in the {product-title-short} portal have been updated to match the default Jira priorities.
* Checks were added for integration creation to minimize the risk that issue creation will fail after the integration is saved.
* A checkbox was added to give you the option to disable setting the priority.

A TLS certificate rotation fix is included. In the past, the Operator attempted to rotate TLS certificates for Central components only after they expired. Additionally, a bug prevented update of the expired certificate in the `central-tls` secret. With this fix, the Operator will rotate all Central components' service TLS certificates 6 months before they expire. The following conditions apply:

* The rotation of certificates in the secrets does not trigger the components to automatically reload them. However, reloads typically occur when the pod is replaced as part of an {product-title-short} upgrade or as a result of node reboots. If neither of those events happens at least every 6 months, you must restart the pods before the old (in-memory) service certificates expire. For example, you can delete the pods with an `app` label that contains one of the values of `central`, `central-db`, `scanner`, or `scanner-db`.
* CA certificates are not updated. They are valid for 5 years.
* The service certificates in the init bundles used by secured cluster components are not updated. You must rotate the init bundles at regular intervals.

[id="resolved-in-version-435_{context}"]
=== Resolved in version 4.3.5

*Release date*: 13 March 2024

This release provides the following bug fix:

* Fixed an issue where an upgrade to version 4.3 from an earlier version caused the Central component to enter a crash loop.

It provides the following security fixes:

* pgx: SQL Injection via Protocol Message Size Overflow (link:https://access.redhat.com/security/cve/cve-2024-27304[CVE-2024-27304])
* pgx: SQL Injection via Line Comment Creation (link:https://access.redhat.com/security/cve/cve-2024-27289[CVE-2024-27289])

[id="resolved-in-version-436_{context}"]
=== Resolved in version 4.3.6

*Release date*: 27 March 2024

This release provides the following bug fix:

* Fixed an issue where an incorrectly configured Jira notifier causes the Central component of {product-title-short} to enter a crash loop

It provides the following security fix where an image is flagged due to an indirect dependency of {product-title-short}:

* go-git: Maliciously crafted Git server replies can lead to path traversal and remote code execution (RCE) on go-git clients link:https://access.redhat.com/security/cve/cve-2023-49569[(CVE-2023-49569)]

It also provides the following security fixes:

* Helm: Missing YAML content leads to panic link:https://access.redhat.com/security/cve/cve-2024-26147[(CVE-2024-26147)]
* Helm: Shows secrets with `--dry-run` option in clear text link:https://access.redhat.com/security/cve/cve-2019-25210[(CVE-2019-25210)]

[id="resolved-in-version-437_{context}"]
=== Resolved in version 4.3.7

*Release date*: 13 May 2024

This release provides the following bug fixes:

* This release fixes an issue where the Central pod failed with a `SQLSTATE 23503` error after updating {product-title-short} to release 4.3.6. This resulted in the collector pods showing the `CrashLoopBackoff` state because the collector probe was unavailable.
* This release updates the Scanner baseline vulnerability data to address changes made to the Red{nbsp}Hat security data feeds that were not compatible with earlier data from Scanner's scheduled feed processing. This fixes various issues where vulnerabilities were detected for images containing packages that were incorrectly indicated as affected by a vulnerability.
* This release fixes a crash and rendering error in the network graph that occurs when Central is running an {product-title-short} release of 4.3.6 or earlier and Sensor is running an {product-title-short} release of 4.4.0 or later.

This release provides the following change:

* The default telemetry endpoint is now set to a Red{nbsp}Hat proxy.

This releases updates the following items to patch vulnerabilities:

* Go has been updated to release 1.20.12.
* The `golang.org/x/net` module has been updated from release v0.22.0 to v0.23.0.

[id="resolved-in-version-438_{context}"]
=== Resolved in version 4.3.8

*Release date*: 11 June 2024

This release contains updates to patch vulnerabilities, including the following update:

* `webpack-dev-middleware` has been updated from version 5.3.3 to version 5.3.4.

The following Scanner packages have been updated:

* `github.com/containers/image/v5` from v5.28.0 to v5.29.3
* `github.com/docker/docker` from v24.0.7 to v24.0.9

[id="known-issues-430_{context}"]
== Known issues

* {product-title-short} version 4.2 introduced additional logic that considers the socket connection state to decide whether Collector reports a connection or not. The expected behavior is that the connection is not reported until it is successfully established. A known issue on the `ppc64le` architecture can cause a blocked or failing connection to be reported instead of being silenced. No workaround exists for this issue.
* {product-title-short} Central components do not deploy correctly on a default {product-rosa-short} cluster. The workaround is to scale the worker nodes to allow the {product-title-short} components to be scheduled. See link:https://access.redhat.com/solutions/7035877[{product-title-short} Central pods do not schedule on a default ROSA cluster] for more information.

[id="image-versions_{context}"]
== Image versions

[%header,cols="1,1,2"]
|===
| Image | Description | Current version

| Main
| Includes Central, Sensor, Admission controller, and Compliance. Also includes `roxctl` for use in continuous integration (CI) systems.
a| `registry.redhat.io/advanced-cluster-security/rhacs-main-rhel8:{rhacs-version}`

| Scanner
| Scans images and nodes.
a|`registry.redhat.io/advanced-cluster-security/rhacs-scanner-rhel8:{rhacs-version}`

| Scanner DB
| Stores image scan results and vulnerability definitions.
a|`registry.redhat.io/advanced-cluster-security/rhacs-scanner-db-rhel8:{rhacs-version}`

| Collector
| Collects runtime activity in Kubernetes or {ocp} clusters.
a| * `registry.redhat.io/advanced-cluster-security/rhacs-collector-rhel8:{rhacs-version}`
* `registry.redhat.io/advanced-cluster-security/rhacs-collector-slim-rhel8:{rhacs-version}`

| Central DB
| PostgreSQL instance that provides the database storage for Central.
a| `registry.redhat.io/advanced-cluster-security/rhacs-central-db-rhel8:{rhacs-version}`
|===
