:_content-type: ASSEMBLY
include::_attributes/common-attributes.adoc[]
[id="serverless-configuration"]
= Global configuration
:context: serverless-configuration

toc::[]

The {ServerlessOperatorName} manages the global configuration of a Knative installation, including propagating values from the `KnativeServing` and `KnativeEventing` custom resources to system link:https://kubernetes.io/docs/concepts/configuration/configmap/[config maps]. Any updates to config maps which are applied manually are overwritten by the Operator. However, modifying the Knative custom resources allows you to set values for these config maps.

Knative has multiple config maps that are named with the prefix `config-`. All Knative config maps are created in the same namespace as the custom resource that they apply to. For example, if the `KnativeServing` custom resource is created in the `knative-serving` namespace, all Knative Serving config maps are also created in this namespace.

The `spec.config` in the Knative custom resources have one `<name>` entry for each config map, named `config-<name>`, with a value which is be used for the config map `data`.

// Knative Eventing
include::modules/serverless-channel-default.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources
* xref:../../serverless/admin_guide/serverless-kafka-admin.adoc#serverless-kafka-broker-configmap_serverless-kafka-admin[Configuring Kafka broker settings]
* xref:../../serverless/eventing/brokers/serverless-broker-backing-channel-default.adoc#serverless-broker-backing-channel-default[Configuring the default broker backing channel]





ifdef::openshift-enterprise[]
[id="additional-resources_knative-serving-CR-config"]
[role="_additional-resources"]
== Additional resources
* xref:../../operators/understanding/crds/crd-managing-resources-from-crds.adoc[Managing resources from custom resource definitions]
* xref:../../storage/understanding-persistent-storage.adoc#understanding-persistent-storage[Understanding persistent storage]
* xref:../../networking/configuring-a-custom-pki.adoc[Configuring a custom PKI]
endif::[]
