:_content-type: ASSEMBLY
[id="enable-offline-mode"]
= Enabling offline mode
include::modules/common-attributes.adoc[]
:context: enable-offline-mode

toc::[]

[role="_abstract"]
You can use {product-title} for clusters that are not connected to the internet by enabling the offline mode. In offline mode, {product-title} components do not connect to addresses or hosts on the internet.

[NOTE]
====
{product-title} does not determine if the user-supplied hostnames, IP addresses, or other resources are on the internet. For example, if you try to integrate with a Docker registry hosted on the internet, {product-title} will not block this request.
====

To deploy and operate {product-title} in offline mode:

. Download {product-title-short} images and install them in your clusters. If you are using {ocp}, you can use link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/operators/understanding-operators#operator-lifecycle-manager-olm[{olm-first}] and OperatorHub to download images to a workstation that is connected to the internet. The workstation then pushes images to a mirror registry that is also connected to your secured cluster. For other platforms, you can use a program such as Skopeo or Docker to pull the images from the remote registry and push them to your own private registry, as described in xref:../configuration/enable-offline-mode.adoc#download-images-directly_enable-offline-mode[Downloading images directly].
. Enable offline mode during installation.
. (Optional) Routinely update Scanner’s vulnerability list by uploading a new definitions file.
. (Optional) When required, add support for runtime collection on more kernel versions by uploading new kernel support packages.

[IMPORTANT]
====
You can only enable offline mode during the installation, and not during an upgrade.
====

[id="download-images-for-offline-use"]
== Downloading images for offline use

include::modules/download-images-directly.adoc[leveloffset=+2]

include::modules/retag-images.adoc[leveloffset=+3]

[id="enable-offline-mode-during-installation"]
== Enabling offline mode during installation

You can enable offline mode during the installation of {product-title}.

include::modules/enable-offline-mode-helm.adoc[leveloffset=+2]

include::modules/enable-offline-mode-roxctl.adoc[leveloffset=+2]


[id="update-scanner-definitions-in-offline-mode"]
== Updating Scanner definitions in offline mode

Scanner contains a local vulnerability definitions database. When {product-title} runs in normal mode (connected to the internet), Scanner fetches new vulnerability definitions from the internet and updates its database.
//TODO: Add link to Vulnerability definitions

However, when you are using {product-title} in offline mode, you must manually update Scanner definitions by uploading them to Central.

When {product-title} runs in offline mode, Scanner checks for new definitions from Central. If new definitions are available, Scanner downloads the new definitions from Central, marks them as default, and then uses the updated definitions for scanning images.

To update the definitions in offline mode:

. Download the definitions.
. Upload the definitions to Central.

//Download the definitions
include::modules/download-scanner-definitions.adoc[leveloffset=+2]

[id="upload-definitions-to-central"]
=== Uploading definitions to Central

To upload Scanner definitions to Central, you can either use an API token or your administrator password. Red Hat recommends using an authentication token in a production environment because each token is assigned specific access control permissions.

//Upload the definitions to Central (API Token)
include::modules/upload-definitions-to-central-api-token.adoc[leveloffset=+3]

[role="_additional-resources"]
===== Additional resources
* xref:../cli/getting-started-cli.adoc#cli-authentication_cli-getting-started[Authenticating using the `roxctl` CLI]

//Upload the definitions to Central (admin password)
include::modules/upload-definitions-to-central-admin-pass.adoc[leveloffset=+3]

include::modules/update-kernel-support-packages.adoc[leveloffset=+1]

include::modules/download-kernel-support-package.adoc[leveloffset=+2]

include::modules/upload-kernel-support-package-to-central.adoc[leveloffset=+2]
