// Module included in the following assemblies:
//
// * admin_guide/cluster-autoscaler.adoc

[id='about-cluster-auto-scaler-{context}']
= About the {product-title} auto-scaler

The auto-scaler in {product-title} repeatedly checks to see how many
pods are pending node allocation. If pods are pending allocation and
the auto-scaler has not met its maximum capacity, then new nodes are
continuously provisioned to accommodate the current demand. When
demand drops and fewer nodes are required, the auto-scaler removes
unused nodes. The behaviour of the auto-scaler is automatic - there's
nothing additional to add to existing deployment beyond setting the
desired number of replicas.

In {product-title} version {product-version}, you can deploy the
auto-scaler only on Amazon Web Services (AWS). The auto-scaler uses
some standard AWS objects to manage your cluster size, including Auto
Scaling Groups (ASGs) and Launch Configurations (LCs).

The auto-scaler uses the following assets:

Auto Scaling groups:: An Auto Scaling group (ASG) is a logical
representation of a set of machines. You configure an ASG with a
minimum number of instances to run, the maximum number of instances
that can run, and your desired number of instances to run. An ASG
starts by launching enough instances to meet your desired capacity.
You can configure an ASGs to start with zero instances.

Launch Configurations::
A Launch Configuration (LC) is a template that an ASG uses to launch
instances; you specify information such as the ID of the Amazon
Machine Image (AMI); the instance type, such as *m4.large*; a key pair;
one or more security groups; or subnets.

{product-title} primed images::
When the ASG provisions a new instance, the image that runs must have
{product-name} already prepared. The ASG uses this image to both automatically
bootstrap the node and enroll it within the cluster without any manual
intervention.
