= Terminology
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:

toc::[]

== Overview


== Project vs Domain
Project is essentially a rename of domain from v2.  Project does have several features that aren't a part of domains in v2

== Gear vs Container
The gear and container names are interchangeable.  Containers have a cleaner mapping of being 1:1 with images where as many cartridges could be added to a single gear.  And with containers, the collocation concept is satisfied by pods.

== Master vs Broker
Masters in v3 do the job of the broker layer in v2.  However, the MongoDB and ActiveMQ layers used by the broker in v2 are no longer necessary since etcd is typically installed with each master.

== Cartridge vs Image
The easiest replacement term for cartridge in v3 is image.  An image does more than a cartridge from a packaging perspective providing better encapsulation and flexibility.  But the cartridge concept also included logic for build/deploy/routing which don't exist in images.  In v3 these additional needs are meet by source-to-image and templated configuration.

See: link:carts_vs_images.html[Cartridges vs Images]

== Application
The term/concept no longer exists in v3.  See: link:applications.html[Applications]