[id="integrate-with-splunk"]
= Integrating with Splunk
include::modules/common-attributes.adoc[]
:context: integrate-with-splunk

toc::[]

[role="_abstract"]
If you are using link:https://www.splunk.com/[Splunk], you can forward alerts from {product-title} to Splunk and view vulnerability and compliance related data from within Splunk.

Depending on your use case, you can integrate {product-title} with Splunk by using the following ways:

* By xref:../integration/integrate-with-splunk.adoc#integrate-splunk-http-event-collector[using an HTTP event collector] in Splunk
** Use the event collector option to forward alerts and audit log data
* By xref:../integration/integrate-with-splunk.adoc#integrate-splunk-add-on[using the StackRox Kubernetes Security Platform add-on]
** Use the add-on to pull vulnerability detection and compliance data into Splunk
+
[NOTE]
====
The StackRox Kubernetes Security Platform add-on is only available if you are using {product-title} version 3.0.51.0 or newer.
====

You can use one or both of these integration options to integrate the {product-title} with Splunk.

[id="integrate-splunk-http-event-collector"]
== Using the HTTP event collector

You can forward alerts from {product-title} to Splunk by using an HTTP event collector.

To integrate {product-title} with Splunk by using the HTTP event collector, follow these steps:

. Add a new HTTP event collector in Splunk and get the token value.
. Use the token value to set up notifications in {product-title}.
. Identify policies for which you want to send notifications, and update the notification settings for those policies.

include::modules/add-http-event-collector-splunk.adoc[leveloffset=+2]

include::modules/integrate-splunk-enable-http-event-collector.adoc[leveloffset=+3]

include::modules/splunk-configuring-acs.adoc[leveloffset=+2]

:toolname: Splunk
include::modules/configure-policy-notifications.adoc[leveloffset=+2]

[id="integrate-splunk-add-on"]
== Using the StackRox Kubernetes Security Platform add-on

You can use the StackRox Kubernetes Security Platform add-on to forward the vulnerability detection and compliance related data from the {product-title} to Splunk.

Begin by generating an API token with read permission for all resources in {product-title} and then use that token to install and configure the add-on.

include::modules/install-and-configure-the-splunk-add-on.adoc[leveloffset=+2]
