:_mod-docs-content-type: ASSEMBLY
[id="integrate-with-s3-api-compatible-services"]
= Integrating with S3 API compatible services
include::modules/common-attributes.adoc[]
:context: integrate-with-s3-api-compatible-services

toc::[]

[role="_abstract"]
{product-title} can be integrated with S3 API compatible services to enable data backups.
These backups can be used for data restoration in the case of an infrastructure disaster or corrupt data.
After integrating with the S3 API compatible provider, you can schedule daily or weekly backups and do manual on-demand backups.

The backup includes the entire {product-title-short} database, which includes all configurations, resources, events, and certificates.
Make sure that backups are stored securely.

[IMPORTANT]
====
* To back up to Amazon S3, use the dedicated xref:integrate-with-amazon-s3.adoc#integrate-with-amazon-s3[Amazon S3] integration to ensure the best compatibility.
* Red Hat does not test this integration with every S3 API compatible provider, so the integration is not guaranteed to work with all providers.
====

include::modules/s3-api-compatible-services-configuring-acs.adoc[leveloffset=+1]

include::modules/perform-on-demand-backups-s3-api-compatible-services.adoc[leveloffset=+1]

[role="_additional-resources"]
== Additional resources
* xref:../backup_and_restore/backing-up-acs.adoc#backing-up-red-hat-advanced-cluster-security-for-kubernetes[Backing up {product-title}]
* xref:../backup_and_restore/restore-acs.adoc#restoring-from-a-backup[Restoring from a backup]
