:_mod-docs-content-type: ASSEMBLY
:context: nodes-pods-allocate-dra
[id="nodes-pods-allocate-dra"]
= Allocating GPUs to pods by using DRA
include::_attributes/common-attributes.adoc[]

toc::[]

// Taken from https://issues.redhat.com/browse/OCPSTRAT-1756
// Naming taken from https://issues.redhat.com/browse/OCPSTRAT-2384. Is this correct?

[role="_abstract"]
You can use {attribute-based-full} to enable fine-tuned control over graphics processing unit (GPU) resource allocation in {product-title}, allowing pods to request GPUs based on specific device attributes, including product name, GPU memory capacity, compute capability, vendor name and driver version. Having access to these attributes, which are exposed by a third-party Dynamic Resource Allocation (DRA) driver, allows {product-title} to schedule a pod on a node that has the specific devices that the workload needs. 

This workflow provides significant improvement in the device allocation workflow when compared to device plugins, which require per-container device requests, do not support device sharing, and do not support expression-based device filtering.

// The following include statements pull in the module files that comprise
// the assembly. Include any combination of concept, procedure, or reference
// modules required to cover the user story. You can also include other
// assemblies.

include::modules/nodes-pods-allocate-dra-about.adoc[leveloffset=+1]

include::modules/nodes-pods-allocate-dra-configure-about.adoc[leveloffset=+1]

include::modules/nodes-pods-allocate-dra-configure.adoc[leveloffset=+1]
