[id="osdk-ansible"]
= Creating Ansible-based Operators
include::modules/common-attributes.adoc[]
:context: osdk-ansible

toc::[]

This guide outlines Ansible support in the Operator SDK and walks Operator authors through examples building and running Ansible-based Operators with the `operator-sdk` CLI tool that use Ansible playbooks and modules.

include::modules/osdk-ansible-support.adoc[leveloffset=+1]
include::modules/osdk-ansible-custom-resource-files.adoc[leveloffset=+2]
include::modules/osdk-ansible-watches-file.adoc[leveloffset=+2]
include::modules/osdk-ansible-extra-variables.adoc[leveloffset=+2]
include::modules/osdk-ansible-runner-directory.adoc[leveloffset=+2]

include::modules/osdk-building-ansible-operator.adoc[leveloffset=+1]

[id="osdk-ansible-k8s-module"]
== Managing application lifecycle using the k8s Ansible module

To manage the lifecycle of your application on Kubernetes using Ansible, you can use the link:https://docs.ansible.com/ansible/2.7/modules/k8s_module.html[`k8s` Ansible module]. This Ansible module allows a developer to either leverage their existing Kubernetes resource files (written in YAML) or express the lifecycle management in native Ansible.

One of the biggest benefits of using Ansible in conjunction with existing Kubernetes resource files is the ability to use Jinja templating so that you can customize resources with the simplicity of a few variables in Ansible.

This section goes into detail on usage of the `k8s` Ansible module. To get started, install the module on your local workstation and test it using a playbook before moving on to using it within an Operator.

include::modules/osdk-ansible-k8s-module-installing.adoc[leveloffset=+2]
include::modules/osdk-ansible-k8s-module-testing-locally.adoc[leveloffset=+2]
include::modules/osdk-ansible-k8s-module-inside-operator.adoc[leveloffset=+2]

include::modules/osdk-ansible-managing-cr-status.adoc[leveloffset=+1]

[id="osdk-ansible-addtl-resources"]
== Additional resources

- See xref:../../operators/operator_sdk/osdk-appendices.adoc#osdk-project-scaffolding-layout_operator-appendices[Appendices] to learn about the project directory structures created by the Operator SDK.
- link:https://blog.openshift.com/reaching-for-the-stars-with-ansible-operator/[Reaching for the Stars with Ansible Operator] - Red Hat OpenShift Blog

- link:https://operators.gitbook.io/operator-developer-guide-for-red-hat-partners/[Operator Development Guide for Red Hat Partners]
