:_mod-docs-content-type: ASSEMBLY
[id="installing-oadp-aws"]
= Configuring the OpenShift API for Data Protection with Amazon Web Services
include::_attributes/common-attributes.adoc[]
:context: installing-oadp-aws
:installing-oadp-aws:
:credentials: cloud-credentials
:provider: aws

toc::[]

You install the OpenShift API for Data Protection (OADP) with Amazon Web Services (AWS) by installing the OADP Operator. The Operator installs link:https://{velero-domain}/docs/v{velero-version}/[Velero {velero-version}].

include::snippets/oadp-mtc-operator.adoc[]

You configure AWS for Velero, create a default `Secret`, and then install the Data Protection Application. For more details, see xref:../../..//backup_and_restore/application_backup_and_restore/installing/oadp-installing-operator.adoc#oadp-installing-operator-doc[Installing the OADP Operator].

To install the OADP Operator in a restricted network environment, you must first disable the default OperatorHub sources and mirror the Operator catalog. See xref:../../../operators/admin/olm-restricted-networks.adoc#olm-restricted-networks[Using Operator Lifecycle Manager on restricted networks] for details.

You can also install OADP on an AWS Security Token Service (AWS STS) cluster manually. Amazon AWS provides AWS Security Token Service (AWS STS) as a web service that enables you to request temporary, limited-privilege credentials for users. You use STS to provide trusted users with temporary access to resources via API calls, your AWS console or the AWS command line interface (CLI).


//include::modules/oadp-installing-operator.adoc[leveloffset=+1]
include::modules/migration-configuring-aws-s3.adoc[leveloffset=+1]
include::modules/oadp-about-backup-snapshot-locations-secrets.adoc[leveloffset=+1]
include::modules/oadp-creating-default-secret.adoc[leveloffset=+2]
include::modules/oadp-secrets-for-different-credentials.adoc[leveloffset=+2]

[id="configuring-dpa-aws"]
== Configuring the Data Protection Application

You can configure the Data Protection Application by setting Velero resource allocations or enabling self-signed CA certificates.

include::modules/oadp-setting-resource-limits-and-requests.adoc[leveloffset=+2]
include::modules/oadp-self-signed-certificate.adoc[leveloffset=+2]

include::modules/oadp-installing-dpa-1-2-and-earlier.adoc[leveloffset=+1]
include::modules/oadp-installing-dpa-1-3.adoc[leveloffset=+1]
include::modules/oadp-enabling-csi-dpa.adoc[leveloffset=+2]

:!installing-oadp-aws:
