:_mod-docs-content-type: ASSEMBLY
[id="windows-containers-support"]
= Getting support
include::_attributes/common-attributes.adoc[]
:context: windows-containers-support

toc::[]


// wording taken and modified from https://access.redhat.com/support/policy/updates/openshift#windows

Windows Container Support for Red{nbsp}Hat OpenShift is provided and available as an optional, installable component. Windows Container Support for Red{nbsp}Hat OpenShift is not part of the {product-title} subscription. It requires an additional Red{nbsp}Hat subscription and is supported according to the link:https://access.redhat.com/support/offerings/production/soc/[Scope of coverage] and link:https://access.redhat.com/support/offerings/production/sla[Service level agreements].

You must have this separate subscription to receive support for Windows Container Support for Red{nbsp}Hat OpenShift. Without this additional Red{nbsp}Hat subscription, deploying Windows container workloads in production clusters is not supported. You can request support through the link:http://access.redhat.com/[Red{nbsp}Hat Customer Portal].

For more information, see the Red{nbsp}Hat {product-title} Life Cycle Policy document for link:https://access.redhat.com/support/policy/updates/openshift#windows[{productwinc}].

If you do not have this additional Red{nbsp}Hat subscription, you can use the Community Windows Machine Config Operator, a distribution that lacks official support.
