[id="windows-containers-release-notes-2-x"]
= Windows Container Support for Red Hat OpenShift release notes
include::modules/common-attributes.adoc[]
:context: windows-containers-release-notes

toc::[]

[id="about-windows-containers"]
== About Windows Container Support for Red Hat OpenShift

Windows Container Support for Red Hat OpenShift is a feature providing the ability to run Windows compute nodes in an {product-title} cluster. This is possible by using the Red Hat Windows Machine Config Operator (WMCO) to install and manage Windows nodes. With Windows nodes available, you can run Windows container workloads in {product-title}.

The release notes for Red Hat OpenShift for Windows Containers tracks the development of the WMCO, which provides all Windows container workload capabilities in {product-title}.

[id="getting-support"]
== Getting support

You must have a subscription to receive support for the Red Hat WMCO. Deploying Windows container workloads in production clusters is not supported without a subscription. If you do not have a subscription, you can use the community WMCO, a distribution that lacks official support. Request support through the link:http://access.redhat.com/[Red Hat Customer Portal].

[id="wmco-2-0-0"]
== Release notes for Red Hat Windows Machine Config Operator 2.0.0

This release of the WMCO provides bug fixes and enhancements for running Windows compute nodes in an {product-title} cluster. The components of the WMCO 2.0.0 were released in link:https://access.redhat.com/errata/RHBA-2021:0440[RHBA-2021:0440].

WMCO supports self-managed clusters built using installer-provisioned infrastructure running on the following cloud providers:

* Amazon Web Services (AWS)
* Microsoft Azure
* VMware vSphere

The following Windows Server operating systems are supported in this release of the WMCO, depending on which platform your cluster is installed on:

[cols="1,4",options="header"]
|===

|WMCO platform
|Windows Server version

|AWS
|Windows Server Long-Term Servicing Channel (LTSC): Windows Server 2019

|Azure
|Windows Server Long-Term Servicing Channel (LTSC): Windows Server 2019

|vSphere
|Windows Server Semi-Annual Channel (SAC): Windows Server 2004 with link:https://support.microsoft.com/en-us/topic/august-11-2020-kb4566782-os-build-19041-450-ec5cf4b6-86ed-b0d3-539c-5fbe1b17f56a[Microsoft patch KB4566782]

|===

[IMPORTANT]
====
Running Windows container workloads is not supported for clusters in a restricted network or disconnected environment.
====

Version 2.x of the WMCO is only compatible with {product-title} 4.7.

[id="wmco-2-0-0-improvements"]
=== New features and improvements

This release adds the following new features and improvements.

[id="wmco-2-0-0-vsphere-support"]
==== Support for clusters running on VMware vSphere

You can now run Windows nodes on a cluster installed on VMware vSphere version 6.5, 6.7, or 7.0. You can create a Windows `MachineSet` object on vSphere to host Windows Server compute nodes. For more information, see xref:../windows_containers/creating_windows_machinesets/creating-windows-machineset-vsphere.adoc#creating-windows-machineset-vsphere[Creating a Windows `MachineSet` object on vSphere].

[id="wmco-2-0-0-monitoring"]
==== Enhanced Windows node monitoring

Windows nodes are now fully integrated with most of the monitoring capabilities provided by the web console. However, it is not possible to view workload graphs for pods running on Windows nodes in this release.

[id="wmco-2-0-0-known-issues"]
=== Known issues

* The filesystem graphs available in the web console do not display for Windows nodes. This is caused by changes in the filesystem queries. This will be fixed in a future release of WMCO. (link:https://bugzilla.redhat.com/show_bug.cgi?id=1930347[*BZ#1930347*])

* The Prometheus windows_exporter used by the WMCO currently collects metrics through HTTP, so it is considered unsafe. You must ensure that only trusted users can retrieve metrics from the endpoint. The windows_exporter feature recently added support for HTTPS configuration, but this configuration has not been implemented for WMCO. Support for HTTPS configuration in the WMCO will be added in a future release.

* The kube-proxy service terminates unexpectedly after the load balancer is created if you create the load balancer after the Windows pods begin running. To avoid this issue, you must create the load balancer before the Windows pods status transitions to `Running`. (link:https://bugzilla.redhat.com/show_bug.cgi?id=1939968[*BZ#1939968*])
