:_mod-docs-content-type: ASSEMBLY
include::_attributes/common-attributes.adoc[]
[id="monitoring-release-notes"]
= {product-title} release notes
:context: monitoring-release-notes

toc::[]

[role="_abstract"]
The {ocp} release notes for the monitoring stack contain information about new features and enhancements, Technology Previews, deprecated and removed features, known issues, and fixed issues.

For details about other changes in the {ocp} release, see the link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html-single/release_notes/index#ocp-4-19-release-notes[{ocp} {product-version} release notes].

//Support version matrix for monitoring components
include::modules/monitoring-support-version-matrix-for-monitoring-components.adoc[leveloffset=+1]

//{ocp} {product-version} monitoring release notes
include::modules/monitoring-4-20-release-notes.adoc[leveloffset=+1]

[id="monitoring-asynchronous-errata-updates_{context}"]
== Asynchronous errata updates

Security, fixed issues, and enhancement updates for {ocp} {product-version} are released as asynchronous errata through the Red{nbsp}Hat Network. This includes updates for the monitoring stack and other components.

For more information about monitoring updates, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/release_notes/ocp-4-19-release-notes#ocp-4-19-asynchronous-errata-updates_release-notes[Asynchronous errata updates].
