[id="virt-creating-data-volumes"]
= Creating data volumes
include::modules/virt-document-attributes.adoc[]
:context: virt-creating-data-volumes

toc::[]

When you create a data volume, the Containerized Data Importer (CDI) creates a persistent volume claim (PVC) and populates the PVC with your data. You can create a data volume as either a standalone resource or by using a `dataVolumeTemplate` resource in a virtual machine specification. You create a data volume by using either the PVC API or storage APIs.

[IMPORTANT]
====
When using {VirtProductName} with {product-title} Container Storage, specify RBD block mode persistent volume claims (PVCs) when creating virtual machine disks. With virtual machine disks, RBD block mode volumes are more efficient and provide better performance than Ceph FS or RBD filesystem-mode PVCs.

To specify RBD block mode PVCs, use the 'ocs-storagecluster-ceph-rbd' storage class and `VolumeMode: Block`.
====

[TIP]
====
Whenever possible, use the storage API to optimize space allocation and maximize performance.
====

A _storage profile_ is a custom resource that the CDI manages. It provides recommended storage settings based on the associated storage class. A storage profile is allocated for each storage class.

Storage profiles enable you to create data volumes quickly while reducing coding and minimizing potential errors.

For recognized storage types, the CDI provides values that optimize the creation of PVCs.  However, you can configure automatic settings for a storage class if you customize the storage profile.

include::modules/virt-creating-data-volumes-using-storage-api.adoc[leveloffset=+1]

include::modules/virt-creating-data-volumes-using-pvc-api.adoc[leveloffset=+1]

include::modules/virt-customizing-storage-profile.adoc[leveloffset=+1]

[id="additional-resources_creating-data-volumes-using-profiles"]
== Additional resources
* xref:../../../virt/virtual_machines/virtual_disks/virt-configuring-local-storage-for-vms.adoc#virt-creating-storage-class_virt-configuring-local-storage-for-vms[Creating a storage class]

* xref:../../../virt/virtual_machines/virtual_disks/virt-reserving-pvc-space-fs-overhead.adoc#virt-overriding-default-fs-overhead-value_virt-reserving-pvc-space-fs-overhead[Overriding the default file system overhead value]

* xref:../../../virt/virtual_machines/virtual_disks/virt-cloning-a-datavolume-using-smart-cloning.adoc#virt-cloning-a-datavolume-using-smart-cloning[Cloning a data volume using smart cloning]
