:_mod-docs-content-type: ASSEMBLY
[id="ibi-factory-image-based-install"]
= About image-based installation for {sno}
include::_attributes/common-attributes.adoc[]
:context: ibi-factory-image-based-install

toc::[]

Use the `openshift-install` program to create a live installation ISO for preinstalling {sno} on bare-metal hosts. For more information about downloading the installation program, see "Installation process" in the "Additional resources" section.

The installation program takes a seed image URL and other inputs, such as the release version of the seed image and the disk to use for the installation process, and creates a live installation ISO. You can then start the host using the live installation ISO to begin preinstallation. When preinstallation is complete, the host is ready to ship to a remote site for the final site-specific configuration and deployment.

The following are the high-level steps to preinstall a {sno} cluster using an image-based installation:

* Generate a seed image.
* Create a live installation ISO using the `openshift-install` installation program.
* Boot the host using the live installation ISO to preinstall the host.

[role="_additional-resources"]
.Additional resources

* xref:../../installing/overview/index.adoc#installation-process_ocp-installation-overview[Installation process]

include::modules/ibi-create-iso-for-bmh.adoc[leveloffset=+1]

include::modules/ibi-provision-install-iso-to-bmh.adoc[leveloffset=+1]

include::modules/ibi-installer-installation-config.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* xref:../../edge_computing/image_base_install/ibi-preparing-for-image-based-install.adoc#cnf-image-based-upgrade-shared-container-partition_ibi-preparing-image-based-install[Configuring a shared container partition between ostree stateroots]
