[id="installing-rhv-creating-custom-vm"]
= Creating a custom virtual machine template on RHV
include::modules/common-attributes.adoc[]
:context: installing-rhv-creating-custom-vm

toc::[]

Before installing a {product-title} cluster on your {rh-virtualization-first} environment, you create a custom virtual machine template and configure your environment so the installation program uses the template.

[IMPORTANT]
====
Creating a custom virtual machine template for {rh-virtualization} is a workaround for a known issue (link:https://bugzilla.redhat.com/show_bug.cgi?id=1818577[*BZ#1818577*]). If you do not create a custom virtual machine, the {product-title} cluster you install will fail.
====

.Prerequisites
* Review details about the
xref:../../architecture/architecture-installation.adoc#architecture-installation[{product-title} installation and update]
processes.
* If you use a firewall,
xref:../../installing/install_config/configuring-firewall.adoc#configuring-firewall[configure it to allow the sites] that your cluster requires access to.

include::modules/installing-rhv-downloading-rhcos-image.adoc[leveloffset=+1]

include::modules/installing-rhv-using-ansible-playbook.adoc[leveloffset=+1]

== Determining the resources available to customize your virtual machine template

If you plan to xref:../../installing/installing_rhv/installing-rhv-default.html#installing-rhv-default[install a cluster quickly on {rh-virtualization} using the default configuration options], skip to the next task, xref:installing-rhv-attaching-virt-disk-to-vm_installing-rhv-creating-custom-vm[Attaching the virtual disk with the RHCOS image to the virtual machine].

Otherwise, if you plan to xref:../../installing/installing_rhv/installing-rhv-customizations.html#installing-rhv-customizations[install a cluster on {rh-virtualization} with customizations], consider the following information.

You can customize the virtual machine template the installation program uses to create the control and compute machines in your {product-title} cluster. You can customize the template so these machines have more than the default virtual CPU, memory, and storage resources. Your customizations apply equally to both control and compute machines; they cannot be customized differently.

Over-allocating resources can cause the installation or operation of your cluster to fail. To avoid over-allocating resources, you must determine how much of each resource is available for each virtual machine: Inspect the resources in your {rh-virtualization-first} cluster and divide them by the number of virtual machines. The resulting quotients are the maximum values you can allocate for each resource.

.Procedure

. Inspect the available resources in your {rh-virtualization} cluster.
.. Go to xref:../../installing/installing_rhv/installing-rhv-default.html#installing-rhv-verifying-the-rhv-environment_installing-rhv-default[Verifying the requirements for the {rh-virtualization} environment]
.. Record the values of the storage *Free Space*, *Logical CPU Cores*, and *Max free Memory for scheduling new VMs*.
. Record the number of virtual machines in your {product-title} cluster.
** By default, your cluster contains seven machines.
** You can also customize the number of machines, as described in xref:../../installing/installing_rhv/installing-rhv-customizations.html#installing-rhv-installation-configuration-parameters_installing-rhv-customizations[Installation configuration parameters for {rh-virtualization}]. To account for the bootstrap machine, add one machine to the number in the configuration file.
. Divide each resource by the number of virtual machines.
. Record these values for use later on.

include::modules/installing-rhv-attaching-virt-disk-to-vm.adoc[leveloffset=+1]

include::modules/installing-rhv-configuring-and-creating-the-vm.adoc[leveloffset=+1]

include::modules/installing-rhv-creating-vm-template.adoc[leveloffset=+1]

include::modules/installing-rhv-export-some-environment-variables.adoc[leveloffset=+1]
