[id="installing-rhv-installer-custom"]
= Installing a cluster on {rh-virtualization} with customizations
include::modules/common-attributes.adoc[]
:context: installing-rhv-installer-custom

toc::[]

In {product-title} version {product-version}, you can customize and install a
cluster on {rh-virtualization-first}.

To customize the cluster, you perform the following steps:

. Create an installation configuration file, `install-config.yaml`, by running the installer and answering its prompts.
. Inspect and modify parameters in `install-config.yaml`.
. Make a working copy of `install-config.yaml`.
. Run the installer with a copy of `install-config.yaml` (no prompts).
+
Then, the installer creates the {product-title} cluster using “installer-provisioned infrastructure.”

This installer is available for Linux and macOS only.

To learn more, see
xref:../../architecture/architecture-installation.adoc#architecture-installation[this overview of the installation and update processes].

NOTE: Replace all example values with real ones.

.Prerequisites

You have xref:../../installing/installing_rhv/installing-rhv-preparing-to-install.adoc[prepared the RHV environment and network].

.Procedure

include::modules/installing-rhv-create-install-config-file.adoc[leveloffset=+1]
include::modules/installing-rhv-responding-to-installer-prompts.adoc[leveloffset=+1]
include::modules/installing-rhv-inspect-and-modify-params-in-install-config.adoc[leveloffset=+1]
include::modules/installing-rhv-customizing-the-virtual-machine-template.adoc[leveloffset=+1]
include::modules/installing-rhv-copying-install-config-and-running-installer.adoc[leveloffset=+1]

NOTE: At this point, the installer begins creating the cluster.

include::modules/installing-rhv-accessing-the-ocp-web-console.adoc[leveloffset=+1]

NOTE: You have finished installing a custom {product-title} cluster on {rh-virtualization}.

include::modules/installing-rhv-post-installation-tasks.adoc[leveloffset=+1]

.Troubleshooting
If the installation fails, the installer times out and displays an error message. To learn more, see xref:../../installing-rhv-troubleshooting.adoc[Troubleshooting Installation Problems].
