name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1.3.0
      working-directory: .github
      with:

        # Optional
        config: .vale.ini

        # Optional
        files: modules
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
