name: Build and deploy preview

on:
  push:
    paths:
      - 'maps/**'
      - 'assemblies/**'
      - 'modules/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install asciidoctor
        run: sudo gem install asciidoctor
      - name: Build HTML
        run: |
          asciidoctor maps/navigation.adoc \
            -D _site \
            -a toc=left \
            -a doctype=book \
            -a docinfo=shared-footer
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
