[[using-images-s2i-images-nodejs]]
= Node.js
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:

toc::[]

== Overview
OpenShift provides
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#source-build[S2I]
enabled Node.js images for building and running Node.js applications.
ifndef::openshift-enterprise[]
The https://github.com/openshift/sti-nodejs[Node.js S2I builder image]
endif::openshift-enterprise[]
ifdef::openshift-enterprise[]
The Node.js S2I builder image
endif::openshift-enterprise[]
assembles your application source with any required dependencies to create a
new image containing your Node.js application. This resulting image can be run
either by OpenShift or by Docker.

== Versions
Currently, {product-title} provides versions
https://github.com/openshift/sti-nodejs/tree/master/0.10[0.10] and
https://github.com/openshift/sti-nodejs[4] of Node.js.

== Images

ifdef::openshift-online[]
RHEL 7 images are available through the Red Hat Registry:

----
$ docker pull registry.access.redhat.com/openshift3/nodejs-010-rhel7
$ docker pull registry.access.redhat.com/rhscl/nodejs-4-rhel7
----

You can use these images through the `nodejs` image stream.
endif::openshift-online[]

ifndef::openshift-online[]
These images come in two flavors, depending on your needs:

* RHEL 7
* CentOS 7

*RHEL 7 Based Images*

The RHEL 7 images are available through the Red Hat Registry:

----
$ docker pull registry.access.redhat.com/openshift3/nodejs-010-rhel7
$ docker pull registry.access.redhat.com/rhscl/nodejs-4-rhel7
----

*CentOS 7 Based Image*

This image is available on Docker Hub:

----
$ docker pull openshift/nodejs-010-centos7
----

To use these images, you can either access them directly from these
xref:../../architecture/infrastructure_components/image_registry.adoc#architecture-infrastructure-components-image-registry[image
registries], or push them into your
xref:../../architecture/infrastructure_components/image_registry.adoc#integrated-openshift-registry[OpenShift Docker
registry]. Additionally, you can create an
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#image-streams[image
stream] that points to the image, either in your Docker registry or at the
external location. Your OpenShift resources can then reference the ImageStream.
You can find
https://github.com/openshift/origin/tree/master/examples/image-streams[example
image stream definitions] for all the provided {product-title} images.
endif::openshift-online[]

[[nodejs-configuration]]
== Configuration
The Node.js image supports a number of environment variables, which can be set
to control the configuration and behavior of the Node.js runtime.

To set these environment variables as part of your image, you can place them into
xref:../../dev_guide/builds/build_strategies.adoc#environment-files[a *_.s2i/environment_* file]
inside your source code repository, or define them in
xref:../../dev_guide/builds/build_strategies.adoc#buildconfig-environment[the environment
section] of the build configuration's `*sourceStrategy*` definition.

You can also set environment variables to be used with an existing image when
xref:../../dev_guide/application_lifecycle/new_app.adoc#specifying-environment-variables[creating new
applications], or by
xref:../../dev_guide/environment_variables.adoc#set-environment-variables[updating
environment variables for existing objects] such as deployment configurations.

[NOTE]
====
Environment variables that control build behavior must be set as part of the s2i build
configuration or in the *_.s2i/environment_* file to make them available to the build
steps.
====

.Development Mode Environment Variables
[cols="3a,6a",options="header"]
|===

| Variable name | Description

|`*DEV_MODE*`
|When set to `true`, enables hot deploy and opens the debug port. Additionally, indicates to tooling that the image is in development mode.  Default is `false`.

|`*DEBUG_PORT*`
|The debug port. Only valid if `*DEV_MODE*` is set to true. Default is 5858.

|`*NPM_MIRROR*`
|The custom NPM registry mirror URL. All NPM packages will be downloaded from the mirror link during the build process.

|===

[[nodejs-hot-deploying]]
== Hot Deploying

Hot deployment allows you to quickly make and deploy changes to your application
without having to generate a new S2I build. In order to immediately pick up
changes made in your application source code, you must run your built image with
the `*DEV_MODE=true*` environment variable.

You can set new environment variables when
xref:../../dev_guide/application_lifecycle/new_app.adoc#specifying-environment-variables[creating new
applications], or
xref:../../dev_guide/environment_variables.adoc#set-environment-variables[updating
environment variables for existing objects].

[WARNING]
====
Only use the `*DEV_MODE=true*` environment variable while developing or
debugging. Using this in your production environment is not recommended.
====

To change the source code of a running pod,
xref:../../cli_reference/basic_cli_operations.adoc#troubleshooting-and-debugging-cli-operations[open
a remote shell into the container]:

----
$ oc rsh <pod_id>
----

Entering into a running container changes your current directory to
*_/opt/app-root/src_*, where the source code is located.

ifdef::openshift-online[]
[[nodejs-templates]]
== Node.js Templates

{product-title} includes an example template to deploy a
link:https://github.com/openshift/nodejs-ex[sample Node.js application].
This template builds and deploys the sample application on Node.js with a
MongoDB database using a persistent volume for storage.

The sample application can be built and deployed using the
`rhscl/nodejs-4-rhel7` image with the following command:

----
$ oc new-app --template=nodejs-mongo-persistent
----
endif::openshift-online[]
