= Perl
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:

toc::[]

== Overview
OpenShift provides
link:../../architecture/core_concepts/builds_and_image_streams.html#source-build[S2I]
enabled Perl images for building and running Perl applications.
ifdef::openshift-origin[]
The https://github.com/openshift/sti-perl[Perl S2I builder image]
endif::openshift-origin[]
ifdef::openshift-enterprise[]
The Perl S2I builder image
endif::openshift-enterprise[]
assembles your application source with any required dependencies to create a
new image containing your Perl application. This resulting image can be run
either by OpenShift or by Docker.

== Versions
Currently, OpenShift supports version
https://github.com/openshift/sti-perl/tree/master/5.16[5.16] of Perl.

== Images

This image comes in two flavors, depending on your needs:

* RHEL 7
* CentOS 7

*RHEL 7 Based Image*

The RHEL 7 image is available through Red Hat's subscription registry using:

----
$ docker pull registry.access.redhat.com/openshift3/perl-516-rhel7
----

*CentOS 7 Based Image*

This image is available on DockerHub. To download it:

----
$ docker pull openshift/perl-516-centos7
----

To use these images, you can either access them directly from these
link:../../architecture/infrastructure_components/image_registry.html[image
registries], or push them into your
link:../../install_config/install/docker_registry.html[OpenShift Docker
registry]. Additionally, you can create an
link:../../architecture/core_concepts/builds_and_image_streams.html#image-streams[image
stream] that points to the image, either in your Docker registry or at the
external location. Your OpenShift resources can then reference the ImageStream.
You can find
https://github.com/openshift/origin/tree/master/examples/image-streams[example
image stream definitions] for all the provided OpenShift images.

== Configuration
The Perl image supports a number of environment variables which can be set to
control the configuration and behavior of the Perl runtime.

To set these environment variables, you can place them into
link:../../dev_guide/builds.html#environment-files[a *_.sti/environment_* file]
inside your source code repository, or define them in
link:../../dev_guide/builds.html#buildconfig-environment[the environment
section] of the build configuration's `*sourceStrategy*` definition.

.Perl Environment Variables
[cols="4a,6a",options="header"]
|===

|Variable name |Description

|`*ENABLE_CPAN_TEST*`
|This variable installs all the cpan modules and runs their tests. By default,
the testing of the modules is turned off.

|`*CPAN_MIRROR*`
|This variable specifies a mirror URL which
cpanminus uses to install dependencies. By default, this URL is not specified.

a|`*PERL_APACHE2_RELOAD*`
|Set this to *true* to enable automatic reloading of modified Perl modules. By
default, automatic reloading is turned off.

[WARNING]
====
You should only use this option while developing or debugging; it is not
recommended to turn this on in your production environment.
====
|===

[[perl-hot-deploy]]

== Hot Deploying
Hot deployment allows you to quickly make and deploy changes to your application
without having to generate a new S2I build. To enable hot deployment in this
image, you must set the `*PERL_APACHE2_RELOAD*` environment variable to *true*.
You can use
link:../../dev_guide/environment_variables.html#set-environment-variables[the
`oc env` command] to update environment variables of existing objects.

[WARNING]
====
You should only use this option while developing or debugging; it is not
recommended to turn this on in your production environment.
====

To change your source code in a running pod, use
link:../../cli_reference/basic_cli_operations.html#troubleshooting-and-debugging-cli-operations[the
`oc rsh` command] to enter the container:

----
$ oc rsh <pod_id>
----

After you enter into the running container, your current directory is set to
*_/opt/app-root/src_*, where the source code is located.
